FCLib: tools/skeleton/build_ensemble.c File Reference
tools/skeleton/build_ensemble.c File Reference
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <assert.h>
#include <stdlib.h>
#include <fc.h>
#include "lib_skeleton.h"
Data Structures
struct default_t
Functions
static void dumpHelp (void)
static int getIndexAndTruncateName (char *name)
static void checkArgs (int argc, char **argv, FC_VerbosityLevel *verbose_level, char **file_name_i, char **file_name_o, char **mesh_name, char **disp_name, int *step1, int *num_trees, whittleAlgorithm_t *whittle_type, int *percent)
static FC_ReturnCode getMeshByNameOrDie (FC_Dataset ds, char *mesh_name, FC_Mesh *m)
void * mallocOrDie (size_t s)
int main (int argc, char **argv)
Variables
default_t defaults []
Function Documentation
static void checkArgs (int argc, char ** argv, FC_VerbosityLevel * verbose_level, char ** file_name_i, char ** file_name_o, char ** mesh_name, char ** disp_name, int * step1, int * num_trees, whittleAlgorithm_t * whittle_type, int * percent) [static]
Definition at line 122 of file build_ensemble.c.
References convertStringToWhittleAlg(), default_t::displacement, dumpHelp(), FC_LOG_MESSAGES, FC_WA_UNKNOWN, FC_WARNING_MESSAGES, default_t::file, getIndexAndTruncateName(), and info.
{
  int ich;
  int i,id;
  if(argc<2) dumpHelp();
  *file_name_i = *file_name_o = *mesh_name = *disp_name = NULL;
  *whittle_type = FC_WA_UNKNOWN;
  *percent = 50;
  *step1 = -1; //Initial location
  *num_trees = 1;
  while( (ich = getopt(argc, argv, "i:o:m:d:p:w:n:I:vVh")) != EOF){
    switch(ich){
    case 'i':  *file_name_i   = strdup(optarg); break;
    case 'o':  *file_name_o   = strdup(optarg); break;
    case 'm':  *mesh_name     = strdup(optarg); break;
    case 'd':  *disp_name     = strdup(optarg); break;
    case 'p':  *percent       = atoi(optarg);   break;
    case 'w':  *whittle_type  = convertStringToWhittleAlg(optarg); break;
    case 'n':  *num_trees     = atoi(optarg); break;
    case 'v':  *verbose_level = FC_WARNING_MESSAGES; break;
    case 'V':  *verbose_level = FC_LOG_MESSAGES;     break;
    case 'I':
      id = atoi(optarg);
      for(i=0; (i<id) && (defaults[i].file); i++);
      if((id<0)||(!defaults[i].file)){
     printf("Default id (%d) out of range?\n", id);
     dumpHelp();
     exit(0);
      }
      *file_name_i         = strdup(defaults[i].file);
      *mesh_name         = strdup(defaults[i].mesh);
      *disp_name = (defaults[i].displacement) ? defaults[i].displacement : NULL;
      printf("Running with default %d: %s\n", i, defaults[i].info);
      break;
    case 'h':
    default:
      dumpHelp(); break;
    }
  }
  //Grab the input filename or die
  if(optind<argc)
    *file_name_i = strdup(argv[optind++]);
  if(*num_trees<1){
    printf("Need to make at least one tree");
    dumpHelp();
  }
  if((!*file_name_i)||(!*mesh_name)){
    printf("Error: not all required input fields defined\n");
    dumpHelp();
  }
  //See if there's a timestep index in mesh names (ie, block_1[3])
  *step1 = getIndexAndTruncateName(*mesh_name);
  //Assign the default displacement name
  if((*step1>=0)&&(!*disp_name)) *disp_name = strdup("displacement");
  return;
}
static void dumpHelp (void) [static]
Definition at line 78 of file build_ensemble.c.
References default_t::file, getNextWhittleAlgorithmDescription(), and info.
{
  int i, rc;
  char *name, *sname, *description;
  int id;
  printf("Build Ensemble: a tool for generating a dataset that contains multiple tree representations of\n"
         "  the input mesh.\n"
      "\n"
      "Usage: build_ensemble [options]\n"
         "  -n number_trees                 How many unique trees to generate\n"
         "  -w whittle_type                 Whittle algorithm to use\n");
  for(i=0; (rc=getNextWhittleAlgorithmDescription(i,&name, &sname, &id, &description)); i++){
    printf("        %s : %23s - %s\n", sname, name, description);
  }
  printf("\n"
      "  -p whittle_percent              percentage of tree to leave behind (1-99)\n"
         "  -m mesh_name[step]              (can be appended with displacement step, like block_1[2])\n"
         "  -d displacement_variable_name   (does combinding on _x,_y,_z and defaults to 'displacement')\n"
         "  -v                              (display warning messages)\n"
         "  -V                              (display log messages)\n"
         "  -h                              (this help screen)\n"
         "  -I ##                           Use the following built-in input files:\n");
  for(i=0; defaults[i].file; i++)
    printf("     %d : %s\n", i, defaults[i].info);
  exit(0);
}
static int getIndexAndTruncateName (char * name) [static]
Definition at line 108 of file build_ensemble.c.
Referenced by checkArgs().
{
  char *c;
  c=name;
  while(*c!='\0') {
    if(*c=='['){
      *c='\0';
      c++;
      return atoi(c);
    }
    c++;
  }
  return -1; //No index, assume initial geometry
}
static FC_ReturnCode getMeshByNameOrDie (FC_Dataset ds, char * mesh_name, FC_Mesh * m) [static]
Definition at line 208 of file build_ensemble.c.
References emsg, fc_exitIfError, fc_getMeshByName(), FC_SUCCESS, and FREE.
Referenced by main().
{
  FC_ReturnCode rc;
  FC_Mesh *meshes;
  int numMeshes;
  rc = fc_getMeshByName(ds, mesh_name, &numMeshes, &meshes);
  fc_exitIfError(rc);
  if(numMeshes!=1)
    emsg("Found %d meshes named %s", numMeshes, mesh_name);
  *m = meshes[0];
  FREE(meshes);
  return FC_SUCCESS;
}
int main (int argc, char ** argv)
Definition at line 236 of file build_ensemble.c.
References checkArgs(), convertWhittleAlgToString(), emsg, fc_convertTreeToMesh(), fc_createDataset(), fc_exitIfError, FC_FT_EXODUS, fc_getMeshNumElement(), fc_initLibrary(), fc_loadDataset(), fc_makeSpanningTree(), fc_setLibraryVerbosity(), FC_WA_MIN_ANGLE_CHANGE, FC_WA_MIN_DESCENDANTS, FC_WA_MIN_SEGMENT_LENGTHS, FC_WA_OCTANTS, FC_WA_UNKNOWN, FC_WARNING_MESSAGES, fc_writeDataset(), FREE, getMeshByNameOrDie(), getWhittleAlgorithmName(), info, mallocOrDie(), spanning_tree_t::nodes, verbose_level, and whittleSkeleton().
{
  FC_ReturnCode rc;
  FC_VerbosityLevel verbose_level = FC_WARNING_MESSAGES;
  char *file_name_i, *file_name_o;
  char *mesh_name, *disp_name;
  whittleAlgorithm_t wa=FC_WA_UNKNOWN;
  double wa_fraction;
  whittleAlgorithm_t *whittle_algs;
  double *whittle_fracs;
  int same_center=0;
  int same_whittle_alg=1;
  int same_whittle_frac=0;
  FC_Dataset ds1;
  FC_Dataset ds_skel;
  FC_Mesh    m1;
  int        step1;
  spanning_tree_t *tree1=NULL, *tree2=NULL;
  int *centers;
  char *mname;
  int num_trees=1;
  int num_elem;
  int percent;
  int i,j;
  //Look at args user gave us
  checkArgs(argc, argv,
         &verbose_level,
         &file_name_i, &file_name_o,
         &mesh_name, &disp_name, &step1,
         &num_trees,
         &wa, &percent);
 //Pass back info to user
  info("build_ensemble is running with args\n"
       "\tInput File   = '%s'\n"
       "\tOutput File  = '%s'\n"
       "\tMesh Name    = '%s'\n"
       "\tDisplacement = '%s'\n"
       "\tAlgorithm    = '%s'\n"
       "\tPercent      =  %d%%'",
       file_name_i,
       file_name_o,
       mesh_name,
       disp_name,
       getWhittleAlgorithmName(wa),
       percent);
  wa_fraction = ((double)percent)/100.0;
  rc = fc_setLibraryVerbosity(verbose_level);         fc_exitIfError(rc);
  rc = fc_initLibrary();                              fc_exitIfError(rc);
  //Load the first mesh
  rc = fc_loadDataset(file_name_i, &ds1);             fc_exitIfError(rc);
  rc = getMeshByNameOrDie(ds1, mesh_name, &m1);      fc_exitIfError(rc);
  rc = fc_getMeshNumElement(m1, &num_elem);           fc_exitIfError(rc);
  printf("%d\n",num_trees);
  if(num_elem<num_trees) num_trees=num_elem; //Limit
  printf("Making %d spanning trees\n",num_trees);
  rc = fc_createDataset("skelozos", &ds_skel);        fc_exitIfError(rc);
  mname = (char *)mallocOrDie( (strlen("tree_")+5) * 2);
  centers = (int *)mallocOrDie(num_trees*sizeof(int));
  whittle_algs   = (whittleAlgorithm_t *)mallocOrDie(num_trees*sizeof(whittleAlgorithm_t));
  whittle_fracs  = (double *)mallocOrDie(num_trees*sizeof(double));
  //Figure out where centers should be
  if(same_center){
    //All have same center
    centers[0] = (int) ((double)(num_elem-1)) * (rand()/(RAND_MAX+1.0));
    for(i=1; i<num_trees-1; i++)
      centers[i] = centers[0];
  } else {
    //Different center for each node
    for(i=0; i<num_trees; i++){
      //Generate a new random center until we get a unique val
      do{
     centers[i] = (int) ((double)(num_elem-1)) * (rand()/(RAND_MAX+1.0));
     for(j=0; (j<i) && (centers[i]!=centers[j]) ; j++);
      } while (j<i);
    }
  }
  //Figure out which algorithm to use on each tree
  if(same_whittle_alg){
    for(i=0; i<num_trees; i++)
      whittle_algs[i] = wa;
  } else {
    for(i=0; i<num_trees; i++){
      switch(i%4){
      case 0: whittle_algs[i] = FC_WA_OCTANTS; break;
      case 1: whittle_algs[i] = FC_WA_MIN_DESCENDANTS; break;
      case 2: whittle_algs[i] = FC_WA_MIN_SEGMENT_LENGTHS; break;
      case 3: whittle_algs[i] = FC_WA_MIN_ANGLE_CHANGE; break;
      default:
     emsg("Bad case?");
      }
    }
  }
  //Figure out percentage we should use
  if(same_whittle_frac){
    for(i=0; i<num_trees; i++)
      whittle_fracs[i] = wa_fraction;
  } else {
    for(i=0; i<num_trees; i++)
      whittle_fracs[i] = 0.9 - (0.8/(double)num_trees)*((double)i);
  }
  for(i=0; i<num_trees; i++){
    //Build new tree
    printf("Building (%d/%d): center=%d Whittle=%.2lf WA=%s\n",
        i, num_trees, centers[i], whittle_fracs[i], convertWhittleAlgToString(whittle_algs[i]));
    rc = fc_makeSpanningTree(m1, centers[i], &tree1); fc_exitIfError(rc);
    if(whittle_algs[i]!=FC_WA_UNKNOWN){
      rc = whittleSkeleton(tree1, whittle_algs[i], whittle_fracs[i], &tree2); fc_exitIfError(rc);
      FREE(tree1->nodes);
      FREE(tree1);
      tree1 = tree2;
      tree2 = NULL;
    }
    sprintf(mname, "tree_%.4d", centers[i]);
    printf("Writing mesh '%s'\n", mname);
    rc = fc_convertTreeToMesh(ds_skel, *tree1, mname, disp_name , NULL);
  }
  printf("Trying to write\n");
  rc = fc_writeDataset(ds_skel, file_name_o, FC_FT_EXODUS);
  fc_exitIfError(rc);
  printf("Done\n");
  FREE(whittle_fracs);
  FREE(whittle_algs);
  FREE(centers);
  return 0;
}
void * mallocOrDie (size_t s)
Definition at line 227 of file build_ensemble.c.
References emsg.
Referenced by main().
{
  void *x;
  x = (void *)malloc(s);
  if(!x)
    emsg("Couldn't malloc");
  return x;
}
Variable Documentation
default_t defaults[]
Initial value:
 {
  { "/datasets/fe/plates/3plates.e",               "block_2",        NULL,           "3 Plates"},
  { "/datasets/fe/table40_sqmesh_simple.e",        "block_2",        "displacement", "Table Sq Mesh, w/ displacement"},
  { "/datasets/fe/plates/4plates.e",               "scaled_1",       NULL,           "4 Plates Scaled"},
  { "/datasets/fe/oldcans/080414_run1.ex2",        "block_2",        "displacement", "Old can"},
  { "/datasets/fe/ballsmash1.e",                   "Material_ID_3",  NULL,           "Ballsmash"},
  { "/datasets/fe/ballsmash1.e",                   "Material_ID_3",  "displacement", "Ballsmash w/ displacement"},
  { "/datasets/fe/wobble_c.e",                     "part_1",         NULL,           "Wobble"},
  { "/datasets/fe/wobble_c.e",                     "part_1",         "displacement", "Wobble w/ displacement"},
  { "/datasets/fe/helium_1.50_2.11.e",             "block_1",        NULL,           "Helium"},
  { "/datasets/fe/bookshelf/bookshelf_hole_a.e",   "block_15",       NULL,           "Bookshelf: hole at A"},
  { "/datasets/fe/bookshelf/bookshelf_hole_cba.e", "block_19",       NULL,           "Bookshelf: hole at A,B,C"},
  { NULL, NULL, NULL, NULL}
}
Definition at line 59 of file build_ensemble.c.