FCLib: tools/skeleton/generate_tree.c File Reference
tools/skeleton/generate_tree.c File Reference
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <assert.h>
#include <fc.h>
#include "lib_skeleton.h"
Data Structures
struct default_t
Functions
static void dumpHelp (void)
static int getIndexAndTruncateName (char *name)
static void checkArgs (int argc, char **argv, FC_VerbosityLevel *verbose_level, char **file_in_name, char **file_out_name, char **mesh1_name, char **displacement1_name, int *step1)
static FC_ReturnCode getMeshByNameOrDie (FC_Dataset ds, char *mesh_name, FC_Mesh *m)
int main (int argc, char **argv)
Variables
default_t defaults []
Function Documentation
static void checkArgs (int argc, char ** argv, FC_VerbosityLevel * verbose_level, char ** file_in_name, char ** file_out_name, char ** mesh1_name, char ** displacement1_name, int * step1) [static]
Definition at line 109 of file generate_tree.c.
References _skeleton_dbg, default_t::displacement, dumpHelp(), FC_LOG_MESSAGES, FC_WARNING_MESSAGES, default_t::file, and getIndexAndTruncateName().
{
  int ich, id, i;
  if(argc<2) dumpHelp();
  *file_in_name = *file_out_name = *mesh1_name = *displacement1_name = NULL;
  *step1 = -1; //Initial location
  _skeleton_dbg=1; //Default to printing info
  while( (ich = getopt(argc, argv, "s:d:m:o:d:i:SvVh")) != EOF){
    switch(ich){
    case 'v':                          *verbose_level      = FC_WARNING_MESSAGES; break;
    case 'V':                          *verbose_level      = FC_LOG_MESSAGES;     break;
    case 'S':                          _skeleton_dbg       = 0;                   break;
    case 's':                          *step1              = atoi(optarg);        break;
    case 'd': if(!*displacement1_name) *displacement1_name = strdup(optarg);      break;
    case 'm': if(!*mesh1_name)         *mesh1_name         = strdup(optarg);      break;
    case 'o': if(!*file_out_name)      *file_out_name      = strdup(optarg);      break;
    case 'i': //Use one of the built-in cases
      id = atoi(optarg);
      for(i=0; (i<id) && (defaults[i].file); i++);
      if((id<0)||(!defaults[i].file)){
     printf("Default id (%d) out of range?\n", id);
     dumpHelp();
     exit(0);
      }
      *file_in_name       = strdup(defaults[i].file);
      *mesh1_name         = strdup(defaults[i].mesh);
      *displacement1_name = (defaults[i].displacement) ? defaults[i].displacement : NULL;
      break;
    case 'h':
    default:
      dumpHelp(); break;
    }
  }
  //Grab the input filename or die
  if(optind<argc)
    *file_in_name = strdup(argv[optind++]);
  if(!*file_out_name)
    *file_out_name = strdup("result_tree.e");
  if((!*file_in_name)||(!*mesh1_name)){
    printf("Error: not all required input fields defined\n");
    dumpHelp();
  }
  //See if there's a timestep index in mesh names (ie, block_1[3])
  *step1 = getIndexAndTruncateName(*mesh1_name);
  //Assign the default displacement name
  if((*step1>=0)&&(!*displacement1_name)) *displacement1_name = strdup("displacement");
  return;
}
static void dumpHelp (void) [static]
Definition at line 72 of file generate_tree.c.
References default_t::file, and info.
{
  int i;
  printf("Generate Tree: a simple tool for extracting a tree representation from a mesh\n"
         "  This tool takes an input file, generates a spanning-tree structure for a specified\n"
         "  mesh, and then saves the mesh to a file. This representation may provide a more\n"
         "  convenient way to examine and compare one or more meshes.\n"
         "\n"
      "Usage: generate_tree [options] input_file1\n"
      "  -m mesh_name[step]              (can be appended with displacement step, like block_1[2])\n"
      " [-d displacement_variable_name ] (does combinding on _x,_y,_z and defaults to 'displacement')\n"
      " [-o output_file ]                output file to generate (default=result_tree.e)\n"
      "  -v                              display warning messages\n"
      "  -V                              display log messages\n"
      "  -S                              Silent operation: don't print info\n"
      "  -h                              this help screen\n"
      "  -i ##                           Use the following built-in input files:\n");
  for(i=0; defaults[i].file; i++)
    printf("     %d : %s\n", i, defaults[i].info);
  exit(0);
}
static int getIndexAndTruncateName (char * name) [static]
Definition at line 95 of file generate_tree.c.
{
  char *c;
  c=name;
  while(*c!='\0') {
    if(*c=='['){
      *c='\0';
      c++;
      return atoi(c);
    }
    c++;
  }
  return -1; //No index, assume initial geometry
}
static FC_ReturnCode getMeshByNameOrDie (FC_Dataset ds, char * mesh_name, FC_Mesh * m) [static]
Definition at line 176 of file generate_tree.c.
References emsg, fc_exitIfError, fc_getMeshByName(), FC_SUCCESS, and FREE.
{
  FC_ReturnCode rc;
  FC_Mesh *meshes;
  int numMeshes;
  rc = fc_getMeshByName(ds, mesh_name, &numMeshes, &meshes);
  fc_exitIfError(rc);
  if(numMeshes!=1)
    emsg("Found %d meshes named %s", numMeshes, mesh_name);
  *m = meshes[0];
  FREE(meshes);
  return FC_SUCCESS;
}
int main (int argc, char ** argv)
Definition at line 197 of file generate_tree.c.
References checkArgs(), fc_exitIfError, fc_initLibrary(), fc_loadDataset(), fc_makeSpanningTree(), fc_saveSkeleton(), fc_setLibraryVerbosity(), FC_WARNING_MESSAGES, getMeshByNameOrDie(), info, and verbose_level.
{
  FC_ReturnCode rc;
  FC_VerbosityLevel verbose_level = FC_WARNING_MESSAGES;
  char *file_in_name, *file_out_name, *mesh1_name, *displacement1_name;
  FC_Dataset ds1;
  FC_Mesh    m1;
  int        step1;
  spanning_tree_t *tree1, *tree2;
  tree1 = tree2 = NULL;
  //Look at args user gave us
  checkArgs(argc, argv,
         &verbose_level,
         &file_in_name, &file_out_name,
         &mesh1_name, &displacement1_name, &step1);
  //Open up the library
  rc = fc_setLibraryVerbosity(verbose_level);         fc_exitIfError(rc);
  rc = fc_initLibrary();                              fc_exitIfError(rc);
  //Pass back info to user
  info("generate_tree is running with\n"
       "\tInput File   = '%s'\n"
       "\tMesh Name    = '%s'\n"
       "\tDisplacement = '%s'\n"
       "\tStep         = %d\n"
       "\tOutput File  = '%s'",
       file_in_name, mesh1_name,
       displacement1_name, step1,
       file_out_name);
  //Load the mesh
  rc = fc_loadDataset(file_in_name, &ds1);            fc_exitIfError(rc);
  rc = getMeshByNameOrDie(ds1, mesh1_name, &m1);      fc_exitIfError(rc);
  //Build a spanning tree for it
  info("Building a spanning tree");
  rc = fc_makeSpanningTree(m1, -1,&tree1 );           fc_exitIfError(rc);
  //Save the tree to its own file
  rc = fc_saveSkeleton(*tree1, displacement1_name,
                 file_out_name);                fc_exitIfError(rc);
  info("Done");
  return 0;
}
Variable Documentation
default_t defaults[]
Initial value:
 {
  { "/datasets/fe/ballsmash1.e",                   "Material_ID_3",  NULL,           "Ballsmash"},
  { "/datasets/fe/ballsmash1.e",                   "Material_ID_3",  "displacement", "Ballsmash w/ displacement"},
  { "/datasets/fe/wobble_c.e",                     "part_1",         NULL,           "Wobble"},
  { "/datasets/fe/wobble_c.e",                     "part_1",         "displacement", "Wobble w/ displacement"},
  { "/datasets/fe/helium_1.50_2.11.e",             "block_1",        NULL,           "Helium"},
  { "/datasets/fe/bookshelf/bookshelf_hole_a.e",   "block_15",       NULL,           "Bookshelf: hole at A"},
  { "/datasets/fe/bookshelf/bookshelf_hole_cba.e", "block_19",       NULL,           "Bookshelf: hole at A,B,C"},
  { NULL, NULL, NULL, NULL}
}
Definition at line 59 of file generate_tree.c.