FCLib: Topological Relations
Topological Relations
[FCLib API]
Detailed Description
Relationships between elements and vertices of the mesh.
Description:
The topology functions compute relationships between elements and vertices of the mesh itself, with no consideration of the actual physical coordinates of the vertices. So topology functions include ones such as compute which elements share a vertex, which vertices are part of an element, which vertices are part of an element which shares a face with a given element, etc.
Modules
(Private)
Membership relations.
FC_ReturnCode fc_getMeshEntityChildren (FC_Mesh mesh, FC_AssociationType parent_assoc, int parentID, FC_AssociationType child_assoc, int *numChild, int **childIDs)
Get the entities which make up the specified entity.
FC_ReturnCode fc_getMeshEntityParents (FC_Mesh mesh, FC_AssociationType child_assoc, int childID, FC_AssociationType parent_assoc, int *numParent, int **parentIDs)
Get the entities which own the specified entity.
FC_ReturnCode fc_changeMeshEntityType (FC_Mesh mesh, FC_AssociationType old_assoc, int numOldID, int *oldIDs, FC_AssociationType new_assoc, int doStrict, int *numNewID, int **newIDs)
Change the type of mesh entities.
Neighbors.
FC_ReturnCode fc_getMeshEntityNeighbors (FC_Mesh mesh, int entityID, FC_AssociationType assoc, int shared_dim, int *numNbr, int **nbrIDs)
Get the neighbors of a mesh subentity.
FC_ReturnCode fc_getSubsetNeighbors (FC_Subset subset, int level, int shared_dim, FC_AssociationType *nbr_assoc, int *numNbr, int **nbrIDs)
Get the neighbors of a subset.
Create connected components.
FC_ReturnCode fc_segment (FC_Subset subset, int shared_dim, int *numSubset, FC_Subset **newSubsets)
Created separate connected components.
Skins.
FC_ReturnCode fc_getSubsetSkin (FC_Subset subset, FC_Subset *skin)
Create a skin of the subset.
FC_ReturnCode fc_getMeshSkin (FC_Mesh mesh, FC_Subset *skin)
Create skin of the mesh.
Function Documentation
FC_ReturnCode fc_changeMeshEntityType (FC_Mesh mesh, FC_AssociationType old_assoc, int numOldID, int * oldIDs, FC_AssociationType new_assoc, int doStrict, int * numNewID, int ** newIDs)
Change the type of mesh entities.
Description:
Given an array of mesh entities, return an array of mesh entities of a different type that correspond to the same part of the mesh.
If the new association type is of higher dimensionality than the old (e.g. new subset will be on element and old was on vertices), the 'doStrict' flag determines whether to keep new entities if not all of their child entities are in the old subset. 1 = be strict and only have the entity in the new subset if all of it's children are present in the old subset. 0 = be lenient and add all entities that have at least one child in the old subset.
Entities cannot be of association type FC_AT_WHOLE_DATASET.
Modifications:
08/24/04 WSK, created.
Parameters:
mesh input - mesh
old_assoc input - the input association type
numOldID input - the number of old entities
oldIDs input - array of old entities' IDs
new_assoc input - the output association type
doStrict input - flag for dropping incomplete entities
numNewID output - the number of new entities
newIDs output - array of new entities' IDs
Definition at line 369 of file topo.c.
References _fc_deleteEntryFromSortedIntArray(), fc_addIntArrayToSortedIntArray(), FC_AT_UNKNOWN, FC_AT_WHOLE_DATASET, fc_convertSortedIntArrayToIntArray(), fc_getMeshEntityChildren(), fc_getMeshEntityParents(), fc_getMeshNumEntity(), fc_getReturnCodeText(), fc_initSortedIntArray(), FC_INPUT_ERROR, fc_isAssociationTypeValid(), fc_isMeshValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_SortedIntArray::numVal, and FC_SortedIntArray::vals.
Referenced by _fc_getSubsetDiameterCore(), _fc_getSubsetsDiameterCore(), _fc_getSubsetsProximityCore(), fc_copySubsetWithNewAssociation(), fc_createSubsetMesh(), fc_getDisplacedSubsetBoundingBox(), fc_getDisplacedSubsetCentroid(), fc_getEntitiesWithinBoundingBox(), fc_getEntitiesWithinSphere(), fc_getSubsetBoundingBox(), fc_getSubsetCentroid(), fc_getVariableWeightedDisplacedSubsetCentroid(), fc_getVariableWeightedSubsetCentroid(), and main().
  {
  FC_ReturnCode rc;
  int i, j;
  int numOldEntity, numTempID, *tempIDs;
  FC_SortedIntArray sia;
  int *mask;
  // default return values
  if (numNewID)
    *numNewID = -1;
  if (newIDs)
    *newIDs = NULL;
  // check input
  if (!fc_isMeshValid(mesh) || !fc_isAssociationTypeValid(old_assoc) ||
      old_assoc == FC_AT_UNKNOWN || old_assoc == FC_AT_WHOLE_DATASET ||
      numOldID < 0 || (numOldID > 0 && !oldIDs) ||
      !fc_isAssociationTypeValid(new_assoc) ||
      new_assoc == FC_AT_UNKNOWN || new_assoc == FC_AT_WHOLE_DATASET ||
      (doStrict != 0 && doStrict != 1) || !numNewID || !newIDs) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  rc = fc_getMeshNumEntity(mesh, old_assoc, &numOldEntity);
  for (i = 0; i < numOldID; i++) {
    if (oldIDs[i] < 0 || oldIDs[i] > numOldEntity) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
      return FC_INPUT_ERROR;
    }
  }
  // log message
  fc_printfLogMessage("Changing mesh entity type");
  // trivial case - empty old array
  if (numOldID == 0) {
    *numNewID = 0;
    return FC_SUCCESS;
  }
  // get list of all new association type (lenient)
  fc_initSortedIntArray(&sia);
  for (i = 0; i < numOldID; i++) {
    if (new_assoc < old_assoc)
      fc_getMeshEntityChildren(mesh, old_assoc, oldIDs[i], new_assoc,
                               &numTempID, &tempIDs);
    else if (new_assoc > old_assoc)
      fc_getMeshEntityParents(mesh, old_assoc, oldIDs[i], new_assoc,
                              &numTempID, &tempIDs);
    else {
      numTempID = 1;
      tempIDs = &oldIDs[i];
    }
    fc_addIntArrayToSortedIntArray(&sia, numTempID, tempIDs, 0);
    if (new_assoc != old_assoc)
      free(tempIDs);
  }
  // if strict, remove from members that don't have all of their children
  if (doStrict && new_assoc > old_assoc) {
    // make mask for easy lookup of old members
    mask = calloc(numOldEntity, sizeof(int));
    if (!mask)
      return FC_MEMORY_ERROR;
    for (i = 0; i < numOldID; i++)
      mask[oldIDs[i]] = 1;
    // walk sia and remove members
    j = 0;
    while (j < sia.numVal) {
      int notFound = 0;
      fc_getMeshEntityChildren(mesh, new_assoc, sia.vals[j], old_assoc,
                               &numTempID, &tempIDs);
      for (i = 0; i < numTempID; i++) {
        if (mask[tempIDs[i]] == 0) {
          notFound = 1;
          break;
        }
      }
      free(tempIDs);
      if (notFound) { // remove this node
     _fc_deleteEntryFromSortedIntArray(&sia, j);
      }
      else {
     j++;
      }
    }
    free(mask);
  }
  // convert sia to array
  return fc_convertSortedIntArrayToIntArray(&sia, numNewID, newIDs);
}
FC_ReturnCode fc_getMeshEntityChildren (FC_Mesh mesh, FC_AssociationType parent_assoc, int parentID, FC_AssociationType child_assoc, int * numChild, int ** childIDs)
Get the entities which make up the specified entity.
Description:
Given an entity on a mesh (e.g. vertex, element, etc) find the specified type of children of that entity. The specified child has to have a topological dimensionality less than the parent entity. (E.g., vertices and edges can be children of a face, but elements cannot.)
Entities cannot be of association FC_AT_WHOLE_DATASET
Todo:
Make sure this only calls the edge/face stuff when it's needed Clean up!
Modifications:
07/16/04 WSK Created.
11/01/2005 WSD. Fixed up so lazy building of edges & faces doesn't get called where not needed.
Parameters:
mesh input - mesh
parent_assoc input - the parent's entity type
parentID input - the parent's ID (e.g. element ID, etc)
child_assoc input - the type of mesh entities to return (must have topo dimensionality < parent_assoc.
numChild output - the number of children
childIDs output - array of child IDs
Definition at line 116 of file topo.c.
References _fc_getMeshElementParentsOfFacesPtr(), fc_addIntToSortedIntArray(), FC_AT_EDGE, FC_AT_ELEMENT, FC_AT_FACE, FC_AT_UNKNOWN, FC_AT_VERTEX, FC_AT_WHOLE_DATASET, FC_AT_WHOLE_MESH, fc_convertSortedIntArrayToIntArray(), fc_getElementTypeNumEdge(), fc_getElementTypeNumEntity(), fc_getMeshEdgeConnsPtr(), fc_getMeshElementConnsPtr(), fc_getMeshElementToEdgeConnsPtr(), fc_getMeshElementToFaceConnsPtr(), fc_getMeshElementType(), fc_getMeshEntityElementType(), fc_getMeshFaceConnsPtr(), fc_getMeshNumEntity(), fc_getReturnCodeText(), fc_initSortedIntArray(), FC_INPUT_ERROR, fc_isAssociationTypeValid(), fc_isMeshValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by _fc_buildFaceInfoListFromShape(), _fc_buildFaceInfoListFromSubset(), _fc_doesElementContainPoint(), fc_changeMeshEntityType(), fc_copySeqVariableWithNewAssociation(), fc_copyVariableWithNewAssociation(), fc_getPlanarSideNormal(), fc_getSideNormalMeanSdev(), and fc_getSubsetSkin().
  {
  FC_ReturnCode rc;
  int i, j, k;
  int numParent;
  FC_ElementType elemType;
  int maxNumChildPerParent, *parentToChildConns;
  // default return values
  if (numChild)
    *numChild = -1;
  if (childIDs)
    *childIDs = NULL;
  // check input
  if (!fc_isMeshValid(mesh) || !fc_isAssociationTypeValid(parent_assoc) ||
      parent_assoc == FC_AT_UNKNOWN || parent_assoc == FC_AT_WHOLE_DATASET ||
      parentID < 0 || !fc_isAssociationTypeValid(child_assoc) ||
      child_assoc == FC_AT_UNKNOWN || parent_assoc <= child_assoc ||
      !numChild || !childIDs) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  rc = fc_getMeshNumEntity(mesh, parent_assoc, &numParent);
  if (rc != FC_SUCCESS || parentID >= numParent) {
        fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting entities which make up the specified entity.");
  // special case 1: if whole, return list that is all of the child entities
  if (parent_assoc == FC_AT_WHOLE_MESH) {
    rc = fc_getMeshNumEntity(mesh, child_assoc, numChild);
    if (*numChild > 0) {
      *childIDs = (int*)malloc(*numChild*sizeof(int));
      if (*childIDs == NULL) {
        fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
        return FC_MEMORY_ERROR;
      }
      for (i = 0; i < *numChild; i++)
        (*childIDs)[i] = i;
    }
    return FC_SUCCESS;
  }
  // special case 2: face->edge conns don't exist on the mesh, so do
  // a local calc
  if (child_assoc == FC_AT_EDGE && parent_assoc == FC_AT_FACE) {
    int elemID, edgeID, found;
    int numEdgePerElem, *edgeConns, *elemToEdgeConns;
    int *numVertPerFace, maxNumVertPerFace, *faceConns;
    int *numElemPerFace, **elemParentsPerFace;
    FC_SortedIntArray sia;
    // setup
    rc = fc_getMeshElementType(mesh, &elemType);
    if (rc != FC_SUCCESS)
      return rc;
    rc = fc_getMeshEdgeConnsPtr(mesh, &edgeConns);
    if (rc != FC_SUCCESS)
      return rc;
    rc = fc_getMeshFaceConnsPtr(mesh, &numVertPerFace, &maxNumVertPerFace,
                                &faceConns);
    if (rc != FC_SUCCESS)
      return rc;
    rc = fc_getMeshElementToEdgeConnsPtr(mesh, &elemToEdgeConns);
    if (rc != FC_SUCCESS)
      return rc;
    rc = _fc_getMeshElementParentsOfFacesPtr(mesh, &numElemPerFace,
                                          &elemParentsPerFace);
    if (rc != FC_SUCCESS)
      return rc;
    numEdgePerElem = fc_getElementTypeNumEdge(elemType);
    // Get an element that owns the face
    elemID = elemParentsPerFace[parentID][0];
    // For each edge in element, if edge's verts are all in the face, add!
    fc_initSortedIntArray(&sia);
    for (i = 0; i < numEdgePerElem; i++) {
      edgeID = elemToEdgeConns[elemID*numEdgePerElem+i];
      found = 0;
      for (j = 0; j < 2; j++)
        for (k = 0; k < numVertPerFace[parentID]; k++)
          if (edgeConns[edgeID*2+j] ==
              faceConns[parentID*maxNumVertPerFace+k])
            found++;
      if (found == 2) { // both verts matched!
        int ret = fc_addIntToSortedIntArray(&sia, edgeID);
        if (ret < 0) {
          fc_printfErrorMessage("Failed to add edge to sia");
          return ret;
        }
      }
    }
    // all done
    rc = fc_convertSortedIntArrayToIntArray(&sia, numChild, childIDs);
    if (rc != FC_SUCCESS)
      return rc;
    return FC_SUCCESS;
  }
  // Get numChild & ids
  rc = fc_getMeshEntityElementType(mesh, parent_assoc, parentID, &elemType);
  if (rc != FC_SUCCESS)
    return rc;
  *numChild = fc_getElementTypeNumEntity(elemType, child_assoc);
  if (*numChild > 0) {
    *childIDs = (int*)malloc(*numChild*sizeof(int));
    if (*childIDs == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    maxNumChildPerParent = *numChild;
    if (child_assoc == FC_AT_VERTEX && parent_assoc == FC_AT_EDGE)
      rc = fc_getMeshEdgeConnsPtr(mesh, &parentToChildConns);
    else if (child_assoc == FC_AT_VERTEX && parent_assoc == FC_AT_FACE)
      rc = fc_getMeshFaceConnsPtr(mesh, NULL, &maxNumChildPerParent,
                                  &parentToChildConns);
    else if (child_assoc == FC_AT_VERTEX && parent_assoc == FC_AT_ELEMENT)
      rc = fc_getMeshElementConnsPtr(mesh, &parentToChildConns);
    else if (child_assoc == FC_AT_EDGE && parent_assoc == FC_AT_ELEMENT)
      rc = fc_getMeshElementToEdgeConnsPtr(mesh, &parentToChildConns);
    else if (child_assoc == FC_AT_FACE && parent_assoc == FC_AT_ELEMENT)
      rc = fc_getMeshElementToFaceConnsPtr(mesh, &parentToChildConns);
    memcpy(*childIDs, &parentToChildConns[parentID*maxNumChildPerParent],
           *numChild*sizeof(int));
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshEntityNeighbors (FC_Mesh mesh, int entityID, FC_AssociationType assoc, int shared_dim, int * numNbr, int ** nbrIDs)
Get the neighbors of a mesh subentity.
Description:
Given an entity on a mesh (e.g. vertex, element, etc) find the neighbors of that entity. The returned entities will be of the same type as the initial entity. The order indicates the depth of the neighbors, i.e. an order of 1 will return the immediate neighbors of the entity, an order of 2 will return the immediate neighbors and also the neighbors of the neighbors, etc.
The shared_dim parameter indicates the minimum dimensionality of the overlap (or shared parts) neighbors. In general, the shared_dim has to be less than the dimensionality of the entity and/or equal to 0 (vertices and point elements are special cases where shared_dim = dim = 0). Also, as the shared_dim increases, the condition for being neighbors becomes more stringent. For example, in a hex mesh, you can request element neighbors that share a face (share_dim = 2) or element neighbors that share an edge (share_dim = 1, this includes the face neighbors too) or element neighbors that share a vertex (share_dim = 0, this includes face and edge neighbors).
Entities cannot be of association type FC_AT_WHOLE_DATASET.
Modifications:
07/09/04 WSK Created to replace all of the entity specific neighbor routines like fc_getElementVertexNeighbors() with a single general purpose routine.
Parameters:
mesh input - mesh
entityID input - mesh entity ID (e.g. vertex ID, etc)
assoc input - the type of mesh entity
shared_dim input - the minimum dimensionality of shared part of neighbors
numNbr output - the number of neighbors
nbrIDs output - array of neighbor IDs
Definition at line 510 of file topo.c.
References _fc_getEdgeNeighbors(), _fc_getElementNeighbors(), _fc_getFaceNeighbors(), _fc_getVertexNeighbors(), FC_AT_EDGE, FC_AT_ELEMENT, FC_AT_FACE, FC_AT_UNKNOWN, FC_AT_VERTEX, FC_AT_WHOLE_DATASET, FC_AT_WHOLE_MESH, FC_ERROR, fc_getMeshNumEntity(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isAssociationTypeValid(), fc_isMeshValid(), fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by _fc_createShapePartsFromFaceInfoList(), _fc_growNeighborList(), fc_makeSpanningTree(), fc_segment(), and myCharacterizationFunkyAve().
  {
  FC_ReturnCode rc;
  int numEntity;
  // default return values
  if (numNbr)
    *numNbr = -1;
  if (nbrIDs)
    *nbrIDs = NULL;
  // check input
  if (!fc_isMeshValid(mesh) || entityID < 0 ||
      !fc_isAssociationTypeValid(assoc) || assoc == FC_AT_UNKNOWN ||
      assoc == FC_AT_WHOLE_DATASET ||
      shared_dim < 0 || shared_dim > 2 || !numNbr || !nbrIDs) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  rc = fc_getMeshNumEntity(mesh, assoc, &numEntity);
  if (rc != FC_SUCCESS || entityID >= numEntity) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting the neighbors of a mesh subentity.");
  // fill up list of neighbors by calling recursive functions
  switch (assoc) {
  case FC_AT_VERTEX:
    if (shared_dim != 0)
      return FC_INPUT_ERROR;
    else
      return _fc_getVertexNeighbors(mesh, entityID, numNbr, nbrIDs);
  case FC_AT_EDGE:
    if (shared_dim != 0)
      return FC_INPUT_ERROR;
    else
      return _fc_getEdgeNeighbors(mesh, entityID, numNbr, nbrIDs);
  case FC_AT_FACE:
    return _fc_getFaceNeighbors(mesh, entityID, shared_dim, numNbr, nbrIDs);
  case FC_AT_ELEMENT:
    return _fc_getElementNeighbors(mesh, entityID, shared_dim, numNbr, nbrIDs);
  case FC_AT_WHOLE_MESH:
    *numNbr = 0;
    return FC_SUCCESS;
  case FC_AT_WHOLE_DATASET: // shouldn't reach here
    return FC_ERROR;
  case FC_AT_UNKNOWN:
    fc_printfErrorMessage("Unknown association type");
    return FC_ERROR;
  }
  return FC_ERROR; // should never get here
}
FC_ReturnCode fc_getMeshEntityParents (FC_Mesh mesh, FC_AssociationType child_assoc, int childID, FC_AssociationType parent_assoc, int * numParent, int ** parentIDs)
Get the entities which own the specified entity.
Description:
Given an entity on a mesh (e.g. vertex, element, etc) find the specified type of parents of that entity. The specified parent has to have a topological dimensionality greater than the child entity. (E.g, faces and elements can be parents of an edge, but vertices cannot.)
This type of information is sometimes called adjacencies, e.g. get the elements adjacent to the given vertex.
Entities cannot be of association type FC_AT_WHOLE_DATASET.
Modifications:
07/09/04 WSK Created to replace fc_getElementIDsWithVertex with a more general purpose routine.
Parameters:
mesh input - mesh
child_assoc input - the child's entity type
childID input - the child's ID (e.g. vertex ID, etc)
parent_assoc input - the type of mesh entities to return (must have topo dimensionality > child_assoc.
numParent output - the number of parents
parentIDs output - array of parent IDs
Definition at line 279 of file topo.c.
References _fc_getEdgeParents(), _fc_getFaceParents(), _fc_getVertexParents(), FC_AT_EDGE, FC_AT_ELEMENT, FC_AT_FACE, FC_AT_UNKNOWN, FC_AT_VERTEX, FC_AT_WHOLE_DATASET, FC_AT_WHOLE_MESH, FC_ERROR, fc_getMeshNumEntity(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isAssociationTypeValid(), fc_isMeshValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by fc_changeMeshEntityType(), fc_copySeqVariableWithNewAssociation(), and fc_copyVariableWithNewAssociation().
  {
  FC_ReturnCode rc;
  int numEntity;
  // default return values
  if (numParent)
    *numParent = -1;
  if (parentIDs)
    *parentIDs = NULL;
  // check input
  if (!fc_isMeshValid(mesh) || !fc_isAssociationTypeValid(child_assoc) ||
      child_assoc == FC_AT_UNKNOWN || childID < 0 ||
      !fc_isAssociationTypeValid(parent_assoc) || parent_assoc == FC_AT_UNKNOWN
      || parent_assoc == FC_AT_WHOLE_DATASET || parent_assoc <= child_assoc ||
      !numParent || !parentIDs) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  rc = fc_getMeshNumEntity(mesh, child_assoc, &numEntity);
  if (rc != FC_SUCCESS || childID >= numEntity) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting the entities which own the specified entity.");
  // call a helper
  switch(child_assoc) {
  case FC_AT_VERTEX:
    return _fc_getVertexParents(mesh, childID, parent_assoc, numParent,
                                parentIDs);
  case FC_AT_EDGE:
    return _fc_getEdgeParents(mesh, childID, parent_assoc, numParent,
                              parentIDs);
  case FC_AT_FACE:
    return _fc_getFaceParents(mesh, childID, parent_assoc, numParent,
                              parentIDs);
  case FC_AT_ELEMENT:
    *numParent = 1;
    *parentIDs = (int*)malloc(sizeof(int));
    if (*parentIDs == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    (*parentIDs)[0] = 0;
    return FC_SUCCESS;
  case FC_AT_WHOLE_MESH: // shouldn't reach here
  case FC_AT_WHOLE_DATASET: // shouldn't reach here
  case FC_AT_UNKNOWN: // shouldn't reach here
    fc_printfErrorMessage("Input Error: Wrong association type");
    return FC_INPUT_ERROR;
  }
  // should never get here
  return FC_ERROR;
}
FC_ReturnCode fc_getMeshSkin (FC_Mesh mesh, FC_Subset * skin)
Create skin of the mesh.
Description:
This function creates a subset which contains the "skin" of the mesh. The topo dimensionality of the skin will always be 1 less than the topo dimensionality of the mesh's elements (e.g. the skin of a hex mesh will be faces, and the skin of an edge mesh will be verticies).
This routine is similar to fc_getSubsetSkin.
Todo:
?Let user name skin.
Modifications:
09/03/04 WSK, created.
Parameters:
mesh input - mesh
skin output - subset with skin of the mesh
Definition at line 1792 of file topo.c.
References fc_addMemberToSubset(), FC_AT_WHOLE_MESH, fc_createSubset(), fc_deleteSubset(), fc_getReturnCodeText(), fc_getSubsetSkin(), FC_INPUT_ERROR, fc_isMeshValid(), FC_NULL_SUBSET, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by fc_getDecayedSkin(), fc_getExposedSkin(), and main().
  {
  FC_ReturnCode rc;
  FC_Subset temp_subset;
  //---default return values
  if (skin)
    *skin = FC_NULL_SUBSET;
  // check input
  if (!fc_isMeshValid(mesh) || !skin) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Creating new subset which is the skin of the mesh");
  // create a temp subset which is the whole mesh & call fc_getSubsetSkin()
  rc = fc_createSubset(mesh, "fc_getMeshSkin temp subset", FC_AT_WHOLE_MESH,
                       &temp_subset);
  if (rc != FC_SUCCESS) {
    fc_deleteSubset(temp_subset);
    return rc;
  }
  fc_addMemberToSubset(temp_subset, 0);
  // do it
  rc = fc_getSubsetSkin(temp_subset, skin);
  fc_deleteSubset(temp_subset);
  return rc;
}
FC_ReturnCode fc_getSubsetNeighbors (FC_Subset subset, int level, int shared_dim, FC_AssociationType * nbr_assoc, int * numNbr, int ** nbrIDs)
Get the neighbors of a subset.
Description:
This routine will return the neighbors of a subset. Neighbor type is determined by association type of the subset and the argument 'shared_dim' (see fc_getMeshEntityNeighbors for more on neighbors). Level indicates the depth of the neighbors where a level of 1 will return the the first layer of neighbors immediately surrounding the subset members, level 2 will return two layers of neighbors (neighbors of the neighbors), etc.
The shared_dim parameter indicates the minimum dimensionality of the overlap (or shared parts) neighbors. In general, the shared_dim has to be less than the dimensionality of the subset's entities and/or equal to 0 (vertices and point elements are special cases where shared_dim = dim = 0). Also, as the shared_dim increases, the condition for being neighbors becomes more stringent. For example, in a hex mesh, you can request element neighbors that share a face (share_dim = 2) or element neighbors that share an edge (share_dim = 1, this includes the face neighbors too) or element neighbors that share a vertex (share_dim = 0, this includes face and edge neighbors).
Modifications:
07/023/04 WSK Created so that I can get rid of recursive getNeighbors calls.
Parameters:
subset input - subset
level input - depth of neighbors to return, 1 or greater
shared_dim input - the minimum dimensionality of shared part of neighbors
nbr_assoc output - the type of mesh entity
numNbr output - the number of neighbors
nbrIDs output - array of neighbor IDs
Definition at line 603 of file topo.c.
References _fc_growNeighborList(), fc_addIntArrayToSortedIntArray(), FC_AT_UNKNOWN, fc_convertSortedIntArrayToIntArray(), fc_deleteIntFromSortedIntArray(), fc_freeSortedIntArray(), fc_getMeshFromSubset(), fc_getReturnCodeText(), fc_getSubsetInfo(), fc_getSubsetMembersAsArray(), fc_initSortedIntArray(), FC_INPUT_ERROR, fc_isSubsetValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by fc_createSideAdjacencyMatrix(), and fc_subsetPlusNeighborGreaterSegmentationMesh().
  {
  FC_ReturnCode rc;
  int i;
  int maxNumMember, numMember, *memberIDs;
  int *checked;
  FC_Mesh mesh;
  FC_SortedIntArray members_list, nbrs_list;
  // default return values
  if (nbr_assoc)
    *nbr_assoc = FC_AT_UNKNOWN;
  if (numNbr)
    *numNbr = -1;
  if (nbrIDs)
    *nbrIDs = NULL;
  // check input
  if (!fc_isSubsetValid(subset) ||  level < 1 || shared_dim < 0 ||
      shared_dim > 2 || !nbr_assoc  || !numNbr || !nbrIDs) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting the neighbors of a subset.");
  // get info from subset
  rc = fc_getSubsetInfo(subset, &numMember, &maxNumMember, nbr_assoc);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Error getting info from subset.");
    return rc;
  }
  rc = fc_getSubsetMembersAsArray(subset, &numMember, &memberIDs);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getMeshFromSubset(subset, &mesh);
  if (rc != FC_SUCCESS)
    return rc;
  fc_initSortedIntArray(&members_list);
  fc_addIntArrayToSortedIntArray(&members_list, numMember, memberIDs, 1);
  // Recursively expand the nbrs_list
  checked = calloc(maxNumMember, sizeof(int));
  if (checked == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  fc_initSortedIntArray(&nbrs_list);
  rc = _fc_growNeighborList(mesh, &members_list, *nbr_assoc, level, shared_dim,
                             checked, &nbrs_list);
  free(checked);
  fc_freeSortedIntArray(&members_list);
  if (rc != FC_SUCCESS) {
    *nbr_assoc = FC_AT_UNKNOWN;
    free(memberIDs);
    fc_printfErrorMessage("Error growing neighbor list.");
    return rc;
  }
  // make sure current members are not in list
  for (i = 0; i < numMember; i++)
    fc_deleteIntFromSortedIntArray(&nbrs_list, memberIDs[i]);
  free(memberIDs);
  // convert nbrs_list to array
  rc = fc_convertSortedIntArrayToIntArray(&nbrs_list, numNbr, nbrIDs);
  return rc;
}
FC_ReturnCode fc_getSubsetSkin (FC_Subset subset, FC_Subset * skin)
Create a skin of the subset.
Description:
This function creates a subset which contains the "skin" of the original subset. The topo dimensionality of the skin will always be 1 less than the topo dimensionality of the original subset's members. (e.g. the skin of a subset containing 3D elements will be faces, the skin of an edge subset will be vertices).
This may change: for now, it is an error to try to create a skin of an empty subset.
The skin of a subset is found by iterating over the "skins" of the original mesh entities and determining which skin elements are only seen once. The list of unique skins of the original mesh entities will be the skin of the entire subset.
Be warned that behavior on subsets associated with entities that are not elements may not be what you expect. For example, if you have a subset which consists of the six faces of a hex element, the generated skin will be empty because the edges of the faces all belong to more than one face.
Todo:
Decide what to do if no members in original subset. Error or not? If not, return null handle or empty subset?
Modifications:
09/03/04 WSK, created.
Parameters:
subset input - subset
skin output - array of segmented regions
Definition at line 1645 of file topo.c.
References fc_addMemberToSubset(), FC_AT_EDGE, FC_AT_ELEMENT, FC_AT_FACE, FC_AT_UNKNOWN, FC_AT_VERTEX, FC_AT_WHOLE_MESH, fc_createSubset(), FC_ERROR, fc_getAssociationTypeText(), fc_getElementTypeTopoDim(), fc_getMeshEntityChildren(), fc_getMeshEntityElementType(), fc_getMeshFromSubset(), fc_getMeshNumElement(), fc_getMeshNumEntity(), fc_getReturnCodeText(), fc_getSubsetInfo(), fc_getSubsetMembersAsArray(), fc_getSubsetName(), fc_getSubsetNumMember(), FC_INPUT_ERROR, fc_isAssociationTypeValid(), fc_isSubsetValid(), FC_MEMORY_ERROR, FC_NULL_SUBSET, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by fc_getDecayedSkin(), fc_getExposedSkin(), and fc_getMeshSkin().
  {
  FC_ReturnCode rc;
  int i, j;
  FC_AssociationType assoc_orig, assoc_skin;
  char* temp_name, *subset_name;
  int numMember, *memberIDs, maxNumSkin, *counts, numChild, *childIDs;
  int topodim_orig;
  FC_Mesh mesh;
  FC_ElementType elemType;
  //---default return values
  if (skin)
    *skin = FC_NULL_SUBSET;
  // check input
  if (!fc_isSubsetValid(subset) || !skin) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Creating new subset which is the skin of this subset");
  // Get info from subset and a little more checking
  rc = fc_getSubsetNumMember(subset, &numMember);
  if (rc != FC_SUCCESS)
    return FC_ERROR;
  rc = fc_getSubsetInfo(subset, NULL, NULL, &assoc_orig);
  if (rc != FC_SUCCESS)
    return FC_ERROR;
  rc = fc_getMeshFromSubset(subset, &mesh);
  if (rc != FC_SUCCESS)
    return FC_ERROR;
  if (numMember < 1) {
    fc_printfErrorMessage("Can't create skin of empty subset");
    return FC_ERROR;
  }
  if (!fc_isAssociationTypeValid(assoc_orig) || assoc_orig == FC_AT_UNKNOWN ||
      assoc_orig == FC_AT_VERTEX) {
    fc_printfErrorMessage("Can't handle subset with association type %s",
                          fc_getAssociationTypeText(assoc_orig));
    return FC_ERROR;
  }
  // Get members -- If subset is whole, get all elements
  if (assoc_orig == FC_AT_WHOLE_MESH) {
    assoc_orig = FC_AT_ELEMENT;
    rc = fc_getMeshNumElement(mesh, &numMember);
    if (rc != FC_SUCCESS)
      return FC_ERROR;
    memberIDs = malloc(numMember*sizeof(int));
    if (!memberIDs) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    for (i = 0; i < numMember; i++)
      memberIDs[i] = i;
  }
  else {
    rc = fc_getSubsetMembersAsArray(subset, &numMember, &memberIDs);
    if (rc != FC_SUCCESS)
      return FC_ERROR;
  }
  // determine topodim of the members
  rc = fc_getMeshEntityElementType(mesh, assoc_orig, 0, &elemType);
  if (rc != FC_SUCCESS)
    return FC_ERROR;
  topodim_orig = fc_getElementTypeTopoDim(elemType);
  // count children of the members
  switch (topodim_orig) {
  case 3:  assoc_skin = FC_AT_FACE;    break;
  case 2:  assoc_skin = FC_AT_EDGE;    break;
  case 1:  assoc_skin = FC_AT_VERTEX;  break;
  default:
    fc_printfErrorMessage("Invalid topodim '%d'", topodim_orig);
    free(memberIDs);
    return FC_ERROR;
  }
  rc = fc_getMeshNumEntity(mesh, assoc_skin, &maxNumSkin);
  if (rc != FC_SUCCESS)
    return rc;
  counts = calloc(maxNumSkin, sizeof(int));
  if (!counts) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < numMember; i++) {
    fc_getMeshEntityChildren(mesh, assoc_orig, memberIDs[i], assoc_skin,
                             &numChild, &childIDs);
    for (j = 0; j < numChild; j++)
      counts[childIDs[j]]++;
    free(childIDs);
  }
  free(memberIDs);
  // create new subset
  rc = fc_getSubsetName(subset, &subset_name);
  if (rc != FC_SUCCESS)
    return FC_ERROR;
  temp_name = malloc((strlen(subset_name)+10)*sizeof(char));
  sprintf(temp_name, "%s_skin", subset_name);
  free(subset_name);
  rc = fc_createSubset(mesh, temp_name, assoc_skin, skin);
  free(temp_name);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Error creating subset.");
    return FC_ERROR;
  }
  // stuff in new members
  for (i = maxNumSkin-1; i >= 0; i--) {
    if (counts[i] == 1) {
      fc_addMemberToSubset(*skin, i);
    }
  }
  // cleanup
  free(counts);
  return FC_SUCCESS;
}
FC_ReturnCode fc_segment (FC_Subset subset, int shared_dim, int * numSubset, FC_Subset ** newSubsets)
Created separate connected components.
Description:
This function takes a subset and separates into separate connected regions. It returns the number of regions and a new subset for each region. The new subsets will be named as the name of the original subset, postpended with "_Seg#" where # will be the index into the array of returned subsets.
Mesh subentities (e.g. elements, vertices, etc) are considered to be connected if they are neighbors. The type of neighborship relation is specified by the minimum shared dim (see fc_getMeshEntityNeighbors). The most common value of shared_dim is 0.
Modifications:
02/06/04 WSK, created.
06/29/04 RM, combined _fc_segment() into fc_segment(), changed interface to take subset as input and return subsets
Parameters:
subset input - subset
shared_dim input - the minimum dimensionality of shared part of neighbors
numSubset output - number of new subsets
newSubsets output - array of segmented regions
Definition at line 1432 of file topo.c.
References _fc_expandIntArray(), _fc_getSubSlot(), fc_addArrayMembersToSubset(), FC_AT_EDGE, FC_AT_FACE, FC_AT_VERTEX, fc_convertIntArrayToSortedIntArray(), fc_createSubset(), fc_deleteIntFromSortedIntArray(), FC_ERROR, fc_freeSortedIntArray(), fc_getMeshEntityNeighbors(), fc_getMeshFromSubset(), fc_getReturnCodeText(), fc_getSortedIntArrayFront(), fc_getSubsetInfo(), fc_getSubsetMembersAsArray(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_popSortedIntArrayFront(), fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SlotHeader::name, and FC_SortedIntArray::numVal.
Referenced by calcSegmentsVolumes(), calcShapeIntersection(), fc_subsetSegmentsMesh(), fc_subsetSegmentsSubset(), find_and_print_bbs(), main(), processOneVar(), and segmentMesh().
  {
  int i;
  int ret;
  FC_ReturnCode rc;
  int numSegment = 0;
  int numMember, *memberIDs;
  FC_Subset *segments = NULL;
  FC_SortedIntArray orig_list;  // the starting list, will end empty
  FC_AssociationType assoc;
  _FC_SubSlot *subsetSlot;
  char* temp_name, *subsetName;
  FC_Mesh mesh;
  int key, numID, maxNumID, *IDs; // not using an sia for ids - don't need sort
  int numWorking, maxNumWorking, *workingIDs; // also don't need sort
  void* temp;
  //---default return values
  if (numSubset)
    *numSubset = -1;
  if (newSubsets)
    *newSubsets = NULL;
  // check input
  subsetSlot = _fc_getSubSlot(subset);
  if (!subsetSlot || shared_dim < 0 || shared_dim > 2 || !numSubset ||
      !newSubsets) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  rc = fc_getSubsetInfo(subset, NULL, NULL, &assoc);
  if (rc != FC_SUCCESS)
    return FC_ERROR;
  if ( ( (assoc == FC_AT_VERTEX || assoc == FC_AT_EDGE) && shared_dim > 0) ||
       (assoc == FC_AT_FACE && shared_dim > 1) ) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Segmenting subset '%s'", subsetSlot->header.name);
  // Get more info from subset
  rc = fc_getMeshFromSubset(subset, &mesh);
  if (rc != FC_SUCCESS)
    return FC_ERROR;
  rc = fc_getSubsetMembersAsArray(subset, &numMember, &memberIDs);
  if (rc != FC_SUCCESS)
    return FC_ERROR;
  subsetName = subsetSlot->header.name;
  // trivial case, if no members, not an error, return success
  if (numMember == 0) {
    *numSubset = 0;
    return FC_SUCCESS;
  }
  // convert memberIDs to orig list
  rc = fc_convertIntArrayToSortedIntArray(numMember, memberIDs, 1, &orig_list);
  if (rc < FC_SUCCESS)
    return rc;
  // setup space for names of segments
  temp_name = malloc((strlen(subsetName)+20)*sizeof(char));
  if (temp_name == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  //---segment the linked list
  numSegment = 0;
  while (orig_list.numVal > 0) { // each pass will create a new subset
    // FIX change all to back 'cause more efficient
    // initialize working list & segment list
    numWorking = 0;
    maxNumWorking = 0;
    workingIDs = NULL;
    numID = 0;
    maxNumID = 0;
    IDs = NULL;
    // remove starting ID (seed) from orig list ...
    fc_getSortedIntArrayFront(&orig_list, &key);
    fc_popSortedIntArrayFront(&orig_list);
    // ... & add to working & segment lists
    _fc_expandIntArray(&maxNumWorking, &workingIDs);
    _fc_expandIntArray(&maxNumID, &IDs);
    workingIDs[0] = key;
    numWorking++;
    IDs[0] = key;
    numID++;
    // "grow" connected region from seed by checking neighbors recursively
    while (numWorking > 0) {
      int numNeighbor, *neighborIDs;
      // can stop early if orig_list is empty
      if (orig_list.numVal == 0)
        break;
      // remove 1st entity from working list
      key = workingIDs[numWorking-1];
      numWorking--;
      // Move neighbors of that entity that are in the orig
      // list to the segments list & also the working list
      rc = fc_getMeshEntityNeighbors(mesh, key, assoc, shared_dim,
                                     &numNeighbor, &neighborIDs);
      if (rc != FC_SUCCESS)
        return rc;
      for (i = 0; i < numNeighbor; i++) {
        ret = fc_deleteIntFromSortedIntArray(&orig_list, neighborIDs[i]);
        if (ret > 0) { // found one
       if (numWorking == maxNumWorking) {
         rc = _fc_expandIntArray(&maxNumWorking, &workingIDs);
         if (rc != FC_SUCCESS)
           return rc;
       }
       if (numID == maxNumID) {
         rc = _fc_expandIntArray(&maxNumID, &IDs);
         rc = _fc_expandIntArray(&maxNumWorking, &workingIDs);
         if (rc != FC_SUCCESS)
           return rc;
       }
       workingIDs[numWorking] = neighborIDs[i];
       numWorking++;
       IDs[numID] = neighborIDs[i];
       numID++;
        }
      }
      free(neighborIDs);
    }
    // create subset from list of IDs
    temp = realloc(segments, (numSegment+1)*sizeof(FC_Subset));
    if (temp == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    segments = temp;
    sprintf(temp_name, "%s_Seg%d", subsetName, numSegment);
    rc = fc_createSubset(mesh, temp_name, assoc, &segments[numSegment]);
    if (rc != FC_SUCCESS) {
      fc_printfErrorMessage("cannot create newSubset[%d]", numSegment);
      return FC_ERROR;
    }
    rc = fc_addArrayMembersToSubset(segments[numSegment], numID, IDs);
    if (rc != FC_SUCCESS) {
      fc_printfErrorMessage("cannot add members to newSubset[%d]", numSegment);
      return FC_ERROR;
    }
    free(workingIDs);
    free(IDs);
    numSegment++;
  }
  // cleanup (orig_list is empty)
  free(temp_name);
  fc_freeSortedIntArray(&orig_list);
  // return values
  *numSubset = numSegment;
  *newSubsets = segments;
  return FC_SUCCESS;
}