FCLib: File IO
File IO
[Data Interface]
Detailed Description
Generic file IO.
Description:
This file provides wrappers to the various file IO options to hide the specific implementations (the specific implementations should generally not be used). We used to support certian SAF conventions, but no longer. For details about a specific type of IO see (Private Exodus IO) (Private LS-Dyna IO).
Modifications:
07/13/2005 WSD created to separate file IO out more so that it is easier to add new types.
10/15/2007 ACG removed saf
Modules
(Private Generic IO)
Generic file IO.
(Private Exodus IO)
Exodus II file IO.
(Private LS-Dyna IO)
LS-Dyna file IO.
File IO enumerated type.
enum FC_FileIOType {
FC_FT_NONE = 0,
FC_FT_EXODUS,
FC_FT_LSDYNA
}
Types of file formats for dataset file IO.
Queries of File IO enumerated type.
int fc_isFileIOTypeValid (FC_FileIOType fileType)
Verify that the given value is valid for this enum.
char * fc_getFileIOTypeText (FC_FileIOType fileType)
Return name of the FC_FileIOType's value.
int fc_isFileIOTypeReadSupported (FC_FileIOType fileType)
Verify that a file IO type can be read.
int fc_isFileIOTypeWriteSupported (FC_FileIOType fileType)
Verify that a file IO type can be written.
File IO operations on datasets.
FC_ReturnCode fc_getDatasetFileIOType (FC_Dataset dataset, FC_FileIOType *fileType)
Get type of file format.
FC_ReturnCode fc_loadDataset (char *filename, FC_Dataset *dataset)
Load a dataset and it's members from a file.
FC_ReturnCode fc_loadDatasetWithFormat (char *filename, FC_FileIOType fileType, FC_Dataset *dataset)
Load a dataset and it's members from a file.
FC_ReturnCode fc_writeDataset (FC_Dataset dataset, char *filename, FC_FileIOType fileType)
Write a dataset.
FC_ReturnCode fc_rewriteDataset (FC_Dataset dataset, char *filename, FC_FileIOType fileType)
Rewrite a dataset.
Enumeration Type Documentation
enum FC_FileIOType
Types of file formats for dataset file IO.
Description:
All possible file types are defined, but not all may be available in a specific installation.
NOTE: purposefully do not have this type stuff in base.h because then only this set of files (fileio) needs to be modified if different format types are available.
Todo:
? Add html pointers for each type?
Todo:
? Is the NOTE above true? move this & helpers to base.h?
Modifications:
7/13/05 WSD Created.
Enumerator:
FC_FT_NONE Type not specified
FC_FT_EXODUS Exodus II
FC_FT_LSDYNA LS-DYNA
Definition at line 79 of file fileio.h.
             {
  FC_FT_NONE = 0,   /**< Type not specified */
  FC_FT_EXODUS,     /**< Exodus II */
  FC_FT_LSDYNA,     /**< LS-DYNA */
} FC_FileIOType;
Function Documentation
FC_ReturnCode fc_getDatasetFileIOType (FC_Dataset dataset, FC_FileIOType * fileType)
Get type of file format.
Modifications:
7/14/2005 WSD Created.
Parameters:
dataset input - dataset handle
fileType output - file format type
Definition at line 1517 of file fileio.c.
References _fc_getDsSlot(), FC_FT_NONE, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_DsSlot::fileType, _FC_DsSlot::header, and _FC_SlotHeader::name.
Referenced by main().
  {
  _FC_DsSlot* dsSlot;
  // default return value
  if (fileType)
    *fileType = FC_FT_NONE;
  // check input
  dsSlot = _fc_getDsSlot(dataset);
  if (dsSlot == NULL || fileType == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting file type for dataset '%s'",
                dsSlot->header.name);
  // do it
  *fileType = dsSlot->fileType;
  return FC_SUCCESS;
}
char* fc_getFileIOTypeText (FC_FileIOType fileType)
Return name of the FC_FileIOType's value.
Modifications:
7/14/2005 WSD, Created
Definition at line 1418 of file fileio.c.
References FC_FT_EXODUS, FC_FT_LSDYNA, and FC_FT_NONE.
Referenced by _fc_getMeshExodusGlobalElementIDOffset(), _fc_getMeshExodusGlobalNodalIDsPtr(), and _fc_printDsTable().
  {
  switch(fileType) {
  case FC_FT_NONE:    return "FC_FT_NONE";
  case FC_FT_EXODUS:  return "FC_FT_EXODUS";
  case FC_FT_LSDYNA:  return "FC_FT_LSDYNA";
  // no default case so will get warning if new values added to enum
  }
  return "invalid value for enum FC_FileIOType";
}
int fc_isFileIOTypeReadSupported (FC_FileIOType fileType)
Verify that a file IO type can be read.
Description:
The library can be build with or without support for various file types and some types are supported only for reading. Use this routine to determine if the requested file type is supported for reading.
Note that a file IO type of FC_FT_NONE is considered supported since it requires no support.
Todo:
Think more about what FC_FT_NONE should return.
Modifications:
2/1/2006 WSD, Created
Definition at line 1448 of file fileio.c.
References FC_FT_EXODUS, FC_FT_LSDYNA, and FC_FT_NONE.
  {
  switch(fileType) {
  case FC_FT_NONE:
    return 1;  // requires no support, so supported by default
  case FC_FT_EXODUS:
#ifdef HAVE_EXODUS
    return 1;
#else
    return 0;
#endif
  case FC_FT_LSDYNA:
    return 1;
  // no default case so will get warning if new values added to enum
  }
  return 0;
}
int fc_isFileIOTypeValid (FC_FileIOType fileType)
Verify that the given value is valid for this enum.
Modifications:
7/14/2005 WSD, Created
Definition at line 1398 of file fileio.c.
References FC_FT_EXODUS, FC_FT_LSDYNA, and FC_FT_NONE.
Referenced by fc_rewriteDataset(), and fc_writeDataset().
  {
  switch(fileType) {
  case FC_FT_NONE:     // fall through
  case FC_FT_EXODUS:   // fall through
  case FC_FT_LSDYNA:   // fall through
  // no default case so will get warning if new values added to enum
    return 1;
  }
  return 0;
}
int fc_isFileIOTypeWriteSupported (FC_FileIOType fileType)
Verify that a file IO type can be written.
Description:
The library can be build with or without support for various file types and some types are supported only for reading. Use this routine to determine if the requested file type is supported for writing.
Note that a file IO type of FC_FT_NONE is considered supported since it requires no support.
Todo:
Think more about what FC_FT_NONE should return.
Modifications:
2/1/2006 WSD, Created
Definition at line 1485 of file fileio.c.
References FC_FT_EXODUS, FC_FT_LSDYNA, and FC_FT_NONE.
Referenced by main().
  {
  switch(fileType) {
  case FC_FT_NONE:
    return 0;  // can't do, so not supported
  case FC_FT_EXODUS:
#ifdef HAVE_EXODUS
    return 1;
#else
    return 0;
#endif
  case FC_FT_LSDYNA:
    return 0;
  // no default case so will get warning if new values added to enum
  }
  return 0;
}
FC_ReturnCode fc_loadDataset (char * filename, FC_Dataset * dataset)
Load a dataset and it's members from a file.
Description:
Given a the name of a database file, this routine loads the dataset and makes all of it's members available for use.
This routine automatically picks file format based on the name of the file. If this is unsatisfactory, use fc_loadDatasetWithFormat. See FC_FileIOType for supported formats.
For some formats the members are loaded lazily: that is all of their metadata data is loaded immediately, but the big data arrays are not loaded until needed (this happens automatically). (this was true with saf and is only partially true with exodus)
Modifications:
7/13/2004 WSD. Old method contents moved to fc_loadDatasetWithFormat. This is a convenience function w/o the fileType arg.
Parameters:
filename input - name of dataset to open
dataset output - handle for this dataset
Definition at line 1565 of file fileio.c.
References FC_FT_NONE, and fc_loadDatasetWithFormat().
Referenced by main().
  {
  return fc_loadDatasetWithFormat(filename, FC_FT_NONE, dataset);
}
FC_ReturnCode fc_loadDatasetWithFormat (char * filename, FC_FileIOType fileType, FC_Dataset * dataset)
Load a dataset and it's members from a file.
Description:
Given a the name of a database file, this routine loads the dataset and makes all of it's members available for use.
If a specific filetype is passed in, the load will fail if the file is not of that type. If FC_FT_NONE is passed in, this routine automatically determines the dataset type. See FC_FileIOType for supported formats.
For some formats, the members are loaded lazily: that is all of their metadata data is loaded immediately, but the big data arrays are not loaded until needed (this happens automatically). (This was true with saf, and is ony partially true with exodus)
Modifications:
Nancy Collins Created.
Aug 5, 2002 W Koegler Now calls _fc_setupDsSlot() so that fc_openDataset() and use_dataset() can use the same code to setup the ftable slot. (RM comment: use_dataset() does not exist anymore.)
11/20/03 RM changed behavior: when library is not initialized - return an error.
11/25/03 RM, always return default NULL dataset handle if anything goes wrong.
09/07/04 WSK, changed name from fc_openDataset to fc_loadDataset.
01/13/05 WSK, this code now wraps calls to database type specific codes. Most of the old contents have been moved to _fc_loadSAFDataset().
7/13/02005 WSD Moved to fileio.c.
7/13/2004 WSD Added flag for file format type. Name changed.
4/17/2007 CDU Added check to see if file is a regular file
Parameters:
filename input - name of dataset to open
fileType input - File Type (pass FC_FT_NONE if unknonw
dataset output - handle for this dataset
Definition at line 1607 of file fileio.c.
References _fc_isLibraryInit(), _fc_loadExodusDataset(), _fc_loadLSDynaDataset(), FC_ERROR, FC_FILE_IO_ERROR, FC_FT_EXODUS, FC_FT_LSDYNA, FC_FT_NONE, fc_getBasename(), fc_getExtension(), fc_getReturnCodeText(), FC_INPUT_ERROR, FC_NULL_DATASET, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by fc_loadDataset().
  {
  struct stat f_stat;
  int res;
  FC_ReturnCode rc;
  // default return value
  if (dataset != NULL)
    *dataset = FC_NULL_DATASET;
  // check input
  if ((filename == NULL) || (dataset == NULL)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // make sure library is ready, return error if it's not
  if (!_fc_isLibraryInit()) {
    fc_printfErrorMessage("Cannot load a dataset until library is initialized.");
    return FC_ERROR;
  }
  // log message
  fc_printfLogMessage("Loading dataset '%s'", filename);
  // Make sure this is a readable file in case lower io libs
  // don't check (ie, exodus)
  res=stat(filename, &f_stat);
  if(res || !S_ISREG(f_stat.st_mode)){
    fc_printfErrorMessage("File %s is not a regular file.", filename);
    return FC_ERROR;
  }
  // Pick a type
  // FIX make this smarter?
  if (fileType == FC_FT_NONE) {
    char *basename = fc_getBasename(filename);
    char *extension = fc_getExtension(filename, 1);
    if (!strcasecmp(basename, "d3plot")) // test this first
      fileType = FC_FT_LSDYNA;
    else if (extension) {
      if (!strcasecmp(extension, "e") || !strcasecmp(extension, "e2") ||
       !strcasecmp(extension, "exo"))
     fileType = FC_FT_EXODUS;
    }
    free(basename);
    free(extension);
  }
  switch (fileType) {
  case FC_FT_EXODUS:
#ifdef HAVE_EXODUS
    return _fc_loadExodusDataset(filename, dataset);
#else
    fc_printfErrorMessage("Exodus module not available");
    return FC_FILE_IO_ERROR;
#endif
  case FC_FT_LSDYNA:
    return _fc_loadLSDynaDataset(filename, dataset);
  case FC_FT_NONE: // fall through
  default:
    // Try every type until we get one that works
#ifdef HAVE_EXODUS
    rc = _fc_loadExodusDataset(filename, dataset);
    if (rc == FC_SUCCESS)
      return rc;
#endif
    rc = _fc_loadLSDynaDataset(filename, dataset);
    if (rc == FC_SUCCESS)
      return rc;
    // Couldn't find one
    fc_printfErrorMessage("Could not open database '%s'",
                 filename);
    return FC_FILE_IO_ERROR;
  }
}
FC_ReturnCode fc_rewriteDataset (FC_Dataset dataset, char * filename, FC_FileIOType fileType)
Rewrite a dataset.
Description:
This will force the writing of a dataset that is already associated with a file on disk, e.g. to rewrite an Exodus dataset or write an Exodus dataset into a differnt type of file. Calling on a dataset that has never been associated with a file is o.k.
Empty subsets do not get written.
Todo:
?Passing NULL for the name will make it use the original dataset's filename and type -- essentially rewriting it?
Todo:
?Replace fc_writeDataset with this version?
Todo:
Write to filename.tmp then move filename.tmp to filename -- then if rewriting a file, old version less likely to get clobbered in case of an error.
Modifications:
3/25/2006 WSD Created.
Parameters:
dataset the dataset to write
filename the filename to write to
fileType the file type to write
Definition at line 1776 of file fileio.c.
References _fc_closeDataset(), _fc_getDsSlot(), _fc_getMeshSlot(), _fc_getSeqSlot(), _fc_getSubSlot(), _fc_getVarSlot(), _FC_SlotHeader::committed, fc_getGlobalSeqVariables(), fc_getGlobalVariables(), fc_getMeshCoordsPtr(), fc_getMeshElementConnsPtr(), fc_getMeshes(), fc_getReturnCodeText(), fc_getSequenceCoordsPtr(), fc_getSequences(), fc_getSeqVariables(), fc_getSubsetMembersAsArray(), fc_getSubsets(), fc_getVariableDataPtr(), fc_getVariables(), FC_INPUT_ERROR, fc_isFileIOTypeValid(), fc_printfErrorMessage, FC_SUCCESS, fc_writeDataset(), _FC_DsSlot::header, _FC_MeshSlot::header, _FC_SubSlot::header, _FC_SeqSlot::header, _FC_VarSlot::header, _FC_DsSlot::numMesh, _FC_DsSlot::numSeq, and _FC_DsSlot::writable.
Referenced by main().
  {
  FC_ReturnCode rc;
  _FC_DsSlot* dsSlot;
  // check input
  dsSlot = _fc_getDsSlot(dataset);
  if (dsSlot == NULL || (dsSlot->numSeq == 0 && dsSlot->numMesh == 0) ||
      !fc_isFileIOTypeValid(fileType)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // if not writable, make writable
  if (dsSlot->writable == 0) {
    int i, j, k;
    int numSeq, numGlbVar, numGlbSeqVar, numMesh;
    int numSub, numVar, numSeqVar, numMember, *numSteps;
    FC_Sequence *sequences;
    _FC_SeqSlot* seqSlot;
    FC_Mesh* meshes;
    _FC_MeshSlot* meshSlot;
    FC_Subset* subsets;
    _FC_SubSlot* subSlot;
    FC_Variable *glbVars, **glbSeqVars, *variables, **seqVars;
    _FC_VarSlot* varSlot;
    double* coords;
    int *conns, *ids;
    void* data;
    // Force loading of all data & set to uncommited
    fc_getGlobalVariables(dataset, &numGlbVar, &glbVars);
    for (i = 0; i < numGlbVar; i++) {
      fc_getVariableDataPtr(glbVars[i], &data);
      varSlot = _fc_getVarSlot(glbVars[i]);
      varSlot->header.committed = 0;
    }
    free(glbVars);
    fc_getGlobalSeqVariables(dataset, &numGlbSeqVar, &numSteps, &glbSeqVars);
    for (i = 0; i < numGlbSeqVar; i++) {
      for (j = 0; j < numSteps[i]; j++) {
        fc_getVariableDataPtr(glbSeqVars[i][j], &data);
        varSlot = _fc_getVarSlot(glbSeqVars[i][j]);
        varSlot->header.committed = 0;
      }
      free(glbSeqVars[i]);
    }
    free(numSteps);
    free(glbSeqVars);
    fc_getSequences(dataset, &numSeq, &sequences);
    for (i = 0; i < numSeq; i++) {
      fc_getSequenceCoordsPtr(sequences[i], &data);
      seqSlot = _fc_getSeqSlot(sequences[i]);
      seqSlot->header.committed = 0;
    }
    fc_getMeshes(dataset, &numMesh, &meshes);
    for (i = 0; i < numMesh; i++) {
      fc_getMeshCoordsPtr(meshes[i], &coords);
      fc_getMeshElementConnsPtr(meshes[i], &conns);
      fc_getSubsets(meshes[i], &numSub, &subsets);
      for (j = 0; j < numSub; j++) {
     fc_getSubsetMembersAsArray(subsets[j], &numMember, &ids);
     free(ids);
     subSlot = _fc_getSubSlot(subsets[j]);
     subSlot->header.committed = 0;
      }
      free(subsets);
      fc_getVariables(meshes[i], &numVar, &variables);
      for (j = 0; j < numVar; j++) {
     fc_getVariableDataPtr(variables[j], &data);
     varSlot = _fc_getVarSlot(variables[j]);
     varSlot->header.committed = 0;
      }
      free(variables);
      fc_getSeqVariables(meshes[i], &numSeqVar, &numSteps, &seqVars);
      for (j = 0; j < numSeqVar; j++) {
     for (k = 0; k < numSteps[j]; k++) {
       fc_getVariableDataPtr(seqVars[j][k], &data);
       varSlot = _fc_getVarSlot(seqVars[j][k]);
       varSlot->header.committed = 0;
     }
     free(seqVars[j]);
      }
      free(numSteps);
      free(seqVars);
      meshSlot = _fc_getMeshSlot(meshes[i]);
      meshSlot->header.committed = 0;
    }
    free(sequences);
    free(meshes);
    dsSlot->header.committed = 0;
    // reset to look like a created dataset
    rc = _fc_closeDataset(dataset);
    if (rc != FC_SUCCESS)
      return rc;
    dsSlot->writable = 1;
  }
  return fc_writeDataset(dataset, filename, fileType);
}
FC_ReturnCode fc_writeDataset (FC_Dataset dataset, char * filename, FC_FileIOType fileType)
Write a dataset.
Description:
Currently, only a created dataset can be written; the function cannot update changes to a dataset read from disk. To save changes to a dataset that has been read to disk, or already written, use fc_rewriteDataset().
Empty subsets do not get written.
Modifications:
2003-NOV-11 WSK Created.
7/13/2005 WSD Moved to fileio.c.
7/13/2005 WSD Made into a wrapper (old guts are now _fc_writeSAFDataset)
10/15/2007 ACG exodus is now default file type as saf is removed
Parameters:
dataset the dataset to write
filename the filename to write to
fileType the file type to write
Definition at line 1706 of file fileio.c.
References _fc_getDsSlot(), _fc_writeExodusDataset(), FC_ERROR, FC_FILE_IO_ERROR, FC_FT_EXODUS, FC_FT_LSDYNA, FC_FT_NONE, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isFileIOTypeValid(), fc_printfErrorMessage, fc_printfLogMessage, _FC_DsSlot::header, _FC_SlotHeader::name, _FC_DsSlot::numMesh, _FC_DsSlot::numSeq, and _FC_DsSlot::writable.
Referenced by fc_rewriteDataset(), fc_saveSkeleton(), and main().
  {
  _FC_DsSlot* dsSlot;
  // check input
  dsSlot = _fc_getDsSlot(dataset);
  if (dsSlot == NULL || dsSlot->writable == 0 ||
      (dsSlot->numSeq == 0 && dsSlot->numMesh == 0) ||
      !fc_isFileIOTypeValid(fileType)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Writing dataset '%s'", dsSlot->header.name);
  // if no type, choose one
  if (fileType == FC_FT_NONE)
    fileType = FC_FT_EXODUS;
  // Call format specific writers
  switch (fileType) {
  case FC_FT_EXODUS:
#ifdef HAVE_EXODUS
    return _fc_writeExodusDataset(dataset, filename);
#else
    fc_printfErrorMessage("Exodus module not available");
    return FC_FILE_IO_ERROR;
#endif
  case FC_FT_LSDYNA:
    fc_printfErrorMessage("This installation does not support writing files "
                 "in LS-Dyna format\n");
    return FC_ERROR;
  case FC_FT_NONE: // fall through
    fc_printfErrorMessage("Should never reach this point! should have "
                 "chosen a default format");
    return FC_ERROR;
  }
  // error if reach this point
  fc_printfErrorMessage("Programmer error!: Should never reach this point\n");
  return FC_ERROR;
}