FCLib: (Private)
(Private)
[Sequence]
Data Structures
struct _FC_SeqSlot
Sequence Slot Structure for the Sequence Table.
Functions
void _fc_initSeqSlot (_FC_SeqSlot *seqSlot)
Initialize a sequence slot.
void _fc_releaseSeqSlot (_FC_SeqSlot *seqSlotp)
Release non-necessary resources in a sequence slot.
void _fc_clearSeqSlot (_FC_SeqSlot *seqSlotp)
Clear a sequence slot.
int _fc_getSeqTableSize ()
Get the size of the sequence table.
_FC_SeqSlot * _fc_getNewSeqSlot ()
Get an empty sequence slot from the sequence table.
_FC_SeqSlot * _fc_getSeqSlot (FC_Sequence sequence)
Get a sequence slot from a sequence handle.
_FC_SeqSlot * _fc_getSeqSlotFromID (int seqID)
Get a sequence slot based on ID.
FC_ReturnCode _fc_deleteSeqSlot (FC_Sequence sequence)
Delete the sequence slot associated with the sequence handle.
void _fc_printSeqTable (char *label)
Print the contents of the Sequence Table (seqTable) to stderr.
void _fc_freeSeqTable ()
Free all entries in the sequence table.
Variables
static int seqTableSize = 0
The number of allocated slots in the sequence table.
static _FC_SeqSlot ** seqTable = NULL
The sequence table.
static FC_SortedIntArray seqOpenSlots = { 0, 0, 0 }
The list of unused slots in the sequence table.
Function Documentation
void _fc_clearSeqSlot (_FC_SeqSlot * seqSlotp)
Clear a sequence slot.
Description:
Releases all dynamically allocated resources in a sequence, and reinitializes all members.
Modifications:
2003-APR-17 W Koegler Created
2003-APR-31 W Koegler Made more comprehensive
Parameters:
seqSlotp input - qtable pointer
Definition at line 2069 of file sequence.c.
References _fc_clearSlotHeader(), _fc_initSeqSlot(), _fc_releaseSeqSlot(), and _FC_SeqSlot::header.
Referenced by _fc_deleteSeqSlot(), and _fc_freeSeqTable().
  {
  if (seqSlotp != NULL) {
    // release big data
    _fc_releaseSeqSlot(seqSlotp);
    // free other dynamic arrays, if any
    // clear table header
    _fc_clearSlotHeader(&seqSlotp->header);
    // reinit
    _fc_initSeqSlot(seqSlotp);
  }
}
FC_ReturnCode _fc_deleteSeqSlot (FC_Sequence sequence)
Delete the sequence slot associated with the sequence handle.
Description:
This routine clears the dynamic data in the slot and then deletes the slot from the table.
Modifications:
12/20/2005 WSD. Created.
Parameters:
sequence input - sequence
Definition at line 2189 of file sequence.c.
References _fc_clearSeqSlot(), _fc_deleteSlot(), _fc_getSeqSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, _FC_SeqSlot::header, seqTableSize, and _FC_SlotHeader::slotID.
Referenced by fc_deleteSequence().
  {
  _FC_SeqSlot* seqSlot;
  seqSlot = _fc_getSeqSlot(sequence);
  if (seqSlot == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // do it
  _fc_clearSeqSlot(seqSlot);
  return _fc_deleteSlot(seqSlot->header.slotID, seqTableSize,
               (_FC_SlotHeader**)seqTable, &seqOpenSlots);
}
void _fc_freeSeqTable (void)
Free all entries in the sequence table.
Description:
This should only be called after making sure that all slots have been cleared.
Modifications:
05/21/04 WSK Created.
Definition at line 2274 of file sequence.c.
References _fc_clearSeqSlot(), fc_freeSortedIntArray(), and seqTableSize.
Referenced by fc_finalLibrary().
{
  int i;
  for (i = 0; i < seqTableSize; i++) {
    _fc_clearSeqSlot(seqTable[i]);
    free(seqTable[i]);
  }
  free(seqTable);
  fc_freeSortedIntArray(&seqOpenSlots);
  seqTableSize = 0;
  seqTable = NULL;
}
_FC_SeqSlot* _fc_getNewSeqSlot (void)
Get an empty sequence slot from the sequence table.
Description:
Will return a new slot or NULL. A NULL means a memory error occurred.
Modifications:
2003-MAY-01 W Koegler Created
12/08/03 WSK Changed because changed XTables from arrays of slots to arrays of handles to slots. The _fc_new_XSlot() routines do not call a common helper routine anymore.
5/11/04 WSK Moved common code from _fc_getNewDsSlot(), _fc_getNewSeqSlot(), etc to _fc_getNewSlot().
Definition at line 2113 of file sequence.c.
References _fc_getNewSlot(), _fc_initSeqSlot(), and seqTableSize.
Referenced by fc_createSequence().
{
  _FC_SeqSlot* seqSlot;
  seqSlot = (_FC_SeqSlot*) _fc_getNewSlot(&seqTableSize,
                           (_FC_SlotHeader***)&seqTable,
                           &seqOpenSlots, sizeof(_FC_SeqSlot));
  _fc_initSeqSlot(seqSlot);
  return seqSlot;
}
_FC_SeqSlot* _fc_getSeqSlot (FC_Sequence sequence)
Get a sequence slot from a sequence handle.
Description: g The slot id of the sequence handle is used to find the the slot in the sequence table. The identity is then verified by checking that the slot and the handle's uIDs are the same. On success, a pointer to the slot is returned. Otherwise a NULL pointer is returned.
Modifications:
2003-OCT-19 WSK Created to replace using _fc_checkhandle and GET_ID for better type checking (using pointer's to slots is less bug prone than lot's of xxxTable[xxxID] references).
05/25/04 WSK Changed to call new _fc_isHandleValid common to all tables.
Parameters:
sequence input - sequence
Definition at line 2142 of file sequence.c.
References _fc_isHandleValid(), seqTableSize, FC_Sequence::slotID, and FC_Sequence::uID.
Referenced by _fc_deleteSeqSlot(), _fc_loadExodusDataset(), _fc_readExodusSequenceCoords(), _fc_readSequenceCoords(), fc_changeSequenceName(), fc_copyDataset(), fc_copyGlobalSeqVariable(), fc_copySeqSubset(), fc_copySequence(), fc_copySeqVariable(), fc_createGlobalSeqVariable(), fc_createSeqSubset(), fc_createSeqVariable(), fc_deleteSequence(), fc_getClosestSequenceValue(), fc_getDatasetFromSequence(), fc_getSequenceCoordsAsDataType(), fc_getSequenceCoordsPtr(), fc_getSequenceDataType(), fc_getSequenceInfo(), fc_getSequenceMinMaxMono(), fc_getSequenceName(), fc_getSequenceNumStep(), fc_getSequenceSpacingMinMaxMeanSdev(), fc_isSeqSubsetValid(), fc_isSeqVariableValid(), fc_printSequence(), fc_releaseSequence(), fc_rewriteDataset(), fc_setSequenceCoords(), fc_setSequenceCoordsPtr(), and fc_shiftAndScaleSequence().
  {
  if (_fc_isHandleValid(sequence.slotID, sequence.uID, seqTableSize,
                        (_FC_SlotHeader**)seqTable))
    return seqTable[sequence.slotID];
  else
    return NULL;
}
_FC_SeqSlot* _fc_getSeqSlotFromID (int seqID)
Get a sequence slot based on ID.
Description:
The _FC_SeqSlot at the requested slotID is returned. This should only be used when you really know that it is the slot you want because there is no checking of the uID like with _fc_getSeqSlot. The only checking is that the slotID is exists in the table and that the uID is > 0 (i.e. it is not empty).
Modifications:
11/27/03 WSK Created so that external routines can index into tables without knowing about them.
05/25/04 WSK Changed to call new _fc_getSlot() common to all tables.
Definition at line 2170 of file sequence.c.
References _fc_getSlot(), and seqTableSize.
Referenced by fc_copyDataset(), fc_getSequenceByName(), and fc_getSequences().
  {
  return (_FC_SeqSlot*) _fc_getSlot(seqID, seqTableSize,
                                    (_FC_SlotHeader**)seqTable);
}
int _fc_getSeqTableSize (void)
Get the size of the sequence table.
Modifications:
05/21/04 WSK Created.
Definition at line 2093 of file sequence.c.
References seqTableSize.
{
  return seqTableSize;
}
void _fc_initSeqSlot (_FC_SeqSlot * seqSlot)
Initialize a sequence slot.
Modifications: APR-30-2003 W Koegler Created.
Parameters:
seqSlot input - the qtable slot to initialize
Definition at line 2021 of file sequence.c.
References _fc_initSlotHeader(), _FC_SeqSlot::coords, _FC_SeqSlot::datatype, _FC_SeqSlot::ds, FC_DT_UNKNOWN, FC_NULL_DATASET, _FC_SeqSlot::header, and _FC_SeqSlot::numStep.
Referenced by _fc_clearSeqSlot(), and _fc_getNewSeqSlot().
  {
  if (seqSlot != NULL) {
    _fc_initSlotHeader(&seqSlot->header);
    seqSlot->ds = FC_NULL_DATASET;
    seqSlot->numStep = 0;
    seqSlot->datatype = FC_DT_UNKNOWN;
    seqSlot->coords = NULL;
  }
}
void _fc_printSeqTable (char * label)
Print the contents of the Sequence Table (seqTable) to stderr.
Description:
Prints the contents of the Sequence Table in a human readable form. It takes a string to use as a label for this print out of the table. Pass NULL if you don't want a label.
Modifications:
Nancy Collins Created.
2003-NOV-13 WSK Fixed up.
Parameters:
label Input - label for this version the table (without a trailing \n) pass NULL if no label is desired
Definition at line 2220 of file sequence.c.
References _fc_printSlotHeader(), _FC_SeqSlot::coords, _FC_SeqSlot::datatype, _FC_SeqSlot::ds, fc_getDataTypeText(), _FC_SeqSlot::header, _FC_SeqSlot::numStep, seqTableSize, FC_Dataset::slotID, TABLE_DIVIDER_STRING, and FC_Dataset::uID.
  {
  int i;
  _FC_SeqSlot* seqSlot;
  // print table heading
  fprintf(stderr, TABLE_DIVIDER_STRING);
  fprintf(stderr, "Sequence Table (seqTable):\n");
  if (label != NULL)
    fprintf(stderr, "%s\n", label);
  fprintf(stderr, TABLE_DIVIDER_STRING);
  fflush(NULL);
  // We're done if it's empty
  if (seqTableSize < 1) {
    fprintf(stderr, "(empty)\n");
    fprintf(stderr, "\n");
    fflush(NULL);
    return;
  }
  // print contents for each slot
  for (i = 0; i < seqTableSize; i++) {
    seqSlot = seqTable[i];
    fprintf(stderr, "%3d: %s\n", i, (seqSlot) ? "exists" : "NULL");
    if (seqSlot == NULL)
      continue;
    _fc_printSlotHeader(seqSlot->header);
    fprintf(stderr, "     FC_Dataset = { %d, %d }\n",
            seqSlot->ds.slotID, seqSlot->ds.uID);
    fprintf(stderr, "     numStep = %d, datatype = %s, coords = %s\n",
            seqSlot->numStep, fc_getDataTypeText(seqSlot->datatype),
            (seqSlot->coords) ? "exists" : "NULL");
  }
  fprintf(stderr, "\n");
  fflush(NULL);
  return;
}
void _fc_releaseSeqSlot (_FC_SeqSlot * seqSlotp)
Release non-necessary resources in a sequence slot.
Description:
Releases the coordinates.
Modifications: 2003-APR-17 W Koegler Created
Parameters:
seqSlotp input - qtable pointer
Definition at line 2044 of file sequence.c.
References _FC_SeqSlot::coords.
Referenced by _fc_clearSeqSlot().
  {
  // release big data
  if (seqSlotp->coords)
    free(seqSlotp->coords);
  seqSlotp->coords = NULL;
  return;
}
Variable Documentation
FC_SortedIntArray seqOpenSlots = { 0, 0, 0 } [static]
The list of unused slots in the sequence table.
Definition at line 96 of file sequence.c.
_FC_SeqSlot** seqTable = NULL [static]
The sequence table.
Definition at line 91 of file sequence.c.
int seqTableSize = 0 [static]
The number of allocated slots in the sequence table.
Definition at line 86 of file sequence.c.
Referenced by _fc_deleteSeqSlot(), _fc_freeSeqTable(), _fc_getNewSeqSlot(), _fc_getSeqSlot(), _fc_getSeqSlotFromID(), _fc_getSeqTableSize(), _fc_printSeqTable(), and fc_isSequenceValid().