FCLib: (Private)
(Private)
[Variable]
Data Structures
struct _FC_VarSlot
Variable Slot Structure for the Variable Table.
Functions
void _fc_initVarSlot (_FC_VarSlot *varSlot)
Initialize a variable slot.
void _fc_releaseVarSlot (_FC_VarSlot *varSlotp)
Release non-necessary resources in a variable slot.
void _fc_clearVarSlot (_FC_VarSlot *varSlotp)
Clear a variable slot.
int _fc_getVarTableSize ()
Get the size of the variable table.
_FC_VarSlot * _fc_getNewVarSlot ()
Get an empty variable slot from the variable table.
_FC_VarSlot * _fc_getVarSlot (FC_Variable variable)
Get a variable slot from a variable handle.
_FC_VarSlot * _fc_getVarSlotFromID (int varID)
Get a variable slot based on ID.
FC_ReturnCode _fc_deleteVarSlot (FC_Variable variable)
Delete the variable slot associated with the variable handle.
void _fc_printVarTable (char *label)
Print the contents of the Variable Table (varTable) to stderr.
void _fc_freeVarTable ()
Free all entries in the variable table.
FC_ReturnCode _fc_getNextComponentExtension (unsigned int *state, unsigned int *lastCompInGuess, unsigned int *lastCompInSearch, char *extension)
Get a common component extension for combining vars.
Variables
static int varTableSize = 0
The number of allocated slots in the variable table.
static _FC_VarSlot ** varTable = NULL
The variable table.
static FC_SortedIntArray varOpenSlots = { 0, 0, 0 }
The list of unused slots in the variable table.
Function Documentation
void _fc_clearVarSlot (_FC_VarSlot * varSlotp)
Clear a variable slot.
Description:
Releases all dynamically allocated resources in a variable, and reinitializes all members.
Modifications:
Aug 6, 2002 W Koegler Created
2003-APR-31 W Koegler Made more comprehensive
Parameters:
varSlotp input - vtable pointer
Definition at line 6462 of file variable.c.
References _fc_clearSlotHeader(), _fc_initVarSlot(), _fc_releaseVarSlot(), and _FC_VarSlot::header.
Referenced by _fc_deleteVarSlot(), and _fc_freeVarTable().
  {
  if (varSlotp != NULL) {
    // free big data
    _fc_releaseVarSlot(varSlotp);
    // free other dynamic arrays, if any
    // clear table header
    _fc_clearSlotHeader(&varSlotp->header);
    // reinit
    _fc_initVarSlot(varSlotp);
  }
}
FC_ReturnCode _fc_deleteVarSlot (FC_Variable variable)
Delete the variable slot associated with the variable handle.
Description:
This routine clears the dynamic data in the slot and then deletes the slot from the table.
Modifications:
12/20/2005 WSD. Created.
Parameters:
variable input - variable
Definition at line 6584 of file variable.c.
References _fc_clearVarSlot(), _fc_deleteSlot(), _fc_getVarSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, _FC_VarSlot::header, _FC_SlotHeader::slotID, and varTableSize.
Referenced by fc_deleteSeqVariable(), and fc_deleteVariable().
  {
  _FC_VarSlot* varSlot;
  varSlot = _fc_getVarSlot(variable);
  if (varSlot == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // do it
  _fc_clearVarSlot(varSlot);
  return _fc_deleteSlot(varSlot->header.slotID, varTableSize,
               (_FC_SlotHeader**)varTable, &varOpenSlots);
}
void _fc_freeVarTable (void)
Free all entries in the variable table.
Description:
This should only be called after making sure that all slots have been cleared.
Modifications:
05/21/04 WSK Created.
Definition at line 6677 of file variable.c.
References _fc_clearVarSlot(), fc_freeSortedIntArray(), and varTableSize.
Referenced by fc_finalLibrary().
{
  int i;
  for (i = 0; i < varTableSize; i++) {
    _fc_clearVarSlot(varTable[i]);
    free(varTable[i]);
  }
  free(varTable);
  fc_freeSortedIntArray(&varOpenSlots);
  varTableSize = 0;
  varTable = NULL;
}
_FC_VarSlot* _fc_getNewVarSlot (void)
Get an empty variable slot from the variable table.
Description:
Will return a new slot or NULL. A NULL means a memory error occurred.
Modifications:
2003-MAY-01 W Koegler Created
12/08/03 WSK Changed because changed XTables from arrays of slots to arrays of handles to slots. The _fc_new_XSlot() routines do not call a common helper routine anymore.
5/11/04 WSK Moved common code from _fc_getNewDsSlot(), _fc_getNewSeqSlot(), etc to _fc_getNewSlot().
Definition at line 6506 of file variable.c.
References _fc_getNewSlot(), _fc_initVarSlot(), and varTableSize.
Referenced by fc_createGlobalSeqVariable(), fc_createGlobalVariable(), fc_createSeqVariable(), and fc_createVariable().
{
  _FC_VarSlot* varSlot;
  varSlot = (_FC_VarSlot*) _fc_getNewSlot(&varTableSize,
                           (_FC_SlotHeader***)&varTable,
                           &varOpenSlots, sizeof(_FC_VarSlot));
  _fc_initVarSlot(varSlot);
  return varSlot;
}
FC_ReturnCode _fc_getNextComponentExtension (unsigned int * state, unsigned int * lastCompInGuess, unsigned int * lastCompInSearch, char * extension)
Get a common component extension for combining vars.
Description:
This function is used when searching for single-component vars/seqVars that should be combined into a multicomponent var/seqVar. This function holds a table of common extensions and is designed to generate several permutations of the extension format to make guessing the component names easier. A state variable is passed to the function in order to keep track of where the search is. The idea is that a user keeps calling this function until a good match is found or the function runs out of guesses.
This function produces one component extension at a time, sequentially (ie, for the first extension guess, it gives _x, _y, and then _z). The lastCompInGuess variable indicates that the result is the last component of a particular extension. The lastCompInSearch indicates that the result is the last component of the last possible guess.
The user can find out info about the guesses by passing NULL into state. In this case, lastCompInGuess returns the maximum number of characters in an individual extension, while lastCompInSearch returns the largest number of components a guess can have.
Modifications:
12/12/2007 CDU Created.
Parameters:
state input - state information retained between calls
lastCompInGuess output - flag indicating this is the last component of a guess
lastCompInSearch output - flag indicating this is the last component of last guess
extension input - pre-allocated array where extension is written
Definition at line 6722 of file variable.c.
References FC_ERROR, FC_INPUT_ERROR, fc_printfErrorMessage, and FC_SUCCESS.
Referenced by fc_getSeqVariableComponentsByName(), and fc_getVariableComponentsByName().
 {
  //Extension Table: If you want to add more extension labels to the below
  //table, make sure you do the following:
  // - Update num_rows to reflect number of different extension patterns
  // - Update num_cols to reflect max number of components in a pattern
  // - Update max_ext_len if your extension symbols become longer
  // - Insert longer vectors first: Make sure tuvw comes before
  //    tuv so longer number of components are found first
  const unsigned int num_rows    = 6; //How many rows in table below
  const unsigned int num_cols    = 4; //How many columns in table below
  const unsigned int num_rounds  = 6; //All underline/capital letter cases
  const unsigned int max_ext_len = 2+2+1; //underscores + extension + \0
  char *vector_endings[][4] = { {"x",  "y",  "z",  NULL },
                    {"x",  "y",  NULL, NULL },
                    {"c0", "c1", "c2", "c3" },
                    {"c0", "c1", "c2", NULL },
                    {"t",  "u",  "v",  "w"  },
                    {"t",  "u",  "v",  NULL } };
  char *underscore, *s;
  int upper;
  unsigned int round, row, col;
  //Always must have at least these two return pointers
  if((!lastCompInGuess)||(!lastCompInSearch)){
    fc_printfErrorMessage("Null variable in input");
    return FC_INPUT_ERROR;
  }
  //When user passes NULL in for state, they're actually querying to
  //see what the dimensions of the table are. Just pass these back
  if(!state){
    *lastCompInGuess  = max_ext_len;
    *lastCompInSearch = num_cols;
    return FC_SUCCESS;
  }
  //Unpack the state
  col   = (*state>> 0) & 0x0FF;
  row   = (*state>> 8) & 0x0FF;
  round = (*state>>16) & 0x0FF;
  //printf("Working on round/row/col : %d/%d/%d\n", round, row, col);
  //Check bounds
  if( (round >= num_rounds) || (row >= num_rows) || (col >= num_cols) ||
      (!vector_endings[row][col])){
    fc_printfErrorMessage("Input boundary check failure");
    return FC_INPUT_ERROR;
  }
  //The user may not want to actually retrieve the extension. They may
  //just be looping through the components in a row because one of the
  //components wasn't found.
  if(extension){
    switch(round){
    case 0: underscore="_";  upper=0; break;
    case 1: underscore="_";  upper=1; break;
    case 2: underscore="__"; upper=0; break;
    case 3: underscore="__"; upper=1; break;
    case 4: underscore="";   upper=1; break;
    case 5: underscore="";   upper=0; break;
    default:
      fc_printfErrorMessage("Bad case statement?");
      return FC_ERROR;
    }
    snprintf(extension, max_ext_len, "%s%s",underscore,vector_endings[row][col]);
    if(upper){ //Convert to uppercase
      s=extension;
      while(*s!='\0'){
     *s = toupper(*s);
     s++;
      }
    }
  }
  //Done with this entry: Update the state
  col++;
  *lastCompInGuess=0;
  *lastCompInSearch=0;
  if((col==num_cols) || (!vector_endings[row][col])){
    //End of column
    *lastCompInGuess=1;
    col=0;
    row++;
    if(row==num_rows){
      //End of rows
      row=0;
      round++;
      if(round==num_rounds){
     //End of search
     *lastCompInSearch=1;
      }
    }
  }
  //Pack the state again
  *state = (round<<16) | (row<<8) | (col);
  return FC_SUCCESS;
}
_FC_VarSlot* _fc_getVarSlot (FC_Variable variable)
Get a variable slot from a variable handle.
Description:
The slot id of the variable handle is used to find the the slot in the variable table. The identity is then verified by checking that the slot and the handle's uIDs are the same. On success, a pointer to the slot is returned. Otherwise a NULL pointer is returned.
Modifications:
2003-OCT-19 WSK Created to replace using _fc_checkhandle and GET_ID for better type checking (using pointer's to slots is less bug prone than lot's of xxxTable[xxxID] references).
05/25/04 WSK Changed to call new _fc_isHandleValid common to all tables.
Parameters:
variable input - variable
Definition at line 6536 of file variable.c.
References _fc_isHandleValid(), FC_Variable::slotID, FC_Variable::uID, and varTableSize.
Referenced by _fc_deleteVarSlot(), _fc_exo_seqVar_cmp(), _fc_exo_seqVar_meshID_cmp(), _fc_loadExodusDataset(), _fc_loadLSDynaDataset(), _fc_readExodusAttributeData(), _fc_readExodusOneStepVariableData(), _fc_readExodusVariableData(), _fc_readLSDynaVariableData(), _fc_readVariableData(), _fc_writeExodusDataset(), fc_centeredWindowAverage(), fc_centeredWindowAverage_Time(), fc_changeSeqVariableName(), fc_changeVariableName(), fc_constOperatorSeqVar(), fc_constOperatorVar(), fc_convertVariablesToSeqVariable(), fc_copyGlobalSeqVariable(), fc_copyGlobalVariable(), fc_copySeqVariable(), fc_copySeqVariableStepFromRegionMesh(), fc_copySeqVariableWithNewAssociation(), fc_copyVariable(), fc_copyVariableFromRegionMesh(), fc_copyVariableToRegionMesh(), fc_copyVariableWithNewAssociation(), fc_deleteSeqVariable(), fc_deleteVariable(), fc_dimensionlessAreaBetweenCurves(), fc_euclideanDistanceBetweenCurves(), fc_firstDerivative_REA(), fc_getDatasetFromVariable(), fc_getMeshFromVariable(), fc_getSequenceFromSeqVariable(), fc_getSeqVariableDataPointSlice(), fc_getSeqVariableSeriesMeanSdev(), fc_getSeqVariableSeriesMinMax(), fc_getSeqVariableSeriesSum(), fc_getVariableAssociationType(), fc_getVariableDataAsDataType(), fc_getVariableDataPtr(), fc_getVariableDataType(), fc_getVariableInfo(), fc_getVariableMathType(), fc_getVariableName(), fc_getVariableNumComponent(), fc_getVariableNumDataPoint(), fc_integral_TR(), fc_isSeqVariableValid(), fc_isVariableGlobal(), fc_leadingWindowAverage(), fc_leadingWindowAverage_Time(), fc_linearInterpolation(), fc_linearLeastSquares(), fc_normalForm(), fc_operatorSeqVar(), fc_operatorVar(), fc_printSeqVariableRange(), fc_printVariable(), fc_releaseSeqVariable(), fc_releaseVariable(), fc_rewriteDataset(), fc_seqConstOperatorSeqVar(), fc_seqVarBinaryFunctionConstSeqVar(), fc_seqVarBinaryFunctionSeqConstSeqVar(), fc_seqVarBinaryFunctionSeqVarConst(), fc_seqVarBinaryFunctionSeqVarSeqConst(), fc_seqVarBinaryFunctionSeqVarSeqVar(), fc_seqVarBinaryFunctionSeqVarVar(), fc_seqVarBinaryFunctionVarSeqVar(), fc_seqVarOperatorConst(), fc_seqVarOperatorSeqConst(), fc_seqVarOperatorSeqVar(), fc_seqVarOperatorVar(), fc_seqVarUnaryFunction(), fc_setVariableData(), fc_setVariableDataPtr(), fc_varBinaryFunctionConstVar(), fc_varBinaryFunctionVarConst(), fc_varBinaryFunctionVarVar(), fc_varOperatorConst(), fc_varOperatorSeqVar(), fc_varOperatorVar(), and fc_varUnaryFunction().
  {
  if (_fc_isHandleValid(variable.slotID, variable.uID, varTableSize,
                        (_FC_SlotHeader**)varTable))
    return varTable[variable.slotID];
  else
    return NULL;
}
_FC_VarSlot* _fc_getVarSlotFromID (int varID)
Get a variable slot based on ID.
Description:
The _FC_VarSlot at the requested slotID is returned. This should only be used when you really know that it is the slot you want because there is no checking of the uID like with _fc_getVarSlot. The only checking is that the slotID is exists in the table and that the uID is > 0 (i.e. it is not empty).
Modifications:
11/27/03 WSK Created so that external routines can index into tables without knowing about them.
05/25/04 WSK Changed to call new _fc_getSlot() common to all tables.
Definition at line 6565 of file variable.c.
References _fc_getSlot(), and varTableSize.
Referenced by fc_copyDataset(), fc_deleteSequence(), fc_getGlobalSeqVariableByName(), fc_getGlobalSeqVariables(), fc_getGlobalVariableByName(), fc_getGlobalVariables(), fc_getMeshCoordsAsVariable(), fc_getSeqVariableByName(), fc_getSeqVariables(), fc_getVariableByName(), and fc_getVariables().
  {
  return (_FC_VarSlot*) _fc_getSlot(varID, varTableSize,
                                   (_FC_SlotHeader**)varTable);
}
int _fc_getVarTableSize (void)
Get the size of the variable table.
Modifications:
05/21/04 WSK Created.
Definition at line 6486 of file variable.c.
References varTableSize.
{
  return varTableSize;
}
void _fc_initVarSlot (_FC_VarSlot * varSlot)
Initialize a variable slot.
Modifications: APR-30-2003 W Koegler Created.
Parameters:
varSlot input - the vtable slot to initialize
Definition at line 6408 of file variable.c.
References _fc_initSlotHeader(), _FC_VarSlot::assoc, _FC_VarSlot::data, _FC_VarSlot::datatype, _FC_VarSlot::ds, FC_AT_UNKNOWN, FC_DT_UNKNOWN, FC_MT_UNKNOWN, FC_NULL_DATASET, FC_NULL_MESH, FC_NULL_SEQUENCE, _FC_VarSlot::header, _FC_VarSlot::mathtype, _FC_VarSlot::mesh, _FC_VarSlot::numComponent, _FC_VarSlot::numDataPoint, _FC_VarSlot::sequence, and _FC_VarSlot::stepID.
Referenced by _fc_clearVarSlot(), and _fc_getNewVarSlot().
  {
  if (varSlot != NULL) {
    _fc_initSlotHeader(&varSlot->header);
    varSlot->ds = FC_NULL_DATASET;
    varSlot->mesh = FC_NULL_MESH;
    varSlot->sequence = FC_NULL_SEQUENCE;
    varSlot->stepID = -1;
    varSlot->numDataPoint = 0;
    varSlot->numComponent = 0;
    varSlot->mathtype = FC_MT_UNKNOWN;
    varSlot->datatype = FC_DT_UNKNOWN;
    varSlot->assoc = FC_AT_UNKNOWN;
    varSlot->data = NULL;
  }
}
void _fc_printVarTable (char * label)
Print the contents of the Variable Table (varTable) to stderr.
Description:
Prints the contents of the Variable Table in a human readable form. It takes a string to use as a label for this print out of the table. Pass NULL if you don't want a label.
Modifications:
Nancy Collins Created.
2003-NOV-13 WSK Fixed up.
Parameters:
label Input - label for this version the table (without a trailing \n) pass NULL if no label is desired
Definition at line 6615 of file variable.c.
References _fc_printSlotHeader(), _FC_VarSlot::assoc, _FC_VarSlot::data, _FC_VarSlot::datatype, _FC_VarSlot::ds, fc_getAssociationTypeText(), fc_getDataTypeText(), fc_getMathTypeText(), _FC_VarSlot::header, _FC_VarSlot::mathtype, _FC_VarSlot::mesh, _FC_VarSlot::numComponent, _FC_VarSlot::numDataPoint, _FC_VarSlot::sequence, FC_Sequence::slotID, FC_Mesh::slotID, FC_Dataset::slotID, _FC_VarSlot::stepID, TABLE_DIVIDER_STRING, FC_Sequence::uID, FC_Mesh::uID, FC_Dataset::uID, and varTableSize.
  {
  int i;
  _FC_VarSlot* varSlot;
  // print table heading
  fprintf(stderr, TABLE_DIVIDER_STRING);
  fprintf(stderr, "Variable Table (varTable):\n");
  if (label != NULL)
    fprintf(stderr, "%s\n", label);
  fprintf(stderr, TABLE_DIVIDER_STRING);
  fflush(NULL);
  // We're done if it's empty
  if (varTableSize < 1) {
    fprintf(stderr, "(empty)\n");
    fprintf(stderr, "\n");
    fflush(NULL);
    return;
  }
  // print contents for each slot
  for (i = 0; i < varTableSize; i++) {
    varSlot = varTable[i];
    fprintf(stderr, "%3d: %s\n", i, (varSlot) ? "exists" : "NULL");
    if (varSlot == NULL)
      continue;
    _fc_printSlotHeader(varSlot->header);
    fprintf(stderr, "     FC_Dataset = { %d, %d }, FC_Mesh = { %d, %d }\n",
            varSlot->ds.slotID, varSlot->ds.uID,
         varSlot->mesh.slotID, varSlot->mesh.uID);
    fprintf(stderr, "     FC_Sequence = { %d, %d }, stepID = %d\n",
            varSlot->sequence.slotID, varSlot->sequence.uID, varSlot->stepID);
    fprintf(stderr, "     numDataPoint = %d, numComponent = %d\n",
            varSlot->numDataPoint, varSlot->numComponent);
    fprintf(stderr, "     association = %s, mathtype = %s\n",
            fc_getAssociationTypeText(varSlot->assoc),
            fc_getMathTypeText(varSlot->mathtype));
    fprintf(stderr, "     datatype = %s, data = %s\n",
            fc_getDataTypeText(varSlot->datatype),
            (varSlot->data) ? "exists" : "NULL");
  }
  fprintf(stderr, "\n");
  fflush(NULL);
  return;
}
void _fc_releaseVarSlot (_FC_VarSlot * varSlotp)
Release non-necessary resources in a variable slot.
Description:
Releases the data values.
Modifications: Aug 6, 2002 W Koegler Created
Parameters:
varSlotp input - vtable pointer
Definition at line 6437 of file variable.c.
References _FC_VarSlot::data.
Referenced by _fc_clearVarSlot().
  {
    // release big data
    if (varSlotp->data) {
      free(varSlotp->data);
      varSlotp->data = NULL;
    }
    return;
}
Variable Documentation
FC_SortedIntArray varOpenSlots = { 0, 0, 0 } [static]
The list of unused slots in the variable table.
Definition at line 106 of file variable.c.
_FC_VarSlot** varTable = NULL [static]
The variable table.
Definition at line 101 of file variable.c.
int varTableSize = 0 [static]
The number of allocated slots in the variable table.
Definition at line 96 of file variable.c.
Referenced by _fc_deleteVarSlot(), _fc_freeVarTable(), _fc_getNewVarSlot(), _fc_getVarSlot(), _fc_getVarSlotFromID(), _fc_getVarTableSize(), _fc_printVarTable(), and fc_isVariableValid().