FCLib: Misc Utilities
Misc Utilities
[Utilities]
Defines
#define FC_PI 3.14159265358979323846
Macro that gives value of PI.
Functions
int fc_intCompare (const void *n, const void *m)
Compare two ints.
FC_ReturnCode fc_sortIntArray (int num, int *array)
Sort an int array.
FC_ReturnCode fc_addValueToIntArray (int **array_p, int *num_p, int new_value)
Add a new value to an array of ints.
char * fc_replaceChars (char *in_string, char toBeReplaced, char replaceWith)
Replace occurances of a char in a string.
Define Documentation
#define FC_PI 3.14159265358979323846
Macro that gives value of PI.
Definition at line 174 of file util.h.
Referenced by fc_calcAngleBetweenVectors(), fc_createStressPressureVariables(), and main().
Function Documentation
FC_ReturnCode fc_addValueToIntArray (int ** array_p, int * num_p, int new_value)
Add a new value to an array of ints.
Description:
Given an array, the number of elements in the array, and a new value, append the value to the array. The array is assumed to be dynamically generated and the user is responsibly for freeing it when it is no longer in use. The new value is appended to the end and the count is increased by 1. A return value not equal to 0 indicates a failed malloc and the array and the arguments should remain unchanged.
Modifications:
FEB-13-2002 W Koegler Created.
Definition at line 1001 of file util.c.
References FC_ERROR, fc_getReturnCodeText(), FC_MEMORY_ERROR, fc_printfErrorMessage, and FC_SUCCESS.
{
  int *temp_array;
  // check input
  if (!array_p || !num_p || *num_p < 0)
    return FC_ERROR;
  // copy values & replace array
  temp_array = malloc(sizeof(int)*(*num_p + 1));
  if (!temp_array) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  if (*num_p > 0) {
    memcpy(temp_array, *array_p, sizeof(int)*(*num_p));
    free(*array_p);
  }
  *array_p = temp_array;
  // add new value
  (*array_p)[*num_p] = new_value;
  (*num_p)++;
  return FC_SUCCESS;
}
int fc_intCompare (const void * n, const void * m)
Compare two ints.
Description:
Compares two ints and returns 1 if the first is greater, 0 if they are equal, and -1 if the 2nd is greater. Return values are what routines like qsort expect.
Modifications:
10/10/2005 WSD. Promoted (used to be inside fc_sortIntArray()).
Definition at line 945 of file util.c.
Referenced by _fc_buildEdgeConns(), _fc_loadLSDynaDataset(), _fc_readNamesFile(), and fc_sortIntArray().
{
  int a = ((const int*)n)[0];
  int b = ((const int*)m)[0];
  if (a > b)
    return 1;
  else if (a < b)
    return -1;
  else
    return 0;
}
char* fc_replaceChars (char * in_string, char toBeReplaced, char replaceWith)
Replace occurances of a char in a string.
Description:
Return a new string (to be freed by the caller) where occurences of a specified char are replaced with another specified char.
For example, fc_replaceChar("hi there!", ' ', '_') returns "hi_there!");
Parameters:
in_string input - input string
toBeReplaced input - char to be replaced
replaceWith input - char to be inserted
Definition at line 1038 of file util.c.
References temp_string.
  {
  size_t i, len;
  char* temp_string;
  // check input
  if (!in_string)
    return NULL;
  // do it
  len = strlen(in_string);
  temp_string = (char*)malloc((len+1)*sizeof(char));
  if (!temp_string)
    return NULL;
  strcpy(temp_string, in_string);
  for (i = 0; i < len; i++)
    if (temp_string[i] == toBeReplaced)
      temp_string[i] = replaceWith;
  // done
  return temp_string;
}
FC_ReturnCode fc_sortIntArray (int num, int * array)
Sort an int array.
Description:
Just a wrapper around qsort and fc_intCompare.
Modifications:
07/01/04 WSK Created.
Parameters:
num input - number of entries in array
array input - the array
Definition at line 968 of file util.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_intCompare(), fc_printfErrorMessage, and FC_SUCCESS.
Referenced by _fc_getVertexIDsWithinBoundingBoxUsingVertexBin(), _fc_getVertexIDsWithinSphereUsingVertexBin(), and fc_convertIntArrayToSortedIntArray().
{
  if (num < 1 || array == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  qsort((void*)array, (size_t)num, sizeof(int), fc_intCompare);
  return FC_SUCCESS;
}