FCLib: Simple Data Objects
Simple Data Objects
[FCLib API]
Detailed Description
Simple Data Objects.
Description:
The majority of these data objects were created to manipulate collections of ids.
Modules
(Private)
Data Structures
struct FC_SortedIntArray
Sorted, exclusive, self-exanding int array.
struct FC_SortedBlobArray
Sorted, exclusive, self-exanding array of data blobs.
Typedefs
typedef double FC_Coords [3]
Coordinates data structure.
typedef double FC_Vector [3]
Vector data structure.
Sorted Int Array Routines
Sorted, exclusive, self-exanding int array.
FC_ReturnCode fc_initSortedIntArray (FC_SortedIntArray *sia)
Initialize a sorted int array.
int fc_isSortedIntArrayValid (FC_SortedIntArray *sia)
Check to see if a sorted int array is valid.
FC_ReturnCode fc_copySortedIntArray (FC_SortedIntArray *sia_src, FC_SortedIntArray *sia_dest)
Copy (deep copy) a sorted int array.
FC_ReturnCode fc_getSortedIntArrayNumValue (FC_SortedIntArray *sia, int *numValue)
Get number of values in sorted int array.
FC_ReturnCode fc_getSortedIntArrayValues (FC_SortedIntArray *sia, int *numValue, int **values)
Get a copy of the values stored in the sorted int array.
FC_ReturnCode fc_getSortedIntArrayValuesInInsertOrder (FC_SortedIntArray *sia, int *numValue, int **values)
Get a copy of the values stored in the sorted array, orderd in the way they were inserted.
int fc_isIntInSortedIntArray (FC_SortedIntArray *sia, int ix)
Query for int in sorted int array.
int fc_addIntToSortedIntArray (FC_SortedIntArray *sia, int ix)
Add an int to a sorted int array.
int fc_addIntArrayToSortedIntArray (FC_SortedIntArray *sia, int num, int *array, int isSorted)
Add an array of ints to a sorted int array.
int fc_deleteIntFromSortedIntArray (FC_SortedIntArray *sia, int ix)
Remove an int from a sorted int array.
int fc_getSortedIntArrayFront (FC_SortedIntArray *sia, int *value)
Get first value in the sorted int array (WARNING: does not check for empty array).
int fc_getSortedIntArrayBack (FC_SortedIntArray *sia, int *value)
Get last value in the sorted int array (WARNING: does not check for empty array).
int fc_popSortedIntArrayFront (FC_SortedIntArray *sia)
Delete the first value in a sorted int array.
int fc_popSortedIntArrayBack (FC_SortedIntArray *sia)
Delete the last value in a sorted int array.
FC_ReturnCode fc_squeezeSortedIntArray (FC_SortedIntArray *sia)
Realloc the sorted int array so it has no extra space.
void fc_freeSortedIntArray (FC_SortedIntArray *sia)
Free the sorted int array's values.
FC_ReturnCode fc_printSortedIntArray (FC_SortedIntArray *sia)
prints the sortedint array
int _fc_qsortCmpInt (const void *a, const void *b)
Initialize a sorted int array.
Sorted Blob Array Routines
Sorted, exclusive, self-exanding array of pointers to data blobs. The array is implemented as an array of pointers (void*) to the objects of interest and do not manage the blobs themselves. The user must also provide a function that compares blobs and returns -1 if the first blob is "less than" the 2nd, 0 if the blobs are equivalent, and 1 if the 2nd glob is greater than first blob (the same as compare functions for qsort).
FC_ReturnCode fc_initSortedBlobArray (FC_SortedBlobArray *sba)
Initialize a sorted blob array.
int fc_isSortedBlobArrayValid (FC_SortedBlobArray *sba)
Check to see if a sorted blob array is valid.
FC_ReturnCode fc_getSortedBlobArrayNumBlob (FC_SortedBlobArray *sba, int *numBlob)
Get number of blobs in sorted blob array.
FC_ReturnCode fc_getSortedBlobArrayBlobs (FC_SortedBlobArray *sba, int *numBlob, void ***blobs)
Get a copy of the blob locations stored in the sorted blob array.
int fc_isBlobInSortedBlobArray (FC_SortedBlobArray *sba, void *blob, int blobCmp(const void *, const void *), void **foundBlob)
Query for blob in sorted blob array.
int fc_addBlobToSortedBlobArray (FC_SortedBlobArray *sba, void *blob, int blobCmp(const void *, const void *))
Add a blob to a sorted blob array.
int fc_deleteBlobFromSortedBlobArray (FC_SortedBlobArray *sba, void *blob, int blobCmp(const void *, const void *), void **deletedBlob)
Remove a blob from a sorted blob array.
FC_ReturnCode fc_squeezeSortedBlobArray (FC_SortedBlobArray *sba)
Realloc the sorted blob array so it has no extra space.
void fc_freeSortedBlobArray (FC_SortedBlobArray *sba)
Free the sorted blob array's values.
Conversion routines
Conversion implies that original data object will be consumed (no longer available) in the process.
int fc_convertIntArrayToSortedIntArray (int num, int *array, int isSorted, FC_SortedIntArray *sia)
Convert int array (no duplicates) to sorted int array.
int fc_convertSortedIntArrayToIntArray (FC_SortedIntArray *sia, int *num, int **array)
Convert sorted int array to array.
FC_ReturnCode fc_createIntArrayFromMask (int numMask, int *mask, int *numArray, int **array)
Create an Int Array from a Mask.
FC_ReturnCode fc_createMaskFromIntArray (int numArray, int *array, int numMask, int **mask)
Create a Mask from an Int Array.
Typedef Documentation
typedef double FC_Coords[3]
Coordinates data structure.
Description:
Structure to hold coordinates. Maximum dimensionality is 3. (This is essentially a double[3] declaration).
Definition at line 68 of file storage.h.
typedef double FC_Vector[3]
Vector data structure.
Description:
Structure to hold a vector, assuming that it originates at the origin. Maximum dimensionality is 3. (This is essentially a double[3] declaration).
Definition at line 81 of file storage.h.
Function Documentation
int _fc_qsortCmpInt (const void * a, const void * b)
Initialize a sorted int array.
Description:
The sia must already have been allocated
Modifications:
06/06/06 ACG Created.
Definition at line 269 of file storage.c.
Referenced by fc_addIntArrayToSortedIntArray(), and fc_getSortedIntArrayValuesInInsertOrder().
{
  if( *((const int *)a) < *((const int *)b) ) return -1;
  if( *((const int *)a) > *((const int *)b) ) return  1;
  return 0;
}
int fc_addBlobToSortedBlobArray (FC_SortedBlobArray * sba, void * blob, int blobCmpconst void *, const void *)
Add a blob to a sorted blob array.
Description:
Add a blob to a sorted blob array. Returns 1 if the blob is added. Returns 0 if the blob was already there. Returns an FC_ReturnCode if there is an error.
Modifications:
08/08/2006 WSD Created.
Parameters:
sba input/output - sortedBlobArray
blob input - blob to add
blobCmp input - the blob comparison function
Definition at line 1115 of file storage.c.
References _fc_addEntryToSortedBlobArray(), _fc_lookupBlobInSortedBlobArray(), and FC_SUCCESS.
Referenced by _fc_readNamesFile(), and _fc_writeExodusDataset().
 {
  FC_ReturnCode rc;
  int foundInt, idx;
  // this call also checks args
  rc = _fc_lookupBlobInSortedBlobArray(sba, blob, blobCmp, &foundInt, &idx);
  if (rc < 0)
    return rc;
  // early return
  if (foundInt == 1)
    return 0;
  // do it (this routine allocates memory if needed)
  rc = _fc_addEntryToSortedBlobArray(sba, idx, blob);
  if (rc != FC_SUCCESS)
    return rc;
  else
    return 1;
}
int fc_addIntArrayToSortedIntArray (FC_SortedIntArray * sia, int num, int * array, int isSorted)
Add an array of ints to a sorted int array.
Description:
Add an array of ints to a sorted int array. Returns the total number of ints added (if all ints already existed, would return zero). Returns an FC_ReturnCode if there is an error.
The extra flag, isSorted, is for performance. A value of 1 means the incoming ints are already sorted (0 means they may not be).
The incoming int array can have repeated values.
Modifications:
2006/07/13 WSD Created.
2008/05/02 CDU Updated to support getting unsorted vals back
Parameters:
sia input/output - sortedIntArray
num input - number of ints to add
array input - the ints to add
isSorted input - flag, 1 = incoming ints are sorted
Definition at line 441 of file storage.c.
References _fc_qsortCmpInt(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSortedIntArrayValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, FC_SortedIntArray::maxNumVal, FC_SortedIntArray::nextTicket, FC_SortedIntArray::numVal, FC_SortedIntArray::tickets, and FC_SortedIntArray::vals.
Referenced by _fc_buildMeshElementNeighborsViaEntity(), _fc_getEdgeNeighbors(), _fc_getFaceNeighbors(), _fc_growNeighborList(), fc_addArrayMembersToSubset(), fc_changeMeshEntityType(), fc_computeTreeDescendantsAncestors(), fc_createSubsetMesh(), fc_getSideNormalMeanSdev(), fc_getSubsetNeighbors(), and fc_groupSelfCorrespond().
 {
  int i, j;
  //int *sortedArray;
  int numAdded;
  int newNum, newMaxNum, *newVals, *newTickets;
  int spacing;
  int *combined;
  // check input
  if (!fc_isSortedIntArrayValid(sia) || num < 0 || (num > 0 && array == NULL)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // early return - empty array
  if (num == 0)
    return 0;
  // sort, if necessary
  if (isSorted) {
    //Since this is already sorted, just use it. We have to use a spacing
    //of one since "combined" isn't really a combination- it's just a
    //pointer to vals.
    spacing = 1;
    combined = array;
  }else {
    //Create a combined block where val and insert id are interleaved
    spacing = 2;
    combined = (int *)malloc(num*2*sizeof(int));
    if(!combined){
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    for(i=0;i<num;i++){
      combined[i*2+0] = array[i]; //value that gets looked at
      combined[i*2+1] = i;
    }
    qsort((void *) combined, num, 2*sizeof(int), _fc_qsortCmpInt );
  }
  // make space for result (will replace current sia->vals)
  newMaxNum = sia->numVal + num;
  newVals = (int*)malloc(newMaxNum*sizeof(int));
  newTickets = (int *)malloc(newMaxNum*sizeof(int));
  if ((newVals == NULL) || (newTickets==NULL)){
    free(newVals);
    free(newTickets);
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  // make new vals
  numAdded = 0;
  newNum = 0;
  i = j = 0;
  while (i < sia->numVal && j < num) {
    if (sia->vals[i] < combined[j*spacing]) {
      //Original array smaller
      newVals[newNum]    = sia->vals[i];
      newTickets[newNum] = sia->tickets[i];
      newNum++;
      i++;
    }
    else if (combined[j*spacing] < sia->vals[i]) {
      //New val is smaller
      newVals[newNum] = combined[j*spacing];
      newTickets[newNum] = sia->nextTicket;          //All new vals start at current ticket
      newTickets[newNum] += (isSorted) ? j : combined[j*2+1]; //Plus their insert id
      newNum++;
      numAdded++;
      j++;
      while ((j < num) && (combined[j*spacing] == combined[(j-1)*spacing])) // skip duplicates
     j++;
    }
    else {
      newVals[newNum] = sia->vals[i];
      newTickets[newNum] = sia->tickets[i];
      newNum++;
      i++;
      j++;
      while ((j < num) && (combined[j*spacing] == combined[(j-1)*spacing])) // skip duplicates
     j++;
    }
  }
  if (i < sia->numVal) {
    //Leftovers in original array
    memcpy(&newVals[newNum],    &sia->vals[i],              (sia->numVal-i)*sizeof(int));
    memcpy(&newTickets[newNum], &sia->tickets[i], (sia->numVal-i)*sizeof(int));
    newNum += sia->numVal-i;
  }
  else if (j < num) {
    //Leftovers in new array
    while (j < num) {
      newVals[newNum]    = combined[j*spacing];
      newTickets[newNum] = sia->nextTicket;          //All new vals start at current ticket
      newTickets[newNum] += (isSorted) ? j : combined[j*2+1]; //Plus their insert id
      newNum++;
      numAdded++;
      j++;
      while ((j < num) && (combined[j*spacing] == combined[(j-1)*spacing])) // skip duplicates
     j++;
    }
  }
  // swap old vals for new
  if (numAdded == 0) {
    free(newVals);
    free(newTickets);
  }
  else {
    assert(sia->nextTicket+num > sia->nextTicket); //Check for overflow
    free(sia->vals);
    free(sia->tickets);
    sia->numVal = newNum;
    sia->maxNumVal = newMaxNum;
    sia->vals = newVals;
    sia->tickets = newTickets;
    sia->nextTicket += num; //must do all of array, even if some unused
  }
  // cleanup after sort, if necessary
  if (!isSorted)
    free(combined);
  return numAdded;
}
int fc_addIntToSortedIntArray (FC_SortedIntArray * sia, int ix)
Add an int to a sorted int array.
Description:
Add an int to a sorted int array. Returns 1 if the int is added. Returns 0 if the int was already there. Returns an FC_ReturnCode if there is an error.
Modifications:
06/06/06 ACG Created.
07/13/06 WSD Separated binary search into it's own routine. Separated lookupInt into two seperate add and query functions.
Parameters:
sia input/output - sortedIntArray
ix input - int to add
Definition at line 397 of file storage.c.
References _fc_addEntryToSortedIntArray(), _fc_lookupIntInSortedIntArray(), and FC_SUCCESS.
Referenced by _fc_buildMeshVertexNeighborsViaEdge(), _fc_buildParents(), _fc_deleteSlot(), _fc_getEdgeParents(), _fc_getNewSlot(), _fc_growNeighborList(), _fc_readExodusSubsetMembers(), calcShapeIntersection(), fc_addMemberToSubset(), fc_getMeshEntityChildren(), fc_groupSelfCorrespond(), fc_projectedSubsetElementBoundingBoxIntersection(), fc_reduceShapeNumSides(), getRemoveSIAIntersection(), and main().
 {
  FC_ReturnCode rc;
  int foundInt, idx;
  // this call also checks args
  rc = _fc_lookupIntInSortedIntArray(sia, ix, &foundInt, &idx);
  if (rc < 0)
    return rc;
  // early return
  if (foundInt == 1)
    return 0;
  // do it (this routine allocates memory if needed)
  rc = _fc_addEntryToSortedIntArray(sia, idx, ix);
  if (rc != FC_SUCCESS)
    return rc;
  else
    return 1;
}
int fc_convertIntArrayToSortedIntArray (int num, int * array, int isSorted, FC_SortedIntArray * sia)
Convert int array (no duplicates) to sorted int array.
Description:
Convert the int array to a sorted int array. The input array is assumed to have no duplicates. If it does, use fc_addIntArrayToSortedIntArray. For performance, there is a flag to specify if the array has already been sorted.
The sorted int array has to already have been allocated. The int array is "destroyed" in that the responsibility for freeing the array is transfered to the sorted int array.
WARNING: Do not use this routine on an automatically allocated array (i.e. one declared as int array[8]). Instead use fc_addIntArrayToSortedIntArray().
NOTE: It was decided not to handle duplicates because this is meant to be a quick conversion.
NOTE: For speed, insert order is calculated on the sorted version of the array and not the order passed to the function (see above).
Modifications:
2006/08/04 WSD Created.
2008/05/02 CDU Updated to support getting unsorted vals back
Parameters:
num input - number of ints in array
array input - the array of ints
isSorted input - sorted flag, 1 = sorted, 0 = not sorted
sia input/output - sortedIntArray
Definition at line 1301 of file storage.c.
References fc_getReturnCodeText(), fc_initSortedIntArray(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_sortIntArray(), FC_SUCCESS, FC_SortedIntArray::maxNumVal, FC_SortedIntArray::nextTicket, FC_SortedIntArray::numVal, FC_SortedIntArray::tickets, and FC_SortedIntArray::vals.
Referenced by _fc_buildFaceInfoListFromShape(), fc_projectedSubsetElementBoundingBoxIntersection(), and fc_segment().
 {
  FC_ReturnCode rc;
  int i;
  // default return
  // ??? init the sia?
  // check arguments
  if (num < 0 || (num > 0 && array == NULL) || !sia) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // setup sia
  rc = fc_initSortedIntArray(sia);
  if (rc != FC_SUCCESS)
    return rc;
  // simple case - no entries
  if (num == 0)
    return FC_SUCCESS;
  // sort
  if (!isSorted)
    fc_sortIntArray(num, array);
  // do it
  sia->numVal = num;
  sia->maxNumVal = num;
  sia->vals = array;
  sia->tickets = (int *)malloc(num*sizeof(int));
  if(!sia->tickets){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for(i=0;i<num;i++)
    sia->tickets[i] = i;
  sia->nextTicket = num;
  return FC_SUCCESS;
}
int fc_convertSortedIntArrayToIntArray (FC_SortedIntArray * sia, int * num, int ** array)
Convert sorted int array to array.
Description:
Convert the sorted int array to an int array. The sorted int array will be "destroyed" in that it's contents will be freed (and set back to zero). The sorted int array may still need to be freed it was malloc'd.
Modifications:
2006/08/04 WSD Created.
2008/05/02 CDU Updated to support getting unsorted vals back
Parameters:
sia input/output - sortedIntArray
num input - number of ints in array
array input - the array of ints
Definition at line 1363 of file storage.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_squeezeSortedIntArray(), FC_SUCCESS, FC_SortedIntArray::maxNumVal, FC_SortedIntArray::nextTicket, FC_SortedIntArray::numVal, FC_SortedIntArray::tickets, and FC_SortedIntArray::vals.
Referenced by _fc_buildMeshElementNeighborsViaEntity(), _fc_buildMeshVertexNeighborsViaEdge(), _fc_buildParents(), _fc_getEdgeNeighbors(), _fc_getEdgeParents(), _fc_getFaceNeighbors(), fc_changeMeshEntityType(), fc_createSubsetMesh(), fc_getMeshEntityChildren(), and fc_getSubsetNeighbors().
 {
  FC_ReturnCode rc;
  // default return
  if (num)
    *num = -1;
  if (array)
    *array = NULL;
  // check arguments
  if (!sia || !num || !array) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // minimize space usage
  rc = fc_squeezeSortedIntArray(sia);
  if (rc != FC_SUCCESS)
    return rc;
  // do it
  *num = sia->numVal;
  *array = sia->vals;
  sia->numVal = 0;
  sia->maxNumVal = 0;
  sia->vals = NULL;
  free(sia->tickets);
  sia->tickets = NULL;
  sia->nextTicket = 0;
  return FC_SUCCESS;
}
FC_ReturnCode fc_copySortedIntArray (FC_SortedIntArray * sia_src, FC_SortedIntArray * sia_dest)
Copy (deep copy) a sorted int array.
Description:
The destination sia must already have been allocated but does not have to be initialized. This peforms a deep copy (i.e. internal data is copied).
Modifications:
2006/08/04 WSD Created.
2008/05/02 CDU Updated to support getting unsorted vals back
Parameters:
sia_src input - sortedIntArray to copy
sia_dest output - new sortedIntArray
Definition at line 156 of file storage.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSortedIntArrayValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_SortedIntArray::maxNumVal, FC_SortedIntArray::nextTicket, FC_SortedIntArray::numVal, FC_SortedIntArray::tickets, and FC_SortedIntArray::vals.
{
  if (!fc_isSortedIntArrayValid(sia_src) || !sia_dest) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  fc_printfLogMessage("Copying sorted int array");
  sia_dest->numVal    = sia_src->numVal;
  sia_dest->maxNumVal = sia_src->numVal;
  sia_dest->nextTicket = sia_src->nextTicket;
  if (sia_src->numVal > 0) {
    sia_dest->vals              = malloc(sia_src->numVal*sizeof(int));
    sia_dest->tickets = malloc(sia_src->numVal*sizeof(unsigned int));
    if((sia_dest->vals == NULL) ||
       (sia_dest->tickets == NULL)){
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    memcpy(sia_dest->vals, sia_src->vals, sia_src->numVal*sizeof(int));
    memcpy(sia_dest->tickets, sia_src->tickets, sia_src->numVal*sizeof(unsigned int));
  }
  else {
    sia_dest->vals    = NULL;
    sia_dest->tickets = NULL;
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_createIntArrayFromMask (int numMask, int * mask, int * numArray, int ** array)
Create an Int Array from a Mask.
Description:
Creates an Int Array from the given mask. The original mask is left untouched. The returned Int Array will be sorted.
Modifications:
07/01/04 WSK, Created
Parameters:
numMask input - number of entries in Mask
mask input - mask array
numArray output - number of entries in returned array
array output - returned int array, will be sorted
Definition at line 1412 of file storage.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
  {
  int i, num;
  // default return
  if (numArray)
    *numArray = -1;
  if (array)
    *array = NULL;
  // input checking
  if (numMask < 1 || !mask || !numArray || !array) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Creating integer array from mask.");
  // do it
  num = 0;
  for (i = 0; i < numMask; i++)
    if (mask[i] > 0)
      num++;
  *numArray = num;
  if (num > 0) {
    *array = malloc(num*sizeof(int));
    if (*array == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    num = 0;
    for (i = 0; i < numMask; i++) {
      if (mask[i] > 0) {
        (*array)[num] = i;
        num++;
      }
    }
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_createMaskFromIntArray (int numArray, int * array, int numMask, int ** mask)
Create a Mask from an Int Array.
Description:
Creates a Mask from the given Int Array; the length of the mask must also be provided. The original array is left untouched. numArray = 0 is a valid input that creates a mask with all entries being 0. If any entries of array are outside the range [0, numMask-1], the routine does not create the mask and returns an error.
Modifications:
07/01/04 WSK, Created
Parameters:
numArray input - number of entries in array
array input - the array
numMask input - number of entries in Mask
mask output - the mask array
Definition at line 1475 of file storage.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
  {
  int i;
  // default return
  if (mask)
    *mask = NULL;
  // input checking
  if (numArray < 0 || (numArray > 0 && !array) || numMask < 1 || !mask) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Creating mask from integer array.");
  // do it
  *mask = calloc(numMask, sizeof(int));
  if (*mask == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < numArray; i++) {
    if (array[i] < 0 || array[i] > numMask-1) {
      free(*mask);
      *mask = NULL;
      fc_printfErrorMessage("Input Error: array element has invalid value.");
      return FC_INPUT_ERROR;
    }
    (*mask)[array[i]] = 1;
  }
  return FC_SUCCESS;
}
int fc_deleteBlobFromSortedBlobArray (FC_SortedBlobArray * sba, void * blob, int blobCmpconst void *, const void *, void ** deletedBlob)
Remove a blob from a sorted blob array.
Description:
Returns 1 if the blob was found and deleted, returns 0 if the blob was not in the array, and returns an error code if something went wrong. (Note: the total size of the array does not change, call fc_squeezeSortedBlobArray() to save space). Also returns pointer to the blob deleted from the array if requested (pass NULL if you don't want it).
Modifications:
08/08/2006 WSD Created.
Parameters:
sba input/output - sortedBlobArray
blob input - blob to delete
blobCmp input - the blob comparison function
deletedBlob output - (optional) the deleted blob
Definition at line 1157 of file storage.c.
References _fc_deleteEntryFromSortedBlobArray(), _fc_lookupBlobInSortedBlobArray(), FC_SortedBlobArray::blobs, and FC_SUCCESS.
 {
  FC_ReturnCode rc;
  int foundInt, idx;
  // default return
  if (deletedBlob)
    *deletedBlob = NULL;
  // This call also checks sia
  rc = _fc_lookupBlobInSortedBlobArray(sba, blob, blobCmp, &foundInt, &idx);
  if (rc < 0)
    return rc;
  // early return
  if (foundInt == 0)
    return 0;
  // do it
  if (deletedBlob)
    *deletedBlob = sba->blobs[idx];
  rc = _fc_deleteEntryFromSortedBlobArray(sba, idx);
  if (rc != FC_SUCCESS)
    return rc;
  else
    return 1;
}
int fc_deleteIntFromSortedIntArray (FC_SortedIntArray * sia, int ix)
Remove an int from a sorted int array.
Description:
Returns 1 if the int was found and deleted, returns 0 if the int was not in the array, and returns an error code if something went wrong. (Note: the total size of the array does not change, call fc_squeezeSortedIntArray() to save space).
Modifications:
06/06/06 ACG Created.
07/13/06 WSD Separated binary search into it's own routine.
Parameters:
sia input/output - sortedIntArray
ix input - int to lookup
Definition at line 591 of file storage.c.
References _fc_deleteEntryFromSortedIntArray(), _fc_lookupIntInSortedIntArray(), and FC_SUCCESS.
Referenced by _fc_buildFaceInfoListFromShape(), _fc_buildMeshElementNeighborsViaEntity(), _fc_getEdgeNeighbors(), _fc_getFaceNeighbors(), fc_deleteMemberFromSubset(), fc_getSideNormalMeanSdev(), fc_getSubsetNeighbors(), fc_projectedSubsetElementBoundingBoxIntersection(), fc_reduceShapeNumSides(), and fc_segment().
 {
  FC_ReturnCode rc;
  int foundInt, idx;
  // This call also checks sia
  rc = _fc_lookupIntInSortedIntArray(sia, ix, &foundInt, &idx);
  if (rc < 0)
    return rc;
  // early return
  if (foundInt == 0)
    return 0;
  // do it
  rc = _fc_deleteEntryFromSortedIntArray(sia, idx);
  if (rc != FC_SUCCESS)
    return rc;
  else
    return 1;
}
void fc_freeSortedBlobArray (FC_SortedBlobArray * sba)
Free the sorted blob array's values.
Description:
This routine frees the internals of a sorted blob array, but not the sba itself. The user must dealloc the sba itself, unless it was automatically allocated.
Modifications:
06/06/06 ACG Created.
Parameters:
sba input/output - sortedBlobArray
Definition at line 1245 of file storage.c.
References FC_SortedBlobArray::blobs, fc_isSortedBlobArrayValid(), FC_SortedBlobArray::maxNumBlob, and FC_SortedBlobArray::numBlob.
Referenced by _fc_buildEdgeConns(), _fc_buildFaceConns(), _fc_freeNamesFileNames(), and _fc_writeExodusDataset().
 {
  if (!fc_isSortedBlobArrayValid(sba)){
    return;
  }
  if (sba->blobs){
    free(sba->blobs);
    sba->numBlob = 0;
    sba->maxNumBlob = 0;
    sba->blobs = NULL;
  }
}
void fc_freeSortedIntArray (FC_SortedIntArray * sia)
Free the sorted int array's values.
Description:
This routine frees the internals of a sorted int array, but not the sia itself. The user must dealloc the sia itself, unless it was automatically allocated.
Modifications:
2006/06/06 ACG Created.
2008/05/02 CDU Updated to support getting unsorted vals back
Parameters:
sia input/output - sortedIntArray
Definition at line 846 of file storage.c.
References fc_isSortedIntArrayValid(), FC_SortedIntArray::maxNumVal, FC_SortedIntArray::nextTicket, FC_SortedIntArray::numVal, FC_SortedIntArray::tickets, and FC_SortedIntArray::vals.
Referenced by _fc_buildFaceInfoListFromShape(), _fc_freeDsTable(), _fc_freeMeshTable(), _fc_freeSeqTable(), _fc_freeSubTable(), _fc_freeVarTable(), _fc_growNeighborList(), _fc_releaseSubSlot(), calcShapeIntersection(), fc_computeTreeDescendantsAncestors(), fc_getSideNormalMeanSdev(), fc_getSubsetNeighbors(), fc_groupSelfCorrespond(), fc_projectedSubsetElementBoundingBoxIntersection(), fc_reduceShapeNumSides(), fc_releaseSubset(), fc_segment(), freeShapeIntersection(), and main().
 {
  if (!fc_isSortedIntArrayValid(sia)){
    return;
  }
  if (sia->vals){
    free(sia->vals);
    free(sia->tickets);
    sia->numVal = 0;
    sia->maxNumVal = 0;
    sia->nextTicket = 0;
    sia->vals = NULL;
    sia->tickets = NULL;
  }
}
FC_ReturnCode fc_getSortedBlobArrayBlobs (FC_SortedBlobArray * sba, int * numBlob, void *** blobs)
Get a copy of the blob locations stored in the sorted blob array.
Description:
Returns a copy of the blob locations storee in the sorted blob array. The caller is responsible for freeing the returned array.
Modifications:
08/08/06 WSD created.
Parameters:
sba input - sortedBlobArray
numBlob output - number of values
blobs output - blob locations (needs to be freed)
Definition at line 1027 of file storage.c.
References FC_SortedBlobArray::blobs, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSortedBlobArrayValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, FC_SUCCESS, and FC_SortedBlobArray::numBlob.
 {
  // default returns
  if (numBlob)
    *numBlob = -1;
  if (blobs)
    *blobs = NULL;
  // check arguments
  if (!fc_isSortedBlobArrayValid(sba) || !numBlob || !blobs) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // easy case - no valus
  if (sba->numBlob == 0) {
    *numBlob = 0;
    *blobs = NULL;
    return FC_SUCCESS;
  }
  // do it
  *blobs = malloc(sba->numBlob*sizeof(void*));
  if (!(*blobs)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  *numBlob = sba->numBlob;
  memcpy(*blobs, sba->blobs, sba->numBlob*sizeof(void*));
  return FC_SUCCESS;
}
FC_ReturnCode fc_getSortedBlobArrayNumBlob (FC_SortedBlobArray * sba, int * numBlob)
Get number of blobs in sorted blob array.
Modifications:
08/08/06 WSD created.
Parameters:
sba input - sortedBlobArray
numBlob output - number of blobs
Definition at line 995 of file storage.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSortedBlobArrayValid(), fc_printfErrorMessage, FC_SUCCESS, and FC_SortedBlobArray::numBlob.
 {
  // default returns
  if (numBlob)
    *numBlob = -1;
  // check arguments
  if (!fc_isSortedBlobArrayValid(sba) || !numBlob) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // do it
  *numBlob = sba->numBlob;
  return FC_SUCCESS;
}
int fc_getSortedIntArrayBack (FC_SortedIntArray * sia, int * value)
Get last value in the sorted int array (WARNING: does not check for empty array).
Description:
Returns the last value in a non empty sorted int array. Do not use this funciton on empty sorted int arrays. Use fc_getSortedIntArrayNumValue to determine if an array has values. To remove the back value, use fc_popSortedIntArrayBack.
You can also manipulate the front of a sorted int array; see also fc_getSortedIntArrayFront and fc_popSortedIntArrayFront.
Modifications:
08/03/06 WSD Created.
Parameters:
sia input - sortedIntArray
value input - last value in the array
Definition at line 676 of file storage.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSortedIntArrayValid(), fc_printfErrorMessage, fc_printfWarningMessage, FC_SUCCESS, FC_SortedIntArray::numVal, and FC_SortedIntArray::vals.
Referenced by _fc_buildFaceInfoListFromShape().
 {
  // default return
  if (value)
    *value = -1;
  // check arguments
  if (!fc_isSortedIntArrayValid(sia)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // do it
  if (sia->numVal > 0) {
    *value = sia->vals[sia->numVal-1];
  }
  else {
    fc_printfWarningMessage("Getting the front of an empty sorted int array");
  }
  return FC_SUCCESS;
}
int fc_getSortedIntArrayFront (FC_SortedIntArray * sia, int * value)
Get first value in the sorted int array (WARNING: does not check for empty array).
Description:
Returns the first value in a non empty sorted int array. Do not use this funciton on empty sorted int arrays. Use fc_getSortedIntArrayNumValue to determine if an array has values. To remove the front value, use fc_popSortedIntArrayFront.
You can also manipulate the back of a sorted int array; see also fc_getSortedIntArrayBack and fc_popSortedIntArrayBack.
Modifications:
08/03/06 WSD Created.
Parameters:
sia input - sortedIntArray
value input - first value in the array
Definition at line 633 of file storage.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSortedIntArrayValid(), fc_printfErrorMessage, fc_printfWarningMessage, FC_SUCCESS, FC_SortedIntArray::numVal, and FC_SortedIntArray::vals.
Referenced by fc_segment().
 {
  // default return
  if (value)
    *value = -1;
  // check arguments
  if (!fc_isSortedIntArrayValid(sia)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // do it
  if (sia->numVal > 0) {
    *value = sia->vals[0];
  }
  else {
    fc_printfWarningMessage("Getting the front of an empty sorted int array");
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_getSortedIntArrayNumValue (FC_SortedIntArray * sia, int * numValue)
Get number of values in sorted int array.
Modifications:
2006/08/03 WSD created.
Parameters:
sia input - sortedIntArray
numValue output - number of values
Definition at line 198 of file storage.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSortedIntArrayValid(), fc_printfErrorMessage, FC_SUCCESS, and FC_SortedIntArray::numVal.
 {
  // default returns
  if (numValue)
    *numValue = -1;
  // check arguments
  if (!fc_isSortedIntArrayValid(sia) || !numValue) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // do it
  *numValue = sia->numVal;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getSortedIntArrayValues (FC_SortedIntArray * sia, int * numValue, int ** values)
Get a copy of the values stored in the sorted int array.
Description:
Returns a copy of the values stores in the sorted int array. The caller is responsible for freeing the return array. If you know you never want to use the current values of the sorted int array again, you can instead convert by using fc_convertSortedIntArrayToIntArray.
Modifications:
2006/08/04 WSD created.
Parameters:
sia input - sortedIntArray
numValue output - number of values
values output - values (needs to be freed)
Definition at line 232 of file storage.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSortedIntArrayValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, FC_SUCCESS, FC_SortedIntArray::numVal, and FC_SortedIntArray::vals.
 {
  // default returns
  if (numValue)
    *numValue = -1;
  if (values)
    *values = NULL;
  // check arguments
  if (!fc_isSortedIntArrayValid(sia) || !numValue || !values) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // easy case - no valus
  if (sia->numVal == 0) {
    *numValue = 0;
    *values = NULL;
    return FC_SUCCESS;
  }
  // do it
  *values = malloc(sia->numVal*sizeof(int));
  if (!(*values)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  *numValue = sia->numVal;
  memcpy(*values, sia->vals, sia->numVal*sizeof(int));
  return FC_SUCCESS;
}
FC_ReturnCode fc_getSortedIntArrayValuesInInsertOrder (FC_SortedIntArray * sia, int * numValue, int ** values)
Get a copy of the values stored in the sorted array, orderd in the way they were inserted.
Description:
Returns a copy of the values stores in the sorted int array, ordered in the way they were inserted. This allows a sortedIntArray to be used as a list where ordering is significant. The caller is responsible for freeing the return array. If you know you never want to use the current values of the sorted int array again, you can instead convert by using fc_convertSortedIntArrayToIntArray. If you don't care about order, fc_getSortedIntArrayValues is faster.
Modifications:
2008/05/02 CDU created.
Parameters:
sia input - sortedIntArray
numValue output - number of values
values output - values (needs to be freed)
Definition at line 293 of file storage.c.
References _fc_qsortCmpInt(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSortedIntArrayValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, FC_SUCCESS, FC_SortedIntArray::numVal, FC_SortedIntArray::tickets, and FC_SortedIntArray::vals.
 {
  int  i;
  int *tmp;
  // default returns
  if (numValue)
    *numValue = -1;
  if (values)
    *values = NULL;
  // check arguments
  if (!fc_isSortedIntArrayValid(sia) || !numValue || !values) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // easy case - no valus
  if (sia->numVal == 0) {
    *numValue = 0;
    *values = NULL;
    return FC_SUCCESS;
  }
  // do it
  *values = malloc(sia->numVal*sizeof(int));
  if (!(*values)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  *numValue = sia->numVal;
  //Need to resort the values by their insert id. We can do this by
  //packing both the insert time and val together and passing on
  //to quicksort. Quicksort is given an integer comparison function
  //and a stride of 2 to make this work. After everything, we
  //unpack the results
  tmp = malloc(sia->numVal * 2 * sizeof(int));
  for(i=0; i<sia->numVal; i++){
    tmp[2*i+0] = sia->tickets[i];
    tmp[2*i+1] = sia->vals[i];
  }
  qsort((void *) tmp, sia->numVal, 2*sizeof(int), _fc_qsortCmpInt );
  for(i=0; i<sia->numVal; i++)
    (*values)[i] = tmp[2*i+1]; //Grab vals
  free(tmp);
  return FC_SUCCESS;
}
FC_ReturnCode fc_initSortedBlobArray (FC_SortedBlobArray * sba)
Initialize a sorted blob array.
Description:
The sba must already have been allocated
Modifications:
08/07/06 WSK Created.
Parameters:
sba input/output - sortedBlobArray
Definition at line 944 of file storage.c.
References FC_SortedBlobArray::blobs, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_SortedBlobArray::maxNumBlob, and FC_SortedBlobArray::numBlob.
Referenced by _fc_readNamesFile(), and _fc_writeExodusDataset().
{
  if (sba == NULL){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  fc_printfLogMessage("Initing sorted blob array");
  sba->numBlob = 0;
  sba->maxNumBlob = 0;
  sba->blobs = NULL;
  return FC_SUCCESS;
}
FC_ReturnCode fc_initSortedIntArray (FC_SortedIntArray * sia)
Initialize a sorted int array.
Description:
The sia must already have been allocated
Modifications:
06/06/06 ACG Created.
Parameters:
sia input/output - sortedIntArray
Definition at line 95 of file storage.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_SortedIntArray::maxNumVal, FC_SortedIntArray::nextTicket, FC_SortedIntArray::numVal, FC_SortedIntArray::tickets, and FC_SortedIntArray::vals.
Referenced by _fc_buildMeshElementNeighborsViaEntity(), _fc_buildMeshVertexNeighborsViaEdge(), _fc_buildParents(), _fc_getEdgeNeighbors(), _fc_getEdgeParents(), _fc_getFaceNeighbors(), _fc_growNeighborList(), _fc_initSubSlot(), calcShapeIntersection(), fc_changeMeshEntityType(), fc_computeTreeDescendantsAncestors(), fc_convertIntArrayToSortedIntArray(), fc_createSubsetMesh(), fc_getMeshEntityChildren(), fc_getSideNormalMeanSdev(), fc_getSubsetNeighbors(), fc_groupSelfCorrespond(), fc_projectedSubsetElementBoundingBoxIntersection(), and fc_reduceShapeNumSides().
{
  if (sia == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  fc_printfLogMessage("Initing sorted int array");
  sia->numVal     = 0;
  sia->maxNumVal  = 0;
  sia->vals       = NULL;
  sia->nextTicket = 0;
  sia->tickets    = NULL;
  return FC_SUCCESS;
}
int fc_isBlobInSortedBlobArray (FC_SortedBlobArray * sba, void * blob, int blobCmpconst void *, const void *, void ** foundBlob)
Query for blob in sorted blob array.
Description:
Returns 1 if the blob is in the array, 0 if it is not, and an FC_ReturnCode if an error occurs. Also returns pointer to the blob already in the array if requested (pass NULL if you don't want it).
Modifications:
08/08/2006 WSD Created.
Parameters:
sba input - sortedBlobArray
blob input - blob to look for
blobCmp input - the blob comparison function
foundBlob output - (optional) the found blob
Definition at line 1077 of file storage.c.
References _fc_lookupBlobInSortedBlobArray(), and FC_SortedBlobArray::blobs.
Referenced by _fc_loadLSDynaDataset().
 {
  FC_ReturnCode rc;
  int foundInt, idx;
  // default return
  if (foundBlob)
    *foundBlob = NULL;
  // this call also checks args
  rc = _fc_lookupBlobInSortedBlobArray(sba, blob, blobCmp, &foundInt, &idx);
  if (rc < 0)
    return rc;
  if (foundInt && foundBlob)
    *foundBlob = sba->blobs[idx];
  return foundInt;
}
int fc_isIntInSortedIntArray (FC_SortedIntArray * sia, int ix)
Query for int in sorted int array.
Description:
Returns 1 if the int is in the array, 0 if it is not, and an FC_ReturnCode if an error occurs.
Modifications:
06/06/06 ACG Created.
07/13/06 WSD Separated binary search into it's own routine. Separated lookupInt into two seperate add and query functions.
Parameters:
sia input - sortedIntArray
ix input - int to look for
Definition at line 367 of file storage.c.
References _fc_lookupIntInSortedIntArray().
Referenced by calcShapeIntersection(), and fc_isMemberInSubset().
 {
  FC_ReturnCode rc;
  int foundInt, idx;
  // this call also checks args
  rc = _fc_lookupIntInSortedIntArray(sia, ix, &foundInt, &idx);
  if (rc < 0)
    return rc;
  return foundInt;
}
int fc_isSortedBlobArrayValid (FC_SortedBlobArray * sba)
Check to see if a sorted blob array is valid.
Description:
Checks that the sorted blob array has "sane" values. Returns 1 if the sorted array looks valid and 0 if it does not.
Modifications:
06/06/06 ACG Created.
Parameters:
sba input - sortedBlobArray
Definition at line 974 of file storage.c.
References FC_SortedBlobArray::blobs, FC_SortedBlobArray::maxNumBlob, and FC_SortedBlobArray::numBlob.
Referenced by _fc_addEntryToSortedBlobArray(), _fc_deleteEntryFromSortedBlobArray(), _fc_freeNamesFileNames(), _fc_lookupBlobInSortedBlobArray(), fc_freeSortedBlobArray(), fc_getSortedBlobArrayBlobs(), fc_getSortedBlobArrayNumBlob(), and fc_squeezeSortedBlobArray().
{
  if (!sba || sba->numBlob < 0 || sba->maxNumBlob < 0 ||
      sba->numBlob > sba->maxNumBlob ||
      (sba->maxNumBlob == 0 && sba->blobs != NULL) ||
      (sba->maxNumBlob > 0 && sba->blobs == NULL)) {
    return 0;
  }
  else
    return 1;
}
int fc_isSortedIntArrayValid (FC_SortedIntArray * sia)
Check to see if a sorted int array is valid.
Description:
Checks that the sorted int array has "sane" values. Returns 1 if the sorted array looks valid and 0 if it does not.
Modifications:
2006/06/06 ACG Created.
Parameters:
sia input - sortedIntArray
Definition at line 127 of file storage.c.
References FC_SortedIntArray::maxNumVal, FC_SortedIntArray::numVal, FC_SortedIntArray::tickets, and FC_SortedIntArray::vals.
Referenced by _fc_addEntryToSortedIntArray(), _fc_deleteEntryFromSortedIntArray(), _fc_lookupIntInSortedIntArray(), fc_addIntArrayToSortedIntArray(), fc_copySortedIntArray(), fc_freeSortedIntArray(), fc_getSortedIntArrayBack(), fc_getSortedIntArrayFront(), fc_getSortedIntArrayNumValue(), fc_getSortedIntArrayValues(), fc_getSortedIntArrayValuesInInsertOrder(), fc_popSortedIntArrayBack(), fc_popSortedIntArrayFront(), fc_printSortedIntArray(), and fc_squeezeSortedIntArray().
{
  if ((!sia) ||
      (sia->numVal < 0)                                                                 ||
      (sia->maxNumVal < 0)                                                              ||
      (sia->numVal > sia->maxNumVal)                                                    ||
      ((sia->maxNumVal == 0) && ((sia->vals != NULL)|| (sia->tickets!=NULL))) ||
      ((sia->maxNumVal  > 0) && ((sia->vals == NULL)|| (sia->tickets==NULL)))   ) {
    return 0;
  }
  else
    return 1;
}
int fc_popSortedIntArrayBack (FC_SortedIntArray * sia)
Delete the last value in a sorted int array.
Description:
Delete the last value in a sorted int array. The return value is an FC_ReturnCode if there is an error, 0 if the array is empty, or 1 if the value has been deleted.
If you want to know the value of the back, before popping you must call fc_getSortedIntArrayBack.
You can also manipulate the front of a sorted int array; see also fc_getSortedIntArrayFront and fc_popSortedIntArrayFront.
Modifications:
08/03/06 WSD Created.
Parameters:
sia input/output - sortedIntArray
Definition at line 763 of file storage.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSortedIntArrayValid(), fc_printfErrorMessage, and FC_SortedIntArray::numVal.
Referenced by _fc_buildFaceInfoListFromShape().
 {
  // check arguments
  if (!fc_isSortedIntArrayValid(sia)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // do it (do minimum amt of work)
  if (sia->numVal > 0) {
    sia->numVal--;
    return 1;
  }
  else {
    return 0;
  }
}
int fc_popSortedIntArrayFront (FC_SortedIntArray * sia)
Delete the first value in a sorted int array.
Description:
Delete the first value in a sorted int array. The return value is an FC_ReturnCode if there is an error, 0 if the array is empty, or 1 if the value has been deleted.
If you want to know the value of the front, before popping you must call fc_getSortedIntArrayFront.
You can also manipulate the back of a sorted int array; see also fc_getSortedIntArrayBack and fc_popSortedIntArrayBack.
Modifications:
08/03/06 WSD Created.
2008/05/02 CDU Updated to support getting unsorted vals back
Parameters:
sia input/output - sortedIntArray
Definition at line 721 of file storage.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSortedIntArrayValid(), fc_printfErrorMessage, FC_SortedIntArray::numVal, FC_SortedIntArray::tickets, and FC_SortedIntArray::vals.
Referenced by _fc_getNewSlot(), and fc_segment().
 {
  // check arguments
  if (!fc_isSortedIntArrayValid(sia)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // do it (do minimum amt of work)
  if (sia->numVal > 0) {
    sia->numVal--;
    if (sia->numVal > 0) {
      memmove(sia->vals,    sia->vals+1,    sia->numVal*sizeof(int));
      memmove(sia->tickets, sia->tickets+1, sia->numVal*sizeof(int));
    }
    return 1;
  }
  else {
    return 0;
  }
}
FC_ReturnCode fc_printSortedIntArray (FC_SortedIntArray * sia)
prints the sortedint array
Description:
Prints the contents of a sorted int array.
Modifications:
06/06/06 ACG Created.
06/07/06 ACG takes ptr to array as parameter
Parameters:
sia input - sortedIntArray
Definition at line 877 of file storage.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSortedIntArrayValid(), fc_printfErrorMessage, FC_SUCCESS, FC_SortedIntArray::maxNumVal, FC_SortedIntArray::numVal, FC_SortedIntArray::tickets, and FC_SortedIntArray::vals.
 {
  int i;
  // check args
  if (!fc_isSortedIntArrayValid(sia)){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  printf("Sorted Int Array:\n");
  printf("    numVal = %d\n", sia->numVal);
  printf("    maxNumVal = %d\n", sia->maxNumVal);
  printf("    vals =");
  if (sia->numVal == 0){
    printf(" (empty)\n");
  }
  else {
    for (i = 0; i < sia->numVal; i++){
      printf(" %d",sia->vals[i]);
    }
    printf("\n");
  }
  printf("    insert tickets =");
  if (sia->numVal == 0){
    printf(" (empty)\n");
  }
  else {
    for (i = 0; i < sia->numVal; i++){
      printf(" %d",sia->tickets[i]);
    }
    printf("\n");
  }
  fflush(NULL);
  return FC_SUCCESS;
}
FC_ReturnCode fc_squeezeSortedBlobArray (FC_SortedBlobArray * sba)
Realloc the sorted blob array so it has no extra space.
Modifications:
06/06/06 ACG Created.
Parameters:
sba input - sortedBlobArray
Definition at line 1197 of file storage.c.
References FC_SortedBlobArray::blobs, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSortedBlobArrayValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, FC_SUCCESS, FC_SortedBlobArray::maxNumBlob, and FC_SortedBlobArray::numBlob.
 {
  void** temp;
  // check args
  if (!fc_isSortedBlobArrayValid(sba)){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // early return
  if (sba->numBlob == sba->maxNumBlob) // already compressed
    return FC_SUCCESS;
  // special case - empty
  if (sba->numBlob == 0) {
    free(sba->blobs);
    sba->maxNumBlob = 0;
    sba->blobs = NULL;
    return FC_SUCCESS;
  }
  // do it
  temp = (void**)realloc(sba->blobs, (sba->numBlob)*sizeof(void*));
  if (temp == NULL){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  sba->maxNumBlob = sba->numBlob;
  sba->blobs = temp;
  return FC_SUCCESS;
}
FC_ReturnCode fc_squeezeSortedIntArray (FC_SortedIntArray * sia)
Realloc the sorted int array so it has no extra space.
Modifications:
06/06/06 ACG Created.
Parameters:
sia input - sortedIntArray
Definition at line 789 of file storage.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSortedIntArrayValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, FC_SUCCESS, FC_SortedIntArray::maxNumVal, FC_SortedIntArray::nextTicket, FC_SortedIntArray::numVal, FC_SortedIntArray::tickets, and FC_SortedIntArray::vals.
Referenced by fc_convertSortedIntArrayToIntArray().
 {
  int *temp1, *temp2;
  // check args
  if (!fc_isSortedIntArrayValid(sia)){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // early return
  if (sia->numVal == sia->maxNumVal) // already compressed
    return FC_SUCCESS;
  // special case - empty
  if (sia->numVal == 0) {
    free(sia->vals);
    free(sia->tickets);
    sia->maxNumVal = 0;
    sia->vals = NULL;
    sia->tickets = NULL;
    sia->nextTicket = 0;
    return FC_SUCCESS;
  }
  // do it
  temp1 = (int*)realloc(sia->vals,    (sia->numVal)*sizeof(int));
  temp2 = (int*)realloc(sia->tickets, (sia->numVal)*sizeof(int));
  if((temp1 == NULL)||(temp2 == NULL)){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  sia->maxNumVal = sia->numVal;
  sia->vals      = temp1;
  sia->tickets   = temp2;
  return FC_SUCCESS;
}