FCLib: (Private)
(Private)
[Element Death]
Functions
FC_ReturnCode _fc_recursive_IndividuallySegmentingNodes (FC_Subset subset, int compare, int shared_segdim, int numin, int *inset, int *numout, int **outset)
helper function that recursively determines node ids that individually will result in greater segmentation than some comparison value
Function Documentation
FC_ReturnCode _fc_recursive_IndividuallySegmentingNodes (FC_Subset subset, int compare, int shared_segdim, int numin, int * inset, int * numout, int ** outset)
helper function that recursively determines node ids that individually will result in greater segmentation than some comparison value
Description:
helper function that recursively determines node ids that will individually result in greater segmentation than some comparison value
Note:
This uses recursion to test on big sets of elem first and only narrow it down to smaller set if the big sets segment first. i.e., It is assumed that if a whole group doesnt result in a greater segmenting, that the items of the group taken individually wont result in a greater segmenting. There is the possibility that there could be offsetting effects that occur within the bigger set that will cuase this to be a faulty assumption, particularly when the dead region is close to the boundary of the mesh. However, if this is used primarily for cases where we are looking for the mesh to be just about to break, then we expect that the num of elements that will satisfy the condition is small and so this should be ok.
Todo:
will we want less segmentation too.
Modifications:
9/20/05 ACG created in response to thinking that its better to return the segmenting rather than the nonsegmenting nodeset so dont have to do inversion of the set later. replaces _fc_maximalNonSegmentingNodeset
9/22/05 ACG added shared segdim
10/09/05 ACG explicitly check that 1 element set doesnt result in less segmentation (rather than just equal). will continue to loop for larger sets resulting in less segmentation (for instance if whole set of neighbors subsumes the live regions, still want to delve down into individual bits)
Definition at line 1268 of file elemdeath.c.
References _fc_recursive_IndividuallySegmentingNodes(), fc_addArrayMembersToSubset(), fc_copySubset(), fc_deleteSubset(), fc_getMeshFromSubset(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSubsetValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, fc_subsetSegmentsMesh(), and FC_SUCCESS.
Referenced by _fc_recursive_IndividuallySegmentingNodes(), and fc_subsetPlusNeighborGreaterSegmentationMesh().
 {
  FC_ReturnCode rc;
  FC_Mesh mesh;
  FC_Subset testSubset;
  int numSegment;
  int i;
  //defaults
  *numout = 0;
  if (outset)
    *outset = NULL;
  // Test input (shared_segdim checked in fc_segment)
  if (!fc_isSubsetValid(subset) || !numout || !outset ||
      numin < 0 || (!inset  && numin != 0)){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  fc_printfLogMessage("recursive segmenting nodes");
  //  printf("\tChecking set (%d) ",numin);
  //  for (i = 0; i < numin; i++){
  //    printf("%d ", inset[i]);
  //  }
  //  printf("\n");
  if (numin == 0){
    return FC_SUCCESS;
  }
  //now lets get a copy of the subset to play with
  rc = fc_getMeshFromSubset(subset,&mesh);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("cant get mesh");
    return rc;
  }
  rc = fc_copySubset(subset,mesh,"test_subset",&testSubset);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("cant copy subset");
    return rc;
  }
  //now see if adding if the whole set does anything
  rc = fc_addArrayMembersToSubset(testSubset,numin,inset);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("cant add ids to subset");
    return rc;
  }
  rc =  fc_subsetSegmentsMesh(testSubset,shared_segdim,NULL,
                     &numSegment,NULL);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("failed to segment");
    return rc;
  }
  rc = fc_deleteSubset(testSubset);
  //compare is passed in so we dont have to recalc it each time, but it better
  //be correct
  if (numSegment == compare){
    //    printf("elements as a group do not divide any more (or less) (%d). maximal recursion - returning 0 elem\n",numSegment);
    //then adding the vals doesnt cause any greater segmentation
    *numout = 0;
  } else {
    if (numin == 1){
      if (numSegment <= compare){
     //     printf("single element %d doesnt divide more. maximal recursion - returning 1 elem\n",inset[0]);
     *numout = 0;
      }else {
     //     printf("single element %d divides. maximal recursion - returning 1 elem\n",inset[0]);
     *numout = 1;
     *outset = (int*)malloc(sizeof(int));
     if (*outset == NULL){
       fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
       return FC_MEMORY_ERROR;
     }
     (*outset)[0] = inset[0];
      }
    }else{
      int idiv = numin/2;
      int *seta, *setb;
      int *reta, *retb, nreta, nretb;
      //      printf("this does divide - recursing\n");
      seta = malloc(idiv*sizeof(int));
      setb = malloc((numin-idiv)*sizeof(int));
      if ((seta == NULL && idiv > 0) || (setb == NULL && numin-idiv > 0)){
     fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
     return FC_MEMORY_ERROR;
      }
      for (i = 0; i < idiv; i++){
     seta[i] = inset[i];
      }
      for (i = 0; i < numin-idiv; i++){
     setb[i] = inset[i+idiv];
      }
      //      printf("\tcalling set A\n");
      rc = _fc_recursive_IndividuallySegmentingNodes(subset,compare,shared_segdim,
                           idiv,seta,&nreta,&reta);
      if (rc != FC_SUCCESS){
     fc_printfErrorMessage("failed to get recursive segmenting nodes");
     free(seta);
     free(setb);
     return rc;
      }
      //      printf("\tcalling set B\n");
      rc = _fc_recursive_IndividuallySegmentingNodes(subset,compare,shared_segdim,
                           numin-idiv,setb,&nretb,&retb);
      if (rc != FC_SUCCESS){
     fc_printfErrorMessage("failed to get recursive segmenting nodes");
     free(seta);
     free(setb);
     return rc;
      }
      free(seta);
      free(setb);
      *numout = nreta + nretb;
      if (*numout > 0){
     *outset = (int*)malloc(*numout*sizeof(int));
     if (*outset == NULL){
       //no cleanup in case of memory error
       fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
       return FC_MEMORY_ERROR;
     }
     for (i = 0; i < nreta; i++){
       (*outset)[i] = reta[i];
     }
     for (i = 0; i < nretb; i++){
       (*outset)[i+nreta] = retb[i];
     }
     //      if (*numout != 0) printf("\trecur: %d in %d out\n",numin,*numout);
     if (reta) free(reta); //they will be NULL otherwise
     if (retb) free(retb);
      }
    }
  }
  return FC_SUCCESS;
}