FCLib: Helpers (not available outside this module)
Helpers (not available outside this module)
[Features]
Functions
FC_ReturnCode _fc_featureGroup_addFeature (FC_FeatureGroup *group, _FC_Feature *feature)
Helper routine to add a feature to the feature group.
FC_ReturnCode _fc_featureGroup_addROI (FC_FeatureGroup *group, int featureID, int stepID, FC_Subset roi, int *roiID)
Helper routine to Add an ROI to the feature group.
FC_ReturnCode _fc_writeFeatureGroup (FC_FeatureGroup *group, FILE *file)
Print the contents of a feature group.
FC_ReturnCode _fc_writeFeatureGraph (FC_FeatureGroup *group, FILE *file)
Write a feature graph to a file.
Function Documentation
FC_ReturnCode _fc_featureGroup_addFeature (FC_FeatureGroup * group, _FC_Feature * feature)
Helper routine to add a feature to the feature group.
Description:
Adds a feature to the feature Group. Helper routine to extend the internal structures of the group. It assigns the feature an ID and adds the feature to both the features array. The feature group now has ownership of the passed in feature.
Modifications:
MAR-20-2003 W Koegler Created
Parameters:
group input - pointer to feature group
feature input - pointer to a feature
Definition at line 1447 of file feature.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_FeatureGroup::features, _FC_Feature::id, and FC_FeatureGroup::numFeature.
Referenced by fc_featureGroup_newFeature().
  {
  int numFeature;
  _FC_Feature** temp_features;
  // check input
  if (!group || !feature)  {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Adding feature to a feature group.");
  // check feature group state // FIX?
  numFeature = group->numFeature;
  if (numFeature < 0)
    numFeature = 0;
  // NOTE: finish setting up feature before touching feature groups' info
  // (this also provides a check on the feature's fitness)
  // set feature ID
  feature->id = numFeature;
  // extend features array
  if (numFeature > 0) {
    temp_features = malloc(sizeof(_FC_Feature*) * (numFeature + 1));
    if (temp_features == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    memcpy(temp_features, group->features, sizeof(_FC_Feature*)*numFeature);
    free(group->features);
    group->features = temp_features;
  }
  else
    group->features = malloc(sizeof(_FC_Feature*));
    if (group->features == NULL ) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
  // add feature to features array
  group->features[numFeature] = feature;
  group->numFeature = numFeature + 1;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_featureGroup_addROI (FC_FeatureGroup * group, int featureID, int stepID, FC_Subset roi, int * roiID)
Helper routine to Add an ROI to the feature group.
Description:
Adds an ROI to the feature Group. Helper routine to extend the internal structures of the group. It uses the ROI's stepID to place it in the group's structures and sets its roiID. It also requires an argument specifying the id of the owning feature. The feature group now has ownership of the passed in ROI.
Modifications:
MAR-19-2003 W Koegler Created
fc_isSubsetValid(roi) ||
Parameters:
group input - pointer to feature group
featureID input - the ID of the feature that owns ROI
stepID input - the stepID of the ROI
roi input - the ROI
roiID output - the ID of the roi within the step on the group
Definition at line 1515 of file feature.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_FeatureGroup::numROIperStep, FC_FeatureGroup::numStep, FC_FeatureGroup::roiFeatureIDs, and FC_FeatureGroup::rois.
Referenced by fc_featureGroup_continueFeature(), and fc_featureGroup_newFeature().
  {
  int i;
  FC_Subset** temp_rois;
  FC_Subset* temp_step_rois;
  int numROI;
  int new_numStep;
  int* temp_numROIperStep;
  int** temp_roiFeatureIDs;
  int* temp_step_roiFeatureIDs;
  // default output
  if (roiID)
    *roiID = -1;
  // check input
  if (!group || featureID < 0 || stepID < 0 || /*!fc_isSubsetValid(roi) ||*/
      !roiID)  {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Adding ROI a feature group.");
  // NOTE: finish setting up ROI before touching feature groups' info
  // (this also provides a check on the ROI's fitness)
  // get next roi ID
  if (stepID < group->numStep)
    *roiID = group->numROIperStep[stepID];
  else
    *roiID = 0; // first in the next step
  // if needed, extend numROI & outer level of roiFeatureIDs & rois (over steps)
  if (stepID >= group->numStep) {
    new_numStep = stepID + 1;
    // allocate arrays
    temp_numROIperStep = malloc(sizeof(int)*new_numStep);
    temp_roiFeatureIDs = malloc(sizeof(int*)*new_numStep);
    temp_rois = malloc(sizeof(FC_Subset*)*new_numStep);
    if (temp_numROIperStep == NULL || temp_rois == NULL ||
        temp_roiFeatureIDs == NULL ) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    // copy existing values
    memcpy(temp_numROIperStep, group->numROIperStep,
           sizeof(int)*group->numStep);
    memcpy(temp_roiFeatureIDs, group->roiFeatureIDs,
           sizeof(int*)*group->numStep);
    memcpy(temp_rois, group->rois, sizeof(FC_Subset*)*group->numStep);
    // initialize new values
    for (i = group->numStep; i < new_numStep; i++) {
      temp_numROIperStep[i] = 0;
      temp_roiFeatureIDs[i] = NULL;
      temp_rois[i] = NULL;
    }
    // swap pointers
    free(group->numROIperStep);
    group->numROIperStep = temp_numROIperStep;
    free(group->roiFeatureIDs);
    group->roiFeatureIDs = temp_roiFeatureIDs;
    free(group->rois);
    group->rois = temp_rois;
    // set numStep
    group->numStep = new_numStep;
  }
  // extend the inner roiFeatureIDs and rois arrays for this specific step
  numROI = group->numROIperStep[stepID];
  if (numROI < 1) {
    group->roiFeatureIDs[stepID] = malloc(sizeof(int));
    group->rois[stepID] = malloc(sizeof(FC_Subset));
    if (group->roiFeatureIDs[stepID] == NULL || group->rois[stepID] == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
  }
  else {
    temp_step_roiFeatureIDs = malloc(sizeof(int)*(numROI+1));
    temp_step_rois = malloc(sizeof(FC_Subset)*(numROI+1));
    if (temp_step_roiFeatureIDs == NULL || temp_step_rois == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    memcpy(temp_step_roiFeatureIDs, group->roiFeatureIDs[stepID],
           sizeof(int)*numROI);
    for (i = 0; i < numROI; i++)
      temp_step_rois[i] = group->rois[stepID][i];
    free(group->roiFeatureIDs[stepID]);
    group->roiFeatureIDs[stepID] = temp_step_roiFeatureIDs;
    free(group->rois[stepID]);
    group->rois[stepID] = temp_step_rois;
  }
  // add the new roi
  // FIX the featureID will be added when it is assigned
  group->roiFeatureIDs[stepID][numROI] = featureID;
  group->rois[stepID][numROI] = roi;
  group->numROIperStep[stepID]++;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_writeFeatureGraph (FC_FeatureGroup * group, FILE * file)
Write a feature graph to a file.
Description:
Prints code that the program 'dot' in ATT&T's graphviz package can convert to a pretty picture of the graph of the features.
Modifications:
APR-01-2003 W Koegler Created
Parameters:
group input - pointer to the feature group
file input - pointer to the file
Definition at line 1820 of file feature.c.
References _FC_Feature::childIDs, fc_featureGroup_getNumFeature(), FC_FILE_IO_ERROR, fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_FeatureGroup::features, _FC_Feature::numChild, FC_FeatureGroup::numFeature, _FC_Feature::numParent, _FC_Feature::numROI, FC_FeatureGroup::numStep, and _FC_Feature::stepIDs.
Referenced by fc_printFeatureGraph(), and fc_writeFeatureGraph().
  {
  int i, j;
  int numFeature;
  char name[1024];
  char endName[1024];
  char childName[1024];
  char** stepNames;
  _FC_Feature* feature;
  // check input (group already checked?)
  if (!group || !file) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  fc_featureGroup_getNumFeature(group, &numFeature);
  if (numFeature < 1) {
    fc_printfErrorMessage("Cannot write graph of empty feature group");
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Writing feature graph to a file.");
  // NOTE: lots of things must be enclosed in quotes so there are
  //       lots of  \" 's, yuck!
  //---start graph
  // try the first one, if ok assume the rest will be ok
  fprintf(file, "digraph G {\n");
  if (fprintf(file, "orientation = portrait;\n") < 0)
    return FC_FILE_IO_ERROR;
  fprintf(file, "size = \"10,7.5\"; \n");
  fprintf(file, "ranksep = \"0.25\"; \n");
  fprintf(file, "node [height=0.25,width=0.25];\n");
  fflush(NULL);
  //---make step names
  stepNames = malloc(sizeof(char*)*group->numStep);
  if (stepNames == NULL ) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < group->numStep; i++) {
    stepNames[i] = malloc(sizeof(char)*1024);
    if (stepNames[i] == NULL ) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    sprintf(stepNames[i], "T%d", i);
  }
  //---write time line graph
  fprintf(file, "\n");
  fprintf(file, "{ node [shape=box]; \n");
  fprintf(file, "\"%s\"", stepNames[0]);
  fflush(NULL);
  for (i = 1; i < group->numStep; i++) {
    fprintf(file, " -> \"%s\"", stepNames[i]);
    fflush(NULL);
  }
  fprintf(file, " ; \n");
  fprintf(file, "} \n\n");
  fflush(NULL);
  //---for each feature
  for (i = 0; i < group->numFeature; i++) {
    // dereference feature once
    feature = group->features[i];
    // default names
    sprintf(name, "%d", i);
    sprintf(endName, "%s", name); // same as name
    fflush(NULL);
    //---if feature has no parent, distinguish it's node
    if (feature->numParent == 0)
      fprintf(file, "\"%s\" [style=filled,color=grey];\n", name);
    //---set rank same as it's start step, will show up at same position
    fprintf(file, "{ rank = same; \"%s\" ; \"%s\" ; }\n",
           stepNames[feature->stepIDs[0]], name);
    //---if feature exists for more than 1 step, make an "end" node
    //   and connect to start node
    if (feature->numROI > 1) {
      sprintf(endName, "%s_end", name);
      // label="" makes it not get a label (default label is node name)
      fprintf(file, "\"%s\" [label=\"\", style=filled,color=black,"
             "shape=diamond,height=0.2,width=0.2] ;\n", endName);
      fprintf(file, "{ rank = same ; \"%s\"; \"%s\" ; }\n",
             stepNames[feature->stepIDs[feature->numROI-1]], endName);
      fprintf(file, "\"%s\" -> \"%s\"\n", name, endName);
    }
    fflush(NULL);
    //---do child edges
    for (j = 0; j < feature->numChild; j++) {
      sprintf(childName, "%d", feature->childIDs[j]);
      fprintf(file, "\"%s\" -> \"%s\"\n", endName, childName);
      fflush(NULL);
    }
  }
  // end of digraph;
  fprintf(file, "}\n");
  fflush(NULL);
  // free resources
  for (i = 0; i < group->numStep; i++)
    free(stepNames[i]);
  free(stepNames);
  return FC_SUCCESS;
}
FC_ReturnCode _fc_writeFeatureGroup (FC_FeatureGroup * group, FILE * file)
Print the contents of a feature group.
Description:
Helper routine writes features to the specified FILE Prints human readable information about the features in a featureGroup.
Modifications:
APR-01-2003 W Koegler Created
Parameters:
group input - pointer to the feature group
file input - pointer to the file
Definition at line 1732 of file feature.c.
References FC_FILE_IO_ERROR, fc_getFeatureChildIDs(), fc_getFeatureParentIDs(), fc_getFeatureROIs(), fc_getReturnCodeText(), fc_getSubsetName(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_FeatureGroup::features, FC_FeatureGroup::numFeature, _FC_Feature::numROI, and FC_FeatureGroup::numStep.
Referenced by fc_printFeatureGroup(), and fc_writeFeatureGroup().
  {
  int i, j;
  int numParent, numChild, numROI, *parentIDs, *childIDs, *stepIDs;
  FC_Subset *ROIs;
  char *temp_name;
  if (!group || !file) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Printing contents of a feature group.");
  // try the first one, if ok assume the rest will be ok
  if (fprintf(file, "Feature Group:\n") < 0)
    return FC_FILE_IO_ERROR;
  fprintf(file, "    numStep = %d, numFeature = %d\n", group->numStep,
          group->numFeature);
  fprintf(file, "\n");
  fflush(NULL);
  // for each feature
  for (i = 0; i < group->numFeature; i++) {
    // general feature info, numROI, parents & children
    fprintf(file, "Feature %d:\n", i);
    fflush(NULL);
    // parent ids
    fc_getFeatureParentIDs(group, i, &numParent, &parentIDs);
    fprintf(file, "    numParent = %d, IDs: ", numParent);
    if (numParent > 0) {
      fprintf(file, "%d", parentIDs[0]);
      for (j = 1; j < numParent; j++)
        fprintf(file, ", %d", parentIDs[j]);
    }
    fprintf(file, "\n");
    fflush(NULL);
    free(parentIDs);
    // child ids
    fc_getFeatureChildIDs(group, i, &numChild, &childIDs);
    fprintf(file, "    numChild  = %d, IDs: ", numChild);
    if (numChild > 0) {
      fprintf(file, "%d", childIDs[0]);
      for (j = 1; j < numChild; j++)
        fprintf(file, ", %d", childIDs[j]);
    }
    fprintf(file, "\n");
    fflush(NULL);
    free(childIDs);
    // rois
    fc_getFeatureROIs(group, i, &numROI, &stepIDs, &ROIs);
    fprintf(file, "    numROI = %d\n", numROI);
    fprintf(file, "    ROIs:\n");
    for (j = 0; j < group->features[i]->numROI; j++) {
      fc_getSubsetName(ROIs[j], &temp_name);
      fprintf(file, "        %d: stepID = %d, ROI = '%s'\n", j, stepIDs[j],
              temp_name);
      fflush(NULL);
      free(temp_name);
    }
    fprintf(file, "\n");
    fflush(NULL);
    free(stepIDs);
    free(ROIs);
  }
  return FC_SUCCESS;
}