FCLib: (Private)
(Private)
[Shape]
Functions
FC_ReturnCode _fc_initSFI_Array (_FC_SFI_ARRAY *sfi)
inits the sfi array
int _fc_addToSFI_Array (_FC_SFI_ARRAY *sfi, _FC_FACEINFO *fi)
add an sfi to the sfi array
FC_ReturnCode _fc_lookupInSFI_Array (_FC_SFI_ARRAY *sfi, int i, _FC_FACEINFO **fi)
looks for a fi index in sfi array
FC_ReturnCode _fc_removeFromSFI_Array (_FC_SFI_ARRAY *sfi, int i, _FC_FACEINFO **fi)
removes an item from the sfi array
int _fc_reallocSFI_Array (_FC_SFI_ARRAY *sfi)
reallocs the sfi array
void _fc_printSFI_Array (_FC_SFI_ARRAY *sfi)
prints the sfi array
void _fc_freeSFI_Array (_FC_SFI_ARRAY *sfi)
frees the sfi array
FC_ReturnCode _fc_buildFaceInfoListFromSubset (FC_Subset subset, _FC_SFI_ARRAY *skinlist)
return sorted array of ptrs to faceinfos for the subset skin
FC_ReturnCode _fc_buildFaceInfoListFromShape (FC_Shape *shape, _FC_SFI_ARRAY *skinlist)
given a current shape, return sorted array of ptrs to faceinfos for the shape sides
FC_ReturnCode _fc_getOutwardFaceNormal (FC_Mesh mesh, int faceID, int elemID, FC_Vector *normal)
Returns outward normal vector for a given face on a given element.
FC_ReturnCode _fc_createShapePartsFromFaceInfoList (FC_Mesh mesh, _FC_SFI_ARRAY *in_faceinfolist, char **basename, double comp_angle, int shared_dim, int *numSides, FC_Subset **newFaceSubsets, FC_Subset **newElemSubsets, int ***adjmatrix)
makes the shape parts from the faceinfolist
Function Documentation
int _fc_addToSFI_Array (_FC_SFI_ARRAY * sfi, _FC_FACEINFO * fi)
add an sfi to the sfi array
Description:
adds an sfi to the sfi array. returns 1 if it added it, 0 if there is one already there.
Modifications:
06/07/06 ACG created
Definition at line 132 of file shape.c.
References _faceinfo::faceID, fc_getReturnCodeText(), FC_MEMORY_ERROR, fc_printfErrorMessage, _sfi_array::maxVals, _sfi_array::numVals, and _sfi_array::vals.
Referenced by _fc_buildFaceInfoListFromShape(), and _fc_buildFaceInfoListFromSubset().
 {
  int low, high, mid;
  int indexx;
  _FC_FACEINFO **temp;
  if (sfi->vals == NULL){ //empty
    sfi->vals = (_FC_FACEINFO**)malloc(sizeof(_FC_FACEINFO*));
    if (sfi->vals == NULL){
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    sfi->numVals = 1;
    sfi->maxVals = 1;
    sfi->vals[0] = fi; //gets the ptr, now responsible for the memory
    return 1;
  }
  //binary search
  low = 0;
  high = sfi->numVals-1;
  while(low <= high){
    mid = (low+high)/2;
    //      printf("low %d high %d mid %d\n",low,high,mid);
    if ((sfi->vals[mid])->faceID == fi->faceID){
      return 0;
    } else if ((sfi->vals[mid])->faceID < fi->faceID){
      low = mid+1;
    } else{
      high = mid -1;
    }
  }
  //either goes below or above mid. realloc if necessary
  indexx = ((sfi->vals[mid])->faceID > fi->faceID ? mid:mid+1);
  if (sfi->numVals >= sfi->maxVals){ //grow
    temp = (_FC_FACEINFO**)realloc(sfi->vals,(2*sfi->maxVals)*sizeof(_FC_FACEINFO*));
    if (temp == NULL){
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    sfi->maxVals*=2;
    sfi->vals = temp;
  }
  //memcpy didnt work right when i moved more than 1 element up
  memmove((sfi->vals)+indexx+1,(sfi->vals)+indexx,
       (sfi->numVals-indexx)*sizeof(_FC_FACEINFO*));
  sfi->vals[indexx] = fi; //gets the ptr, now responsible for the memory
  sfi->numVals++;
  return 1;
}
FC_ReturnCode _fc_buildFaceInfoListFromShape (FC_Shape * shape, _FC_SFI_ARRAY * skinlist)
given a current shape, return sorted array of ptrs to faceinfos for the shape sides
Description:
Similiar to _fc_buildFaceInfoListFromShape, but in that case you have the subset of the entire shape elements, including its innards. This method is instead called when you are going to reshape, and therefore have only the information about the sides.
Todo:
will this work ?
untested
Modifications:
08/19/06 ACG created
Parameters:
shape input -shape
skinlist output - sorted array of faceinfos
Definition at line 593 of file shape.c.
References _fc_addToSFI_Array(), _fc_freeSFI_Array(), _fc_getOutwardFaceNormal(), _fc_initSFI_Array(), _faceinfo::elemID, FC_Shape::elems, _faceinfo::faceID, FC_Shape::faces, FC_AT_ELEMENT, FC_AT_FACE, fc_convertIntArrayToSortedIntArray(), fc_deleteIntFromSortedIntArray(), FC_ERROR, fc_freeSortedIntArray(), fc_getMeshEntityChildren(), fc_getMeshFromSubset(), fc_getSortedIntArrayBack(), fc_getSubsetMembersAsArray(), FC_INPUT_ERROR, fc_popSortedIntArrayBack(), fc_printfErrorMessage, FC_SUCCESS, _faceinfo::normal, FC_Shape::numSides, and FC_SortedIntArray::numVal.
Referenced by fc_reshapeByAngle().
   {
  FC_ReturnCode rc;
  FC_Mesh mesh;
  int i,k;
  if (!shape || shape->numSides < 1){
    return FC_INPUT_ERROR;
  }
  rc = fc_getMeshFromSubset(shape->faces[0],&mesh);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("Can't get mesh from subset");
    return rc;
  }
  rc = _fc_initSFI_Array(skinlist);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("Can't init SFI array");
    return rc;
  }
  //each face can only be a child of one element making up the sides
  for (i = 0; i < shape->numSides; i++){
    int *farr, *earr, numf, nume;
    FC_SortedIntArray facearr;
    FC_SortedIntArray elemarr;
    rc = fc_getSubsetMembersAsArray(shape->faces[i],&numf,&farr);
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("Can't get face members");
      _fc_freeSFI_Array(skinlist);
      return rc;
    }
    rc = fc_getSubsetMembersAsArray(shape->elems[i],&nume,&earr);
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("Can't get elem members");
      free(farr);
      _fc_freeSFI_Array(skinlist);
      return rc;
    }
    rc = fc_convertIntArrayToSortedIntArray(numf,farr,1,&facearr);
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("Can't convert face array");
      free(farr);
      free(earr);
      _fc_freeSFI_Array(skinlist);
      return rc;
    }
    rc = fc_convertIntArrayToSortedIntArray(nume,earr,1,&elemarr);
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("Can't convert elem array");
      fc_freeSortedIntArray(&facearr);
      free(earr);
      _fc_freeSFI_Array(skinlist);
      return rc;
    }
    while(elemarr.numVal){
      int curre;
      int numChild, *childIDs;
      rc = fc_getSortedIntArrayBack(&elemarr,&curre);
      if (rc != FC_SUCCESS){
     fc_printfErrorMessage("Can't get last elem");
     fc_freeSortedIntArray(&facearr);
     fc_freeSortedIntArray(&elemarr);
     _fc_freeSFI_Array(skinlist);
     return rc;
      }
      rc = fc_getMeshEntityChildren(mesh,FC_AT_ELEMENT,curre,
                        FC_AT_FACE,&numChild,&childIDs);
      if (rc != FC_SUCCESS){
     fc_printfErrorMessage("Can't get elem children");
     fc_freeSortedIntArray(&facearr);
     fc_freeSortedIntArray(&elemarr);
     _fc_freeSFI_Array(skinlist);
     return rc;
      }
      for (k = 0; k < numChild;k++){
     int ret;
     if (fc_deleteIntFromSortedIntArray(&facearr,childIDs[k])){
       _FC_FACEINFO *face_data = (_FC_FACEINFO*)malloc(sizeof(_FC_FACEINFO));
       face_data->faceID = childIDs[k];
       face_data->elemID = curre;
       rc = _fc_getOutwardFaceNormal(mesh, face_data->faceID,
                         face_data->elemID,
                         &(face_data->normal));
       if (rc != FC_SUCCESS){
         fc_printfErrorMessage("Can't get normal for this face");
         fc_freeSortedIntArray(&facearr);
         fc_freeSortedIntArray(&elemarr);
         _fc_freeSFI_Array(skinlist);
         return FC_ERROR;
       }
       ret = _fc_addToSFI_Array(skinlist,face_data);
       if (!ret){
         fc_printfErrorMessage("Can't add to SFI array");
         fc_freeSortedIntArray(&facearr);
         fc_freeSortedIntArray(&elemarr);
         _fc_freeSFI_Array(skinlist);
         if (face_data) free(face_data);
         return FC_ERROR;
       }
     }
      }//loop over children of this element
      free(childIDs);
      fc_popSortedIntArrayBack(&elemarr);
    } //loop over elements of this side
    //now all the faces and elems should have been moved to the skinlist
    if (facearr.numVal && elemarr.numVal){
      fc_printfErrorMessage("there are still remaining faces or elems for this side");
      fc_freeSortedIntArray(&facearr);
      fc_freeSortedIntArray(&elemarr);
      _fc_freeSFI_Array(skinlist);
      return FC_ERROR;
    }
    fc_freeSortedIntArray(&facearr);
    fc_freeSortedIntArray(&elemarr);
  }//loop over sides
  return FC_SUCCESS;
}
FC_ReturnCode _fc_buildFaceInfoListFromSubset (FC_Subset subset, _FC_SFI_ARRAY * skinlist)
return sorted array of ptrs to faceinfos for the subset skin
Description:
This is a variation of fc_getSubsetSkin that also returns the element and the normal giving rise to those faces. Its easier to get these all at the same time.
There seems to be an issue in skin on how to handle an empty subset. Here I will return empty subset as an error.
Note: Since this is based on skin, in theory it handles not just element-faces but other topodim as well. In those cases I don't think there is a guarentee that the face-equivalent item is unique in the set.
This is a helper for the revised _fc_getSubsetShapes. It is a combination of the old _fc_makeSubsetSkinFaceListWithElementData and the the old _fc_makeFaceListWithNormalsData. This was then renamed from getDetailedSkinData
Todo:
replaced the linked list with a numFace allocated array to simulate a hash table to speed things up. will want a real hash table
Modifications:
06/02/06 ACG created from the elem data and the normal data to increase efficiency of sides.
06/05/06 ACG trying replacing the linked list with a numFace allocated array to simulate a hash table to speed things up.
06/07/06 ACG replacing the skinlist with a sorted array of _FC_FACEINFO since it will need to search it later
08/19/06 ACG renamed from getDetailedSkinData.
Parameters:
subset input - subset
skinlist output - sorted array of faceinfos
Definition at line 402 of file shape.c.
References _fc_addToSFI_Array(), _fc_getOutwardFaceNormal(), _fc_initSFI_Array(), _faceinfo::elemID, _faceinfo::faceID, FC_AT_ELEMENT, FC_AT_FACE, FC_AT_WHOLE_MESH, FC_ERROR, fc_getAssociationTypeText(), fc_getElementTypeTopoDim(), fc_getMeshEntityChildren(), fc_getMeshEntityElementType(), fc_getMeshFromSubset(), fc_getMeshNumElement(), fc_getMeshNumEntity(), fc_getReturnCodeText(), fc_getSubsetInfo(), fc_getSubsetMembersAsArray(), fc_getSubsetNumMember(), FC_INPUT_ERROR, fc_isSubsetValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, and _faceinfo::normal.
Referenced by fc_getSubsetShapes().
   {
  FC_ReturnCode rc;
  int i, j;
  FC_AssociationType assoc_orig, assoc_skin;
  int numMember, *memberIDs, maxNumSkin, *counts, numChild, *childIDs;
  int topodim_orig;
  FC_Mesh mesh;
  FC_ElementType elemType;
  int *temp_hasharray; //this wil be replaced by a real hashtable later
  //---default return values
  //  if (skinlist)
  //    *skinlist = NULL;
  // check input
  if (!fc_isSubsetValid(subset) ||
      !skinlist) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Creating faceinfo list");
  // Get info from subset and a little more checking
  rc = fc_getSubsetNumMember(subset, &numMember);
  if (rc != FC_SUCCESS)
    return rc;
  if (numMember < 1) {
    fc_printfErrorMessage("Can't create skin of empty subset");
    return FC_INPUT_ERROR;
  }
  rc = fc_getSubsetInfo(subset, NULL, NULL, &assoc_orig);
  if (rc != FC_SUCCESS)
    return rc;
  if (!(assoc_orig == FC_AT_ELEMENT || assoc_orig == FC_AT_WHOLE_MESH)){
    fc_printfErrorMessage("Can't handle subset with association type %s",
                          fc_getAssociationTypeText(assoc_orig));
    return FC_INPUT_ERROR;
  }
  rc = fc_getMeshFromSubset(subset, &mesh);
  if (rc != FC_SUCCESS)
    return rc;
  // determine topodim of the members
  rc = fc_getMeshEntityElementType(mesh, assoc_orig, 0, &elemType);
  if (rc != FC_SUCCESS){
    free(memberIDs);
    return rc;
  }
  topodim_orig = fc_getElementTypeTopoDim(elemType);
  if (topodim_orig != 3){
    fc_printfErrorMessage("Invalid topodim %d (must be 3)\n",topodim_orig);
    return FC_INPUT_ERROR;
  }
  assoc_skin = FC_AT_FACE;
  // Get members -- If subset is whole, get all elements
  if (assoc_orig == FC_AT_WHOLE_MESH) {
    assoc_orig = FC_AT_ELEMENT;
    rc = fc_getMeshNumElement(mesh, &numMember);
    if (rc != FC_SUCCESS)
      return rc;
    memberIDs = malloc(numMember*sizeof(int));
    if (!memberIDs) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    for (i = 0; i < numMember; i++)
      memberIDs[i] = i;
  }
  else {
    rc = fc_getSubsetMembersAsArray(subset, &numMember, &memberIDs);
    if (rc != FC_SUCCESS)
      return rc;
  }
  rc = fc_getMeshNumEntity(mesh, assoc_skin, &maxNumSkin);
  if (rc != FC_SUCCESS){
    free(memberIDs);
    return rc;
  }
  counts = calloc(maxNumSkin, sizeof(int));
  if (!counts) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  //adding all the faces for each element with the element id as the data.
  //if a face arises again from a different element, then remove it
  temp_hasharray = (int*)malloc(maxNumSkin*sizeof(int));
  if (temp_hasharray == NULL){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < maxNumSkin; i++){
    temp_hasharray[i] = -1;
  }
  //  printf("determining the skin faces and elems\n");
  for (i = 0; i < numMember; i++) {
    fc_getMeshEntityChildren(mesh, assoc_orig, memberIDs[i], assoc_skin,
                    &numChild, &childIDs);
    for (j = 0; j < numChild; j++){
      switch(++counts[childIDs[j]]){
      case 1:{ //add it
     temp_hasharray[childIDs[j]] = memberIDs[i];
     break;
      }
      case 2:{ //remove it
     temp_hasharray[childIDs[j]] = -1;
     break;
      }
      default:  //its gone already
     //      printf("skipping face %d element %d\n",childIDs[j],memberIDs[i]);
     break;
      }
    }
    free(childIDs);
  }
  free(memberIDs);
  free(counts);
  //  printf("done determining the skin faces and elems\n");
  //  printf("buiding the SFI array and determining the normals\n");
  //since its already sorted there is a faster way to add things, but we will
  //use the interface for now
  rc = _fc_initSFI_Array(skinlist);
  for (i = maxNumSkin-1; i >= 0; i--){
    if (temp_hasharray[i] != -1){
      int test = 0;
      _FC_FACEINFO *face_data = (_FC_FACEINFO*)malloc(sizeof(_FC_FACEINFO));
      face_data->faceID = i;
      face_data->elemID = temp_hasharray[i];
      //      printf("adding face %d element %d\n",face_data->faceID,
      //       face_data->elemID);
      rc = _fc_getOutwardFaceNormal(mesh, i, temp_hasharray[i],&(face_data->normal));
      if (rc != FC_SUCCESS){
     return FC_ERROR;
      }
      test = _fc_addToSFI_Array(skinlist,face_data);
      if (!test){
     free(temp_hasharray);
     if (face_data) free(face_data);
     //skinlist will be freed outside
     return rc;
      }
    }
  }
  //  printf("done building the skinlist and determining the normals\n");
  free(temp_hasharray);
  return FC_SUCCESS;
}
FC_ReturnCode _fc_createShapePartsFromFaceInfoList (FC_Mesh mesh, _FC_SFI_ARRAY * in_faceinfolist, char ** basename, double comp_angle, int shared_dim, int * numSides, FC_Subset ** newFaceSubsets, FC_Subset ** newElemSubsets, int *** adjmatrix)
makes the shape parts from the faceinfolist
Description: makes the shape parts from the faceinfolist. This was the major guts of the old _fc_getSubsetSides (now defunct as a result), but I'm pulling it out in order to be able to do a reangle of an existing shape.
Todo:
will need to standardize on devouring the faceinfo list, in case of input error etc
just writing this now, it isnt tested
Modifications:
10/04/05 ACG created as surfacesegment. trying to keep this as close as possible in algorithm to fc_segment
11/30/05 ACG changed name from surfaceSegment to getSubsetSides to reflect new terminology.
01/13/06 ACG rewrote using new WSK algorithm in fc_segment
06/06/06 ACG replacing the currlist (built from the working list) with two growing int arrays which are then handed to the subsets. this drops out one of the (sorting) linked lists.
06/07/06 ACG replacing the working list (built from the face list) with a growing unsorted array of _FC_FACEINFO ptrs. this drops out another sorted linked list.
06/07/06 ACG replacing the faceinfo list (built from buildFaceInfoList) with a growing sorted array of _FC_FACEINFO ptrs. this drops out another sorted linked list. We wont be adding anything to it, but the search will be faster
06/16/06 ACG warning about creases
06/28/06 ACG moved to private
08/16/06 ACG created from splitting out of _fc_getSubsetSides. renamed to createShapePartsFromFaceInfoList
2 subsets(faces and elems) - add the whole array at once
Parameters:
mesh input -- the mesh
in_faceinfolist input - the starting array with all the facedata, if this method is successful, will end empty
basename input - base name for the sides
comp_angle input - if two neighboring faces differ by more than this angle then they are considered to be on different surfaces.
shared_dim input - the minimum dimensionality of shared part of neighbors of faces
numSides output - number of new subsets
newFaceSubsets output - array of segmented regions (by face)
newElemSubsets output - array of segmented regions (by element)
adjmatrix output - adjmatrix
Definition at line 893 of file shape.c.
References _fc_lookupInSFI_Array(), _fc_removeFromSFI_Array(), _faceinfo::elemID, _faceinfo::faceID, fc_addArrayMembersToSubset(), FC_AT_ELEMENT, FC_AT_FACE, fc_calcAngleBetweenVectors(), fc_createSubset(), FC_ERROR, fc_getMeshEntityNeighbors(), fc_getMeshNumFace(), fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, fc_printfWarningMessage, FC_SUCCESS, _intpair::ID1, _intpair::ID2, _faceinfo::normal, _sfi_array::numVals, and _sfi_array::vals.
Referenced by fc_getSubsetShapes(), and fc_reshapeByAngle().
   {
  FC_ReturnCode rc;
  char* temp_name;
  _FC_INTPAIR *edgePairs = NULL;
  int numEdgePairs = 0;
  int maxEdgePairs = 0;
  int *sideArray = NULL; //temporary till I get a hash table - edge face ID to side table
  int numMeshFace = 0;
  int numSegments; //these are temporary till we set up the new Shape Object
  FC_Subset* faceSegments = NULL;
  FC_Subset* elemSegments = NULL;
  int **intmatrix = NULL;
  int i,j;
  //---default return values
  if (numSides)
    *numSides = -1;
  if (newFaceSubsets)
    *newFaceSubsets = NULL;
  if (newElemSubsets)
    *newElemSubsets = NULL;
  if (adjmatrix)
    *adjmatrix = NULL;
  // check input
  if (!in_faceinfolist || !numSides ||
      shared_dim < 0 || shared_dim > 1  || !adjmatrix ||
      !newFaceSubsets || ! newElemSubsets || comp_angle < 0 ||
      comp_angle > 180) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("getting shapeinfo from faceinfolist");
  if (in_faceinfolist->numVals == 0){ //return if empty subset
    *numSides = 0;
    return FC_SUCCESS;
  }
  // setup space for names of segments
  temp_name = malloc((strlen(*basename)+30)*sizeof(char));
  if (temp_name == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  //set up space for edgepairs
  edgePairs = (_FC_INTPAIR*)malloc(sizeof(_FC_INTPAIR));
  if (edgePairs == NULL){
    free(temp_name);
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  numEdgePairs = 0;
  maxEdgePairs = 1;
  //set up space for sideArray, to be replaced by a hashtable
  rc = fc_getMeshNumFace(mesh,&numMeshFace);
  if (rc != FC_SUCCESS){
    free(temp_name);
    return rc;
  }
  sideArray = (int*)malloc(numMeshFace*sizeof(int));
  if (sideArray == NULL){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i=0 ; i < numMeshFace; i++){
    sideArray[i] = -1;
  }
  //  printf("segmenting faceinfo list\n");
  //---segment the faceinfo list
  numSegments = 0;
  while(in_faceinfolist->numVals){ // each pass will create a new side
    //first set up data structures....
    //info list which will contain members of the current side
    //being built. this list needs to be added to, popped off
    //either end and order doesnt matter (neither here or later).
    //contains info on the face, assoc elem, and normal.
    //therefore choosing faceinfo array. allocating space for
    //1 since we know there will be at least one in this face
    //(that is - the one we pop off the facelist
    //directly below)
    _FC_FACEINFO** working_list  = (_FC_FACEINFO**)malloc(sizeof(_FC_FACEINFO*));
    int numworkinglist = 0;
    int maxworkinglist = 1;
    //id arrays for the current side. chose (unsorted) int arrays
    //becuase its the most efficient way to later add the IDs to the
    ///2 subsets(faces and elems) - add the whole array at once
    //(subset will do a sorting and uniqueness of the array).
    //they dont need to be sorted or searched. start by
    //allocating space for 1, since we know there wil be at least
    //1 side in this face (that is - the one we pop off the facelist
    //directly below
    int *currside_faces = (int*)malloc(sizeof(int));
    int *currside_elems = (int*)malloc(sizeof(int));
    int numcurrsideIDs = 0;
    int maxcurrsideIDs = 1;
    if (!working_list || ! currside_faces || ! currside_elems){
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    //     printf("working on side %d\n",numSegments);
    //initialize - pop off the last one and addit to the working list
    _FC_FACEINFO *temp_node = in_faceinfolist->vals[in_faceinfolist->numVals-1];
    in_faceinfolist->numVals--;
    working_list[0]= temp_node; //we know we have space for it
    numworkinglist = 1;
    // "grow" connected region from seed by checking neighbors
    while(numworkinglist){
      int currID;
      FC_Vector currNormal;
      // remove last entity from working list and put it on
      // the 3 lists with side info
      _FC_FACEINFO *currnode = working_list[numworkinglist-1];
      numworkinglist--;
      sideArray[currnode->faceID] = numSegments; //fill in its side in the array (hashtable)
      if (numcurrsideIDs == maxcurrsideIDs){//grow the lists
     int* temp = (int*)realloc(currside_faces,(2*maxcurrsideIDs)*sizeof(int));
     if (temp == NULL){
       fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
       return FC_MEMORY_ERROR;
     }
     currside_faces = temp;
     temp = (int*)realloc(currside_elems,(2*maxcurrsideIDs)*sizeof(int));
     if (temp == NULL){
       fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
       return FC_MEMORY_ERROR;
     }
     currside_elems = temp;
     maxcurrsideIDs*=2;
      }
      currside_faces[numcurrsideIDs] = currnode->faceID;
      currside_elems[numcurrsideIDs] = currnode->elemID;
      numcurrsideIDs++;
      //we only need these if there is a neighbor, but it
      //allows us to free the currnode
      currID = currnode->faceID;
      for (i = 0; i < 3; i++){
     currNormal[i] = currnode->normal[i];
      }
      free(currnode); //free the actual info, not the ptr.
      if (in_faceinfolist->numVals){ //we have neighbors to check (otherwise
     // just loop till empty out working list
     int *neighborIDs;
     int numNeighbor;
     //   printf("checking neighbors of currid = %d\n",currID);
     // Move neighbors of that entity that satisfy the angle criteria
     // that are in the orig list to the working list
     rc = fc_getMeshEntityNeighbors(mesh, currID, FC_AT_FACE, shared_dim,
                           &numNeighbor, &neighborIDs);
     if (rc != FC_SUCCESS)
       //clean up
       return rc;
     for (i = 0; i < numNeighbor; i++) {
       double angle;
       _FC_FACEINFO *node;
       rc = _fc_lookupInSFI_Array(in_faceinfolist,neighborIDs[i],&node);
       if (rc != FC_SUCCESS){
         fc_printfErrorMessage("cant check for key in list");
         //clean up
         return rc;
       }
       if (node == NULL){ //this face is not part of the skin
         //        printf("face %d in not ont he skin\n",neighborIDs[i]);
         continue;
       }
       //does this neighbor satisfy the angle criteria ?
       rc = fc_calcAngleBetweenVectors(currNormal,
                           node->normal,
                           &angle);
       if (rc != FC_SUCCESS){
         fc_printfErrorMessage("cant get angle between vectors");
         //clean up
         return rc;
       }
       if (angle > comp_angle){
         //this face is not part of this side, but it is an edgepair
         void *temp;
         //        printf("face %d in not on the side, but is an edge\n",node->faceID);
         if (numEdgePairs + 1 > maxEdgePairs) {
           maxEdgePairs *= 2;
           temp = realloc(edgePairs, maxEdgePairs*sizeof(_FC_INTPAIR));
           if (temp == NULL) {
          fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
          return FC_MEMORY_ERROR;
           }
           edgePairs = temp;
         }
         edgePairs[numEdgePairs].ID1 = currID;
         edgePairs[numEdgePairs].ID2 = node->faceID;
         numEdgePairs++;
         continue;
       }
       //its part of the skin and its on this side
       //   printf("face %d is on the side\n",node->faceID);
       rc = _fc_removeFromSFI_Array(in_faceinfolist,neighborIDs[i],&node);
       if (rc != FC_SUCCESS){
         fc_printfErrorMessage("cant remove node");
         //clean up
         return rc;
       }
       //now add that data to the workinglist
       if (numworkinglist == maxworkinglist){ //grow the array
         _FC_FACEINFO** temp = (_FC_FACEINFO**)realloc(working_list,
                                     (2*maxworkinglist)*sizeof(_FC_FACEINFO*));
         if (temp == NULL){
           fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
           return FC_MEMORY_ERROR;
         }
         working_list = temp;
         maxworkinglist*=2;
       }
       working_list[numworkinglist] = node; //gets the ptr
       numworkinglist++;
     } //end for
     free(neighborIDs);
      } //end if facelist != NULL
    } // end while working list
    free(working_list); //this is the array itself, there are no members now
    //now weve got faces and elem arrays for this side
    { // create subsets from arrays of IDs
      void *temp;
      //      printf("making subsets from arrays\n");
      temp = realloc(faceSegments, (numSegments+1)*sizeof(FC_Subset));
      if (temp == NULL) {
     fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
     return FC_MEMORY_ERROR;
      }
      faceSegments = temp;
      sprintf(temp_name, "%s_FaceSurface%d", *basename, numSegments);
      rc = fc_createSubset(mesh, temp_name, FC_AT_FACE, &faceSegments[numSegments]);
      if (rc != FC_SUCCESS) {
     fc_printfErrorMessage("cannot create newFaceSubset[%d]", numSegments);
     //clean up
     return FC_ERROR;
      }
      rc = fc_addArrayMembersToSubset(faceSegments[numSegments], numcurrsideIDs,
                          currside_faces);
      if (rc != FC_SUCCESS) {
     fc_printfErrorMessage("cannot add ids to facesegment");
     //clean up
     return FC_ERROR;
      }
      temp = realloc(elemSegments, (numSegments+1)*sizeof(FC_Subset));
      if (temp == NULL) {
     fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
     return FC_MEMORY_ERROR;
      }
      elemSegments = temp;
      sprintf(temp_name, "%s_ElemSurface%d", *basename, numSegments);
      rc = fc_createSubset(mesh, temp_name, FC_AT_ELEMENT, &elemSegments[numSegments]);
      if (rc != FC_SUCCESS) {
     fc_printfErrorMessage("cannot create newElemSubset[%d]", numSegments);
     //clean up
     return FC_ERROR;
      }
      rc = fc_addArrayMembersToSubset(elemSegments[numSegments], numcurrsideIDs,
                          currside_elems);
      if (rc != FC_SUCCESS) {
     fc_printfErrorMessage("cannot add ids to facesegment");
     //clean up
     return FC_ERROR;
      }
      //clean up currside info
      free(currside_faces);
      free(currside_elems);
      numSegments++;
    } //created subsets
  } // while orig_list
  free(in_faceinfolist->vals); //free the array of ptrs, already freed what they are pting to
  //adjmatrix calculation
  intmatrix = (int**)malloc(numSegments*sizeof(int*));
  for (i = 0; i < numSegments; i++){
    intmatrix[i] = (int*)calloc(numSegments,sizeof(int));
  }
  //  printf("internal calc of adjmatrix\n");
  for (i = 0; i < numEdgePairs; i++){
    //      printf("ID %d side %d ID %d side %d\n",edgePairs[i].ID1,sideArray[edgePairs[i].ID1],
    //        edgePairs[i].ID2,sideArray[edgePairs[i].ID2]);
    if (sideArray[edgePairs[i].ID1] == sideArray[edgePairs[i].ID2]){
      fc_printfWarningMessage("Faces %d %d are edges but both on same side %d - Might be a crease\n",
                     edgePairs[i].ID1,edgePairs[i].ID2,sideArray[edgePairs[i].ID1]);
    }else{
      intmatrix[sideArray[edgePairs[i].ID1]][sideArray[edgePairs[i].ID2]] = 1;
      intmatrix[sideArray[edgePairs[i].ID2]][sideArray[edgePairs[i].ID1]] = 1;
    }
  }
  if (0){
    //print adj matrix
    printf("before leaving shape parts\n");
    for (i = 0; i < numSegments; i++){
      for (j = 0; j < numSegments; j++){
     printf("%d ", intmatrix[i][j]);
      }
      printf("\n");
    }
  }
  // cleanup (orig_list is empty)
  free(temp_name);
  free(sideArray);
  free(edgePairs);
  //return values
  *numSides = numSegments;
  *newFaceSubsets = faceSegments;
  *newElemSubsets = elemSegments;
  *adjmatrix = intmatrix;
  return FC_SUCCESS;
}
void _fc_freeSFI_Array (_FC_SFI_ARRAY * sfi)
frees the sfi array
Description:
frees the sfi array
Modifications:
06/07/06 ACG created
Definition at line 347 of file shape.c.
References _sfi_array::maxVals, _sfi_array::numVals, and _sfi_array::vals.
Referenced by _fc_buildFaceInfoListFromShape(), fc_getSubsetShapes(), and fc_reshapeByAngle().
  {
  int i;
  for(i = 0; i < sfi->numVals; i++){
    //free each face info
    _FC_FACEINFO *fi = sfi->vals[i];
    free(fi);
  }
  //free the array if it isnt already
  if (sfi->vals) free(sfi->vals);
  sfi->vals = NULL;
  sfi->numVals = 0;
  sfi->maxVals = 0;
}
FC_ReturnCode _fc_getOutwardFaceNormal (FC_Mesh mesh, int faceID, int elemID, FC_Vector * normal)
Returns outward normal vector for a given face on a given element.
Description:
Returns outward normal vector for a given face on a given element Uses assumption of fc_calcSurfaceNormals that this is only correct for planar elements (like triangles and planar quads), but checking FaceType rather than ElemType.
Todo:
faster search
check mem allocation, esp in inner _fc_calcSurfaceNormal
does this need to be explicitly unittested? it is tested inso far as getSubsetSides and getPlanarSideNormal have been tested
Modifications:
10/07/05 ACG created
12/19/2005 ACG moved from Topological Relations to Shape
Parameters:
mesh input - mesh
faceID input - faceID
elemID input - elemID
normal output - normal vector
Definition at line 750 of file shape.c.
References _fc_calcSurfaceNormal(), FC_ET_QUAD, FC_ET_TRI, fc_getElementTypeNumFace(), fc_getElementTypeText(), fc_getMeshCoordsPtr(), fc_getMeshElementFaceOrientsPtr(), fc_getMeshElementToFaceConnsPtr(), fc_getMeshFaceConnsPtr(), fc_getMeshFaceTypesPtr(), fc_getMeshInfo(), fc_getMeshNumFace(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isMeshValid(), fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by _fc_buildFaceInfoListFromShape(), _fc_buildFaceInfoListFromSubset(), fc_getPlanarSideNormal(), and fc_getSideNormalMeanSdev().
  {
  FC_ReturnCode rc;
  FC_ElementType elemType, *faceTypes;
  FC_Coords coords[4]; //restricted to tri and quad
  FC_Vector temp_normal;
  int numelem, numface, orient, numDim, numFacePerElem;
  int i,j,k;
  double* mesh_coords;
  int maxNumVertPerFace, *numVertPerFace, *faceConns, *elemToFaceConns;
  int *elemFaceOrients;
  //default
  if (normal){
    for (i = 0; i < 3; i++){
      (*normal)[i] = 0;
    }
  }
  fc_printfLogMessage("calc normal for face %d on elem %d\n", faceID, elemID);
  if (!fc_isMeshValid(mesh) || !normal){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  rc = fc_getMeshInfo(mesh, NULL, &numDim, NULL, &numelem, &elemType);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getMeshNumFace(mesh,&numface);
  if (rc != FC_SUCCESS)
    return rc;
  numFacePerElem = fc_getElementTypeNumFace(elemType);
  if (elemID < 0 || elemID > numelem || faceID < 0 || faceID > numface){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  rc = fc_getMeshFaceConnsPtr(mesh, &numVertPerFace, &maxNumVertPerFace,
                              &faceConns);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getMeshFaceTypesPtr(mesh, &faceTypes);
  if (rc != FC_SUCCESS)
    return rc;
  if (faceTypes[faceID] != FC_ET_TRI && faceTypes[faceID] != FC_ET_QUAD){
    fc_printfErrorMessage("%s, can't handle face type %s",
                          fc_getReturnCodeText(FC_INPUT_ERROR),
                          fc_getElementTypeText(faceTypes[faceID]));
   return FC_INPUT_ERROR;
  }
  rc = fc_getMeshElementToFaceConnsPtr(mesh, &elemToFaceConns);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getMeshElementFaceOrientsPtr(mesh, &elemFaceOrients);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getMeshCoordsPtr(mesh, &mesh_coords);
  if (rc != FC_SUCCESS)
    return rc;
  orient = 0;
  for (i = 0; i < numFacePerElem; i++){
    if (elemToFaceConns[elemID*numFacePerElem+i] == faceID){
      orient = elemFaceOrients[elemID*numFacePerElem+i];
      break;
    }
  }
  if (orient == 0){
    fc_printfErrorMessage("face %d not in face list for element %d",
                          faceID,elemID);
    return FC_INPUT_ERROR;
  }
  for (j = 0; j < numVertPerFace[faceID]; j++) {
    for (k = 0; k < numDim; k++)
     coords[j][k] = mesh_coords[faceConns[faceID*maxNumVertPerFace+j]*numDim+k];
    for (k = numDim; k < 3; k++)
      coords[j][k] = 0;
  }
  _fc_calcSurfaceNormal(numVertPerFace[faceID], coords, &temp_normal);
  //  printf("surface normal (%g %g %g) ",
  //     temp_normal[0],temp_normal[1], temp_normal[2]);
  //  normal = (FC_Vector*)malloc(sizeof(FC_Vector));
  for (i = 0; i < 3; i++)
    (*normal)[i] = orient*temp_normal[i];
  //  printf(" after orient (%g %g %g)\n",(*normal)[0],(*normal)[1],
  //     (*normal)[2]);
  return FC_SUCCESS;
}
FC_ReturnCode _fc_initSFI_Array (_FC_SFI_ARRAY * sfi)
inits the sfi array
Description:
inits the sfi array
Modifications:
06/07/06 ACG created
Parameters:
sfi input - sorted face info array
Definition at line 109 of file shape.c.
References FC_SUCCESS, _sfi_array::maxVals, _sfi_array::numVals, and _sfi_array::vals.
Referenced by _fc_buildFaceInfoListFromShape(), and _fc_buildFaceInfoListFromSubset().
   {
  sfi->numVals = 0;
  sfi->maxVals = 0;
  sfi->vals = NULL;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_lookupInSFI_Array (_FC_SFI_ARRAY * sfi, int i, _FC_FACEINFO ** fi)
looks for a fi index in sfi array
Description:
looks for a fi index in sfi array. returns a pointer to the item if its there, NULL if not
Modifications:
06/07/06 ACG created
Definition at line 200 of file shape.c.
References FC_SUCCESS, _sfi_array::numVals, and _sfi_array::vals.
Referenced by _fc_createShapePartsFromFaceInfoList().
 {
  int low, high, mid;
  *fi = NULL;
  if (sfi->vals == NULL){ //empty
    return FC_SUCCESS;
  }
  //binary search
  low = 0;
  high = sfi->numVals-1;
  while(low <= high){
    mid = (low+high)/2;
    //      printf("low %d high %d mid %d\n",low,high,mid);
    if ((sfi->vals[mid])->faceID == i){
      *fi = sfi->vals[mid];
      return FC_SUCCESS;
    } else if ((sfi->vals[mid])->faceID < i){
      low = mid+1;
    } else{
      high = mid -1;
    }
  }
  return FC_SUCCESS;
}
void _fc_printSFI_Array (_FC_SFI_ARRAY * sfi)
prints the sfi array
Description:
prints the sfi array
Modifications:
06/07/06 ACG created
Definition at line 320 of file shape.c.
References _sfi_array::numVals, and _sfi_array::vals.
 {
  int i;
  printf("SFI_Array has %d vals\n",sfi->numVals);
  for (i = 0; i < sfi->numVals; i++){
    printf("faceid %d elemid %d normal %10g %10g %10g\n",
        (sfi->vals[i])->faceID,
        (sfi->vals[i])->elemID,
        (sfi->vals[i])->normal[0],
        (sfi->vals[i])->normal[1],
        (sfi->vals[i])->normal[2]);
  }
}
int _fc_reallocSFI_Array (_FC_SFI_ARRAY * sfi)
reallocs the sfi array
Description:
reallocs the sfi array
Modifications:
06/07/06 ACG created
Definition at line 294 of file shape.c.
References fc_getReturnCodeText(), FC_MEMORY_ERROR, fc_printfErrorMessage, _sfi_array::maxVals, _sfi_array::numVals, and _sfi_array::vals.
  {
  _FC_FACEINFO **temp = (_FC_FACEINFO**)realloc(sfi->vals,
                               (sfi->numVals)*sizeof(_FC_FACEINFO*));
  if (temp == NULL){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  sfi->maxVals = sfi->numVals;
  sfi->vals = temp;
  return 1;
}
FC_ReturnCode _fc_removeFromSFI_Array (_FC_SFI_ARRAY * sfi, int i, _FC_FACEINFO ** fi)
removes an item from the sfi array
Description:
removes an item from the sfi array. returns a pointer to it. the user is responsible for freeing it when he is done with it
Modifications:
06/07/06 ACG created
Definition at line 246 of file shape.c.
References FC_SUCCESS, _sfi_array::numVals, and _sfi_array::vals.
Referenced by _fc_createShapePartsFromFaceInfoList().
 {
  int low, high, mid;
  *fi = NULL;
  if (sfi->vals == NULL){ //empty
    return FC_SUCCESS;
  }
  //binary search
  low = 0;
  high = sfi->numVals-1;
  while(low <= high){
    mid = (low+high)/2;
    //      printf("low %d high %d mid %d\n",low,high,mid);
    if ((sfi->vals[mid])->faceID == i){
      *fi = sfi->vals[mid];
      //shuffle everything down
      memmove((sfi->vals)+mid,(sfi->vals)+mid+1,
           (sfi->numVals-mid)*sizeof(_FC_FACEINFO*));
      sfi->numVals--;
      return FC_SUCCESS;
    } else if ((sfi->vals[mid])->faceID < i){
      low = mid+1;
    } else{
      high = mid -1;
    }
  }
  return FC_SUCCESS;
}