FCLib: (Private)
(Private)
[Simple Data Objects]
Functions
FC_ReturnCode _fc_expandIntArray (int *length, int **array)
Expand an int array.
FC_ReturnCode _fc_lookupIntInSortedIntArray (FC_SortedIntArray *sia, int i, int *foundInt, int *idx)
Lookup int in the sorted int array.
FC_ReturnCode _fc_addEntryToSortedIntArray (FC_SortedIntArray *sia, int idx, int value)
Add entry to a sorted int array at the specified location.
FC_ReturnCode _fc_deleteEntryFromSortedIntArray (FC_SortedIntArray *sia, int idx)
Remove an entry at a specified location from a sorted int array.
FC_ReturnCode _fc_expandBlobArray (int *length, void ***array)
Expand a blob array.
FC_ReturnCode _fc_lookupBlobInSortedBlobArray (FC_SortedBlobArray *sba, void *blob, int blobCmp(const void *blob1, const void *blob2), int *foundBlob, int *idx)
Lookup blob in the sorted blob array.
FC_ReturnCode _fc_addEntryToSortedBlobArray (FC_SortedBlobArray *sba, int idx, void *blob_p)
Add entry to a sorted blob array at the specified location.
FC_ReturnCode _fc_deleteEntryFromSortedBlobArray (FC_SortedBlobArray *sba, int idx)
Remove an entry at a specified location from a sorted blob array.
Function Documentation
FC_ReturnCode _fc_addEntryToSortedBlobArray (FC_SortedBlobArray * sba, int idx, void * blob_p)
Add entry to a sorted blob array at the specified location.
Description:
Use this after you know where to put the new entry (usually use _fc_lookupBlobInSortedBlobArray).
NOTE! Make sure that use of this function does not violate the sorted and uniqueness of the sorted blob array!
Modifications:
08/08/06 WSD Created.
Parameters:
sba input/output - sortedBlobArray
idx input - location to add the blob
blob_p input - the pointer to the blob
Definition at line 1847 of file storage.c.
References _fc_expandBlobArray(), FC_SortedBlobArray::blobs, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSortedBlobArrayValid(), fc_printfErrorMessage, FC_SUCCESS, FC_SortedBlobArray::maxNumBlob, and FC_SortedBlobArray::numBlob.
Referenced by _fc_buildEdgeConns(), _fc_buildFaceConns(), and fc_addBlobToSortedBlobArray().
{
  // check args
  if (!fc_isSortedBlobArrayValid(sba) || idx < 0 || idx > sba->numBlob ||
      !blob_p) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // make sure there is room
  if (sba->numBlob >= sba->maxNumBlob)
    _fc_expandBlobArray(&sba->maxNumBlob, &sba->blobs);
  // do it
  if (idx < sba->numBlob) {
    memmove((sba->blobs)+idx+1,(sba->blobs)+idx,
         (sba->numBlob-idx)*sizeof(void*));
  }
  sba->blobs[idx] = blob_p;
  sba->numBlob++;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_addEntryToSortedIntArray (FC_SortedIntArray * sia, int idx, int value)
Add entry to a sorted int array at the specified location.
Description:
Use this after you know where to put the new entry (usually use _fc_lookupIntInSortedIntArray).
NOTE! Make sure that use of this function does not violate the sorted and uniqueness of the sorted int array!
Modifications:
2006/08/04 WSD Created.
2008/05/02 CDU Updated to support getting unsorted vals back
Parameters:
sia input/output - sortedIntArray
idx input - location to add the value
value input - the value to add
Definition at line 1642 of file storage.c.
References _fc_expandIntArray(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSortedIntArrayValid(), fc_printfErrorMessage, FC_SUCCESS, FC_SortedIntArray::maxNumVal, FC_SortedIntArray::nextTicket, FC_SortedIntArray::numVal, FC_SortedIntArray::tickets, and FC_SortedIntArray::vals.
Referenced by fc_addIntToSortedIntArray().
{
  FC_ReturnCode rc;
  // check args
  if (!fc_isSortedIntArrayValid(sia) || idx < 0 || idx > sia->numVal) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // make sure there is room
  if (sia->numVal >= sia->maxNumVal){
    int tmp;
    tmp = sia->maxNumVal;
    rc = _fc_expandIntArray(&sia->maxNumVal, &sia->vals);
    if(rc!=FC_SUCCESS)
      return rc;
    rc = _fc_expandIntArray(&tmp, &sia->tickets);
    if(rc!=FC_SUCCESS)
      return rc;
  }
  // do it
  if (idx < sia->numVal) {
    memmove(&sia->vals[idx+1],    &sia->vals[idx],    (sia->numVal-idx)*sizeof(int));
    memmove(&sia->tickets[idx+1], &sia->tickets[idx], (sia->numVal-idx)*sizeof(int));
  }
  sia->vals[idx] = value;
  sia->tickets[idx] = sia->nextTicket;
  sia->numVal++;
  sia->nextTicket++;
  assert(sia->nextTicket > sia->tickets[idx]); //Look for overflow
  return FC_SUCCESS;
}
FC_ReturnCode _fc_deleteEntryFromSortedBlobArray (FC_SortedBlobArray * sba, int idx)
Remove an entry at a specified location from a sorted blob array.
Description:
Use this after you know which entry you want to delete (usually use _fc_lookupBlobInSortedBlobArray).
This routine will fail if you try to delete an entry from an empty array.
Modifications:
08/08/06 WSD Created.
Parameters:
sba input/output - sortedBlobArray
idx input - location to remove value
Definition at line 1890 of file storage.c.
References FC_SortedBlobArray::blobs, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSortedBlobArrayValid(), fc_printfErrorMessage, FC_SUCCESS, and FC_SortedBlobArray::numBlob.
Referenced by fc_deleteBlobFromSortedBlobArray().
{
  // check args
  if (!fc_isSortedBlobArrayValid(sba) || idx < 0 || idx > sba->numBlob-1) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // do it
  if (idx+1 < sba->numBlob) {
    memmove((sba->blobs)+idx,(sba->blobs)+idx+1,
         (sba->numBlob-(idx+1))*sizeof(void*));
  }
  sba->numBlob--;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_deleteEntryFromSortedIntArray (FC_SortedIntArray * sia, int idx)
Remove an entry at a specified location from a sorted int array.
Description:
Use this after you know which entry you want to delete (usually use _fc_lookupIntInSortedIntArray).
This routine will fail if you try to delete an entry from an empty array.
Modifications:
08/04/06 WSD Created.
Parameters:
sia input/output - sortedIntArray
idx input - location to remove value
Definition at line 1698 of file storage.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSortedIntArrayValid(), fc_printfErrorMessage, FC_SUCCESS, FC_SortedIntArray::numVal, FC_SortedIntArray::tickets, and FC_SortedIntArray::vals.
Referenced by fc_changeMeshEntityType(), fc_deleteIntFromSortedIntArray(), and getRemoveSIAIntersection().
{
  // check args
  if (!fc_isSortedIntArrayValid(sia) || idx < 0 || idx > sia->numVal-1) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // do it
  if (idx+1 < sia->numVal) {
    memmove(&sia->vals[idx],              &sia->vals[idx+1],              (sia->numVal-(idx+1))*sizeof(int));
    memmove(&sia->tickets[idx], &sia->tickets[idx+1], (sia->numVal-(idx+1))*sizeof(int));
  }
  sia->numVal--;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_expandBlobArray (int * length, void *** array)
Expand a blob array.
Description:
If length == 0, an array of length 1 is generated. If length > 0, then the array length is doubled. If length < 0, an error is generated.
Modifications:
08/07/06 WSD Created.
Parameters:
length input/output - length of the array
array input/output - the array
Definition at line 1732 of file storage.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, and FC_SUCCESS.
Referenced by _fc_addEntryToSortedBlobArray().
 {
  int new_length;
  void** new_array;
  // test args (note, array doesn't have to be null if length = 0)
  if (!length || *length < 0 || !array)
    return FC_INPUT_ERROR;
  // do it
  new_length = *length > 0 ? 2*(*length) : 1;
  if (*length == 0)  // malloc in case they didn't pass in NULL
    new_array = malloc(new_length*sizeof(void*));
  else
    new_array = realloc(*array, new_length*sizeof(void*));
  if (!new_array) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  // return
  *length = new_length;
  *array = new_array;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_expandIntArray (int * length, int ** array)
Expand an int array.
Description:
If length == 0, an array of length 1 is generated. If length > 0, then the array length is doubled. If length < 0, an error is generated.
Modifications:
08/07/06 WSD Created.
Parameters:
length input/output - length of the array
array input/output - the array
Definition at line 1531 of file storage.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, and FC_SUCCESS.
Referenced by _fc_addEntryToSortedIntArray(), and fc_segment().
 {
  int new_length;
  int* new_array;
  // test args (note, array doesn't have to be null if length = 0)
  if (!length || *length < 0 || !array)
    return FC_INPUT_ERROR;
  // do it
  new_length = *length > 0 ? 2*(*length) : 1;
  if (*length == 0)  // malloc in case they didn't pass in NULL
    new_array = malloc(new_length*sizeof(int));
  else
    new_array = realloc(*array, new_length*sizeof(int));
  if (!new_array) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  // return
  *length = new_length;
  *array = new_array;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_lookupBlobInSortedBlobArray (FC_SortedBlobArray * sba, void * blob, int blobCmpconst void *blob1, const void *blob2, int * foundBlob, int * idx)
Lookup blob in the sorted blob array.
Description:
Look for an blob in a sorted blob array using the provided compare function. A flag for whether a matching blob is found is returned in foundBlob (1 = found, 0 = not found). The index that the int is at (or would be at if it was in the array) is returned in idx.
This is implemented as binary search and should have average run time of O(log(sia->numVal)).
Modifications:
06/06/06 ACG Created.
07/13/06 WSD Separated binary search into it's own routine.
Parameters:
sba input - sortedIntArray
blob input - blob to lookup
blobCmp input - the compare function
foundBlob output - 1 if find blob, or 0
idx output - the index if blob is found, or the index the blob would have been at
Definition at line 1778 of file storage.c.
References FC_SortedBlobArray::blobs, FC_INPUT_ERROR, fc_isSortedBlobArrayValid(), FC_SUCCESS, and FC_SortedBlobArray::numBlob.
Referenced by _fc_buildEdgeConns(), _fc_buildFaceConns(), fc_addBlobToSortedBlobArray(), fc_deleteBlobFromSortedBlobArray(), and fc_isBlobInSortedBlobArray().
 {
  int low, high, mid, cmpVal;
  // default returns
  if (foundBlob)
    *foundBlob = -1;
  if (idx)
    *idx = -1;
  // check arguments
  //?FIX could blob be null?
  if (!fc_isSortedBlobArrayValid(sba) || !blob || !blobCmp || !foundBlob ||
      !idx) {
    return FC_INPUT_ERROR;
  }
  // early return
  if (sba->numBlob < 1) {
    *foundBlob = 0;
    *idx = 0;
    return FC_SUCCESS;
  }
  // binary search
  low = 0;
  high = sba->numBlob-1;
  while (low <= high) {
    mid = (low+high)/2;
    cmpVal = blobCmp((const void*)blob, (const void*)sba->blobs[mid]);
    if (cmpVal == 0) {
      *foundBlob = 1;
      *idx = mid;
      return FC_SUCCESS;
    } else if (cmpVal < 0) { // blob is before mid
      high = mid-1;
    } else {
      low = mid+1;
    }
  }
  // no match
  *foundBlob = 0;
  *idx = (cmpVal < 0 ? mid : mid+1);
  return FC_SUCCESS;
}
FC_ReturnCode _fc_lookupIntInSortedIntArray (FC_SortedIntArray * sia, int i, int * foundInt, int * idx)
Lookup int in the sorted int array.
Description:
Look for an int in a sorted int array. A flag for whether the int is found is returned in foundInt (1 = found, 0 = not found). The index that the int is at (or would be at if it was in the array) is returned in idx.
This is implemented as binary search and should have average run time of O(log(sia->numVal)).
Modifications:
06/06/06 ACG Created.
07/13/06 WSD Separated binary search into it's own routine.
Parameters:
sia input - sortedIntArray
i input - int to lookup
foundInt output - 1 if find int, or 0
idx output - the index if int is found, or the index the int would have been at
Definition at line 1577 of file storage.c.
References FC_INPUT_ERROR, fc_isSortedIntArrayValid(), FC_SUCCESS, FC_SortedIntArray::numVal, and FC_SortedIntArray::vals.
Referenced by fc_addIntToSortedIntArray(), fc_computeTreeDescendantsAncestors(), fc_deleteIntFromSortedIntArray(), and fc_isIntInSortedIntArray().
 {
  int low, high, mid;
  // default returns
  if (foundInt)
    *foundInt = -1;
  if (idx)
    *idx = -1;
  // check arguments
  if (!fc_isSortedIntArrayValid(sia) || !foundInt || !idx) {
    return FC_INPUT_ERROR;
  }
  // early return
  if (sia->numVal < 1) {
    *foundInt = 0;
    *idx = 0;
    return FC_SUCCESS;
  }
  // binary search
  low = 0;
  high = sia->numVal-1;
  while (low <= high) {
    mid = (low+high)/2;
    if (i == sia->vals[mid]) {
      *foundInt = 1;
      *idx = mid;
      return FC_SUCCESS;
    } else if (i < sia->vals[mid]) { // val is before mid
      high = mid-1;
    } else {
      low = mid+1;
    }
  }
  // no match
  *foundInt = 0;
  *idx = (i < sia->vals[mid] ? mid : mid+1);
  return FC_SUCCESS;
}