FCLib: Subset
Subset
[Data Interface]
Detailed Description
Operations on subsets.
Description:
Sequence subsets are stored as an array of subsets. If a function does not have a seqSubset version, in many cases you can call the subset version on the first varaible in the seqSubset array and get the results you expect, e.g., fc_getSubsetInfo(seqSubset[0],...). In some cases you would need to loop over all subsets in the seqSubset array, .e.g, fc_getSubsetMembersAsArray(seqSubset[i], ...). (For an explanation of general data manipulations, see Data Interface.)
Modules
(Private)
Create new subset from scratch.
FC_ReturnCode fc_createSubset (FC_Mesh mesh, char *subsetName, FC_AssociationType assoc, FC_Subset *subset)
Create a new subset on a specified mesh.
FC_ReturnCode fc_createSeqSubset (FC_Mesh mesh, FC_Sequence sequence, char *subsetName, FC_AssociationType assoc, int *numStep, FC_Subset **seqSubs)
Create a new sequence subset on a specified mesh.
Other ways to get new subsets.
FC_ReturnCode fc_copySubset (FC_Subset subset, FC_Mesh destMesh, char *newSubsetName, FC_Subset *newSubset)
Copy subset to a new subset.
FC_ReturnCode fc_copySeqSubset (int numStep, FC_Subset *src_seqSubset, FC_Mesh dest_mesh, FC_Sequence dest_seq, char *newName, FC_Subset **new_seqSubset)
Copy seq subset.
FC_ReturnCode fc_convertSubsetsToSeqSubset (int numStep, FC_Subset *subs, FC_Sequence sequence, char *new_name, FC_Subset **seqSubset)
Convert an array of basic subsets into a sequence subset.
FC_ReturnCode fc_convertSeqSubsetToSubsets (int numStep, FC_Subset *seqSubset, char *new_name, FC_Subset **subsets)
Convert a sequence subset into an array of normal subsets.
FC_ReturnCode fc_copySubsetWithNewAssociation (FC_Subset subset, char *newSubsetName, FC_AssociationType new_assoc, int doStrict, FC_Subset *newSubset)
Create copy subset associated with a different mesh entity type.
FC_ReturnCode fc_createSubsetComplement (FC_Subset subset, char *newSubsetName, FC_Subset *newSubset)
Create subset containing complement of the subset (NOT operator).
FC_ReturnCode fc_createSubsetIntersection (FC_Subset subset1, char *operation, FC_Subset subset2, char *newSubsetName, FC_Subset *newSubset)
Create subset based on intersection of two input subsets.
Get subset.
FC_ReturnCode fc_getSubsets (FC_Mesh mesh, int *numSubset, FC_Subset **subsets)
Get the subsets in a mesh.
FC_ReturnCode fc_getSeqSubsets (FC_Mesh mesh, int *numSeqSubs, int **numStepPerSub, FC_Subset ***seqSubs)
Get the seq subsets in a mesh.
FC_ReturnCode fc_getNumSubset (FC_Mesh mesh, int *numSubset)
Get the number of subsets in a mesh.
FC_ReturnCode fc_getNumSeqSubset (FC_Mesh mesh, int *numSeqSubset)
Get the number of seq subsets in a mesh.
FC_ReturnCode fc_getSubsetByName (FC_Mesh mesh, char *subName, int *numSubsets, FC_Subset **subsets)
Get subsets of a given name from a mesh.
FC_ReturnCode fc_getSeqSubsetByName (FC_Mesh mesh, char *subName, int *numSeqSubset, int **numStepPerSubset, FC_Subset ***seqSubsets)
Get sequence subsets of a given name from the mesh.
Subset comparisons.
FC_ReturnCode fc_doSubsetsIntersect (FC_Subset subset1, FC_Subset subset2, int *indicator)
Test if two subsets intersect.
FC_ReturnCode fc_isSubsetSuperset (FC_Subset subset_super, FC_Subset subset_sub, int *indicator)
Test if first subset is a superset of the second subset.
Change the name of a subset.
FC_ReturnCode fc_changeSubsetName (FC_Subset subset, char *newName)
Change the name of a subset.
FC_ReturnCode fc_changeSeqSubsetName (int numStep, FC_Subset *subsets, char *newName)
Change the name of a sequence subset.
Add members to subset
FC_ReturnCode fc_addMemberToSubset (FC_Subset subset, int memberID)
Add member to a subset.
FC_ReturnCode fc_addArrayMembersToSubset (FC_Subset subset, int numMember, int *array)
Add members from an array to a subset.
FC_ReturnCode fc_addMaskMembersToSubset (FC_Subset subset, int maskLength, int *mask)
Add members from a mask to a subset.
Delete members from a subset.
FC_ReturnCode fc_deleteMemberFromSubset (FC_Subset subset, int member)
Delete member from a subset.
FC_ReturnCode fc_deleteArrayMembersFromSubset (FC_Subset subset, int numElement, int *array)
Delete array members from a subset.
FC_ReturnCode fc_deleteMaskMembersFromSubset (FC_Subset subset, int maskLength, int *mask)
Delete mask members from a subset.
Release/delete subsets.
FC_ReturnCode fc_releaseSubset (FC_Subset subset)
Attempt to minimize subset's memory usage.
FC_ReturnCode fc_releaseSeqSubset (int numStep, FC_Subset *subsets)
Attempt to minimize seq subset's memory usage.
FC_ReturnCode fc_deleteSubset (FC_Subset subset)
Delete a subset.
FC_ReturnCode fc_deleteSeqSubset (int numStep, FC_Subset *subsets)
Delete a seq subset.
Get subset metadata.
int fc_isSubsetValid (FC_Subset subset)
Check that the handle refers to a valid subset.
int fc_isSeqSubsetValid (int numStep, FC_Subset *seqSub)
Check that the handle refers to a valid subset.
FC_ReturnCode fc_getSubsetName (FC_Subset subset, char **subsetName)
Get subset name.
FC_ReturnCode fc_getMeshFromSubset (FC_Subset subset, FC_Mesh *mesh)
Get the parent mesh of the subset.
FC_ReturnCode fc_getSubsetInfo (FC_Subset subset, int *numMember, int *maxNumMember, FC_AssociationType *assoc)
Get information about a subset.
FC_ReturnCode fc_getSubsetNumMember (FC_Subset subset, int *numMember)
Get number of members in a subset.
FC_ReturnCode fc_getSubsetMaxNumMember (FC_Subset subset, int *maxNumMember)
Get the maximum possible number of members a subset could have.
FC_ReturnCode fc_getSubsetAssociationType (FC_Subset subset, FC_AssociationType *assoc)
Get subset's association type.
Get/query subset big data.
int fc_isMemberInSubset (FC_Subset subset, int memberID)
Check to see if a member is in a subset.
FC_ReturnCode fc_getSubsetMembersAsArray (FC_Subset subset, int *numMember, int **array)
Get a copy of subset members as array.
FC_ReturnCode fc_getSubsetMembersAsMask (FC_Subset subset, int *maskLength, int **mask)
Get a copy of subset members as mask.
FC_ReturnCode fc_getSequenceFromSeqSubset (int numStep, FC_Subset *seqSubset, FC_Sequence *sequence)
Get the parent sequence of a seq subset.
Print subset.
FC_ReturnCode fc_printSubset (FC_Subset subset, char *label, int print_members)
Print subset meta data to stdout, and optionally the member IDs.
Print Sequence Subset Range.
FC_ReturnCode fc_printSeqSubsetRange (int numStep, FC_Subset *seqSubset, int range_start, int range_stop, char *label, int print_members)
Print sequence subset meta data to stdout, and optionally the member IDs (with start and stop index values).
Print Sequence Subset
FC_ReturnCode fc_printSeqSubset (int numStep, FC_Subset *seqSubset, char *label, int print_members)
Print sequence subset meta data to stdout, and optionally the member IDs.
FC_ReturnCode fc_printSubsetOfMesh (FC_Subset subset, FC_Mesh mesh)
Print the subset of a mesh.
FC_ReturnCode fc_printSubsetOfVariable (FC_Subset subset, FC_Variable variable)
Print the subset of a variable.
Function Documentation
FC_ReturnCode fc_addArrayMembersToSubset (FC_Subset subset, int numMember, int * array)
Add members from an array to a subset.
Description:
Add members given in an array to a subset. The operation is done on native subset representation type. FC_INPUT_ERROR is returned if any of the input members are outside the valid range.
An empty array is o.k and will not return an error.
Members cannot be added to a committed subset (i.e. written to disk).
Modifications:
04/30/04 RM, created.
05/11/05 WSK, changed to reflect changes to FC_Subset.
06/02/06 WSD, added array specific imlementation instead of calling fc_addMembersToSubset() which was not efficient enough.
Parameters:
subset input/output - subset handle
numMember input - number of members in an input array
array input - pointer to array of member IDs
Definition at line 2064 of file subset.c.
References _fc_getSubSlot(), _FC_SlotHeader::committed, fc_addIntArrayToSortedIntArray(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SubSlot::maxNumMember, _FC_SlotHeader::name, _FC_SubSlot::numMember, and _FC_SubSlot::sia.
Referenced by _fc_createShapePartsFromFaceInfoList(), _fc_recursive_IndividuallySegmentingNodes(), fc_copySeqSubset(), fc_copySubset(), fc_copySubsetWithNewAssociation(), fc_createSideAdjacencyMatrix(), fc_createSubsetIntersection(), fc_getDecayedShapeSkin(), fc_projectedSubsetElementBoundingBoxIntersection(), fc_reduceShapeNumSides(), fc_segment(), getDeathThresholdSubset(), and main().
  {
  int i;
  int ret;
  _FC_SubSlot* subSlot;
  // check input
  subSlot = _fc_getSubSlot(subset);
  if( !subSlot || numMember < 0 || ( numMember > 0 && !array)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  for (i = 0; i < numMember; i++) {
    if (array[i] < 0 || array[i] >= subSlot->maxNumMember) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
      return FC_INPUT_ERROR;
    }
  }
   // can't modify a committed subset
  if (subSlot->header.committed) {
    fc_printfErrorMessage("Can't modify committed subset '%s'",
                          subSlot->header.name);
    return FC_INPUT_ERROR;
  }
 // no logging on purpose since this may get called over and over
  // trivial case, no members in an array
  if (numMember == 0)
    return FC_SUCCESS;
  // do it
  ret = fc_addIntArrayToSortedIntArray(&subSlot->sia, numMember, array, 0);
  if (ret < 0) {
    fc_printfErrorMessage("Failed to add int array to sorted int array");
    return ret;
  }
  subSlot->numMember += ret;
  return FC_SUCCESS;
}
FC_ReturnCode fc_addMaskMembersToSubset (FC_Subset subset, int maskLength, int * mask)
Add members from a mask to a subset.
Description:
Add members given by a mask to a subset. The operation is done on native subset representation type. FC_INPUT_ERROR is returned if the given mask has different size that the mask in subset.
A mask of zero length is o.k. and will not return an error.
Members cannot be added to a committed subset (i.e. written to disk).
Modifications:
04/30/04 RM, created.
05/11/05 WSK, changed to reflect changes to FC_Subset.
Parameters:
subset input - subset handle
maskLength input - number of elements in an input mask
mask input - pointer to input mask with subset members
Definition at line 2128 of file subset.c.
References _fc_getSubSlot(), _FC_SlotHeader::committed, fc_addMemberToSubset(), FC_ERROR, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SubSlot::maxNumMember, and _FC_SlotHeader::name.
Referenced by fc_createSubsetComplement().
  {
  int i;
  FC_ReturnCode rc;
  _FC_SubSlot* subSlot;
  // check input
  subSlot = _fc_getSubSlot(subset);
  if ( !subSlot || maskLength < 0 || (maskLength > 0 && !mask) ||
       (maskLength > 0  && maskLength != subSlot->maxNumMember)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // no logging on purpose since this may get called over and over
  // can't modify a committed subset
  if (subSlot->header.committed) {
    fc_printfErrorMessage("Can't modify committed subset '%s'",
                          subSlot->header.name);
    return FC_INPUT_ERROR;
  }
  // trivial case, no elements in a mask
  if (maskLength == 0)
    return FC_SUCCESS;
  for (i = 0; i < maskLength; i++) {
    // add member where mask == 1
    if (mask[i] == 1) {
      rc = fc_addMemberToSubset(subset, i);
      if (rc != FC_SUCCESS ) {
        fc_printfErrorMessage("Failed to add member to subset '%s'",
                              subSlot->header.name);
        return FC_ERROR;
      }
    }
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_addMemberToSubset (FC_Subset subset, int memberID)
Add member to a subset.
Description:
Add member to a given subset. Returns with an error if the member is outside of the valid range.
Members cannot be added to a committed subset (i.e. exists on disk).
Modifications:
04/30/04 RM, created.
05/11/05 WSK, changed to reflect changes to FC_Subset.
Parameters:
subset input - subset to add member to
memberID input - ID of member to add
Definition at line 2008 of file subset.c.
References _fc_getSubSlot(), _FC_SlotHeader::committed, fc_addIntToSortedIntArray(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SubSlot::maxNumMember, _FC_SlotHeader::name, _FC_SubSlot::numMember, and _FC_SubSlot::sia.
Referenced by _fc_loadExodusDataset(), fc_addMaskMembersToSubset(), fc_createSubsetMesh(), fc_createThresholdSubset(), fc_getDisplacedMeshDiameter(), fc_getDisplacedMeshesDiameter(), fc_getDisplacedMeshesProximity(), fc_getMeshDiameter(), fc_getMeshesDiameter(), fc_getMeshesProximity(), fc_getMeshShapes(), fc_getMeshSkin(), fc_getSubsetSkin(), main(), printStats(), and segmentMesh().
  {
  _FC_SubSlot* subSlot;
  int ret;
  // check input, subset->storageType should never be FC_ST_UNKNOWN,
  // memberID has to be positive >= 0
  subSlot = _fc_getSubSlot(subset);
  if(!subSlot || memberID < 0 || memberID > subSlot->maxNumMember-1 ) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // can't modify a committed subset
  if (subSlot->header.committed) {
    fc_printfErrorMessage("Can't modify committed subset '%s'",
                          subSlot->header.name);
    return FC_INPUT_ERROR;
  }
  // no logging on purpose since this may get called over and over
  // add memberID to the subset
  ret = fc_addIntToSortedIntArray(&subSlot->sia, memberID);
  if (ret < 0) {
    fc_printfErrorMessage("Failed to add int to sorted int array");
    return ret; // an error occured
  }
  subSlot->numMember += ret;
  return FC_SUCCESS;
}
FC_ReturnCode fc_changeSeqSubsetName (int numStep, FC_Subset * subsets, char * newName)
Change the name of a sequence subset.
Modifications:
03/04/08 ACG created
Parameters:
numStep Input - Number of steps in the seq subset.
subsets Input - the steps of the seq subset.
newName Input - new name for the seq subset.
Definition at line 1958 of file subset.c.
References _fc_getSubSlot(), _fc_setSlotHeaderName(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSeqSubsetValid(), fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_SubSlot::header, and _FC_SlotHeader::name.
  {
  FC_ReturnCode rc, rc_keep = FC_SUCCESS;
  int i;
  _FC_SubSlot* subSlot;
  // check input
  if (!fc_isSeqSubsetValid(numStep, subsets) || newName == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  subSlot = _fc_getSubSlot(subsets[0]);
  fc_printfLogMessage("Changing name of seq subset from '%s' to '%s'",
                      subSlot->header.name, newName);
  // Do it
  for (i = 0; i < numStep; i++) {
    rc = _fc_setSlotHeaderName(&subSlot->header, newName);
    if (rc != FC_SUCCESS)
      rc_keep = rc;
  }
  return rc_keep;
}
FC_ReturnCode fc_changeSubsetName (FC_Subset subset, char * newName)
Change the name of a subset.
Modifications:
8/24/2005 WSD. Created.
Parameters:
subset Input - the subset.
newName Input - new name for the subset.
Definition at line 1930 of file subset.c.
References _fc_getSubSlot(), _fc_setSlotHeaderName(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, _FC_SubSlot::header, and _FC_SlotHeader::name.
Referenced by fc_getSubsetShapes(), fc_reduceShapeNumSides(), and main().
  {
  _FC_SubSlot* subSlot;
  // check input
  subSlot = _fc_getSubSlot(subset);
  if (subSlot == NULL || newName == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Changing name of subset from '%s' to '%s'",
                      subSlot->header.name, newName);
  // Do it
  return _fc_setSlotHeaderName(&subSlot->header, newName);
}
FC_ReturnCode fc_convertSeqSubsetToSubsets (int numStep, FC_Subset * seqSubset, char * new_name, FC_Subset ** subsets)
Convert a sequence subset into an array of normal subsets.
Description:
This routine converts a sequence subset into an array of basic subsets. It is a LOT more efficient than copy the data of a seq subset into the steps of newly created basic subsets because no creation/destruction goes on -- it just changes how the mesh views the subset handles.
The subsets will come out in the step order. Number of output subsets will be the number of steps in the original seqSubset. If a name is passed in the subsets will be named as the name postpended with "_#" where the number is the step number. Otherwise they will be named with the current name similiarly postpended. Note that if you are using this method for conversions to write to exodus, be sure that any name you use if short enough so that the name is under the exodus name character limit, or else the numbering will be lost.
Todo:
this has max length of digit postpending as 40 char - actaully calc the powers of 10 to set this correctly
Modifications:
03/13/08 ACG created
Parameters:
numStep input - the number of new steps in the seqSubset
seqSubset input - the seqSubset
new_name input - new name (optional)
subsets output - array of subsets
Definition at line 747 of file subset.c.
References _fc_getMeshSlot(), _fc_getSubSlot(), _fc_setSlotHeaderName(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSeqSubsetValid(), FC_MEMORY_ERROR, FC_NULL_SEQUENCE, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SubSlot::mesh, _FC_SlotHeader::name, _FC_MeshSlot::numSeqSub, _FC_MeshSlot::numStepPerSeqSub, _FC_MeshSlot::numSub, _FC_MeshSlot::seqSubIDs, _FC_SubSlot::sequence, _FC_SlotHeader::slotID, _FC_SubSlot::stepID, and _FC_MeshSlot::subIDs.
Referenced by _fc_writeExodusDataset().
  {
  _FC_MeshSlot* meshSlot;
  _FC_SubSlot* subSlot;
  char* newSubsetName;
  int* tempSlotIDs;
  int i, j;
  // default return
  if (subsets)
    *subsets = NULL;
  // check input
  if (!subsets || !seqSubset || !fc_isSeqSubsetValid(numStep, seqSubset) || numStep == 0) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  subSlot = _fc_getSubSlot(seqSubset[0]);
  meshSlot = _fc_getMeshSlot(subSlot->mesh);
  // log message
  fc_printfLogMessage("Copying seq subset '%s' to basic subsets",
                      subSlot->header.name);
  //remove handles from the list of sequence subs
  if (meshSlot->numSeqSub == 1){
    free(meshSlot->numStepPerSeqSub);
    meshSlot->numStepPerSeqSub = NULL;
    free(meshSlot->seqSubIDs[0]);
    free(meshSlot->seqSubIDs);
    meshSlot->seqSubIDs = NULL;
    meshSlot->numSeqSub = 0;
  } else {
    for (i = 0; i < meshSlot->numSeqSub; i++) {
      if ((meshSlot->seqSubIDs)[i][0] == subSlot->header.slotID)
     break;
    }
    free((meshSlot->seqSubIDs)[i]);
    for (j = i+1; j < meshSlot->numSeqSub; j++){
      (meshSlot->numStepPerSeqSub)[j-1] = (meshSlot->numStepPerSeqSub)[j];
      (meshSlot->seqSubIDs)[j-1] = (meshSlot->seqSubIDs)[j];
    }
    meshSlot->numSeqSub--;
  }
  tempSlotIDs = realloc(meshSlot->subIDs, sizeof(int)*(meshSlot->numSub+numStep));
  if (tempSlotIDs == NULL){
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
  }
  meshSlot->subIDs = tempSlotIDs;
  if (new_name == NULL){
    newSubsetName = (char*)malloc((strlen(subSlot->header.name)+1)*
                      sizeof(char));
    strcpy(newSubsetName, subSlot->header.name);
  } else {
    newSubsetName = (char*)malloc((strlen(new_name)+1)*
                      sizeof(char));
    strcpy(newSubsetName, new_name);
  }
  //add handles to the list of basic subs
  for (i = 0; i < numStep; i++) {
    char* temp_name;
    //change sub contents to reflect new as state non seq subset
    subSlot = _fc_getSubSlot(seqSubset[i]);
    subSlot->sequence = FC_NULL_SEQUENCE;
    subSlot->stepID = -1;
    temp_name = malloc((strlen(newSubsetName)+40)*sizeof(char));
    if (temp_name == NULL) {
      free(newSubsetName);
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    snprintf(temp_name, strlen(newSubsetName)+40,
            "%s_%d", newSubsetName, i);
    _fc_setSlotHeaderName(&subSlot->header, temp_name);
    free(temp_name);
    meshSlot->subIDs[meshSlot->numSub] = subSlot->header.slotID;
    meshSlot->numSub++;
  }
  free(newSubsetName);
  // make return values
  *subsets= (FC_Subset*)malloc(numStep*sizeof(FC_Subset));
  for (i = 0; i < numStep; i++)
    (*subsets)[i] = seqSubset[i];
  return FC_SUCCESS;
}
FC_ReturnCode fc_convertSubsetsToSeqSubset (int numStep, FC_Subset * subs, FC_Sequence sequence, char * new_name, FC_Subset ** seqSubset)
Convert an array of basic subsets into a sequence subset.
Description:
This routine converts an array of basic subsets into a sequence subset. It is a LOT more efficient than copy the data of basic subsets into the steps of a newly created seq subset because no creation/destruction goes on -- it just changes how the mesh views the subset handles.
You should put the subsets in the order they will be on the sequence. There must be the same number of subsets as there are steps on the sequence. The subsets and the sequence have to be in the same mesh. All of the subsets must be on the same mesh and have the same metadata (except the name). The subsets cannot already be part of a sequence subset.
If no name is supplied, the seqSubset will have the name of the first subset.
(The array of subsets that is the seq subset should be exactly the array passed in. A new one is made in case the original array was automatically generated--fc_deleteSeqSubset would fail on an automatically allocated array because it tries to free the array of handles.)
Todo:
Note that unlike the seqVariable version we do not check that they are on the same dataset. Is that a problem?
Modifications:
03/05/08 ACG created
Parameters:
numStep input - the number of steps
subs input - the subsets (array numStep long) (this should be freed by user if malloc'd)
sequence input - the sequence (with numStep steps)
new_name input - new name (optional)
seqSubset output - pointer to seq's subsets handles
Definition at line 568 of file subset.c.
References _fc_getMeshSlot(), _fc_getSubSlot(), _fc_setSlotHeaderName(), FC_ERROR, fc_getMeshFromSubset(), fc_getReturnCodeText(), fc_getSequenceNumStep(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, fc_isSequenceValid(), fc_isSubsetValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, FC_SUCCESS, _FC_MeshSlot::numSeqSub, _FC_MeshSlot::numStepPerSeqSub, _FC_MeshSlot::numSub, _FC_MeshSlot::seqSubIDs, _FC_SubSlot::sequence, _FC_SubSlot::stepID, and _FC_MeshSlot::subIDs.
  {
  int i, j;
  int temp_numStep;
  FC_Mesh mesh;
  _FC_MeshSlot* meshSlot;
  _FC_SubSlot *subSlots[numStep];
  int* subMask;
  int *tempNumPer, **tempSlotIDs;
  int *numBasicSub_p, **basicSubIDs_p;
  int *numSeqSub_p, **numStepPerSeqSub_p, ***seqSubIDs_p;
  // default return
  if (seqSubset)
    *seqSubset = NULL;
  // test input -- a lot of conditions!
  if (numStep < 0 || !subs || !fc_isSequenceValid(sequence) ||
      !seqSubset) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  fc_getSequenceNumStep(sequence, &temp_numStep);
  if (numStep != temp_numStep) {
    fc_printfErrorMessage("numStep (%d) does not agree with sequence's "
                          "numStep (%d)", numStep, temp_numStep);
    return FC_INPUT_ERROR;
  }
  for (i = 0; i < numStep; i++) {
    if (!fc_isSubsetValid(subs[i])) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
      return FC_INPUT_ERROR;
    }
    subSlots[i] = _fc_getSubSlot(subs[i]);
    if (subSlots[i]->stepID >= 0) {
      fc_printfErrorMessage("Subset is already part of a sequence subset");
      return FC_INPUT_ERROR;
    }
  }
  fc_getMeshFromSubset(subs[0], &mesh);
  for (i = 1; i < numStep; i++) {
    if (!FC_HANDLE_EQUIV(subSlots[i]->mesh, mesh)) {
      fc_printfErrorMessage("subsets are not on same mesh");
      return FC_INPUT_ERROR;
    }
    if (subSlots[i]->assoc        != subSlots[0]->assoc ||
     subSlots[i]->maxNumMember        != subSlots[0]->maxNumMember) {
      fc_printfErrorMessage("variables have differing metadata");
      return FC_INPUT_ERROR;
    }
  }
  // similar to fc_createSeqSubset()
  // Change names
  if (new_name) {
    for (i = 0; i < numStep; i++)
      _fc_setSlotHeaderName(&subSlots[i]->header, new_name);
  }
  else {
    for (i = 1; i < numStep; i++)
      _fc_setSlotHeaderName(&subSlots[i]->header, subSlots[0]->header.name);
  }
  // change sub contents to reflect new state as seq subs
  for (i = 0; i < numStep; i++) {
    subSlots[i]->sequence = sequence;
    subSlots[i]->stepID = i;
  }
  // get pointers to stuff on mesh depending
  meshSlot = _fc_getMeshSlot(subSlots[0]->mesh);
  numBasicSub_p = &meshSlot->numSub;
  basicSubIDs_p = &meshSlot->subIDs;
  numSeqSub_p = &meshSlot->numSeqSub;
  numStepPerSeqSub_p = &meshSlot->numStepPerSeqSub;
  seqSubIDs_p = &meshSlot->seqSubIDs;
 // Add the handles to list of sequence vars
  tempNumPer = (int*)realloc(*numStepPerSeqSub_p,
                    ((*numSeqSub_p)+1)*sizeof(int));
  tempSlotIDs = (int**)realloc(*seqSubIDs_p,
                      (*numSeqSub_p+1)*sizeof(int*));
  if (!tempNumPer || !tempSlotIDs) {
    free(tempNumPer); free(tempSlotIDs);
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  tempSlotIDs[*numSeqSub_p] = (int*)malloc(numStep*sizeof(int));
  if (!tempSlotIDs[*numSeqSub_p]) {
    free(tempNumPer); free(tempSlotIDs);
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  tempNumPer[*numSeqSub_p] = numStep;
  for (i = 0; i < numStep; i++)
    tempSlotIDs[*numSeqSub_p][i] = subs[i].slotID;
  *numStepPerSeqSub_p = tempNumPer;
  *seqSubIDs_p = tempSlotIDs;
  *numSeqSub_p = (*numSeqSub_p) + 1;
  // remove handles from list of basic subs
  subMask = calloc(*numBasicSub_p, sizeof(int));
  if (subMask == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < numStep; i++) {
    for (j = 0; j < *numBasicSub_p; j++) {
      if (subs[i].slotID == (*basicSubIDs_p)[j]) {
        subMask[j] = 1;
        break;
      }
    }
    if (j == *numBasicSub_p) {
      printf("**** developer note: something went wrong!!\n");
      fflush(NULL);
      return FC_ERROR;
    }
  }
  j = 0;
  *numBasicSub_p = *numBasicSub_p - numStep;
  if (*numBasicSub_p == 0) {
    free(*basicSubIDs_p);
    *basicSubIDs_p = NULL;
  }
  else {
    for (i = 0; i < *numBasicSub_p + numStep; i++) {
      if (subMask[i] == 0) {
        (*basicSubIDs_p)[j] = (*basicSubIDs_p)[i];
        j++;
      }
    }
  }
  free(subMask);
  // FIX realloc to make smaller
  // make return values
  *seqSubset = (FC_Subset*)malloc(numStep*sizeof(FC_Subset));
  for (i = 0; i < numStep; i++)
    (*seqSubset)[i] = subs[i];
  return FC_SUCCESS;
}
FC_ReturnCode fc_copySeqSubset (int numStep, FC_Subset * src_seqSubset, FC_Mesh dest_mesh, FC_Sequence dest_seq, char * newName, FC_Subset ** new_seqSubset)
Copy seq subset.
Description:
Create a copy of a seq subset into the specified mesh with the given name. This will return an erorr if the source and destination sequences and meshes are not similiar enough. This will copy a sequence if necessary. The destination mesh and sequence need to belong to the same dataset of an error will be returned.
Modifications:
03/05/08 ACG, created.
Parameters:
numStep input - the number of steps in the sequence variable
src_seqSubset input - the source seq subsets to be copied
dest_mesh input - the destination mesh to be copied into
dest_seq input - the destination seq to be copied into
newName input - the name of the new seqsubset, a NULL value is a flag to use the name of the source seqsubset
new_seqSubset output - array of handles to the new seq subset
Definition at line 438 of file subset.c.
References _fc_getMeshSlot(), _fc_getSeqSlot(), _fc_getSubSlot(), _FC_SeqSlot::ds, _FC_MeshSlot::ds, fc_addArrayMembersToSubset(), fc_createSeqSubset(), fc_deleteSeqSubset(), FC_ERROR, fc_getMeshNumEntity(), fc_getReturnCodeText(), fc_getSubsetInfo(), fc_getSubsetMembersAsArray(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, fc_isSeqSubsetValid(), fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SlotHeader::name, and _FC_SeqSlot::numStep.
Referenced by fc_copyMesh().
 {
  FC_ReturnCode rc;
  _FC_MeshSlot* dest_meshSlot;
  _FC_SeqSlot* dest_seqSlot;
  _FC_SubSlot* subSlot;
  FC_AssociationType assoc;
  int numEntity, maxNumMember, numMember, *memberIDs;
  int temp_numStep;
  int i;
  // default returns
  if (new_seqSubset)
    *new_seqSubset =NULL;
  // check input - NULL name is o.k.
  dest_meshSlot = _fc_getMeshSlot(dest_mesh);
  dest_seqSlot = _fc_getSeqSlot(dest_seq);
  if (!fc_isSeqSubsetValid(numStep,src_seqSubset) || dest_meshSlot == NULL ||
      dest_seqSlot == NULL || ! FC_HANDLE_EQUIV(dest_meshSlot->ds, dest_seqSlot->ds) ||
      numStep != dest_seqSlot->numStep || new_seqSubset == NULL){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // check for null name
  subSlot = _fc_getSubSlot(src_seqSubset[0]);
  if (newName == NULL)
    newName = subSlot->header.name;
  // log message
  fc_printfLogMessage("Copying seq subset '%s' to '%s'",
                      subSlot->header.name, newName);
  // get other info from source subset & dest mesh
  rc = fc_getSubsetInfo(src_seqSubset[0], NULL, &maxNumMember, &assoc);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get info from subset.");
    return FC_ERROR;
  }
  rc = fc_getMeshNumEntity(dest_mesh, assoc, &numEntity);
  if (rc != FC_SUCCESS)
    return FC_INPUT_ERROR;
  // more checking - destination mesh and subset assoc type are compatible
  if (numEntity != maxNumMember ) {
    fc_printfErrorMessage("%s: destination mesh not compatible with the subset",
                          fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // --- do it
  rc = fc_createSeqSubset(dest_mesh, dest_seq, newName, assoc, &temp_numStep,
                 new_seqSubset);
  if ( rc != FC_SUCCESS) {
    fc_printfErrorMessage("error creating new seq subset '%s'",newName);
    return rc;
  }
  //get and copy data for each step
  for (i = 0; i < numStep; i++){
    rc = fc_getSubsetMembersAsArray(src_seqSubset[i], &numMember, &memberIDs);
    if (rc != FC_SUCCESS) {
      fc_printfErrorMessage("error in getting members from subset.");
      fc_deleteSeqSubset(numStep, *new_seqSubset);
      free(new_seqSubset);
      return rc;
    }
    rc = fc_addArrayMembersToSubset((*new_seqSubset)[i], numMember, memberIDs);
    if ( rc != FC_SUCCESS) {
      fc_printfErrorMessage("error adding members to a new subset.");
      fc_deleteSeqSubset(numStep, *new_seqSubset);
      free(new_seqSubset);
      if (memberIDs) free(memberIDs);
      return rc;
    }
    // cleanup
    if (memberIDs) free(memberIDs); //could have been empty subset
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_copySubset (FC_Subset subset, FC_Mesh destMesh, char * newSubsetName, FC_Subset * newSubset)
Copy subset to a new subset.
Description:
Create new subset by copying the input subset onto a destination mesh. If destination and source mesh is not close enough the error will be returned, the new subset will not be created.
Modifications:
05/24/04 RM, created.
06/02/04 RM reworked, added checking compatibility between the destination mesh's number of association elements and the maxNumMember number of subset
Parameters:
subset input - handle to subset to be copied
destMesh input - the destination mesh to be copied to
newSubsetName input - new subset's name
newSubset output - handle to new subset
Definition at line 351 of file subset.c.
References _fc_getSubSlot(), fc_addArrayMembersToSubset(), fc_createSubset(), FC_ERROR, fc_getMeshNumEntity(), fc_getReturnCodeText(), fc_getSubsetInfo(), fc_getSubsetMembersAsArray(), FC_INPUT_ERROR, fc_isMeshValid(), fc_isSubsetValid(), FC_NULL_SUBSET, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_SubSlot::header, and _FC_SlotHeader::name.
Referenced by _fc_recursive_IndividuallySegmentingNodes(), fc_copyMesh(), fc_copyShape(), fc_copySubsetWithNewAssociation(), fc_createSubsetIntersection(), fc_reduceShapeNumSides(), fc_subsetSegmentsSubset(), and processOneVar().
 {
  FC_ReturnCode rc;
  int numEntity, maxNumMember, numMember, *memberIDs;
  FC_AssociationType assoc;
  _FC_SubSlot *subSlot;
  // default returns
  if (newSubset)
    *newSubset = FC_NULL_SUBSET;
  // check input - NULL name is o.k.
  if (!fc_isSubsetValid(subset) || !fc_isMeshValid(destMesh) || !newSubset) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // check for null name
  subSlot = _fc_getSubSlot(subset);
  if (newSubsetName == NULL)
    newSubsetName = subSlot->header.name;
  // log message
  fc_printfLogMessage("Copying subset '%s' to '%s'",
                      subSlot->header.name, newSubsetName);
  // get other info from source subset & dest mesh
  rc = fc_getSubsetInfo(subset, NULL, &maxNumMember, &assoc);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get info from subset.");
    return FC_ERROR;
  }
  rc = fc_getMeshNumEntity(destMesh, assoc, &numEntity);
  if (rc != FC_SUCCESS)
    return FC_INPUT_ERROR;
  // more checking - destination mesh and subset assoc type are compatible
  if (numEntity != maxNumMember ) {
    fc_printfErrorMessage("%s: destination mesh not compatible with the subset",
                          fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // --- do it
  rc = fc_getSubsetMembersAsArray(subset, &numMember, &memberIDs);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("error in getting members from subset.");
    return FC_ERROR;
  }
  rc = fc_createSubset(destMesh, newSubsetName, assoc, &(*newSubset));
  if ( rc != FC_SUCCESS) {
    fc_printfErrorMessage("error creating subset.");
    return FC_ERROR;
  }
  rc = fc_addArrayMembersToSubset(*newSubset, numMember, memberIDs);
  if ( rc != FC_SUCCESS) {
    fc_printfErrorMessage("error adding members to a new subset.");
    return FC_ERROR;
  }
  // cleanup
  free(memberIDs);
  return FC_SUCCESS;
}
FC_ReturnCode fc_copySubsetWithNewAssociation (FC_Subset subset, char * newSubsetName, FC_AssociationType new_assoc, int doStrict, FC_Subset * newSubset)
Create copy subset associated with a different mesh entity type.
Description:
This routine is essentially the same as fc_changeMeshEntityType() but for a subset instead of a list of entity IDs.
If the new association type is of higher dimensionality than the old (e.g. new subset will be on element and old was on vertices), the 'doStrict' flag determines whether to keep new entities if not all of their child entities are in the old subset. 1 = be strict and only have the entity in the new subset if all of it's children are present in the old subset. 0 = be lenient and add all entities that have at least one child in the old subset.
The new association type cannot be FC_AT_WHOLE_DATASET.
Modifications:
11/29/04 WSK, created.
Parameters:
subset input - handle to subset to be copied
newSubsetName input - new subset's name
new_assoc input - the output association type
doStrict input - flag for dropping incomplete entities
newSubset output - handle to new subset
Definition at line 869 of file subset.c.
References _fc_getSubSlot(), fc_addArrayMembersToSubset(), FC_AT_UNKNOWN, FC_AT_WHOLE_DATASET, fc_changeMeshEntityType(), fc_copySubset(), fc_createSubset(), FC_ERROR, fc_getMeshFromSubset(), fc_getReturnCodeText(), fc_getSubsetAssociationType(), fc_getSubsetMembersAsArray(), FC_INPUT_ERROR, fc_isAssociationTypeValid(), fc_isSubsetValid(), FC_NULL_SUBSET, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_SubSlot::header, and _FC_SlotHeader::name.
Referenced by fc_getDisplacedSubsetVolume(), fc_getSubsetVolume(), and main().
 {
  FC_ReturnCode rc;
  int numMember, *memberIDs, newNumMember, *newMemberIDs;
  FC_Mesh mesh;
  FC_AssociationType assoc;
  _FC_SubSlot *subSlot;
  // default returns
  if (newSubset)
    *newSubset = FC_NULL_SUBSET;
  // check input - NULL name is o.k.
  if (!fc_isSubsetValid(subset) || !fc_isAssociationTypeValid(new_assoc) ||
      new_assoc == FC_AT_UNKNOWN || new_assoc == FC_AT_WHOLE_DATASET ||
      (doStrict != 0 && doStrict != 1) || !newSubset) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // check for null name
  subSlot = _fc_getSubSlot(subset);
  if (newSubsetName == NULL)
    newSubsetName = subSlot->header.name;
  // log message
  fc_printfLogMessage("Copying subset '%s' while changing association type",
                      subSlot->header.name);
  // get other info from source subset & dest mesh
  rc = fc_getSubsetAssociationType(subset, &assoc);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get info from subset.");
    return FC_ERROR;
  }
  rc = fc_getMeshFromSubset(subset, &mesh);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get mesh from subset.");
    return FC_ERROR;
  }
  // special case -- if assoc is the same, just call fc_copySubset()
  if (new_assoc == assoc)
    return fc_copySubset(subset, mesh, newSubsetName, newSubset);
  // --- do it
  rc = fc_createSubset(mesh, newSubsetName, new_assoc, newSubset);
  if ( rc != FC_SUCCESS) {
    fc_printfErrorMessage("error creating subset.");
    return FC_ERROR;
  }
  rc = fc_getSubsetMembersAsArray(subset, &numMember, &memberIDs);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("error in getting members from subset.");
    return FC_ERROR;
  }
  if (numMember > 0) {
    rc = fc_changeMeshEntityType(mesh, assoc, numMember, memberIDs, new_assoc,
                                 doStrict, &newNumMember, &newMemberIDs);
    free(memberIDs);
    if (rc != FC_SUCCESS) {
      fc_printfErrorMessage("error changing member association");
      return FC_ERROR;
    }
    if (newNumMember > 0) {
      rc = fc_addArrayMembersToSubset(*newSubset, newNumMember, newMemberIDs);
      if (rc != FC_SUCCESS) {
        fc_printfErrorMessage("error adding members to a new subset.");
        return FC_ERROR;
      }
      free(newMemberIDs);
    }
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_createSeqSubset (FC_Mesh mesh, FC_Sequence sequence, char * subsetName, FC_AssociationType assoc, int * numStep, FC_Subset ** seqSubs)
Create a new sequence subset on a specified mesh.
Description:
Create a new (empty) sequence subset as an array of subsets. A sequence must be provided in addition to the mesh that will be the owner of the subset. The sequence and mesh must be in the same dataset.
Modifications:
03-03-08 ACG, created
Parameters:
mesh input - mesh handle
sequence input - sequence handle
subsetName input - sequence subset name
assoc input - association of subset entities
numStep output - the number of steps
seqSubs output - seq subset handles
Definition at line 219 of file subset.c.
References _FC_GET_HANDLE, _fc_getMeshSlot(), _fc_getNewSubSlot(), _fc_getSeqSlot(), _fc_setSlotHeaderName(), _FC_SubSlot::assoc, _FC_SeqSlot::ds, _FC_MeshSlot::ds, FC_AT_UNKNOWN, FC_AT_WHOLE_DATASET, fc_getAssociationTypeText(), fc_getMeshNumEntity(), fc_getReturnCodeText(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, fc_isAssociationTypeValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_MeshSlot::header, _FC_SubSlot::maxNumMember, _FC_SubSlot::mesh, _FC_SlotHeader::name, _FC_MeshSlot::numSeqSub, _FC_SeqSlot::numStep, _FC_MeshSlot::numStepPerSeqSub, _FC_MeshSlot::seqSubIDs, _FC_SubSlot::sequence, and _FC_SubSlot::stepID.
Referenced by fc_copySeqSubset(), and fc_createSubsetMesh().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  _FC_SeqSlot* seqSlot;
  _FC_SubSlot* subSlot;
  int *tempNumPer, **tempSlotIDs;
  int num;
  int i;
  // default return
  if (numStep)
    *numStep = -1;
  if (seqSubs)
    *seqSubs = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  seqSlot = _fc_getSeqSlot(sequence);
  if (meshSlot == NULL || seqSlot == NULL || subsetName == NULL ||
      !assoc ||  !fc_isAssociationTypeValid(assoc) || assoc == FC_AT_UNKNOWN ||
      assoc == FC_AT_WHOLE_DATASET || numStep == NULL || seqSubs == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  if (!FC_HANDLE_EQUIV(meshSlot->ds, seqSlot->ds)) {
    fc_printfErrorMessage("%s",fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Creating new seq subset '%s'", subsetName);
  // do as much checking as possible before creating new slot
  // ----- get number of mask elements depending on association
  rc = fc_getMeshNumEntity(mesh,assoc,&num);
  if (rc != FC_SUCCESS)
    return FC_INPUT_ERROR;
  if (num < 1) {
    fc_printfErrorMessage("Entity type %s does not exists on mesh '%s'",
                          fc_getAssociationTypeText(assoc),
                          meshSlot->header.name);
    return FC_INPUT_ERROR;
  }
  //make room for array & setup return values;
  *numStep = seqSlot->numStep;
  *seqSubs = malloc(sizeof(FC_Subset)*seqSlot->numStep);
  if (*seqSubs == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < seqSlot->numStep; i++){
    // get an open slot
    subSlot = _fc_getNewSubSlot();
    if (!subSlot) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    // table header information
    _FC_GET_HANDLE((*seqSubs)[i], subSlot);
    _fc_setSlotHeaderName(&subSlot->header, subsetName);
    // Setup subset metadata
    subSlot->assoc = assoc;
    subSlot->maxNumMember = num;
    // set back and forth references
    subSlot->mesh = mesh;
    subSlot->sequence = sequence;
    subSlot->stepID = i;
  }
  //set more back and forth references
  tempNumPer = (int*)realloc(meshSlot->numStepPerSeqSub,
                    (meshSlot->numSeqSub+1)*sizeof(int));
  tempSlotIDs = (int**)realloc(meshSlot->seqSubIDs,
                      (meshSlot->numSeqSub+1)*sizeof(int*));
  if (!tempNumPer || ! tempSlotIDs) {
    free(tempNumPer);
    free(tempSlotIDs);
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  tempSlotIDs[meshSlot->numSeqSub] = (int*)malloc(seqSlot->numStep*sizeof(int));
  if (!tempSlotIDs[meshSlot->numSeqSub]) {
    free(tempNumPer);
    free(tempSlotIDs);
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  meshSlot->numStepPerSeqSub = tempNumPer;
  meshSlot->numStepPerSeqSub[meshSlot->numSeqSub] = seqSlot->numStep;
  meshSlot->seqSubIDs = tempSlotIDs;
  for (i = 0; i < seqSlot->numStep; i++) {
    meshSlot->seqSubIDs[meshSlot->numSeqSub][i] = (*seqSubs)[i].slotID;
  }
  meshSlot->numSeqSub++;
  return FC_SUCCESS;
}
FC_ReturnCode fc_createSubset (FC_Mesh mesh, char * subsetName, FC_AssociationType assoc, FC_Subset * subset)
Create a new subset on a specified mesh.
Description:
Create a new (empty) subset to hold entities of the specified type on a specified mesh. Sets up subset data structure and initializes it to default values. Mesh, subsetName and assoc must be given and valid. It is an error to try to create a subset on an entity type that does not exists (e.g. faces on a line mesh).
It is not possible to create subsets with association FC_AT_WHOLE_DATASET.
Modifications:
03/31/04 RM, Created.
05/11/05 WSK, changed to reflect changes to FC_Subset.
07/23/05 WSK, removed storage type from argument list.
Parameters:
mesh input - mesh handle
subsetName input - name of a subset to be created
assoc input - association of subset entities
subset output - subset handle
Definition at line 135 of file subset.c.
References _FC_GET_HANDLE, _fc_getMeshSlot(), _fc_getNewSubSlot(), _fc_setSlotHeaderName(), _FC_SubSlot::assoc, FC_AT_UNKNOWN, FC_AT_WHOLE_DATASET, fc_getAssociationTypeText(), fc_getMeshNumEntity(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isAssociationTypeValid(), FC_MEMORY_ERROR, FC_NULL_SUBSET, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_MeshSlot::header, _FC_SubSlot::maxNumMember, _FC_SubSlot::mesh, _FC_SlotHeader::name, _FC_MeshSlot::numSub, _FC_SlotHeader::slotID, and _FC_MeshSlot::subIDs.
Referenced by _fc_createShapePartsFromFaceInfoList(), _fc_loadExodusDataset(), fc_copySubset(), fc_copySubsetWithNewAssociation(), fc_createSideAdjacencyMatrix(), fc_createSubsetComplement(), fc_createSubsetIntersection(), fc_createSubsetMesh(), fc_createThresholdSubset(), fc_getDisplacedMeshDiameter(), fc_getDisplacedMeshesDiameter(), fc_getDisplacedMeshesProximity(), fc_getMeshDiameter(), fc_getMeshesDiameter(), fc_getMeshesProximity(), fc_getMeshShapes(), fc_getMeshSkin(), fc_getSubsetSkin(), fc_projectedSubsetElementBoundingBoxIntersection(), fc_segment(), getDeathThresholdSubset(), main(), printStats(), and segmentMesh().
  {
  FC_ReturnCode rc;
  int num;
  int *tempSlotIDs;
  _FC_MeshSlot* meshSlot;
  _FC_SubSlot* subSlot;
  // default return
  if (subset)
    *subset = FC_NULL_SUBSET;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || !subsetName  || !assoc ||
      !fc_isAssociationTypeValid(assoc) || assoc == FC_AT_UNKNOWN ||
      assoc == FC_AT_WHOLE_DATASET || !subset) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Creating new subset '%s'", subsetName);
  // do as much checking as possible before creating new slot
  // ----- get number of mask elements depending on association
  rc = fc_getMeshNumEntity(mesh,assoc,&num);
  if (rc != FC_SUCCESS)
    return FC_INPUT_ERROR;
  if (num < 1) {
    fc_printfErrorMessage("Entity type %s does not exists on mesh '%s'",
                          fc_getAssociationTypeText(assoc),
                          meshSlot->header.name);
    return FC_INPUT_ERROR;
  }
  // get an open slot
  subSlot = _fc_getNewSubSlot();
  if (!subSlot) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  // table header information
  _FC_GET_HANDLE(*subset, subSlot);
  _fc_setSlotHeaderName(&subSlot->header, subsetName);
  // set back and forth references to mesh
  subSlot->mesh = mesh;
  tempSlotIDs = realloc(meshSlot->subIDs, sizeof(int)*(meshSlot->numSub+1));
  if (tempSlotIDs == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  meshSlot->subIDs = tempSlotIDs;
  meshSlot->subIDs[meshSlot->numSub] = subSlot->header.slotID;
  meshSlot->numSub++;
  // Setup subset metadata
  subSlot->assoc = assoc;
  subSlot->maxNumMember = num;
  return FC_SUCCESS;
}
FC_ReturnCode fc_createSubsetComplement (FC_Subset subset, char * newSubsetName, FC_Subset * newSubset)
Create subset containing complement of the subset (NOT operator).
Description:
Create new complement subset by performing logical NOT operation on a subset. New subset will be on the same mesh as original subset.
Modifications:
05/21/04 RM, created.
Parameters:
subset input - handle to original subset
newSubsetName input - new subset's name
newSubset output - handle to new subset
Definition at line 963 of file subset.c.
References _fc_getSubSlot(), fc_addMaskMembersToSubset(), fc_createSubset(), FC_ERROR, fc_getMeshFromSubset(), fc_getReturnCodeText(), fc_getSubsetInfo(), fc_getSubsetMembersAsMask(), FC_INPUT_ERROR, fc_isSubsetValid(), FC_NULL_SUBSET, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_SubSlot::header, and _FC_SlotHeader::name.
Referenced by fc_subsetSegmentsMesh().
 {
  FC_ReturnCode rc, rc1, rc2;
  int i;
  int maskLength, *mask;
  _FC_SubSlot *subSlot;
  FC_Mesh mesh;
  FC_AssociationType assoc;
  // default returns
  if (newSubset)
    *newSubset = FC_NULL_SUBSET;
  // check input
  if (!fc_isSubsetValid(subset) || !newSubsetName || !newSubset) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  subSlot = _fc_getSubSlot(subset);
  fc_printfLogMessage("Creating complement to subset '%s' with name '%s'",
                      subSlot->header.name, newSubsetName);
  // get subset members
  rc = fc_getMeshFromSubset(subset, &mesh);
  rc1 = fc_getSubsetInfo(subset, NULL, NULL, &assoc);
  rc2 = fc_getSubsetMembersAsMask(subset, &maskLength, &mask);
  if (rc != FC_SUCCESS || rc1 != FC_SUCCESS || rc2 != FC_SUCCESS) {
    fc_printfErrorMessage("error in accessing subset's fields");
    return FC_ERROR;
  }
  // revert mask in place
  for (i = 0; i < maskLength; i++)
    mask[i] = ( mask[i] == 0 ) ? 1 : 0;
  // create the new subset
  rc = fc_createSubset(mesh, newSubsetName, assoc, &(*newSubset));
  if (rc1 != FC_SUCCESS) {
    free(mask);
    fc_printfErrorMessage("error creating subset");
    return FC_ERROR;
  }
  rc = fc_addMaskMembersToSubset(*newSubset, maskLength, mask);
  free(mask);
  return rc;
}
FC_ReturnCode fc_createSubsetIntersection (FC_Subset subset1, char * operation, FC_Subset subset2, char * newSubsetName, FC_Subset * newSubset)
Create subset based on intersection of two input subsets.
Description:
Create new subset by performing logical operation (intersection) on two input subsets. The operation is given by a string and can have the following values:
"AND", "and", "&&" or "&" --- the logical AND operation
"OR", "or", "||" or "|" --- the logical OR op.
"XOR" "xor", or "^" --- the logical XOR (OR-AND) op.
Subset's need to have the same association type.
FC_NULL_SUBSET is allowed for one of the subsets and behaves the same as if you had provided an empty subset.
Todo:
?Right now can only intersect sets on same mesh.
Modifications:
05/18/04 RM, created.
09/21/04 WSK, changed input checking & cleanup.
Parameters:
subset1 input - first subset's handle
operation input - string describing logical operation
subset2 input - second subset's handle
newSubsetName output - new subset's name
newSubset output - new subset handle
Definition at line 1040 of file subset.c.
References fc_addArrayMembersToSubset(), fc_copySubset(), fc_createSubset(), FC_ERROR, fc_getMeshFromSubset(), fc_getReturnCodeText(), fc_getSubsetInfo(), fc_getSubsetMaxNumMember(), fc_getSubsetMembersAsArray(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, fc_isSubsetValid(), FC_MEMORY_ERROR, FC_NULL_SUBSET, fc_printfErrorMessage, and FC_SUCCESS.
Referenced by fc_createThresholdRangeSubset(), fc_getDecayedSkin(), fc_getExposedSkin(), main(), and printStats().
  {
  int ioper, i, j, k;
  FC_ReturnCode rc,rc1,rc2;
  FC_Subset tempSubset;
  FC_Mesh mesh1, mesh2;
  FC_AssociationType assoc1, assoc2;
  int numMember1, *members1, numMember2, *members2;
  int maxNumMember, *newMembers, newNumMember;
  // default returns
  if (newSubset)
    *newSubset = FC_NULL_SUBSET;
  // check input (1 NULL subset is o.k., but not both)
  if (!newSubset || !operation || !newSubsetName || !newSubset ||
      (!fc_isSubsetValid(subset1) && !FC_HANDLE_EQUIV(subset1,FC_NULL_SUBSET)) ||
      (!fc_isSubsetValid(subset2) && !FC_HANDLE_EQUIV(subset2,FC_NULL_SUBSET)) ||
      (!fc_isSubsetValid(subset1) && !fc_isSubsetValid(subset2))   ) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // check the ops
  if (!strcmp(operation,"AND") ||
      !strcmp(operation,"and") ||
      !strcmp(operation,"&&")  ||
      !strcmp(operation,"&")      )
    ioper = 0;
  else if (!strcmp(operation,"OR") ||
           !strcmp(operation,"or") ||
           !strcmp(operation,"||") ||
           !strcmp(operation,"|")      )
    ioper = 1;
  else if (!strcmp(operation,"XOR") ||
           !strcmp(operation,"xor") ||
           !strcmp(operation,"^")      )
    ioper = 2;
  else {
        fc_printfErrorMessage("unrecognized operation '%s'",operation);
    return FC_INPUT_ERROR;
  }
  // ----- special case: one subset is FC_NULL_SUBSET
  if (FC_HANDLE_EQUIV(subset1, FC_NULL_SUBSET) ||
      FC_HANDLE_EQUIV(subset2, FC_NULL_SUBSET)    ) {
    // identify non-null subset & it's parent mesh
    if (!FC_HANDLE_EQUIV(subset1, FC_NULL_SUBSET))
      tempSubset = subset1;
    else
      tempSubset = subset2;
    rc = fc_getMeshFromSubset(tempSubset, &mesh1);
    if (rc != FC_SUCCESS) {
      fc_printfErrorMessage("Can't get mesh from subset.");
      return  FC_ERROR;
    }
    // if operation is "AND" return an empty subset of appropriate assoc
    if (ioper == 0 ) {
      rc = fc_getSubsetInfo(tempSubset, NULL, NULL, &assoc1);
      if (rc != FC_SUCCESS)
        return FC_ERROR;
      rc = fc_createSubset(mesh1, newSubsetName, assoc1, newSubset);
      if (rc != FC_SUCCESS)
        return FC_ERROR;
    }
    // otherwise return a copy of the other subset
    else {
      rc = fc_copySubset(tempSubset, mesh1, newSubsetName, &(*newSubset));
      if (rc != FC_SUCCESS)
        return  FC_ERROR;
    }
    return FC_SUCCESS;  // return after special cases
  }
  // check if subsets are defined on the same mesh, if not return input error
  rc1 = fc_getMeshFromSubset(subset1, &mesh1);
  rc2 = fc_getMeshFromSubset(subset2, &mesh2);
  if (rc1 != FC_SUCCESS || rc2 != FC_SUCCESS || !FC_HANDLE_EQUIV(mesh1,mesh2)) {
    fc_printfErrorMessage("FC_INPUT_ERROR: Can't get mesh from subset, or "
                          "subsets defined on different meshes");
    return  FC_INPUT_ERROR;
  }
  // get info about the subsets
  rc1 = fc_getSubsetInfo(subset1, NULL, NULL, &assoc1);
  rc2 = fc_getSubsetInfo(subset2, NULL, NULL, &assoc2);
  // check if both subsets have the same association
  if (rc1 != FC_SUCCESS || rc2 != FC_SUCCESS || assoc1 != assoc2 ) {
    fc_printfErrorMessage("FC_INPUT_ERROR: Can't get info from subset, or "
                          "subsets defined with different association type");
    return  FC_INPUT_ERROR;
  }
  // --- get new members
  // setup
  rc = fc_getSubsetMaxNumMember(subset1, &maxNumMember);
  rc1 = fc_getSubsetMembersAsArray(subset1, &numMember1, &members1);
  rc2 = fc_getSubsetMembersAsArray(subset2, &numMember2, &members2);
  if (rc != FC_SUCCESS || rc1 != FC_SUCCESS || rc2 != FC_SUCCESS) {
    free(members1);
    free(members2);
    return FC_ERROR;
  }
  newMembers = (int*)malloc(sizeof(int)*maxNumMember);
  if (!newMembers) {
    free(members1);
    free(members2);
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  // Walk both arrays at same time, adding to newMembers when appropriate
  newNumMember = 0;
  i = 0;
  j = 0;
  while (i < numMember1 && j < numMember2) {
    if (members1[i] < members2[j]) { // not the same
      if (ioper == 1) { // "OR"
        newMembers[newNumMember] = members1[i];
        newNumMember++;
      }
      else if (ioper == 2) { // "XOR"
        newMembers[newNumMember] = members1[i];
        newNumMember++;
      }
      i++;
    }
    else if (members1[i] > members2[j]) { // not the same
      if (ioper == 1) { // "OR"
        newMembers[newNumMember] = members2[j];
        newNumMember++;
      }
      else if (ioper == 2) { // "XOR"
        newMembers[newNumMember] = members2[j];
        newNumMember++;
      }
      j++;
    }
    else { // the same
      if (ioper == 0) { // "AND"
        newMembers[newNumMember] = members1[i];
        newNumMember++;
      }
      else if (ioper == 1) { // "OR"
        newMembers[newNumMember] = members1[i];
        newNumMember++;
      }
      i++;
      j++;
    }
  }
  for (k = i; k < numMember1; k++) {
    if (ioper > 0) {
      newMembers[newNumMember] = members1[k];
      newNumMember++;
    }
  }
  for (k = j; k < numMember2; k++) {
    if (ioper > 0) {
      newMembers[newNumMember] = members2[k];
      newNumMember++;
    }
  }
  free(members1);
  free(members2);
  // --- make the new subset
  rc = fc_createSubset(mesh1, newSubsetName, assoc1, newSubset);
  if (rc != FC_SUCCESS) {
    free(newMembers);
    return FC_ERROR;
  }
  // --- done if there are no members
  if (newNumMember == 0) {
    free(newMembers);
    return FC_SUCCESS;
  }
  rc = fc_addArrayMembersToSubset(*newSubset, newNumMember, newMembers);
  free(newMembers);
  return rc;
}
FC_ReturnCode fc_deleteArrayMembersFromSubset (FC_Subset subset, int numElement, int * array)
Delete array members from a subset.
Description:
Delete members given in an array from a subset. The operation is done on native subset representation type. FC_INPUT_ERROR will be returned if any of the array members are outside the valid range.
An empty array is o.k. and will not return an error.
Members cannot be deleted from a committed subset (i.e. written to disk).
Modifications:
05/03/04 RM, created.
05/11/05 WSK, changed to reflect changes to FC_Subset.
Parameters:
subset input - subset handle
numElement input - number of elements in an input array
array input - pointer to input array with subset members
Definition at line 2249 of file subset.c.
References _fc_getSubSlot(), _FC_SlotHeader::committed, fc_deleteMemberFromSubset(), FC_ERROR, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SubSlot::maxNumMember, and _FC_SlotHeader::name.
Referenced by fc_subsetSegmentsSubset().
  {
  int i;
  FC_ReturnCode rc;
  _FC_SubSlot* subSlot;
  // check input
  subSlot = _fc_getSubSlot(subset);
  if ( !subSlot || numElement < 0 || (numElement > 0 && !array) ) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  for (i = 0; i < numElement; i++) {
    if (array[i] < 0 || array[i] >= subSlot->maxNumMember) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
      return FC_INPUT_ERROR;
    }
  }
  // can't modify a committed subset
  if (subSlot->header.committed) {
    fc_printfErrorMessage("Can't modify committed subset '%s'",
                          subSlot->header.name);
    return FC_INPUT_ERROR;
  }
  // trivial case, no members in an array
  if (numElement == 0)
    return FC_SUCCESS;
  // do it
  for (i = 0; i < numElement; i++) {
    rc = fc_deleteMemberFromSubset(subset, array[i]);
    if(rc != FC_SUCCESS ) {
      fc_printfErrorMessage("Failed to delete member from subset '%s'",
                            subSlot->header.name);
      return FC_ERROR;
    }
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_deleteMaskMembersFromSubset (FC_Subset subset, int maskLength, int * mask)
Delete mask members from a subset.
Description:
Delete members given by a mask from a subset. The operation is done on native subset representation type. FC_INPUT_ERROR is returned if the given mask has different size that the mask in subset.
Members cannot be deleted from a committed subset (i.e. written to disk).
Modifications:
05/03/04 RM, created.
05/11/05 WSK, changed to reflect changes to FC_Subset.
Parameters:
subset input - subset handle
maskLength input - number of elements in an input mask
mask input - pointer to input mask with subset members
Definition at line 2312 of file subset.c.
References _fc_getSubSlot(), _FC_SlotHeader::committed, fc_deleteMemberFromSubset(), FC_ERROR, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SubSlot::maxNumMember, and _FC_SlotHeader::name.
  {
  int i;
  FC_ReturnCode rc;
  _FC_SubSlot* subSlot;
  // check input
  subSlot = _fc_getSubSlot(subset);
  if ( !subSlot || maskLength < 0 || (maskLength > 0 && !mask) ||
       (maskLength > 0 && maskLength != subSlot->maxNumMember) ) {
   fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // can't modify a committed subset
  if (subSlot->header.committed) {
    fc_printfErrorMessage("Can't modify committed subset '%s'",
                          subSlot->header.name);
    return FC_INPUT_ERROR;
  }
  // no logging on purpose since this may get called over and over
  // trivial case, no elements in a mask
  if (maskLength == 0)
    return FC_SUCCESS;
  for (i = 0; i < maskLength; i++)
    // delete member where mask == 1
    if (mask[i] == 1) {
      rc = fc_deleteMemberFromSubset(subset, i);
      if (rc != FC_SUCCESS ) {
        fc_printfErrorMessage("Failed to delete member to subset '%s'",
                              subSlot->header.name);
        return FC_ERROR;
      }
    }
  return FC_SUCCESS;
}
FC_ReturnCode fc_deleteMemberFromSubset (FC_Subset subset, int member)
Delete member from a subset.
Description:
Delete member from a given subset, does not change subset type--operation is done on the native subset type. FC_INPUT_ERROR is returned if the member is outside of the valid range.
Members cannot be deleted from a committed subset (i.e. written to disk).
Modifications:
05/03/04 RM, created.
05/11/04 WSK, changed to reflect changes to FC_Subset.
Parameters:
subset input/output - subset handle
member input - member to delete
Definition at line 2195 of file subset.c.
References _fc_getSubSlot(), _FC_SlotHeader::committed, fc_deleteIntFromSortedIntArray(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SubSlot::maxNumMember, _FC_SlotHeader::name, _FC_SubSlot::numMember, and _FC_SubSlot::sia.
Referenced by fc_deleteArrayMembersFromSubset(), and fc_deleteMaskMembersFromSubset().
  {
  _FC_SubSlot* subSlot;
  int ret;
  // check input, subset->storageType should never be FC_ST_UNKNOWN,
  // member has to be positive >= 0
  subSlot = _fc_getSubSlot(subset);
  if (!subSlot || member < 0 || member > subSlot->maxNumMember-1 ) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // can't modify a committed subset
  if (subSlot->header.committed) {
    fc_printfErrorMessage("Can't modify committed subset '%s'",
                          subSlot->header.name);
    return FC_INPUT_ERROR;
  }
  // no logging on purpose since this may get called over and over
  // delete member from the subset
  ret = fc_deleteIntFromSortedIntArray(&subSlot->sia, member);
  if (ret < 0) {
    fc_printfErrorMessage("Failed to delete in from sorted int array");
    return ret;
  }
  subSlot->numMember -= ret;
  return FC_SUCCESS;
}
FC_ReturnCode fc_deleteSeqSubset (int numStep, FC_Subset * subsets)
Delete a seq subset.
Description:
Call when this seq subset is no longer needed.
NOTE: this does not delete the array of subset handles that makes up the seq subset, the user is still responsible for this.
Modifications:
03/03/08 ACG created
Parameters:
numStep input - the number of subset handles
subsets input - subset handles
Definition at line 2543 of file subset.c.
References _fc_deleteSubSlot(), _fc_getMeshSlot(), _fc_getSubSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSeqSubsetValid(), fc_printfErrorMessage, fc_printfLogMessage, fc_printfWarningMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SubSlot::mesh, _FC_SlotHeader::name, _FC_MeshSlot::numSeqSub, _FC_MeshSlot::numStepPerSeqSub, _FC_MeshSlot::seqSubIDs, and _FC_SlotHeader::slotID.
Referenced by fc_copySeqSubset(), and fc_deleteMesh().
  {
  FC_ReturnCode rc, rc_keep;
  _FC_SubSlot* first_subSlot;
  _FC_MeshSlot* meshSlot;
  int i, j;
  // special case: deleting a null list is not an error
  if (numStep <= 0 && subsets == NULL) {
    fc_printfWarningMessage("Deleting NULL seq subset");
    return FC_SUCCESS;
  }
  // check input
  if (!fc_isSeqSubsetValid(numStep, subsets)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  first_subSlot = _fc_getSubSlot(subsets[0]);
  if (first_subSlot == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Deleting subset '%s'", first_subSlot->header.name);
  //remove references from mesh
  meshSlot = _fc_getMeshSlot(first_subSlot->mesh);
  if (meshSlot->numSeqSub == 1 ) {
    free(meshSlot->numStepPerSeqSub);
    meshSlot->numStepPerSeqSub = NULL;
    free(meshSlot->seqSubIDs[0]);
    free(meshSlot->seqSubIDs);
    meshSlot->seqSubIDs = NULL;
    meshSlot->numSeqSub = 0;
  } else {
    for (i = 0; i < meshSlot->numSeqSub; i++){
      if ((meshSlot->seqSubIDs)[i][0] == first_subSlot->header.slotID)
        break;
    }
    free((meshSlot->seqSubIDs)[i]);
    for (j = i+1; j < meshSlot->numSeqSub; j++) {
      (meshSlot->numStepPerSeqSub)[j-1] = (meshSlot->numStepPerSeqSub)[j];
      (meshSlot->seqSubIDs)[j-1] = (meshSlot->seqSubIDs)[j];
    }
    meshSlot->numSeqSub--;
  }
  // clear & delete slots
  rc_keep = FC_SUCCESS;
  for (i = 0; i < numStep; i++){
    rc = _fc_deleteSubSlot(subsets[i]);
    if (rc != FC_SUCCESS)
      rc_keep = rc;
  }
  return rc_keep;
}
FC_ReturnCode fc_deleteSubset (FC_Subset subset)
Delete a subset.
Description:
Call when this subset is no longer needed.
Modifications:
04/20/04 RM, created.
05/11/05 WSK, changed to reflect changes to FC_Subset.
9/9/04 WSK changed name to delete. Changed behavior so that delete always deletes no matter whether on disk or not.
Parameters:
subset input - subset handle
Definition at line 2482 of file subset.c.
References _fc_deleteSubSlot(), _fc_getMeshSlot(), _fc_getSubSlot(), fc_getReturnCodeText(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, FC_NULL_SUBSET, fc_printfErrorMessage, fc_printfLogMessage, fc_printfWarningMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SubSlot::mesh, _FC_SlotHeader::name, _FC_MeshSlot::numSub, _FC_SlotHeader::slotID, and _FC_MeshSlot::subIDs.
Referenced by _fc_recursive_IndividuallySegmentingNodes(), broken(), calcSegmentsVolumes(), calcShapeIntersection(), fc_calcTearLength(), fc_createSideAdjacencyMatrix(), fc_createThresholdRangeSubset(), fc_deleteMesh(), fc_freeShape(), fc_getDecayedShapeSides(), fc_getDecayedShapeSkin(), fc_getDecayedSkin(), fc_getDisplacedMeshDiameter(), fc_getDisplacedMeshesDiameter(), fc_getDisplacedMeshesProximity(), fc_getDisplacedSubsetVolume(), fc_getExposedSkin(), fc_getMeshDiameter(), fc_getMeshesDiameter(), fc_getMeshesProximity(), fc_getMeshShapes(), fc_getMeshSkin(), fc_getSubsetVolume(), fc_subsetSegmentsMesh(), fc_subsetSegmentsSubset(), find_and_print_bbs(), freeShapeWOrder_ShapeOnly(), getDeathThresholdSubset(), main(), printStats(), processOneVar(), projection(), and segmentMesh().
  {
  int i, j;
  _FC_SubSlot* subSlot;
  _FC_MeshSlot* meshSlot;
  // special case: deleting a null handle is not an error
  if (FC_HANDLE_EQUIV(subset, FC_NULL_SUBSET)) {
    fc_printfWarningMessage("Deleting FC_NULL_SUBSET");
    return FC_SUCCESS;
  }
  // check input
  subSlot = _fc_getSubSlot(subset);
  if (subSlot == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Deleting subset '%s'", subSlot->header.name);
  // setup
  meshSlot = _fc_getMeshSlot(subSlot->mesh);
  // remove reference from mesh
  if (meshSlot->numSub == 1) {
    free(meshSlot->subIDs);
    meshSlot->subIDs = NULL;
  }
  else {
    for (i = 0; i < meshSlot->numSub; i++) {
      if (meshSlot->subIDs[i] == subSlot->header.slotID)
        break;
    }
    for (j = i+1; j < meshSlot->numSub; j++) {
      meshSlot->subIDs[j-1] = meshSlot->subIDs[j];
    }
  }
  meshSlot->numSub--;
  // clear & delete slot
  return _fc_deleteSubSlot(subset);
}
FC_ReturnCode fc_doSubsetsIntersect (FC_Subset subset1, FC_Subset subset2, int * indicator)
Test if two subsets intersect.
Description:
The indicator flag is set to true (1) if two subsets intersect and false (0) if they do not, and -1 in case of error.
Either input subset can be FC_NULL_SUBSET, but the routine will return early with an error if both are. Either subset can be empty, but the routine will return early with an error if both are.
Subsets must have the same associatation type and be defined on the same mesh. These are the same constraints as in fc_createSubsetIntersection().
Modifications:
10/27/05 ACG created
01/16/06 ACG making more efficient by copying guts of getSubsetIntersection but stopping when a match is found.
Parameters:
subset1 input - subset
subset2 input - subset
indicator output - indicator flag, 1 = they intersect
Definition at line 1684 of file subset.c.
References FC_ERROR, fc_getMeshFromSubset(), fc_getReturnCodeText(), fc_getSubsetInfo(), fc_getSubsetMembersAsArray(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, fc_isSubsetValid(), FC_NULL_SUBSET, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by calcShapeIntersection(), fc_createSideAdjacencyMatrix(), and fc_getSubsetDecayType().
  {
  FC_ReturnCode rc1,rc2;
  FC_Mesh mesh1, mesh2;
  FC_AssociationType assoc1, assoc2;
  int numMember1, *members1, numMember2, *members2;
  int i,j;
  if (indicator)
    *indicator = -1;
  // check input (1 NULL subset is o.k., but not both)
  if (!indicator ||
      (!fc_isSubsetValid(subset1) && !FC_HANDLE_EQUIV(subset1,FC_NULL_SUBSET)) ||
      (!fc_isSubsetValid(subset2) && !FC_HANDLE_EQUIV(subset2,FC_NULL_SUBSET)) ||
      (!fc_isSubsetValid(subset1) && !fc_isSubsetValid(subset2))   ) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  fc_printfLogMessage("doSubsetsIntersect ?");
  //if one is NULL then return 0
  if (FC_HANDLE_EQUIV(subset1,FC_NULL_SUBSET) ||
      FC_HANDLE_EQUIV(subset2,FC_NULL_SUBSET)){
    *indicator = 0;
    return FC_SUCCESS;
  }
  // check if subsets are defined on the same mesh, if not return input error
  rc1 = fc_getMeshFromSubset(subset1, &mesh1);
  rc2 = fc_getMeshFromSubset(subset2, &mesh2);
  if (rc1 != FC_SUCCESS || rc2 != FC_SUCCESS || !FC_HANDLE_EQUIV(mesh1,mesh2)) {
    fc_printfErrorMessage("FC_INPUT_ERROR: Can't get mesh from subset, or "
                          "subsets defined on different meshes");
    return  FC_INPUT_ERROR;
  }
  // get info about the subsets
  rc1 = fc_getSubsetInfo(subset1, NULL, NULL, &assoc1);
  rc2 = fc_getSubsetInfo(subset2, NULL, NULL, &assoc2);
  // check if both subsets have the same association
  if (rc1 != FC_SUCCESS || rc2 != FC_SUCCESS || assoc1 != assoc2 ) {
    fc_printfErrorMessage("FC_INPUT_ERROR: Can't get info from subset, or "
                          "subsets defined with different association type");
    return  FC_INPUT_ERROR;
  }
  // setup
  rc1 = fc_getSubsetMembersAsArray(subset1, &numMember1, &members1);
  rc2 = fc_getSubsetMembersAsArray(subset2, &numMember2, &members2);
  if (rc1 != FC_SUCCESS || rc2 != FC_SUCCESS) {
    free(members1);
    free(members2);
    return FC_ERROR;
  }
  //empty subsets
  if (numMember1 == 0 && numMember2 == 0){
    free(members1);
    free(members2);
    fc_printfErrorMessage("FC_INPUT_ERROR: Can't do two empty subsets");
    return  FC_INPUT_ERROR;
  }
  if (numMember1 == 0 || numMember2 == 0){
    free(members1);
    free(members2);
    *indicator = 0;
    return FC_SUCCESS;
  }
  // Walk both arrays at same time
  i = 0;
  j = 0;
  while (i < numMember1 && j < numMember2) {
    if (members1[i] < members2[j]) { // not the same
      i++;
    }
    else if (members1[i] > members2[j]) { // not the same
      j++;
    }
    else { // the same
      //then they intersect
      free(members1);
      free(members2);
      *indicator = 1;
      return FC_SUCCESS;
    }
  }
  //havent found anything in common
  *indicator = 0;
  free(members1);
  free(members2);
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshFromSubset (FC_Subset subset, FC_Mesh * mesh)
Get the parent mesh of the subset.
Modifications:
04/20/04 RM, created.
05/11/05 WSK, changed to reflect changes to FC_Subset.
Parameters:
subset input - subset handle
mesh output - mesh handle
Definition at line 2741 of file subset.c.
References _fc_getSubSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, FC_NULL_MESH, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SubSlot::mesh, and _FC_SlotHeader::name.
Referenced by _fc_buildFaceInfoListFromShape(), _fc_buildFaceInfoListFromSubset(), _fc_getSubsetDiameterCore(), _fc_getSubsetsDiameterCore(), _fc_getSubsetsProximityArgsTest(), _fc_getSubsetsProximityCore(), _fc_recursive_IndividuallySegmentingNodes(), calcSegmentsVolumes(), fc_convertSubsetsToSeqSubset(), fc_copyShape(), fc_copySubsetWithNewAssociation(), fc_createSideAdjacencyMatrix(), fc_createSubsetComplement(), fc_createSubsetIntersection(), fc_createSubsetMesh(), fc_doSubsetsIntersect(), fc_evalPrestoSpotWeld(), fc_getDecayedSkin(), fc_getDisplacedMeshesDiameter(), fc_getDisplacedSubsetBoundingBox(), fc_getDisplacedSubsetCentroid(), fc_getDisplacedSubsetDiameter(), fc_getDisplacedSubsetsDiameter(), fc_getDisplacedSubsetVolume(), fc_getElementsThatContainPointFromSubset(), fc_getExposedSkin(), fc_getMeshesDiameter(), fc_getPlanarSideNormal(), fc_getShapeSidesAreas(), fc_getSideNormalMeanSdev(), fc_getSubsetArea(), fc_getSubsetBoundingBox(), fc_getSubsetCentroid(), fc_getSubsetNeighbors(), fc_getSubsetShapes(), fc_getSubsetSkin(), fc_getSubsetVolume(), fc_getVariableWeightedDisplacedSubsetCentroid(), fc_getVariableWeightedSubsetCentroid(), fc_isSubsetSuperset(), fc_projectedSubsetElementBoundingBoxIntersection(), fc_reduceShapeNumSides(), fc_reshapeByAngle(), fc_segment(), fc_subsetSegmentsSubset(), main(), and myCharacterizationFunkyAve().
  {
  _FC_SubSlot* subSlot;
  // default return
  if (mesh)
    *mesh = FC_NULL_MESH;
  // check input
  subSlot = _fc_getSubSlot(subset);
  if(!subSlot || !mesh) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting mesh from subset '%s'", subSlot->header.name);
  // return requested value
  *mesh = subSlot->mesh;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getNumSeqSubset (FC_Mesh mesh, int * numSeqSubset)
Get the number of seq subsets in a mesh.
Modifications:
03/03/08 ACG created
Parameters:
mesh input - mesh
numSeqSubset output - number of subsets
Definition at line 1420 of file subset.c.
References _fc_getMeshSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, and _FC_MeshSlot::numSeqSub.
Referenced by _fc_writeExodusDataset(), and fc_printMesh().
  {
  _FC_MeshSlot* meshSlot;
  // set up defaults
  if (numSeqSubset != NULL)
    *numSeqSubset = -1;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || numSeqSubset == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting number of seq subsets from mesh '%s'",
                      meshSlot->header.name);
  // get num subset
  *numSeqSubset = meshSlot->numSeqSub;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getNumSubset (FC_Mesh mesh, int * numSubset)
Get the number of subsets in a mesh.
Modifications:
9/28/04 WSK created.
Parameters:
mesh input - mesh
numSubset output - number of subsets
Definition at line 1385 of file subset.c.
References _fc_getMeshSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, and _FC_MeshSlot::numSub.
Referenced by fc_printMesh().
  {
  _FC_MeshSlot* meshSlot;
  // set up defaults
  if (numSubset != NULL)
    *numSubset = -1;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || numSubset == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting number of subsets from mesh '%s'",
                      meshSlot->header.name);
  // get num subset
  *numSubset = meshSlot->numSub;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getSeqSubsetByName (FC_Mesh mesh, char * subName, int * numSeqSubset, int ** numStepPerSubset, FC_Subset *** seqSubsets)
Get sequence subsets of a given name from the mesh.
Description:
Returns an array of seq subset (array of arrays of subsets) as well as an array of the number of steps per sequence subset. The use is responsible for freeing all returned arrays. (SeqSubsets is a 2D array, so to free: for (i = 0; i < numSeq subs) { free(seqSubsets[i])); })
Modifications:
03/04/08 ACG created
Parameters:
mesh input - mesh handle
subName input - seq subset name
numSeqSubset output - number of sequence subsets
numStepPerSubset output - array with number of steps for each sequence subset
seqSubsets output - array of sequence subsets (each sequence subset is array of numStep subsets
Definition at line 1551 of file subset.c.
References _FC_GET_HANDLE, _fc_getMeshSlot(), _fc_getSubSlotFromID(), fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numSeqSub, _FC_MeshSlot::numStepPerSeqSub, and _FC_MeshSlot::seqSubIDs.
  {
  int i, j;
  _FC_MeshSlot *meshSlot;
  _FC_SubSlot *subSlot;
  int numStep;
  FC_Subset *seqsub;
  FC_Subset **lmatch = NULL;
  int *lstepmatch = NULL;
  int numlmatch, maxnumlmatch;
  // default return values
 if (numSeqSubset != NULL)
    *numSeqSubset = -1;
  if (numStepPerSubset != NULL)
    *numStepPerSubset = NULL;
  if (seqSubsets != NULL)
    *seqSubsets = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || !subName || numSeqSubset == NULL ||
      numStepPerSubset == NULL || seqSubsets == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting sequence subset '%s'", subName);
  numlmatch = 0;
  maxnumlmatch = 0;
 // look for subName in this mesh's seq sub list
  for (i = 0; i < meshSlot->numSeqSub; i++) {
    subSlot = _fc_getSubSlotFromID(meshSlot->seqSubIDs[i][0]);
    if (!strcmp(subName, subSlot->header.name)) {
      numStep = meshSlot->numStepPerSeqSub[i];
      seqsub = malloc((numStep)*sizeof(FC_Subset));
      if (seqsub == NULL) {
     fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
     return FC_MEMORY_ERROR;
      }
      for (j = 0; j < numStep; j++) {
     subSlot = _fc_getSubSlotFromID(meshSlot->seqSubIDs[i][j]);
     _FC_GET_HANDLE(seqsub[j], subSlot);
      }
      if (lmatch == NULL){
     lmatch = (FC_Subset**)malloc(sizeof(FC_Subset*));
     lstepmatch = (int*)malloc(sizeof(int));
     if (lmatch == NULL || lstepmatch == NULL){
       fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
       return FC_MEMORY_ERROR;
     }
     numlmatch = 1;
     maxnumlmatch = 1;
     lmatch[0] = seqsub;
     lstepmatch[0] = numStep;
      }else{
     if(numlmatch == maxnumlmatch){
       FC_Subset **temp;
       int *tempstep;
       temp = (FC_Subset**)realloc(lmatch,(2*numlmatch)*sizeof(FC_Subset*));
       tempstep = (int*)realloc(lstepmatch,(2*numlmatch)*sizeof(FC_Subset*));
       if (temp == NULL || tempstep == NULL){
         fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
         return FC_MEMORY_ERROR;
       }
       maxnumlmatch*=2;
       lmatch = temp;
       lstepmatch = tempstep;
     }
     lmatch[numlmatch] = seqsub;
     lstepmatch[numlmatch] = numStep;
     numlmatch++;
      }
    }
  }
  if (numlmatch){
    *numSeqSubset = numlmatch;
    *numStepPerSubset = lstepmatch;
    *seqSubsets = lmatch;
    return FC_SUCCESS;
  }
  //no matches
  *numSeqSubset = 0;
  *numStepPerSubset = NULL;
  *seqSubsets = NULL;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getSeqSubsets (FC_Mesh mesh, int * numSeqSubs, int ** numStepPerSub, FC_Subset *** seqSubs)
Get the seq subsets in a mesh.
Description:
This returns an array of the seq subsets in the mesh (array of arrays of subsets) as well as an array of the number of steps per seq subset. The caller is responsible for freeing all returned arrays. (SeqSubs is a 2D array so to free: for (i = 0; i < numSeqSub) { free(seqSub[i])})
Modifications:
03/03/08 ACG Created.
Parameters:
mesh input - mesh
numSeqSubs output - number of seq subsets
numStepPerSub output - array with number of steps for each seq sub
seqSubs output - array of seq subsets (each seq sub is an array of numStep subsets)
Definition at line 1313 of file subset.c.
References _FC_GET_HANDLE, _fc_getMeshSlot(), _fc_getSubSlotFromID(), fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numSeqSub, _FC_MeshSlot::numStepPerSeqSub, and _FC_MeshSlot::seqSubIDs.
Referenced by _fc_writeExodusDataset(), fc_copyMesh(), fc_createSubsetMesh(), fc_deleteMesh(), and fc_releaseMesh().
  {
  _FC_MeshSlot* meshSlot;
  _FC_SubSlot* subSlot;
  int i,j;
  // set up defaults
  if (numSeqSubs != NULL)
    *numSeqSubs = -1;
  if (numStepPerSub != NULL)
    *numStepPerSub = NULL;
  if (seqSubs != NULL)
    *seqSubs = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || numSeqSubs == NULL || numStepPerSub == NULL ||
      seqSubs == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting seq subsets from mesh '%s'",
                      meshSlot->header.name);
  // get num seq subsets
  *numSeqSubs = meshSlot->numSeqSub;
  // get seq subsets
  if (*numSeqSubs > 0) {
    *numStepPerSub = malloc(sizeof(int) * (*numSeqSubs));
    if (*numStepPerSub == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    *seqSubs = malloc(sizeof(FC_Subset*) * (*numSeqSubs));
    if (*seqSubs == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    for (i = 0; i < *numSeqSubs; i++) {
      (*numStepPerSub)[i] = meshSlot->numStepPerSeqSub[i];
      (*seqSubs)[i] = malloc(meshSlot->numStepPerSeqSub[i]*sizeof(FC_Subset));
      if ( (*seqSubs)[i] == NULL) {
     fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
     return FC_MEMORY_ERROR;
      }
      for (j = 0; j < meshSlot->numStepPerSeqSub[i]; j++){
     subSlot = _fc_getSubSlotFromID(meshSlot->seqSubIDs[i][j]);
     _FC_GET_HANDLE((*seqSubs)[i][j],subSlot);
      }
    }
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_getSequenceFromSeqSubset (int numStep, FC_Subset * seqSubset, FC_Sequence * sequence)
Get the parent sequence of a seq subset.
Modifications:
03/03/08 ACG created
Parameters:
numStep input - number of steps in sequence variable
seqSubset input - sequence subset (array of subsets)
sequence output - sequence handle
Definition at line 3131 of file subset.c.
References _fc_getSubSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSeqSubsetValid(), FC_NULL_SEQUENCE, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SlotHeader::name, and _FC_SubSlot::sequence.
Referenced by fc_copyMesh(), and fc_createSubsetMesh().
   {
  _FC_SubSlot* subSlot;
  //set default value
  if (sequence != NULL)
    *sequence = FC_NULL_SEQUENCE;
  //check input
  if (!fc_isSeqSubsetValid(numStep, seqSubset) || sequence == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  //log message
  subSlot = _fc_getSubSlot(seqSubset[0]);
  fc_printfLogMessage("Getting sequence from seq subset '%s'",
                subSlot->header.name);
  //return requested value
  *sequence = subSlot->sequence;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getSubsetAssociationType (FC_Subset subset, FC_AssociationType * assoc)
Get subset's association type.
Modifications:
09/20/04 WSK, created.
Parameters:
subset input - subset handle
assoc output - association type
Definition at line 2902 of file subset.c.
References _fc_getSubSlot(), _FC_SubSlot::assoc, FC_AT_UNKNOWN, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_SubSlot::header, and _FC_SlotHeader::name.
Referenced by _fc_getSubsetsProximityCore(), fc_copySubsetWithNewAssociation(), fc_createSideAdjacencyMatrix(), fc_createSubsetMesh(), fc_getPlanarSideNormal(), fc_getShapeSidesAreas(), fc_getShapeSidesDecayType(), fc_getSideNormalMeanSdev(), fc_getSubsetArea(), fc_getSubsetDecayType(), fc_projectedSubsetElementBoundingBoxIntersection(), and main().
  {
  _FC_SubSlot *subSlot;
  // default return value
  if (assoc)
    *assoc = FC_AT_UNKNOWN;
  // check input
  subSlot = _fc_getSubSlot(subset);
  if (subSlot == NULL || !assoc) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting association type for subset '%s'",
                      subSlot->header.name);
  // fill in requested value
  *assoc = subSlot->assoc;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getSubsetByName (FC_Mesh mesh, char * subName, int * numSubsets, FC_Subset ** subsets)
Get subsets of a given name from a mesh.
Description:
Returns subset on the mesh with the specified name.
Modifications:
05/27/04 WSK Created.
9/9/03 WSK, changed name and moved to mesh (to be next to fc_getSubsets)
9/26/06 ACG returns array
Parameters:
mesh input - mesh handle
subName input - subset name
numSubsets output - num matching
subsets output - subset handles
Definition at line 1461 of file subset.c.
References _FC_GET_HANDLE, _fc_getMeshSlot(), _fc_getSubSlotFromID(), fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numSub, and _FC_MeshSlot::subIDs.
Referenced by main().
  {
  int i;
  _FC_MeshSlot* meshSlot;
  _FC_SubSlot *subSlot;
  FC_Subset subset;
  FC_Subset *lmatch = NULL;
  int numlmatch, maxnumlmatch;
  // default values returned if anything goes wrong
  if (numSubsets)
    *numSubsets = -1;
  if (subsets)
    *subsets = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || subName == NULL || !numSubsets || !subsets){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting subset '%s'", subName);
  numlmatch = 0;
  maxnumlmatch = 0;
  // find the existing slot
  for (i = 0; i < meshSlot->numSub; i++) {
    subSlot = _fc_getSubSlotFromID(meshSlot->subIDs[i]);
    if (!strcmp(subSlot->header.name, subName)) {
      _FC_GET_HANDLE(subset, subSlot);
      if (lmatch == NULL){
     lmatch = (FC_Subset*)malloc(sizeof(FC_Subset));
     if (lmatch == NULL){
       fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
       return FC_MEMORY_ERROR;
     }
     numlmatch = 1;
     maxnumlmatch = 1;
     lmatch[0] = subset;
      }else{
     if(numlmatch == maxnumlmatch){
       FC_Subset *temp;
       temp = (FC_Subset*)realloc(lmatch,(2*numlmatch)*sizeof(FC_Subset));
       if (temp == NULL){
         fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
         return FC_MEMORY_ERROR;
       }
       maxnumlmatch*=2;
       lmatch = temp;
     }
     lmatch[numlmatch] = subset;
     numlmatch++;
      }
    }
  }
  *numSubsets = numlmatch;
  *subsets = lmatch;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getSubsetInfo (FC_Subset subset, int * numMember, int * maxNumMember, FC_AssociationType * assoc)
Get information about a subset.
Description:
Get number of elements in a subset, subset type and its association. Set an output argument to NULL if you don't need it to be returned.
Modifications:
04/20/04 RM, created.
05/11/04 WSK, changed to reflect changes to FC_Subset.
05/17/04 RM, added maxNumMember into return parameters
09/21/04 WSK, removed storage type from arguments.
Parameters:
subset input - subset handle
numMember output - optional, number of members in subset
maxNumMember output - optional, maximum value Member
assoc output - optional, association type
Definition at line 2782 of file subset.c.
References _fc_getSubSlot(), _FC_SubSlot::assoc, FC_AT_UNKNOWN, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SubSlot::maxNumMember, _FC_SlotHeader::name, and _FC_SubSlot::numMember.
Referenced by _fc_buildFaceInfoListFromSubset(), _fc_getSubsetDiameterCore(), _fc_getSubsetsDiameterCore(), _fc_writeExodusDataset(), fc_copySeqSubset(), fc_copySubset(), fc_createSubsetComplement(), fc_createSubsetIntersection(), fc_createSubsetMesh(), fc_doSubsetsIntersect(), fc_evalPrestoSpotWeld(), fc_getDecayedSkin(), fc_getDisplacedSubsetBoundingBox(), fc_getDisplacedSubsetCentroid(), fc_getElementsThatContainPointFromSubset(), fc_getExposedSkin(), fc_getSubsetBoundingBox(), fc_getSubsetCentroid(), fc_getSubsetNeighbors(), fc_getSubsetShapes(), fc_getSubsetSkin(), fc_getVariableSubsetMeanSdev(), fc_getVariableSubsetMinMax(), fc_getVariableSubsetSum(), fc_getVariableWeightedDisplacedSubsetCentroid(), fc_getVariableWeightedSubsetCentroid(), fc_isSubsetSuperset(), fc_printSeqSubsetRange(), fc_printSubset(), fc_printSubsetOfMesh(), fc_printSubsetOfVariable(), fc_releaseMesh(), fc_segment(), fc_subsetPlusNeighborGreaterSegmentationMesh(), fc_subsetSegmentsSubset(), main(), and myCharacterizationFunkyAve().
  {
  _FC_SubSlot* subSlot;
  // default return values
  if (numMember)
    *numMember = -1;
  if (maxNumMember)
    *maxNumMember = -1;
  if (assoc)
    *assoc = FC_AT_UNKNOWN;
  // check input
  subSlot = _fc_getSubSlot(subset);
  if (subSlot == NULL || (!numMember && !maxNumMember && !assoc)) {
     fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting info for subset '%s'", subSlot->header.name);
  // fill in requested values
  if (numMember)
    *numMember = subSlot->numMember;
  if (maxNumMember)
    *maxNumMember = subSlot->maxNumMember;
  if (assoc)
    *assoc = subSlot->assoc;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getSubsetMaxNumMember (FC_Subset subset, int * maxNumMember)
Get the maximum possible number of members a subset could have.
Description:
This number should be equal to the number of mesh subentities (e.g. vertices, edges, elements, etc). This is the maximum possible number of members and is also the length of the subset mask.
Modifications:
05/17/04 RM, created.
Parameters:
subset input - subset handle
maxNumMember output - maximum number the subset member can have
Definition at line 2868 of file subset.c.
References _fc_getSubSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SubSlot::maxNumMember, and _FC_SlotHeader::name.
Referenced by fc_createSubsetIntersection().
  {
  _FC_SubSlot* subSlot;
  // default return value
  if (maxNumMember)
    *maxNumMember = -1;
  // check input
  subSlot = _fc_getSubSlot(subset);
  if(subSlot == NULL || !maxNumMember) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting maximum possible number of members for subset "
                      "'%s'", subSlot->header.name);
  // fill in requested value
  *maxNumMember = subSlot->maxNumMember;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getSubsetMembersAsArray (FC_Subset subset, int * numMember, int ** array)
Get a copy of subset members as array.
Description:
Get a copy of a subset's members as array. Note It's user's responsibility to deallocate array's memory. The operation is done on native subset representation type.
Modifications:
04/30/04 RM, created.
05/11/05 WSK, changed to reflect changes to FC_Subset.
Parameters:
subset input - subset handle
numMember output - number of members in output array
array output - pointer to output array with subset members
Definition at line 3001 of file subset.c.
References _fc_getSubSlot(), _fc_readSubsetMembers(), _FC_SlotHeader::committed, fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SlotHeader::name, _FC_SubSlot::numMember, FC_SortedIntArray::numVal, _FC_SubSlot::sia, and FC_SortedIntArray::vals.
Referenced by _fc_buildFaceInfoListFromShape(), _fc_buildFaceInfoListFromSubset(), _fc_getSubsetDiameterCore(), _fc_getSubsetsDiameterCore(), _fc_getSubsetsProximityCore(), _fc_writeExodusDataset(), fc_computeNumOverlapScore(), fc_copySeqSubset(), fc_copySubset(), fc_copySubsetWithNewAssociation(), fc_createSubsetIntersection(), fc_createSubsetMesh(), fc_doSubsetsIntersect(), fc_evalPrestoSpotWeld(), fc_getDecayedShapeSkin(), fc_getDisplacedSubsetBoundingBox(), fc_getDisplacedSubsetCentroid(), fc_getDisplacedSubsetVolume(), fc_getPlanarSideNormal(), fc_getShapeSidesAreas(), fc_getSideNormalMeanSdev(), fc_getSubsetArea(), fc_getSubsetBoundingBox(), fc_getSubsetCentroid(), fc_getSubsetNeighbors(), fc_getSubsetSkin(), fc_getSubsetVolume(), fc_getVariableSubsetMeanSdev(), fc_getVariableSubsetMinMax(), fc_getVariableSubsetSum(), fc_getVariableWeightedDisplacedSubsetCentroid(), fc_getVariableWeightedSubsetCentroid(), fc_isSubsetSuperset(), fc_printSeqSubsetRange(), fc_printSubset(), fc_printSubsetOfMesh(), fc_printSubsetOfVariable(), fc_projectedSubsetElementBoundingBoxIntersection(), fc_reduceShapeNumSides(), fc_rewriteDataset(), fc_segment(), fc_subsetSegmentsSubset(), getDeathThresholdSubset(), and main().
  {
  FC_ReturnCode rc;
  int i;
  _FC_SubSlot* subSlot;
  // default returns
  if(numMember)
    *numMember = -1;
  if(array)
    *array = NULL;
  // check input
  subSlot = _fc_getSubSlot(subset);
  if (!subSlot || !numMember || !array) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // FIX? log?
  // trivial case, no members in subset
  if (subSlot->numMember == 0) {
    *numMember = 0;
    return FC_SUCCESS;
  }
  // lazy member fetching done here
  if (subSlot->header.committed == 1 && subSlot->sia.numVal == 0) {
    rc = _fc_readSubsetMembers(subset);
    if (rc != FC_SUCCESS) {
      fc_printfErrorMessage("Lazy loading of members of subset '%s' failed",
                            subSlot->header.name);
      return rc;
    }
  }
  // allocate memory for resulting array, copy subset members into it
  *array = malloc(sizeof(int)*subSlot->numMember);
  if(!(*array)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  //FIX: why doesn't this work?
  //memcpy(*array, subSlot->sia.vals, subSlot->numMember*sizeof(int));
  for (i = 0; i < subSlot->numMember; i++)
    (*array)[i] = subSlot->sia.vals[i];
  *numMember = subSlot->numMember;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getSubsetMembersAsMask (FC_Subset subset, int * maskLength, int ** mask)
Get a copy of subset members as mask.
Description:
Get a copy of a subset's members as mask array. Note It's user's responsibility to deallocate mask's memory.
Modifications:
04/30/04 RM, created.
05/11/05 WSK, changed to reflect changes to FC_Subset.
Parameters:
subset input - subset handle
maskLength output - length of mask array
mask output - pointer to output mask array
Definition at line 3069 of file subset.c.
References _fc_getSubSlot(), _fc_readSubsetMembers(), _FC_SlotHeader::committed, fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SubSlot::maxNumMember, _FC_SlotHeader::name, _FC_SubSlot::numMember, FC_SortedIntArray::numVal, _FC_SubSlot::sia, and FC_SortedIntArray::vals.
Referenced by fc_createSubsetComplement(), fc_getElementsThatContainPointFromSubset(), and myCharacterizationFunkyAve().
  {
  FC_ReturnCode rc;
  int i;
  _FC_SubSlot* subSlot;
  // default returns
  if(maskLength)
    *maskLength = -1;
  if(mask)
    *mask = NULL;
  // check input
  subSlot = _fc_getSubSlot(subset);
  if ( !subSlot || !maskLength || !mask) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // FIX? log?
  // lazy member fetching done here
  if (subSlot->header.committed == 1 && subSlot->sia.numVal == 0) {
    rc = _fc_readSubsetMembers(subset);
    if (rc != FC_SUCCESS) {
      fc_printfErrorMessage("Lazy loading of members of subset '%s' failed",
                            subSlot->header.name);
      return rc;
    }
  }
  // allocate memory for resulting mask array, initialize to zeros
  *mask = (int*)calloc(subSlot->maxNumMember, sizeof(int));
  if (!(*mask)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  // and length
  *maskLength = subSlot->maxNumMember;
  // trivial case, no members in subset
  if (subSlot->numMember == 0)
    return FC_SUCCESS;
  for (i = 0; i < subSlot->numMember; i++) {
    (*mask)[subSlot->sia.vals[i]] = 1;
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_getSubsetName (FC_Subset subset, char ** subsetName)
Get subset name.
Description:
Return copy of the name from the subset. User should free this memory later.
Modifications:
04/20/04 RM, created.
05/11/05 WSK, changed to reflect changes to FC_Subset.
Parameters:
subset input - subset handle
subsetName output - subset name
Definition at line 2700 of file subset.c.
References _fc_getSubSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_SubSlot::header, and _FC_SlotHeader::name.
Referenced by _fc_writeExodusDataset(), _fc_writeFeatureGroup(), calcSegmentsVolumes(), fc_copyShape(), fc_createSubsetMesh(), fc_getSubsetShapes(), fc_getSubsetSkin(), fc_printSubsetOfMesh(), fc_printSubsetOfVariable(), fc_reduceShapeNumSides(), main(), and processOneVar().
  {
  char *name;
  _FC_SubSlot* subSlot;
  // default return
  if(subsetName)
    *subsetName = NULL;
  // check input
  subSlot = _fc_getSubSlot(subset);
  if(subSlot == NULL || subsetName == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting name for subset '%s'", subSlot->header.name);
  // copy name
  name = subSlot->header.name;
  *subsetName = malloc(strlen(name) + 1);
  if (*subsetName == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  strcpy(*subsetName, name);
  return FC_SUCCESS;
}
FC_ReturnCode fc_getSubsetNumMember (FC_Subset subset, int * numMember)
Get number of members in a subset.
Modifications:
04/20/04 RM, created.
05/11/05 WSK, changed to reflect changes to FC_Subset.
Parameters:
subset input - subset handle
numMember output - number of members in the subset
Definition at line 2828 of file subset.c.
References _fc_getSubSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SlotHeader::name, and _FC_SubSlot::numMember.
Referenced by _fc_buildFaceInfoListFromSubset(), calcShapeIntersection(), fc_computeBestMatchNumOverlapScore(), fc_createSideAdjacencyMatrix(), fc_getSubsetDecayType(), fc_getSubsetSkin(), main(), printStats(), processOneVar(), and projection().
  {
  _FC_SubSlot* subSlot;
  // default return value
  if (numMember)
    *numMember = -1;
  // check input
  subSlot = _fc_getSubSlot(subset);
  if(subSlot == NULL || !numMember) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
     return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting number of members in the subset '%s'",
                       subSlot->header.name);
  *numMember = subSlot->numMember;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getSubsets (FC_Mesh mesh, int * numSubset, FC_Subset ** subsets)
Get the subsets in a mesh.
Description:
This returns an array of the subsets in the mesh. The caller is responsible for freeing the array of mesh handles.
Modifications:
05/13/04 WSK Created.
9/9/04 WSK, changed to return subset handles instead of subset names.
Parameters:
mesh input - mesh
numSubset output - number of subsets
subsets output - array of subsets
Definition at line 1253 of file subset.c.
References _FC_GET_HANDLE, _fc_getMeshSlot(), _fc_getSubSlotFromID(), fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numSub, and _FC_MeshSlot::subIDs.
Referenced by _fc_writeExodusDataset(), fc_copyMesh(), fc_createSubsetMesh(), fc_deleteMesh(), fc_releaseMesh(), fc_rewriteDataset(), and main().
  {
  int i;
  _FC_MeshSlot* meshSlot;
  _FC_SubSlot* subSlot;
  // set up defaults
  if (numSubset != NULL)
    *numSubset = -1;
  if (subsets != NULL)
    *subsets = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || numSubset == NULL || subsets == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting subsets from mesh '%s'",
                      meshSlot->header.name);
  // get num subset
  *numSubset = meshSlot->numSub;
  // get subsets
  if (meshSlot->numSub > 0) {
    *subsets = malloc(sizeof(FC_Subset) * meshSlot->numSub);
    if (*subsets == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    for (i = 0; i < meshSlot->numSub; i++) {
      subSlot = _fc_getSubSlotFromID(meshSlot->subIDs[i]);
      _FC_GET_HANDLE((*subsets)[i], subSlot);
    }
  }
  return FC_SUCCESS;
}
int fc_isMemberInSubset (FC_Subset subset, int memberID)
Check to see if a member is in a subset.
Description:
Check to see if a member is in a subset. Returns 1 if the member is present and 0 if not. If an error occurs, return an error code (always less than 1).
Modifications:
2006/8/17 WSK, created.
Parameters:
subset input - subset handle
memberID input - member ID
Definition at line 2948 of file subset.c.
References _fc_getSubSlot(), _fc_readSubsetMembers(), _FC_SlotHeader::committed, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isIntInSortedIntArray(), fc_printfErrorMessage, fc_printfWarningMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SubSlot::maxNumMember, _FC_SlotHeader::name, _FC_SubSlot::numMember, FC_SortedIntArray::numVal, and _FC_SubSlot::sia.
Referenced by findShapeSide(), and main().
  {
  FC_ReturnCode rc;
  _FC_SubSlot* subSlot;
  // check args
  subSlot = _fc_getSubSlot(subset);
  if (!subSlot) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // easy case 1: out of range
  if (memberID < 0 || memberID >= subSlot->maxNumMember) {
    fc_printfWarningMessage("Asked for member ID (%d) out of range (0-%d)",
                   memberID, subSlot->maxNumMember-1);
    return 0;
  }
  // easy case 2: empty
  if (subSlot->numMember < 1)
    return 0;
  // lazy member fetching done here
  if (subSlot->header.committed == 1 && subSlot->sia.numVal == 0) {
    rc = _fc_readSubsetMembers(subset);
    if (rc != FC_SUCCESS) {
      fc_printfErrorMessage("Lazy loading of members of subset '%s' failed",
                            subSlot->header.name);
      return rc;
    }
  }
  // general case
  return fc_isIntInSortedIntArray(&subSlot->sia, memberID);
}
int fc_isSeqSubsetValid (int numStep, FC_Subset * seqSub)
Check that the handle refers to a valid subset.
Description:
Returns 1 (true) if the seq subset handle is valid, and 0 (false) if it is not. Valid means numStep is correct and all subset handles are valid and in correct order)
Modifications:
03/03/08 ACG created
Parameters:
numStep input - num of steps in seq sub
seqSub input - seq subset (array of subsets)
Definition at line 2643 of file subset.c.
References _fc_getMeshSlot(), _fc_getSeqSlot(), _fc_getSubSlot(), FC_ERROR, fc_isSubsetValid(), fc_printfErrorMessage, _FC_SubSlot::header, _FC_SubSlot::mesh, _FC_MeshSlot::numSeqSub, _FC_SeqSlot::numStep, _FC_MeshSlot::seqSubIDs, _FC_SubSlot::sequence, and _FC_SlotHeader::slotID.
Referenced by fc_changeSeqSubsetName(), fc_convertSeqSubsetToSubsets(), fc_copySeqSubset(), fc_deleteSeqSubset(), fc_getSequenceFromSeqSubset(), and fc_releaseSeqSubset().
  {
  int i;
  _FC_SubSlot* subSlot;
  _FC_SeqSlot* seqSlot;
  _FC_MeshSlot* meshSlot;
  int sub_id;  //id's into mesh's slotID arrays
  //quick check
  if (numStep < 0 || seqSub == NULL || !fc_isSubsetValid(seqSub[0]))
    return 0;
  // check that numStep agrees with sequence
  subSlot = _fc_getSubSlot(seqSub[0]);
  seqSlot = _fc_getSeqSlot(subSlot->sequence);
  if (numStep != seqSlot->numStep)
    return 0;
  //check that all steps are valid and fromt he same subset
  //instead of checking metadata, we check against the parent's list
  meshSlot = _fc_getMeshSlot(subSlot->mesh);
  sub_id = -1;
  for (i = 0; i < meshSlot->numSeqSub; i++){
    if (subSlot->header.slotID == (meshSlot->seqSubIDs)[i][0]){
      sub_id = i;
      break;
    }
  }
  if (sub_id == -1){
    fc_printfErrorMessage("bad code? shouldn't ever happen?");
    return FC_ERROR;
  }
  for (i = 1; i < numStep; i++){
    if (!fc_isSubsetValid(seqSub[i]) ||
     seqSub[i].slotID != (meshSlot->seqSubIDs)[sub_id][i])
      return 0;
  }
  //passed all tests
  return 1;
}
FC_ReturnCode fc_isSubsetSuperset (FC_Subset subset_super, FC_Subset subset_sub, int * indicator)
Test if first subset is a superset of the second subset.
Description:
The indicator flag is set to true (1) if the first subset is a superset of the second and false (0) if, not and -1 in case of error.
Either input subset can be FC_NULL_SUBSET, but the routine will return early with an error if both are. Either subset can be empty, but the routine will return early with an error if both are.
Subsets must have the same associatation type and be defined on the same mesh. These are the same constraints as in fc_createSubsetIntersection().
Modifications:
02/13/06 ACG created
09/28/06 ACG bug fix in walking the array and end condition
Parameters:
subset_super input - subset
subset_sub input - subset
indicator output - indicator flag, 1 = is a superset
Definition at line 1809 of file subset.c.
References FC_ERROR, fc_getMeshFromSubset(), fc_getReturnCodeText(), fc_getSubsetInfo(), fc_getSubsetMembersAsArray(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, fc_isSubsetValid(), FC_NULL_SUBSET, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by fc_getSubsetDecayType().
  {
  FC_ReturnCode rc1,rc2;
  FC_Mesh mesh1, mesh2;
  FC_AssociationType assoc1, assoc2;
  int numMember1, *members1, numMember2, *members2;
  int i,j;
  if (indicator)
    *indicator = -1;
  // check input (1 NULL subset is o.k., but not both)
  if (!indicator ||
      (!fc_isSubsetValid(subset_super) && !FC_HANDLE_EQUIV(subset_super,FC_NULL_SUBSET)) ||
      (!fc_isSubsetValid(subset_sub) && !FC_HANDLE_EQUIV(subset_sub,FC_NULL_SUBSET)) ||
      (!fc_isSubsetValid(subset_super) && !fc_isSubsetValid(subset_sub))   ) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  fc_printfLogMessage("is Subset Superset ?");
  //if one is NULL then return 0
  if (FC_HANDLE_EQUIV(subset_super,FC_NULL_SUBSET) ||
      FC_HANDLE_EQUIV(subset_sub,FC_NULL_SUBSET)){
    *indicator = 0;
    return FC_SUCCESS;
  }
  // check if subsets are defined on the same mesh, if not return input error
  rc1 = fc_getMeshFromSubset(subset_super, &mesh1);
  rc2 = fc_getMeshFromSubset(subset_sub, &mesh2);
  if (rc1 != FC_SUCCESS || rc2 != FC_SUCCESS || !FC_HANDLE_EQUIV(mesh1,mesh2)) {
    fc_printfErrorMessage("FC_INPUT_ERROR: Can't get mesh from subset, or "
                          "subsets defined on different meshes");
    return  FC_INPUT_ERROR;
  }
  // get info about the subsets
  rc1 = fc_getSubsetInfo(subset_super, NULL, NULL, &assoc1);
  rc2 = fc_getSubsetInfo(subset_sub, NULL, NULL, &assoc2);
  // check if both subsets have the same association
  if (rc1 != FC_SUCCESS || rc2 != FC_SUCCESS || assoc1 != assoc2 ) {
    fc_printfErrorMessage("FC_INPUT_ERROR: Can't get info from subset, or "
                          "subsets defined with different association type");
    return  FC_INPUT_ERROR;
  }
  // setup
  rc1 = fc_getSubsetMembersAsArray(subset_super, &numMember1, &members1);
  rc2 = fc_getSubsetMembersAsArray(subset_sub, &numMember2, &members2);
  if (rc1 != FC_SUCCESS || rc2 != FC_SUCCESS) {
    free(members1);
    free(members2);
    return FC_ERROR;
  }
  //empty
  if (numMember1 == 0 && numMember2 == 0){
    free(members1);
    free(members2);
    fc_printfErrorMessage("FC_INPUT_ERROR: Can't do two empty subsets");
    return  FC_INPUT_ERROR;
  }
  if (numMember1 == 0 || numMember2 == 0){
    free(members1);
    free(members2);
    *indicator = 0;
    return FC_SUCCESS;
  }
  if (numMember1 < numMember2){
    free(members1);
    free(members2);
    *indicator = 0;
    return FC_SUCCESS;
  }
  // Walk both arrays at same time
  i = 0;
  j = 0;
  while (i < numMember1 && j < numMember2){
    if (members1[i] > members2[j]){
      free(members1);
      free(members2);
      *indicator = 0;
      return FC_SUCCESS;
    }else if (members1[i] == members2[j]){
      i++;
      j++;
    }else{
      i++;
    }
  }
  free(members1);
  free(members2);
  //did we get the last one ?
  *indicator = (j == numMember2);
  return FC_SUCCESS;
}
int fc_isSubsetValid (FC_Subset subset)
Check that the handle refers to a valid subset.
Description:
Returns 1 (true) if the handle is valid, and 0 (false) if it is not.
Modifications:
05/25/04 WSK Created.
Parameters:
subset input - subset handle
Definition at line 2622 of file subset.c.
References _fc_isHandleValid(), FC_Subset::slotID, subTableSize, and FC_Subset::uID.
Referenced by _fc_buildFaceInfoListFromSubset(), _fc_getSubsetsProximityArgsTest(), _fc_recursive_IndividuallySegmentingNodes(), fc_convertSubsetsToSeqSubset(), fc_copySubset(), fc_copySubsetWithNewAssociation(), fc_createSideAdjacencyMatrix(), fc_createSubsetComplement(), fc_createSubsetIntersection(), fc_doSubsetsIntersect(), fc_getDecayedShapeSides(), fc_getDecayedShapeSkin(), fc_getDecayedSkin(), fc_getDisplacedSubsetBoundingBox(), fc_getDisplacedSubsetCentroid(), fc_getDisplacedSubsetDiameter(), fc_getDisplacedSubsetsDiameter(), fc_getDisplacedSubsetVolume(), fc_getExposedSkin(), fc_getPlanarSideNormal(), fc_getShapeSidesAreas(), fc_getShapeSidesDecayType(), fc_getSideNormalMeanSdev(), fc_getSubsetArea(), fc_getSubsetBoundingBox(), fc_getSubsetCentroid(), fc_getSubsetDecayType(), fc_getSubsetDiameter(), fc_getSubsetNeighbors(), fc_getSubsetsDiameter(), fc_getSubsetShapes(), fc_getSubsetSkin(), fc_getSubsetVolume(), fc_getVariableSubsetMeanSdev(), fc_getVariableSubsetMinMax(), fc_getVariableSubsetSum(), fc_getVariableWeightedDisplacedSubsetCentroid(), fc_getVariableWeightedSubsetCentroid(), fc_isSeqSubsetValid(), fc_isSubsetSuperset(), fc_printSubsetOfMesh(), fc_printSubsetOfVariable(), fc_projectedSubsetElementBoundingBoxIntersection(), fc_subsetPlusNeighborGreaterSegmentationMesh(), fc_subsetSegmentsMesh(), fc_subsetSegmentsSubset(), and myCharacterizationFunkyAve().
  {
  return _fc_isHandleValid(subset.slotID, subset.uID, subTableSize,
                           (_FC_SlotHeader**)subTable);
}
FC_ReturnCode fc_printSeqSubset (int numStep, FC_Subset * seqSubset, char * label, int print_members)
Print sequence subset meta data to stdout, and optionally the member IDs.
Modifications:
04/29/08 CDU, created.
Parameters:
numStep input - number of steps in sequence subset
seqSubset input - the sequence subset
label input - label to prepend variable name with, can be NULL
print_members input - print the data values.
Definition at line 3368 of file subset.c.
References fc_printSeqSubsetRange().
 {
  return fc_printSeqSubsetRange(numStep, seqSubset, -1, -2, label, print_members);
}
FC_ReturnCode fc_printSeqSubsetRange (int numStep, FC_Subset * seqSubset, int range_start, int range_stop, char * label, int print_members)
Print sequence subset meta data to stdout, and optionally the member IDs (with start and stop index values).
Modifications:
04/29/08 CDU, created.
Parameters:
numStep input - number of steps in sequence subset
seqSubset input - the sequence subset
range_start input - offset of first variable to print or -1 for first, -2 for last
range_stop input - offset of last variable to print or -1 for first, -2 for last
label input - label to prepend variable name with, can be NULL
print_members input - print the data values.
Definition at line 3256 of file subset.c.
References _fc_getSubSlot(), FC_ERROR, fc_getAssociationTypeText(), fc_getReturnCodeText(), fc_getSubsetInfo(), fc_getSubsetMembersAsArray(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, fc_printfWarningMessage, FC_SUCCESS, and INDENT_STR.
Referenced by fc_printSeqSubset().
 {
  FC_ReturnCode rc;
  int i,k;
  _FC_SubSlot* subSlots[numStep];
  int start, stop, mod;
  int maxNumMember, numMember;
  FC_AssociationType assoc;
  int* members;
  // special case: printing a null handle is not an error
  if(numStep <= 0 || seqSubset == NULL) {
    fc_printfWarningMessage("Printing a NULL sequence subset");
    printf("Sequence Subset: FC_NULL_VARIABLE\n");
    return FC_SUCCESS;
  }
  //Check input
  for(i=0; i<numStep; i++){
    subSlots[i] = _fc_getSubSlot(seqSubset[i]);
    if(subSlots[i] == NULL){
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
      return FC_INPUT_ERROR;
    }
  }
  //log message
  fc_printfLogMessage("Printing SeqSubset '%s'", subSlots[0]->header.name);
  // print label & var name
  if (label)
    printf("%s: ", label);
  else
    printf("Sequence Subset: ");
  printf("'%s'\n", subSlots[0]->header.name);
  fflush(NULL);
  // print meta data
  rc = fc_getSubsetInfo(seqSubset[0], &numMember, &maxNumMember, &assoc);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get info for subset '%s'",
                          subSlots[0]->header.name);
    return rc;
  }
  printf("%snumMember = %d, maxNumMember = %d\n", INDENT_STR,
         numMember, maxNumMember);
  printf("%sassoc = %s\n", INDENT_STR, fc_getAssociationTypeText(assoc));
  fflush(NULL);
  if( print_members && numStep){
    //Handle special case where start/stop are the first/last steps
    if(range_start<0){
      start = (range_start==-2) ? numStep-1 : 0;
    } else {
      start = (range_start>numStep-1) ? numStep-1 : range_start;
    }
    if(range_stop<0){
      stop = (range_stop==-2) ? numStep-1 : 0;
    } else {
      stop = (range_stop>numStep-1) ? numStep-1 : range_stop;
    }
    //Calculate the step size's direction
    mod   = (start<=stop)   ? 1 : -1;
    for(k=start; (mod>0) ? (k<=stop) : (k>=stop) ; k+= mod){
      rc = fc_getSubsetMembersAsArray(seqSubset[k], &numMember, &members);
      if (rc != FC_SUCCESS) {
     fc_printfErrorMessage("Failed to get members for sequence subset '%s' step %d",
                     subSlots[k]->header.name, k);
     return FC_ERROR;
      }
      // print the members
      printf("%sMember IDs (Step %d of seqSubset '%s'):\n",
          INDENT_STR, k, subSlots[0]->header.name);
      for (i = 0; i < numMember; i++)
     printf("%s%s%d:  %6d\n", INDENT_STR, INDENT_STR, i, members[i]);
      fflush(NULL);
      free(members);
    }
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_printSubset (FC_Subset subset, char * label, int print_members)
Print subset meta data to stdout, and optionally the member IDs.
Modifications:
05/24/04 WSK, created.
Parameters:
subset input - the subset
label input - label to prepend subset name with, can be NULL
print_members input - 1 = print the member IDs.
Definition at line 3173 of file subset.c.
References _fc_getSubSlot(), FC_ERROR, fc_getAssociationTypeText(), fc_getReturnCodeText(), fc_getSubsetInfo(), fc_getSubsetMembersAsArray(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, FC_NULL_SUBSET, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_SubSlot::header, INDENT_STR, and _FC_SlotHeader::name.
Referenced by fc_printShape(), main(), printScrew(), and processOneVar().
  {
  FC_ReturnCode rc;
  int i;
  _FC_SubSlot* subSlot;
  int maxNumMember, numMember;
  FC_AssociationType assoc;
  int* members;
  // special case: printing a null handle is not an error
  if (FC_HANDLE_EQUIV(subset, FC_NULL_SUBSET)) {
    printf("Subset: FC_NULL_SUBSET\n");
    fflush(NULL);
    return FC_SUCCESS;
  }
  // check input
  subSlot = _fc_getSubSlot(subset);
  if (subSlot == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Printing subset '%s'", subSlot->header.name);
  // print label & var name
  if (label)
    printf("%s: ", label);
  else
    printf("Subset: ");
  printf("'%s'\n", subSlot->header.name);
  fflush(NULL);
  // print meta data
  rc = fc_getSubsetInfo(subset, &numMember, &maxNumMember, &assoc);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get info for subset '%s'",
                          subSlot->header.name);
    return rc;
  }
  printf("%snumMember = %d, maxNumMember = %d\n", INDENT_STR,
         numMember, maxNumMember);
  printf("%sassoc = %s\n", INDENT_STR, fc_getAssociationTypeText(assoc));
  fflush(NULL);
  // print values
  if (print_members && numMember > 0) {
    rc = fc_getSubsetMembersAsArray(subset, &numMember, &members);
    if (rc != FC_SUCCESS) {
      fc_printfErrorMessage("Failed to get members for subset '%s'",
                            subSlot->header.name);
      return FC_ERROR;
    }
    // print the members
    printf("%sMember IDs:\n", INDENT_STR);
    for (i = 0; i < numMember; i++)
      printf("%s%s%d:  %6d\n", INDENT_STR, INDENT_STR, i, members[i]);
    fflush(NULL);
    free(members);
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_printSubsetOfMesh (FC_Subset subset, FC_Mesh mesh)
Print the subset of a mesh.
Description:
If the association is the vertices, this will print the coordinates. If the association is not the vertices, this will print the appropriate connectivities.
This routine can be used with a subset on a different mesh, as long as the meshes are similar enough (i.e. same number of mesh subentities for the association type).
Modifications:
11/23/03 WSK Created to replace lots and lots of too specific printBLAH routines.
05/24/04 WSK Changed to printing a subset of a mesh.
12/15/04 WSK Fixed up - can handle edges & faces.
Parameters:
subset input - subset
mesh input - mesh
Definition at line 3401 of file subset.c.
References FC_AT_EDGE, FC_AT_ELEMENT, FC_AT_FACE, FC_AT_VERTEX, FC_AT_WHOLE_MESH, FC_ERROR, FC_ET_MIXED, fc_getAssociationTypeText(), fc_getElementTypeNumVertex(), fc_getElementTypeText(), fc_getMeshCoordsPtr(), fc_getMeshDim(), fc_getMeshEdgeConnsPtr(), fc_getMeshElementConnsPtr(), fc_getMeshElementType(), fc_getMeshFaceConnsPtr(), fc_getMeshFaceType(), fc_getMeshName(), fc_getMeshNumEntity(), fc_getReturnCodeText(), fc_getSubsetInfo(), fc_getSubsetMembersAsArray(), fc_getSubsetName(), FC_INPUT_ERROR, fc_isMeshValid(), fc_isSubsetValid(), fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, and INDENT_STR.
  {
  FC_ReturnCode rc;
  int i, j;
  int dim, numMember, maxNumMember, *members, numEntity;
  char* meshName, *subsetName;
  FC_AssociationType assoc;
  FC_ElementType elemType;
  // check input
  if (!fc_isSubsetValid(subset) || !fc_isMeshValid(mesh)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // get meta data
  rc = fc_getSubsetInfo(subset, &numMember, &maxNumMember, &assoc);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getMeshNumEntity(mesh, assoc, &numEntity);
  if (rc != FC_SUCCESS)
    return rc;
  // a little more checking - have to have same total number of entity
  if (maxNumMember != numEntity) {
    fc_printfErrorMessage("Subset and mesh do not have similar enough "
                          "associations");
    return FC_INPUT_ERROR;
  }
  // get some more info
  rc = fc_getMeshName(mesh, &meshName);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getSubsetName(subset, &subsetName);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getSubsetMembersAsArray(subset, &numMember, &members);
  if (rc != FC_SUCCESS)
    return rc;
  // log message
  fc_printfLogMessage("Printing subset '%s' of mesh '%s'", subsetName,
                      meshName);
  // print meta data
  printf("Subset '%s' of Mesh '%s'\n", subsetName, meshName);
  printf("%snumMember = %d (of %d), assoc = %s, ", INDENT_STR, numMember,
         maxNumMember, fc_getAssociationTypeText(assoc));
  fflush(NULL);
  switch(assoc) {
  case FC_AT_EDGE: // fall through to FC_AT_WHOLE_MESH
  case FC_AT_WHOLE_MESH:
    printf("\n");
    break;
  case FC_AT_VERTEX:
    fc_getMeshDim(mesh, &dim);
    printf("dim = %d\n", dim);
    break;
  case FC_AT_FACE:
    fc_getMeshFaceType(mesh, &elemType);
    printf("faceType = %s\n", fc_getElementTypeText(elemType));
    break;
  case FC_AT_ELEMENT:
    fc_getMeshElementType(mesh, &elemType);
    printf("elemType = %s\n", fc_getElementTypeText(elemType));
    break;
  default:
    return FC_ERROR;
  }
  fflush(NULL);
  // print the data
  if (numMember > 0) {
    if (assoc == FC_AT_WHOLE_MESH) {
      ; // do nothing
    }
    else if (assoc == FC_AT_VERTEX) { // print coords of members
      double* coords;
      rc = fc_getMeshCoordsPtr(mesh, &coords);
      if (rc != FC_SUCCESS)
        return rc;
      printf("%sVertex Coordinates:\n", INDENT_STR);
      for (i = 0; i < numMember; i++) {
        printf("%s%s%d:  ", INDENT_STR, INDENT_STR, members[i]);
        for (j = 0; j < dim; j++)
          printf("%11g ", coords[members[i]*dim +j]);
        printf("\n");
      }
      fflush(NULL);
    }
    else { // print connectivities of members
      int* conns;
      int numVertPerEntity = 0, *numVertPerFace = NULL, numVert;
      if (assoc == FC_AT_EDGE) {
        numVertPerEntity = 2;
        rc = fc_getMeshEdgeConnsPtr(mesh, &conns);
        if (rc != FC_SUCCESS)
          return rc;
        printf("%sEdge connectivities:\n", INDENT_STR);
      }
      else if (assoc == FC_AT_FACE && elemType == FC_ET_MIXED) {
        rc = fc_getMeshFaceConnsPtr(mesh, &numVertPerFace, &numVertPerEntity,
                                    &conns);
        if (rc != FC_SUCCESS)
          return rc;
        printf("%sFace connectivities (3 or 4 vertices per face):\n",
               INDENT_STR);
      }
      else if (assoc == FC_AT_FACE) {
        rc = fc_getMeshFaceConnsPtr(mesh, NULL, &numVertPerEntity, &conns);
        if (rc != FC_SUCCESS)
          return rc;
        printf("%sFace connectivities (%d vertices per face):\n",
               INDENT_STR, numVertPerEntity);
      }
      else {
        numVertPerEntity = fc_getElementTypeNumVertex(elemType);
        rc = fc_getMeshElementConnsPtr(mesh, &conns);
        if (rc != FC_SUCCESS)
          return rc;
        printf("%sElement connectivities (%d vertices per element):\n",
               INDENT_STR, numVertPerEntity);
      }
      fflush(NULL);
      for (i = 0; i < numMember; i++) {
        printf("%s%s%d:  ", INDENT_STR, INDENT_STR, members[i]);
        if (assoc == FC_AT_FACE && elemType == FC_ET_MIXED)
          numVert = numVertPerFace[members[i]];
        else
          numVert = numVertPerEntity;
        for (j = 0; j < numVert; j++)
          printf("%6d ", conns[members[i]*numVertPerEntity + j]);
        printf("\n");
      }
      fflush(NULL);
    }
  }
  // cleanup
  free(members);
  free(meshName);
  free(subsetName);
  return FC_SUCCESS;
}
FC_ReturnCode fc_printSubsetOfVariable (FC_Subset subset, FC_Variable variable)
Print the subset of a variable.
Description:
Print the data values on the subset of the mesh. This only works if the subset and variable share the same association type, and their parent meshes are similar enough (i.e. same number of mesh subentities for association type).
Modifications:
11/26/03 WSK Created.
05/24/04 WSK Changed to printing a subset of a variable.
Parameters:
subset input - subset
variable input - variable
Definition at line 3570 of file subset.c.
References FC_DT_CHAR, FC_DT_DOUBLE, FC_DT_FLOAT, FC_DT_INT, FC_DT_UNKNOWN, fc_getAssociationTypeText(), fc_getDataTypeText(), fc_getMathTypeText(), fc_getReturnCodeText(), fc_getSubsetInfo(), fc_getSubsetMembersAsArray(), fc_getSubsetName(), fc_getVariableDataPtr(), fc_getVariableInfo(), fc_getVariableName(), FC_INPUT_ERROR, fc_isSubsetValid(), fc_isVariableValid(), fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, and INDENT_STR.
  {
  FC_ReturnCode rc;
  int i, j;
  int numDataPoint, numComp, numMember, maxNumMember, *members;
  char* varName, *subsetName;
  FC_AssociationType assoc, temp_assoc;
  FC_DataType dataType;
  FC_MathType mathType;
  // check input
  if (!fc_isSubsetValid(subset) || !fc_isVariableValid(variable)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // get meta data
  rc = fc_getSubsetInfo(subset, &numMember, &maxNumMember, &temp_assoc);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getVariableInfo(variable, &numDataPoint, &numComp, &assoc,
                          &mathType, &dataType);
  if (rc != FC_SUCCESS)
    return rc;
  // a little more checking - have to have same total number of entity
  if (temp_assoc != assoc || maxNumMember != numDataPoint) {
    fc_printfErrorMessage("Subset and mesh do not have similar enough "
                          "associations");
    return FC_INPUT_ERROR;
  }
  rc = fc_getVariableName(variable, &varName);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getSubsetName(subset, &subsetName);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getSubsetMembersAsArray(subset, &numMember, &members);
  if (rc != FC_SUCCESS)
    return rc;
  // log message
  fc_printfLogMessage("Printing subset '%s' of variable '%s'", subsetName,
                      varName);
  // print meta data
  printf("Subset '%s' of Variable '%s'\n", subsetName, varName);
  printf("%snumMember = %d (of %d), numComponent = %d\n", INDENT_STR,
         numMember, maxNumMember, numComp);
  printf("%sassoc = %s, mathType = %s, dataType = %s\n", INDENT_STR,
         fc_getAssociationTypeText(assoc), fc_getMathTypeText(mathType),
         fc_getDataTypeText(dataType));
  fflush(NULL);
  if (numMember > 0) {
    // print the values
    void* dbuf;
    rc = fc_getVariableDataPtr(variable, &dbuf);
    if (rc != FC_SUCCESS)
      return rc;
    printf("%sData:\n", INDENT_STR);
    fflush(NULL);
    switch (dataType) {
    case FC_DT_CHAR:
      {
        char* cast_buf = (char *)dbuf;
        for (i = 0; i < numMember; i++) {
          printf("%s%s%d:  ", INDENT_STR, INDENT_STR, members[i]);
          for (j = 0; j < numComp; j++)
            printf("%c ", cast_buf[members[i]*numComp + j]);
          printf("\n");
        }
      }
      break;
    case FC_DT_INT:
      {
        int* cast_buf = (int *)dbuf;
        for (i = 0; i < numMember; i++) {
          printf("%s%s%d:  ", INDENT_STR, INDENT_STR, members[i]);
          for (j = 0; j < numComp; j++)
            printf("%6d ", cast_buf[members[i]*numComp + j]);
          printf("\n");
        }
      }
      break;
    case FC_DT_FLOAT:
      {
        float* cast_buf = (float *)dbuf;
        for (i = 0; i < numMember; i++) {
          printf("%s%s%d:  ", INDENT_STR, INDENT_STR, members[i]);
          for (j = 0; j < numComp; j++)
            printf("%11.6g ", cast_buf[members[i]*numComp + j]);
          printf("\n");
        }
      }
      break;
    case FC_DT_DOUBLE:
      {
        double* cast_buf = (double *)dbuf;
        for (i = 0; i < numMember; i++) {
          printf("%s%s%d:  ", INDENT_STR, INDENT_STR, members[i]);
          for (j = 0; j < numComp; j++)
            // print the same way as in fc_printVariable()
            printf("%16.11g ", cast_buf[members[i]*numComp + j]);
          printf("\n");
        }
      }
      break;
    case FC_DT_UNKNOWN:
      printf("Cannot print data type '%s'\n", fc_getDataTypeText(dataType));
    }
    fflush(NULL);
  }
  // cleanup
  free(members);
  free(varName);
  free(subsetName);
  return FC_SUCCESS;
}
FC_ReturnCode fc_releaseSeqSubset (int numStep, FC_Subset * subsets)
Attempt to minimize seq subset's memory usage.
Description:
Call to try and release un-needed memory in a seq subset. If the subset has been saved to disk, the large data is released. If the subset has not been saved to disk, this will do nothing.
fc_releaseSubset() can be called on specific steps of the seq subset.
Todo:
test this. note that there is no way to have commmitted seqSubsets in exodus
Modifications:
03/03/08 ACG Created.
Parameters:
numStep input - number of steps in the seq subset
subsets input - subset handles
Definition at line 2427 of file subset.c.
References _fc_getSubSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSeqSubsetValid(), fc_printfErrorMessage, fc_printfLogMessage, fc_printfWarningMessage, fc_releaseSubset(), FC_SUCCESS, _FC_SubSlot::header, and _FC_SlotHeader::name.
Referenced by fc_releaseMesh().
  {
  FC_ReturnCode rc, rc_keep = FC_SUCCESS;
  int i;
  _FC_SubSlot* subSlot;
  // special case: releasing a null handle is not an error
  if ( numStep < 1 || subsets == NULL) {
    fc_printfWarningMessage("Releasing NULL seq subset");
    return FC_SUCCESS;
  }
  // check input
  if (!fc_isSeqSubsetValid(numStep, subsets)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  subSlot = _fc_getSubSlot(subsets[0]);
  if (subSlot == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Cleaning up subset '%s'", subSlot->header.name);
  //do it
  rc_keep = FC_SUCCESS;
  for (i = 0; i < numStep; i++) {
    rc = fc_releaseSubset(subsets[i]);
    if (rc != FC_SUCCESS)
      rc_keep = rc;
  }
  return rc_keep;
}
FC_ReturnCode fc_releaseSubset (FC_Subset subset)
Attempt to minimize subset's memory usage.
Description:
Call to try and release un-needed memory in a subset. If the subset has been saved to disk, the large data is released. If the subset has not been saved to disk, this will do nothing.
Modifications:
04/19/04 WSK Created.
Parameters:
subset input - subset handle
Definition at line 2376 of file subset.c.
References _fc_getSubSlot(), _FC_SlotHeader::committed, fc_freeSortedIntArray(), fc_getReturnCodeText(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, FC_NULL_SUBSET, fc_printfErrorMessage, fc_printfLogMessage, fc_printfWarningMessage, FC_SUCCESS, _FC_SubSlot::header, _FC_SlotHeader::name, and _FC_SubSlot::sia.
Referenced by fc_releaseMesh(), and fc_releaseSeqSubset().
  {
  _FC_SubSlot* subSlot;
  // special case: releasing a null handle is not an error
  if (FC_HANDLE_EQUIV(subset, FC_NULL_SUBSET)) {
    fc_printfWarningMessage("Releasing FC_NULL_SUBSET");
    return FC_SUCCESS;
  }
  // check input
  subSlot = _fc_getSubSlot(subset);
  if (subSlot == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Cleaning up subset '%s'", subSlot->header.name);
  // remove big data if this slot is committed
  if (subSlot->header.committed == 1) {
    fc_freeSortedIntArray(&subSlot->sia);
  }
  return FC_SUCCESS;
}