FCLib: (Private)
(Private)
[Dataset]
Data Structures
struct _FC_DsSlot
Dataset Slot Structure for the Dataset Table.
Functions
void _fc_initDsSlot (_FC_DsSlot *dsSlot)
Initialize a dataset slot.
void _fc_clearDsSlot (_FC_DsSlot *dsSlotp)
Clear a dataset slot.
int _fc_getDsTableSize ()
Get the size of the dataset table.
_FC_DsSlot * _fc_getNewDsSlot ()
Get an empty dataset slot from the dataset table.
_FC_DsSlot * _fc_getDsSlot (FC_Dataset dataset)
Get a dataset slot from a dataset handle.
_FC_DsSlot * _fc_getDsSlotFromID (int dsID)
Get a dataset slot based on ID.
FC_ReturnCode _fc_deleteDsSlot (FC_Dataset dataset)
Delete the dataset slot associated with the dataset handle.
void _fc_printDsTable (char *label)
Print the contents of the Dataset Table (dsTable) to stderr.
void _fc_freeDsTable ()
Free all entries in the dataset table.
Variables
static int dsTableSize = 0
The number of allocated slots in the dataset table.
static _FC_DsSlot ** dsTable = NULL
The datasest table.
static FC_SortedIntArray dsOpenSlots = { 0, 0, 0 }
The list of unused slots in the dataset table.
Function Documentation
void _fc_clearDsSlot (_FC_DsSlot * dsSlotp)
Clear a dataset slot.
Description:
Releases all dynamically allocated resources in a dataset, and reinitializes all members.
Modifications:
2003-APR-17 W Koegler Created
2003-APR-31 W Koegler Made more comprehensive
Parameters:
dsSlotp input - dtable pointer
Definition at line 940 of file dataset.c.
References _fc_clearSlotHeader(), _fc_initDsSlot(), _FC_DsSlot::baseFile, _FC_DsSlot::basicVarIDs, _FC_DsSlot::header, _FC_DsSlot::meshIDs, _FC_DsSlot::numSeqVar, _FC_DsSlot::numStepPerSeqVar, _FC_DsSlot::seqIDs, and _FC_DsSlot::seqVarIDs.
Referenced by _fc_deleteDsSlot(), and _fc_freeDsTable().
  {
  int i;
  if (dsSlotp != NULL) {
    // free strings
    if (dsSlotp->baseFile)
      free(dsSlotp->baseFile);
    // free dynamic arrays
    if (dsSlotp->meshIDs)
      free(dsSlotp->meshIDs);
    if (dsSlotp->seqIDs)
      free(dsSlotp->seqIDs);
    if (dsSlotp->basicVarIDs)
      free(dsSlotp->basicVarIDs);
    if (dsSlotp->numStepPerSeqVar)
      free(dsSlotp->numStepPerSeqVar);
    if (dsSlotp->seqVarIDs) {
      for (i = 0; i < dsSlotp->numSeqVar; i++)
     free(dsSlotp->seqVarIDs[i]);
      free(dsSlotp->seqVarIDs);
    }
    // clear table header
    _fc_clearSlotHeader(&dsSlotp->header);
    // reinit
    _fc_initDsSlot(dsSlotp);
  }
}
FC_ReturnCode _fc_deleteDsSlot (FC_Dataset dataset)
Delete the dataset slot associated with the dataset handle.
Description:
This routine clears the dynamic data in the slot and then deletes the slot from the table.
Modifications:
12/20/2005 WSD. Created.
Parameters:
dataset input - dataset
Definition at line 1075 of file dataset.c.
References _fc_clearDsSlot(), _fc_deleteSlot(), _fc_getDsSlot(), dsTableSize, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, _FC_DsSlot::header, and _FC_SlotHeader::slotID.
Referenced by fc_deleteDataset().
  {
  _FC_DsSlot* dsSlot;
  dsSlot = _fc_getDsSlot(dataset);
  if (dsSlot == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // do it
  _fc_clearDsSlot(dsSlot);
  return _fc_deleteSlot(dsSlot->header.slotID, dsTableSize,
               (_FC_SlotHeader**)dsTable, &dsOpenSlots);
}
void _fc_freeDsTable (void)
Free all entries in the dataset table.
Description:
This should only be called after making sure that all slots have been cleared.
Modifications:
05/21/04 WSK Created.
Definition at line 1212 of file dataset.c.
References _fc_clearDsSlot(), dsTableSize, and fc_freeSortedIntArray().
Referenced by fc_finalLibrary().
                       {
  int i;
  for (i = 0; i < dsTableSize; i++) {
    _fc_clearDsSlot(dsTable[i]);
    free(dsTable[i]);
  }
  free(dsTable);
  fc_freeSortedIntArray(&dsOpenSlots);
  dsTableSize = 0;
  dsTable = NULL;
}
_FC_DsSlot* _fc_getDsSlot (FC_Dataset dataset)
Get a dataset slot from a dataset handle.
Description:
The slot id of the dataset handle is used to find the the slot in the dataset table. The identity is then verified by checking that the slot and the handle's uIDs are the same. On success, a pointer to the slot is returned. Otherwise a NULL pointer is returned.
Modifications:
2003-OCT-19 WSK Created to replace using _fc_checkhandle and GET_ID for better type checking (using pointer's to slots is less bug prone than lot's of xxxTable[xxxID] references).
05/25/04 WSK Changed to call new _fc_isHandleValid common to all tables.
Parameters:
dataset input - dataset
Definition at line 1029 of file dataset.c.
References _fc_isHandleValid(), dsTableSize, FC_Dataset::slotID, and FC_Dataset::uID.
Referenced by _fc_closeDataset(), _fc_closeExodusDataset(), _fc_closeLSDynaDataset(), _fc_deleteDsSlot(), _fc_getMeshExodusGlobalElementIDOffset(), _fc_getMeshExodusGlobalNodalIDsPtr(), _fc_hasSharedLSDynaVertices(), _fc_loadExodusDataset(), _fc_loadLSDynaDataset(), _fc_readExodusAttributeData(), _fc_readExodusMeshCoords(), _fc_readExodusMeshElemConns(), _fc_readExodusOneStepVariableData(), _fc_readExodusSequenceCoords(), _fc_readExodusSubsetMembers(), _fc_readLSDynaMeshCoords(), _fc_readLSDynaMeshElemConns(), _fc_readLSDynaVariableData(), _fc_readMeshCoords(), _fc_readMeshElemConns(), _fc_readSequenceCoords(), _fc_readSubsetMembers(), _fc_readVariableData(), _fc_writeExodusDataset(), fc_changeDatasetName(), fc_convertVariablesToSeqVariable(), fc_copyDataset(), fc_copyGlobalSeqVariable(), fc_copyMesh(), fc_copySequence(), fc_createGlobalSeqVariable(), fc_createGlobalVariable(), fc_createIntersectingRangeRegularSequence(), fc_createIntersectingRegularSequence(), fc_createMesh(), fc_createRegularSequence(), fc_createSequence(), fc_createSubsetMesh(), fc_deleteDataset(), fc_deleteMesh(), fc_deleteSequence(), fc_deleteSeqVariable(), fc_deleteVariable(), fc_getDatasetFileIOType(), fc_getDatasetName(), fc_getGlobalSeqVariableByName(), fc_getGlobalSeqVariables(), fc_getGlobalVariableByName(), fc_getGlobalVariables(), fc_getMeshByName(), fc_getMeshes(), fc_getNumGlobalSeqVariable(), fc_getNumGlobalVariable(), fc_getNumMesh(), fc_getNumSequence(), fc_getSequenceByName(), fc_getSequences(), fc_isSeqVariableValid(), fc_printDataset(), fc_releaseDataset(), fc_rewriteDataset(), fc_setVariableData(), fc_setVariableDataPtr(), fc_shiftAndScaleSequence(), and fc_writeDataset().
  {
  if (_fc_isHandleValid(dataset.slotID, dataset.uID, dsTableSize,
                        (_FC_SlotHeader**)dsTable))
    return dsTable[dataset.slotID];
  else
    return NULL;
}
_FC_DsSlot* _fc_getDsSlotFromID (int dsID)
Get a dataset slot based on ID.
Description:
The _FC_DsSlot at the requested slotID is returned. This should only be used when you really know that it is the slot you want because there is no checking of the uID like with _fc_getDsSlot. The only checking is that the slotID is exists in the table and that the uID is > 0 (i.e. it is not empty).
Modifications:
11/27/03 WSK Created so that external routines can index into tables without knowing about them.
05/25/04 WSK Changed to call new _fc_getSlot() common to all tables.
Definition at line 1056 of file dataset.c.
References _fc_getSlot(), and dsTableSize.
Referenced by fc_finalLibrary(), fc_getDatasetByName(), fc_getDatasets(), and fc_getNumDataset().
  {
  return (_FC_DsSlot*) _fc_getSlot(dsID, dsTableSize,
                                   (_FC_SlotHeader**)dsTable);
}
int _fc_getDsTableSize (void)
Get the size of the dataset table.
Modifications:
05/21/04 WSK Created.
Definition at line 980 of file dataset.c.
References dsTableSize.
Referenced by fc_finalLibrary(), fc_getDatasetByName(), fc_getDatasets(), and fc_getNumDataset().
{
  return dsTableSize;
}
_FC_DsSlot* _fc_getNewDsSlot (void)
Get an empty dataset slot from the dataset table.
Description:
Will return a new slot or NULL. A NULL means a memory error occurred.
Modifications:
2003-MAY-01 W Koegler Created
12/08/03 WSK Changed because changed XTables from arrays of slots to arrays of handles to slots. The _fc_new_XSlot() routines do not call a common helper routine anymore.
5/11/04 WSK Moved common code from _fc_getNewDsSlot(), _fc_getNewSeqSlot(), etc to _fc_getNewSlot().
Definition at line 1000 of file dataset.c.
References _fc_getNewSlot(), _fc_initDsSlot(), and dsTableSize.
Referenced by fc_createDataset().
{
  _FC_DsSlot* dsSlot;
  dsSlot = (_FC_DsSlot*) _fc_getNewSlot(&dsTableSize,
                         (_FC_SlotHeader***)&dsTable,
                         &dsOpenSlots, sizeof(_FC_DsSlot));
  _fc_initDsSlot(dsSlot);
  return dsSlot;
}
void _fc_initDsSlot (_FC_DsSlot * dsSlot)
Initialize a dataset slot.
Modifications: APR-30-2003 W Koegler Created.
Parameters:
dsSlot input - the dataset slot to initialize
Definition at line 907 of file dataset.c.
References _fc_initSlotHeader(), _FC_DsSlot::baseFile, _FC_DsSlot::basicVarIDs, FC_FT_NONE, _FC_DsSlot::fileType, _FC_DsSlot::header, _FC_DsSlot::meshIDs, _FC_DsSlot::numBasicVar, _FC_DsSlot::numMesh, _FC_DsSlot::numSeq, _FC_DsSlot::numSeqVar, _FC_DsSlot::numStepPerSeqVar, _FC_DsSlot::seqIDs, _FC_DsSlot::seqVarIDs, and _FC_DsSlot::writable.
Referenced by _fc_clearDsSlot(), and _fc_getNewDsSlot().
  {
  if (dsSlot != NULL) {
    _fc_initSlotHeader(&dsSlot->header);
    dsSlot->fileType = FC_FT_NONE;
    dsSlot->baseFile = NULL;
    dsSlot->writable = 1;
    dsSlot->numSeq = 0;
    dsSlot->seqIDs = NULL;
    dsSlot->numMesh = 0;
    dsSlot->meshIDs = NULL;
    dsSlot->numBasicVar = 0;
    dsSlot->basicVarIDs = NULL;
    dsSlot->numSeqVar = 0;
    dsSlot->numStepPerSeqVar = 0;
    dsSlot->seqVarIDs = 0;
  }
}
void _fc_printDsTable (char * label)
Print the contents of the Dataset Table (dsTable) to stderr.
Description:
Prints the contents of the Datatset Table in a human readable form. It takes a string to use as a label for this print out of the table. Pass NULL if you don't want a label.
Modifications:
Nancy Collins Created.
2003-NOV-13 WSK Fixed up.
Parameters:
label Input - label for this version the table (without a trailing \n) pass NULL if no label is desired
Definition at line 1106 of file dataset.c.
References _fc_printSlotHeader(), _FC_DsSlot::baseFile, _FC_DsSlot::basicVarIDs, dsTableSize, fc_getFileIOTypeText(), _FC_DsSlot::fileType, _FC_DsSlot::header, _FC_DsSlot::meshIDs, _FC_DsSlot::numBasicVar, _FC_DsSlot::numMesh, _FC_DsSlot::numSeq, _FC_DsSlot::numSeqVar, _FC_DsSlot::numStepPerSeqVar, _FC_DsSlot::seqIDs, _FC_DsSlot::seqVarIDs, TABLE_DIVIDER_STRING, and _FC_DsSlot::writable.
  {
  int i, j, k;
  _FC_DsSlot* dsSlot;
  // print table heading
  fprintf(stderr, TABLE_DIVIDER_STRING);
  fprintf(stderr, "Dataset Table (dsTable):\n");
  if (label != NULL)
    fprintf(stderr, "%s\n", label);
  fprintf(stderr, TABLE_DIVIDER_STRING);
  fflush(NULL);
  // We're done if it's empty
  if (dsTableSize < 1) {
    fprintf(stderr, "(empty)\n");
    fprintf(stderr, "\n");
    fflush(NULL);
    return;
  }
  // print contents for each slot
  for (i = 0; i < dsTableSize; i++) {
    dsSlot = dsTable[i];
    fprintf(stderr, "%3d: %s\n", i, (dsSlot) ? "exists" : "NULL");
    if (dsSlot == NULL)
      continue;
    _fc_printSlotHeader(dsSlot->header);
    fprintf(stderr, "     fileType = %s\n",
            fc_getFileIOTypeText(dsSlot->fileType));
    fprintf(stderr, "     baseFile = %s\n", (dsSlot->baseFile) ?
            dsSlot->baseFile : "NULL");
    fprintf(stderr, "     writable = %d\n", dsSlot->writable);
    fprintf(stderr, "     numSeq = %d, seqIDs = ", dsSlot->numSeq);
    if (dsSlot->numSeq == 0)
      fprintf(stderr, "NULL\n");
    else {
      fprintf(stderr, "{ %d", dsSlot->seqIDs[0]);
      for (j = 1; j < dsSlot->numSeq; j++)
        fprintf(stderr, ", %d", dsSlot->seqIDs[j]);
      fprintf(stderr, " }\n");
    }
    fprintf(stderr, "     numMesh = %d, meshIDs = ", dsSlot->numMesh);
    if (dsSlot->numMesh == 0)
      fprintf(stderr, "NULL\n");
    else {
      fprintf(stderr, " { %d", dsSlot->meshIDs[0]);
      for (j = 1; j < dsSlot->numMesh; j++)
        fprintf(stderr, ", %d", dsSlot->meshIDs[j]);
      fprintf(stderr, " }\n");
    }
    fprintf(stderr, "     numBasicVar = %d, basicVarIDs = ",
         dsSlot->numBasicVar);
    if (dsSlot->numBasicVar == 0)
      fprintf(stderr, "NULL\n");
    else {
      fprintf(stderr, "{ %d", dsSlot->basicVarIDs[0]);
      for (j = 1; j < dsSlot->numBasicVar; j++)
        fprintf(stderr, ", %d", dsSlot->basicVarIDs[j]);
      fprintf(stderr, " }\n");
    }
    fprintf(stderr, "     numSeqVar = %d, numStepPerSeqVar = ", dsSlot->numSeqVar);
    if (!dsSlot->numStepPerSeqVar)
      fprintf(stderr, "NULL\n");
    else {
      fprintf(stderr, "{ %d", dsSlot->numStepPerSeqVar[0]);
      for (j = 1; j < dsSlot->numSeqVar; j++)
        fprintf(stderr, ", %d", dsSlot->numStepPerSeqVar[j]);
      fprintf(stderr, " }\n");
    }
    fprintf(stderr, "     seqVarIDs = ");
    if (!dsSlot->seqVarIDs)
      fprintf(stderr, "NULL\n");
    else {
      fprintf(stderr, "{\n");
      for (j = 0; j < dsSlot->numSeqVar; j++) {
     fprintf(stderr, "         seqVarIDs[%d] = { %d", j,
                  dsSlot->seqVarIDs[j][0]);
     for (k = 1; k < dsSlot->numStepPerSeqVar[j]; k++)
       fprintf(stderr, ", %d", dsSlot->seqVarIDs[j][k]);
     fprintf(stderr, " }\n");
      }
      fprintf(stderr, "     }\n");
    }
    fflush(NULL);
  }
  fprintf(stderr, "\n");
  fflush(NULL);
  return;
}
Variable Documentation
FC_SortedIntArray dsOpenSlots = { 0, 0, 0 } [static]
The list of unused slots in the dataset table.
Definition at line 98 of file dataset.c.
_FC_DsSlot** dsTable = NULL [static]
The datasest table.
Definition at line 93 of file dataset.c.
int dsTableSize = 0 [static]
The number of allocated slots in the dataset table.
Definition at line 88 of file dataset.c.
Referenced by _fc_deleteDsSlot(), _fc_freeDsTable(), _fc_getDsSlot(), _fc_getDsSlotFromID(), _fc_getDsTableSize(), _fc_getNewDsSlot(), _fc_printDsTable(), and fc_isDatasetValid().