FCLib: Features
Features
[FCLib API]
Detailed Description
Basic feature data structures and routines for manipulating them.
Description:
** WARNING ** This interface will definitely change some day **
The feature module provides the basic feature data structures as well as routines for manipulating them.
ROI - region of interest in a single time step (two pieces of data--the step ID and an FC_Subset--are used to represent this)
Features - an ordered collecting of ROIs from successive time steps that are considered to be the same structure, also knows its parents and children features.
Feature Group - container for related features. It stores ROIs and creates and stores features.
Usage will usually be through the Feature Group interface so that it can properly manage ROIs and features. Generally, you add ROIs from successive time step to the Group and it will create the features. Features that have an ROI for the latest time step are considered to be "open" (i.e. still exists), and conversely, features that do not have an ROI for the latest time step are considered to have terminated.
These routines purposefully do not check that the ROI's are valid FC_Subsets. This was done to make testing easier, but also makes the feature and feature group data structures more flexible.
Todo:
: fundamental question, store ROIs as array of arrays indexed by step and then local ROI index, or as a single array with a helper array indexed by step & local ROI index?
It is nice to have the 2 indices in the feature because can tell it's sequence extent directly from the stepIDs. But it might also be nice to have global ROI IDs. Could do both? can easily keep a total ROI count too
Modifications:
FEB-18-2003 W Koegler Created
07/02/04 WSK Removed FC_Roi type and replaced use with FC_Subset.
Modules
(Private)
Helpers (not available outside this module)
Data Structures
struct FC_FeatureGroup
Feature Group object.
Feature group creation and desctruction.
FC_ReturnCode fc_createFeatureGroup (FC_FeatureGroup **group)
Create a new Feature Group.
void fc_freeFeatureGroup (FC_FeatureGroup *group)
Free memory associated with a feature group.
Feature group feature manipulation.
FC_ReturnCode fc_featureGroup_newFeature (FC_FeatureGroup *group, int timeID, FC_Subset roi, int *featureID)
Creates a new feature in the feature group.
FC_ReturnCode fc_featureGroup_setParentChildPair (FC_FeatureGroup *group, int parentID, int childID)
Create a Parent/Child Relationship in the feature Group.
FC_ReturnCode fc_featureGroup_continueFeature (FC_FeatureGroup *group, int featureID, int timeID, FC_Subset roi)
Continues a feature.
FC_ReturnCode fc_featureGroup_noFeaturesThisStep (FC_FeatureGroup *group, int stepID)
Declare that a step in the feature group has no features.
Feature group group query.
FC_ReturnCode fc_featureGroup_getNumStep (FC_FeatureGroup *group, int *numStep_p)
Get the number of steps in the Feature Group.
FC_ReturnCode fc_featureGroup_getNumFeature (FC_FeatureGroup *group, int *numFeature_p)
Get the number of Features in the Feature Group.
Query step of a feature group.
FC_ReturnCode fc_featureGroup_getNumFeatureInStep (FC_FeatureGroup *group, int stepID, int *numFeature_p)
Get the number Features in a step of the Feature Group.
FC_ReturnCode fc_featureGroup_getFeatureIDsInStep (FC_FeatureGroup *group, int stepID, int *numFeature_p, int **featureIDs_p)
Get the IDs of the features in a step.
FC_ReturnCode fc_featureGroup_getNumROI (FC_FeatureGroup *group, int *numROI_p)
Get the number of ROIs in the Feature Group.
FC_ReturnCode fc_featureGroup_getROIsInStep (FC_FeatureGroup *group, int stepID, int *numRoi_p, FC_Subset **rois_p)
Get the ROIs in a step from the Feature Group.
Query features.
FC_ReturnCode fc_getFeatureNumROI (FC_FeatureGroup *group, int featureID, int *numROI_p)
Get the number of ROIs in a feature.
FC_ReturnCode fc_getFeatureROIs (FC_FeatureGroup *group, int featureID, int *numRoi_p, int **stepIDs_p, FC_Subset **rois_p)
Get the ROIs in a feature.
FC_ReturnCode fc_getFeatureROIAtStep (FC_FeatureGroup *group, int featureID, int stepID, FC_Subset *roi_p)
Get the ROI for the specified step.
FC_ReturnCode fc_getFeatureNumParent (FC_FeatureGroup *group, int featureID, int *numParent_p)
Get the number of parents of a feature.
FC_ReturnCode fc_getFeatureParentIDs (FC_FeatureGroup *group, int featureID, int *numParent_p, int **parentIDs_p)
Get the parents of a feature.
FC_ReturnCode fc_getFeatureNumChild (FC_FeatureGroup *group, int featureID, int *numChild_p)
Get the number of children of a feature.
FC_ReturnCode fc_getFeatureChildIDs (FC_FeatureGroup *group, int featureID, int *numChild_p, int **childIDs_p)
Get the children of a feature.
Printing.
FC_ReturnCode fc_printFeatureGroup (FC_FeatureGroup *group)
Print the contents of a feature group.
FC_ReturnCode fc_writeFeatureGroup (FC_FeatureGroup *group, char *filename)
Writes the contents of a feature group to file.
FC_ReturnCode fc_printFeatureGraph (FC_FeatureGroup *group)
Print a feature graph.
FC_ReturnCode fc_writeFeatureGraph (FC_FeatureGroup *group, char *filename)
Print a feature graph.
Function Documentation
FC_ReturnCode fc_createFeatureGroup (FC_FeatureGroup ** group)
Create a new Feature Group.
Modifications:
MAR-17-2003 W Koegler Created
11/11/04 WSK Changed so that allocates room for itself.
Parameters:
group output - the new feature group
Definition at line 126 of file feature.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by main().
  {
  // default return
  if (group)
    *group = NULL;
  // check input
  if (!group) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Creating new feature group.");
  // create
  *group = malloc(sizeof(FC_FeatureGroup));
  if (*group == NULL) {
   fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  // assign values
  (*group)->numStep = 0;
  (*group)->numROIperStep = NULL;
  (*group)->roiFeatureIDs = NULL;
  (*group)->rois = NULL;
  (*group)->numFeature = 0;
  (*group)->features = NULL;
  return FC_SUCCESS;
}
FC_ReturnCode fc_featureGroup_continueFeature (FC_FeatureGroup * group, int featureID, int timeID, FC_Subset roi)
Continues a feature.
Description:
Given a feature, this routine 'continues' the feature by adding the given ROI.
Modifications:
MAR-25-2003 W Koegler Created
fc_isSubsetValid(roi) ||
Parameters:
group input - pointer to feature group
featureID input - ID of the feature to be continued
timeID input - time ID for the ROI
roi input - ROI to add to feature
Definition at line 344 of file feature.c.
References _fc_feature_addROI(), _fc_featureGroup_addROI(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_FeatureGroup::features, and FC_FeatureGroup::numFeature.
Referenced by fc_addROIsUsingBasicEvents().
  {
  FC_ReturnCode rc;
  int roiID;
  // check input
  if (!group || timeID < 0 || /*!fc_isSubsetValid(roi) || */
      featureID >= group->numFeature)  {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Continuing a feature by copying in a ROI.");
  // add new ROI to group
  rc = _fc_featureGroup_addROI(group, featureID, timeID, roi, &roiID);
  if (rc != FC_SUCCESS)
    return rc;
  // Add ROI to feature
  rc = _fc_feature_addROI(group->features[featureID], timeID, roiID);
  return rc;
}
FC_ReturnCode fc_featureGroup_getFeatureIDsInStep (FC_FeatureGroup * group, int stepID, int * numFeature_p, int ** featureIDs_p)
Get the IDs of the features in a step.
Description:
Returns the number of features and an array of their IDs which exist in the specified step of the feature group. This array needs to be freed by the calling routine.
Modifications:
MAR-17-2003 W Koegler Created
Parameters:
group input - pointer to feature group
stepID input - the step id
numFeature_p output - the number of features in the step
featureIDs_p output - array of feature IDs
Definition at line 558 of file feature.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_FeatureGroup::numROIperStep, FC_FeatureGroup::numStep, and FC_FeatureGroup::roiFeatureIDs.
Referenced by fc_addROIsUsingBasicEvents().
  {
  // default output
  if (numFeature_p)
    *numFeature_p = -1;
  if (featureIDs_p)
    *featureIDs_p = NULL;
  // check input
  if (!group || stepID < 0 || stepID >= group->numStep || !numFeature_p ||
      !featureIDs_p) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting IDs of the existing feature.");
  // get numStep and make array for ids
  *numFeature_p = group->numROIperStep[stepID];
  if (*numFeature_p <= 0)
    *featureIDs_p = NULL;
  else {
    *featureIDs_p = malloc(sizeof(_FC_Feature*) * (*numFeature_p));
    if (*featureIDs_p == NULL ) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    memcpy(*featureIDs_p, group->roiFeatureIDs[stepID],
           sizeof(int)*(*numFeature_p));
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_featureGroup_getNumFeature (FC_FeatureGroup * group, int * numFeature_p)
Get the number of Features in the Feature Group.
Modifications:
MAR-17-2003 W Koegler Created
Parameters:
group input - pointer to feature group
numFeature_p output - the number of features in group
Definition at line 478 of file feature.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, and FC_FeatureGroup::numFeature.
Referenced by _fc_writeFeatureGraph(), fc_writeFeatureGraph(), and main().
  {
  // default output
  if (numFeature_p)
    *numFeature_p = -1;
  // check input
  if (!group || !numFeature_p) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting number of features in a feature group.");
  // return number of features
  *numFeature_p = group->numFeature;
  return FC_SUCCESS;
}
FC_ReturnCode fc_featureGroup_getNumFeatureInStep (FC_FeatureGroup * group, int stepID, int * numFeature_p)
Get the number Features in a step of the Feature Group.
Description:
Returns the number of features that exist at a specified step in the feature group. Note: this is the same as the number of ROIs at the same step.
Modifications:
APR-07-2003 W Koegler Created
Parameters:
group input - pointer to feature group
stepID input - the step id
numFeature_p output - the number of features in the step
Definition at line 520 of file feature.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_FeatureGroup::numROIperStep, and FC_FeatureGroup::numStep.
  {
  // default output
  if (numFeature_p)
    *numFeature_p = -1;
  // check input
  if (!group || stepID < 0 || stepID >= group->numStep || !numFeature_p) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting number of features in step %d of the feature "
                      " group.", stepID);
  // return number of features
  *numFeature_p = group->numROIperStep[stepID];
  return FC_SUCCESS;
}
FC_ReturnCode fc_featureGroup_getNumROI (FC_FeatureGroup * group, int * numROI_p)
Get the number of ROIs in the Feature Group.
Modifications:
11/12/04 WSK Created.
Parameters:
group input - pointer to feature group
numROI_p output - number of ROIs per step
Definition at line 604 of file feature.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_FeatureGroup::numROIperStep, and FC_FeatureGroup::numStep.
  {
  int i;
  // default output
  if (numROI_p)
    *numROI_p = -1;
  // check input
  if (!group || !numROI_p) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting number of ROIs in a feature group.");
  // sum up number of ROI's per step
  *numROI_p = 0;
  for (i = 0; i < group->numStep; i++)
    *numROI_p += group->numROIperStep[i];
  return FC_SUCCESS;
}
FC_ReturnCode fc_featureGroup_getNumStep (FC_FeatureGroup * group, int * numStep_p)
Get the number of steps in the Feature Group.
Modifications:
MAR-31-2003 W Koegler Created
Parameters:
group input - pointer to feature group
numStep_p output - the number of steps in this group
Definition at line 449 of file feature.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, and FC_FeatureGroup::numStep.
  {
  // default output
  if (numStep_p)
    *numStep_p = -1;
  // check input
  if (!group || !numStep_p) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting number of steps in a feature group.");
  // return number of features
  *numStep_p = group->numStep;
  return FC_SUCCESS;
}
FC_ReturnCode fc_featureGroup_getROIsInStep (FC_FeatureGroup * group, int stepID, int * numRoi_p, FC_Subset ** rois_p)
Get the ROIs in a step from the Feature Group.
Description:
Returns an array of subset handles that are the ROIs for the indicated step. Freeing the array is the responsibility of the caller.
Modifications:
MAR-31-2003 W Koegler Created
11/11/04 WSK changed to just get a single steps ROIs
Parameters:
group input - the feature group
stepID input - the step ID
numRoi_p output - the number of ROIs
rois_p output - arrays of ROIs
Definition at line 644 of file feature.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_FeatureGroup::numROIperStep, FC_FeatureGroup::numStep, and FC_FeatureGroup::rois.
Referenced by fc_trackStep_custom().
  {
  int i;
  // default output
  if (numRoi_p)
    *numRoi_p = -1;
  if (rois_p)
    *rois_p = NULL;
  // check input
  if (!group || stepID < 0 || stepID >= group->numStep || !numRoi_p ||
      !rois_p) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting ROIs in step #%d a feature group.", stepID);
  // return rois
  *numRoi_p = group->numROIperStep[stepID];
  if (*numRoi_p > 0) {
    *rois_p = (FC_Subset*)malloc(sizeof(FC_Subset)*(*numRoi_p));
    if (*rois_p == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    for (i = 0; i < group->numROIperStep[stepID]; i++)
      (*rois_p)[i] = group->rois[stepID][i];
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_featureGroup_newFeature (FC_FeatureGroup * group, int timeID, FC_Subset roi, int * featureID)
Creates a new feature in the feature group.
Description:
Creates a new feature whose first ROI is the stepID and the given subset. If this new feature is a child of a previous feature, use fc_featureGroup_setParentChildPair() to set that relationship.
Modifications:
MAR-17-2003 W Koegler Created
fc_isSubsetValid(roi) ||
Parameters:
group input - pointer to feature group
timeID input - time ID for the ROI
roi input - the first ROI in feature
featureID output - the new feature's ID
Definition at line 243 of file feature.c.
References _fc_createFeature(), _fc_feature_addROI(), _fc_featureGroup_addFeature(), _fc_featureGroup_addROI(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, and _FC_Feature::id.
Referenced by fc_addROIsUsingBasicEvents().
  {
  FC_ReturnCode rc;
  _FC_Feature* new_feature;
  int roiID;
  // default output
  if (featureID)
    *featureID = -1;
  // check input
  if (!group || timeID < 0 || /*!fc_isSubsetValid(roi) ||*/ !featureID) {
    if (featureID)
      *featureID = -1;
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Creating new feature in a feature group.");
  // get a new feature
  rc = _fc_createFeature(1, &new_feature);
  if (rc != FC_SUCCESS)
    return rc;
  // add feature to group
  rc = _fc_featureGroup_addFeature(group, new_feature);
  if (rc != FC_SUCCESS)
    return rc;
  // get feature id
  *featureID = new_feature->id;
  // add ROI to the group & feature
  rc = _fc_featureGroup_addROI(group, *featureID, timeID, roi, &roiID);
  if (rc != FC_SUCCESS)
    return rc;
  rc = _fc_feature_addROI(new_feature, timeID, roiID);
  if (rc != FC_SUCCESS)
    return rc;
  return rc;
}
FC_ReturnCode fc_featureGroup_noFeaturesThisStep (FC_FeatureGroup * group, int stepID)
Declare that a step in the feature group has no features.
Description:
This routine is used to add a step to a feature group if there are no features in that step (steps are automatically added if there if you use fc_featureGroup_newFeature() or fc_featureGroup_continueFeature()).
It is an error to call this routine on a step that already exists in the feature group.
Modifications:
MAR-17-2003 W Koegler Created
Parameters:
group input - pointer to feature group
stepID input - step
Definition at line 391 of file feature.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_FeatureGroup::numROIperStep, FC_FeatureGroup::numStep, FC_FeatureGroup::roiFeatureIDs, and FC_FeatureGroup::rois.
Referenced by fc_addROIsUsingBasicEvents().
  {
  int i;
  int new_numStep, *temp_nums, **temp_featureIDs;
  FC_Subset** temp_rois;
  // check input
  if (!group || stepID < 0 || stepID < group->numStep) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Adding featureless step to a feature group.");
  // grow the arrays to accommodate this new step (fill intervening steps
  // with zeros).
  new_numStep = stepID + 1;
  temp_nums = (int*)realloc(group->numROIperStep, new_numStep*sizeof(int));
  temp_rois = (FC_Subset**)realloc(group->rois,
                                   new_numStep*sizeof(FC_Subset*));
  temp_featureIDs = (int**)realloc(group->roiFeatureIDs,
                                   new_numStep*sizeof(int*));
  if (!temp_nums || !temp_rois || !temp_featureIDs) {
    free(temp_nums);
    free(temp_rois);
    free(temp_featureIDs);
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  group->numROIperStep = temp_nums;
  group->rois = temp_rois;
  group->roiFeatureIDs = temp_featureIDs;
  for (i = group->numStep; i < new_numStep; i++) {
    temp_nums[i] = 0;
    temp_rois[i] = NULL;
    temp_featureIDs[i] = NULL;
  }
  group->numStep = new_numStep;
  return FC_SUCCESS;
}
FC_ReturnCode fc_featureGroup_setParentChildPair (FC_FeatureGroup * group, int parentID, int childID)
Create a Parent/Child Relationship in the feature Group.
Description:
Creates a parent/child relationship in the feature Group. A pointer to the parent is added to the child feature; and a pointer to the child is added to the parent feature. Both features must already be in the feature group.
Modifications:
MAR-25-2003 W Koegler Created
Parameters:
group input - pointer to feature group
parentID input - the feature's ID
childID input - the id of the child to be added
Definition at line 306 of file feature.c.
References _fc_feature_addChild(), _fc_feature_addParent(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_FeatureGroup::features, and FC_FeatureGroup::numFeature.
Referenced by fc_addROIsUsingBasicEvents().
  {
  FC_ReturnCode rc;
  // check input - equal IDs not allowed (circular references!)
  if (!group || parentID == childID || childID < 0 || parentID < 0 ||
      parentID >= group->numFeature || childID >= group->numFeature) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Creating parent/child relationship in feature group.");
  // add child
  rc = _fc_feature_addChild(group->features[parentID], childID);
  if (rc != FC_SUCCESS)
    return rc;
  rc = _fc_feature_addParent(group->features[childID], parentID);
  return rc;
}
void fc_freeFeatureGroup (FC_FeatureGroup * group)
Free memory associated with a feature group.
Description:
This routine should only be called on a feature group created using fc_createFeatureGroup. This frees the dynamically allocated memory inside the group as well as all features own by the group (but doesn't delete the ROI's).
Modifications:
MAR-17-2003 W Koegler Created
11/11/04 WSK Changed so that it frees itself as well as it's dynamically allocated data.
Parameters:
group input - pointer to feature group
Definition at line 177 of file feature.c.
References _fc_freeFeature(), fc_printfLogMessage, FC_FeatureGroup::features, FC_FeatureGroup::numFeature, FC_FeatureGroup::numROIperStep, FC_FeatureGroup::numStep, FC_FeatureGroup::roiFeatureIDs, and FC_FeatureGroup::rois.
Referenced by main().
  {
  int i;
  // early return
  if (group == NULL)
    return;
  // log message
  fc_printfLogMessage("Closing feature group.");
  // free 2d array of roi handles
  if (group->numStep > 0 && group->numROIperStep && group->rois) {
    for (i = 0; i < group->numStep; i++) {
      if (group->rois[i])
        free(group->rois[i]);
    }
    free(group->rois);
  }
  // free 2d allocated roiFeatureIDs
  if (group->numStep > 0 && group->roiFeatureIDs) {
    for (i = 0; i < group->numStep; i++)
      if (group->roiFeatureIDs[i])
        free(group->roiFeatureIDs[i]);
    free(group->roiFeatureIDs);
  }
  // free allocated features & their array
  if (group->numFeature > 0 && group->features) {
    for (i = 0; i < group->numFeature; i++) {
      if (group->features[i]) {
        _fc_freeFeature(group->features[i]);
      }
    }
    free(group->features);
  }
  // free other arrays
  if (group->numROIperStep)
    free(group->numROIperStep);
  // free itself
  free(group);
}
FC_ReturnCode fc_getFeatureChildIDs (FC_FeatureGroup * group, int featureID, int * numChild_p, int ** childIDs_p)
Get the children of a feature.
Description:
Returns IDs (in the same feature group) of the children of the feature. Freeing the arrays is the responsibility of the caller.
Modifications:
11/11/04 WSK, created.
Parameters:
group input - the feature group
featureID input - the feature ID
numChild_p output - the number of children
childIDs_p output - the child IDs
Definition at line 986 of file feature.c.
References _FC_Feature::childIDs, fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_FeatureGroup::features, _FC_Feature::numChild, and FC_FeatureGroup::numFeature.
Referenced by _fc_writeFeatureGroup(), and main().
  {
  int i;
  // default output
  if (numChild_p)
    *numChild_p = -1;
  if (childIDs_p)
    *childIDs_p = NULL;
  // check input
  if (!group || featureID < 0 || featureID >= group->numFeature ||
      !numChild_p || !childIDs_p) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting children of feature #%d a feature group.",
                      featureID);
  // return rois
  *numChild_p = group->features[featureID]->numChild;
  if (*numChild_p > 0) {
    *childIDs_p = (int*)malloc(sizeof(int)*(*numChild_p));
    if (*childIDs_p == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    for (i = 0; i < *numChild_p; i++)
      (*childIDs_p)[i] = group->features[featureID]->childIDs[i];
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_getFeatureNumChild (FC_FeatureGroup * group, int featureID, int * numChild_p)
Get the number of children of a feature.
Modifications:
11/11/04 WSK, created.
Parameters:
group input - the feature group
featureID input - the feature ID
numChild_p output - the number of children
Definition at line 948 of file feature.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_FeatureGroup::features, _FC_Feature::numChild, and FC_FeatureGroup::numFeature.
  {
  // default output
  if (numChild_p)
    *numChild_p = -1;
  // check input
  if (!group || featureID < 0 || featureID >= group->numFeature ||
      !numChild_p) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting numChild in feature #%d a feature group.",
                      featureID);
  // return rois
  *numChild_p = group->features[featureID]->numChild;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getFeatureNumParent (FC_FeatureGroup * group, int featureID, int * numParent_p)
Get the number of parents of a feature.
Modifications:
11/11/04 WSK, created.
Parameters:
group input - the feature group
featureID input - the feature ID
numParent_p output - the number of parents
Definition at line 863 of file feature.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_FeatureGroup::features, FC_FeatureGroup::numFeature, and _FC_Feature::numParent.
  {
  // default output
  if (numParent_p)
    *numParent_p = -1;
  // check input
  if (!group || featureID < 0 || featureID >= group->numFeature ||
      !numParent_p) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting numParent in feature #%d a feature group.",
                      featureID);
  // return rois
  *numParent_p = group->features[featureID]->numParent;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getFeatureNumROI (FC_FeatureGroup * group, int featureID, int * numROI_p)
Get the number of ROIs in a feature.
Description:
The number of ROI in a feature is equivalent to the number of steps over which the feature exists.
Modifications:
11/11/04 WSK, created.
Parameters:
group input - the feature group
featureID input - the feature ID
numROI_p output - the number of steps
Definition at line 701 of file feature.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_FeatureGroup::features, FC_FeatureGroup::numFeature, and _FC_Feature::numROI.
  {
  // default output
  if (numROI_p)
    *numROI_p = -1;
  // check input
  if (!group || featureID < 0 || featureID >= group->numFeature ||
      !numROI_p) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting numStep in feature #%d a feature group.",
                      featureID);
  // return rois
  *numROI_p = group->features[featureID]->numROI;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getFeatureParentIDs (FC_FeatureGroup * group, int featureID, int * numParent_p, int ** parentIDs_p)
Get the parents of a feature.
Description:
Returns IDs (in the same feature group) of the parents of the feature. Freeing the arrays is the responsibility of the caller.
Modifications:
11/11/04 WSK, created.
Parameters:
group input - the feature group
featureID input - the feature ID
numParent_p output - the number of parents
parentIDs_p output - the parent IDs
Definition at line 901 of file feature.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_FeatureGroup::features, FC_FeatureGroup::numFeature, _FC_Feature::numParent, and _FC_Feature::parentIDs.
Referenced by _fc_writeFeatureGroup(), and main().
  {
  int i;
  // default output
  if (numParent_p)
    *numParent_p = -1;
  if (parentIDs_p)
    *parentIDs_p = NULL;
  // check input
  if (!group || featureID < 0 || featureID >= group->numFeature ||
      !numParent_p || !parentIDs_p) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting parents of feature #%d a feature group.",
                      featureID);
  // return rois
  *numParent_p = group->features[featureID]->numParent;
  if (*numParent_p > 0) {
    *parentIDs_p = (int*)malloc(sizeof(int)*(*numParent_p));
    if (*parentIDs_p == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    for (i = 0; i < *numParent_p; i++)
      (*parentIDs_p)[i] = group->features[featureID]->parentIDs[i];
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_getFeatureROIAtStep (FC_FeatureGroup * group, int featureID, int stepID, FC_Subset * roi_p)
Get the ROI for the specified step.
Description:
Returns the ROI that exists in the feature for the specified step. If no ROI exists at the requested step, function returns an error.
Modifications:
11/122/04 WSK, created.
Parameters:
group input - the feature group
featureID input - the feature ID
stepID input - the step ID
roi_p output - ROI
Definition at line 811 of file feature.c.
References FC_ERROR, fc_getFeatureROIs(), fc_getReturnCodeText(), FC_INPUT_ERROR, FC_NULL_SUBSET, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_FeatureGroup::numFeature, and FC_FeatureGroup::numStep.
  {
  FC_ReturnCode rc;
  int i;
  int numROI, *stepIDs;
  FC_Subset* rois;
  // default output
  if (roi_p)
    *roi_p = FC_NULL_SUBSET;
  // check input
  if (!group || featureID < 0 || featureID >= group->numFeature ||
      stepID < 0 || stepID >= group->numStep || !roi_p) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting ROI at stepID %d in feature #%d",
                      stepID, featureID);
  // return roi
  rc = fc_getFeatureROIs(group, featureID, &numROI, &stepIDs, &rois);
  if (rc != FC_SUCCESS)
    return rc;
  for (i = 0; i < numROI; i++) {
    if (stepIDs[i] == stepID) {
      *roi_p = rois[i];
      break;
    }
  }
  free(stepIDs);
  free(rois);
  if (i == numROI)
    return FC_ERROR;
  else
    return FC_SUCCESS;
}
FC_ReturnCode fc_getFeatureROIs (FC_FeatureGroup * group, int featureID, int * numRoi_p, int ** stepIDs_p, FC_Subset ** rois_p)
Get the ROIs in a feature.
Description:
Returns an array of stepIDs and an array of subset handles that are the ROIs for the indicated feature. Freeing the arrays is the responsibility of the caller. Pass NULL for either array if you don't want it returned.
Modifications:
11/11/04 WSK, created.
Parameters:
group input - the feature group
featureID input - the feature ID
numRoi_p output - the number of ROIs
stepIDs_p output - (optional) array of step IDs
rois_p output - (optional) arrays of ROIs
Definition at line 741 of file feature.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_FeatureGroup::features, FC_FeatureGroup::numFeature, _FC_Feature::numROI, _FC_Feature::roiIDs, FC_FeatureGroup::rois, and _FC_Feature::stepIDs.
Referenced by _fc_writeFeatureGroup(), fc_getFeatureROIAtStep(), and main().
  {
  int i;
  int stepID, roiID;
  // default output
  if (numRoi_p)
    *numRoi_p = -1;
  if (stepIDs_p)
    *stepIDs_p = NULL;
  if (rois_p)
    *rois_p = NULL;
  // check input
  if (!group || featureID < 0 || featureID >= group->numFeature ||
      !numRoi_p || (!stepIDs_p && !rois_p)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting ROIs in feature #%d a feature group.",
                      featureID);
  // return rois
  *numRoi_p = group->features[featureID]->numROI;
  if (*numRoi_p > 0) {
    if (stepIDs_p) {
      *stepIDs_p = (int*)malloc(sizeof(int)*(*numRoi_p));
      if (*stepIDs_p == NULL) {
        fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
        return FC_MEMORY_ERROR;
      }
      for (i = 0; i < *numRoi_p; i++)
        (*stepIDs_p)[i] = group->features[featureID]->stepIDs[i];
    }
    if (rois_p) {
      *rois_p = (FC_Subset*)malloc(sizeof(FC_Subset)*(*numRoi_p));
      if (*rois_p == NULL) {
        fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
        return FC_MEMORY_ERROR;
      }
      for (i = 0; i < *numRoi_p; i++) {
        stepID = group->features[featureID]->stepIDs[i];
        roiID = group->features[featureID]->roiIDs[i];
        (*rois_p)[i] = group->rois[stepID][roiID];
      }
    }
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_printFeatureGraph (FC_FeatureGroup * group)
Print a feature graph.
Description:
Prints code that the program 'dot' in ATT&T's graphviz package can convert to a pretty picture of the graph of the features.
Modifications:
APR-09-2003 W Koegler Created
Parameters:
group input - pointer to the feature group
Definition at line 1117 of file feature.c.
References _fc_writeFeatureGraph(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, and fc_printfLogMessage.
  {
  // check input
  if (!group) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Printing a feature graph.");
  // do it
  return _fc_writeFeatureGraph(group, stdout);
}
FC_ReturnCode fc_printFeatureGroup (FC_FeatureGroup * group)
Print the contents of a feature group.
Description:
Prints human readable information about the features in a featureGroup.
Modifications:
APR-01-2003 W Koegler Created
Parameters:
group input - pointer to the feature group
Definition at line 1044 of file feature.c.
References _fc_writeFeatureGroup(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, and fc_printfLogMessage.
Referenced by main().
  {
  // check input
  if (!group) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Printing features.");
  // do it
  return _fc_writeFeatureGroup(group, stdout);
}
FC_ReturnCode fc_writeFeatureGraph (FC_FeatureGroup * group, char * filename)
Print a feature graph.
Description:
Prints code that the program 'dot' in ATT&T's graphviz package can convert to a pretty picture of the graph of the features.
Modifications:
APR-09-2003 W Koegler Created
Parameters:
group input - pointer to the feature group
filename input - filename
Definition at line 1145 of file feature.c.
References _fc_writeFeatureGraph(), fc_featureGroup_getNumFeature(), FC_FILE_IO_ERROR, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, and fc_printfLogMessage.
Referenced by main().
  {
  FC_ReturnCode rc;
  FILE *file;
  int numFeature;
  // check input
  if (!group || !filename) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  fc_featureGroup_getNumFeature(group, &numFeature);
  if (numFeature < 1) {
    fc_printfErrorMessage("Cannot write graph of empty feature group");
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Writing a feature graph.");
  // open file
  file = fopen(filename, "w");
  if (file == NULL)
    return FC_FILE_IO_ERROR;
  // do it
  rc = _fc_writeFeatureGraph(group, file);
  // close file
  fclose(file);
  return rc;
}
FC_ReturnCode fc_writeFeatureGroup (FC_FeatureGroup * group, char * filename)
Writes the contents of a feature group to file.
Description:
Prints human readable information about the features in a featureGroup into a file.
Todo:
Add a flag fore more info - like the association type and number of members in each subset.
Modifications:
APR-01-2003 W Koegler Created
Parameters:
group input - pointer to the feature group
filename input - filename
Definition at line 1075 of file feature.c.
References _fc_writeFeatureGroup(), FC_FILE_IO_ERROR, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, and fc_printfLogMessage.
  {
  FC_ReturnCode rc;
  FILE* file;
  // check input
  if (!group || !filename) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Writing contents of a feature group to a file.");
  // get the file pointer
  file = fopen(filename, "w");
  if (!file)
    return FC_FILE_IO_ERROR;
  // do it
  rc = _fc_writeFeatureGroup(group, file);
  // close file
  fclose(file);
  return rc;
}