FCLib: File Path Processing
File Path Processing
[Utilities]
Detailed Description
Various routines for decomposing file paths.
Functions
char * fc_getDirname (char *path)
Get the dirname in a path string.
char * fc_getBasename (char *path)
Get the basename in a path string.
char * fc_getBasenameWOExtension (char *path, int ext_flag)
Get the root of a basename in a path string.
char * fc_getExtension (char *path, int ext_flag)
Get the extension of path.
Function Documentation
char* fc_getBasename (char * path)
Get the basename in a path string.
Description:
Returns the part of the path after the last slash (ignoring trailing slashes). For example "/usr/local/bin" -> "bin" or "../../cherry.txt" -> "cherry.txt" or "grumpy.xslt" -> "grumpy.xslt".
User is responsible for freeing the returned string.
If no path is provided, this routine returns NULL.
Modifications:
7/14/2005 WSD Created.
Definition at line 781 of file util.c.
Referenced by fc_getBasenameWOExtension(), fc_getExtension(), and fc_loadDatasetWithFormat().
{
  char* temp_path;
  char* temp_str;
  char* base;
  // early return
  if (path == NULL)
    return NULL;
  // Use C library function to get base
  temp_path = (char*)malloc((strlen(path)+1)*sizeof(char));
  strcpy(temp_path, path);
  base = basename(temp_path);
  // copy, cleanup & return
  temp_str = (char*)malloc((strlen(base)+1)*sizeof(char));
  strcpy(temp_str, base);
  free(temp_path);
  return temp_str;
}
char* fc_getBasenameWOExtension (char * path, int ext_flag)
Get the root of a basename in a path string.
Description:
Returns the part of the path after the last slash (ignoring trailing slashes) minus any extension. For example "/usr/local/bin" -> "bin" or "../../cherry.txt" -> "cherry" or "grumpy.xslt" -> "grumpy".
The user can specify whether the extension starts with the first "." (0) or the last "." (1). For example, "bundle.tar.gz" would be "bundle" or "bundle.tar". A leading "." is not treated as an extension ".". For example. ".cshrc" -> ".cshrc";
User is responsible for freeing the returned string.
If no path is provided, this routine returns NULL.
Modifications:
7/14/2005 WSD Created.
Parameters:
path the path
ext_flag 0 = extension starts at 1st ".", 1 = extentsion starts at last "."
Definition at line 824 of file util.c.
References fc_getBasename().
Referenced by _fc_readNamesFile(), checkArgs(), and main().
  {
  size_t i;
  char* temp_str;
  // early return
  if (path == NULL)
    return NULL;
  // get base
  temp_str = fc_getBasename(path);
  // clip off extentions
  if (ext_flag == 0) {
    for (i = 1; i < strlen(temp_str); i++) {
      if (temp_str[i] == '.') {
     temp_str[i] = '\0';
     break;
      }
    }
  }
  else {
    for (i = strlen(temp_str); i > 0; i--) {
      if (temp_str[i] == '.') {
     temp_str[i] = '\0';
     break;
      }
    }
  }
  return temp_str;
}
char* fc_getDirname (char * path)
Get the dirname in a path string.
Description:
Returns the part of the path before the last slash (ignoring trailing slashes). For example "/usr/local/bin" -> "/usr/local" or "../../cherry.txt" -> "../.." or "grumpy.xslt" -> ".".
User is responsible for freeing the returned string.
If no path is provided, this routine returns NULL.
Modifications:
7/14/2005 WSD Created.
Definition at line 743 of file util.c.
Referenced by _fc_readNamesFile().
{
  char* temp_path;
  char* temp_str;
  char* dir;
  // early return
  if (path == NULL)
    return NULL;
  // Use C library function to get dir
  temp_path = (char*)malloc((strlen(path)+1)*sizeof(char));
  strcpy(temp_path, path);
  dir = dirname(temp_path);
  // copy, cleanup & return
  temp_str = (char*)malloc((strlen(dir)+1)*sizeof(char));
  strcpy(temp_str, dir);
  free(temp_path);
  return temp_str;
}
char* fc_getExtension (char * path, int ext_flag)
Get the extension of path.
Description:
Returns the extension of a file if it exists. For example "/usr/local/bin" -> NULL or "../../cherry.txt" -> "txt" or "grumpy.xslt" -> "xslt".
The user can specify whether the extension starts with the first "." (0) or the last "." (1). For example, "bundle.tar.gz" would be "tar.gz" or ".gz". A leading "." is not treated as an extension ".". For example. ".cshrc" -> "";
NOTE: If there is no extension, a string is still returned, it just happens to be empty (and you still have to free it).
User is responsible for freeing the returned string.
Modifications:
7/14/2005 WSD Created.
Parameters:
path input - the path
ext_flag input - 0 = extension starts at 1st ".", 1 = extentsion starts at last "."
Definition at line 883 of file util.c.
References fc_getBasename().
Referenced by checkArgs(), and fc_loadDatasetWithFormat().
  {
  size_t i;
  char* temp_str;
  char* ext;
  int start = -1;
  // early return
  if (path == NULL)
    return NULL;
  // get base
  temp_str = fc_getBasename(path);
  // find start of extension (".")
  if (ext_flag == 0) {
    for (i = 1; i < strlen(temp_str); i++) {
      if (temp_str[i] == '.') {
     start = i;
     break;
      }
    }
  }
  else {
    for (i = strlen(temp_str); i > 0; i--) {
      if (temp_str[i] == '.') {
     start = i;
     break;
      }
    }
  }
  // make the extension
  if (start < 0) {
    ext = (char*)malloc(sizeof(char));
    ext[0] = '\0';
  }
  else {
    ext = (char*)malloc((strlen(temp_str)-start)*sizeof(char));
    strcpy(ext, &temp_str[start+1]);
  }
  free(temp_str);
  return ext;
}