FCLib: Element Death
Element Death
[FCLib API]
Detailed Description
Dead element analysis routines and helper functions.
Description:
In many simulations, changing mesh topology is approximated by allowing elements to "die". The mesh topology stays the same, but any elements that are labeld "dead" no longer participate in the simulation. Dead elements can be used to model rips, tears and other changes in the mesh.
The input of most of the routines in this module is a subset representing a dead element region, and is assumed to have the association type of FC_AT_ELEMENT. It is also assumed that the coordinates of vertices within an dead element region cannot be trusted (the vertices on the boundary of the dead element region may be o.k. if they are still on live elements).
A dead element region does not have to be a single topological segment, but most of the results are more easily interpreted if this is true.
Modules
(Private)
Decay of Subsets
FC_ReturnCode fc_getExposedSkin (FC_Subset subset, FC_Subset *opt_meshSkin, FC_Subset *exposed)
Get exposed skin.
FC_ReturnCode fc_getDecayedSkin (FC_Subset deadregion, FC_Subset *opt_meshSkin, FC_Subset *decayedSkin)
Get decayed skin.
FC_ReturnCode fc_getSubsetDecayType (FC_Subset deadSubset, FC_Subset compSubset, int *sidedecayflag)
Get identifier telling if deadSubset intersects, or entirely erodes a subset.
Decay of Shapes
FC_ReturnCode fc_getDecayedShapeSkin (FC_Subset deadregion, FC_Shape *shape, FC_Subset *decayedSkin)
Get the decayed Skin.
FC_ReturnCode fc_getDecayedShapeSides (FC_Subset deadregion, FC_Shape *shape, FC_Subset **decayedSides)
Get the decayed item of each of a shapes sides.
FC_ReturnCode fc_getShapeSidesDecayType (FC_Subset deadSubset, FC_Shape *shape, int **sidedecayflag)
Get identifier telling if deadSubset intersects or entirely erodes the sides of a shape.
Dead region segmenting mesh
FC_ReturnCode fc_subsetSegmentsMesh (FC_Subset subset, int shared_segdim, char *varname, int *numSubset, FC_Subset **newSubsets)
returns the segments (and their number) that result from segmenting the mesh by the input subset.
FC_ReturnCode fc_subsetSegmentsSubset (FC_Subset subset_inner, FC_Subset subset_outer, int shared_segdim, char *varname, int *numSubset, FC_Subset **newSubsets)
returns the segments (and their number) that result from segmenting a subset by another subset.
FC_ReturnCode fc_subsetPlusNeighborGreaterSegmentationMesh (FC_Subset subset, int shared_neighbordim, int shared_segdim, int *numNbr, int **nbrIDs)
given an input subset and parameters for specifying neghbors, returns IDs of neighbors for which adding any single one individually to the subset will result in a greater segmentation of the mesh than results from segmenting based on the orginal subset
Characterizations of Dead Element Regions
FC_ReturnCode fc_calcTearLength (FC_Subset subset, FC_Subset *opt_meshSkin, FC_Variable *displ_coords, double *length)
Get tear length.
Function Documentation
FC_ReturnCode fc_calcTearLength (FC_Subset subset, FC_Subset * opt_meshSkin, FC_Variable * displ_coords, double * length)
Get tear length.
Description:
This function is just for convenience - it calls fc_getExposedSkin() and then fc_getSubsetDiameter() (or fc_getDisplacedSubsetDiameter() if the displacement variable is provided).
Todo:
Unit test this.
Modifications:
7/6/2005 WSD. Created.
Parameters:
subset input - A subset of "dead" elements
opt_meshSkin input - (optional) pointer to mesh skin (or NULL)
displ_coords input - (optional) pointer to the owning mesh's coordinate displacements (or NULL)
length ouput - diameter of the vertex set
Definition at line 1196 of file elemdeath.c.
References fc_deleteSubset(), fc_getDisplacedSubsetDiameter(), fc_getExposedSkin(), fc_getSubsetDiameter(), and FC_SUCCESS.
  {
  FC_ReturnCode rc;
  FC_Subset exposed;
  rc = fc_getExposedSkin(subset, opt_meshSkin, &exposed);
  if (rc != FC_SUCCESS) {
    *length = -1;
    return rc;
  }
  if (displ_coords)
    rc = fc_getDisplacedSubsetDiameter(exposed, *displ_coords, length, NULL,
                           NULL);
  else
    rc = fc_getSubsetDiameter(exposed, length, NULL, NULL);
  fc_deleteSubset(exposed);
  return rc;
}
FC_ReturnCode fc_getDecayedShapeSides (FC_Subset deadregion, FC_Shape * shape, FC_Subset ** decayedSides)
Get the decayed item of each of a shapes sides.
Description:
Given a dead element region and a shape, returns an array of subsets, which is the intersection of the dead and the faces of each side. This is basically fc_getDecayedSkin called for each side in turn, so see the text there.
If you want to get thsi information for a single side, call fc_getDecayedSkin and send it the single side face subset.
If the inner calls fail for any of the sides, the whole thing fails.
Modifications:
03/02/2006 ACG fc_getDecayedSidesSegments created
07/16/2006 ACG This is born from fc_getDecayedSkinSegments, but without the segmenting.
Parameters:
deadregion input - dead region elements
shape input - shape
decayedSides output - decayedSkin subsets, one for each face
Definition at line 583 of file elemdeath.c.
References FC_Shape::faces, fc_deleteSubset(), fc_getDecayedSkin(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSubsetValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, FC_SUCCESS, and FC_Shape::numSides.
Referenced by fc_getDecayedShapeSkin().
   {
  FC_ReturnCode rc;
  FC_Subset *sidesdecay;
  int i,j;
  // default returns
  if (decayedSides!= NULL)
    *decayedSides = NULL;
  // Test input.
  if (!fc_isSubsetValid(deadregion) || !shape || !shape->numSides ||
      !decayedSides){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  sidesdecay = (FC_Subset*)malloc((shape->numSides) * sizeof(FC_Subset));
  if (!sidesdecay){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < shape->numSides; i++){
    rc = fc_getDecayedSkin(deadregion,&(shape->faces[i]),&sidesdecay[i]);
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("cant get decayedSkin of face %d",i);
      for (j = 0; j < i; j++){
     fc_deleteSubset(sidesdecay[j]);
      }
      free(sidesdecay);
      return rc;
    }
  }
  *decayedSides = sidesdecay;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getDecayedShapeSkin (FC_Subset deadregion, FC_Shape * shape, FC_Subset * decayedSkin)
Get the decayed Skin.
Description:
Analogous method to fc_getDecayedSkin but where the meshskin is that defined by a shape. If you want the decay information on a side-by-side basis, use fc_getDecayedShapeSides.
Modifications:
07/16/2006 ACG created
Parameters:
deadregion input - dead region elements
shape input - ptr to shape
decayedSkin output - decayedSkin
Definition at line 499 of file elemdeath.c.
References fc_addArrayMembersToSubset(), fc_deleteSubset(), fc_getDecayedShapeSides(), fc_getReturnCodeText(), fc_getSubsetMembersAsArray(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, fc_isSubsetValid(), FC_NULL_SUBSET, fc_printfErrorMessage, FC_SUCCESS, and FC_Shape::numSides.
Referenced by calcShapeIntersection().
   {
  FC_ReturnCode rc;
  FC_Subset *sidesdecay;
  int i,j;
  // default returns
  if (decayedSkin)
    *decayedSkin = FC_NULL_SUBSET;
  // Test input.
  if (!fc_isSubsetValid(deadregion) || !shape || !shape->numSides ||
      !decayedSkin){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  rc = fc_getDecayedShapeSides(deadregion,shape,&sidesdecay);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("cant get decayed shape skin");
    return rc;
  }
  for (i = 1; i < shape->numSides; i++){
    int num, *arr;
    if (!FC_HANDLE_EQUIV(sidesdecay[i],FC_NULL_SUBSET)){
      rc = fc_getSubsetMembersAsArray(sidesdecay[i],&num,&arr);
      if (rc != FC_SUCCESS){
     fc_printfErrorMessage("cant get subset members as array");
     fc_deleteSubset(sidesdecay[0]);
     for (j = i; j < shape->numSides; j++){
       fc_deleteSubset(sidesdecay[j]);
     }
     free(sidesdecay);
     return rc;
      }
      rc = fc_addArrayMembersToSubset(sidesdecay[0],num,arr);
      free(arr);
      if (rc != FC_SUCCESS){
     fc_printfErrorMessage("cant add aray members to subset");
     fc_deleteSubset(sidesdecay[0]);
     for (j = i; j < shape->numSides; j++){
       fc_deleteSubset(sidesdecay[j]);
     }
     free(sidesdecay);
     return rc;
      }
    }
  }
  *decayedSkin = sidesdecay[0];
  free(sidesdecay);
  return FC_SUCCESS;
}
FC_ReturnCode fc_getDecayedSkin (FC_Subset deadregion, FC_Subset * opt_meshSkin, FC_Subset * decayedSkin)
Get decayed skin.
Description:
Given a dead element region and the skin of a mesh or subset, returns a subset which is the intersection of the dead element region and the skin, referred to as the "decayedSkin". The return subset is named "DecayedSkin".
The dead region must have association FC_AT_ELEMENT, the skin must have association FC_AT_FACE, and the return subset has the assocation FC_AT_FACE. Both input subsets must be on the same mesh. If you want the elements of the decayed face, call fc_createSubsetIntersection directly on the dead region and subset giving rise to the input skin.
This method does not check that the initial subsets actually describe a dead region and a skin, so this can in fact be used to calculate the intersection of any element subset and some other skin. It is being placed in elemdeath however, because this function was developed for a specific dead element need and and using the deadelement terminology in this function name is beneficial.
Notes:
if the deadregion is NULL or the input skin is empty, returns with error (this is to be consistent with fc_getExposedSkin)
if the input skin is NULL, it creates the mesh skin
if the dead region is empty, returns empty subset.
if there are no intersections, returns a subset with no members.
Modifications:
11/30/2005 ACG Created via moving here from surface demo code.
12/05/2005 ACG Added the unittest (see todo above).
03/01/2006 ACG added explicit type checking for hte input subsets
03/02/2006 ACG changing name for DecayedMeshSkin to DecayedSkin since the skin doesnt have to be a meshskin
07/16/2006 ACG This was fc_getDecayedSkinSegments, but removing the segmenting
Parameters:
deadregion input - dead region elements
opt_meshSkin input - optional ptr to mesh skin or NULL
decayedSkin output - skin items ids comprising the dead skin (not segmented)
Definition at line 262 of file elemdeath.c.
References FC_AT_ELEMENT, FC_AT_FACE, fc_createSubsetIntersection(), fc_deleteSubset(), fc_getMeshFromSubset(), fc_getMeshSkin(), fc_getReturnCodeText(), fc_getSubsetInfo(), fc_getSubsetSkin(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, fc_isSubsetValid(), FC_NULL_SUBSET, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by fc_getDecayedShapeSides(), main(), and projection().
   {
  FC_ReturnCode rc;
  FC_Mesh mesh1, mesh2;
  FC_Subset deadregionskin,meshskin,createmeshskin,deadfaces;
  FC_AssociationType assocdead, assocskin;
  int n_dead, n_skin;
  int junk;
  // default returns
  if (decayedSkin)
    *decayedSkin = FC_NULL_SUBSET;
  // Test input.
  if (!fc_isSubsetValid(deadregion) || !decayedSkin ||
      (opt_meshSkin != NULL && !fc_isSubsetValid(*opt_meshSkin))){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  rc = fc_getSubsetInfo(deadregion,&n_dead,&junk,&assocdead);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("cant get info of dead region");
    return rc;
  }
  if (assocdead != FC_AT_ELEMENT){
    fc_printfErrorMessage("deadregion must have element assoc");
    return FC_INPUT_ERROR;
  }
  rc = fc_getMeshFromSubset(deadregion,&mesh1);
  if (rc != FC_SUCCESS)
    return rc;
  if (opt_meshSkin) {
    rc = fc_getMeshFromSubset(*opt_meshSkin, &mesh2);
    if (rc != FC_SUCCESS)
      return rc;
    if (!FC_HANDLE_EQUIV(mesh1, mesh2)) {
      fc_printfErrorMessage("deadregion and skin must be on the same mesh");
      return FC_INPUT_ERROR;
    }
  }
  createmeshskin = FC_NULL_SUBSET;
  if (opt_meshSkin){
    meshskin = *opt_meshSkin;
  } else {
    rc = fc_getMeshSkin(mesh1, &createmeshskin);
    if (rc != FC_SUCCESS)
      return rc;
    meshskin = createmeshskin;
  }
  rc = fc_getSubsetInfo(meshskin,&n_skin,&junk,&assocskin);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("cant get info of skin");
    fc_deleteSubset(createmeshskin);
    return rc;
  }
  if (assocskin != FC_AT_FACE){
    fc_printfErrorMessage("skin must have face assoc");
    fc_deleteSubset(createmeshskin);
    return FC_INPUT_ERROR;
  }
  //have to check if the skin is empty before checking if the dead set is
  if (n_skin == 0){
    fc_printfErrorMessage("cant work on an empty skin");
    fc_deleteSubset(createmeshskin);
    return FC_INPUT_ERROR;
  }
  if (n_dead == 0){
    return FC_SUCCESS;
  }
  fc_printfLogMessage("get decayed skin ");
  //get the skin of the dead region
  rc = fc_getSubsetSkin(deadregion,&deadregionskin);
  if (rc != FC_SUCCESS){
    fc_deleteSubset(createmeshskin);
    fc_printfErrorMessage("cant get dead region skin");
    return rc;
  }
  //intersect to get the dead faces
  rc = fc_createSubsetIntersection(deadregionskin,"AND",meshskin,
                       "DeadSkin",&deadfaces);
  fc_deleteSubset(deadregionskin);
  fc_deleteSubset(createmeshskin);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("cant get dead mesh faces");
    return rc;
  }
  *decayedSkin = deadfaces;
  return FC_SUCCESS;
};
FC_ReturnCode fc_getExposedSkin (FC_Subset subset, FC_Subset * opt_meshSkin, FC_Subset * exposed)
Get exposed skin.
Description:
Given a subset of elements, this routine returns a subset of the entities that would become "exposed" (i.e. become part of the mesh skin) if the given elements were removed from the parent mesh. The exposed skin is the boundary between the dead region and the rest of the mesh. It is useful as a subset of the dead region because all members are still "real" unlike entities that are totally within a dead region which may no longer have physical meaning.
Since calculating the skin of the parent mesh can be very computationally expension, there is an optional argument to pass in an already computed mesh skin.
If there are no exposed entities, this routine returns successfully but with FC_NULL_SUBSET (instead of a subset with no members).
This function will fail if there are no members in the input subset.
Modifications:
6/27/2005 WSD. Created.
Parameters:
subset input - A subset of "dead" elements
opt_meshSkin input - (optional) pointer to mesh skin (or NULL)
exposed output - The exposed skin
Definition at line 130 of file elemdeath.c.
References FC_AT_ELEMENT, FC_AT_WHOLE_MESH, fc_createSubsetIntersection(), fc_deleteSubset(), fc_getMeshFromSubset(), fc_getMeshSkin(), fc_getReturnCodeText(), fc_getSubsetInfo(), fc_getSubsetSkin(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, fc_isSubsetValid(), FC_NULL_SUBSET, fc_printfErrorMessage, and FC_SUCCESS.
Referenced by fc_calcTearLength(), and main().
  {
  FC_ReturnCode rc;
  FC_AssociationType in_assoc;
  int numMember, maxNumMember;
  FC_Mesh mesh, temp_mesh;
  FC_Subset mesh_skin, subset_skin, union_subset;
  // default returns
  if (exposed)
    *exposed = FC_NULL_SUBSET;
  // Test input
  if (!fc_isSubsetValid(subset) || !exposed ||
      (opt_meshSkin != NULL && !fc_isSubsetValid(*opt_meshSkin))) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  rc = fc_getSubsetInfo(subset, &numMember, &maxNumMember, &in_assoc);
  if (rc != FC_SUCCESS)
    return rc;
  if (in_assoc != FC_AT_ELEMENT && in_assoc != FC_AT_WHOLE_MESH) {
    fc_printfErrorMessage("Subset must have element or whole association");
    return FC_INPUT_ERROR;
  }
  // A little setup and more testing
  rc = fc_getMeshFromSubset(subset, &mesh);
  if (rc != FC_SUCCESS)
    return rc;
  if (opt_meshSkin) {
    rc = fc_getMeshFromSubset(*opt_meshSkin, &temp_mesh);
    if (rc != FC_SUCCESS)
      return rc;
    if (!FC_HANDLE_EQUIV(mesh, temp_mesh)) {
      fc_printfErrorMessage("Subset and mesh sking must be on the same mesh");
      return FC_INPUT_ERROR;
    }
  }
  // Error case - No dead elements // FIX? is this really an error?
  if (numMember == 0) {
    fc_printfErrorMessage("Cannot handle empty subset");
    return FC_INPUT_ERROR;
  }
  // Special case - all elements are dead
  if (in_assoc == FC_AT_WHOLE_MESH ||  numMember == maxNumMember) {
    // return NULL handle
    return FC_SUCCESS;
  }
  // Setup - get the skin's of the mesh and the subset
  if (opt_meshSkin)
    mesh_skin = *opt_meshSkin;
  else {
    rc = fc_getMeshSkin(mesh, &mesh_skin);
    if (rc != FC_SUCCESS)
      return rc;
  }
  rc = fc_getSubsetSkin(subset, &subset_skin);
  if (rc != FC_SUCCESS)
    return rc;
  // Exposed enties are subset_skin - any skin shared with orig mesh
  // Union of mesh & subset skins will give us overlap
  rc = fc_createSubsetIntersection(mesh_skin, "AND", subset_skin, "temp",
                       &union_subset);
  if (!opt_meshSkin)
    fc_deleteSubset(mesh_skin);
  if (rc != FC_SUCCESS) {
    fc_deleteSubset(subset_skin);
    return rc;
  }
  // Xor of overlap and subset skin should give skin NOT overlapping
  rc = fc_createSubsetIntersection(subset_skin, "XOR", union_subset,
                       "temp", exposed);
  fc_deleteSubset(subset_skin);
  fc_deleteSubset(union_subset);
  // done
  return rc;
}
FC_ReturnCode fc_getShapeSidesDecayType (FC_Subset deadSubset, FC_Shape * shape, int ** sidedecayflag)
Get identifier telling if deadSubset intersects or entirely erodes the sides of a shape.
Description:
Given a dead subset, returns an array of identifiers, one for each side of a shape, telling if the deadSubset intersects or entirely erodes the sides of a shape.
Identifier values:
0 if the deadSubset doesnt intersect the sides at all.
1 if the deadSubset intersects the side
2 if the deadSubset erodes the whole side.
-1 in case of error
The dead subset can have assoc FC_AT_FACE or FC_AT_ELEM. The dead subset and shape have to be on the same mesh. This function is essentially a wrapper around fc_getSubsetDecayType. If you want this functionally for only 1 side of the Shape, then call fc_getSubsetDecayType.
Right now, if any side fails, the whole thing fails, since you wouldnt have an empty or NULL side in a shape and therefore this is probably indicative of a more serious error in your shape.
While this is expected to be used for a dead region and a shape, there is nothing that checks that it is a dead region and so it can be used more generally. It is being placed in elemdeath however, because this function was developed for a specific dead element need and using the deadelement terminology in this function name is beneficial.
Todo:
do we want this to succeed if any one side is bad?
Modifications:
02/14/2006 ACG fc_getSidesDecay created, which replaced fc_getDecayedMeshSkinSideIntersections.
07/17/2006 ACG new version born of fc_getSidesDecay.
Parameters:
deadSubset input - deadSubset
shape input - ptr to shape
sidedecayflag output - decay flag array
Definition at line 669 of file elemdeath.c.
References FC_Shape::elems, FC_Shape::faces, FC_AT_ELEMENT, FC_AT_FACE, fc_getReturnCodeText(), fc_getSubsetAssociationType(), fc_getSubsetDecayType(), FC_INPUT_ERROR, fc_isSubsetValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, FC_SUCCESS, and FC_Shape::numSides.
Referenced by eroded(), and main().
    {
  FC_ReturnCode rc;
  FC_AssociationType assocdead;
  int *flags;
  int usefaces = 0;
  int i;
  //default returns
  if (sidedecayflag)
    *sidedecayflag = NULL;
  //other things chekced inside
  if (!fc_isSubsetValid(deadSubset) || !shape ||
      !sidedecayflag){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  flags = (int*)malloc(shape->numSides*sizeof(int));
  if (!flags){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  //check assoc, mesh is checked in internal calls.
  rc = fc_getSubsetAssociationType(deadSubset,&assocdead);
  if (assocdead != FC_AT_ELEMENT && assocdead!= FC_AT_FACE){
    fc_printfErrorMessage("deadSubset must have face or element assoc");
    return FC_INPUT_ERROR;
  }
  if (assocdead == FC_AT_FACE){
    usefaces = 1;
  } //otherwise use elems
  for (i = 0; i < shape->numSides; i++){
    FC_Subset tempSubset;
    if (usefaces){
      tempSubset = shape->faces[i];
    }else{
      tempSubset = shape->elems[i];
    }
    rc = fc_getSubsetDecayType(deadSubset,tempSubset,&flags[i]);
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("Can't get decay type for side %d",i);
      free(flags);
      return rc;
    }
  }
  *sidedecayflag = flags;
  return FC_SUCCESS;
};
FC_ReturnCode fc_getSubsetDecayType (FC_Subset deadSubset, FC_Subset compSubset, int * sidedecayflag)
Get identifier telling if deadSubset intersects, or entirely erodes a subset.
Description:
Given a dead subset, returns an identifier telling if the deadSubset intersects, or entirely erodes the comparisonSubset.
Identifier values:
0 if the deadSubset doesnt intersect the compSubset at all.
1 if the deadSubset intersects the compSubset.
2 if the deadSubset erodes the whole compSubset.
-1 in case of error
The deadSubset and the compSubset both have to have the same assocation. It must either be FC_AT_FACE or FC_AT_ELEMENT. They must also be on the same mesh. This function is currently a wrapper around fc_doSubsetsIntersect and fc_isSubsetSuperset and is subject to the constraints of those methods.
Fails if the compsubset is empty or null of if the deadsubset is null. The dead set can be empty and returns 0. (The inner calls would support permuations of empty and null, but the logic of the call does not).
In general, it is expect that this will be used to compare a dead region and the side of a mesh, but there is nothing that checks that so this can in fact be used more generally, and also misused at your peril. It is being placed in elemdeath however, because this function was developed for a specific dead element need and using the deadelement terminology in this function name is beneficial. If you want to do this comparison for all the sides of a shape, use fc_getShapeSidesDecayType.
Todo:
make more efficient by not having to call both the intersection and the superset code.
Modifications:
02/14/2006 ACG fc_getSidesDecay created, which replaced fc_getDecayedMeshSkinSideIntersections.
07/17/2006 ACG new version born of fc_getSidesDecay.
Parameters:
deadSubset input - deadSubset
compSubset input - comparison subset
sidedecayflag output - decay flag
Definition at line 410 of file elemdeath.c.
References FC_AT_ELEMENT, FC_AT_FACE, fc_doSubsetsIntersect(), fc_getReturnCodeText(), fc_getSubsetAssociationType(), fc_getSubsetNumMember(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, fc_isSubsetSuperset(), fc_isSubsetValid(), FC_NULL_SUBSET, fc_printfErrorMessage, and FC_SUCCESS.
Referenced by fc_getShapeSidesDecayType().
    {
  FC_ReturnCode rc;
  FC_AssociationType assocdead, assoccomp;
  int ret = -1;
  int i;
  //default returns
  if (sidedecayflag)
    *sidedecayflag = -1;
  if (!fc_isSubsetValid(deadSubset) || !fc_isSubsetValid(compSubset) ||
      !sidedecayflag){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  if (FC_HANDLE_EQUIV(compSubset,FC_NULL_SUBSET)){
    fc_printfErrorMessage("comp subset cannot be NULL");
    return FC_INPUT_ERROR;
  }
  rc = fc_getSubsetNumMember(compSubset,&i);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("cant get num members of comp subset");
    return rc;
  }
  if (!i){
    fc_printfErrorMessage("comp subset cannot be empty");
    return FC_INPUT_ERROR;
  }
  //check assoc, mesh is checked in internal calls.
  rc = fc_getSubsetAssociationType(deadSubset,&assocdead);
  if (assocdead != FC_AT_ELEMENT && assocdead!= FC_AT_FACE){
    fc_printfErrorMessage("deadSubset must have face or element assoc");
    return FC_INPUT_ERROR;
  }
  rc = fc_getSubsetAssociationType(compSubset,&assoccomp);
  if (assoccomp != assocdead){
    fc_printfErrorMessage("compSubset must have smae assoc as deadSubset");
    return FC_INPUT_ERROR;
  }
  rc = fc_doSubsetsIntersect(deadSubset,compSubset,&ret);
  if (rc != FC_SUCCESS){
    return rc;
  }
  if (ret == 1){
    int ind2;
    rc = fc_isSubsetSuperset(deadSubset,compSubset,&ind2);
    if (rc != FC_SUCCESS){
      return rc;
    }
    ret = (ind2 == 1 ? 2:1);
  }
  *sidedecayflag  = ret;
  return FC_SUCCESS;
};
FC_ReturnCode fc_subsetPlusNeighborGreaterSegmentationMesh (FC_Subset subset, int shared_neighbordim, int shared_segdim, int * numNbr, int ** nbrIDs)
given an input subset and parameters for specifying neghbors, returns IDs of neighbors for which adding any single one individually to the subset will result in a greater segmentation of the mesh than results from segmenting based on the orginal subset
Description:
given an input subset and parameters for specifying neghbors, returns IDs of neighbors for which adding any single one individually to the subset will result in a greater segmentation of the mesh than results from segmenting based on the orginal subset.
Returns -1 in case of error. Passing in an empty subset returns -1.
Notes:
No sense passing in anything more than level 1 since we are considering no element combos at this point.
This uses recursive innards that test on big sets of elem first and only narrow it down to smaller set if the big sets segment first. i.e., It is assumed that if a whole group doesnt result in any different segmenting, that the items of the group taken individually wont rest in different segmenting. There is the possibility that there could be offsetting effects that occur within the bigger set that will cuase this to be a faulty assumption, particularly when the dead region is near the boundary of the mesh. However, if this is used primarily for cases where we are looking for the mesh to be just about to break, then we expect that the num of elements that will satisfy the condition is small and so this should be ok.
Todo:
prob need a version that doesnt make the assumption that the recusion implies - esp for dead regions near boundary of mesh.
should this return IDS if it segments into fewer (ie subsumes the mesh, or causes to segments to combine ?). Note may cause problems with considering things as groups as effects might counter each other.
may want a version that does combos of elem. the recursive innards, would not support that.
should we return num of resulting segments ?
should we make a time version or no ?
note: will need to upate if change return vals of recurive innard
do we want to explicity test the shareddim earlier in the call, and the unittest ratehr than them just being caught in the innards ?
Modifications:
8/24/2005 ACG. Created.
8/31/2005 ACG recusive version
9/20/2005 ACG changed so uses new recursive innards taht retrun segmenting nodes instead of non-segmenting nodes so dont have to invert the list at the end.
9/20/2005 ACG name change to reflect that will only be dealing with greater segmentation
9/22/2005 ACG added segmentation dim
10/9/05 ACG limited it to neighbor depth level 1
Parameters:
subset input - subset testing on
shared_neighbordim input - minimum dimensionality of shared part of neighbors
shared_segdim input - shared dim for segmentation
numNbr output - number of neigbors that will individually cause greater segmentation
nbrIDs output - IDS of neighbors that will individually cause greater segmentation
Definition at line 1072 of file elemdeath.c.
References _fc_recursive_IndividuallySegmentingNodes(), FC_AT_ELEMENT, FC_AT_WHOLE_MESH, fc_getReturnCodeText(), fc_getSubsetInfo(), fc_getSubsetNeighbors(), FC_INPUT_ERROR, fc_isSubsetValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, fc_subsetSegmentsMesh(), and FC_SUCCESS.
   {
  FC_ReturnCode rc;
  FC_AssociationType in_assoc;
  int numMember, maxNumMember;
  int numSubset, natNbr, *natNbrIDs, nmaxnsegids, *maxnsegids;
  int i;
  int level = 1;
  // default returns
  if (numNbr)
    *numNbr = -1;
  if (nbrIDs)
    *nbrIDs = NULL;
  // Test input (segment will check shared_segdim)
  if (!fc_isSubsetValid(subset) ||  level < 1 || shared_neighbordim < 0 ||
      shared_neighbordim > 2 || !numNbr || !nbrIDs) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  rc = fc_getSubsetInfo(subset, &numMember, &maxNumMember, &in_assoc);
  if (rc != FC_SUCCESS)
    return rc;
  if (in_assoc != FC_AT_ELEMENT && in_assoc != FC_AT_WHOLE_MESH) {
    fc_printfErrorMessage("Subset must have element or whole association");
    return FC_INPUT_ERROR;
  }
  if (numMember == 0) {
    fc_printfErrorMessage("Cannot handle empty subset");
    return FC_INPUT_ERROR;
  }
  fc_printfLogMessage("subsetPlusNeighborsSegmentsMesh");
  //first determine the orignal segmentation
  rc = fc_subsetSegmentsMesh(subset,shared_segdim,NULL,&numSubset,NULL);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("cant get original segmentation");
    return rc;
  }
  //now get the neighbors
  rc = fc_getSubsetNeighbors(subset,level,shared_neighbordim,
                     &in_assoc,
                     &natNbr,&natNbrIDs);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("cant get neighbors");
    return rc;
  }
  if (natNbr == 0){ //no neighbors - treat this as valid
    *numNbr = 0;
    return FC_SUCCESS;
  }
  rc = _fc_recursive_IndividuallySegmentingNodes(subset,numSubset,shared_segdim,
                        natNbr,natNbrIDs,
                        &nmaxnsegids, &maxnsegids);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("cant get recursive segmenting nodes");
    if (natNbrIDs) free(natNbrIDs);
    return rc;
  }
  //clean up neighbor arrays
  if (natNbrIDs) free(natNbrIDs);
  //return vals from recursive call are all the vals we want to return
  //dont have to check them anymore
  //now set real return values
  *numNbr = nmaxnsegids;
  if (nmaxnsegids > 0){
    *nbrIDs = (int*)malloc(nmaxnsegids*sizeof(int));
    if (*nbrIDs == NULL){ //no lcean up in case of memory error
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    for (i = 0; i < nmaxnsegids;i++){
      (*nbrIDs)[i] = maxnsegids[i];
    }
  }
  if (maxnsegids) free(maxnsegids);
  return FC_SUCCESS;
}
FC_ReturnCode fc_subsetSegmentsMesh (FC_Subset subset, int shared_segdim, char * varname, int * numSubset, FC_Subset ** newSubsets)
returns the segments (and their number) that result from segmenting the mesh by the input subset.
Description:
Returns the segments (and their number) that result from segmenting the mesh by the input subset. If you dont want the segment array, then newSubsets and varname are optional parameters. If you do want the segments, they will be named as the varname parameter pospended with "_Seg#" where # will be the index into the array of returned subsets.
Returns -1 in case of error. If you pass in an empty subset -- this is not an error, unlike fc_exposedSkin.
One can pass in subsets that have nothing to do with dead cells as well, of course, but we anticipate that this will be most often used with a dead region. If the number of returned segments > the original number of segments then the subset has broken the mesh. If the number of returned segments = 0 then the subset has consumed the mesh, and therefore may also be considered to have broken the mesh.
This is the mesh equivalent of fc_subsetSegmentsSubset
Todo:
test this for things other than elem
Modifications:
8/2/2005 ACG. Created.
8/5/05 ACG. reincarnation of fc_subsetBreaksMesh
8/11/05 ACG made empty subset an ok case because the user prob wants to compare the number of segments to the orignal number to see if there are more. an empty subset is a valid case, esp if one is doing this over time.
9/22/05 ACG added shared segmentation dim
Parameters:
subset input - subset testing on
shared_segdim input - shared dim for segmentation
varname input - prefix for returned segments (optional)
numSubset output - number of resulting segments
newSubsets output - array of resulting segments (optional)
Definition at line 778 of file elemdeath.c.
References fc_createSubsetComplement(), fc_deleteSubset(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isSubsetValid(), fc_printfErrorMessage, fc_printfLogMessage, fc_segment(), and FC_SUCCESS.
Referenced by _fc_recursive_IndividuallySegmentingNodes(), and fc_subsetPlusNeighborGreaterSegmentationMesh().
 {
  FC_ReturnCode rc;
  FC_Subset tempSubset,*tempsubarray;
  //  FC_AssociationType in_assoc;
  //  int numMember, maxNumMember;
  int i;
  char* tempname;
  // default returns
  if (numSubset)
    *numSubset = -1;
  if (newSubsets)
    *newSubsets = NULL;
  // Test input. (shared_segdim checked in fc_segment)
  if (!fc_isSubsetValid(subset) || !numSubset ||
      (!newSubsets && varname) || (newSubsets && !varname))
       //couldnt get xor (^) to work
    {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // no - dont limit this to elems
  //NOTE: next two test sections copied from getExposedSkin above
  //  rc = fc_getSubsetInfo(subset, &numMember, &maxNumMember, &in_assoc);
  //  if (rc != FC_SUCCESS)
  //    return rc;
  //
  //  if (in_assoc != FC_AT_ELEMENT && in_assoc != FC_AT_WHOLE_MESH) {
  //    fc_printfErrorMessage("Subset must have element or whole association");
  //    return FC_INPUT_ERROR;
  //  }
  fc_printfLogMessage("subsetSegmentsMesh");
  tempname = varname ? varname : "temp_subset";
  //this works for empty subset
  rc = fc_createSubsetComplement(subset,tempname, &tempSubset);
  if (rc != FC_SUCCESS){
    return rc;
  }
  if (newSubsets){ //even though this is more code, onyl 1 if check
    //to determine the arg and do the delete, vs doing a temp
    //pts variable like i did for the name above and then
    //having to check again for the delete
    rc = fc_segment(tempSubset,shared_segdim, numSubset,newSubsets);
    if (rc != FC_SUCCESS){
      fc_deleteSubset(tempSubset);
      return rc;
    }
  } else {
    rc = fc_segment(tempSubset,shared_segdim, numSubset,&tempsubarray);
    if (rc != FC_SUCCESS){
      fc_deleteSubset(tempSubset);
      return rc;
    }
    for (i = 0; i < *numSubset; i++){
      fc_deleteSubset(tempsubarray[i]);
    }
    free(tempsubarray);
  }
  //clean up
  fc_deleteSubset(tempSubset);
  return FC_SUCCESS;
}
FC_ReturnCode fc_subsetSegmentsSubset (FC_Subset subset_inner, FC_Subset subset_outer, int shared_segdim, char * varname, int * numSubset, FC_Subset ** newSubsets)
returns the segments (and their number) that result from segmenting a subset by another subset.
Description:
Returns the segments (and their number) that result from segmenting a subset by another subset. If you dont want the segment array, then newSubsets and varname are optional parameters. If you do want the segments, they will be named as the varname parameter postpended with "_Seg#" where # will be the index into the array of returned subsets. Note: this is not the additional number of segments that result, but the total - that is,
Returns -1 in case of error. If the outer subset is empty or MULL this returns with an error. If the inner subset is empty or NULL this is not an error, unlike fc_exposedSkin. Both subsets must have the same association and be on the same mesh. See fc_segment for restrictions on the segmentation dimension.
One can pass in subsets that have nothing to do with dead cells as well, of course, but we anticipate that this will be most often used with a dead region. If the number of returned segments > the original number of segments then the inner subset has broken the outer. If the number of returned segments = 0 then the inner subset has consumed the outer, and therefore may also be considered to have broken the outer.
This is the subset equivalent of fc_subsetSegmentsMesh
Todo:
test this for things other than elem
Modifications:
2/23/06 ACG created
Parameters:
subset_inner input - subset that cuases the segmentation
subset_outer input - subset being segmented
shared_segdim input - shared dim for segmentation
varname input - prefix for returned segments (optional)
numSubset output - number of resulting segments
newSubsets output - array of resulting segments (optional)
Definition at line 898 of file elemdeath.c.
References fc_copySubset(), fc_deleteArrayMembersFromSubset(), fc_deleteSubset(), fc_getMeshFromSubset(), fc_getReturnCodeText(), fc_getSubsetInfo(), fc_getSubsetMembersAsArray(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, fc_isSubsetValid(), FC_NULL_SUBSET, fc_printfErrorMessage, fc_segment(), and FC_SUCCESS.
Referenced by broken(), and calcShapeIntersection().
 {
  FC_ReturnCode rc1, rc2;
  FC_Subset tempSubset,*tempsubarray;
  FC_Mesh mesh_inner, mesh_outer;
  FC_AssociationType assoc_inner, assoc_outer;
  int numMember_inner, numMember_outer;
  int maxNumMember_inner, maxNumMember_outer;
  int i;
  char* tempname;
  // default returns
  if (numSubset)
    *numSubset = -1;
  if (newSubsets)
    *newSubsets = NULL;
  // Test input. (shared_segdim checked in fc_segment)
  if (!fc_isSubsetValid(subset_inner) ||!fc_isSubsetValid(subset_outer) ||
      !numSubset || (!newSubsets && varname) ||(newSubsets && !varname)){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  rc1 = fc_getMeshFromSubset(subset_inner,&mesh_inner);
  rc2 = fc_getMeshFromSubset(subset_outer,&mesh_outer);
  if (rc1 != FC_SUCCESS)
    return rc1;
  else if (rc2 != FC_SUCCESS)
    return rc2;
  if (!FC_HANDLE_EQUIV(mesh_outer, mesh_inner)){
    fc_printfErrorMessage("Subsets must be on same mesh");
    return FC_INPUT_ERROR;
  }
  rc1 = fc_getSubsetInfo(subset_inner, &numMember_inner, &maxNumMember_inner, &assoc_inner);
  rc2 = fc_getSubsetInfo(subset_outer, &numMember_outer, &maxNumMember_outer, &assoc_outer);
  if (rc1 != FC_SUCCESS)
    return rc1;
  else if (rc2 != FC_SUCCESS)
    return rc2;
  if (FC_HANDLE_EQUIV(subset_outer, FC_NULL_SUBSET) || numMember_outer == 0){
    fc_printfErrorMessage("Outer subset cannot be empty or NULL ");
    return FC_INPUT_ERROR;
  }
  //  if (assoc_inner != FC_AT_ELEMENT || assoc_outer != FC_AT_ELEMENT) {
  //    fc_printfErrorMessage("Subsets must have element assoc ");
  //    return FC_INPUT_ERROR;
  //  }
  if (assoc_inner !=  assoc_outer) {
    fc_printfErrorMessage("Subsets must have same assoc ");
    return FC_INPUT_ERROR;
  }
  tempname = varname ? varname : "temp_subset";
  rc1 = fc_copySubset(subset_outer,mesh_outer,tempname, &tempSubset);
  if (rc1 != FC_SUCCESS)
    return rc1;
  if (!FC_HANDLE_EQUIV(subset_inner,FC_NULL_SUBSET) && !numMember_inner == 0){
    int* array;
    rc1 = fc_getSubsetMembersAsArray(subset_inner, &numMember_inner, &array);
    if (rc1 != FC_SUCCESS)
      return rc1;
    rc1 = fc_deleteArrayMembersFromSubset(tempSubset, numMember_inner, array);
    if (rc1 != FC_SUCCESS)
      return rc1;
    free(array);
  }
  if (newSubsets){ //even though this is more code, onyl 1 if check
    //to determine the arg and do the delete, vs doing a temp
    //pts variable like i did for the name above and then
    //having to check again for the delete
    rc1 = fc_segment(tempSubset,shared_segdim, numSubset,newSubsets);
    if (rc1 != FC_SUCCESS){
      fc_deleteSubset(tempSubset);
      return rc1;
    }
  } else {
    rc1 = fc_segment(tempSubset,shared_segdim, numSubset,&tempsubarray);
    if (rc1 != FC_SUCCESS){
      fc_deleteSubset(tempSubset);
      return rc1;
    }
    for (i = 0; i < *numSubset; i++){
      fc_deleteSubset(tempsubarray[i]);
    }
    free(tempsubarray);
  }
  //clean up
  fc_deleteSubset(tempSubset);
  return FC_SUCCESS;
}