FCLib: Dataset
Dataset
[Data Interface]
Detailed Description
Operations on datasets.
Description:
(For an explanation of general data manipulations, see Data Interface.)
Modules
(Private)
Create new dataset from scratch.
FC_ReturnCode fc_createDataset (char *name, FC_Dataset *dataset)
Create a new dataset.
Other ways to get new datasets.
FC_ReturnCode fc_copyDataset (FC_Dataset src_ds, char *newName, FC_Dataset *new_ds)
Copy a dataset.
Get existing datasets.
FC_ReturnCode fc_getDatasets (int *numDataset, FC_Dataset **datasets)
Return a list of datasets in the library.
FC_ReturnCode fc_getNumDataset (int *numDataset)
Return number of datasets in the library.
FC_ReturnCode fc_getDatasetByName (char *datasetName, int *numDatasets, FC_Dataset **datasets)
Gets all datasets with a given name.
Change the name of a dataset.
FC_ReturnCode fc_changeDatasetName (FC_Dataset dataset, char *newName)
Change the name of a dataset.
Release/delete datasets.
FC_ReturnCode fc_releaseDataset (FC_Dataset dataset)
Attempt to minimize dataset's memory usage.
FC_ReturnCode fc_deleteDataset (FC_Dataset dataset)
Delete a dataset.
Get dataset metadata.
int fc_isDatasetValid (FC_Dataset dataset)
Check that the handle refers to a valid dataset.
FC_ReturnCode fc_getDatasetName (FC_Dataset dataset, char **dsName)
Return name of a dataset.
Print dataset.
FC_ReturnCode fc_printDataset (FC_Dataset dataset, char *label)
Print dataset meta data to stdout.
Function Documentation
FC_ReturnCode fc_changeDatasetName (FC_Dataset dataset, char * newName)
Change the name of a dataset.
Description:
This does not affect the name of the file the dataset is associated with.
Modifications:
8/24/2005 WSD. Created.
Parameters:
dataset Input - the dataset.
newName Input - new name for the dataset.
Definition at line 542 of file dataset.c.
References _fc_getDsSlot(), _fc_setSlotHeaderName(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, _FC_DsSlot::header, and _FC_SlotHeader::name.
Referenced by main().
  {
  _FC_DsSlot* dsSlot;
  // check input
  dsSlot = _fc_getDsSlot(dataset);
  if (dsSlot == NULL || newName == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Changing name of dataset from '%s' to '%s'",
                      dsSlot->header.name, newName);
  // Do it
  return _fc_setSlotHeaderName(&dsSlot->header, newName);
}
FC_ReturnCode fc_copyDataset (FC_Dataset src_ds, char * newName, FC_Dataset * new_ds)
Copy a dataset.
Description:
Create a copy of a dataset with the given name. This routine will copy all subentities (sequences & meshes).
Modifications:
2003-NOV-11 WSK Created
9/21/2006 WSD Added copying of global vars.
Parameters:
src_ds Input - the source dataset to be copied
newName Input - the name of the new dataset, a NULL value is a flag to use the name of the source dataset
new_ds Output - handle to the new dataset
Definition at line 172 of file dataset.c.
References _FC_GET_HANDLE, _fc_getDsSlot(), _fc_getMeshSlotFromID(), _fc_getSeqSlot(), _fc_getSeqSlotFromID(), _fc_getVarSlotFromID(), _FC_DsSlot::basicVarIDs, _FC_SeqSlot::coords, _FC_SeqSlot::datatype, fc_copyGlobalSeqVariable(), fc_copyGlobalVariable(), fc_copyMesh(), fc_copySequence(), fc_createDataset(), fc_deleteDataset(), FC_ERROR, fc_getReturnCodeText(), fc_getSequenceCoordsPtr(), fc_getSequenceInfo(), fc_getSequenceName(), fc_getSequences(), FC_INPUT_ERROR, FC_NULL_DATASET, fc_printfErrorMessage, fc_printfLogMessage, fc_sizeofDataType(), FC_SUCCESS, _FC_MeshSlot::header, _FC_VarSlot::header, _FC_SeqSlot::header, _FC_DsSlot::header, _FC_DsSlot::meshIDs, _FC_SlotHeader::name, _FC_DsSlot::numBasicVar, _FC_DsSlot::numMesh, _FC_DsSlot::numSeq, _FC_DsSlot::numSeqVar, _FC_SeqSlot::numStep, _FC_DsSlot::numStepPerSeqVar, _FC_DsSlot::seqIDs, _FC_VarSlot::sequence, and _FC_DsSlot::seqVarIDs.
  {
  int i, j;
  FC_ReturnCode rc;
  _FC_DsSlot* src_dsSlot;
  // default return
  if (new_ds)
    *new_ds = FC_NULL_DATASET;
  // check input
  src_dsSlot = _fc_getDsSlot(src_ds);
  if (src_dsSlot == NULL || new_ds == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // test for NULL name
  if (newName == NULL)
    newName = src_dsSlot->header.name;
  // log message
  fc_printfLogMessage("Copying dataset '%s' to '%s'", src_dsSlot->header.name,
                      newName);
  // create new dataset with new name
  rc = fc_createDataset(newName, new_ds);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to create new dataset '%s'",
                          newName);
    return FC_ERROR;
  }
  // copy the sequences
  for (i = 0; i < src_dsSlot->numSeq; i++) {
    FC_Sequence src_seq, new_seq;
    _FC_SeqSlot* src_seqSlot = _fc_getSeqSlotFromID(src_dsSlot->seqIDs[i]);
    _FC_GET_HANDLE(src_seq, src_seqSlot);
    rc = fc_copySequence(src_seq, *new_ds, NULL, &new_seq);
    if (rc != FC_SUCCESS) {
      fc_deleteDataset(*new_ds);
      *new_ds = FC_NULL_DATASET;
      fc_printfErrorMessage("Failed to copy sequence '%s'",
                            src_seqSlot->header.name);
      return rc;
    }
  }
  // copy the global vars
  for (i = 0; i < src_dsSlot->numBasicVar; i++) {
    FC_Variable src_var, new_var;
    _FC_VarSlot* src_varSlot = _fc_getVarSlotFromID(src_dsSlot->basicVarIDs[i]);
    _FC_GET_HANDLE(src_var, src_varSlot);
    rc = fc_copyGlobalVariable(src_var, *new_ds, NULL, &new_var);
    if (rc != FC_SUCCESS) {
      fc_deleteDataset(*new_ds);
      *new_ds = FC_NULL_DATASET;
      fc_printfErrorMessage("Failed to copy global var '%s'",
                   src_varSlot->header.name);
      return rc;
    }
  }
  // copy the global seq vars
  // (similar to code in fc_copyMesh())
  for (i = 0; i < src_dsSlot->numSeqVar; i++) {
    int numStep = src_dsSlot->numStepPerSeqVar[i];
    FC_Variable src_seqVar[numStep], *new_seqVar;
    int temp_numSeq;
    FC_Sequence dest_seq, *temp_seqs;
    _FC_VarSlot* src_varSlot = _fc_getVarSlotFromID(src_dsSlot->seqVarIDs[i][0]);
    _FC_SeqSlot* src_seqSlot = _fc_getSeqSlot(src_varSlot->sequence);
    // find the appropriate new sequence from the dest sequences
    rc = fc_getSequences(*new_ds, &temp_numSeq, &temp_seqs);
    for (j = 0; j < temp_numSeq; j++) {
      char* temp_name;
      int temp_numStep;
      FC_DataType temp_dataType;
      void* temp_coords;
      rc = fc_getSequenceName(temp_seqs[j], &temp_name);
      if (rc != FC_SUCCESS)
          return rc;
      rc = fc_getSequenceInfo(temp_seqs[j], &temp_numStep, &temp_dataType);
      if (rc != FC_SUCCESS)
     return rc;
      rc = fc_getSequenceCoordsPtr(temp_seqs[j], &temp_coords);
      if (rc != FC_SUCCESS)
          return rc;
      if (!strcmp(temp_name, src_seqSlot->header.name) &&
       temp_numStep == src_seqSlot->numStep &&
       temp_dataType == src_seqSlot->datatype &&
       !memcmp(temp_coords, src_seqSlot->coords, src_seqSlot->numStep *
            fc_sizeofDataType(src_seqSlot->datatype))) {
       free(temp_name);
       dest_seq = temp_seqs[j];
       break;
      }
      free(temp_name);
    }
    free(temp_seqs);
    // assemble handles
    for (j = 0; j < numStep; j++) {
      src_varSlot = _fc_getVarSlotFromID(src_dsSlot->seqVarIDs[i][j]);
      _FC_GET_HANDLE(src_seqVar[j], src_varSlot);
    }
    rc = fc_copyGlobalSeqVariable(numStep, src_seqVar, *new_ds, dest_seq,
                      NULL, &new_seqVar);
    if (rc != FC_SUCCESS) {
      fc_deleteDataset(*new_ds);
        *new_ds = FC_NULL_DATASET;
      fc_printfErrorMessage("Failed to copy global var '%s'",
                   src_varSlot->header.name);
      return rc;
    }
    free(new_seqVar);
  }
  // copy the meshes
  for (i = 0; i < src_dsSlot->numMesh; i++) {
    FC_Mesh src_mesh, new_mesh;
    _FC_MeshSlot* src_meshSlot = _fc_getMeshSlotFromID(src_dsSlot->meshIDs[i]);
    _FC_GET_HANDLE(src_mesh, src_meshSlot);
    rc = fc_copyMesh(src_mesh, *new_ds, NULL, 1, 1, 1, 1, &new_mesh);
    if (rc != FC_SUCCESS) {
      fc_deleteDataset(*new_ds);
      *new_ds = FC_NULL_DATASET;
      fc_printfErrorMessage("Failed to copy mesh '%s'",
                            src_meshSlot->header.name);
      return rc;
    }
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_createDataset (char * name, FC_Dataset * dataset)
Create a new dataset.
Description:
Create a new, in memory, dataset.
Modifications:
Nancy Collins, Created.
Parameters:
name input - name for new dataset
dataset output - new dataset
Definition at line 116 of file dataset.c.
References _FC_GET_HANDLE, _fc_getNewDsSlot(), _fc_isLibraryInit(), _fc_setSlotHeaderName(), FC_ERROR, fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, FC_NULL_DATASET, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, and _FC_DsSlot::header.
Referenced by _fc_loadExodusDataset(), _fc_loadLSDynaDataset(), fc_copyDataset(), fc_saveSkeleton(), main(), and setupDataset().
  {
  _FC_DsSlot* dsSlot;
  // default return
  if (dataset != NULL)
    *dataset = FC_NULL_DATASET;
  // check input
  if (name == NULL || dataset == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // make sure library is ready, return error if it's not
  if (!_fc_isLibraryInit()) {
    fc_printfErrorMessage("Cannot create a dataset until library is initialized.");
    return FC_ERROR;
  }
  // log message
  fc_printfLogMessage("Creating new dataset '%s'", name);
  // get an open slot
  dsSlot = _fc_getNewDsSlot();
  if (dsSlot == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  // table header information
  _FC_GET_HANDLE(*dataset, dsSlot);
  _fc_setSlotHeaderName(&(dsSlot->header), name);
  return FC_SUCCESS;
}
FC_ReturnCode fc_deleteDataset (FC_Dataset dataset)
Delete a dataset.
Description:
Call when this dataset is no longer needed. It deletes the dataset and all of it's children including it's meshes, variables, etc.
Modifications:
Nancy Collins Created.
Aug 5, 2002 W Koegler Now calls _fc_killDsSlot so that fc_closeDataset and fc_openDataset can use the same code to release the dsTable slot.
11/20/03 RM, added more input checking, if dataset closed with default handle FC_NULL_DATASET then do nothing and return success (issue warning if fc_getLibraryVerbosity()).
9/21/2006 WSD added deleting of member global vars
Parameters:
dataset input - dataset to be deleted
Definition at line 659 of file dataset.c.
References _fc_closeDataset(), _fc_deleteDsSlot(), _fc_getDsSlot(), _FC_SlotHeader::committed, fc_deleteMesh(), fc_deleteSequence(), fc_deleteSeqVariable(), fc_deleteVariable(), fc_getGlobalSeqVariables(), fc_getGlobalVariables(), fc_getMeshes(), fc_getReturnCodeText(), fc_getSequences(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, FC_NULL_DATASET, fc_printfErrorMessage, fc_printfLogMessage, fc_printfWarningMessage, FC_SUCCESS, _FC_DsSlot::header, and _FC_SlotHeader::name.
Referenced by fc_copyDataset(), fc_finalLibrary(), and main().
  {
  FC_ReturnCode rc;
  int i;
  _FC_DsSlot* dsSlot;
  int numSequence, numMesh, numVar, numSeqVar, *numStepPerVar;
  FC_Sequence *sequences;
  FC_Mesh *meshes;
  FC_Variable *variables, **seqVariables;
  // special case: deleting a null handle is not an error
  if ( FC_HANDLE_EQUIV(dataset, FC_NULL_DATASET)) {
    fc_printfWarningMessage("Deleting FC_NULL_DATASET.");
    return FC_SUCCESS;
  }
  // check input
  dsSlot = _fc_getDsSlot(dataset);
  if (dsSlot == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Deleting dataset '%s'", dsSlot->header.name);
  // free up any file IO related stuff
  if (dsSlot->header.committed) {
    rc = _fc_closeDataset(dataset);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // delete member global vars
  rc = fc_getGlobalVariables(dataset, &numVar, &variables);
  if (rc != FC_SUCCESS)
    return rc;
  for (i = 0; i < numVar; i++) {
    rc = fc_deleteVariable(variables[i]);
    if (rc != FC_SUCCESS)
      return rc;
  }
  free(variables);
  // delete member global seq vars
  rc = fc_getGlobalSeqVariables(dataset, &numSeqVar, &numStepPerVar,
                    &seqVariables);
  if (rc != FC_SUCCESS)
    return rc;
  for (i = 0; i < numSeqVar; i++) {
    rc = fc_deleteSeqVariable(numStepPerVar[i], seqVariables[i]);
    if (rc != FC_SUCCESS)
      return rc;
  }
  free(numStepPerVar);
  for (i = 0; i < numSeqVar; i++)
    free(seqVariables[i]);
  free(seqVariables);
  // delete member meshes
  rc = fc_getMeshes(dataset, &numMesh, &meshes);
  if (rc != FC_SUCCESS)
    return rc;
  for (i = 0; i < numMesh; i++) {
    rc = fc_deleteMesh(meshes[i]);
    if (rc != FC_SUCCESS)
      return rc;
  }
  free(meshes);
  // delete member sequences
  rc = fc_getSequences(dataset, &numSequence, &sequences);
  if (rc != FC_SUCCESS)
    return rc;
  for (i = 0; i < numSequence; i++) {
    rc = fc_deleteSequence(sequences[i]);
    if (rc != FC_SUCCESS)
      return rc;
  }
  free(sequences);
  // clear & delete slot
  return _fc_deleteDsSlot(dataset);
}
FC_ReturnCode fc_getDatasetByName (char * datasetName, int * numDatasets, FC_Dataset ** datasets)
Gets all datasets with a given name.
Description:
Return the handles of all datasets with the given name.
Modifications:
9/8/04 WSK, created.
9/21/06 ACG now returns multiple matching items.
Parameters:
datasetName input - name of dataset to find
numDatasets output - num matching datasets
datasets output - dataset handle
Definition at line 447 of file dataset.c.
References _FC_GET_HANDLE, _fc_getDsSlotFromID(), _fc_getDsTableSize(), _fc_isLibraryInit(), FC_ERROR, fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_DsSlot::header, and _FC_SlotHeader::name.
  {
  int i;
  _FC_DsSlot* dsSlot;
  FC_Dataset dataset;
  FC_Dataset *lmatch = NULL;
  int numlmatch, maxnumlmatch;
  // default values returned if anything goes wrong
  if (numDatasets)
    *numDatasets = -1;
  if (datasets)
    *datasets = NULL;
  // call on uninitialized library is an error
  if (!_fc_isLibraryInit()) {
    fc_printfErrorMessage("Library has not been initialized");
    return FC_ERROR;
  }
  // check input
  if (datasetName == NULL || !datasets || !numDatasets) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting dataset '%s'", datasetName);
  numlmatch = 0;
  maxnumlmatch = 0;
  // look for existing slot with the matching name
  for (i = 0; i < _fc_getDsTableSize(); i++) {
    dsSlot = _fc_getDsSlotFromID(i);
    if (dsSlot) {
      if (!strcmp(datasetName, dsSlot->header.name)) {
        _FC_GET_HANDLE(dataset, dsSlot);
     if (lmatch == NULL){
       lmatch = (FC_Dataset*)malloc(sizeof(FC_Dataset));
       if (lmatch == NULL){
         fc_printfErrorMessage("%s",
                      fc_getReturnCodeText(FC_MEMORY_ERROR));
         return FC_MEMORY_ERROR;
       }
       numlmatch = 1;
       maxnumlmatch = 1;
       lmatch[0] = dataset;
     }else{
       if(numlmatch == maxnumlmatch){
         FC_Dataset *temp;
         temp = (FC_Dataset*)realloc(lmatch,
                         (2*numlmatch)*sizeof(FC_Dataset));
         if (temp == NULL){
           fc_printfErrorMessage("%s",
                        fc_getReturnCodeText(FC_MEMORY_ERROR));
           return FC_MEMORY_ERROR;
         }
         maxnumlmatch*=2;
         lmatch = temp;
       }
       lmatch[numlmatch] = dataset;
       numlmatch++;
     }
      }
    }
  }
  *numDatasets = numlmatch;
  *datasets = lmatch;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getDatasetName (FC_Dataset dataset, char ** dsName)
Return name of a dataset.
Description:
Return the name associated with a dataset handle. Spaced is allocated for the string so it needs to be freed by the user when finished.
Modifications:
Aug, 9, 2002. W Koegler Created.
11/21/03 RM, added checking for NULL dataset handle default return filename as NULL if anything is wrong
Parameters:
dataset input - dataset handle
dsName output - dataset name, space allocated here and must be freed by user when finished
Definition at line 784 of file dataset.c.
References _fc_getDsSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_DsSlot::header, and _FC_SlotHeader::name.
Referenced by _fc_writeExodusDataset(), fc_finalLibrary(), and main().
  {
  char *cp;
  _FC_DsSlot* dsSlot;
  // default return value
  if (dsName)
    *dsName = NULL;
  // check input
  dsSlot = _fc_getDsSlot(dataset);
  if (dsSlot == NULL || dsName == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting name for dataset '%s'", dsSlot->header.name);
  // copy name
  cp = dsSlot->header.name;
  *dsName = malloc(strlen(cp) + 1);
  if (*dsName == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  strcpy(*dsName, cp);
  return FC_SUCCESS;
}
FC_ReturnCode fc_getDatasets (int * numDataset, FC_Dataset ** datasets)
Return a list of datasets in the library.
Description:
Returns an array of handles for the existing datasets. The user is responsible for freeing the array of handles.
Modifications:
9/8/04 WSK Created.
Parameters:
numDataset output - number of existing datasets
datasets output - array of dataset (optional)
Definition at line 333 of file dataset.c.
References _FC_GET_HANDLE, _fc_getDsSlotFromID(), _fc_getDsTableSize(), _fc_isLibraryInit(), FC_ERROR, fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
  {
  int i;
  int num;
  _FC_DsSlot* dsSlot;
  // default return values
  if (numDataset != NULL)
    *numDataset = -1;
  if (datasets != NULL)
    *datasets = NULL;
  // call on uninitialized library is an error
  if (!_fc_isLibraryInit()) {
    fc_printfErrorMessage("Library has not been initialized");
    return FC_ERROR;
  }
  // check input
  if (numDataset == NULL || datasets == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting datasets");
  // count datasets
  num = 0;
  for (i = 0; i < _fc_getDsTableSize(); i++) {
    dsSlot = _fc_getDsSlotFromID(i);
    if (dsSlot)
      num++;
  }
  *numDataset = num;
  // get handles
  if (num > 0) {
    *datasets = (FC_Dataset*)malloc(num*sizeof(FC_Dataset));
    if (*datasets == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    num = 0;
    for (i = 0; i < _fc_getDsTableSize(); i++) {
      dsSlot = _fc_getDsSlotFromID(i);
      if (dsSlot) {
        _FC_GET_HANDLE((*datasets)[num], dsSlot);
        num++;
      }
    }
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_getNumDataset (int * numDataset)
Return number of datasets in the library.
Modifications:
9/28/04 WSK Created.
Parameters:
numDataset output - number of existing datasets
Definition at line 398 of file dataset.c.
References _fc_getDsSlotFromID(), _fc_getDsTableSize(), _fc_isLibraryInit(), FC_ERROR, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
  {
  int i, num;
  _FC_DsSlot* dsSlot;
  // default return values
  if (numDataset != NULL)
    *numDataset = -1;
  // call on uninitialized library is an error
  if (!_fc_isLibraryInit()) {
    fc_printfErrorMessage("Library has not been initialized");
    return FC_ERROR;
  }
  // check input
  if (numDataset == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting number of datasets");
  // count datasets
  num = 0;
  for (i = 0; i < _fc_getDsTableSize(); i++) {
    dsSlot = _fc_getDsSlotFromID(i);
    if (dsSlot)
      num++;
  }
  *numDataset = num;
  return FC_SUCCESS;
}
int fc_isDatasetValid (FC_Dataset dataset)
Check that the handle refers to a valid dataset.
Description:
Returns 1 (true) if the handle is valid, and 0 (false) if it is not.
Modifications:
05/25/04 WSK Created.
Parameters:
dataset input - dataset handle
Definition at line 762 of file dataset.c.
References _fc_isHandleValid(), dsTableSize, FC_Dataset::slotID, and FC_Dataset::uID.
Referenced by _fc_makeMeshFromFiles(), fc_copyGlobalVariable(), fc_createBoundingBoxMesh(), fc_createSimpleHexMesh(), and fc_createSphereMesh().
  {
  return _fc_isHandleValid(dataset.slotID, dataset.uID, dsTableSize,
                           (_FC_SlotHeader**)dsTable);
}
FC_ReturnCode fc_printDataset (FC_Dataset dataset, char * label)
Print dataset meta data to stdout.
Modifications:
11/20/03 WSK Created.
Parameters:
dataset input - dataset
label input - label to prepend dataset name with, can be NULL
Definition at line 831 of file dataset.c.
References _fc_getDsSlot(), fc_getNumGlobalSeqVariable(), fc_getNumGlobalVariable(), fc_getNumMesh(), fc_getNumSequence(), fc_getReturnCodeText(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, FC_NULL_DATASET, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_DsSlot::header, INDENT_STR, and _FC_SlotHeader::name.
Referenced by main().
  {
  FC_ReturnCode rc;
  int numMesh, numSeq;
  int numGlbVar, numGlbSeqVar;
  _FC_DsSlot* dsSlot;
  // special case: printing a null handle is not an error
  if (FC_HANDLE_EQUIV(dataset, FC_NULL_DATASET)) {
    printf("Dataset: FC_NULL_DATASET\n");
    fflush(NULL);
    return FC_SUCCESS;
  }
  // check input
  dsSlot = _fc_getDsSlot(dataset);
  if (dsSlot == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Printing dataset '%s'", dsSlot->header.name);
  // print label & var name
  if (label)
    printf("%s: ", label);
  else
    printf("Dataset: ");
  printf("'%s'\n", dsSlot->header.name);
  fflush(NULL);
  // print meta data
  rc = fc_getNumSequence(dataset, &numSeq);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get sequences for dataset '%s'",
                          dsSlot->header.name);
    return rc;
  }
  rc = fc_getNumGlobalVariable(dataset, &numGlbVar);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get global vars for dataset '%s'",
                          dsSlot->header.name);
    return rc;
  }
  rc = fc_getNumGlobalSeqVariable(dataset, &numGlbSeqVar);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get global seq vars for dataset '%s'",
                          dsSlot->header.name);
    return rc;
  }
  rc = fc_getNumMesh(dataset, &numMesh);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get meshes for dataset '%s'",
                          dsSlot->header.name);
    return rc;
  }
  printf("%snumSeq = %d, numGlbVar = %d, numGlbSeqVar = %d, numMesh = %d\n",
         INDENT_STR, numSeq, numGlbVar, numGlbSeqVar, numMesh);
  fflush(NULL);
  return FC_SUCCESS;
}
FC_ReturnCode fc_releaseDataset (FC_Dataset dataset)
Attempt to minimize dataset's memory usage.
Description:
Call to try to release un-needed memory in a dataset. It the dataset has been saved to disk, the large data is released. If the dataset has not be saved to disk, all large data is saved.
This function will recursively call release on it's child sequences and meshes (and they will call their children).
Modifications:
9/27/04 WSK Created.
Parameters:
dataset input - dataset handle
Definition at line 585 of file dataset.c.
References _fc_getDsSlot(), fc_getGlobalSeqVariables(), fc_getGlobalVariables(), fc_getMeshes(), fc_getReturnCodeText(), fc_getSequences(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, FC_NULL_DATASET, fc_printfErrorMessage, fc_printfLogMessage, fc_printfWarningMessage, fc_releaseMesh(), fc_releaseSequence(), fc_releaseSeqVariable(), fc_releaseVariable(), FC_SUCCESS, _FC_DsSlot::header, and _FC_SlotHeader::name.
  {
  int i;
  FC_Sequence *sequences;
  FC_Mesh *meshes;
  FC_Variable *variables, **seqVariables;
  _FC_DsSlot* dsSlot;
  int numSequence, numMesh, numVar, numSeqVar, *numSteps;
  // special case: releasing a null handle is not an error
  if (FC_HANDLE_EQUIV(dataset, FC_NULL_DATASET)) {
    fc_printfWarningMessage("Releasing FC_NULL_DATASET");
    return FC_SUCCESS;
  }
  // check input
  dsSlot = _fc_getDsSlot(dataset);
  if (dsSlot == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Cleaning up dataset '%s'", dsSlot->header.name);
  // call release on children sequences & meshes & global vars
  fc_getSequences(dataset, &numSequence, &sequences);
  for (i = 0; i < numSequence; i++)
    fc_releaseSequence(sequences[i]);
  free(sequences);
  fc_getMeshes(dataset, &numMesh, &meshes);
  for (i = 0; i < numMesh; i++)
    fc_releaseMesh(meshes[i]);
  free(meshes);
  fc_getGlobalVariables(dataset, &numVar, &variables);
  for (i = 0; i < numVar; i++)
    fc_releaseVariable(variables[i]);
  free(variables);
  fc_getGlobalSeqVariables(dataset, &numSeqVar, &numSteps, &seqVariables);
  for (i = 0; i < numSeqVar; i++)
    fc_releaseSeqVariable(numSteps[i], seqVariables[i]);
  free(numSteps);
  for (i = 0; i < numSeqVar; i++)
    free(seqVariables[i]);
  free(seqVariables);
  // no big data
  //if (dsSlot->header.committed == 1) {
  //}
  return FC_SUCCESS;
}