FCLib: Data Types
Data Types
[FCLib API]
Detailed Description
Data types of the library.
Description:
The possible values of many types of data are represented with enumerations. This module contains the enum declarations and some basic functions for manipulating them.
DataType Enums
enum FC_VerbosityLevel {
FC_QUIET = 0,
FC_ERROR_MESSAGES,
FC_WARNING_MESSAGES,
FC_LOG_MESSAGES,
FC_DEBUG_MESSAGES
}
Possible verbosity levels.
enum FC_ReturnCode {
FC_SUCCESS = 0,
FC_ERROR = -1,
FC_MEMORY_ERROR = -2,
FC_INPUT_ERROR = -3,
FC_FILE_IO_ERROR = -4
}
Possible function return values.
enum FC_ElementType {
FC_ET_UNKNOWN = 0,
FC_ET_POINT,
FC_ET_LINE,
FC_ET_TRI,
FC_ET_QUAD,
FC_ET_TET,
FC_ET_PYRAMID,
FC_ET_PRISM,
FC_ET_HEX,
FC_ET_MIXED
}
Possible element types.
enum FC_DataType {
FC_DT_UNKNOWN = 0,
FC_DT_CHAR,
FC_DT_INT,
FC_DT_FLOAT,
FC_DT_DOUBLE
}
Possible data types.
enum FC_MathType {
FC_MT_UNKNOWN = 0,
FC_MT_SCALAR,
FC_MT_VECTOR,
FC_MT_SYMTENSOR,
FC_MT_TENSOR
}
Possible ways of organizing data values.
enum FC_AssociationType {
FC_AT_UNKNOWN = 0,
FC_AT_VERTEX,
FC_AT_EDGE,
FC_AT_FACE,
FC_AT_ELEMENT,
FC_AT_WHOLE_MESH,
FC_AT_WHOLE_DATASET
}
Possible association of the data to the mesh.
Check that an enum has a valid value
These routines return true (1) if the int passed is a valid value for the enumerated type, and false (0) if it is not. Enum values of the type FC_X_UNKNOWN are considered valid because they are possible values of the enum. In many cases you may want to check for a "good" value and should check "fc_isXValid(value) && value != FC_X_UNKNOWN".
int fc_isVerbosityLevelValid (FC_VerbosityLevel verbosity)
Verify that the given value is valid for this enum.
int fc_isReturnCodeValid (FC_ReturnCode rc)
Verify that the given value is valid for this enum.
int fc_isElementTypeValid (FC_ElementType elemType)
Verify that the given value is valid for this enum.
int fc_isDataTypeValid (FC_DataType dataType)
Verify that the given value is valid for this enum.
int fc_isMathTypeValid (FC_MathType mathtype)
Verify that the given value is valid for this enum.
int fc_isAssociationTypeValid (FC_AssociationType assoc)
Verify that the given value is valid for this enum.
Get the name of an enum value as text
These routines return a text string holding the name of the enum value. If the enum value is invalid, they return NULL. The returned string should NOT be freed.
char * fc_getVerbosityLevelText (FC_VerbosityLevel verbosity)
Return the name of the FC_VerbosityLevel's value.
char * fc_getReturnCodeText (FC_ReturnCode rc)
Return the name of the FC_ReturnCode's value.
char * fc_getElementTypeText (FC_ElementType elemType)
Return the name of the FC_ElementType's value.
char * fc_getDataTypeText (FC_DataType dataType)
Return the name of the FC_DataType's value.
char * fc_getMathTypeText (FC_MathType mathtype)
Return the name of the FC_MathType's value.
char * fc_getAssociationTypeText (FC_AssociationType assoc)
Return the name of the FC_AssociationType's value.
Get information about an FC_ElementType
int fc_getElementTypeTopoDim (FC_ElementType elemType)
Returns number of topological dimensions for a type of element.
int fc_getElementTypeNumVertex (FC_ElementType elemType)
Returns number of vertices in a type of element.
int fc_getElementTypeNumEdge (FC_ElementType elemType)
Returns number of edges in a type of element.
int fc_getElementTypeNumFace (FC_ElementType elemType)
Returns number of faces in a type of element.
int fc_getElementTypeNumEntity (FC_ElementType elemType, FC_AssociationType assoc)
Returns number of the entity type in a type of element.
FC_ElementType fc_getElementTypeFaceType (FC_ElementType elemType)
Returns the element type of the faces of the element.
Get information about an FC_DataType
int fc_sizeofDataType (FC_DataType dataType)
Returns the number of bytes in an FC_DataType, like sizeof().
Enumeration Type Documentation
enum FC_AssociationType
Possible association of the data to the mesh.
Description:
Specifies which type of sub-entity of a mesh something is associated with. E.g a variable with a vertex association will have data for each vertex.
Todo:
?Surely we can come up with a better name? entity type?
Enumerator:
FC_AT_UNKNOWN
FC_AT_VERTEX
FC_AT_EDGE Cannot exist in 0D meshes, and is the same as elements in 1D meshes
FC_AT_FACE Cannot exist in 0D or 1D meshes, and is the same as elements in 2D meshes
FC_AT_ELEMENT Will be 0D, 1D, 2D or 3D depending on element type
FC_AT_WHOLE_MESH Refers to the entire mesh
FC_AT_WHOLE_DATASET Refers to the entire dataset
Definition at line 188 of file base.h.
{
  FC_AT_UNKNOWN = 0,
  FC_AT_VERTEX,
  FC_AT_EDGE,      /**< Cannot exist in 0D meshes, and is the same
              as elements in 1D meshes */
  FC_AT_FACE,      /**< Cannot exist in 0D or 1D meshes, and is the
              same as elements in 2D meshes */
  FC_AT_ELEMENT,   /**< Will be 0D, 1D, 2D or 3D depending on element type */
  FC_AT_WHOLE_MESH,    /**< Refers to the entire mesh */
  FC_AT_WHOLE_DATASET  /**< Refers to the entire dataset */
} FC_AssociationType;
enum FC_DataType
Possible data types.
Enumerator:
FC_DT_UNKNOWN
FC_DT_CHAR
FC_DT_INT
FC_DT_FLOAT
FC_DT_DOUBLE
Definition at line 136 of file base.h.
{
  FC_DT_UNKNOWN = 0,
  FC_DT_CHAR,
  // FC_DT_UCHAR,
  // FC_DT_SHORT,
  // FC_DT_USHORT,
  FC_DT_INT,
  // FC_DT_UINT,
  // FC_DT_LONG,
  // FC_DT_ULONG,
  // FC_DT_LONGLONG,    /* 64 bits */
  // FC_DT_ULONGLONG,   /* 64 bits */
  FC_DT_FLOAT,
  FC_DT_DOUBLE
  // FC_DT_LONGDOUBLE,  /* 128 bits */
} FC_DataType;
enum FC_ElementType
Possible element types.
Description:
Enumerator:
FC_ET_UNKNOWN
FC_ET_POINT
FC_ET_LINE
FC_ET_TRI
FC_ET_QUAD
FC_ET_TET
FC_ET_PYRAMID
FC_ET_PRISM
FC_ET_HEX
FC_ET_MIXED This is needed to describe faces on pyramids & prisms
Definition at line 117 of file base.h.
{
  FC_ET_UNKNOWN = 0,
  FC_ET_POINT,
  FC_ET_LINE,
  FC_ET_TRI,
  FC_ET_QUAD,
  FC_ET_TET,
  FC_ET_PYRAMID,
  FC_ET_PRISM,
  FC_ET_HEX,
  // arbitrary polygon?
  FC_ET_MIXED /**< This is needed to describe faces on pyramids & prisms */
} FC_ElementType;
enum FC_MathType
Possible ways of organizing data values.
Description:
Specifies the organization and order of the components of a variable. For instance, FC_MT_SCALAR denotes a scalar field which will have a single value per data point. FC_MT_VECTOR denotes a vector field with n (numComponent) ordered components such as X, Y and Z for a vector with 3 components.
Enumerator:
FC_MT_UNKNOWN
FC_MT_SCALAR
FC_MT_VECTOR
FC_MT_SYMTENSOR not fully supported by most library routines
FC_MT_TENSOR not fully supported by most library routines
Definition at line 167 of file base.h.
{
  FC_MT_UNKNOWN = 0,
  FC_MT_SCALAR,
  FC_MT_VECTOR,
  FC_MT_SYMTENSOR,  /**< not fully supported by most library routines */
  FC_MT_TENSOR      /**< not fully supported by most library routines */
} FC_MathType;
enum FC_ReturnCode
Possible function return values.
Description:
Enumerated constants are provided for return values. Generally, a function which returns '0' or 'FC_SUCCESS' is considered to have succeeded, and return values less than 1 indicates that an error occurred. FC_ERROR (-1) is a generic error category.
Modifications:
2003-SEP-22 W Koegler Created
Enumerator:
FC_SUCCESS
FC_ERROR
FC_MEMORY_ERROR
FC_INPUT_ERROR
FC_FILE_IO_ERROR
Definition at line 102 of file base.h.
{
  FC_SUCCESS = 0,
  FC_ERROR = -1,
  FC_MEMORY_ERROR = -2,
  FC_INPUT_ERROR = -3,
  FC_FILE_IO_ERROR = -4
} FC_ReturnCode;
enum FC_VerbosityLevel
Possible verbosity levels.
Description:
Generally, error messages are for conditions that halt execution (e.g. "Error: cannot operate on NULL input"); warning messages are for unexpected conditions that can still be handled (e.g. "Warning: expected 1 input but found 3, using first one"); log messages are for normal events (e.g. "Log: Variable 'temp' created"); and debug messages report state, internal variables and other details for developers (e.g. "Debug: 12 entries in DsTable").
In FCLib, a verbosity level implies all levels below it. For instance, asking for warning message will also report error messages. The message hierarchy, from less to more verbose, is:
FC_QUIET < FC_ERROR_MESSAGES < FC_WARNING_MESSAGES < FC_LOG_MESSAGES < FC_DEBUG_MESSAGES
Enumerator:
FC_QUIET no messages
FC_ERROR_MESSAGES error messages
FC_WARNING_MESSAGES warning and error messages
FC_LOG_MESSAGES log, warning and error messages
FC_DEBUG_MESSAGES debug, log, warning and error messages
Definition at line 79 of file base.h.
{
  FC_QUIET = 0,        /**< no messages */
  FC_ERROR_MESSAGES,   /**< error messages   */
  FC_WARNING_MESSAGES, /**< warning and error messages */
  FC_LOG_MESSAGES,     /**< log, warning and error messages  */
  FC_DEBUG_MESSAGES    /**< debug, log, warning and error messages */
} FC_VerbosityLevel;
Function Documentation
char* fc_getAssociationTypeText (FC_AssociationType assoc)
Return the name of the FC_AssociationType's value.
Description:
Returns a string representing the name of the enum value or NULL is the enum value is invalid. The string should NOT be freed.
Modifications: -Nancy Collins Created.
2003-NOV-17 WSK Changed to return the enum values' name instead of more human readable word.
Definition at line 477 of file base.c.
References FC_AT_EDGE, FC_AT_ELEMENT, FC_AT_FACE, FC_AT_UNKNOWN, FC_AT_VERTEX, FC_AT_WHOLE_DATASET, and FC_AT_WHOLE_MESH.
Referenced by _fc_buildFaceInfoListFromSubset(), _fc_buildMeshElementNeighborsViaEntity(), _fc_buildParents(), _fc_printSubTable(), _fc_printVarTable(), _fc_writeExodusDataset(), fc_copyGlobalSeqVariable(), fc_copyGlobalVariable(), fc_createSeqSubset(), fc_createSubset(), fc_evalPrestoSpotWeld(), fc_getMeshNumEntity(), fc_getSubsetSkin(), fc_printSeqSubsetRange(), fc_printSeqVariableRange(), fc_printSubset(), fc_printSubsetOfMesh(), fc_printSubsetOfVariable(), fc_printVariable(), and main().
{
  switch (assoc) {
  case FC_AT_UNKNOWN:        return "FC_AT_UNKNOWN";
  case FC_AT_VERTEX:         return "FC_AT_VERTEX";
  case FC_AT_EDGE:           return "FC_AT_EDGE";
  case FC_AT_FACE:           return "FC_AT_FACE";
  case FC_AT_ELEMENT:        return "FC_AT_ELEMENT";
  case FC_AT_WHOLE_MESH:     return "FC_AT_WHOLE_MESH";
  case FC_AT_WHOLE_DATASET:  return "FC_AT_WHOLE_DATASET";
  // no default case so will get warning if new values added to enum
  }
  return NULL;
}
char* fc_getDataTypeText (FC_DataType dataType)
Return the name of the FC_DataType's value.
Description:
Returns a string representing the name of the enum value or NULL is the enum value is invalid. The string should NOT be freed.
Modifications:
Nancy Collins Created.
2003-NOV-17 WSK Changed to return the enum values' name instead of more human readable word.
Definition at line 419 of file base.c.
References FC_DT_CHAR, FC_DT_DOUBLE, FC_DT_FLOAT, FC_DT_INT, and FC_DT_UNKNOWN.
Referenced by _fc_binaryOperatorCore(), _fc_printSeqTable(), _fc_printVarTable(), _fc_writeExodusDataset(), fc_createThresholdSubset(), fc_getSequenceCoordsAsDataType(), fc_getVariableDataAsDataType(), fc_operatorVar(), fc_printSequence(), fc_printSeqVariableRange(), fc_printSubsetOfVariable(), fc_printVariable(), fc_varBinaryFunctionConstVar(), fc_varBinaryFunctionVarConst(), fc_varBinaryFunctionVarVar(), fc_varUnaryFunction(), get_doubles(), main(), and myCharacterizationFunkyAve().
{
  switch (dataType) {
  case FC_DT_UNKNOWN:       return "FC_DT_UNKNOWN";
  case FC_DT_CHAR:          return "FC_DT_CHAR";
  case FC_DT_INT:           return "FC_DT_INT";
  case FC_DT_FLOAT:         return "FC_DT_FLOAT";
  case FC_DT_DOUBLE:        return "FC_DT_DOUBLE";
  // no default case so will get warning if new values added to enum
  }
  return NULL;
}
FC_ElementType fc_getElementTypeFaceType (FC_ElementType elemType)
Returns the element type of the faces of the element.
Description:
For FC_ET_PYRAMID and FC_ET_PRISM the face type is a mix of FC_ET_TRI and FC_ET_QUAD, so the type FC_ET_MIXED is return.
For FC_ET_POINT and FC_ET_LINE which don't have faces, the type returned is FC_ET_UNKNOWN.
Modifications:
02/05/04 WSK, Created.
Definition at line 698 of file base.c.
References FC_ET_HEX, FC_ET_LINE, FC_ET_MIXED, FC_ET_POINT, FC_ET_PRISM, FC_ET_PYRAMID, FC_ET_QUAD, FC_ET_TET, FC_ET_TRI, FC_ET_UNKNOWN, and fc_printfWarningMessage.
Referenced by _fc_buildFaceConns(), _fc_printMeshTable(), fc_getMeshEdgeFaceInfo(), fc_getMeshFaceConnsPtr(), and fc_getMeshFaceType().
{
  switch (elemType) {
  case FC_ET_MIXED:    // fall through to FC_ET_UNKNOWN
  case FC_ET_UNKNOWN:  return FC_ET_UNKNOWN;
  case FC_ET_POINT:    // fall through to FC_ET_LINE
  case FC_ET_LINE:     return FC_ET_UNKNOWN;
  case FC_ET_TRI:      return FC_ET_TRI;
  case FC_ET_QUAD:     return FC_ET_QUAD;
  case FC_ET_TET:      return FC_ET_TRI;
  case FC_ET_PYRAMID:  // fall through to FC_ET_PRISM
  case FC_ET_PRISM:    return FC_ET_MIXED;
  case FC_ET_HEX:      return FC_ET_QUAD;
  // no default case so will get warning if new values added to enum
  }
  fc_printfWarningMessage(
     "Warning: invalid value for enum FC_ElementType");
  return FC_ET_UNKNOWN;
}
int fc_getElementTypeNumEdge (FC_ElementType elemType)
Returns number of edges in a type of element.
Description:
Returns the number of edges in a type of element. If the type is unknown (FC_ET_UNKNOWN), -1 is returned.
Modifications:
Nancy Collins Created.
2003-NOV-17 WSK Changed to return numVertex instead of passing back out in argument list.
Definition at line 586 of file base.c.
References FC_ET_HEX, FC_ET_LINE, FC_ET_MIXED, FC_ET_POINT, FC_ET_PRISM, FC_ET_PYRAMID, FC_ET_QUAD, FC_ET_TET, FC_ET_TRI, FC_ET_UNKNOWN, and fc_printfWarningMessage.
Referenced by _fc_buildEdgeConns(), _fc_readExodusSubsetMembers(), _fc_writeExodusDataset(), fc_createSubsetMesh(), fc_getElementTypeNumEntity(), and fc_getMeshEntityChildren().
{
  switch (elemType) {
  case FC_ET_MIXED:     // fall through to FC_ET_UNKNOWN
  case FC_ET_UNKNOWN:   return -1;
  case FC_ET_POINT:     return  0;
  case FC_ET_LINE:      return  1;
  case FC_ET_TRI:       return  3;
  case FC_ET_QUAD:      return  4;
  case FC_ET_TET:       return  6;
  case FC_ET_PYRAMID:   return  8;
  case FC_ET_PRISM:     return  9;
  case FC_ET_HEX:       return 12;
  // no default case so will get warning if new values added to enum
  }
  fc_printfWarningMessage(
     "Warning: invalid value for enum FC_ElementType");
  return -1;
}
int fc_getElementTypeNumEntity (FC_ElementType elemType, FC_AssociationType assoc)
Returns number of the entity type in a type of element.
Description:
Returns the number of the entity type for a type of element. If the type is unknown (FC_ET_UNKNOWN), -1 is returned. If the entity type is inappropriate (e.g. FC_AT_WHOLE_MESH on any type of element, or e.g. FC_AT_FACE on for FC_ET_LINE) it returns -1. Note, passing FC_AT_ELEMENT will return 1.
For entity specific behavior see fc_getElementTypeNumVertex(), fc_getElementTypeNumEdge(), and fc_getElementTypeNumFace().
Modifications:
10/24/2005 WSD Created.
Parameters:
elemType input - Type of element
assoc Type of entity
Definition at line 662 of file base.c.
References FC_AT_EDGE, FC_AT_ELEMENT, FC_AT_FACE, FC_AT_UNKNOWN, FC_AT_VERTEX, FC_AT_WHOLE_DATASET, FC_AT_WHOLE_MESH, fc_getElementTypeNumEdge(), fc_getElementTypeNumFace(), fc_getElementTypeNumVertex(), and fc_printfWarningMessage.
Referenced by _fc_buildMeshElementNeighborsViaEntity(), _fc_buildParents(), and fc_getMeshEntityChildren().
{
  switch (assoc) {
  case FC_AT_VERTEX:         return fc_getElementTypeNumVertex(elemType);
  case FC_AT_EDGE:           return fc_getElementTypeNumEdge(elemType);
  case FC_AT_FACE:           return fc_getElementTypeNumFace(elemType);
  case FC_AT_ELEMENT:        return 1;
  case FC_AT_UNKNOWN:        // fall through
  case FC_AT_WHOLE_MESH:     return -1;
  case FC_AT_WHOLE_DATASET:  return -1;
  // no default case so will get warning if new values added to enum
  }
  fc_printfWarningMessage(
     "Warning: invalid value for enum FC_AssociationType");
  return -1;
}
int fc_getElementTypeNumFace (FC_ElementType elemType)
Returns number of faces in a type of element.
Description:
Returns the number of faces for a type of element. If the type is unknown (FC_ET_UNKNOWN), -1 is returned.
Modifications:
Nancy Collins Created.
2003-NOV-17 WSK Changed to return numFace instead of passing back out in argument list.
Definition at line 622 of file base.c.
References FC_ET_HEX, FC_ET_LINE, FC_ET_MIXED, FC_ET_POINT, FC_ET_PRISM, FC_ET_PYRAMID, FC_ET_QUAD, FC_ET_TET, FC_ET_TRI, FC_ET_UNKNOWN, and fc_printfWarningMessage.
Referenced by _fc_buildFaceConns(), _fc_getOutwardFaceNormal(), _fc_readExodusSubsetMembers(), _fc_writeExodusDataset(), calcFaceOrients(), fc_createSubsetMesh(), and fc_getElementTypeNumEntity().
{
  switch (elemType) {
  case FC_ET_MIXED:    // fall through to FC_ET_UNKNOWN
  case FC_ET_UNKNOWN:  return -1;
  case FC_ET_POINT:    // fall through to FC_ET_LINE
  case FC_ET_LINE:     return 0;
  case FC_ET_TRI:      // fall through to FC_ET_QUAD
  case FC_ET_QUAD:     return 1;
  case FC_ET_TET:      return 4;
  case FC_ET_PYRAMID:  // fall through to FC_ET_PRISM
  case FC_ET_PRISM:    return 5;
  case FC_ET_HEX:      return 6;
  // no default case so will get warning if new values added to enum
  }
  fc_printfWarningMessage(
     "Warning: invalid value for enum FC_ElementType");
  return -1;
}
int fc_getElementTypeNumVertex (FC_ElementType elemType)
Returns number of vertices in a type of element.
Description:
Returns the number of vertices of the type of element. If the type is unknown (FC_ET_UNKNOWN), -1 is returned.
Modifications:
Nancy Collins Created.
2003-NOV-17 WSK Changed to return numVertex instead of passing back out in argument list.
Definition at line 550 of file base.c.
References FC_ET_HEX, FC_ET_LINE, FC_ET_MIXED, FC_ET_POINT, FC_ET_PRISM, FC_ET_PYRAMID, FC_ET_QUAD, FC_ET_TET, FC_ET_TRI, FC_ET_UNKNOWN, and fc_printfWarningMessage.
Referenced by _fc_buildEdgeConns(), _fc_buildFaceConns(), _fc_calcLSDynaElemChunks(), _fc_geomSmoothCore(), _fc_readElementFile(), _fc_readExodusMeshElemConns(), _fc_readLSDynaMeshElemConns(), _fc_writeExodusDataset(), fc_createSubsetMesh(), fc_doesElementContainPoint(), fc_evalPrestoSpotWeld(), fc_getDisplacedRegionVolumes(), fc_getDisplacedSurfaceNormals(), fc_getElementCenters(), fc_getElementsThatContainPoint(), fc_getElementTypeNumEntity(), fc_getRegionVolumes(), fc_getSurfaceNormals(), fc_makeSpanningTree(), fc_printMesh(), fc_printSubsetOfMesh(), fc_projectedElementBoundingBoxIntersection(), fc_setMeshElementConns(), and main().
{
  switch (elemType) {
  case FC_ET_MIXED:   // fall through to FC_ET_UNKNOWN
  case FC_ET_UNKNOWN:  return -1;
  case FC_ET_POINT:    return 1;
  case FC_ET_LINE:     return 2;
  case FC_ET_TRI:      return 3;
  case FC_ET_QUAD:     // fall through to FC_ET_TET
  case FC_ET_TET:      return 4;
  case FC_ET_PYRAMID:  return 5;
  case FC_ET_PRISM:    return 6;
  case FC_ET_HEX:      return 8;
  // no default case so will get warning if new values added to enum
  }
  fc_printfWarningMessage(
     "Warning: invalid value for enum FC_ElementType");
  return -1;
}
char* fc_getElementTypeText (FC_ElementType elemType)
Return the name of the FC_ElementType's value.
Description:
Returns a string representing the name of the enum value or NULL is the enum value is invalid. The string should NOT be freed.
Modifications:
Nancy Collins Created.
2003-NOV-17 WSK Changed to return the enum values' name instead of more human readable word.
Definition at line 385 of file base.c.
References FC_ET_HEX, FC_ET_LINE, FC_ET_MIXED, FC_ET_POINT, FC_ET_PRISM, FC_ET_PYRAMID, FC_ET_QUAD, FC_ET_TET, FC_ET_TRI, and FC_ET_UNKNOWN.
Referenced by _fc_buildEdgeConns(), _fc_buildFaceConns(), _fc_getOutwardFaceNormal(), _fc_printMeshTable(), _fc_writeExodusDataset(), fc_getDisplacedFaceAreas(), fc_getDisplacedRegionVolumes(), fc_getFaceAreas(), fc_getRegionVolumes(), fc_getSurfaceNormals(), fc_printMesh(), fc_printSubsetOfMesh(), and main().
{
  switch(elemType) {
  case FC_ET_UNKNOWN:    return "FC_ET_UNKNOWN";
  case FC_ET_POINT:      return "FC_ET_POINT";
  case FC_ET_LINE:       return "FC_ET_LINE";
  case FC_ET_TRI:        return "FC_ET_TRI";
  case FC_ET_QUAD:       return "FC_ET_QUAD";
  case FC_ET_TET:        return "FC_ET_TET";
  case FC_ET_PYRAMID:    return "FC_ET_PYRAMID";
  case FC_ET_PRISM:      return "FC_ET_PRISM";
  case FC_ET_HEX:        return "FC_ET_HEX";
  case FC_ET_MIXED:      return "FC_ET_MIXED";
  // no default case so will get warning if new values added to enum
  }
  return NULL;
}
int fc_getElementTypeTopoDim (FC_ElementType elemType)
Returns number of topological dimensions for a type of element.
Description:
Returns the topological dimensionality of the type of element. If the type is unknown (FC_ET_UNKNOWN), -1 is returned.
Modifications:
Nancy Collins Created.
2003-NOV-17 WSK Changed to return topodim instead of passing back out in argument list.
Definition at line 514 of file base.c.
References FC_ET_HEX, FC_ET_LINE, FC_ET_MIXED, FC_ET_POINT, FC_ET_PRISM, FC_ET_PYRAMID, FC_ET_QUAD, FC_ET_TET, FC_ET_TRI, FC_ET_UNKNOWN, and fc_printfWarningMessage.
Referenced by _fc_buildFaceInfoListFromSubset(), _fc_loadExodusDataset(), _fc_loadLSDynaDataset(), _fc_readExodusSubsetMembers(), _fc_writeExodusDataset(), fc_getSubsetSkin(), fc_setMeshElementConns(), and fc_setMeshElementConnsPtr().
{
  switch (elemType) {
  case FC_ET_MIXED:    // fall through to FC_ET_UNKNOWN
  case FC_ET_UNKNOWN:  return -1;
  case FC_ET_POINT:    return 0;
  case FC_ET_LINE:     return 1;
  case FC_ET_TRI:      // fall through to FC_ET_QUAD
  case FC_ET_QUAD:     return 2;
  case FC_ET_TET:      // fall through to FC_ET_HEX
  case FC_ET_PYRAMID:  // fall through to FC_ET_HEX
  case FC_ET_PRISM:    // fall through to FC_ET_HEX
  case FC_ET_HEX:      return 3;
  // no default case so will get warning if new values added to enum
  }
  fc_printfWarningMessage(
     "Warning: invalid value for enum FC_ElementType");
  return -1;
}
char* fc_getMathTypeText (FC_MathType mathtype)
Return the name of the FC_MathType's value.
Description:
Returns a string representing the name of the enum value or NULL is the enum value is invalid. The string should NOT be freed.
Modifications:
Nancy Collins Created.
2003-NOV-17 WSK Changed to return the enum values' name instead of more human readable word.
Definition at line 448 of file base.c.
References FC_MT_SCALAR, FC_MT_SYMTENSOR, FC_MT_TENSOR, FC_MT_UNKNOWN, and FC_MT_VECTOR.
Referenced by _fc_printVarTable(), fc_printSeqVariableRange(), fc_printSubsetOfVariable(), fc_printVariable(), and main().
{
  switch (mathtype) {
  case FC_MT_UNKNOWN:       return "FC_MT_UNKNOWN";
  case FC_MT_SCALAR:        return "FC_MT_SCALAR";
  case FC_MT_VECTOR:        return "FC_MT_VECTOR";
  case FC_MT_SYMTENSOR:     return "FC_MT_SYMTENSOR";
  case FC_MT_TENSOR:        return "FC_MT_TENSOR";
  // no default case so will get warning if new values added to enum
  }
  return NULL;
}
char* fc_getReturnCodeText (FC_ReturnCode rc)
Return the name of the FC_ReturnCode's value.
Description:
Returns a string representing the name of the enum value or NULL is the enum value is invalid. The string should NOT be freed.
Modifications:
2003-SEP-22 W Koegler Created
Parameters:
rc input - enum to return printable string for
Definition at line 355 of file base.c.
References FC_ERROR, FC_FILE_IO_ERROR, FC_INPUT_ERROR, FC_MEMORY_ERROR, and FC_SUCCESS.
Referenced by _fc_addEntryToSortedBlobArray(), _fc_addEntryToSortedIntArray(), _fc_addToSFI_Array(), _fc_binaryOperatorCore(), _fc_buildEdgeConns(), _fc_buildFaceConns(), _fc_buildFaceInfoListFromSubset(), _fc_buildMeshElementNeighborsViaEntity(), _fc_buildMeshVertexNeighborsViaEdge(), _fc_buildParents(), _fc_calcLSDynaElemChunks(), _fc_calcQuadParams(), _fc_closeDataset(), _fc_closeExodusDataset(), _fc_closeLSDynaDataset(), _fc_createExoVarCompName(), _fc_createFeature(), _fc_createSeqVariableFromVariable(), _fc_createShapePartsFromFaceInfoList(), _fc_createVertexBinCore(), _fc_deleteDsSlot(), _fc_deleteEntryFromSortedBlobArray(), _fc_deleteEntryFromSortedIntArray(), _fc_deleteMeshSlot(), _fc_deleteSeqSlot(), _fc_deleteSubSlot(), _fc_deleteVarSlot(), _fc_doesElementContainPoint(), _fc_expandBlobArray(), _fc_expandIntArray(), _fc_feature_addChild(), _fc_feature_addParent(), _fc_feature_addROI(), _fc_featureGroup_addFeature(), _fc_featureGroup_addROI(), _fc_featureGroup_getFeature(), _fc_featureGroup_getFeatures(), _fc_geomSmoothCore(), _fc_getDiameterOutputArgsTest(), _fc_getDiameterOutputArgsTestMeshes(), _fc_getDiameterOutputArgsTestSubsets(), _fc_getEdgeNeighbors(), _fc_getEdgeParents(), _fc_getElementNeighbors(), _fc_getFaceNeighbors(), _fc_getFaceParents(), _fc_getMeshEdgeParentsOfVerticesPtr(), _fc_getMeshElementNeighborsViaEdgePtr(), _fc_getMeshElementNeighborsViaFacePtr(), _fc_getMeshElementNeighborsViaVertexPtr(), _fc_getMeshElementParentsOfEdgesPtr(), _fc_getMeshElementParentsOfFacesPtr(), _fc_getMeshElementParentsOfVerticesPtr(), _fc_getMeshExodusGlobalElementIDOffset(), _fc_getMeshExodusGlobalNodalIDsPtr(), _fc_getMeshFaceParentsOfVerticesPtr(), _fc_getMeshVertexNeighborsViaEdgePtr(), _fc_getNewSlot(), _fc_getOutwardFaceNormal(), _fc_getSubsetsProximityArgsTest(), _fc_getSubsetsProximityCore(), _fc_getVertexIDsWithinBoundingBoxUsingVertexBin(), _fc_getVertexIDsWithinSphereUsingVertexBin(), _fc_getVertexNeighbors(), _fc_getVertexParents(), _fc_hasSharedLSDynaVertices(), _fc_initSierraInfo(), _fc_loadExodusDataset(), _fc_loadLSDynaDataset(), _fc_makeNewSeqVar(), _fc_parseDefinitionForFunction(), _fc_parseSpotWeld(), _fc_readExodusAttributeData(), _fc_readExodusMeshCoords(), _fc_readExodusMeshElemConns(), _fc_readExodusOneStepVariableData(), _fc_readExodusSequenceCoords(), _fc_readExodusSubsetMembers(), _fc_readExodusVariableData(), _fc_readLSDynaMeshCoords(), _fc_readLSDynaMeshElemConns(), _fc_readLSDynaVariableData(), _fc_readMeshCoords(), _fc_readNamesFile(), _fc_readSequenceCoords(), _fc_reallocSFI_Array(), _fc_recursive_IndividuallySegmentingNodes(), _fc_setSlotHeaderName(), _fc_setSphereCoords(), _fc_writeExodusDataset(), _fc_writeFeatureGraph(), _fc_writeFeatureGroup(), buildScrews(), fc_addArrayMembersToSubset(), fc_addIntArrayToSortedIntArray(), fc_addMaskMembersToSubset(), fc_addMemberToSubset(), fc_addROIsUsingBasicEvents(), fc_addValueToIntArray(), fc_calcAngleBetweenVectors(), fc_calcDistanceMatrix(), fc_calcEuclideanDistance(), fc_calcMeshDeformationUsingCentroid(), fc_calcMeshDeformationUsingRefVertex(), fc_calcSquaredEuclideanDistance(), fc_centeredWindowAverage(), fc_centeredWindowAverage_Time(), fc_changeDatasetName(), fc_changeMeshEntityType(), fc_changeMeshName(), fc_changeSeqSubsetName(), fc_changeSequenceName(), fc_changeSeqVariableName(), fc_changeSubsetName(), fc_changeVariableName(), fc_clearShape(), fc_combineBoundingBoxes(), fc_computeBestMatchCorrespond(), fc_computeBestMatchNumOverlapScore(), fc_computeNumOverlapScore(), fc_computeSimpleCorrespond(), fc_constOperatorSeqVar(), fc_constOperatorVar(), fc_convertIntArrayToSortedIntArray(), fc_convertSeqSubsetToSubsets(), fc_convertSortedIntArrayToIntArray(), fc_convertSubsetsToSeqSubset(), fc_convertVariablesToSeqVariable(), fc_copyDataset(), fc_copyGlobalSeqVariable(), fc_copyGlobalVariable(), fc_copyMesh(), fc_copySeqSubset(), fc_copySequence(), fc_copySeqVariable(), fc_copySeqVariableStepFromRegionMesh(), fc_copySeqVariableWithNewAssociation(), fc_copyShape(), fc_copySortedIntArray(), fc_copySubset(), fc_copySubsetWithNewAssociation(), fc_copyVariable(), fc_copyVariableFromRegionMesh(), fc_copyVariableToRegionMesh(), fc_copyVariableWithNewAssociation(), fc_createBoundingBoxMesh(), fc_createComponentSeqVariables(), fc_createComponentVariables(), fc_createDataset(), fc_createDescendingAreaOrder(), fc_createDisplacedMeshVertexBin(), fc_createFeatureGroup(), fc_createGlobalSeqVariable(), fc_createGlobalVariable(), fc_createIntArrayFromMask(), fc_createIntersectingRangeRegularSequence(), fc_createIntersectingRegularSequence(), fc_createLargeAndNonAdjacentSidesOrder(), fc_createLargeAndOpposingSidesOrder(), fc_createMagnitudeVariable(), fc_createMaskFromIntArray(), fc_createMesh(), fc_createMeshVertexBin(), fc_createNormalTangentVariables(), fc_createNormalTangentVariables2(), fc_createRegularSequence(), fc_createScrewShapeOrder(), fc_createSeqSubset(), fc_createSequence(), fc_createSeqVariable(), fc_createSideAdjacencyMatrix(), fc_createSimpleHexMesh(), fc_createSphereMesh(), fc_createStressPressureVariables(), fc_createSubset(), fc_createSubsetComplement(), fc_createSubsetIntersection(), fc_createSubsetMesh(), fc_createThresholdRangeSubset(), fc_createThresholdSubset(), fc_createVariable(), fc_deleteArrayMembersFromSubset(), fc_deleteDataset(), fc_deleteMaskMembersFromSubset(), fc_deleteMemberFromSubset(), fc_deleteMesh(), fc_deleteSeqSubset(), fc_deleteSequence(), fc_deleteSeqVariable(), fc_deleteSubset(), fc_deleteVariable(), fc_dimensionlessAreaBetweenCurves(), fc_displacedGeomSmoothSeqVariable(), fc_doesElementContainPoint(), fc_doSubsetsIntersect(), fc_euclideanDistanceBetweenCurves(), fc_evalPrestoSpotWeld(), fc_featureGroup_continueFeature(), fc_featureGroup_getFeatureIDsInStep(), fc_featureGroup_getNumFeature(), fc_featureGroup_getNumFeatureInStep(), fc_featureGroup_getNumROI(), fc_featureGroup_getNumStep(), fc_featureGroup_getROIsInStep(), fc_featureGroup_newFeature(), fc_featureGroup_noFeaturesThisStep(), fc_featureGroup_setParentChildPair(), fc_firstDerivative_REA(), fc_freeShape(), fc_geomSmoothSeqVariable(), fc_getBoundingBoxesOverlap(), fc_getClosestSequenceValue(), fc_getDatasetByName(), fc_getDatasetFileIOType(), fc_getDatasetFromMesh(), fc_getDatasetFromSequence(), fc_getDatasetFromVariable(), fc_getDatasetName(), fc_getDatasets(), fc_getDecayedShapeSides(), fc_getDecayedShapeSkin(), fc_getDecayedSkin(), fc_getDisplacedEdgeLengths(), fc_getDisplacedFaceAreas(), fc_getDisplacedMeshBoundingBox(), fc_getDisplacedMeshCentroid(), fc_getDisplacedMeshCoords(), fc_getDisplacedMeshDiameter(), fc_getDisplacedMeshesDiameter(), fc_getDisplacedMeshVolume(), fc_getDisplacedRegionVolumes(), fc_getDisplacedSubsetBoundingBox(), fc_getDisplacedSubsetCentroid(), fc_getDisplacedSubsetDiameter(), fc_getDisplacedSubsetsDiameter(), fc_getDisplacedSubsetVolume(), fc_getDisplacedSurfaceNormals(), fc_getEdgeLengths(), fc_getElementsThatContainPoint(), fc_getElementsThatContainPointFromSubset(), fc_getEntitiesWithinBoundingBox(), fc_getEntitiesWithinSphere(), fc_getExposedSkin(), fc_getFaceAreas(), fc_getFeatureChildIDs(), fc_getFeatureNumChild(), fc_getFeatureNumParent(), fc_getFeatureNumROI(), fc_getFeatureParentIDs(), fc_getFeatureROIAtStep(), fc_getFeatureROIs(), fc_getGlobalSeqVariableByName(), fc_getGlobalSeqVariables(), fc_getGlobalVariableByName(), fc_getGlobalVariables(), fc_getMeshBoundingBox(), fc_getMeshByName(), fc_getMeshCentroid(), fc_getMeshCoordsAsVariable(), fc_getMeshCoordsPtr(), fc_getMeshDiameter(), fc_getMeshDim(), fc_getMeshEdgeConnsPtr(), fc_getMeshEdgeFaceInfo(), fc_getMeshElementConnsPtr(), fc_getMeshElementFaceOrientsPtr(), fc_getMeshElementToEdgeConnsPtr(), fc_getMeshElementToFaceConnsPtr(), fc_getMeshElementType(), fc_getMeshEntityChildren(), fc_getMeshEntityNeighbors(), fc_getMeshEntityParents(), fc_getMeshes(), fc_getMeshesDiameter(), fc_getMeshFaceConnsPtr(), fc_getMeshFaceType(), fc_getMeshFaceTypesPtr(), fc_getMeshFromSubset(), fc_getMeshFromVariable(), fc_getMeshInfo(), fc_getMeshName(), fc_getMeshNumEdge(), fc_getMeshNumElement(), fc_getMeshNumEntity(), fc_getMeshNumFace(), fc_getMeshNumVertex(), fc_getMeshShapes(), fc_getMeshSkin(), fc_getMeshTopodim(), fc_getMeshVolume(), fc_getNumDataset(), fc_getNumGlobalSeqVariable(), fc_getNumGlobalVariable(), fc_getNumMesh(), fc_getNumSeqSubset(), fc_getNumSequence(), fc_getNumSeqVariable(), fc_getNumSubset(), fc_getNumVariable(), fc_getOrGenerateUniqueSeqVariableByName(), fc_getOrGenerateUniqueVariableByName(), fc_getPlanarSideNormal(), fc_getRegionVolumes(), fc_getSeqSubsetByName(), fc_getSeqSubsets(), fc_getSequenceByName(), fc_getSequenceCoordsAsDataType(), fc_getSequenceCoordsPtr(), fc_getSequenceDataType(), fc_getSequenceFromSeqSubset(), fc_getSequenceFromSeqVariable(), fc_getSequenceInfo(), fc_getSequenceMinMaxMono(), fc_getSequenceName(), fc_getSequenceNumStep(), fc_getSequences(), fc_getSequenceSpacingMinMaxMeanSdev(), fc_getSeqVariableByName(), fc_getSeqVariableComponentsByName(), fc_getSeqVariableDataPointSlice(), fc_getSeqVariableDataPointSliceAsSeqVariable(), fc_getSeqVariableMeanSdev(), fc_getSeqVariableMinMax(), fc_getSeqVariables(), fc_getSeqVariableSeriesMeanSdev(), fc_getSeqVariableSeriesMinMax(), fc_getSeqVariableSeriesSum(), fc_getShapeEnds(), fc_getShapeSidesAreas(), fc_getShapeSidesDecayType(), fc_getSideNormalMeanSdev(), fc_getSortedBlobArrayBlobs(), fc_getSortedBlobArrayNumBlob(), fc_getSortedIntArrayBack(), fc_getSortedIntArrayFront(), fc_getSortedIntArrayNumValue(), fc_getSortedIntArrayValues(), fc_getSortedIntArrayValuesInInsertOrder(), fc_getSubsetArea(), fc_getSubsetAssociationType(), fc_getSubsetBoundingBox(), fc_getSubsetByName(), fc_getSubsetCentroid(), fc_getSubsetDecayType(), fc_getSubsetDiameter(), fc_getSubsetInfo(), fc_getSubsetMaxNumMember(), fc_getSubsetMembersAsArray(), fc_getSubsetMembersAsMask(), fc_getSubsetName(), fc_getSubsetNeighbors(), fc_getSubsetNumMember(), fc_getSubsets(), fc_getSubsetsDiameter(), fc_getSubsetShapes(), fc_getSubsetSkin(), fc_getSubsetVolume(), fc_getSurfaceNormals(), fc_getVariableAssociationType(), fc_getVariableByName(), fc_getVariableComponentsByName(), fc_getVariableDataAsDataType(), fc_getVariableDataPtr(), fc_getVariableDataType(), fc_getVariableInfo(), fc_getVariableMathType(), fc_getVariableMeanSdev(), fc_getVariableMinMax(), fc_getVariableName(), fc_getVariableNumComponent(), fc_getVariableNumDataPoint(), fc_getVariables(), fc_getVariableSubsetMeanSdev(), fc_getVariableSubsetMinMax(), fc_getVariableSubsetSum(), fc_getVariableSum(), fc_getVariableWeightedDisplacedMeshCentroid(), fc_getVariableWeightedDisplacedSubsetCentroid(), fc_getVariableWeightedMeshCentroid(), fc_getVariableWeightedSubsetCentroid(), fc_groupSelfCorrespond(), fc_initShape(), fc_initSortedBlobArray(), fc_initSortedIntArray(), fc_integral_TR(), fc_isMemberInSubset(), fc_isSubsetSuperset(), fc_isValidDisplacementVariable(), fc_isVariableGlobal(), fc_leadingWindowAverage(), fc_leadingWindowAverage_Time(), fc_linearInterpolation(), fc_linearLeastSquares(), fc_loadDatasetWithFormat(), fc_mergeComponentSeqVariables(), fc_mergeComponentVariables(), fc_normalForm(), fc_operatorSeqVar(), fc_operatorVar(), fc_parseSierraInputFile(), fc_popSortedIntArrayBack(), fc_popSortedIntArrayFront(), fc_printDataset(), fc_printFeatureGraph(), fc_printFeatureGroup(), fc_printMesh(), fc_printSeqSubsetRange(), fc_printSeqVariableRange(), fc_printShape(), fc_printSierraInfo(), fc_printSortedIntArray(), fc_printSubset(), fc_printSubsetOfMesh(), fc_printSubsetOfVariable(), fc_printVariable(), fc_projectedElementBoundingBoxIntersection(), fc_projectedSubsetElementBoundingBoxIntersection(), fc_reduceShapeNumSides(), fc_releaseDataset(), fc_releaseMesh(), fc_releaseSeqSubset(), fc_releaseSequence(), fc_releaseSeqVariable(), fc_releaseSubset(), fc_releaseVariable(), fc_reorderShape(), fc_reshapeByAngle(), fc_rewriteDataset(), fc_segment(), fc_segmentAdjacencyMatrix(), fc_seqConstOperatorSeqVar(), fc_seqVarBinaryFunctionConstSeqVar(), fc_seqVarBinaryFunctionSeqConstSeqVar(), fc_seqVarBinaryFunctionSeqVarConst(), fc_seqVarBinaryFunctionSeqVarSeqConst(), fc_seqVarBinaryFunctionSeqVarSeqVar(), fc_seqVarBinaryFunctionSeqVarVar(), fc_seqVarBinaryFunctionVarSeqVar(), fc_seqVarOperatorConst(), fc_seqVarOperatorSeqConst(), fc_seqVarOperatorSeqVar(), fc_seqVarOperatorVar(), fc_seqVarUnaryFunction(), fc_setMeshCoords(), fc_setMeshCoordsPtr(), fc_setMeshElementConns(), fc_setMeshElementConnsPtr(), fc_setSequenceCoords(), fc_setSequenceCoordsPtr(), fc_setSphereDisplacementVariable(), fc_setVariableData(), fc_setVariableDataPtr(), fc_shiftAndScaleSequence(), fc_sortIntArray(), fc_squeezeSortedBlobArray(), fc_squeezeSortedIntArray(), fc_subsetPlusNeighborGreaterSegmentationMesh(), fc_subsetSegmentsMesh(), fc_subsetSegmentsSubset(), fc_trackAllSteps_custom(), fc_trackStep_custom(), fc_varBinaryFunctionConstVar(), fc_varBinaryFunctionVarConst(), fc_varBinaryFunctionVarVar(), fc_varOperatorConst(), fc_varOperatorSeqVar(), fc_varOperatorVar(), fc_varUnaryFunction(), fc_writeDataset(), fc_writeFeatureGraph(), fc_writeFeatureGroup(), getLinesAsVectors(), grow_tears(), main(), parseDeathVarSet(), and parser().
{
    switch(rc) {
      case FC_SUCCESS:          return "FC_SUCCESS";
      case FC_ERROR:            return "FC_ERROR";
      case FC_MEMORY_ERROR:     return "FC_MEMORY_ERROR";
      case FC_INPUT_ERROR:      return "FC_INPUT_ERROR";
      case FC_FILE_IO_ERROR:    return "FC_FILE_IO_ERROR";
      // no default case so will get warning if new values added to enum
    }
    return NULL;
}
char* fc_getVerbosityLevelText (FC_VerbosityLevel verbosity)
Return the name of the FC_VerbosityLevel's value.
Description:
Returns a string representing the name of the enum value or NULL is the enum value is invalid. The string should NOT be freed.
Modifications:
3/30/04 WSK, Created
Definition at line 328 of file base.c.
References FC_DEBUG_MESSAGES, FC_ERROR_MESSAGES, FC_LOG_MESSAGES, FC_QUIET, and FC_WARNING_MESSAGES.
Referenced by fc_setLibraryVerbosity().
{
  switch(verbosity) {
  case FC_QUIET:             return "FC_QUIET";
  case FC_ERROR_MESSAGES:    return "FC_ERROR_MESSAGES";
  case FC_WARNING_MESSAGES:  return "FC_WARNING_MESSAGES";
  case FC_LOG_MESSAGES:      return "FC_LOG_MESSAGES";
  case FC_DEBUG_MESSAGES:    return "FC_DEBUG_MESSAGES";
  // no default case so will get warning if new values added to enum
  }
  return NULL;
}
int fc_isAssociationTypeValid (FC_AssociationType assoc)
Verify that the given value is valid for this enum.
Modifications:
8/18/04 WSK, Created
Definition at line 286 of file base.c.
References FC_AT_EDGE, FC_AT_ELEMENT, FC_AT_FACE, FC_AT_UNKNOWN, FC_AT_VERTEX, FC_AT_WHOLE_DATASET, and FC_AT_WHOLE_MESH.
Referenced by _fc_buildMeshElementNeighborsViaEntity(), _fc_buildParents(), _fc_getEdgeParents(), _fc_getVertexParents(), _fc_writeExodusDataset(), fc_changeMeshEntityType(), fc_copySubsetWithNewAssociation(), fc_createSeqSubset(), fc_createSubset(), fc_getEntitiesWithinBoundingBox(), fc_getEntitiesWithinSphere(), fc_getMeshEntityChildren(), fc_getMeshEntityElementType(), fc_getMeshEntityNeighbors(), fc_getMeshEntityParents(), fc_getMeshNumEntity(), fc_getSubsetSkin(), fc_setVariableData(), and fc_setVariableDataPtr().
{
  switch (assoc) {
  case FC_AT_UNKNOWN:  // fall through
  case FC_AT_VERTEX:   // fall through
  case FC_AT_EDGE:     // fall through
  case FC_AT_FACE:     // fall through
  case FC_AT_ELEMENT:  // fall through
  case FC_AT_WHOLE_MESH:    // fall through
  case FC_AT_WHOLE_DATASET: // fall through
  // no default case so will get warning if new values added to enum
    return 1;
  }
  return 0;
}
int fc_isDataTypeValid (FC_DataType dataType)
Verify that the given value is valid for this enum.
Modifications:
8/18/04 WSK, Created
Definition at line 240 of file base.c.
References FC_DT_CHAR, FC_DT_DOUBLE, FC_DT_FLOAT, FC_DT_INT, and FC_DT_UNKNOWN.
Referenced by fc_constOperatorSeqVar(), fc_constOperatorVar(), fc_getSequenceCoordsAsDataType(), fc_getVariableDataAsDataType(), fc_getVariableWeightedDisplacedMeshCentroid(), fc_getVariableWeightedDisplacedSubsetCentroid(), fc_getVariableWeightedMeshCentroid(), fc_getVariableWeightedSubsetCentroid(), fc_seqConstOperatorSeqVar(), fc_seqVarBinaryFunctionSeqConstSeqVar(), fc_seqVarBinaryFunctionSeqVarSeqConst(), fc_seqVarOperatorConst(), fc_seqVarOperatorSeqConst(), fc_setSequenceCoords(), fc_setSequenceCoordsPtr(), fc_setVariableData(), fc_setVariableDataPtr(), fc_varOperatorConst(), and myCharacterizationFunkyAve().
{
  switch (dataType) {
  case FC_DT_UNKNOWN:  // fall through
  case FC_DT_CHAR:     // fall through
  case FC_DT_INT:      // fall through
  case FC_DT_FLOAT:    // fall through
  case FC_DT_DOUBLE:   // fall through
  // no default case so will get warning if new values added to enum
    return 1;
  }
  return 0;
}
int fc_isElementTypeValid (FC_ElementType elemType)
Verify that the given value is valid for this enum.
Modifications:
8/18/04 WSK, Created
Definition at line 212 of file base.c.
References FC_ET_HEX, FC_ET_LINE, FC_ET_MIXED, FC_ET_POINT, FC_ET_PRISM, FC_ET_PYRAMID, FC_ET_QUAD, FC_ET_TET, FC_ET_TRI, and FC_ET_UNKNOWN.
Referenced by fc_setMeshElementConns(), and fc_setMeshElementConnsPtr().
{
  switch(elemType) {
  case FC_ET_UNKNOWN:  // fall through
  case FC_ET_POINT:    // fall through
  case FC_ET_LINE:     // fall through
  case FC_ET_TRI:      // fall through
  case FC_ET_QUAD:     // fall through
  case FC_ET_TET:      // fall through
  case FC_ET_PYRAMID:  // fall through
  case FC_ET_PRISM:    // fall through
  case FC_ET_HEX:      // fall through
  case FC_ET_MIXED:    // fall through
  // no default case so will get warning if new values added to enum
    return 1;
  }
  return 0;
}
int fc_isMathTypeValid (FC_MathType mathtype)
Verify that the given value is valid for this enum.
Modifications:
8/18/04 WSK, Created
Definition at line 263 of file base.c.
References FC_MT_SCALAR, FC_MT_SYMTENSOR, FC_MT_TENSOR, FC_MT_UNKNOWN, and FC_MT_VECTOR.
Referenced by _fc_createExoVarCompName(), fc_mergeComponentSeqVariables(), fc_mergeComponentVariables(), fc_setVariableData(), and fc_setVariableDataPtr().
{
  switch (mathtype) {
  case FC_MT_UNKNOWN:    // fall through
  case FC_MT_SCALAR:     // fall through
  case FC_MT_VECTOR:     // fall through
  case FC_MT_SYMTENSOR:  // fall through
  case FC_MT_TENSOR:     // fall through
  // no default case so will get warning if new values added to enum
    return 1;
  }
  return 0;
}
int fc_isReturnCodeValid (FC_ReturnCode rc)
Verify that the given value is valid for this enum.
Modifications:
8/18/04 WSK, Created
Parameters:
rc input - enum to return printable string for
Definition at line 189 of file base.c.
References FC_ERROR, FC_FILE_IO_ERROR, FC_INPUT_ERROR, FC_MEMORY_ERROR, and FC_SUCCESS.
{
  switch(rc) {
  case FC_SUCCESS:        // fall through
  case FC_ERROR:          // fall through
  case FC_MEMORY_ERROR:   // fall through
  case FC_INPUT_ERROR:    // fall through
  case FC_FILE_IO_ERROR:  // fall through
  // no default case so will get warning if new values added to enum
    return 1;
  }
  return 0;
}
int fc_isVerbosityLevelValid (FC_VerbosityLevel verbosity)
Verify that the given value is valid for this enum.
Modifications:
8/18/04 WSK, Created
Definition at line 166 of file base.c.
References FC_DEBUG_MESSAGES, FC_ERROR_MESSAGES, FC_LOG_MESSAGES, FC_QUIET, and FC_WARNING_MESSAGES.
Referenced by fc_setLibraryVerbosity().
{
  switch(verbosity) {
  case FC_QUIET:             // fall through
  case FC_ERROR_MESSAGES:    // fall through
  case FC_WARNING_MESSAGES:  // fall through
  case FC_LOG_MESSAGES:      // fall through
  case FC_DEBUG_MESSAGES:    // fall through
  // no default case so will get warning if new values added to enum
    return 1;
  }
  return 0;
}
int fc_sizeofDataType (FC_DataType dataType)
Returns the number of bytes in an FC_DataType, like sizeof().
Description:
Returns the size (number of bytes) of a data type. If the type is unknown (FC_DT_UNKNOWN), -1 is returned.
Modifications:
Nancy Collins Created.
2003-NOV-17 WSK Changed to return the number of bytes instead of passing back out in argument list. Also asks system for size instead of hard coding.
Definition at line 741 of file base.c.
References FC_DT_CHAR, FC_DT_DOUBLE, FC_DT_FLOAT, FC_DT_INT, FC_DT_UNKNOWN, and fc_printfWarningMessage.
Referenced by _fc_readLSDynaVariableData(), fc_copyDataset(), fc_copyMesh(), fc_createComponentVariables(), fc_createSubsetMesh(), fc_getSequenceCoordsAsDataType(), fc_getSeqVariableDataPointSlice(), fc_getVariableDataAsDataType(), fc_mergeComponentVariables(), fc_setSequenceCoords(), and fc_setVariableData().
{
  switch (dataType) {
  case FC_DT_UNKNOWN: return -1;
  case FC_DT_CHAR:    return sizeof(char);
  case FC_DT_INT:     return sizeof(int);
  case FC_DT_FLOAT:   return sizeof(float);
  case FC_DT_DOUBLE:  return sizeof(double);
  // no default case so will get warning if new values added to enum
  }
  fc_printfWarningMessage(
     "Warning: invalid value for enum FC_DataType");
  return -1;
}