FCLib: (Private)
(Private)
[Geometric Relations]
Diameter helpers
FC_ReturnCode _fc_getDiameterOutputArgsTest (double *diameter, int *numPair, int **pairIDs)
Helper for 'getDiameter' routines.
FC_ReturnCode _fc_getDiameterOutputArgsTestMeshes (double *diameter, int *numPair, int **pairIDs, FC_Mesh **pairMeshes)
Helper for 'getDiameter' routines.
FC_ReturnCode _fc_getDiameterOutputArgsTestSubsets (double *diameter, int *numPair, int **pairIDs, FC_Subset **pairSubsets)
Helper for 'getDiameter' routines.
FC_ReturnCode _fc_getSubsetDiameterCore (FC_Subset subset, FC_Variable *displ, double *diameter, int *numPair, int **pairIDs)
Core code of 'getDiameter' routines.
FC_ReturnCode _fc_getSubsetsDiameterCore (int numSubset, FC_Subset *subsets, FC_Variable *displs, double *diameter, int *numPair, int **pairIDs, FC_Subset **pairSubsets)
Core code of 'getDiameter' routines.
Proximity helpers
FC_ReturnCode _fc_getSubsetsProximityArgsTest (FC_Mesh *mesh1, FC_Subset *subset1, FC_Variable *displ1, FC_Mesh *mesh2, FC_Subset *subset2, FC_Variable *displ2, double min_dist, int *numPair, int **mesh1VertIDs, int **mesh2VertIDs)
Common argument testing for all proximity routines.
FC_ReturnCode _fc_getSubsetsProximityCore (FC_Subset subset1, FC_Variable *displ1, FC_Subset subset2, FC_Variable *displ2, double min_dist, int *numPair_p, int **mesh1VertIDs_p, int **mesh2VertIDs_p)
Return the proximal vertices between two displaced subsets.
Range query helpers
FC_ReturnCode _fc_createVertexBinCore (int numVertex, int numDim, double *coords, FC_Coords lowers, FC_Coords uppers, FC_VertexBin **bin_p)
Create spatial bins for vertices for geometric queries.
FC_ReturnCode _fc_getVertexIDsWithinBoundingBoxUsingVertexBin (FC_Mesh mesh, FC_VertexBin *bin, FC_Coords lowpoint, FC_Coords highpoint, int *numVertex_p, int **vertexIDs_p)
Find all vertices within a bounding box.
FC_ReturnCode _fc_getVertexIDsWithinSphereUsingVertexBin (FC_Mesh mesh, FC_VertexBin *bin, FC_Coords center, double radius, int *numVertex_p, int **vertexIDs_p)
Find all vertices within a given radius of a point.
FC_ReturnCode _fc_geomSmoothCore (int numMesh, FC_Mesh *meshes, int doDispl, FC_Variable *displs, FC_VertexBin **bins, FC_Variable *vars, double radius, int doLocalSmooth, FC_Variable **smooth_vars)
Smooth a variable field.
Normals helpers
void _fc_calcSurfaceNormal (int numPoint, FC_Coords *coords, FC_Vector *normal)
Compute unit normal of surface.
Math helpers
double _fc_calcDeterminant2x2 (double a1, double a2, double b1, double b2)
Calculate determinant of a 2x2 matrix.
double _fc_calcDeterminant3x3 (double a1, double a2, double a3, double b1, double b2, double b3, double c1, double c2, double c3)
Calculate determinant of a 3x3 matrix.
Parameterization helpers
void _fc_calcQuadParams (FC_Coords *vertices, FC_Coords point, int *numParam, double **params)
Compute parameterization of a point on a quad.
void _fc_calcQuadLocation (FC_Coords *vertices, int numParam, double *params, FC_Coords *point)
Compute parameterization of a point on a quad.
Mesh entities' measurement helpers
void _fc_calcTriArea (int numDim, FC_Coords *vertices, double *area)
Compute surface area of a triangle.
void _fc_calcQuadArea (int numDim, FC_Coords *vertices, double *area)
Compute surface area of a quadrilateral.
void _fc_calcTetVolume (FC_Coords *vertices, double *volume)
Compute volume of a tetrahedron.
void _fc_calcPyramidVolume (FC_Coords *vertices, double *volume)
Compute volume of a pyramid.
void _fc_calcPrismVolume (FC_Coords *vertices, double *volume)
Compute volume of a prism.
void _fc_calcHexVolume (FC_Coords *vertices, double *volume)
Compute volume of a hex.
Functions
FC_ReturnCode _fc_doesElementContainPoint (FC_Mesh mesh, int element_id, double point[3], int dim, int max_num_vert_per_face, int *num_vert_per_face, int *face_conns, double *vert_coords, int *hit_type)
Internal function for determining whether a point is located within an element.
Function Documentation
double _fc_calcDeterminant2x2 (double a1, double a2, double b1, double b2)
Calculate determinant of a 2x2 matrix.
Description:
Input is by rows (top row, then bottom row).
Modifications:
08/23/04 WSK created.
Definition at line 6957 of file geom.c.
Referenced by _fc_calcDeterminant3x3().
{
  return a1*b2 - a2*b1;
}
double _fc_calcDeterminant3x3 (double a1, double a2, double a3, double b1, double b2, double b3, double c1, double c2, double c3)
Calculate determinant of a 3x3 matrix.
Description:
Input is by rows (top row, middle row, etc).
Modifications:
08/23/04 WSK created.
Definition at line 6973 of file geom.c.
References _fc_calcDeterminant2x2().
Referenced by _fc_calcTetVolume().
{
  return (  a1 * _fc_calcDeterminant2x2(b2, b3, c2, c3)
          - b1 * _fc_calcDeterminant2x2(a2, a3, c2, c3)
          + c1 * _fc_calcDeterminant2x2(a2, a3, b2, b3) );
}
void _fc_calcHexVolume (FC_Coords * vertices, double * volume)
Compute volume of a hex.
Description:
Provide array of vertex coords and get the volume back.
Probably only works if the hex is convex.
Implementation. Divides the hex into 5 tets and sum their volumes. Probably only accurate if square faces are convex and planar.
Modifications:
8/23/04 WSK Created
Parameters:
vertices input - the coordinates of the tri
volume output - region volume
Definition at line 7456 of file geom.c.
References _fc_calcTetVolume().
Referenced by fc_getDisplacedRegionVolumes(), and fc_getRegionVolumes().
  {
  int i, j, k;
  int numDim = 3;
  FC_Coords coords[4];
  int lookup[5][4] = { { 0, 1, 2, 5 }, { 0, 2, 3, 7 }, { 0, 5, 7, 4 },
                       { 2, 7, 5, 6 }, { 0, 5, 2, 7 } };
  double temp_vol;
  *volume = 0.0;
  for (i = 0; i < 5; i++) {
    // get coords for tet i
    for (j = 0; j < 4; j++)
      for (k = 0; k < numDim; k++)
        coords[j][k] = vertices[lookup[i][j]][k];
    // add volume for tet i
    _fc_calcTetVolume(coords, &temp_vol);
    *volume += temp_vol;
  }
  return;
}
void _fc_calcPrismVolume (FC_Coords * vertices, double * volume)
Compute volume of a prism.
Description:
Provide array of six vertex coords and get the volume back.
Implementation. Divides the prism into 3 tets and sums their volumes. Probably only accurate if square faces are convex and planar.
Modifications:
8/24/04 WSK Created
Parameters:
vertices input - the coordinates of the tri
volume output - region volume
Definition at line 7416 of file geom.c.
References _fc_calcTetVolume().
Referenced by fc_getDisplacedRegionVolumes(), and fc_getRegionVolumes().
  {
  int i, j, k;
  int numDim = 3;
  FC_Coords coords[4];
  int lookup[3][4] = { { 0, 1, 2, 3 }, { 1, 4, 2, 3 }, { 2, 4, 5, 3 } };
  double temp_vol;
  *volume = 0.0;
  for (i = 0; i < 3; i++) {
    // get coords for tet i
    for (j = 0; j < 4; j++)
      for (k = 0; k < numDim; k++)
        coords[j][k] = vertices[lookup[i][j]][k];
    // add volume for tet i
    _fc_calcTetVolume(coords, &temp_vol);
    *volume += temp_vol;
  }
  return;
}
void _fc_calcPyramidVolume (FC_Coords * vertices, double * volume)
Compute volume of a pyramid.
Description:
Provide array of five vertex coords and get the volume back (the tip of the pyramid is the last last vertex).
Implementation. Divides the pyramid into 2 tets and sum their volumes. Only accurate if square face is planar.
Modifications:
8/24/04 WSK Created
Parameters:
vertices input - the coordinates of the tri
volume output - region volume
Definition at line 7375 of file geom.c.
References _fc_calcTetVolume().
Referenced by fc_getDisplacedRegionVolumes(), and fc_getRegionVolumes().
  {
  // Note, if the square face is not concave, this works no matter which
  // way you split the tet's because if you split "wrong" you get a positve
  // and negative tet volume that add up to the right answer. I think.
  int i, j, k;
  int numDim = 3;
  FC_Coords coords[4];
  int lookup[2][4] = { { 0, 1, 3, 4 }, { 1, 2, 3, 4 } };
  double temp_vol;
  *volume = 0.0;
  for (i = 0; i < 2; i++) {
    // get coords for tet i
    for (j = 0; j < 4; j++)
      for (k = 0; k < numDim; k++)
        coords[j][k] = vertices[lookup[i][j]][k];
    // add volume for tet i
    _fc_calcTetVolume(coords, &temp_vol);
    *volume += temp_vol;
  }
  return;
}
void _fc_calcQuadArea (int numDim, FC_Coords * vertices, double * area)
Compute surface area of a quadrilateral.
Description:
Provide array of vertex coords and get the area back. Note that if the coords are 2D, the last entry of FC_Coords should be 0.
This routine works for planar convex and planar nonconvex quads. (Will return results for non-planar quads, but behavior may not be what you want).
Basic procedure: divide the quad into two triangles and sum the areas of those triangles. There are two possible ways to divide a quad into triangles. This choice is important for non-convex quads and it should be chosen so that the shared edge falls within the quad. However, figuring out which way to divide quads is difficult. Instead, the procedure is to calculate the quad area for both divisions and then to choose the smaller area (the wrong division for a non-convex quad would double count area outside of the quad).
Modifications:
8/23/04 WSK Created
Parameters:
numDim input - the dimensionality of coordinates
vertices input - the coordinates of the tri
area output - surface area
Definition at line 7296 of file geom.c.
References _fc_calcTriArea().
Referenced by fc_getDisplacedFaceAreas(), and fc_getFaceAreas().
  {
  int i, j, k;
  FC_Coords coords[4][3];
  int lookup[4][3] = { { 0, 1, 2 }, { 0, 2, 3 }, { 0, 1, 3 }, { 1, 2, 3 } };
  double area_tri1, area_tri2, area1, area2;
  // setup triangles
  for (i = 0; i < 4; i++) {
    for (j = 0; j < 3; j++) {
      for (k = 0; k < numDim; k++) {
        coords[i][j][k] = vertices[lookup[i][j]][k];
      }
    }
  }
  _fc_calcTriArea(numDim, coords[0], &area_tri1);
  _fc_calcTriArea(numDim, coords[1], &area_tri2);
  area1 = area_tri1 + area_tri2;
  _fc_calcTriArea(numDim, coords[2], &area_tri1);
  _fc_calcTriArea(numDim, coords[3], &area_tri2);
  area2 = area_tri1 + area_tri2;
  // return smaller area
  if (area1 < area2)
    *area = area1;
  else
    *area = area2;
  return;
}
void _fc_calcQuadLocation (FC_Coords * vertices, int numParam, double * params, FC_Coords * point)
Compute parameterization of a point on a quad.
Description:
Given a point on a quad, computes the parameterization location (in u & v) of that point. Combined with fc_calcQuadLocation, it can be used to find the location of a point on a quad that has been moved or distorted.
I.e. given an initial quad and a point in xyz space, the points' relative position in the quad can determined as the parameters u and v. If the quad's vertices' coordinates change. The new xzy coordinates of the point can be determined from u and v and the new quad's coordinates. See fc_calcQuadLocation.
Assumes that the quad is planar. Code is based on implementation in VTK (visualization toolkit). Somebody should probably check the theoretics ....
Modifications:
2003-SEP-04 Wendy Koegler Created.
Parameters:
vertices input - the coordinates of the vertices of the quad
numParam input - the number of params
params input - the parameters of the point
point output - 3d coordinates of the point
Definition at line 7177 of file geom.c.
Referenced by fc_evalPrestoSpotWeld(), and main().
  {
  int i, j;
  double params_m[2];
  double weights[4];
  // FIX? default value?
  if (numParam != 2)
    return;
  // intermediate calcs
  params_m[0] = 1. - params[0];
  params_m[1] = 1. - params[1];
  weights[0] = params_m[0] * params_m[1];
  weights[1] =   params[0] * params_m[1];
  weights[2] =   params[0] *   params[1];
  weights[3] = params_m[0] *   params[1];
  for (i = 0; i < 3; i++)
    (*point)[i] = 0;
  for (i = 0; i < 4; i++)
    for (j = 0; j < 3; j++)
      (*point)[j] += vertices[i][j] * weights[i];
}
void _fc_calcQuadParams (FC_Coords * vertices, FC_Coords point, int * numParam, double ** params)
Compute parameterization of a point on a quad.
Description:
Given a point on a quad, computes the parameterization location (in u & v) of that point. Combined with fc_calcQuadLocation, it can be used to find the location of a point on a quad that has been moved or distorted. (If the point is not on the surface of the quad, the closest point on the surface of the quad is parameterized.)
I.e. given an initial quad and a point in xyz space, the points' relative position in the quad can determined as the parameters u and v. If the quad's vertices' coordinates change. The new xzy coordinates of the point can be determined from u and v and the new quad's coordinates. See fc_calcQuadLocation.
Although this routine returns doubles, they are only gauranted to have as many significant digits as a float.
Modifications:
2003-SEP-04 Wendy Koegler Created.
2006-09-07 WSD Clarified exit conditions.
Parameters:
vertices input - the coordinates of the vertices of the quad
point input - 3d coordinates of a point
numParam output - the number of params found (0 or 2)
params output - the parameters found
Definition at line 7013 of file geom.c.
References _fc_calcSurfaceNormal(), FC_DBL_EQUIV, fc_getReturnCodeText(), FC_MEMORY_ERROR, and fc_printfErrorMessage.
Referenced by fc_evalPrestoSpotWeld(), and main().
  {
  int i, j;
  int iter, MAX_ITER = 10;
  int converged;
  double diff[2], current[2], current_m[2];
  double fcol[2]; // solution vector
  double rcol[2], scol[2];  // columns of the Jacobian matrix
  double determinant;  // matrix determinant
  double weights[4];
  double derivs[8];
  double proj_point[3];
  FC_Vector normal;
  int indices[2];
  int maxID; // the index of the max component (which we will drop)
  double maxComponent;
  // default values
  *numParam = 0;
  *params = NULL;
  // get normal
  _fc_calcSurfaceNormal(4, vertices, &normal);
  // project point to plane of quad
  {
    double temp_point[3];
    double temp;
    // vector from point to "origin" of plane
    for (i = 0; i < 3; i++)
      temp_point[i] = point[i] - vertices[0][i];
    // compute dot product
    temp = 0;
    for (i = 0; i < 3; i++)
      temp += normal[i]*temp_point[i];
    // ??
    for (i = 0; i < 3; i++)
      proj_point[i] = point[i] - temp*normal[i];
  }
  // choose indices
  maxID = 2;
  maxComponent = fabs(normal[2]);
  for (i = 0; i < 2; i++) {
    if (fabs(normal[i]) > maxComponent) {
      maxID = i;
      maxComponent = fabs(normal[i]);
    }
  }
  j = 0;
  for (i = 0; i < 3; i++) {
    if (i != maxID) {
      indices[j] = i;
      j++;
    }
  }
  // Use Newton's method to solve for parametric coordinates
  // initial guess - starting at (0, 0) cause that can be a problem point
  current[0] = current[1] = 0;
  converged = 0;
  for (iter = 0; iter < MAX_ITER; iter++) {
    // intermediate calcs
    current_m[0] = 1. - current[0];
    current_m[1] = 1. - current[1];
    weights[0] = current_m[0] * current_m[1];
    weights[1] =   current[0] * current_m[1];
    weights[2] =   current[0] *   current[1];
    weights[3] = current_m[0] *   current[1];
    derivs[0] = -1 * current_m[1];
    derivs[1] =      current_m[1];
    derivs[2] =        current[1];
    derivs[3] = -1 *   current[1];
    derivs[4] = -1 * current_m[0];
    derivs[5] = -1 *   current[0];
    derivs[6] =        current[0];
    derivs[7] =      current_m[0];
    // calculate newton functions
    for (i = 0; i < 2; i++) {
      fcol[i] = -1 * proj_point[indices[i]];
      rcol[i] = scol[i] = 0.0;
    }
    for (i = 0; i < 4; i++) {
      for (j = 0; j < 2; j++) { // overdetermined system, only use 2 of 3 dims
        fcol[j] += vertices[i][indices[j]] * weights[i];
        rcol[j] += vertices[i][indices[j]] * derivs[i];
        scol[j] += vertices[i][indices[j]] * derivs[i+4];
      }
    }
    determinant = rcol[0]*scol[1] - scol[0]*rcol[1];
    // FIX: check, a zero determinant is bad
    diff[0] = (fcol[0]*scol[1] - scol[0]*fcol[1])/determinant;
    diff[1] = (rcol[0]*fcol[1] - fcol[0]*rcol[1])/determinant;
    // Test for exit, and set up next guess
    if (FC_DBL_EQUIV(current[0] - diff[0], current[0]) &&
     FC_DBL_EQUIV(current[1] - diff[1], current[1])) {
      converged = 1;
      break;
    }
    // guess for next round
    current[0] -= diff[0];
    current[1] -= diff[1];
  } // end of iteration
  // debug
  //printf("***iter = %d, converged = %d\n", iter, converged);
  //printf("***diff        = %.20g %.20g\n", diff[0], diff[1]);
  //printf("***params      = %.20g %.20g\n", current[0], current[1]);
  //printf("***params-diff = %.20g %.20g\n", current[0]-diff[0], current[1]-diff[1]);
  // HACK - The exit condition for the loop is very stringent
  // here we have a more relaxed condition
  if (fabs(diff[0]) < FLT_EPSILON && fabs(diff[1]) < FLT_EPSILON) {
    converged = 1;
  }
  if (converged) {
    *numParam = 2;
    *params = malloc(sizeof(double)*2);
    if ( *params == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      exit(FC_MEMORY_ERROR);
    }
    (*params)[0] = current[0];
    (*params)[1] = current[1];
  }
}
void _fc_calcSurfaceNormal (int numPoint, FC_Coords * coords, FC_Vector * normal)
Compute unit normal of surface.
Description:
This function implements Newell's method of calculating the normal of a planar polygon. It has the advantage of providing a decent estimate of a normal if the polygon is not planar.
Order of the points is important. Looking down on the plane, a counterclockwise traversal of the three points will yield a normal pointing up towards the viewer.
This routine currently assumes 3D coordinates. If you are less than 3D, pad with zeros. This can't do more than 3D.
Reference for Newell's method: Hill, Francis S, "Computer Graphics", Prentice Hall, 1990, pg 258.
Modifications:
2003-SEP-04 W Koegler Created: _fc_SurfaceNormal was split between this function and fc_getSurfaceNormals for better modularity.
11/3/04 WSK Renamed & rewritten to use Newell's method (so will find estimate of surface normal of non-planar quads).
Parameters:
numPoint input - number of points (at least 3)
coords input - array of point coordinates (at least 3)
normal output - surface normal
Definition at line 6901 of file geom.c.
References fc_printfLogMessage.
Referenced by _fc_calcQuadParams(), _fc_getOutwardFaceNormal(), fc_evalPrestoSpotWeld(), fc_getDisplacedSurfaceNormals(), fc_getSurfaceNormals(), and main().
  {
  int i;
  double *point1, *point2; // temp pointers to points
  FC_Coords temp_norm;
  double magnitude;
  // log message
  fc_printfLogMessage("Computing a normal vector.");
  // init
  temp_norm[0] = 0.;
  temp_norm[1] = 0.;
  temp_norm[2] = 0.;
  // Newell method
  for (i = 0; i < numPoint; i++) {
    point1 = coords[i];
    if (i == numPoint - 1)
      point2 = coords[0];
    else
      point2 = coords[i+1];
    temp_norm[0] += (point1[1] - point2[1])*(point1[2] + point2[2]);
    temp_norm[1] += (point1[2] - point2[2])*(point1[0] + point2[0]);
    temp_norm[2] += (point1[0] - point2[0])*(point1[1] + point2[1]);
  }
  // Convert to unit vector
  magnitude = 0;
  for (i = 0; i < 3; i++)
    magnitude += temp_norm[i]*temp_norm[i];
  magnitude = sqrt(magnitude);
  for (i = 0; i < 3; i++)
    (*normal)[i] = temp_norm[i]/magnitude;
}
void _fc_calcTetVolume (FC_Coords * vertices, double * volume)
Compute volume of a tetrahedron.
Description:
Provide array of four vertex coords and get the volume back.
Implementation taken from vtk: vtkTetra::ComputeVolume.
Modifications:
8/23/04 WSK Created
Parameters:
vertices input - the coordinates of the tri
volume output - surface area
Definition at line 7344 of file geom.c.
References _fc_calcDeterminant3x3().
Referenced by _fc_calcHexVolume(), _fc_calcPrismVolume(), _fc_calcPyramidVolume(), fc_getDisplacedRegionVolumes(), and fc_getRegionVolumes().
  {
  *volume = _fc_calcDeterminant3x3(vertices[1][0] - vertices[0][0],
                                   vertices[2][0] - vertices[0][0],
                                   vertices[3][0] - vertices[0][0],
                                   vertices[1][1] - vertices[0][1],
                                   vertices[2][1] - vertices[0][1],
                                   vertices[3][1] - vertices[0][1],
                                   vertices[1][2] - vertices[0][2],
                                   vertices[2][2] - vertices[0][2],
                                   vertices[3][2] - vertices[0][2]) / 6.0;
  return;
}
void _fc_calcTriArea (int numDim, FC_Coords * vertices, double * area)
Compute surface area of a triangle.
Description:
Provide array of three vertex coords and get the area back.
Modifications:
8/23/04 WSK Created
6/30/06 WSD Saw roundoff error w/ gcc 4 with Kahan's algorithm, switched back to Heron's which works fine.
Parameters:
numDim input - the dimensionality of coordinates
vertices input - the coordinates of the tri
area output - surface area
Definition at line 7227 of file geom.c.
References fc_calcSquaredEuclideanDistance().
Referenced by _fc_calcQuadArea(), fc_getDisplacedFaceAreas(), and fc_getFaceAreas().
  {
  double a2, b2, c2;
  //double a, b, c, da, db, dc;
  // get lengths of sides of triangle
  fc_calcSquaredEuclideanDistance(vertices[0], vertices[1], numDim, &a2);
  fc_calcSquaredEuclideanDistance(vertices[1], vertices[2], numDim, &b2);
  fc_calcSquaredEuclideanDistance(vertices[2], vertices[0], numDim, &c2);
  // A version of Heron's formula
  *area = 0.25 * sqrt(fabs(4.0*a2*c2 - (a2-b2+c2)*(a2-b2+c2)));
  // Not used: found lacking on 6/30/06 by WSD. Switch back to old formula
  // This formula is from pdf found on the web:
  // http://www.cs.berkeley.edu/~wkahan/VtetLang.pdf
  // "What has the Volume of a Tetrahedron to do with Computer
  // Programming Languages?"
  // by Prof. W. Kahan, Math Dept & EE & CS Dept at Berkeley
  //
  // It is supposed to be more accurate in terms of roundoff error
  // than the typical Heron's formula and other methods.
  /*
  if (b > c)
    da = (b - a) + c;
  else
    da = (c - a) + b;
  if (a > c)
    db = (a - b) + c;
  else
    db = (c - b) + a;
  if (a > b)
    dc = (a - c) + b;
  else
    dc = (b - c) + a;
  *area = 0.25 * sqrt((a+b+c)*da*db*dc);
  */
  return;
}
FC_ReturnCode _fc_createVertexBinCore (int numVertex, int numDim, double * coords, FC_Coords lowers, FC_Coords uppers, FC_VertexBin ** bin_p)
Create spatial bins for vertices for geometric queries.
Description:
Create an FC_VertexBin to use for geometric queries. The user is responsible for freeing the created FC_VertexBin by calling fc_freeVertexBin().
The algorithm attempts to create bins of roughly equal width in each dimension, and that hold on average about 1 vertex each. Given the Widths of the bounding box of the mesh (Wx,Wy,Wz) and the number of vertices (numVertex) and our requirement of one vertex per bin we can write a conservation of vertices:
Wx * Wy * Wz ~ (Wbin)^3 * numVertex
where Wbin is the bin width for each dimension. However, the bin widths are restricted so that the number of bins in the bounding box of the mesh is an integer. Given that
Wbin-x * nx = Wx
We first choose nx (number of bins in x direction) as
nx = (truncate to int) Wx * cubic_root(numVertex / (Wx*Wy*Wz))
(except if nx < 1, then nx = 1) and then calculate the actual bin width
Wbin-x = Wx / nx
And repeat for z and y.
Todo:
Check that this works with 2D coords
Modifications:
03/08/04 WSK, created.
Parameters:
numVertex input - number of verts to go into the vertex bin
numDim input - dimensionsality of * coords
coords input - coords of vertices
lowers input - the bounding box of the point set
uppers input - the bounding box of the point set
bin_p output - bin
Definition at line 6179 of file geom.c.
References FC_VertexBin::binWidths, fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_VertexBin::lowerCoords, FC_VertexBin::numBins, FC_VertexBin::numVertex, FC_VertexBin::upperCoords, FC_VertexBin::vertexIDs, and FC_VertexBin::widths.
Referenced by fc_createDisplacedMeshVertexBin(), and fc_createMeshVertexBin().
{
  //FC_ReturnCode rc;
  int i, j, I, J, K;
  double volume, density;   // number of points per unit volume, but cube root
  int icoords[3] = { 0, 0, 0 };          // i j k coords of a bin
  void* temp;
  FC_VertexBin* bin;
  // default output
  if (bin_p)
    *bin_p = NULL;
  // Check input
  if (bin_p == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Creating spatial bins for vertices.");
  // Setup basics
  bin = calloc(1, sizeof(FC_VertexBin));
  if (bin == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < numDim; i++) {
    bin->lowerCoords[i] = lowers[i];
    bin->upperCoords[i] = uppers[i];
    bin->widths[i] = bin->upperCoords[i] - bin->lowerCoords[i];
  }
  // determine number of bins (at least 1 bin in each dimension)
  volume = 1;
  for (i = 0; i < numDim; i++)
    volume *= bin->widths[i];
  density = pow(numVertex/volume, 1./3.);
  for (i = 0; i < numDim; i++) {
    bin->numBins[i] = (int)(bin->widths[i]*density); // truncate
    if (bin->numBins[i] < 1) {
      bin->numBins[i] = 1;
      bin->binWidths[i] = bin->widths[i];
    }
    else
      bin->binWidths[i] = bin->widths[i]/bin->numBins[i];
  }
  // make space for bins
  bin->numVertex = malloc(bin->numBins[0]*sizeof(int**));
  bin->vertexIDs = malloc(bin->numBins[0]*sizeof(int***));
  if ( bin->numVertex == NULL ||  bin->vertexIDs == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < bin->numBins[0]; i++) {
    bin->numVertex[i] = malloc(bin->numBins[1]*sizeof(int*));
    bin->vertexIDs[i] = malloc(bin->numBins[1]*sizeof(int**));
    if ( bin->numVertex[i] == NULL ||  bin->vertexIDs[i] == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    for (j = 0; j < bin->numBins[1]; j++) {
      bin->numVertex[i][j] = calloc(bin->numBins[2], sizeof(int));
      bin->vertexIDs[i][j] = calloc(bin->numBins[2], sizeof(int*));
      if ( bin->numVertex[i][j] == NULL ||  bin->vertexIDs[i][j] == NULL) {
        fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
        return FC_MEMORY_ERROR;
      }
    }
  }
  // Put vertices in the bins
  // Usually cells on boundaries of bins land in next bin up
  // (except for highest bin)
  for (i = 0; i < numVertex; i++) {
    for (j = 0; j < numDim; j++) {
      icoords[j] = (int) ((coords[i*numDim+j] - bin->lowerCoords[j]) /
        bin->binWidths[j]);
      // check boundaries
      if (icoords[j] < 0)
        icoords[j] = 0;
      else if (icoords[j] == bin->numBins[j])
        icoords[j] = bin->numBins[j] - 1;
    }
    for (j = numDim; j < 3; j++)
      icoords[j] = 0;
    I = icoords[0];
    J = icoords[1];
    K = icoords[2];
    temp = realloc(bin->vertexIDs[I][J][K],
                   (1 + bin->numVertex[I][J][K])*sizeof(int));
    if (temp == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    bin->vertexIDs[I][J][K] = temp;
    bin->vertexIDs[I][J][K][bin->numVertex[I][J][K]] = i;
    bin->numVertex[I][J][K]++;
  }
  *bin_p = bin;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_doesElementContainPoint (FC_Mesh mesh, int element_id, double point[3], int dim, int max_num_vert_per_face, int * num_vert_per_face, int * face_conns, double * vert_coords, int * hit_type)
Internal function for determining whether a point is located within an element.
Description:
This internal function determines whether a point resides inside of an element or not. The function requires a number of inputs, including information about the mesh's faces and vertex coordinates (which can be obtained with fc_getMeshCoordsPtr() and fc_getMeshFaceConnsPtr()).
This function obtains all of the element's faces and then breaks each face into a collection of triangles. A ray-triangle intersection computation is performed with each triangle. If the point is inside the element, there will only be one intersection with a triangle. This function tries to detect when an intersection point happens to fall on the edge between two triangles (by verifying the distance is the same). In the case where the input point is lies in one of the element's faces, it is counted as being contained within the element.
note: it is possible for multiple elements to contain an element if (a) the elements overlap, or (b) the point lies on a vertex or face the two elements have in common.
Modifications:
03/20/2008 CDU Initial version
Parameters:
mesh input - The mesh this element belong to
element_id input - The id of the mesh element being examined
point input - The xyz coordinate being evaluated
dim input - The dimension of the coordinates (must be 3)
max_num_vert_per_face input - maximum number of vertices a face can have
num_vert_per_face input - number of vertices each face has
face_conns input - face connectivity list
vert_coords input - coordinates for each vertex
hit_type output - Result (0=does not contain, 1=containts, 2=contains, but point is on a face)
Definition at line 7629 of file geom.c.
References FC_AT_ELEMENT, FC_AT_FACE, fc_eqd(), FC_ERROR, fc_getIntersectionBetweenRayAndTriangle(), fc_getMeshEntityChildren(), fc_getReturnCodeText(), fc_gtd(), FC_INPUT_ERROR, fc_printfErrorMessage, and FC_SUCCESS.
Referenced by fc_doesElementContainPoint(), and fc_getElementsThatContainPoint().
 {
  int i,j;
  int num_faces;
  int *face_ids;
  int found_positive_hit, found_negative_hit;
  double t_val_positive, t_val_negative;
  int face_offset;
  double t;
  int hit;
  //In theory, we should do the test multiple times with randomly
  //generated directions. This helps weed out corner cases where
  //an edge/vertex happens to be in just the wrong spot. However, if we
  //compare the distance of all he intersections, and consider t=0.0 to
  //be a special case, I believe we can live with a single direction.
  double ray_direction[3] = {1.0, 0.0, 0.0};
  FC_ReturnCode rc;
  //Check inputs. Note: Mesh is checked in following step
  if(  (element_id<0) || (!point) || (!ray_direction) ||
       (max_num_vert_per_face<=0) || (!num_vert_per_face) ||
       (!vert_coords) || (!hit_type) ) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  if(dim!=3){
    fc_printfErrorMessage("Containment functions only work with 3-Dimensional data");
    return FC_INPUT_ERROR;
  }
  *hit_type = 0; //clear the output
  //Need to get all the faces for this element
  rc = fc_getMeshEntityChildren(mesh,
                    FC_AT_ELEMENT, element_id, //Parent: element
                    FC_AT_FACE,                //Children: faces
                    &num_faces, &face_ids);
  if(rc!=FC_SUCCESS) return rc;
  found_positive_hit = found_negative_hit = 0;
  //Scan through all faces of element
  for(i=0; (i<num_faces); i++){
    if(num_vert_per_face[ face_ids[i] ] < 3){
      fc_printfErrorMessage("Element face must have at least 3 vertices for hit test");
      free(face_ids);
      return FC_ERROR;
    }
    face_offset = max_num_vert_per_face * face_ids[i]; //Shorthand
    //Break each face into a set of 1 or more triangles
    for(j=0; (j<num_vert_per_face[ face_ids[i] ] - 2); j++){
      hit =  fc_getIntersectionBetweenRayAndTriangle(
               point, //Point is ray's origin
               ray_direction,
                     &vert_coords[ dim * face_conns[ face_offset + 0   ] ], //triangle point 0
               &vert_coords[ dim * face_conns[ face_offset + j+1 ] ], //triangle point 1
               &vert_coords[ dim * face_conns[ face_offset + j+2 ] ], //triangle point 2
               &t,NULL,NULL); //Only care about t, the distance to triangle
      if(hit){
     if((fc_eqd(t,0.0)) || (fc_eqd(t,-0.0)) ){
       *hit_type = 2; //point is on a face
       free(face_ids);
       return FC_SUCCESS;
     } else if (fc_gtd(t,0.0)){
       if(found_positive_hit){
         if(t!=t_val_positive){
           //Hit more than one place. Bail out.
           free(face_ids);
           return FC_SUCCESS;
         }
         //Otherwise, this must have been a common edge/vertex, keep going
       } else {
         //First unique hit, record distance so we can count intersections
         t_val_positive = t;
         found_positive_hit = 1;
       }
     } else { //negative hit
       if(found_negative_hit){
         if(t!=t_val_negative){
           //Hit more than one place. Bail out.
           free(face_ids);
           return FC_SUCCESS;
         }
         //Otherwise, this must have been a common edge/vertex, keep going
       } else {
         //First unique hit, record distance so we can count intersecrions
         t_val_negative = t;
         found_negative_hit = 1;
       }
     }
      }
    }
  }
  *hit_type = found_positive_hit && found_negative_hit;
  free(face_ids);
  return FC_SUCCESS;
}
FC_ReturnCode _fc_geomSmoothCore (int numMesh, FC_Mesh * meshes, int doDispl, FC_Variable * displs, FC_VertexBin ** bins, FC_Variable * vars, double radius, int doLocalSmooth, FC_Variable ** smooth_vars)
Smooth a variable field.
Description:
This routine creates a "smoothed" version of the original variable where each data point in the smoothed variable is the average of all data points within the given radius of the original data point. It uses the vertex bins created using fc_createMeshVertexBin(). Non-scalar variables are averaged component-wise. (Note that only entities that completely fall within the radius are used for the smoothing.) The smoothed variable will always have data type of double.
Because the vertex bins are per mesh, if you want to smooth a variable over all meshes, you must provide handles for the variable on all of the meshes and the appropriate vertex bins).
Modifications:
03/09/04 WSK, Created.
04/26/04 WSK, added handling for smoothing element associated vars
Parameters:
numMesh input - the number of meshes the variable is on
meshes input - the meshes
doDispl input - flag for whether to do displacment
displs input - for each mesh, the displacement variable
bins input - for each mesh, its vertex bin
vars input - for each mesh, the variable to smooth
radius input - the kernel radius
doLocalSmooth input - flag for whether smoothing is done over one mesh or all
smooth_vars output - the smoothed vars
Definition at line 6615 of file geom.c.
References FC_AT_EDGE, FC_AT_ELEMENT, FC_AT_FACE, FC_AT_VERTEX, FC_AT_WHOLE_MESH, fc_createVariable(), FC_DT_CHAR, FC_DT_DOUBLE, FC_DT_FLOAT, FC_DT_INT, FC_ERROR, fc_getDisplacedMeshCoords(), fc_getElementTypeNumVertex(), fc_getEntitiesWithinSphere(), fc_getMeshCoordsPtr(), fc_getMeshDim(), fc_getMeshEdgeConnsPtr(), fc_getMeshElementConnsPtr(), fc_getMeshElementType(), fc_getMeshFaceConnsPtr(), fc_getMeshFromVariable(), fc_getMeshNumVertex(), fc_getReturnCodeText(), fc_getVariableDataPtr(), fc_getVariableInfo(), fc_getVariableName(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, fc_isMeshValid(), fc_isValidDisplacementVariable(), fc_isVariableValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, fc_setVariableDataPtr(), FC_SUCCESS, numComponent, and var_name.
Referenced by fc_displacedGeomSmoothVariable(), and fc_geomSmoothVariable().
  {
  FC_ReturnCode rc;
  int i, j, k, m, n;
  char* var_name, *temp_name;
  int dim, numComponent, temp_dim, temp_numComponent;
  int numDataPoints[numMesh];
  FC_Mesh temp_mesh;
  FC_AssociationType assoc, temp_assoc;
  FC_MathType mathtype, temp_mathtype;
  FC_DataType datatype, temp_datatype;
  int numID, *ids;
  double* coords[numMesh];
  int maxNumVertPerFace[numMesh], *numVertPerFaces[numMesh];
  int* edgeConns[numMesh], *faceConns[numMesh], *elemConns[numMesh];
  int num;
  double *sums;
  void *old_datas[numMesh];
  double *new_datas[numMesh];
  // default output
  if (smooth_vars)
    *smooth_vars = NULL;
  // check input
  if (numMesh < 1 || !meshes || (doDispl && !displs) || !bins || !vars ||
      radius <= 0. ||  !smooth_vars) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  for (i = 0; i < numMesh; i++) {
    if (doDispl && !fc_isValidDisplacementVariable(meshes[i], displs[i])) {
      fc_printfErrorMessage("displ[%d] is not a valid displ var", i);
      return FC_INPUT_ERROR;
    }
    fc_getMeshFromVariable(vars[i], &temp_mesh);
    if (!fc_isMeshValid(meshes[i]) || !bins[i] ||
     !fc_isVariableValid(vars[i]) ||
     !FC_HANDLE_EQUIV(temp_mesh, bins[i]->mesh) ||
        !FC_HANDLE_EQUIV(temp_mesh, meshes[i]) ) {
      fc_printfErrorMessage("bins or vars do not match meshes");
      return FC_INPUT_ERROR;
    }
  }
  // log message
  if (doDispl) {
    fc_printfLogMessage("Smoothing a variable on displaced meshes");
  }
  else {
    fc_printfLogMessage("Smoothing a variable.");
  }
  // get info & more checking
  rc = fc_getMeshDim(meshes[0], &dim);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getVariableInfo(vars[0], &numDataPoints[0], &numComponent,
                          &assoc, &mathtype, &datatype);
  if (rc != FC_SUCCESS)
    return rc;
  if (datatype == FC_DT_CHAR) {
    fc_printfErrorMessage("Can't handle FC_DT_CHAR data");
    return FC_ERROR;
  }
  // All variables must have same dim, numComponent, assoc, mathtype, datatype
  for (i = 1; i < numMesh; i++) {
    fc_getMeshDim(meshes[i], &temp_dim);
    fc_getVariableInfo(vars[i], &numDataPoints[i], &temp_numComponent,
                       &temp_assoc, &temp_mathtype, &temp_datatype);
    if (temp_dim != dim || temp_numComponent != numComponent ||
        temp_assoc != assoc || temp_mathtype != mathtype ||
        temp_datatype != datatype) {
      fc_printfErrorMessage("Variables do not match");
      return FC_INPUT_ERROR;
    }
  }
  // For each mesh, get coords & variable data, make room for new data
  for (i = 0; i < numMesh; i++) {
    if (doDispl)
      rc = fc_getDisplacedMeshCoords(meshes[i], displs[i], &coords[i]);
    else
      rc = fc_getMeshCoordsPtr(meshes[i], &coords[i]);
    if (rc != FC_SUCCESS)
      return rc;
    if (assoc == FC_AT_EDGE)
      fc_getMeshEdgeConnsPtr(meshes[i], &edgeConns[i]);
    else if (assoc == FC_AT_FACE)
      fc_getMeshFaceConnsPtr(meshes[i], &numVertPerFaces[i],
                    &maxNumVertPerFace[i], &faceConns[i]);
    else if (assoc == FC_AT_ELEMENT)
      fc_getMeshElementConnsPtr(meshes[i], &elemConns[i]);
    fc_getVariableDataPtr(vars[i], &old_datas[i]);
    new_datas[i] = (double*)malloc(sizeof(double)*
                                   numDataPoints[i]*numComponent);
    if (new_datas[i] == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
  }
  // for each data point
  // 1) find center
  // 2) find all other points on all meshes that fall within radius
  //   ( 2A) make sure have current point)
  // 3) sum all contributions & divide by number of data points
  sums = (double*)malloc(sizeof(double)*numComponent);
  if (sums == NULL)  {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < numMesh; i++) {
    for (j = 0; j < numDataPoints[i]; j++) {
      FC_Coords center;
      // Find center
      if (assoc == FC_AT_VERTEX) {
        for (k = 0; k < dim; k++)
          center[k] = coords[i][j*dim + k];
      }
      else if (assoc == FC_AT_WHOLE_MESH) {
        int numVert;
        fc_getMeshNumVertex(meshes[i], &numVert);
        for (k = 0; k < dim; k++)
          center[k] = 0;
        for (k = 0; k < numVert; k++)
          for (m = 0; m < dim; m++)
            center[m] += coords[i][k*dim + m];
        for (k = 0; k < dim; k++)
          center[k] /= numVert;
      }
      else {
        // Centroid of this edge, face or element
        int numVert, *vertIDs;
        if (assoc == FC_AT_EDGE) {
          numVert = 2;
          vertIDs = &edgeConns[i][j*2];
        }
        else if (assoc == FC_AT_FACE) {
          numVert = numVertPerFaces[i][j];
          vertIDs = &faceConns[i][j*maxNumVertPerFace[i]];
        }
        else if (assoc == FC_AT_ELEMENT) {
       FC_ElementType elemType;
       fc_getMeshElementType(meshes[i], &elemType);
          numVert = fc_getElementTypeNumVertex(elemType);
          vertIDs = &elemConns[i][j*numVert];
        }
        for (k = 0; k < dim; k++)
          center[k] = 0;
        for (k = 0; k < numVert; k++)
          for (m = 0; m < dim; m++)
            center[m] += coords[i][vertIDs[k]*dim + m];
        for (k = 0; k < dim; k++)
          center[k] /= numVert;
      }
      // find geometric neighbors on each mesh & add their values
      num = 0;
      for (k = 0; k < numComponent; k++)
        sums[k] = 0;
      for (k = (doLocalSmooth?i:0); k < (doLocalSmooth?i+1:numMesh); k++) {
        rc = fc_getEntitiesWithinSphere(meshes[k], bins[k], center, radius,
                                        assoc, &numID, &ids);
        if (rc != FC_SUCCESS)
          return rc;
        // make sure we include the current entity
        if (k == i) {
          int found = 0;
          for (m = 0; m < numID; m++) {
            if (ids[m] == j) {
              found = 1;
              break;
            }
          }
          if (!found) {
            int* temp = realloc(ids, (numID+1)*sizeof(int));
            if (!temp) {
              fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
              return FC_MEMORY_ERROR;
            }
            ids = temp;
            ids[numID] = j;
            numID++;
          }
        }
        // add to our cumulative sums
        for (m = 0; m < numID; m++) {
          for (n = 0; n < numComponent; n++) {
            switch(datatype) {
            case FC_DT_INT:
              sums[n] += ((int*)(old_datas[k]))[ids[m]*numComponent+n];
              break;
            case FC_DT_FLOAT:
              sums[n] += ((float*)(old_datas[k]))[ids[m]*numComponent+n];
              break;
            case FC_DT_DOUBLE:
              sums[n] += ((double*)(old_datas[k]))[ids[m]*numComponent+n];
              break;
            default:
              return FC_ERROR;
            }
          }
          num++;
        }
        free(ids);
      }
      for (k = 0; k < numComponent; k++)
        new_datas[i][j*numComponent+k] = sums[k]/num;
    }
  }
  free(sums);
  if (doDispl) {
    for (i = 0; i < numMesh; i++)
      free(coords[i]);
  }
  // create new vars
  *smooth_vars = (FC_Variable*)malloc(numMesh*sizeof(FC_Variable));
  if (*smooth_vars == NULL) {
    fc_printfErrorMessage("memory allocation error");
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < numMesh; i++) {
    rc = fc_getVariableName(vars[i], &var_name);
    temp_name = (char*)malloc((strlen(var_name) + 10)*sizeof(char));
    sprintf(temp_name, "%s_smoothed", var_name);
    free(var_name);
    rc = fc_createVariable(meshes[i], temp_name, &(*smooth_vars)[i]);
    free(temp_name);
    if (rc != FC_SUCCESS)
      return rc;
    rc = fc_setVariableDataPtr((*smooth_vars)[i], numDataPoints[i],
               numComponent, assoc, mathtype, FC_DT_DOUBLE, new_datas[i]);
    if (rc != FC_SUCCESS)
      return rc;
    // don't free new_datas[i]
  }
  return FC_SUCCESS;
}
FC_ReturnCode _fc_getDiameterOutputArgsTest (double * diameter, int * numPair, int ** pairIDs)
Helper for 'getDiameter' routines.
Sets the default return values of output args and tests that output arg values are sane.
Modifications:
6/27/05 WSD Created.
Parameters:
diameter ouput - diameter of the vertex set
numPair output - number of pairs of vertices that are diameter distance from each other
pairIDs output - IDs of the vertex pairs
Definition at line 2127 of file geom.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, and FC_SUCCESS.
Referenced by fc_getDisplacedMeshDiameter(), fc_getDisplacedSubsetDiameter(), fc_getMeshDiameter(), and fc_getSubsetDiameter().
  {
  // default return
  if (diameter)
    *diameter = -1;
  if (numPair)
    *numPair = -1;
  if (pairIDs)
    *pairIDs = NULL;
  // test output args
  if (!diameter) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  if ((numPair && !pairIDs) || (!numPair && pairIDs)) {
    fc_printfErrorMessage("Did not provide both numPair & pairIDs for "
                 "returned vertex IDs");
    return FC_INPUT_ERROR;
  }
  return FC_SUCCESS;
}
FC_ReturnCode _fc_getDiameterOutputArgsTestMeshes (double * diameter, int * numPair, int ** pairIDs, FC_Mesh ** pairMeshes)
Helper for 'getDiameter' routines.
Sets the default return values of output args and tests that output arg values are sane.
Modifications:
3/13/06 WSD Created.
Parameters:
diameter ouput - diameter of the vertex set
numPair output - number of pairs of vertices that are diameter distance from each other
pairIDs output - IDs of the vertex pairs
pairMeshes output - owning meshes for the verts
Definition at line 2165 of file geom.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, and FC_SUCCESS.
Referenced by fc_getDisplacedMeshesDiameter(), and fc_getMeshesDiameter().
  {
  // default return
  if (diameter)
    *diameter = -1;
  if (numPair)
    *numPair = -1;
  if (pairIDs)
    *pairIDs = NULL;
  if (pairMeshes)
    *pairMeshes = NULL;
  // test output args
  if (!diameter) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  if ( (numPair && (!pairIDs || !pairMeshes)) ||
       (!numPair && (pairIDs || pairMeshes)) ) {
    fc_printfErrorMessage("Did not provide both numPair & pairIDs for "
                 "returned vertex IDs");
    return FC_INPUT_ERROR;
  }
  return FC_SUCCESS;
}
FC_ReturnCode _fc_getDiameterOutputArgsTestSubsets (double * diameter, int * numPair, int ** pairIDs, FC_Subset ** pairSubsets)
Helper for 'getDiameter' routines.
Sets the default return values of output args and tests that output arg values are sane.
Modifications:
3/13/06 WSD Created.
Parameters:
diameter ouput - diameter of the vertex set
numPair output - number of pairs of vertices that are diameter distance from each other
pairIDs output - IDs of the vertex pairs
pairSubsets output - owning subsets for the verts
Definition at line 2207 of file geom.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, and FC_SUCCESS.
Referenced by fc_getDisplacedSubsetsDiameter(), and fc_getSubsetsDiameter().
  {
  // default return
  if (diameter)
    *diameter = -1;
  if (numPair)
    *numPair = -1;
  if (pairIDs)
    *pairIDs = NULL;
  if (pairSubsets)
    *pairSubsets = NULL;
  // test output args
  if (!diameter) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  if ( (numPair && (!pairIDs || !pairSubsets)) ||
       (!numPair && (pairIDs || pairSubsets)) ) {
    fc_printfErrorMessage("Did not provide both numPair & pairIDs for "
                 "returned vertex IDs");
    return FC_INPUT_ERROR;
  }
  return FC_SUCCESS;
}
FC_ReturnCode _fc_getSubsetDiameterCore (FC_Subset subset, FC_Variable * displ, double * diameter, int * numPair, int ** pairIDs)
Core code of 'getDiameter' routines.
Implements brute force comparison of all vertices.
Todo:
This routine will be very slow for point sets. The best optimization is to find the convex hull of the set and then brute force search only the points of the hull polygon. However, the 3D convex hull algorithm is not easy to implement so I punted -WSD.
Todo:
This routine should probably be replaced by _fc_getSubsetsDiameterCore() so that the core code isn't duplicated.
Modifications:
6/27/05 WSD Created.
Parameters:
subset input - a subset
displ input - pointer to displ (NULL = no displ)
diameter ouput - diameter of the vertex set
numPair output - number of pairs of vertices that are diameter distance from each other
pairIDs output - IDs of the vertex pairs
Definition at line 2256 of file geom.c.
References FC_AT_VERTEX, fc_calcSquaredEuclideanDistance(), fc_changeMeshEntityType(), FC_DBL_EQUIV, fc_getDisplacedMeshCoords(), fc_getMeshCoordsPtr(), fc_getMeshDim(), fc_getMeshFromSubset(), fc_getSubsetInfo(), fc_getSubsetMembersAsArray(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, and FC_SUCCESS.
Referenced by fc_getDisplacedMeshDiameter(), fc_getDisplacedSubsetDiameter(), fc_getMeshDiameter(), and fc_getSubsetDiameter().
  {
  FC_ReturnCode rc;
  int i, j;
  int numDim, numVertex, *vertexIDs, numMember, *memberIDs;
  double *coords_p, temp;
  FC_Mesh mesh;
  FC_AssociationType assoc;
  int doPairs = 0, num = 0, maxNum = 0, *ids;
  double diameter2 = -1; // squared diameter;
  // setup I
  if (numPair && pairIDs)
    doPairs = 1;
  rc = fc_getMeshFromSubset(subset, &mesh);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getSubsetInfo(subset, &numMember, NULL, &assoc);
  if (rc != FC_SUCCESS)
    return rc;
  // get vertices of the members
  rc = fc_getSubsetMembersAsArray(subset, &numMember, &memberIDs);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_changeMeshEntityType(mesh, assoc, numMember, memberIDs,
                               FC_AT_VERTEX, 1, &numVertex, &vertexIDs);
  free(memberIDs);
  // Special case: if 0 vertex - return error!
  if (numVertex == 0) {
    fc_printfErrorMessage("Subset has 0 members, diameter is undefined.");
    return FC_INPUT_ERROR;
  }
  // Special case: if 1 vertex - return 0
  if (numVertex == 1) {
    free(vertexIDs);
    *diameter = 0.;
    if (doPairs)
      *numPair = 0;
    return FC_SUCCESS;
  }
  // setup II
  rc = fc_getMeshDim(mesh, &numDim);
  if (rc != FC_SUCCESS)
    return rc;
  if (displ) {
    rc = fc_getDisplacedMeshCoords(mesh, *displ, &coords_p);
    if (rc != FC_SUCCESS)
      return rc;
  }
  else {
    rc = fc_getMeshCoordsPtr(mesh, &coords_p);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // Start off with space for at least 1 pair
  if (doPairs) {
    ids = (int*)malloc(2*sizeof(int));
    num = 0;
    maxNum = 1;
  }
  // Do it
  for (i = 0; i < numVertex; i++) {
    for (j = i+1; j < numVertex; j++) {
      fc_calcSquaredEuclideanDistance(&coords_p[vertexIDs[i]*numDim],
                          &coords_p[vertexIDs[j]*numDim],
                          numDim, &temp);
      if (temp > diameter2) {
     diameter2 = temp;
     if (doPairs) {
       ids[0] = vertexIDs[i];
       ids[1] = vertexIDs[j];
       num = 1;
     }
      }
      else if (doPairs && FC_DBL_EQUIV(temp, diameter2)) {
     if (num+1 > maxNum) {
       ids = (int*)realloc(ids, 4*maxNum*sizeof(int));
       if (!ids)
         return FC_MEMORY_ERROR;
       maxNum *= 2;
     }
     ids[num*2] = vertexIDs[i];
     ids[num*2+1] = vertexIDs[j];
     num++;
      }
    }
  }
  if (displ)
    free(coords_p);
  free(vertexIDs);
  // Return?
  *diameter = sqrt(diameter2);
  if (doPairs) {
    *numPair = num;
    *pairIDs = (int*)realloc(ids, 2*num*sizeof(int)); // squeeze
  }
  return FC_SUCCESS;
}
FC_ReturnCode _fc_getSubsetsDiameterCore (int numSubset, FC_Subset * subsets, FC_Variable * displs, double * diameter, int * numPair, int ** pairIDs, FC_Subset ** pairSubsets)
Core code of 'getDiameter' routines.
Implements brute force comparison of all vertices.
Todo:
This routine will be very slow for point sets. The best optimization is to find the convex hull of the set and then brute force search only the points of the hull polygon. However, the 3D convex hull algorithm is not easy to implement so I punted -WSD.
Modifications:
6/27/05 WSD Created.
3/9/06 WSD Changed to do multiple subsets.
Parameters:
numSubset input - number of subsets
subsets input - a subset
displs input - array of displs (NULL = no displ)
diameter ouput - diameter of the vertex set
numPair output - number of pairs of vertices that are diameter distance from each other
pairIDs output - IDs of the vertex pairs
pairSubsets output - Subsets of the vertex pairs
Definition at line 2382 of file geom.c.
References FC_AT_VERTEX, fc_calcSquaredEuclideanDistance(), fc_changeMeshEntityType(), FC_DBL_EQUIV, fc_getDisplacedMeshCoords(), fc_getMeshCoordsPtr(), fc_getMeshDim(), fc_getMeshFromSubset(), fc_getSubsetInfo(), fc_getSubsetMembersAsArray(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, and FC_SUCCESS.
Referenced by fc_getDisplacedMeshesDiameter(), fc_getDisplacedSubsetsDiameter(), fc_getMeshesDiameter(), and fc_getSubsetsDiameter().
  {
  FC_ReturnCode rc;
  int i, j, i_s, j_s;
  int numDim, numVerts[numSubset], *vertIDs[numSubset], numTotalVert;
  int numMember, *memberIDs;
  double *coords[numSubset], temp;
  FC_Mesh meshes[numSubset];
  FC_Subset* subs = NULL, *temp_subs;
  FC_AssociationType assoc;
  int doPairs = 0, num = 0, maxNum = 1, *ids = NULL, *temp_ids;
  double diameter2 = -1; // squared diameter
  // assume args are o.k.
  // FIX: assume numDim is the same for all subsets,
  // pass as an argument!?
  // setup I
  if (numPair && pairSubsets && pairIDs)
    doPairs = 1;
  // Get vertIDs per subset
  numTotalVert = 0;
  for (i = 0; i < numSubset; i++) {
    rc = fc_getMeshFromSubset(subsets[i], &meshes[i]);
    if (rc != FC_SUCCESS)
      return rc;
    rc = fc_getMeshDim(meshes[i], &numDim); // FIX
    if (rc != FC_SUCCESS)
      return rc;
    rc = fc_getSubsetInfo(subsets[i], &numMember, NULL, &assoc);
    if (rc != FC_SUCCESS)
      return rc;
    // get vertices of the members
    rc = fc_getSubsetMembersAsArray(subsets[i], &numMember, &memberIDs);
    if (rc != FC_SUCCESS)
      return rc;
    if (assoc == FC_AT_VERTEX) {
      numVerts[i] = numMember;
      vertIDs[i] = memberIDs;
    }
    else {
      rc = fc_changeMeshEntityType(meshes[i], assoc, numMember, memberIDs,
                       FC_AT_VERTEX, 1, &numVerts[i], &vertIDs[i]);
      free(memberIDs);
      if (rc != FC_SUCCESS)
     return rc;
    }
    numTotalVert += numVerts[i];
  }
  // Special case: if 0 vertex - return error!
  if (numTotalVert == 0) {
    fc_printfErrorMessage("Subsets have 0 members, diameter is undefined.");
    return FC_INPUT_ERROR;
  }
  // Special case: if 1 vertex - return 0
  if (numTotalVert == 1) {
    for (i = 0; i < numSubset; i++)
      free(vertIDs[i]);
    *diameter = 0.;
    if (doPairs)
      *numPair = 0;
    return FC_SUCCESS;
  }
  // Get the coords
  for (i = 0; i < numSubset; i++) {
    if (displs)
      rc = fc_getDisplacedMeshCoords(meshes[i], displs[i], &coords[i]);
    else
      rc = fc_getMeshCoordsPtr(meshes[i], &coords[i]);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // Start off with space for at least 1 pair
  if (doPairs) {
    ids = (int*)malloc(2*sizeof(int));
    subs = (FC_Subset*)malloc(2*sizeof(FC_Subset));
    num = 0;
    maxNum = 1;
  }
  // Note: diameter2 starts at -1
  // Do within each subset
  for (i_s = 0; i_s < numSubset; i_s++) {
    for (i = 0; i < numVerts[i_s]; i++) {
      for (j = i+1; j < numVerts[i_s]; j++) {
     fc_calcSquaredEuclideanDistance(&coords[i_s][vertIDs[i_s][i]*numDim],
                         &coords[i_s][vertIDs[i_s][j]*numDim],
                         numDim, &temp);
     if (temp > diameter2) {
       diameter2 = temp;
       if (doPairs) {
         ids[0] = vertIDs[i_s][i];
         ids[1] = vertIDs[i_s][j];
         subs[0] = subsets[i_s];
         subs[1] = subsets[i_s];
         num = 1;
       }
     }
     else if (doPairs && FC_DBL_EQUIV(temp, diameter2)) {
       if (num+1 > maxNum) {
         temp_ids = (int*)realloc(ids, 4*maxNum*sizeof(int));
         temp_subs = (FC_Subset*)realloc(subs, 4*maxNum*sizeof(FC_Subset));
         if (!temp_ids || !temp_subs)
           return FC_MEMORY_ERROR;
         ids = temp_ids;
         subs = temp_subs;
         maxNum *= 2;
       }
       ids[num*2] = vertIDs[i_s][i];
       ids[num*2+1] = vertIDs[i_s][j];
       subs[num*2] = subsets[i_s];
       subs[num*2+1] = subsets[i_s];
       num++;
     }
      }
    }
  }
  // check each vertex in one subset against all verts in other subsets
  for (i_s = 0; i_s < numSubset; i_s++) {
    for (i = 0; i < numVerts[i_s]; i++) {
      for (j_s = i_s+1; j_s < numSubset; j_s++) {
     for (j = 0; j < numVerts[j_s]; j++) {
       fc_calcSquaredEuclideanDistance(&coords[i_s][vertIDs[i_s][i]*numDim],
                           &coords[j_s][vertIDs[j_s][j]*numDim],
                           numDim, &temp);
       if (temp > diameter2) {
         diameter2 = temp;
         if (doPairs) {
           ids[0] = vertIDs[i_s][i];
           ids[1] = vertIDs[j_s][j];
           subs[0] = subsets[i_s];
           subs[1] = subsets[j_s];
           num = 1;
         }
       }
       else if (doPairs && FC_DBL_EQUIV(temp, diameter2)) {
         if (num+1 > maxNum) {
           temp_ids = (int*)realloc(ids, 4*maxNum*sizeof(int));
           temp_subs = (FC_Subset*)realloc(subs, 4*maxNum*sizeof(FC_Subset));
           if (!temp_ids || !temp_subs)
          return FC_MEMORY_ERROR;
           maxNum*= 2;
           ids = temp_ids;
           subs = temp_subs;
         }
         ids[num*2] = vertIDs[i_s][i];
         ids[num*2+1] = vertIDs[j_s][j];
         subs[num*2] = subsets[i_s];
         subs[num*2+1] = subsets[j_s];
         num++;
       }
     }
      }
    }
  }
  if (displs)
    for (i = 0; i < numSubset; i++)
      free(coords[i]);
  for (i = 0; i < numSubset; i++)
    free(vertIDs[i]);
  // Return?
  *diameter = sqrt(diameter2);
  if (doPairs) {
    *numPair = num;
    *pairSubsets = (FC_Subset*)realloc(subs, 2*num*sizeof(FC_Subset));
    *pairIDs = (int*)realloc(ids, 2*num*sizeof(int)); // squeeze
  }
  return FC_SUCCESS;
}
FC_ReturnCode _fc_getSubsetsProximityArgsTest (FC_Mesh * mesh1, FC_Subset * subset1, FC_Variable * displ1, FC_Mesh * mesh2, FC_Subset * subset2, FC_Variable * displ2, double min_dist, int * numPair, int ** mesh1VertIDs, int ** mesh2VertIDs)
Common argument testing for all proximity routines.
Description:
Modifications:
03/14/2006 WSD Created.
03/16/2006 WSD changed behavior so that if NULLs are passed in for the vertIDs, will return after 1st match.
Parameters:
mesh1 input - the first mesh
subset1 input - the first subset
displ1 input - the displs on the first mesh/subset
mesh2 input - the first mesh
subset2 input - the second subset
displ2 input - the disps on the 2nd mesh/subset
min_dist input - the distance cutoff
numPair output - the number of vertex pairs found
mesh1VertIDs output - ids of the mesh1 verts (order matters), user is responsible for freeing
mesh2VertIDs output - ids of the mesh2 verts (order matters), user is responsible for freeing
Definition at line 5181 of file geom.c.
References fc_getMeshDim(), fc_getMeshFromSubset(), fc_getReturnCodeText(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, fc_isMeshValid(), fc_isSubsetValid(), fc_isValidDisplacementVariable(), fc_isVariableValid(), fc_lt(), fc_printfErrorMessage, and FC_SUCCESS.
Referenced by fc_getDisplacedMeshesProximity(), fc_getDisplacedSubsetsProximity(), fc_getMeshesProximity(), and fc_getSubsetsProximity().
  {
  int numDim1, numDim2;
  FC_Mesh temp_mesh1, temp_mesh2;
  // default returns
  if (numPair)
    *numPair = -1;
  if (mesh1VertIDs)
    *mesh1VertIDs = NULL;
  if (mesh2VertIDs)
    *mesh2VertIDs = NULL;
  // test input
  // It is o.k. to pass in mesh1VertIDs = NULL && mesh2VertIDs = NULL
  if (!numPair || (!mesh1VertIDs && mesh2VertIDs) ||
      (mesh1VertIDs && !mesh2VertIDs)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  if ( (mesh1 && !fc_isMeshValid(*mesh1)) ||
       (mesh2 && !fc_isMeshValid(*mesh2)) ||
       (subset1 && !fc_isSubsetValid(*subset1)) ||
       (subset2 && !fc_isSubsetValid(*subset2)) ||
       (displ1 && !fc_isVariableValid(*displ1)) ||
       (displ2 && !fc_isVariableValid(*displ2)) ||
       fc_lt(min_dist, 0., DBL_EPSILON, DBL_MIN) ) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // If have 1, have to have the other, and can't be equal
  // (NOTE displ1 == displ2 implies mesh1 = mesh2, so not testing that
  if ( (mesh1 && !mesh2) || (!mesh1 && mesh2) ||
       (subset1 && !subset2) || (!subset1 && subset2) ||
       (displ1 && !displ2) || (!displ1 && displ2) ||
       (mesh1 && !displ1 && FC_HANDLE_EQUIV(*mesh1, *mesh2)) ||
       (mesh1 && displ1 && FC_HANDLE_EQUIV(*displ1, *displ2)) ||
       (subset1 && !displ1 && FC_HANDLE_EQUIV(*subset1, *subset2)) ||
       (subset1 && displ1 && (FC_HANDLE_EQUIV(*subset1, *subset2) &&
                     FC_HANDLE_EQUIV(*displ1, *displ2))) ) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // some setup for further testing
  if (mesh1)
    temp_mesh1 = *mesh1;
  else
    fc_getMeshFromSubset(*subset1, &temp_mesh1);
  if (mesh2)
    temp_mesh2 = *mesh2;
  else
    fc_getMeshFromSubset(*subset2, &temp_mesh2);
  // more tests
  if ( (displ1 && !fc_isValidDisplacementVariable(temp_mesh1, *displ1)) ||
       (displ2 && !fc_isValidDisplacementVariable(temp_mesh2, *displ2))) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  fc_getMeshDim(temp_mesh1, &numDim1);
  fc_getMeshDim(temp_mesh2, &numDim2);
  if (numDim1 != numDim2) {
    fc_printfErrorMessage("Meshes must have same numDim (%d != %d)",
                 numDim1, numDim2);
    return FC_INPUT_ERROR;
  }
  // made it past tests
  return FC_SUCCESS;
}
FC_ReturnCode _fc_getSubsetsProximityCore (FC_Subset subset1, FC_Variable * displ1, FC_Subset subset2, FC_Variable * displ2, double min_dist, int * numPair_p, int ** mesh1VertIDs_p, int ** mesh2VertIDs_p)
Return the proximal vertices between two displaced subsets.
Description:
This returns all vertex pairs that are less than or equal to min_dist apart. Vertices may show up in more than one pair. (In the extrememe case if you put in min_dist = infinity, you would end up with each vertex being connected to all vertices of the other subset.)
The routine can be forced to return "early", after the first match is found, if you use NULL for the last two arguments (the vertex arrays). In this case, the returned numPair is really a flag for whether a pair was found or not and will never be greater than 1 even if there are more than one possible pairs.
Note, passing in min_dist = 0 will find overlapping vertices, or if subsets are on the same mesh, will find common vertices.
Note, subsets may be closer together than any of the vertex pairs (imagine 1 vertex of one mesh very close to middle of a face of another mesh. the vert to face distance is less than distance to the face's verts).
Will return if error if subset1 == subset2 AND displ1 == displ2. (subset1 can be the same as subset2 if displ1 != displ2)
Todo:
(performance) Restrict the brute force search to vertices in the bounding box overlap
Todo:
(performance) make the pairs grow by greater than 1 each time
Modifications:
02/14/2006 WSD Created.
03/16/2006 WSD changed behavior so that if NULLs are passed in for the vertIDs, will return after 1st match.
Parameters:
subset1 input - the first subset
displ1 input - the displacements on the mesh of the first subset
subset2 input - the second subset
displ2 input - the displacements on the mesh of the second subset
min_dist input - the distance cutoff
numPair_p output - the number of vertex pairs found
mesh1VertIDs_p output - ids of the mesh1 verts (order matters), user is responsible for freeing
mesh2VertIDs_p output - ids of the mesh2 verts (order matters), user is responsible for freeing
Definition at line 5303 of file geom.c.
References FC_AT_VERTEX, fc_calcSquaredEuclideanDistance(), fc_changeMeshEntityType(), fc_getBoundingBoxesOverlap(), fc_getDisplacedMeshCoords(), fc_getDisplacedSubsetBoundingBox(), fc_getMeshCoordsPtr(), fc_getMeshDim(), fc_getMeshFromSubset(), fc_getReturnCodeText(), fc_getSubsetAssociationType(), fc_getSubsetBoundingBox(), fc_getSubsetMembersAsArray(), FC_INPUT_ERROR, fc_lteq(), FC_MEMORY_ERROR, fc_printfErrorMessage, and FC_SUCCESS.
Referenced by fc_getDisplacedMeshesProximity(), fc_getDisplacedSubsetsProximity(), fc_getMeshesProximity(), and fc_getSubsetsProximity().
  {
  FC_ReturnCode rc;
  int i, j;
  FC_Mesh mesh1, mesh2;
  int numDim, temp_numDim, overlap_flag;
  int numMember1, numMember2, *memberIDs1, *memberIDs2;
  int numVert1, numVert2, *vertIDs1, *vertIDs2;
  FC_AssociationType assoc1, assoc2;
  FC_Coords lowers1, uppers1, lowers2, uppers2, lowers3, uppers3;
  double *coords1, *coords2;
  double min_dist2, distance2; // squared versions of min_dist & distance
  int numPair = 0, *mesh1VertIDs = NULL, *mesh2VertIDs = NULL;
  int *temp1, *temp2;
  int doDispl = 0, doPairs = 0;
  // assume args all tested & defaults set
  // setup
  if (displ1 && displ2)
    doDispl = 1;
  if (mesh1VertIDs_p && mesh2VertIDs_p)
    doPairs = 1;
  fc_getMeshFromSubset(subset1, &mesh1);
  fc_getMeshFromSubset(subset2, &mesh2);
  // plus one more test:
  fc_getMeshDim(mesh1, &numDim);
  fc_getMeshDim(mesh2, &temp_numDim);
  if (numDim != temp_numDim) {
    fc_printfErrorMessage("Meshes must have same numDim (%d != %d)",
                 numDim, temp_numDim);
    return FC_INPUT_ERROR;
  }
  // Compute bounding boxes +/- min_dist/2
  if (doDispl) {
    rc = fc_getDisplacedSubsetBoundingBox(subset1, *displ1, &numDim, &lowers1,
                           &uppers1);
    if (rc != FC_SUCCESS)
      return rc;
    rc = fc_getDisplacedSubsetBoundingBox(subset2, *displ2, &numDim, &lowers2,
                           &uppers2);
    if (rc != FC_SUCCESS)
      return rc;
  }
  else {
    rc = fc_getSubsetBoundingBox(subset1, &numDim, &lowers1, &uppers1);
    if (rc != FC_SUCCESS)
      return rc;
    rc = fc_getSubsetBoundingBox(subset2, &numDim, &lowers2, &uppers2);
    if (rc != FC_SUCCESS)
      return rc;
  }
  for (i = 0; i < numDim; i++) {
    lowers1[i] -= min_dist/2.;
    lowers2[i] -= min_dist/2.;
    uppers1[i] += min_dist/2.;
    uppers2[i] += min_dist/2.;
  }
  rc = fc_getBoundingBoxesOverlap(numDim, lowers1, uppers1, lowers2, uppers2,
                      &overlap_flag, &lowers3, &uppers3);
  if (rc != FC_SUCCESS)
    return rc;
  // early return if no overlap
  if (overlap_flag == 0) {
    *numPair_p = 0;
    return FC_SUCCESS;
  }
  // convert subset members to verts (if needed)
  fc_getSubsetAssociationType(subset1, &assoc1);
  fc_getSubsetAssociationType(subset2, &assoc2);
  fc_getSubsetMembersAsArray(subset1, &numMember1, &memberIDs1);
  fc_getSubsetMembersAsArray(subset2, &numMember2, &memberIDs2);
  if (assoc1 == FC_AT_VERTEX) {
    numVert1 = numMember1;
    vertIDs1 = memberIDs1;
  }
  else {
    fc_changeMeshEntityType(mesh1, assoc1, numMember1, memberIDs1,
                   FC_AT_VERTEX, 0, &numVert1, &vertIDs1);
    free(memberIDs1);
  }
  if (assoc2 == FC_AT_VERTEX) {
    numVert2 = numMember2;
    vertIDs2 = memberIDs2;
  }
  else {
    fc_changeMeshEntityType(mesh2, assoc2, numMember2, memberIDs2,
                   FC_AT_VERTEX, 0, &numVert2, &vertIDs2);
    free(memberIDs2);
  }
  // get coords
  if (doDispl) {
    rc = fc_getDisplacedMeshCoords(mesh1, *displ1, &coords1);
    if (rc != FC_SUCCESS)
      return rc;
    rc = fc_getDisplacedMeshCoords(mesh2, *displ2, &coords2);
    if (rc != FC_SUCCESS)
      return rc;
  }
  else {
    rc = fc_getMeshCoordsPtr(mesh1, &coords1);
    if (rc != FC_SUCCESS)
      return rc;
    rc = fc_getMeshCoordsPtr(mesh2, &coords2);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // FIX make this better
  // 1) have smarter realloc of pairs - grow by *2
  // 2) could just test vertices in the overlap
  // 3) set up two sets of loops - switch from the first
  //    after the first pair is found so don't have the
  //    doPairs test in every loop
  // If find a pair, add to pairs
  // Note: early return if not doing pairs
  min_dist2 = min_dist*min_dist;
  for (i = 0; i < numVert1; i++) {
    int vertID1 = vertIDs1[i];
    for (j = 0; j < numVert2; j++) {
      int vertID2 = vertIDs2[j];
      fc_calcSquaredEuclideanDistance(&coords1[vertID1*numDim],
                          &coords2[vertID2*numDim], numDim,
                          &distance2);
      if (fc_lteq(distance2, min_dist2, DBL_EPSILON, DBL_MIN)) {
     if (!doPairs) {
       *numPair_p = 1;
       free(vertIDs1);
       free(vertIDs2);
       if (doDispl) {
         free(coords1);
         free(coords2);
       }
       return FC_SUCCESS;
     }
     temp1 = realloc(mesh1VertIDs, (numPair+1)*sizeof(int));
     temp2 = realloc(mesh2VertIDs, (numPair+1)*sizeof(int));
     if (!temp1 || !temp2) {
       free(mesh1VertIDs); free(mesh2VertIDs);
       fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
       return FC_MEMORY_ERROR;
     }
     mesh1VertIDs = temp1;
     mesh2VertIDs = temp2;
     mesh1VertIDs[numPair] = vertID1;
     mesh2VertIDs[numPair] = vertID2;
     numPair++;
      }
    }
  }
  free(vertIDs1);
  free(vertIDs2);
  if (doDispl) {
    free(coords1);
    free(coords2);
  }
  // set return values
  *numPair_p = numPair;
  if (doPairs) { // in case numPair is zero
    *mesh1VertIDs_p = mesh1VertIDs;
    *mesh2VertIDs_p = mesh2VertIDs;
  }
  return FC_SUCCESS;
}
FC_ReturnCode _fc_getVertexIDsWithinBoundingBoxUsingVertexBin (FC_Mesh mesh, FC_VertexBin * bin, FC_Coords lowpoint, FC_Coords highpoint, int * numVertex_p, int ** vertexIDs_p)
Find all vertices within a bounding box.
Description:
Takes two points describing a bounding box and returns the IDs of all vertices which are within the bounding box (including those on its boundary), regardless of the connectivity information in the mesh. To use this routine, you must first call fc_createMeshVertexBin to make the vertex bins used for searching.
The returned ID array is created by this routine, but it is the responsibility of the caller to free it.
Modifications:
10/27/04 WSK, Created.
2/21/04 WSD can now handle displaced mesh
Parameters:
mesh input - mesh handle
bin input - vertex bin for mesh
lowpoint input - lower corner of bb
highpoint input - upper corner of bb
numVertex_p output - number of vertices within radius
vertexIDs_p output - array of vertex IDs
Definition at line 6312 of file geom.c.
References FC_VertexBin::binWidths, FC_VertexBin::displ, fc_getDisplacedMeshCoords(), fc_getMeshCoordsPtr(), fc_getReturnCodeText(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, fc_isBoundingBoxValid(), fc_isMeshValid(), fc_isVariableValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, fc_sortIntArray(), FC_SUCCESS, FC_VertexBin::lowerCoords, FC_VertexBin::mesh, FC_VertexBin::numBins, FC_VertexBin::numDim, FC_VertexBin::numVertex, FC_VertexBin::upperCoords, and FC_VertexBin::vertexIDs.
Referenced by fc_getEntitiesWithinBoundingBox().
{
  FC_ReturnCode rc;
  int i, j, k, m, n;
  int numVert, maxNumVert, *vertIDs, *temp;
  int lowerICoords[3] = { 0, 0, 0 };
  int upperICoords[3] = { 0, 0, 0 };
  double lower, upper;
  int intersects = 1; // true;
  double* coords;
  int do_displ;
  // default return
  if (numVertex_p)
    *numVertex_p = -1;
  if (vertexIDs_p)
    *vertexIDs_p = NULL;
  // check input
  if (!fc_isMeshValid(mesh) || !bin || !FC_HANDLE_EQUIV(mesh, bin->mesh) ||
      !fc_isBoundingBoxValid(bin->numDim, lowpoint, highpoint) ||
      !numVertex_p || !vertexIDs_p) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Finding vertices within given bounding box.");
  // determine i,j,k bounding box for bins = intersection with bounding box
  for (i = 0; i < bin->numDim; i++) {
    lower = lowpoint[i];
    upper = highpoint[i];
    // special case - no intersection
    if (lower > bin->upperCoords[i] || upper < bin->lowerCoords[i]) {
      intersects = 0; // false
      break;
    }
    else {
      lowerICoords[i] = (int) ((lower - bin->lowerCoords[i])/bin->binWidths[i]);
      upperICoords[i] = (int) ((upper - bin->lowerCoords[i])/bin->binWidths[i]);
      if (lowerICoords[i] < 0)
        lowerICoords[i] = 0;
      else if (lowerICoords[i] >= bin->numBins[i])
        lowerICoords[i] = bin->numBins[i] - 1;
      if (upperICoords[i] < 0)
        upperICoords[i] = 0;
      else if (upperICoords[i] >= bin->numBins[i])
        upperICoords[i] = bin->numBins[i] - 1;
    }
  }
  // early return
  if (intersects == 0) {
    *numVertex_p = 0;
    return FC_SUCCESS;
  }
  // Setup
  if (fc_isVariableValid(bin->displ)) {
    do_displ = 1;
    rc = fc_getDisplacedMeshCoords(mesh, bin->displ, &coords);
  }
  else {
    do_displ = 0;
    rc = fc_getMeshCoordsPtr(mesh, &coords);
  }
  if (rc != FC_SUCCESS)
    return rc;
  numVert = 0;
  maxNumVert = 0;
  vertIDs = NULL;
  // just check vertices in bins in i,j,k bounding box
  for (i = lowerICoords[0]; i <= upperICoords[0]; i++) {
    for (j = lowerICoords[1]; j <= upperICoords[1]; j++) {
      for (k = lowerICoords[2]; k <= upperICoords[2]; k++) {
        for (m = 0; m < bin->numVertex[i][j][k]; m++) {
       int vertID = bin->vertexIDs[i][j][k][m];
       intersects = 1;
          for (n = 0; n < bin->numDim; n++) {
         if (coords[vertID*bin->numDim+n] < lowpoint[n] ||
          coords[vertID*bin->numDim+n] > highpoint[n]) {
           intersects = 0;
           break;
         }
       }
          if (intersects) {
         if (numVert == maxNumVert) {
           if (maxNumVert == 0)
          maxNumVert = 2;
           else
          maxNumVert *= 2;
           temp = realloc(vertIDs, maxNumVert*sizeof(int));
           if (!temp) {
          free(vertIDs);
          fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
          return FC_MEMORY_ERROR;
           }
           vertIDs = temp;
         }
            vertIDs[numVert] = bin->vertexIDs[i][j][k][m];
            numVert++;
          }
        }
      }
    }
  }
  if (do_displ)
    free(coords);
  // organize results
  if (numVert > 0)
    fc_sortIntArray(numVert, vertIDs);
  *numVertex_p = numVert;
  *vertexIDs_p = vertIDs;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_getVertexIDsWithinSphereUsingVertexBin (FC_Mesh mesh, FC_VertexBin * bin, FC_Coords center, double radius, int * numVertex_p, int ** vertexIDs_p)
Find all vertices within a given radius of a point.
Description:
Takes a point and a radius, and returns the IDs of all vertices which are within the described sphere, regardless of the element (connectivity) information in the mesh. To use this routine, you must first call fc_createMeshVertexBin to make the vertex bins used for searching.
The returned ID array is created by this routine, but it is the responsibility of the caller to free it.
This routine will produce the same results as fc_markGeomNeighbors. It should be used when you plan to perform multiple queries.
Modifications:
03/09/04 WSK, Created.
06/30/04 WSK Changed interface to return int array.
Parameters:
mesh input - mesh handle
bin input - vertex bins
center input - center of sphere
radius input - radius of sphere
numVertex_p output - number of vertices within radius
vertexIDs_p output - array of vertex IDs
Definition at line 6462 of file geom.c.
References FC_VertexBin::binWidths, FC_VertexBin::displ, fc_getDisplacedMeshCoords(), fc_getMeshCoordsPtr(), fc_getReturnCodeText(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, fc_isMeshValid(), fc_isVariableValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, fc_sortIntArray(), FC_SUCCESS, FC_VertexBin::lowerCoords, FC_VertexBin::mesh, FC_VertexBin::numBins, FC_VertexBin::numDim, FC_VertexBin::numVertex, FC_VertexBin::upperCoords, and FC_VertexBin::vertexIDs.
Referenced by fc_getEntitiesWithinSphere().
{
  FC_ReturnCode rc;
  int i, j, k, m, n;
  int numVert, maxNumVert, *vertIDs, *temp;
  double r2, t2, d;
  int lowerICoords[3] = { 0, 0, 0 };
  int upperICoords[3] = { 0, 0, 0 };
  double lower, upper;
  int intersects = 1; // true;
  double* coords;
  int do_displ;
  // default return
  if (numVertex_p)
    *numVertex_p = -1;
  if (vertexIDs_p)
    *vertexIDs_p = NULL;
  // check input
  if (!fc_isMeshValid(mesh) || !bin || !FC_HANDLE_EQUIV(mesh, bin->mesh) ||
      !center || radius < 0. || !numVertex_p || !vertexIDs_p) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Finding vertices within a sphere");
  // algorithm - Most efficient algorithm would only need to search bins
  // that intersect boundary of the sphere - do not take  vertices from bins
  // completely outside of sphere and take all vertices from bins completely
  // inside of sphere. But determining intersection of sphere with the bins
  // is difficult. So instead, here we search all bins that intersect or
  // are within the bounding box of the sphere.
  // determine i,j,k bounding box for bins = intersection with sphere's bounding box
  for (i = 0; i < bin->numDim; i++) {
    lower = center[i] - radius;
    upper = center[i] + radius;
    // special case - no intersection
    if (lower > bin->upperCoords[i] || upper < bin->lowerCoords[i]) {
      intersects = 0; // false
      break;
    }
    else {
      lowerICoords[i] = (int) ((lower - bin->lowerCoords[i])/bin->binWidths[i]);
      upperICoords[i] = (int) ((upper - bin->lowerCoords[i])/bin->binWidths[i]);
      if (lowerICoords[i] < 0)
        lowerICoords[i] = 0;
      else if (lowerICoords[i] >= bin->numBins[i])
        lowerICoords[i] = bin->numBins[i] - 1;
      if (upperICoords[i] < 0)
        upperICoords[i] = 0;
      else if (upperICoords[i] >= bin->numBins[i])
        upperICoords[i] = bin->numBins[i] - 1;
    }
  }
  // early return
  if (intersects == 0) {
    *numVertex_p = 0;
    return FC_SUCCESS;
  }
  // Setup
  if (fc_isVariableValid(bin->displ)) {
    do_displ = 1;
    rc = fc_getDisplacedMeshCoords(mesh, bin->displ, &coords);
  }
  else {
    do_displ = 0;
    rc = fc_getMeshCoordsPtr(mesh, &coords);
  }
  if (rc != FC_SUCCESS)
    return rc;
  numVert = 0;
  maxNumVert = 0;
  vertIDs = NULL;
  // just check vertices in bins in i,j,k bounding box
  r2 = radius * radius;
  for (i = lowerICoords[0]; i <= upperICoords[0]; i++) {
    for (j = lowerICoords[1]; j <= upperICoords[1]; j++) {
      for (k = lowerICoords[2]; k <= upperICoords[2]; k++) {
        for (m = 0; m < bin->numVertex[i][j][k]; m++) {
          t2 = 0;
          for (n = 0; n < bin->numDim; n++) {
            d = center[n] - coords[bin->vertexIDs[i][j][k][m]*bin->numDim+n];
            t2 += d * d;
          }
          if (t2 <= r2) {
         if (numVert == maxNumVert) {
           if (maxNumVert == 0)
          maxNumVert = 2;
           else
          maxNumVert *= 2;
           temp = realloc(vertIDs, maxNumVert*sizeof(int));
           if (!temp) {
          free(vertIDs);
          fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
          return FC_MEMORY_ERROR;
           }
           vertIDs = temp;
         }
            vertIDs[numVert] = bin->vertexIDs[i][j][k][m];
            numVert++;
          }
        }
      }
    }
  }
  if (do_displ)
    free(coords);
  // organize results
  if (numVert > 0)
    fc_sortIntArray(numVert, vertIDs);
  *numVertex_p = numVert;
  *vertexIDs_p = vertIDs;
  return FC_SUCCESS;
}