FCLib: (Private)
(Private)
[Topological Relations]
Functions
FC_ReturnCode _fc_getVertexParents (FC_Mesh mesh, int vertexID, FC_AssociationType parent_assoc, int *numParent, int **parentIDs)
Get mesh entities which contain the given vertex.
FC_ReturnCode _fc_getEdgeParents (FC_Mesh mesh, int edgeID, FC_AssociationType parent_assoc, int *numParent, int **parentIDs)
Get mesh entities which contain the given edge.
FC_ReturnCode _fc_getFaceParents (FC_Mesh mesh, int faceID, FC_AssociationType parent_assoc, int *numParent, int **parentIDs)
Get mesh entities which contain the given face.
FC_ReturnCode _fc_getVertexNeighbors (FC_Mesh mesh, int vertexID, int *numNeigh, int **neighIDs)
Get vertices which are neighbors of this vertex.
FC_ReturnCode _fc_getEdgeNeighbors (FC_Mesh mesh, int edgeID, int *numNeigh, int **neighIDs)
Get edges which are neighbors of this edge.
FC_ReturnCode _fc_getFaceNeighbors (FC_Mesh mesh, int faceID, int shared_dim, int *numNeigh, int **neighIDs)
Get faces which are neighbors of this faces.
FC_ReturnCode _fc_getElementNeighbors (FC_Mesh mesh, int elemID, int shared_dim, int *numNeigh, int **neighIDs)
Get the neighbors of an element.
FC_ReturnCode _fc_growNeighborList (FC_Mesh mesh, FC_SortedIntArray *srcIDs, FC_AssociationType assoc, int level, int shared_dim, int *checked, FC_SortedIntArray *keepIDs)
Get the neighbors of a group of mesh entities.
Function Documentation
FC_ReturnCode _fc_getEdgeNeighbors (FC_Mesh mesh, int edgeID, int * numNeigh, int ** neighIDs)
Get edges which are neighbors of this edge.
Description:
Returns the neighbor edges of the given edge. Edges are considered to be neighbors if they are connected by a vertex.
Modifications:
07/23/04 WSK, created.
Parameters:
mesh input - the mesh
edgeID input - edge ID
numNeigh output - the number of neighbors
neighIDs output - the neighbor IDs
Definition at line 1072 of file topo.c.
References _fc_getMeshEdgeParentsOfVerticesPtr(), fc_addIntArrayToSortedIntArray(), fc_convertSortedIntArrayToIntArray(), fc_deleteIntFromSortedIntArray(), fc_getMeshEdgeConnsPtr(), fc_getMeshNumEdge(), fc_getReturnCodeText(), fc_initSortedIntArray(), FC_INPUT_ERROR, fc_isMeshValid(), fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by fc_getMeshEntityNeighbors().
  {
  FC_ReturnCode rc;
  int i;
  int numEdge, *edgeConns, *numEdgePerVert, **edgeParentsPerVert;
  FC_SortedIntArray sia;
  // default return
  if (numNeigh)
    *numNeigh = -1;
  if (neighIDs)
    *neighIDs = NULL;
  // check input
  if (!fc_isMeshValid(mesh) || edgeID < 0 || !numNeigh || !neighIDs) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  rc = fc_getMeshNumEdge(mesh, &numEdge);
  if (rc != FC_SUCCESS || edgeID >= numEdge) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting edges which are neighbors of this edge.");
  // setup
  rc = fc_getMeshEdgeConnsPtr(mesh, &edgeConns);
  if (rc != FC_SUCCESS)
    return rc;
  rc = _fc_getMeshEdgeParentsOfVerticesPtr(mesh, &numEdgePerVert,
                                       &edgeParentsPerVert);
  if (rc != FC_SUCCESS)
    return rc;
  // Get all edges that own vertices from this edge
  fc_initSortedIntArray(&sia);
  for (i = 0; i < 2; i++) {
    int vertID = edgeConns[edgeID*2+i];
    int ret = fc_addIntArrayToSortedIntArray(&sia, numEdgePerVert[vertID],
                              edgeParentsPerVert[vertID], 0);
    if (ret < 0) {
      fc_printfErrorMessage("Failed to add int to sia");
      return ret;
    }
  }
  // remove this edge from list
  fc_deleteIntFromSortedIntArray(&sia, edgeID);
  // get array
  rc = fc_convertSortedIntArrayToIntArray(&sia, numNeigh, neighIDs);
  return rc;
}
FC_ReturnCode _fc_getEdgeParents (FC_Mesh mesh, int edgeID, FC_AssociationType parent_assoc, int * numParent, int ** parentIDs)
Get mesh entities which contain the given edge.
Description:
Specify an edge and mesh entity (e.g. element) and this routines returns IDs of that type of mesh entity which contain (are made from) the given edge.
Todo:
Make sure only calls edges/face stuff when it needs to. Cleanup!
Modifications:
07/09/04 WSK created.
Parameters:
mesh input - mesh
edgeID input - edge id
parent_assoc input - association type of the parent
numParent output - the number of parents
parentIDs output - array of parent IDs
Definition at line 798 of file topo.c.
References _fc_getMeshElementParentsOfEdgesPtr(), _fc_getMeshFaceParentsOfVerticesPtr(), fc_addIntToSortedIntArray(), FC_AT_EDGE, FC_AT_ELEMENT, FC_AT_FACE, FC_AT_UNKNOWN, FC_AT_VERTEX, FC_AT_WHOLE_MESH, fc_convertSortedIntArrayToIntArray(), FC_ERROR, fc_getMeshEdgeConnsPtr(), fc_getMeshNumEdge(), fc_getReturnCodeText(), fc_initSortedIntArray(), FC_INPUT_ERROR, fc_isAssociationTypeValid(), fc_isMeshValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by fc_getMeshEntityParents().
  {
  FC_ReturnCode rc;
  int i, j;
  int numEdge;
  FC_SortedIntArray sia;
  int* edgeConns;
  // default return values
  if (numParent)
    *numParent = -1;
  if (parentIDs)
    *parentIDs = NULL;
  // check input
  if (!fc_isMeshValid(mesh) || edgeID < 0 ||
      !fc_isAssociationTypeValid(parent_assoc) ||
      parent_assoc == FC_AT_VERTEX || parent_assoc == FC_AT_EDGE ||
      parent_assoc == FC_AT_UNKNOWN || !numParent || !parentIDs) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // get mesh info
  rc = fc_getMeshNumEdge(mesh, &numEdge);
  if (rc != FC_SUCCESS || edgeID >= numEdge) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  rc = fc_getMeshEdgeConnsPtr(mesh, &edgeConns);
  if (rc != FC_SUCCESS)
    return rc;
  // log message
  fc_printfLogMessage("Getting mesh entities which contain the given edge.");
  // type of parent
  if (parent_assoc == FC_AT_WHOLE_MESH) {
    *numParent = 1;
    *parentIDs = (int*)calloc(1, sizeof(int));
    if (*parentIDs == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    return FC_SUCCESS;
  }
  else if (parent_assoc == FC_AT_ELEMENT) {
    int *numElemPerEdge, **elemParentsPerEdge;
    rc = _fc_getMeshElementParentsOfEdgesPtr(mesh, &numElemPerEdge,
                                          &elemParentsPerEdge);
    if (rc != FC_SUCCESS)
      return rc;
    *numParent = numElemPerEdge[edgeID];
    *parentIDs = (int*)malloc(*numParent*sizeof(int));
    if (*parentIDs == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    for (i = 0; i < *numParent; i++)
      (*parentIDs)[i] = elemParentsPerEdge[edgeID][i];
    return FC_SUCCESS;
  }
  else if (parent_assoc == FC_AT_FACE) {
    int *numFacePerVert, **faceParentsPerVert;
    int vertID1, vertID2, numFace1, numFace2, *faceIDs1, *faceIDs2;
    fc_initSortedIntArray(&sia);
    rc = _fc_getMeshFaceParentsOfVerticesPtr(mesh, &numFacePerVert,
                                         &faceParentsPerVert);
    if (rc != FC_SUCCESS)
      return rc;
    if (numFacePerVert == 0) {
      *numParent = 0;
      *parentIDs = NULL;
      return FC_SUCCESS;
    }
    vertID1 = edgeConns[edgeID*2];
    vertID2 = edgeConns[edgeID*2+1];
    numFace1 = numFacePerVert[vertID1];
    numFace2 = numFacePerVert[vertID2];
    faceIDs1 = faceParentsPerVert[vertID1];
    faceIDs2 = faceParentsPerVert[vertID2];
    // WSK - thought about walking the two lists at the same time for
    // speedup, but that would require lists to be sorted, and since
    // these lists are usually small, speedup would probably be minimal.
    for (i = 0; i < numFace1; i++) {
      for (j = 0; j < numFace2; j++) {
        if (faceIDs1[i] == faceIDs2[j]) {
          int ret = fc_addIntToSortedIntArray(&sia, faceIDs1[i]);
          if (ret < 0) {
            fc_printfErrorMessage("Failed to add int to sia");
            return ret;
          }
        }
      }
    }
    rc = fc_convertSortedIntArrayToIntArray(&sia, numParent, parentIDs);
    if (rc != FC_SUCCESS)
      return rc;
    return FC_SUCCESS;
  }
  else {
    fc_printfErrorMessage("shouldn't be able to get here.");
    return FC_ERROR; // shouldn't be able to get here
  }
}
FC_ReturnCode _fc_getElementNeighbors (FC_Mesh mesh, int elemID, int shared_dim, int * numNeigh, int ** neighIDs)
Get the neighbors of an element.
Description:
Returns the elements that are neighbors of the given element. The type of neighbor depends on the input argument 'shared_dim' which is the minimum dimensionality of the overlap between the elements. For example, 0 means that elements that share a vertex, edge or face are neighbors, while 2 means that only elements that share a face are neighbors. The higher the shared_dim, the more restrictive the neighbor condition.
Modifications:
04/24/03 WSK, Create. A more general purpose function to replace _fc_getEdgeNbrs and _fc_getVertexNbrs since they do almost exactly the same.
Parameters:
mesh input - the mesh
elemID input - element number
shared_dim input - the minimum dimensionality of shared entity
numNeigh output - the number of neighbors
neighIDs output - the neighbor IDs
Definition at line 1259 of file topo.c.
References _fc_getMeshElementNeighborsViaEdgePtr(), _fc_getMeshElementNeighborsViaFacePtr(), _fc_getMeshElementNeighborsViaVertexPtr(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isMeshValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by fc_getMeshEntityNeighbors().
  {
  FC_ReturnCode rc;
  int *numElemNeighsViaEntity, **elemNeighsViaEntity;
  // default return
  if (numNeigh)
    *numNeigh = -1;
  if (neighIDs)
    *neighIDs = NULL;
  // check input
  if (!fc_isMeshValid(mesh) || elemID < 0 || shared_dim < 0 || shared_dim > 2
      || !numNeigh || !neighIDs) {
        fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting the neighbors of an element.");
  // Get entity specific info
  switch (shared_dim) {
  case 0:
    rc = _fc_getMeshElementNeighborsViaVertexPtr(mesh, &numElemNeighsViaEntity,
                                                 &elemNeighsViaEntity);
    break;
  case 1:
    rc = _fc_getMeshElementNeighborsViaEdgePtr(mesh, &numElemNeighsViaEntity,
                                               &elemNeighsViaEntity);
    break;
  case 2:
    rc = _fc_getMeshElementNeighborsViaFacePtr(mesh, &numElemNeighsViaEntity,
                                               &elemNeighsViaEntity);
    break;
  }
  if (rc != FC_SUCCESS)
    return rc;
  // Copy the ids
  if (numElemNeighsViaEntity == NULL) {
    *numNeigh = 0;
    *neighIDs = NULL;
    return FC_SUCCESS;
  }
  *numNeigh = numElemNeighsViaEntity[elemID];
  if (*numNeigh > 0) {
    *neighIDs = (int*)malloc(*numNeigh*sizeof(int));
    if (*neighIDs == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    memcpy(*neighIDs, elemNeighsViaEntity[elemID], *numNeigh*sizeof(int));
  }
  return FC_SUCCESS;
}
FC_ReturnCode _fc_getFaceNeighbors (FC_Mesh mesh, int faceID, int shared_dim, int * numNeigh, int ** neighIDs)
Get faces which are neighbors of this faces.
Description:
Returns the neighbor faces of the given face. The type of neighbor depends on the input argument 'shared_dim' which is the minimum dimensionality of the overlap between the elements. For example, 0 means that faces share at least a vertex while 1 means that faces must share an edge. The higher the shared_dim, the more more restrictive the neighbor condition.
Modifications:
07/23/04 WSK, created.
Parameters:
mesh input - the mesh
faceID input - face ID
shared_dim input - the minimum dimensionality of shared entity
numNeigh output - the number of neighbors
neighIDs output - the neighbor IDs
Definition at line 1149 of file topo.c.
References _fc_getMeshFaceParentsOfVerticesPtr(), fc_addIntArrayToSortedIntArray(), fc_convertSortedIntArrayToIntArray(), fc_deleteIntFromSortedIntArray(), fc_getMeshFaceConnsPtr(), fc_getMeshNumFace(), fc_getReturnCodeText(), fc_initSortedIntArray(), FC_INPUT_ERROR, fc_isMeshValid(), fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_SortedIntArray::numVal, and FC_SortedIntArray::vals.
Referenced by fc_getMeshEntityNeighbors().
  {
  FC_ReturnCode rc;
  int i, j, k;
  int numFace, maxNumVertPerFace, *numVertPerFace, *faceConns;
  int *numFacePerVert, **faceParentsPerVert;
  //_FC_Vertex *vertices, *vertex_p;
  FC_SortedIntArray sia;
  // default return
  if (numNeigh)
    *numNeigh = -1;
  if (neighIDs)
    *neighIDs = NULL;
  // check input
  if (!fc_isMeshValid(mesh) || faceID < 0 || shared_dim < 0 || shared_dim > 1
      || !numNeigh || !neighIDs) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  rc = fc_getMeshNumFace(mesh, &numFace);
  if (rc != FC_SUCCESS || faceID >= numFace) {
        fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting faces which are neighbors of this face.");
  // setup
  rc = fc_getMeshFaceConnsPtr(mesh, &numVertPerFace, &maxNumVertPerFace,
                              &faceConns);
  if (rc != FC_SUCCESS)
    return rc;
  rc = _fc_getMeshFaceParentsOfVerticesPtr(mesh, &numFacePerVert,
                                      &faceParentsPerVert);
  if (rc != FC_SUCCESS)
    return rc;
  // Vertex neighbors: Get all faces that own vertices from this face
  fc_initSortedIntArray(&sia);
  for (i = 0; i < numVertPerFace[faceID]; i++) {
    int vertID = faceConns[faceID*maxNumVertPerFace+i];
    int ret = fc_addIntArrayToSortedIntArray(&sia, numFacePerVert[vertID],
                              faceParentsPerVert[vertID], 0);
    if (ret < 0) {
      fc_printfErrorMessage("Failed to add ID to sia");
      return ret;
    }
  }
  // remove this face from list
  fc_deleteIntFromSortedIntArray(&sia, faceID);
  // Edge neighbors - remove faces that don't have 2 verts from this face
  if (shared_dim == 1) {
    k = 0;
    while (k < sia.numVal) {
      int currentID = sia.vals[k];
      int found = 0;
      for (i = 0; i < numVertPerFace[faceID]; i++) {
        for (j = 0; j < numVertPerFace[currentID]; j++) {
          if (faceConns[faceID*maxNumVertPerFace+i] ==
              faceConns[currentID*maxNumVertPerFace+j]) {
            found++;
            break;
          }
        }
        if (found == 2)
          break;
      }
      if (found < 2) {
        fc_deleteIntFromSortedIntArray(&sia, currentID);
      }
      else {
     k++;
      }
    }
  }
  // get array
  rc = fc_convertSortedIntArrayToIntArray(&sia, numNeigh, neighIDs);
  return rc;
}
FC_ReturnCode _fc_getFaceParents (FC_Mesh mesh, int faceID, FC_AssociationType parent_assoc, int * numParent, int ** parentIDs)
Get mesh entities which contain the given face.
Description:
Specify a face and mesh entity (e.g. element) and this routines returns IDs of that type of mesh entity which contain (are made from) the given face.
Modifications:
07/12/04 WSK created.
Parameters:
mesh input - mesh
faceID input - face id
parent_assoc input - association type of the parent
numParent output - the number of parents
parentIDs output - array of parent IDs
Definition at line 922 of file topo.c.
References _fc_getMeshElementParentsOfFacesPtr(), FC_AT_ELEMENT, FC_AT_WHOLE_MESH, FC_ERROR, fc_getMeshNumFace(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isMeshValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by fc_getMeshEntityParents().
  {
  FC_ReturnCode rc;
  int i;
  int numFace;
  // default return values
  if (numParent)
    *numParent = -1;
  if (parentIDs)
    *parentIDs = NULL;
  // check input
  if (!fc_isMeshValid(mesh) || faceID < 0 ||
      (parent_assoc != FC_AT_ELEMENT && parent_assoc != FC_AT_WHOLE_MESH) ||
      !numParent || !parentIDs) {
        fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // get mesh info
  rc = fc_getMeshNumFace(mesh, &numFace);
  if (rc != FC_SUCCESS || faceID >= numFace) {
        fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting mesh entities which contain the given face.");
  // type of parent
  if (parent_assoc == FC_AT_WHOLE_MESH) {
    *numParent = 1;
    *parentIDs = (int*)calloc(1, sizeof(int));
    if (*parentIDs == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    return FC_SUCCESS;
  }
  else if (parent_assoc == FC_AT_ELEMENT) {
    int* numElemPerFace, **elemParentsPerFace;
    rc = _fc_getMeshElementParentsOfFacesPtr(mesh, &numElemPerFace,
                                          &elemParentsPerFace);
    if (rc != FC_SUCCESS)
      return rc;
    *numParent = numElemPerFace[faceID];
    if (*numParent > 0) {
      *parentIDs = (int*)malloc(*numParent*sizeof(int));
      if (*parentIDs == NULL) {
        fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
        return FC_MEMORY_ERROR;
      }
      for (i = 0; i < *numParent; i++)
        (*parentIDs)[i] = elemParentsPerFace[faceID][i];
    }
    return FC_SUCCESS;
  }
  else {
        fc_printfErrorMessage("shouldn't be able to get here.");
    return FC_ERROR; // shouldn't be able to get here
  }
}
FC_ReturnCode _fc_getVertexNeighbors (FC_Mesh mesh, int vertexID, int * numNeigh, int ** neighIDs)
Get vertices which are neighbors of this vertex.
Description:
Returns the neighbor vertices of the given vertices. Vertices are considered to be neighbors if they are connected by an edge.
Modifications:
Nancy Collins Added this wrapper around steph's original routine to use compute the neighbors and extract them in a subset.
02/24/04 WSK, changed name and made more general purpose, like with _fc_getElementTopoNeighbors.
07/15/04 WSK - Changed to not be recursive.
Parameters:
mesh input - the mesh
vertexID input - vertex ID
numNeigh output - the number of neighbors
neighIDs output - the neighbor IDs
Definition at line 1007 of file topo.c.
References _fc_getMeshVertexNeighborsViaEdgePtr(), fc_getMeshNumVertex(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isMeshValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by fc_getMeshEntityNeighbors().
  {
  FC_ReturnCode rc;
  int numVertex, *numVertNeighsViaEdge, **vertNeighsViaEdge;
  // default return
  if (numNeigh)
    *numNeigh = -1;
  if (neighIDs)
    *neighIDs = NULL;
  // check input
  if (!fc_isMeshValid(mesh) || vertexID < 0 || !numNeigh || !neighIDs) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  rc = fc_getMeshNumVertex(mesh, &numVertex);
  if (rc != FC_SUCCESS || vertexID >= numVertex) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting vertices which are neighbors of this vertex.");
  // copy array from Big Data struct
  rc = _fc_getMeshVertexNeighborsViaEdgePtr(mesh, &numVertNeighsViaEdge,
                                            &vertNeighsViaEdge);
  if (rc != FC_SUCCESS)
    return rc;
  // special case -- if edges don't exists
  if (numVertNeighsViaEdge == NULL) {
    *numNeigh = 0;
    neighIDs = NULL;
    return FC_SUCCESS;
  }
  *numNeigh = numVertNeighsViaEdge[vertexID];
  if (*numNeigh > 0) {
    *neighIDs = (int*)malloc((*numNeigh)*sizeof(int));
    if (*neighIDs == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    memcpy(*neighIDs, vertNeighsViaEdge[vertexID], *numNeigh*sizeof(int));
  }
  return FC_SUCCESS;
}
FC_ReturnCode _fc_getVertexParents (FC_Mesh mesh, int vertexID, FC_AssociationType parent_assoc, int * numParent, int ** parentIDs)
Get mesh entities which contain the given vertex.
Description:
Specify a vertex and mesh entity (e.g. element) and this routines returns IDs of that type of mesh entity which contain (are made from) the given vertex.
Modifications:
07/09/04 WSK created.
Parameters:
mesh input - mesh
vertexID input - vertex number
parent_assoc input - association type of the parent
numParent output - the number of parents
parentIDs output - array of parent IDs
Definition at line 696 of file topo.c.
References _fc_getMeshEdgeParentsOfVerticesPtr(), _fc_getMeshElementParentsOfVerticesPtr(), _fc_getMeshFaceParentsOfVerticesPtr(), FC_AT_EDGE, FC_AT_ELEMENT, FC_AT_FACE, FC_AT_UNKNOWN, FC_AT_VERTEX, FC_AT_WHOLE_MESH, fc_getMeshNumVertex(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isAssociationTypeValid(), fc_isMeshValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by fc_getMeshEntityParents().
  {
  FC_ReturnCode rc;
  int i;
  int numVertex, *temp_IDs, whole_ids[1] = { 0 };
  int *numEntityPerVert, **entityParentsPerVert;
  // default return values
  if (numParent)
    *numParent = -1;
  if (parentIDs)
    *parentIDs = NULL;
  // check input
  if (!fc_isMeshValid(mesh) || vertexID < 0 ||
      !fc_isAssociationTypeValid(parent_assoc) ||
      parent_assoc == FC_AT_VERTEX || parent_assoc == FC_AT_UNKNOWN ||
      !numParent || !parentIDs) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // get mesh info
  rc = fc_getMeshNumVertex(mesh, &numVertex);
  if (rc != FC_SUCCESS || vertexID >= numVertex) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting mesh entities which contain the given vertex.");
  // get the number of parents & pointer to parent array to copy
  if (parent_assoc == FC_AT_WHOLE_MESH) {
    *numParent = 1;
    temp_IDs = whole_ids;
  }
  else {
    switch (parent_assoc) {
    case FC_AT_EDGE:
      rc = _fc_getMeshEdgeParentsOfVerticesPtr(mesh, &numEntityPerVert,
                                           &entityParentsPerVert);
      break;
    case FC_AT_FACE:
      rc = _fc_getMeshFaceParentsOfVerticesPtr(mesh, &numEntityPerVert,
                                           &entityParentsPerVert);
      break;
    case FC_AT_ELEMENT:
      rc = _fc_getMeshElementParentsOfVerticesPtr(mesh, &numEntityPerVert,
                                              &entityParentsPerVert);
      break;
    default:
      ; // do nothing, just here to quiet compiler
    }
    if (rc != FC_SUCCESS)
      return rc;
    // check to make sure entities of that type exist
    if (numEntityPerVert == NULL) {
      *numParent = 0;
      *parentIDs = NULL;
      return FC_SUCCESS;
    }
    // finally, set values
    *numParent = numEntityPerVert[vertexID];
    temp_IDs = entityParentsPerVert[vertexID];
  }
  // make parent ID array
  if (*numParent > 0) {
    *parentIDs = (int*)malloc(*numParent*sizeof(int));
    if (*parentIDs == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    for (i = 0; i < *numParent; i++)
      (*parentIDs)[i] = temp_IDs[i];
  }
  return FC_SUCCESS;
}
FC_ReturnCode _fc_growNeighborList (FC_Mesh mesh, FC_SortedIntArray * srcIDs, FC_AssociationType assoc, int level, int shared_dim, int * checked, FC_SortedIntArray * keepIDs)
Get the neighbors of a group of mesh entities.
Description:
This is a helper function for fc_getSubsetNeighbors(). It takes a list of entities to get neighbors from and adds them to the list of neighbors. It is meant to be called recursively with the first call providing the seed IDs and a null list to add to. In addition, a mask for the association type is provided with all zero entries (can prevent adding specific IDs by setting their mask entry to one).
Entities cannot be of association type FC_AT_WHOLE_DATASET.
Modifications:
07/023/04 WSK Created.
Parameters:
mesh input - the mesh the entities are in
srcIDs input - List of IDs to get neighbors from
assoc input - the type of entity
level input - depth of recursion (1 = no recursion)
shared_dim input - neighbor shared dimensionality
checked input - mask allocated by caller
keepIDs input/output - list of neighbor IDs
Definition at line 1341 of file topo.c.
References _fc_growNeighborList(), fc_addIntArrayToSortedIntArray(), fc_addIntToSortedIntArray(), fc_freeSortedIntArray(), fc_getMeshEntityNeighbors(), fc_initSortedIntArray(), fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, FC_SortedIntArray::numVal, and FC_SortedIntArray::vals.
Referenced by _fc_growNeighborList(), and fc_getSubsetNeighbors().
  {
  FC_ReturnCode rc;
  int i, j;
  FC_SortedIntArray newIDs;
  int numNeigh, *neighIDs;
  // input no checking because it's a helper function
  // log message
  fc_printfLogMessage("Getting the neighbors of a group of mesh entities.");
  // go through srcIDs & get unexamined neighbors
  fc_initSortedIntArray(&newIDs);
  for (j = 0; j < srcIDs->numVal; j++) {
    int currentID = srcIDs->vals[j];
    if (checked[currentID])
      continue;
    // check it's neighbors
    rc = fc_getMeshEntityNeighbors(mesh, currentID, assoc, shared_dim,
                       &numNeigh, &neighIDs);
    if (rc != FC_SUCCESS)
      return rc;
    for (i = 0; i < numNeigh; i++) {
        if (!checked[neighIDs[i]]) {
          int ret = fc_addIntToSortedIntArray(&newIDs, neighIDs[i]);
          if (ret < 0) {
            fc_printfErrorMessage("Failed to add ID to list");
            return ret;
          }
        }
    }
    free(neighIDs);
    checked[currentID] = 1;
  }
  // add the new neighbors to our keep list
  rc = fc_addIntArrayToSortedIntArray(keepIDs, newIDs.numVal,
                          newIDs.vals, 1);
  if (rc < FC_SUCCESS)
    return rc;
  // call recursively
  if (level == 1 || newIDs.numVal == 0) {
    fc_freeSortedIntArray(&newIDs);
    return FC_SUCCESS;
  }
  else {
    rc = _fc_growNeighborList(mesh, &newIDs, assoc, level-1,
                               shared_dim, checked, keepIDs);
    fc_freeSortedIntArray(&newIDs);
    return rc;
  }
}