FCLib: Shape
Shape
[FCLib API]
Detailed Description
Information about Shapes.
Description:
Information about Shapes (shapes of meshes etc). These may have a topological flavor to them, but since they arent heirarchical (e.g., children-parent), they are being located here rather than Topological Relations. This is meant to work in conjunction with Element Death e.g., given some information about the shape of a mesh is there some information about a dead element region that would be of interest, such as the region cutting through the shape ?
Modules
(Private)
Data Structures
struct FC_Shape
Shape Struct.
Creating General Shapes from Subsets and Meshes
FC_ReturnCode fc_getSubsetShapes (FC_Subset in_subset, double comp_angle, int shared_dim, int *numShapes, FC_Shape **shapes)
given a subset, returns an array of FC_Shapes
FC_ReturnCode fc_getMeshShapes (FC_Mesh mesh, double comp_angle, int shared_dim, int *numShapes, FC_Shape **shapes)
given a mesh, returns an array of FC_Shapes
FC_ReturnCode fc_reshapeByAngle (FC_Shape *inshape, double newangle, int seg_dim, FC_Shape *newshape)
given a shape and a new angle, creates a new shape where the sides are distinguished byt he new angle
FC_ReturnCode fc_reduceShapeNumSides (FC_Shape *inshape, int reducedNumSides, FC_Shape *reducedshape)
given a shape and a desired number of sides, fewer than the current number of sides, creates a new shape with the desired number of sides
Shape Helpers
FC_ReturnCode fc_copyShape (FC_Shape *inshape, FC_Shape *outshape)
Copy a shape.
FC_ReturnCode fc_reorderShape (int *neworder, FC_Shape *shape)
given a new ordering of the sides, reorders a shape
FC_ReturnCode fc_freeShape (FC_Shape *fcss)
frees a Shape
FC_ReturnCode fc_clearShape (FC_Shape *fcss)
clears the allocated shape memory, but leaves the subsets alive
FC_ReturnCode fc_initShape (FC_Shape *fcss)
inits a Shape
FC_ReturnCode fc_printShape (FC_Shape *fcss, char *label, int verb)
prints a Shape
Side Orders
FC_ReturnCode fc_createScrewShapeOrder (FC_Shape *shape, int **neworder)
given a shape, returns the reordering array for a screw
FC_ReturnCode fc_createDescendingAreaOrder (FC_Shape *shape, int **neworder)
given a shape returns an array of the side ids in descending face area order
FC_ReturnCode fc_createLargeAndNonAdjacentSidesOrder (FC_Shape *shape, int **neworder)
As an approximation to obtaining the major sides of a thin shape, given a shape returns an array of the side ids in the ordered desired for shape with a large side and a non-adjacent side, subject to certain constraints.
FC_ReturnCode fc_createLargeAndOpposingSidesOrder (FC_Shape *shape, double maxangle, int **neworder)
As an approximation to obtaining the major sides of a thin shape, given a shape returns an array of the side ids in the ordered desired for a shape with a large and opposing side.
Adjacencies
FC_ReturnCode fc_createSideAdjacencyMatrix (int numSubsets, FC_Subset *subsets, int shared_dim, int ***intmatrix)
Given an array of subsets specifying the faces of each side of a shape, returns a matrix specifying the side adjacencies.
FC_ReturnCode fc_segmentAdjacencyMatrix (int matrixdim, int **adjmatrix, int *numsegments, int **sidespersegment, int ***sideids)
Given an adjacency matrix, returns segments of it based on connectivities.
FC_ReturnCode fc_calcDistanceMatrix (int nsides, int **adjmatrix, int ***distmatrix)
Given an nxn adjacency matrix returns the (shortestpath) distance matrix.
Misc
FC_ReturnCode fc_getShapeEnds (FC_Shape *shape, int *numEnds, int **endArray)
given a shape returns the shape's ends.
FC_ReturnCode fc_getShapeSidesAreas (FC_Shape *shape, double **area)
Given a Shape, returns the (non-displaced) area for each side.
FC_ReturnCode fc_getPlanarSideNormal (FC_Shape *shape, int sideid, FC_Coords *normal)
Given a shape and the ID of a planar side, returns the outward normal to that face.
FC_ReturnCode fc_getSideNormalMeanSdev (FC_Shape *shape, int sideid, FC_Vector *mean, FC_Vector *std)
Given a shape and a sideid, returns the outward normal and std in each direction to that face.
Function Documentation
FC_ReturnCode fc_calcDistanceMatrix (int nsides, int ** adjmatrix, int *** distmatrix)
Given an nxn adjacency matrix returns the (shortestpath) distance matrix.
Description:
Given an nxn adjacency matrix returns the (shortest path) distance matrix. This is not limited to cases where the adj matrix represents the adj of the sides, but it is intended to be used in that way. Does not take advantage of the symmetry of the adj matrix, so this could be used for non symm matricies. Uses Floyd's algorithm
Note: -1 is used for infinite distance entries.
Note: in theory, this should work for weighted entries; I haven't tried this however, since this method isnt in here for general matrix calculations, but as a precursor for determining side pairs of interest.
Modifications:
12/21/05 ACG created.
01/30/05 ACG changed return val so infinite distance entries return value = -1.
Parameters:
nsides input - nsides (nxn matrix)
adjmatrix input - adj matrix
distmatrix output - distance matrix
Definition at line 3469 of file shape.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by fc_reduceShapeNumSides().
 {
  int** imatrix_a; //intermediatematrix
  int** imatrix_b; //intermediatematrix
  int ***curr, ***next, ***temp;
  int i,j,k;
  //default return
  if (distmatrix)
    *distmatrix = NULL;
  if (!nsides || !adjmatrix || !distmatrix){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Computing Side Distance Matrix");
  // create space for the adj array, initialize to zero
  imatrix_a = calloc(nsides, sizeof(int*));
  imatrix_b = calloc(nsides, sizeof(int*));
  if (imatrix_a == NULL || imatrix_b == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < nsides; i++) {
    imatrix_a[i] = calloc(nsides, sizeof(int));
    imatrix_b[i] = calloc(nsides, sizeof(int));
    if (imatrix_a[i] == NULL || imatrix_b[i] == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
  }
  //intial vals
  for (i = 0; i < nsides; i++){
    imatrix_a[i][i] = 0;
    for (j = 0; j < nsides; j++){
      if (i == j){
     imatrix_a[i][i] = 0;
      } else {
     if (adjmatrix[i][j] == 1){
       imatrix_a[i][j] = 1;
     } else {
       imatrix_a[i][j] = -1;
       //   imatrix_a[i][j] = INT_MAX;
     }
      }
    }
  }
  next = &imatrix_a;
  curr = &imatrix_b;
  for (k = 0; k < nsides; k++){
    temp = next;
    next = curr;
    curr = temp;
    for (i = 0; i < nsides; i++){
      for (j = 0; j < nsides; j++){
     int a = (*curr)[i][j];
     int b;
     //   if ((*curr)[i][k] == INT_MAX || (*curr)[k][j] == INT_MAX){
     //     b = INT_MAX;
     if ((*curr)[i][k] == -1 || (*curr)[k][j] == -1){
       b = -1;
     } else {
       b = (*curr)[i][k]+(*curr)[k][j];
     }
     if (a == -1){
       (*next)[i][j] = b;
     }else if (b == -1){
       (*next)[i][j] = a;
     }else {
       (*next)[i][j] = a < b ? a : b;
     }
     //     (*next)[i][j] = a < b ? a : b;
      }
    }
  }
  for (i = 0; i < nsides; i++){
    free((*curr)[i]);
  }
  free(*curr);
  *distmatrix = *next;
  return FC_SUCCESS;
}
FC_ReturnCode fc_clearShape (FC_Shape * fcss)
clears the allocated shape memory, but leaves the subsets alive
Description:
Clears the allocated shape memory, but leaves the subsets alive. The user will need handles to them to eventually delete them.
Modifications:
08/22/06 ACG created
Parameters:
fcss input - the shape
Definition at line 2370 of file shape.c.
References FC_Shape::adjmatrix, FC_Shape::elems, FC_Shape::faces, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, FC_SUCCESS, and FC_Shape::numSides.
 {
  int i;
  if (!fcss){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  for (i = 0; i < fcss->numSides; i++){
    free(fcss->adjmatrix[i]);
  }
  free(fcss->faces);
  free(fcss->elems);
  free(fcss->adjmatrix);
  fcss->faces= NULL;
  fcss->elems= NULL;
  fcss->adjmatrix= NULL;
  fcss->numSides = 0;
  return FC_SUCCESS;
}
FC_ReturnCode fc_copyShape (FC_Shape * inshape, FC_Shape * outshape)
Copy a shape.
Description:
This is a deep copy; it allocates memory and the created shape will need to be freed by the caller.
Modifications:
06/18/06 ACG created
Parameters:
inshape input - ptr to shape
outshape output - ptr to the shape
Definition at line 2098 of file shape.c.
References FC_Shape::adjmatrix, FC_Shape::elems, FC_Shape::faces, fc_copySubset(), fc_freeShape(), fc_getMeshFromSubset(), fc_getReturnCodeText(), fc_getSubsetName(), fc_initShape(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, and FC_Shape::numSides.
Referenced by fc_reduceShapeNumSides().
 {
  FC_ReturnCode rc;
  FC_Shape shape;
  int i,j;
  //defaults
  if (outshape){
    fc_initShape(outshape);
  }
  if (!inshape || !outshape ){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("copying shape");
  shape.numSides = inshape->numSides;
  shape.faces = (FC_Subset*)malloc(shape.numSides*sizeof(FC_Subset));
  shape.elems = (FC_Subset*)malloc(shape.numSides*sizeof(FC_Subset));
  shape.adjmatrix = (int**)malloc(shape.numSides*sizeof(int*));
  if (!shape.faces || ! shape.elems || ! shape.adjmatrix){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < shape.numSides; i++){
    FC_Mesh mesh; //these really should all be onthe same mesh
    char* subname;
    rc = fc_getMeshFromSubset(inshape->faces[i],&mesh);
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("cant get mesh from subset");
      fc_freeShape(&shape);
      return rc;
    }
    rc = fc_getSubsetName(inshape->faces[i],&subname);
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("cant get name of subset");
      fc_freeShape(&shape);
      return rc;
    }
    //is it ok to use the same name ?
    rc =  fc_copySubset(inshape->faces[i],mesh,subname,&(shape.faces[i]));
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("cant copy subset");
      fc_freeShape(&shape);
      return rc;
    }
    free(subname);
    rc = fc_getMeshFromSubset(inshape->elems[i],&mesh);
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("cant get mesh from subset");
      fc_freeShape(&shape);
      return rc;
    }
    rc = fc_getSubsetName(inshape->elems[i],&subname);
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("cant get name of subset");
      fc_freeShape(&shape);
      return rc;
    }
    //is it ok to use the same name ?
    rc =  fc_copySubset(inshape->elems[i],mesh,subname,&(shape.elems[i]));
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("cant copy subset");
      fc_freeShape(&shape);
      return rc;
    }
    free(subname);
    shape.adjmatrix[i] = (int*)malloc(shape.numSides*sizeof(int));
    if (!shape.adjmatrix[i]){
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
  }
  for (i = 0; i < shape.numSides; i++){
    for (j = 0; j < shape.numSides; j++){
      shape.adjmatrix[i][j] = inshape->adjmatrix[i][j];
    }
  }
  outshape->numSides = shape.numSides;
  outshape->faces = shape.faces;
  outshape->elems = shape.elems;
  outshape->adjmatrix = shape.adjmatrix;
  return FC_SUCCESS;
}
FC_ReturnCode fc_createDescendingAreaOrder (FC_Shape * shape, int ** neworder)
given a shape returns an array of the side ids in descending face area order
Description:
Given a shape returns an array of the side ids in descending face area order. This can then be fed into fc_reorderShape
Modifications:
06/18/06 ACG, created
06/19/06 ACG updated to reflect change in the ordering of the array expected by reorderShape, unittested
09/27/06 ACG changed from ascending to descending
Parameters:
shape input - shape
neworder output - ids of sides
Definition at line 2669 of file shape.c.
References fc_getReturnCodeText(), fc_getShapeSidesAreas(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, and FC_Shape::numSides.
Referenced by createShapeWOrder(), fc_createLargeAndNonAdjacentSidesOrder(), and fc_createLargeAndOpposingSidesOrder().
    {
  FC_ReturnCode rc;
  double *areas;
  int numSides;
  int *order;
  int i,j;
  //defaults
  if (neworder)
    *neworder = NULL;
  if ( !shape ||  !neworder){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting descending area order");
  numSides = shape->numSides;
  rc= fc_getShapeSidesAreas(shape,&areas);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("cant get sides areas");
    return rc;
  }
  order = (int*)malloc(numSides*sizeof(int));
  if (order == NULL){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i =0; i < numSides; i++){
    order[i] = i;
  }
  //order sides by area
  //sort sides areas. yes i know, its bubblesort.
  {
    double tempa;
    int tempi;
    int test;
    for(i = numSides - 1; i > 0; i--){
      test=0;
      for(j = 0; j < i; j++){
     if (areas[j] > areas[j+1]){
       tempa = areas[j];
       areas[j] = areas[j+1];
       areas[j+1] = tempa;
       tempi = order[j];
       order[j] = order[j+1];
       order[j+1] = tempi;
       test=1;
     }
      }
      if(test==0) break; //exit if sorted
    }
  }
  free(areas);
  //reverse the order
  //flip order around for convenience
  for (i = 0; i < numSides/2; i++){
    int a = order[i];
    order[i] = order[numSides-1-i];
    order[numSides-1-i] = a;
  }
  *neworder = order;
  return FC_SUCCESS;
}
FC_ReturnCode fc_createLargeAndNonAdjacentSidesOrder (FC_Shape * shape, int ** neworder)
As an approximation to obtaining the major sides of a thin shape, given a shape returns an array of the side ids in the ordered desired for shape with a large side and a non-adjacent side, subject to certain constraints.
Description: As an approximation to obtaining the major sides of a thin shape, given a shape returns an array of the side ids in the ordered desired for shape with a large side and a non-adjacent side, subject to certain constraints.
A thin shape is a shape that in some dimension is narrow and in a roughly perpendicular direction has a pair of large opposing sides, which are the major sides that the user is interested in. The thin shape order would then have those major sides in the 0th and 1st position, with all other sides in random order. This can then be fed into fc_reorderShape.
This method uses simplifying assumtions to get the major sides, which may not be correct in all cases. Specifically, this method attempts to find the largest side and its largest non-adjacent side and call them the major sides subject to the following constraints (in order):
If there are three or more sides that are the largest, it is not a thin shape (e.g., rectangular prism)
If the two largest sides are of equal area, returns them in random order if they are nonadj. If they are adjacent, then it is not a thin shape.
If the largest non-adj side to the unique largest side is equal in size to another non-adj side, then it is not a thin shape.
If there is no side that is non-adjacent to the largest side then it is not a thin shape.
Note that tests for equals are FC_FLT_EQUIV in order to keep the interface small. If you want to change those conditions, you have to write your own method.
Note that there can be undesirable results for shapes that have no sharp corners and therefore what may be expected to be the thin side actually wraps around the shape as one large continuous side and is therefore the largest side. This case is attempted to be handled by fc_createLargeAndOpposingSidesOrder.
Returns with an error if there is something fundamentally wrong. Returns FC_SUCCESS but empty order array if the shape does not satisfy the thin shape criteria.
Todo:
allows user to send in criteria for equals comparison?
Modifications:
07/18/06 ACG created
07/19/06 ACG changed so returns FC_SUCCESS and null order if it is not an appropriate shape. Only error if there is actually an error.
08/08/06 ACG renamed from createThinShapeOrder.
09/19/06 ACG changed equal comparison from dbl to float
Parameters:
shape input - shape
neworder output - ids of sides
Definition at line 2818 of file shape.c.
References FC_Shape::adjmatrix, fc_createDescendingAreaOrder(), FC_FLT_EQUIV, fc_getReturnCodeText(), fc_getShapeSidesAreas(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, and FC_Shape::numSides.
Referenced by createShapeWOrder().
    {
  FC_ReturnCode rc;
  double *areas;
  int numSides;
  int *order;
  int sidemax,nextside,testside;
  int i,count;
  //defaults
  if (neworder)
    *neworder = NULL;
  if (!shape || !neworder){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting large nonadjside area order");
  numSides = shape->numSides;
  //must be at least 3 sides for this to do anything
  if (numSides < 3){
    fc_printfErrorMessage("shape must have at least 3 sides to have a nonadj side");
    //    return FC_INPUT_ERROR;
    return FC_SUCCESS; //null return
  }
  rc = fc_getShapeSidesAreas(shape,&areas);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("cant get sides areas");
    return rc;
  }
  rc = fc_createDescendingAreaOrder(shape,&order);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("cant get descending order");
    free(areas);
    return rc;
  }
  sidemax = -1;
  nextside = -1;
  testside = -1;
  if (FC_FLT_EQUIV(areas[order[0]], areas[order[1]])){ //two largest sides are of equal area
    if (FC_FLT_EQUIV(areas[order[1]], areas[order[2]])){
      fc_printfErrorMessage("3 or more largest sides - cant get thin shape order");
      free(areas);
      free(order);
      return FC_SUCCESS; // not a thin shape, null return
    }else{
      //only two largest sides but if the two largest sides are adj - bad
      if (shape->adjmatrix[order[0]][order[1]] == 1){
     fc_printfErrorMessage("two largest sides adj - cant get thin shape order");
     free(areas);
     free(order);
     return FC_SUCCESS; // not a thin shape, null return
      }else{
     //return them in random order
     sidemax = order[0];
     nextside = order[1];
      }
    }
  }else{
    //two largest sides are not of equal area
    sidemax = order[0];
    //find the largest non-adjacent side. if that isnt unique - bad
    nextside = -1;
    testside = -1;
    for (i = 1; i < shape->numSides; i++){
      if (shape->adjmatrix[sidemax][order[i]] == 0){
     if (nextside == -1){
       nextside = order[i];
     }else{
       testside = order[i];
       break;
     }
      }
    }
  }
  //sidemax cannot be -1
  if (nextside == -1){
    fc_printfErrorMessage("no non-adj side - cant get thin shape order");
    free(areas);
    free(order);
    return FC_SUCCESS; // not a thin shape, null return
  }
  if (testside != -1){
    if (FC_FLT_EQUIV(areas[nextside],areas[testside])){
      fc_printfErrorMessage("two largest non-adj sides are of equal area - cant get thin shape order");
      free(areas);
      free(order);
      return FC_SUCCESS; // not a thin shape, null return
    }
  }
  //now we have our sides fill in all other ones randomly
  free(order);
  free(areas);
  order = (int*)malloc((shape->numSides)*sizeof(int));
  order[0] = sidemax;
  order[1] = nextside;
  count = 2;
  for (i = 0; i < shape->numSides; i++){
    if (i != sidemax && i!=nextside){
      order[count]= i;
      count++;
    }
  }
  *neworder = order;
  return FC_SUCCESS;
}
FC_ReturnCode fc_createLargeAndOpposingSidesOrder (FC_Shape * shape, double maxangle, int ** neworder)
As an approximation to obtaining the major sides of a thin shape, given a shape returns an array of the side ids in the ordered desired for a shape with a large and opposing side.
Description:
As an approximation to obtaining the major sides of a thin shape, given a shape returns an array of the side ids in the ordered desired for a shape with a large and opposing side. A thin shape is a shape that in some dimension is narrow and in a roughly perpendicular direction has a pair of large opposing sides, which are the major sides that the user is interested in. The thin shape order would then have those major sides in the 0th and 1st position, with all other sides in random order. This can then be fed into fc_reorderShape.
This method uses simplifying assumtions to get the major sides, which may not be correct in all cases. This method will iterate through the sides, starting with the largest one and attempt to find the the largest non-adjacent side for which the angle between the mean of the normals of each face for each side is in the range (180- the input angle) to 180. Currently, there is no restriction on the size of the sides relative to one another.
Note that there can be undesirable results for some shapes - see fc_getSideNormalMeanSdev for comments onthe limitations of the mean of the normals and angle calculation. See also fc_createLargeAndNonAdjacentSidesOrder for another approximation to the ideal thin shape order.
Note that there are no chekcs for unique sides like there are in the largeandnonadj side method. (that is, when there are multiple side options with the same area)
Returns with an error if there is something fundamentally wrong. Returns FC_SUCCESS but empty order array if the shape does not satisfy the large opposing sides criteria.
Todo:
there are no checks on uniqueness in here like there are in non-adj side, prob want to put those in.
make sure both sides are large? add an arg that also limits the ration of the sides relative to each other ?
Modifications:
08/04/06 ACG created
Parameters:
shape input - shape
maxangle input - opposing angle range
neworder output - ids of sides
Definition at line 3005 of file shape.c.
References FC_Shape::adjmatrix, fc_calcAngleBetweenVectors(), fc_createDescendingAreaOrder(), fc_getReturnCodeText(), fc_getSideNormalMeanSdev(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, and FC_Shape::numSides.
Referenced by createShapeWOrder().
    {
  FC_ReturnCode rc;
  FC_Vector* mean;
  int numSides;
  int *order;
  int currside, compside;
  double angle;
  int found = 0;
  int i,j;
  //defaults
  if (neworder)
    *neworder = NULL;
  if (!shape ||  !neworder || maxangle < 0 || maxangle > 180){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting large opposing sides order");
  numSides = shape->numSides;
  //must be at least 3 sides for this to do anything
  if (numSides < 3){
    fc_printfErrorMessage("shape must have at least 3 sides to have opposing sides/thin shape");
    //    return FC_INPUT_ERROR;
    return FC_SUCCESS;//null return
  }
  rc = fc_createDescendingAreaOrder(shape,&order);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("cant get ascending area order");
    return rc;
  }
  mean = (FC_Vector*)malloc((shape->numSides)*sizeof(FC_Vector));
  if (!mean){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < shape->numSides; i++){
    FC_Vector junk;
    rc = fc_getSideNormalMeanSdev(shape,i,&mean[i],&junk);
    if (rc != FC_SUCCESS){
      free(mean);
      return rc;
    }
  }
  for (i = 0; i < numSides; i++){
    currside = order[i];
    for (j = i+1; j < numSides; j++){
      compside = order[j];
      if (!shape->adjmatrix[currside][compside]){
     rc = fc_calcAngleBetweenVectors(mean[currside],mean[compside],
                         &angle);
     if (rc != FC_SUCCESS){
       fc_printfErrorMessage("Can't get angle between vectors");
       free(mean);
       free(order);
       return rc;
     }
     if (angle >= (180-maxangle)){
       found = 1;
       break;
     }
      }
    }
    if (found){
      break;
    }
  }
  free(mean);
  if (found){
    int count = 2;
    order[0] = currside;
    order[1] = compside;
    //now we have our sides fill in all other ones randomly
    for (i = 0; i < shape->numSides; i++){
      if (i != currside && i != compside){
     order[count] = i;
     count++;
      }
    }
    *neworder = order;
  }else{
    //not a large opposing sides shape, null return
    free(order);
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_createScrewShapeOrder (FC_Shape * shape, int ** neworder)
given a shape, returns the reordering array for a screw
Description:
Given a shape, returns the reordering array for a screw. It returns the sides in the following order: head plane, head cylinder, middle plane, base cylinder, base plane (I've made up these names)
If the shape does not satisfy the screw criteria, the method returns FC_SUCCESS but a NULL order array. These cases are shapes without 5 sides or those whose adjacency matricies don't fit the screw adjmatrix pattern. Some non-screw things in theory could slip through the testing cracks. It is up to the user to make sure he uses this in the right way.
Modifications:
06/18/06 ACG created
07/19/06 ACG changed so if the shape is not a screw it returns FC_SUCCESS but an empty order array. Only returns FC_ERROR if there is an actual error.
08/06/06 ACG more of the above - for if not 5 sided figure.
Parameters:
shape input - shape
neworder output - order array
Definition at line 2520 of file shape.c.
References FC_Shape::adjmatrix, FC_Shape::faces, fc_getReturnCodeText(), fc_getSubsetArea(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, and FC_Shape::numSides.
Referenced by createShapeWOrder().
  {
  //head plane has 1 adj side
  //base plane has 1 adj side
  //head cylinder is adj to the head plane and the mid plane
  //base cylinder is adj to the base plane and the mid plane
  //mid plane is adj to the base cylinder and the head cylinder
  //head plane has greater area than base plane
  FC_ReturnCode rc;
  int endcount = 0;
  int othercount = 0;
  int endoptions[5], otheroptions[5];
  double areas[2];
  int *order;
  int nSides;
  int i,j;
  //defaults
  if (neworder)
    *neworder = NULL;
  if (!shape || !neworder){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting screwshape order");
  nSides = shape->numSides;
  if (nSides != 5){
    //success but null return
    return FC_SUCCESS;
  }
  order = (int*)malloc(5*sizeof(int));
  if (!order){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < nSides; i++){
    int count = 0;
    //can initialize these here because endcount and othercount
    //cant exceed i
    order[i] = -1;
    endoptions[i] = -1;
    otheroptions[i] = -1;
    for (j = 0; j < nSides; j++){
      //      printf(" %d",shape->adjmatrix[i][j]);
      //check matrix for symmetry
      if (shape->adjmatrix[i][j] != shape->adjmatrix[j][i]){
     fc_printfErrorMessage("adj matrix not symmetric");
     free(order);
     return FC_INPUT_ERROR;
      }
      if (shape->adjmatrix[i][j]) count++; //count the adjacencies
    }
    //    printf("\n");
    if (count == 1){
      //its the base plane or top plane
      endoptions[endcount++] = i;
      //      printf("end - %d\n",i);
    }else if (count == 2){
      //its the top cylinder, base cylinder, or middle plane
      otheroptions[othercount++] = i;
      //      printf("other - %d\n",i);
    }else {
      //this is an invalid shape
      //      fc_printfErrorMessage("Invalid screw shape");
      free(order);
      return FC_SUCCESS; //not a screw, null return
    }
  }
  if (endcount != 2 || othercount != 3){
    //    fc_printfErrorMessage("Invalid screw shape");
    free(order);
    return FC_SUCCESS; // not a screw
  }
  //determine ends
  for(i = 0; i < endcount; i++){ //endcount is 2
    rc = fc_getSubsetArea(shape->faces[endoptions[i]],&(areas[i]));
    if (rc !=FC_SUCCESS){
      fc_printfErrorMessage("cant get areas");
      free(order);
      return rc;
    }
  }
  i = (areas[0] > areas[1] ? 0:1);
  order[0] = endoptions[i];
  order[4] = endoptions[!i];
  //determine cylinders and midplane
  for (i = 0; i < othercount; i++){
    if (shape->adjmatrix[otheroptions[i]][order[0]] == 1){
      order[1] = otheroptions[i];
    }else if (shape->adjmatrix[otheroptions[i]][order[4]] == 1){
      order[3] = otheroptions[i];
    }else {
      order[2] = otheroptions[i];
    }
  }
  //check midplane adjacencies
  if ((shape->adjmatrix[order[2]][order[1]] != 1) ||
      shape->adjmatrix[order[2]][order[3]] != 1){
    //    fc_printfErrorMessage("invalid screw shape");
    free(order);
    return FC_SUCCESS; //not a screw, null return
  }
  *neworder = order;
  return FC_SUCCESS;
}
FC_ReturnCode fc_createSideAdjacencyMatrix (int numSubsets, FC_Subset * subsets, int shared_dim, int *** intmatrix)
Given an array of subsets specifying the faces of each side of a shape, returns a matrix specifying the side adjacencies.
Description:
Given an array n of subsets, specifying the side faces returns an nxn matrix of 1s and 0s depending on whether or not the sides are adjacenct. Have opted to make the diagonal elements 0. Note that the shapecreating methods automatically create adjacency matricies in a somewhat different way.
If any of the subsets are empty or NULL, this method returns with an error.
Modifications:
02/07/06 ACG created.to handle the screw case.
02/08/06 ACG unittest added.
02/08/06 ACG found another flaw in the logic of old adjacencyMatrix test. Therefore removed old version entirely.
Parameters:
numSubsets input - number of input subsets
subsets input - array of face subsets
shared_dim input - shared dim for determining neighbors
intmatrix output - 1/0 matrix
Definition at line 3142 of file shape.c.
References fc_addArrayMembersToSubset(), FC_AT_FACE, fc_createSubset(), fc_deleteSubset(), fc_doSubsetsIntersect(), fc_getMeshFromSubset(), fc_getReturnCodeText(), fc_getSubsetAssociationType(), fc_getSubsetNeighbors(), fc_getSubsetNumMember(), FC_INPUT_ERROR, fc_isSubsetValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
  {
  FC_ReturnCode rc;
  FC_Mesh mesh;
  FC_AssociationType assoc;
  int i,j,k;
  //default return
  if (intmatrix)
    *intmatrix = NULL;
  if (!numSubsets || !subsets || !intmatrix || !(shared_dim == 1 || shared_dim == 0)){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  //check that all the subsets are valid
  for (i = 0; i < numSubsets; i++){
    if (!fc_isSubsetValid(subsets[i])){
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
      return FC_INPUT_ERROR;
    }
    rc = fc_getSubsetAssociationType(subsets[i], &assoc);
    if (rc != FC_SUCCESS)
      return rc;
    if (assoc != FC_AT_FACE){
      fc_printfErrorMessage("Wrong assoc type");
      return FC_INPUT_ERROR;
    }
    rc= fc_getSubsetNumMember(subsets[i], &k);
    if (rc != FC_SUCCESS)
      return rc;
    if (k < 1){
      fc_printfErrorMessage("sides must have at least one member");
      return FC_INPUT_ERROR;
    }
  }
  // log message
  fc_printfLogMessage("Computing Side Adjacency Matrix");
  rc = fc_getMeshFromSubset(subsets[0],&mesh);
  if (rc !=FC_SUCCESS){
    fc_printfErrorMessage("Can't get mesh from subset");
    return rc;
  }
  // create space for the adj array, initialize to zero
  *intmatrix = calloc(numSubsets, sizeof(int*));
  if (*intmatrix == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < numSubsets; i++) {
    (*intmatrix)[i] = calloc(numSubsets, sizeof(int));
    if ((*intmatrix)[i] == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
  }
  for (i = 0; i < numSubsets; i++){
    int numNbr, *nbrIDs;
    FC_Subset neighborfaces;
    //    printf("determining adj for subset %d\n",i);
    (*intmatrix)[i][i] = 0;
    //get the face neighbors for this subset
    //    printf("getting subset neighbors\n");
    rc = fc_getSubsetNeighbors(subsets[i], 1, shared_dim, &assoc, &numNbr, &nbrIDs);
    if (rc != FC_SUCCESS || assoc != FC_AT_FACE){
      fc_printfErrorMessage("Failed to get subset neighbors");
      for (k = 0; k < numSubsets; k++){
     free((*intmatrix)[k]);
      }
      free((*intmatrix));
      (*intmatrix) = NULL;
      return rc;
    }
    rc = fc_createSubset(mesh,"temp",FC_AT_FACE,&neighborfaces);
    if (rc !=FC_SUCCESS){
      fc_printfErrorMessage("cant create subset");
      for (k = 0; k < numSubsets; k++){
     free((*intmatrix)[k]);
      }
      free((*intmatrix));
      (*intmatrix) = NULL;
      free(nbrIDs);
      return rc;
    }
    //    printf("Adding array members to subset\n");
    rc = fc_addArrayMembersToSubset(neighborfaces,numNbr,nbrIDs);
    if (rc !=FC_SUCCESS){
      fc_printfErrorMessage("cant create subset");
      for (k = 0; k < numSubsets; k++){
     free((*intmatrix)[k]);
      }
      free((*intmatrix));
      (*intmatrix) = NULL;
      fc_deleteSubset(neighborfaces);
      free(nbrIDs);
      return rc;
    }
    free(nbrIDs);
    //    printf("done adding array members to subset\n");
    for (j = i+1; j < numSubsets; j++){ //symmetric result
      int retval;
      //      printf("checking intersection\n");
      rc = fc_doSubsetsIntersect(neighborfaces,subsets[j], &retval);
      if (rc != FC_SUCCESS){
        fc_printfErrorMessage("Failed to get subset intersection");
     for (k = 0; k < numSubsets; k++){
       free((*intmatrix)[k]);
     }
     free((*intmatrix));
     (*intmatrix) = NULL;
     fc_deleteSubset(neighborfaces);
     return rc;
      }
      (*intmatrix)[i][j] = retval;
      (*intmatrix)[j][i] = retval;
    }
    //    printf("done checking intersection\n");
    fc_deleteSubset(neighborfaces);
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_freeShape (FC_Shape * fcss)
frees a Shape
Description:
Deallocate contents of an FC_Shape.
Modifications:
06/04/06 ACG created
07/13/06 ACG renamed from freeShape
07/16/06 removed "skin" from name
Parameters:
fcss input - the shape
Definition at line 2320 of file shape.c.
References FC_Shape::adjmatrix, FC_Shape::elems, FC_Shape::faces, fc_deleteSubset(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, FC_SUCCESS, and FC_Shape::numSides.
Referenced by buildScrews(), fc_copyShape(), fc_reduceShapeNumSides(), freeShapeWOrder_ShapeOnly(), and main().
 {
  int i;
  FC_ReturnCode rc;
  if (!fcss){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  for (i = 0; i < fcss->numSides; i++){
    rc = fc_deleteSubset(fcss->faces[i]);
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("Can't free face %d",i);
      return rc;
    }
    rc = fc_deleteSubset(fcss->elems[i]);
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("Can't free elems %d",i);
      return rc;
    }
    free(fcss->adjmatrix[i]);
  }
  free(fcss->faces);
  free(fcss->elems);
  free(fcss->adjmatrix);
  fcss->faces= NULL;
  fcss->elems= NULL;
  fcss->adjmatrix= NULL;
  fcss->numSides = 0;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshShapes (FC_Mesh mesh, double comp_angle, int shared_dim, int * numShapes, FC_Shape ** shapes)
given a mesh, returns an array of FC_Shapes
Description:
given a mesh, returns an array of FC_Shape. This is the mesh version of fc_getSubsetShapes. See notes there.
Modifications:
6/04/06 ACG created
7/16/06 ACG removed "skin" in name
Parameters:
mesh input - mesh
comp_angle input - if two neighboring faces differ by more than this angle then they are considered to be on different surfaces.
shared_dim input - the minimum dimensionality of shared part of neighbors of faces
numShapes output - number of shapes
shapes output shapes array
Definition at line 1515 of file shape.c.
References fc_addMemberToSubset(), FC_AT_WHOLE_MESH, fc_createSubset(), fc_deleteSubset(), fc_getMeshName(), fc_getReturnCodeText(), fc_getSubsetShapes(), FC_INPUT_ERROR, fc_isMeshValid(), fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by main().
 {
  FC_ReturnCode rc;
  FC_Subset temp_subset;
  char *meshname;
  //---default return values
  if (numShapes)
    *numShapes = -1;
  if (shapes)
    *shapes = NULL;
  //check input - some checked in sides
  if(!numShapes || !shapes){
    fc_printfErrorMessage("%s",fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("getting mesh shapes");
  //does all error checking except is mesh valid inside _fc_getSubsetShapes
  if (!fc_isMeshValid(mesh)){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // create a temp subset which is the whole mesh & call fc_getSubsetShapes
  rc = fc_getMeshName(mesh,&meshname);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_createSubset(mesh, meshname, FC_AT_WHOLE_MESH, &temp_subset);
  if (rc != FC_SUCCESS) {
     fc_deleteSubset(temp_subset);
     free(meshname);
     return rc;
  }
  free(meshname);
  rc = fc_addMemberToSubset(temp_subset, 0);
  if (rc != FC_SUCCESS) {
     fc_deleteSubset(temp_subset);
     return rc;
  }
   // do it
  rc = fc_getSubsetShapes(temp_subset, comp_angle,shared_dim,numShapes,
                     shapes);
  fc_deleteSubset(temp_subset);
  return rc;
}
FC_ReturnCode fc_getPlanarSideNormal (FC_Shape * shape, int sideid, FC_Coords * normal)
Given a shape and the ID of a planar side, returns the outward normal to that face.
Description:
Given a shape and the ID of a planar side, returns the outward normal to that face. Does not actually test to see if the face is planar.
Todo:
decide if need more unittest
Modifications:
03/16/06 ACG created.
08/08/06 ACG changed interface so pass sides in terms of shape rahter than faces and elems.
Parameters:
shape input - the shape
sideid input - the shape side id
normal output - normal
Definition at line 3873 of file shape.c.
References _fc_getOutwardFaceNormal(), FC_Shape::elems, FC_Shape::faces, FC_AT_ELEMENT, FC_AT_FACE, fc_getMeshEntityChildren(), fc_getMeshFromSubset(), fc_getReturnCodeText(), fc_getSubsetAssociationType(), fc_getSubsetMembersAsArray(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, fc_isSubsetValid(), fc_printfErrorMessage, FC_SUCCESS, and FC_Shape::numSides.
Referenced by buildScrews().
   {
  FC_ReturnCode rc1, rc2, rc;
  FC_Mesh mesh1,mesh2;
  FC_AssociationType assoc1, assoc2;
  FC_Vector retvec;
  int faceID,elemID;
  int numItems;
  int *arr;
  int i,j;
  //default
  if (normal){
    for (i = 0; i < 3; i++){
      (*normal)[i] = 0;
    }
  }
  if (!shape || (sideid < 0) || (sideid > (shape->numSides)-1) ||
      !fc_isSubsetValid(shape->faces[sideid]) ||
      !fc_isSubsetValid(shape->elems[sideid]) || !normal ){
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
      return FC_INPUT_ERROR;
  }
  rc1 = fc_getSubsetAssociationType(shape->faces[sideid], &assoc1);
  rc2 = fc_getSubsetAssociationType(shape->elems[sideid], &assoc2);
  if (rc1 != FC_SUCCESS || rc2 != FC_SUCCESS)
    return(rc1 != FC_SUCCESS ? rc1 : rc2);
  if (assoc1 != FC_AT_FACE || assoc2 != FC_AT_ELEMENT){
    fc_printfErrorMessage("Wrong assoc type");
    return FC_INPUT_ERROR;
  }
  rc1 = fc_getMeshFromSubset(shape->faces[sideid],&mesh1);
  rc2 = fc_getMeshFromSubset(shape->elems[sideid],&mesh2);
  if (rc1 != FC_SUCCESS || rc2 != FC_SUCCESS)
    return(rc1 != FC_SUCCESS ? rc1 : rc2);
  if (!FC_HANDLE_EQUIV(mesh1,mesh2)){
    fc_printfErrorMessage("faces and elems must be on same mesh");
    return FC_INPUT_ERROR;
  }
  //since its planar just pick the first face
  rc = fc_getSubsetMembersAsArray(shape->faces[sideid],&numItems,&arr);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("Can't get faces");
    return rc;
  }
  if (numItems < 1){
    fc_printfErrorMessage("must have at least 1 face");
    return FC_INPUT_ERROR;
  }
  faceID = arr[0];
  free(arr);
  //find the elem that gave rise to it - can be only one.
  rc = fc_getSubsetMembersAsArray(shape->elems[sideid],&numItems,&arr);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("Can't get elems");
    return rc;
  }
  elemID = -1;
  for (i = 0; i < numItems; i++){
    int numChild, *childIDs;
    rc = fc_getMeshEntityChildren(mesh1, FC_AT_ELEMENT, arr[i], FC_AT_FACE,
                             &numChild, &childIDs);
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("Cant get elem->face data");
      free(arr);
      return rc;
    }
    for (j = 0; j < numChild; j++){
      if (childIDs[j] == faceID){
     elemID = arr[i];
     break;
      }
    }
    free(childIDs);
    if (elemID != -1){
      break;
    }
  }
  free(arr);
  if (elemID == -1){
    fc_printfErrorMessage("Cant find elem that gave rise to this face");
    return FC_INPUT_ERROR;
  }
  rc =  _fc_getOutwardFaceNormal(mesh1,faceID,elemID, &retvec);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("Cant get outward face normal");
    return FC_INPUT_ERROR;
  }
  for (i = 0; i < 3; i++){
    (*normal)[i] = retvec[i];
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_getShapeEnds (FC_Shape * shape, int * numEnds, int ** endArray)
given a shape returns the shape's ends.
Description:
Given a shape an array containing the ids of the shape's ends. The ends are those sides who are connected to only 1 other side in the shape (Determined by consideration of the adjacency matrix). The ids are those of the indicies of the sides in the order they are specified in the face array. Order of the indicies in the return array are in order from smallest (area) to largest.
Note: nothing checks that the shape actually makes any sense.
Returns -1 for numEnds and NULL array in case of error. If numSides == 0, it is considered an error. If numSides == 1 it is not an error and returns zero ends.
Todo:
decide if this should be expanded to ask for any adj matrix value
Modifications:
02/07/06 ACG, created
06/18/06 ACG, created - revision of old getSidesEnds
06/28/06 ACG now the official shape ends
Parameters:
shape input - shape
numEnds output - num of ends
endArray output - ids of ends
Definition at line 3603 of file shape.c.
References FC_Shape::adjmatrix, FC_Shape::faces, FC_ERROR, fc_getReturnCodeText(), fc_getSubsetArea(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, and FC_Shape::numSides.
Referenced by buildScrews(), and createShapeWOrder().
  {
  int* eholding;
  int nends;
  int numSides;
  int i,j;
  //defaults
  if (numEnds)
    *numEnds = -1;
  if (endArray)
    *endArray = NULL;
  if (!shape || !numEnds || !endArray){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting shape ends B");
  numSides = shape->numSides;
  if (!numSides){
    fc_printfErrorMessage("shape has no sides");
    return FC_ERROR;
  }
  eholding = calloc(numSides,sizeof(int));
  if (!eholding) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    //not cleaning up matrix in case of memory error
    return FC_MEMORY_ERROR;
  }
  nends = 0;
  for (i = 0; i < numSides; i++){
    int conn = 0;
    if (shape->adjmatrix[i][i] != 0){
      fc_printfErrorMessage("non zero diagonal adj matrix");
      free(eholding);
      return FC_ERROR;
    }
    for (j = 0; j < numSides; j++){
      if (shape->adjmatrix[i][j] != shape->adjmatrix[j][i]){
     fc_printfErrorMessage("non symmetric adj matrix");
     free(eholding);
     return FC_ERROR;
      }
      if (shape->adjmatrix[i][j] !=0 ){
     conn+=1;
      }
    }
    if (conn == 1){
      eholding[nends++]=i;
    }
  }
  switch (nends){
  case 0:
    free(eholding);
    eholding = NULL;
    break;
  case 1:
    //do nothing
    break;
  default:
    {
      FC_ReturnCode rc;
      double *areas;
      areas = malloc(nends*sizeof(FC_Subset));
      if (!areas){
     fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
     //not cleaning up in case of memory error
     return FC_MEMORY_ERROR;
      }
      for (i = 0; i < nends; i++){
     rc= fc_getSubsetArea(shape->faces[eholding[i]],&areas[i]);
     if (rc != FC_SUCCESS){
       fc_printfErrorMessage("cant get subset areas");
       free(eholding);
       free(areas);
       return rc;
     }
      }
      //order sides by area
      //sort sides areas. yes i know, its bubblesort.
      {
     double tempa;
     int tempi;
     int test;
     for(i = nends - 1; i > 0; i--){
       test=0;
       for(j = 0; j < i; j++){
         if (areas[j] > areas[j+1]){
           tempa = areas[j];
           areas[j] = areas[j+1];
           areas[j+1] = tempa;
           tempi = eholding[j];
           eholding[j] = eholding[j+1];
           eholding[j+1] = tempi;
           test=1;
         }
       }
       if(test==0) break; //exit if sorted
     }
      }
      free(areas);
      break;
    }
  }
  *numEnds = nends;
  //note: eholding was allocated with numSides members, not nends.
  //this is ok becuase free will free the whole array
  *endArray = eholding;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getShapeSidesAreas (FC_Shape * shape, double ** area)
Given a Shape, returns the (non-displaced) area for each side.
Description:
Given a Shape, returns the (non-displaced) area for each side. Checks to see if all the sides are on the same mesh.
If there is an error in calculating this for any side, then this returns NULL for the entire array.
Todo:
may want to do a displaced version
Modifications:
01/03/06 ACG
07/17/06 ACG born out of old getSidesAreas
Parameters:
shape input - ptr to shape
area output - area array
Definition at line 3754 of file shape.c.
References FC_Shape::faces, FC_AT_FACE, fc_deleteVariable(), fc_getFaceAreas(), fc_getMeshFromSubset(), fc_getReturnCodeText(), fc_getSubsetAssociationType(), fc_getSubsetMembersAsArray(), fc_getVariableDataPtr(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, fc_isSubsetValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, and FC_Shape::numSides.
Referenced by fc_createDescendingAreaOrder(), and fc_createLargeAndNonAdjacentSidesOrder().
 {
  FC_Mesh meshlast, meshnext;
  FC_ReturnCode rc;
  FC_Variable faceareas;
  double *areaarray;
  FC_AssociationType assoc;
  int i,j;
  //default return
  if (area)
    *area = NULL;
  if (!shape || !area ){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  //check that all the subsets are valid
  for (i = 0; i < shape->numSides; i++){
    if (!fc_isSubsetValid(shape->faces[i])){
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
      return FC_INPUT_ERROR;
    }
    rc = fc_getSubsetAssociationType(shape->faces[i], &assoc);
    if (rc != FC_SUCCESS)
      return rc;
    if ( assoc != FC_AT_FACE){
      fc_printfErrorMessage("Wrong association type");
      return FC_INPUT_ERROR;
    }
  }
  // log message
  fc_printfLogMessage("Computing ShapeSide Areas");
  //get areas for all faces of the mesh
  rc = fc_getMeshFromSubset(shape->faces[0],&meshlast);
  if (rc!= FC_SUCCESS){
    return rc;
  }
  rc = fc_getFaceAreas(meshlast,&faceareas);
  if (rc!= FC_SUCCESS){
    fc_printfErrorMessage("cant get face areas");
    return rc;
  }
  rc = fc_getVariableDataPtr(faceareas,(void **) &areaarray);
  if (rc!= FC_SUCCESS){
    return rc;
  }
  *area = calloc(shape->numSides, sizeof(double));
  if (*area == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < shape->numSides; i++){
    int numMem, *ids;
    rc = fc_getMeshFromSubset(shape->faces[i],&meshnext);
    if (rc!= FC_SUCCESS){
      free(*area);
      *area = NULL;
      return rc;
    }
    if (!FC_HANDLE_EQUIV(meshnext, meshlast)){
      fc_printfErrorMessage("all subsets must be on the same mesh");
      free(*area);
      *area = NULL;
      return FC_INPUT_ERROR;
    }
    rc = fc_getSubsetMembersAsArray(shape->faces[i], &numMem, &ids);
    if (rc!= FC_SUCCESS){
      free(*area);
      *area = NULL;
      return rc;
    }
    for (j = 0; j < numMem; j++){
      (*area)[i] += areaarray[ids[j]];
    }
    free(ids);
    meshlast = meshnext;
  }
  fc_deleteVariable(faceareas);
  return FC_SUCCESS;
}
FC_ReturnCode fc_getSideNormalMeanSdev (FC_Shape * shape, int sideid, FC_Vector * mean, FC_Vector * std)
Given a shape and a sideid, returns the outward normal and std in each direction to that face.
Description:
Given a shape and a sideid, returns the mean of the components of the outward normals and std in each direction to that face. Note that the mean is not a normal and also that for the same shape, this can retrun differnet values depending onthe sizes and shapes of the individual faces of the overall side. The hope is that in most cases, if one is using this to compare the results of different sides inthe same mesh, that the elements are sufficiently regular that a meaningful result is obtained.
Modifications:
08/04/06 ACG created.
08/08/06 ACG changed interface so takes a shape rather than the faces and elems of the side
Parameters:
shape input - shape
sideid input - side id
mean output - mean
std output - std in each dir separately
Definition at line 4008 of file shape.c.
References _fc_getOutwardFaceNormal(), FC_Shape::elems, FC_Shape::faces, fc_addIntArrayToSortedIntArray(), FC_AT_ELEMENT, FC_AT_FACE, fc_deleteIntFromSortedIntArray(), FC_ERROR, fc_freeSortedIntArray(), fc_getMeshEntityChildren(), fc_getMeshFromSubset(), fc_getReturnCodeText(), fc_getSubsetAssociationType(), fc_getSubsetMembersAsArray(), FC_HANDLE_EQUIV, fc_initSortedIntArray(), FC_INPUT_ERROR, fc_isSubsetValid(), fc_printfErrorMessage, FC_SUCCESS, FC_Shape::numSides, and FC_SortedIntArray::numVal.
Referenced by fc_createLargeAndOpposingSidesOrder().
   {
  FC_ReturnCode rc1, rc2, rc;
  FC_Mesh mesh1, mesh2;
  FC_AssociationType assoc1, assoc2;
  FC_Vector sum, sumsq;
  FC_Vector compmean, sdev, temp;
  int faceID,elemID;
  int numFaces,numElems;
  int *arrf, *arre;
  FC_SortedIntArray sia;
  int i,j,k;
  //default
  if (mean){
    for (i = 0; i < 3; i++){
      (*mean)[i] = 0;
    }
  }
  if (std){
    for (i = 0; i < 3; i++){
      (*std)[i] = 0;
    }
  }
  if (!shape || (sideid < 0) || (sideid > ((shape->numSides)-1)) ||
      !fc_isSubsetValid(shape->faces[sideid]) ||
      !fc_isSubsetValid(shape->elems[sideid]) || !mean  || !std){
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
      return FC_INPUT_ERROR;
  }
  rc1 = fc_getSubsetAssociationType(shape->faces[sideid], &assoc1);
  rc2 = fc_getSubsetAssociationType(shape->elems[sideid], &assoc2);
  if (rc1 != FC_SUCCESS || rc2 != FC_SUCCESS)
    return(rc1 != FC_SUCCESS ? rc1 : rc2);
  if (assoc1 != FC_AT_FACE || assoc2 != FC_AT_ELEMENT){
    fc_printfErrorMessage("Wrong assoc type");
    return FC_INPUT_ERROR;
  }
  rc1 = fc_getMeshFromSubset(shape->faces[sideid],&mesh1);
  rc2 = fc_getMeshFromSubset(shape->elems[sideid],&mesh2);
  if (rc1 != FC_SUCCESS || rc2 != FC_SUCCESS)
    return(rc1 != FC_SUCCESS ? rc1 : rc2);
  if (!FC_HANDLE_EQUIV(mesh1,mesh2)){
    fc_printfErrorMessage("faces and elems must be on same mesh");
    return FC_INPUT_ERROR;
  }
  rc = fc_getSubsetMembersAsArray(shape->faces[sideid],&numFaces,&arrf);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("Can't get faces");
    return rc;
  }
  if (numFaces < 1){
    fc_printfErrorMessage("must have at least 1 face");
    free(arrf);
    return FC_INPUT_ERROR;
  }
  rc = fc_getSubsetMembersAsArray(shape->elems[sideid],&numElems,&arre);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("Can't get elems");
    free(arrf);
    free(arre);
    return rc;
  }
  rc = fc_initSortedIntArray(&sia);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("Can't init sorted int array");
    free(arrf);
    free(arre);
    return rc;
  }
  //when we get the array from the subset, we know it is sorted
  i = fc_addIntArrayToSortedIntArray(&sia,numFaces,arrf,1);
  free(arrf);
  if (!i){
    fc_printfErrorMessage("Can't add array to sia int array");
    free(arre);
    fc_freeSortedIntArray(&sia);
    return FC_ERROR;
  }
  for (i = 0; i < 3; i++){
    sum[i] = 0;
    sumsq[i] = 0;
  }
  //for each elem, get its kids and match them up with the faces
  //each face can come from only 1 elem.
  //figure its faster to get the elems kids once and check thru a sorted
  //face list than to try to go thru the face list and iterate thur all
  //the elems
  //then get the mean of the normals
  for (i = 0; i < numElems; i++){
    int numChild, *childIDs;
    elemID = arre[i];
    rc = fc_getMeshEntityChildren(mesh1, FC_AT_ELEMENT, arre[i], FC_AT_FACE,
                      &numChild, &childIDs);
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("Cant get elem->face data");
      free(arre);
      fc_freeSortedIntArray(&sia);
      return rc;
    }
    for (j = 0; j < numChild; j++){
      FC_Vector retvec;
      //is this face in the list ?
      faceID = childIDs[j];
      if (fc_deleteIntFromSortedIntArray(&sia,faceID)){
     rc =  _fc_getOutwardFaceNormal(mesh1,faceID,elemID, &retvec);
     if (rc != FC_SUCCESS){
       fc_printfErrorMessage("Cant get outward face normal");
       free(arre);
       fc_freeSortedIntArray(&sia);
       return rc;
     }
     for (k = 0; k < 3; k++){
       sum[k]+=retvec[k];
       sumsq[k]+=(retvec[k]*retvec[k]);
     }
      }
    }
    free(childIDs);
  }
  free(arre);
  //make sure all the faces have been removed
  if (sia.numVal){
    fc_printfErrorMessage("Mismatch of faces and elems");
    fc_freeSortedIntArray(&sia);
    return FC_INPUT_ERROR;
  }
  fc_freeSortedIntArray(&sia);
  for (i = 0; i <3; i++){
    compmean[i] = sum[i]/(double)numFaces;
    if (numFaces > 1){
      temp[i] = (sumsq[i] - (sum[i] * sum[i] /(double) numFaces)) /
     (double)(numFaces - 1);
      sdev[i] = sqrt(fabs(temp[i]));
      // might be negative if roundoff error
    }else{
      sdev[i] = 0.0;
    }
  }
  for (i = 0; i < 3; i++){
    (*mean)[i] = compmean[i];
    (*std)[i] = sdev[i];
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_getSubsetShapes (FC_Subset in_subset, double comp_angle, int shared_dim, int * numShapes, FC_Shape ** shapes)
given a subset, returns an array of FC_Shapes
Description:
Given a subset returns an array of FC_Shapes. Vals for comp_angle are limited to 0->180 degrees because of the return val of acos. The choice is tricky because for curved sides, setting this too low will result in each face along the curve will be considerd a new side, but setting it too high means that some things that should be distinct sides will be combined into one.
The face and elem subsets will be named as the name of the original subset, postpended with "Shape#" followed by "_FaceSurface#" or "_ElemSurface#" where # will be the index into the array of subsets for that shape.
In a given shape the indicies of the face and elem arrays correspond, that is side 0 consists of the faces in the subset face[0] and the elements in the subset elem[0]. There is no correspondence between the order of the faces and the order of the elems, within a subset, that is the first face in side 0 does not necessarily come from the first elem in side 0. In fact, the subsets may have different lengths e.g, if one element corresponds to more than one face on a side (which can happen depending on the angle chosen).
Note that pieces that are touching will come out as 1 distinct shape with a lot of edges as opposed to two distinct shapes. Segment will do the same thing.
Fails if NULL subset. Returns 0 shapes if empty subset.
Notes:
this does not use displacements.
vals for comp_angle are limited to 0->180 degrees because of the return val of acos. Similary, if the mesh angle is not in that range, it will return with an error.
becuase of the calculation of the normals, this method is limited to elements of topodim 3 who have faces of type FC_ET_TRI or FC_ET_QUAD
internally, this uses edge info between sides to build the adj matrix. In the case of a crease in the shape, two faces may appear to be on different sides at some point, but later discovered to be on the same side via neighbors that are without a crease between them. I believe this all works out fine, but I dont guarentee it. In the building of the adjacenecy matrix, the user will be warned about pairs of faces like this.
Todo:
want a hashtable to do the adjmatrix calc (see innards)
note, this does not clean up memory well in case of weird error (that shouldnt occur) deep within the list building
Modifications:
06/04/06 ACG created
08/19/06 ACG _fc_getSubsetSides (created 10/04/05 ACG) merged in now that that facelist processing has been separated out. (see _fc_buildFaceInfoListFromSubset)
09/18/06 ACG better subset names
Parameters:
in_subset input - subset
comp_angle input - if two neighboring faces differ by more than this angle then they are considered to be on different surfaces.
shared_dim input - the minimum dimensionality of shared part of neighbors of faces
numShapes output - number of shapes
shapes output shapes array
Definition at line 1339 of file shape.c.
References _fc_buildFaceInfoListFromSubset(), _fc_createShapePartsFromFaceInfoList(), _fc_freeSFI_Array(), FC_Shape::adjmatrix, FC_Shape::elems, FC_Shape::faces, FC_AT_ELEMENT, FC_AT_WHOLE_MESH, fc_changeSubsetName(), fc_getMeshFromSubset(), fc_getReturnCodeText(), fc_getSubsetInfo(), fc_getSubsetName(), FC_INPUT_ERROR, fc_isSubsetValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, fc_segmentAdjacencyMatrix(), FC_SUCCESS, and FC_Shape::numSides.
Referenced by buildScrews(), fc_getMeshShapes(), and main().
 {
  FC_ReturnCode rc;
  FC_Mesh mesh;
  FC_AssociationType assoc;
  char *subsetName;
  int numMem, junk;
  _FC_SFI_ARRAY faceinfo_list;
  int numSides;
  FC_Subset* newFaceSubsets;
  FC_Subset* newElemSubsets;
  int **adjmatrix;
  int numParts;
  int *sidesPerPart;
  int **partSideIDS;
  FC_Shape *lshapes;
  int i,j,k;
  //defaults
  if (numShapes)
    *numShapes = -1;
  if (shapes)
    *shapes = NULL;
  if (!numShapes || !shapes  || !fc_isSubsetValid(in_subset) ||
  shared_dim < 0 || shared_dim > 1 || comp_angle < 0 ||
  comp_angle > 180){
    fc_printfErrorMessage("%s",fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  fc_printfLogMessage("get subset shapes");
  // setup and more checking
  rc = fc_getSubsetInfo (in_subset, &numMem, &junk,&assoc);
  if (rc != FC_SUCCESS)
    return rc;
  if (assoc != FC_AT_ELEMENT && assoc != FC_AT_WHOLE_MESH){
    fc_printfErrorMessage("subset must have assoc FC_AT_ELEMENT or FC_AT_WHOLE_MESH");
    return FC_INPUT_ERROR;
  }
  if (numMem == 0){ //return if empty subset
    *numShapes = 0;
    return FC_SUCCESS;
  }
  rc = fc_getMeshFromSubset(in_subset, &mesh);
  if (rc != FC_SUCCESS)
    return rc;
  //let's get all the info we need about the skin
  rc = _fc_buildFaceInfoListFromSubset(in_subset,&faceinfo_list);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("cant build face info list\n");
    return rc;
  }
  rc = fc_getSubsetName(in_subset,&subsetName);
  if (rc != FC_SUCCESS){
    _fc_freeSFI_Array(&faceinfo_list);
    free(subsetName);
    return rc;
  }
  rc = _fc_createShapePartsFromFaceInfoList(mesh, &faceinfo_list,&subsetName,
                                            comp_angle,shared_dim,&numSides,
                                            &newFaceSubsets,&newElemSubsets,
                             &adjmatrix);
  if (rc != FC_SUCCESS){
    free(subsetName);
    _fc_freeSFI_Array(&faceinfo_list); //see note about
    //deciding how to handle the freeing of this
  }
  rc = fc_segmentAdjacencyMatrix(numSides,adjmatrix,
                     &numParts, &sidesPerPart, &partSideIDS);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("Can't segment adj matrix sides");
    free(subsetName);
    return rc;
  }
  lshapes = (FC_Shape*)malloc(numParts*sizeof(FC_Shape));
  if (lshapes == NULL){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for(i = 0; i < numParts; i++){
    lshapes[i].numSides = sidesPerPart[i];
    lshapes[i].faces = (FC_Subset*)malloc(sidesPerPart[i]*sizeof(FC_Subset));
    lshapes[i].elems = (FC_Subset*)malloc(sidesPerPart[i]*sizeof(FC_Subset));
    lshapes[i].adjmatrix = (int**)malloc(sidesPerPart[i]*sizeof(int*));
    for (j = 0; j < sidesPerPart[i]; j++){
      char* temp_name;
      temp_name = malloc((strlen(subsetName)+40)*sizeof(char));
      if (temp_name == NULL) {
     fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
     return FC_MEMORY_ERROR;
      }
      snprintf(temp_name,
            strlen(subsetName)+40,
            "%s_Shape%d_FaceSurface%d",
            subsetName, i,j);
      lshapes[i].adjmatrix[j] = (int*)malloc(sidesPerPart[i]*sizeof(int));
      lshapes[i].faces[j] = newFaceSubsets[partSideIDS[i][j]];
      fc_changeSubsetName(lshapes[i].faces[j],temp_name);
      snprintf(temp_name,
            strlen(subsetName)+40,
            "%s_Shape%d_ElemSurface%d",
            subsetName,i,j);
      lshapes[i].elems[j] = newElemSubsets[partSideIDS[i][j]];
      fc_changeSubsetName(lshapes[i].elems[j],temp_name);
      free(temp_name);
      for (k = 0; k < sidesPerPart[i]; k++){
     lshapes[i].adjmatrix[j][k] = adjmatrix[partSideIDS[i][j]][partSideIDS[i][k]];
      }
    }
  }
  free(subsetName);
  for (i = 0; i < numSides; i++){
    free(adjmatrix[i]);
  }
  free(adjmatrix);
  free(newFaceSubsets); //just the array
  free(newElemSubsets); //just the array
  for (i = 0 ; i <numParts; i++){
    free(partSideIDS[i]);
  }
  free(partSideIDS);
  free(sidesPerPart);
  *numShapes = numParts;
  *shapes = lshapes;
  return FC_SUCCESS;
}
FC_ReturnCode fc_initShape (FC_Shape * fcss)
inits a Shape
Description:
Blanks out a shape's fields w/o doing deallocation. This is used in cases where fc_freeShape is not feasible (e.g., can't just free a newly allocated shape becuase the numSides may be anything).
In most cases the user wont need to init a shape. The shape creation methods will handle the newly instantiated shape pointer properly and after that the user will be working with the created shape.
Modifications:
09/28/06 ACG created
Parameters:
fcss input - the shape
Definition at line 2414 of file shape.c.
References FC_Shape::adjmatrix, FC_Shape::elems, FC_Shape::faces, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, FC_SUCCESS, and FC_Shape::numSides.
Referenced by fc_copyShape(), fc_reduceShapeNumSides(), and fc_reshapeByAngle().
 {
  if (!fcss){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  fcss->faces= NULL;
  fcss->elems= NULL;
  fcss->adjmatrix= NULL;
  fcss->numSides = 0;
  return FC_SUCCESS;
}
FC_ReturnCode fc_printShape (FC_Shape * fcss, char * label, int verb)
prints a Shape
Description:
prints an FC_Shape
Todo:
test
Modifications:
06/05/06 ACG created
07/13/06 ACG dropped 'FC' in name
07/16/06 ACG dropped "skin" in name
07/18/06 ACG shape are is ptr
Parameters:
fcss input - the shape
Definition at line 2449 of file shape.c.
References FC_Shape::adjmatrix, FC_Shape::elems, FC_Shape::faces, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printSubset(), FC_SUCCESS, and FC_Shape::numSides.
Referenced by main().
 {
  FC_ReturnCode rc;
  int i,j;
  if (!fcss){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  if (label)
    printf(label);
  printf("Shape has %d sides\n",fcss->numSides);
  if (verb){
    printf("Faces:\n");
    for (i = 0; i < fcss->numSides; i++){
      rc = fc_printSubset(fcss->faces[i],"",verb);
    }
    printf("Elems:\n");
    for (i = 0; i < fcss->numSides; i++){
      rc = fc_printSubset(fcss->elems[i],"",verb);
    }
  }
  printf("AdjMatrix:\n");
  for (i = 0; i < fcss->numSides; i++){
    for (j = 0; j < fcss->numSides; j++){
      printf("%d ",fcss->adjmatrix[i][j]);
    }
    printf("\n");
  }
  printf("\n");
  return FC_SUCCESS;
}
FC_ReturnCode fc_reduceShapeNumSides (FC_Shape * inshape, int reducedNumSides, FC_Shape * reducedshape)
given a shape and a desired number of sides, fewer than the current number of sides, creates a new shape with the desired number of sides
Description:
Given a shape and a desired number of sides, fewer than the current number of sides, creates a new shape with the desired number of sides. This function is intended to be used to merge small, perhaps curved faces into a major side. For instance, if on a rectangular prism with curved edges you set the angle to determine the division between edges as large, then it may resolve into one continuous side; on the other hand, if you set it to small, then all faces along the curve may resolve into distinct sides. If you instead know that you want to end with 6 sides, then call shape with a small angle, resulting in too many sides, and then call this function to reduce the shape to a 6 sided shape, retaining the 6 largest sides.
The innards iterate assigning each reduced out side to an arbitrary side of distance 1 as given by the adj matrix. The reducedout faces therefore arent elegantly distributed into the new sides, and you may end up with odd adjacency matricies as a result.
The kept sides retain their same names and ordering.
See fc_reshapeByAngle
Todo:
avoid the shape copy at the end
intent is to later have another function that class this one that does the shape call and somehow decides what the ideal number and IDs of sides is. this could be done for basic shapes if there is a great discrepancy in the areas of the resulting sides - e.g., 6 large sides and a zillion small ones
Modifications:
08/09/06 ACG creating
09/27/06 ACG changing algorithm
Parameters:
inshape input - shape to be reduced
reducedNumSides input - number of sides to be in reduced shape
reducedshape output - the reduced shape
Definition at line 1725 of file shape.c.
References FC_Shape::adjmatrix, FC_Shape::elems, FC_Shape::faces, fc_addArrayMembersToSubset(), fc_addIntToSortedIntArray(), fc_calcDistanceMatrix(), fc_changeSubsetName(), fc_copyShape(), fc_copySubset(), fc_deleteIntFromSortedIntArray(), fc_freeShape(), fc_freeSortedIntArray(), fc_getMeshFromSubset(), fc_getReturnCodeText(), fc_getSubsetMembersAsArray(), fc_getSubsetName(), fc_initShape(), fc_initSortedIntArray(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, fc_printfWarningMessage, FC_SUCCESS, FC_Shape::numSides, FC_SortedIntArray::numVal, and FC_SortedIntArray::vals.
   {
  FC_ReturnCode rc, rc1, rc2;
  FC_Mesh mesh;
  int **distmatrix;
  //dont need to be sorted, just taking advantage of the selfexpansion
  FC_SortedIntArray *combosides, *newlyassignedsides;
  FC_SortedIntArray remainingsides;
  FC_Shape newshape;
  int i,j,k,l;
  //defaults
  if (reducedshape){
    fc_initShape(reducedshape);
  }
  if (!inshape || reducedNumSides < 1 ||
      reducedNumSides >= inshape->numSides ||
      !reducedshape){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  //log message
  fc_printfLogMessage("reduceShapeNumSides");
  rc = fc_getMeshFromSubset(inshape->faces[0],&mesh);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("Cant get mesh from subset");
    return rc;
  }
  //first copy the sides that we are keeping over
  combosides = (FC_SortedIntArray*)malloc(reducedNumSides*
                           sizeof(FC_SortedIntArray));
  newlyassignedsides = (FC_SortedIntArray*)malloc(reducedNumSides*
                           sizeof(FC_SortedIntArray));
  if (!combosides || ! newlyassignedsides){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < reducedNumSides; i++){
    rc1 = fc_initSortedIntArray(&combosides[i]);
    rc2 = fc_initSortedIntArray(&newlyassignedsides[i]);
    if (rc1 !=FC_SUCCESS || rc2 != FC_SUCCESS){
      fc_printfErrorMessage("Can't init SIA");
      for (j = 0; j < i; j++){
     fc_freeSortedIntArray(&combosides[j]);
     fc_freeSortedIntArray(&newlyassignedsides[j]);
      }
      free(combosides);
      free(newlyassignedsides);
      return (rc1 != FC_SUCCESS ? rc1 : rc2);
    }
    rc = fc_addIntToSortedIntArray(&combosides[i],i);
    if (rc < 0){
      fc_printfErrorMessage("Can't add int to SIA");
      for (j = 0; j < i; j++){
     fc_freeSortedIntArray(&combosides[j]);
     fc_freeSortedIntArray(&newlyassignedsides[j]);
      }
      free(combosides);
      free(newlyassignedsides);
      return rc;
    }
  }
  //get ids for left over faces
  rc = fc_initSortedIntArray(&remainingsides);
  if (rc !=FC_SUCCESS){
    fc_printfErrorMessage("Cant init sia");
    for (j = 0; j < reducedNumSides; j++){
      fc_freeSortedIntArray(&combosides[j]);
      fc_freeSortedIntArray(&newlyassignedsides[j]);
    }
    free(combosides);
    free(newlyassignedsides);
    return rc;
  }
  for (i = reducedNumSides; i < inshape->numSides; i++){
    rc = fc_addIntToSortedIntArray(&remainingsides,i);
    if (rc < 0){
      fc_printfErrorMessage("cant add int to SIA");
      for (j = 0; j < reducedNumSides; j++){
     fc_freeSortedIntArray(&combosides[j]);
     fc_freeSortedIntArray(&newlyassignedsides[j]);
      }
      free(combosides);
      free(newlyassignedsides);
      fc_freeSortedIntArray(&remainingsides);
      return rc;
    }
  }
  rc = fc_calcDistanceMatrix(inshape->numSides, inshape->adjmatrix,
                    &distmatrix);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("Can't get dist matrix");
    for (j = 0; j < reducedNumSides; j++){
      fc_freeSortedIntArray(&combosides[j]);
      fc_freeSortedIntArray(&newlyassignedsides[j]);
    }
    free(combosides);
    free(newlyassignedsides);
    fc_freeSortedIntArray(&remainingsides);
    return rc;
  }
  while(remainingsides.numVal){
    int assigned = 0;
    //find all sides that are distance 1 from one ofthe established sides
    //only update the established sides after each pass
    for (i = 0; i < remainingsides.numVal; i++){
      int foundside = 0;
      int comboid;
      int currside = remainingsides.vals[i];
      for (j = 0; j < reducedNumSides; j++){
     for (k = 0; k < combosides[j].numVal; k++){
       int compside = combosides[j].vals[k];
       comboid = j;
       if (distmatrix[currside][compside] ==1){
         foundside = 1;
         break;
       }
     }
     if (foundside)
       break;
      }
      if (foundside){
     rc1 = fc_addIntToSortedIntArray(&newlyassignedsides[j],currside);
     rc2 = fc_deleteIntFromSortedIntArray(&remainingsides,currside);
     if (rc1 < 0 || rc2 < 0){
       fc_printfErrorMessage("cant add/delete int to/from SIA");
       for (j = 0; j < reducedNumSides; j++){
         fc_freeSortedIntArray(&combosides[j]);
         fc_freeSortedIntArray(&newlyassignedsides[j]);
       }
       free(combosides);
       free(newlyassignedsides);
       fc_freeSortedIntArray(&remainingsides);
       for (j = 0; j < inshape->numSides; j++){
         free(distmatrix[j]);
       }
       free(distmatrix);
       return (rc1 < 0 ? rc1 : rc2);
     }
     assigned++;
      }
    }
    if (!assigned){
      fc_printfErrorMessage("None of the remaining sides are distance 1 from any of the current sides");
      for (j = 0; j < reducedNumSides; j++){
     fc_freeSortedIntArray(&combosides[j]);
     fc_freeSortedIntArray(&newlyassignedsides[j]);
      }
      free(combosides);
      free(newlyassignedsides);
      fc_freeSortedIntArray(&remainingsides);
      for (j = 0; j < inshape->numSides; j++){
     free(distmatrix[j]);
      }
      free(distmatrix);
      return FC_INPUT_ERROR;
    }
    //copy the newly assigned sides into the established sides
    for (i = 0; i < reducedNumSides; i++){
      for (j = 0; j < newlyassignedsides[i].numVal; j++){
     rc = fc_addIntToSortedIntArray(&combosides[i],newlyassignedsides[i].vals[j]);
     if (rc < 0){
       fc_printfErrorMessage("cant add int to SIA");
       for (j = 0; j < reducedNumSides; j++){
         fc_freeSortedIntArray(&combosides[j]);
         fc_freeSortedIntArray(&newlyassignedsides[j]);
       }
       free(combosides);
       free(newlyassignedsides);
       fc_freeSortedIntArray(&remainingsides);
       for (j = 0; j < inshape->numSides; j++){
         free(distmatrix[j]);
       }
       free(distmatrix);
       return rc;
     }
      }
      fc_freeSortedIntArray(&newlyassignedsides[i]);
    }
  } //while
  //clean up some things
  for (j = 0; j < inshape->numSides; j++){
    free(distmatrix[j]);
  }
  free(distmatrix);
  free(newlyassignedsides); //individual ones already freed
  fc_freeSortedIntArray(&remainingsides);
  //now build the new shape
  newshape.numSides = reducedNumSides;
  newshape.faces = (FC_Subset*)malloc(reducedNumSides*sizeof(FC_Subset));
  newshape.elems = (FC_Subset*)malloc(reducedNumSides*sizeof(FC_Subset));
  newshape.adjmatrix = (int**)malloc(reducedNumSides*sizeof(int*));
  if (!newshape.faces || !newshape.elems || !newshape.adjmatrix){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < reducedNumSides; i++){
    //allocate them all now so can use free shape as a set later
    newshape.adjmatrix[i] = (int*)malloc(reducedNumSides*sizeof(int));
    if (!newshape.adjmatrix[i]){
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    for (j = 0; j < reducedNumSides; j++){
      newshape.adjmatrix[i][j] = 0;
    }
  }
  for (i = 0; i < reducedNumSides; i++){
    int nume, numf;
    int *arrf, *arre;
    char *temp;
    //assign the first item in each combo side to the new side
    rc1 = fc_copySubset(inshape->faces[combosides[i].vals[0]],mesh,
               "temp",&(newshape.faces[i]));
    rc2 = fc_copySubset(inshape->elems[combosides[i].vals[0]],mesh,
               "temp",&(newshape.elems[i]));
    if (rc1 != FC_SUCCESS || rc2 != FC_SUCCESS){
      fc_printfErrorMessage("Cant copy subsets");
      for (j = 0; j <= i; j++){
     fc_freeSortedIntArray(&combosides[j]);
      }
      free(combosides);
      fc_freeShape(&newshape);
      return (rc1 != FC_SUCCESS ? rc1:rc2);
    }
    //rename them to what they were in that original position
    //if cant rename, just warn
    rc = fc_getSubsetName(inshape->faces[i],&temp);
    if (rc != FC_SUCCESS || temp == NULL){
      fc_printfWarningMessage("fc_reduceShapeNumSides can't get name for face side %d", i);
    }else{
      rc = fc_changeSubsetName(newshape.faces[i],temp);
      if (rc!= FC_SUCCESS){
     fc_printfWarningMessage("fc_reduceShapeNumSides can't rename face side %d", i);
      }
    }
    if (temp) free(temp);
    rc = fc_getSubsetName(inshape->elems[i],&temp);
    if (rc!= FC_SUCCESS || temp == NULL){
      fc_printfWarningMessage("fc_reduceShapeNumSides can't get name for elem side %d", i);
    }else{
      rc = fc_changeSubsetName(newshape.elems[i],temp);
      if (rc!= FC_SUCCESS){
     fc_printfWarningMessage("fc_reduceShapeNumSides can't rename elem side %d", i);
      }
    }
    if (temp) free(temp);
    //now copy all other members over
    for (j = 1; j < combosides[i].numVal; j++){
      int currside = combosides[i].vals[j];
      rc1 = fc_getSubsetMembersAsArray(inshape->faces[currside],
                           &numf,&arrf);
      rc2 = fc_getSubsetMembersAsArray(inshape->elems[currside],
                           &nume,&arre);
      if (rc1 != FC_SUCCESS || rc2 != FC_SUCCESS){
     fc_printfErrorMessage("Can't get subset members");
     for (j = 0; j < reducedNumSides; j++){
       fc_freeSortedIntArray(&combosides[j]);
     }
     free(combosides);
     fc_freeShape(&newshape);
     if (arrf) free (arrf);
     if (arre) free (arre);
     return (rc1 != FC_SUCCESS ? rc1 : rc2);
      }
      //make sure wont fail if add duplicates
      rc1 = fc_addArrayMembersToSubset(newshape.faces[i],
                           numf,arrf);
      rc1 = fc_addArrayMembersToSubset(newshape.elems[i],
                           nume,arre);
      free(arrf);
      free(arre);
      if (rc1 != FC_SUCCESS || rc2 != FC_SUCCESS){
     fc_printfErrorMessage("Can't add subset members");
     for (j = 0; j < reducedNumSides; j++){
       fc_freeSortedIntArray(&combosides[j]);
     }
     free(combosides);
     fc_freeShape(&newshape);
     return (rc1 != FC_SUCCESS ? rc1 : rc2);
      }
    } //combosides.numVal
  } // reducedNumSides
  //now all the sides have been assigned and the faces and the elems put in
  //the adj matrix is all zeros at this point
  for (i = 0; i < reducedNumSides; i++){
    for (j = i+1; j < reducedNumSides; j++){
      if (inshape->adjmatrix[i][j]){
     //if they were adj before, they still are
     newshape.adjmatrix[i][j] = 1;
     newshape.adjmatrix[j][i] = 1;
      }else{
     //they may now be adj becuase of the reducing
     for (k = 0; k < combosides[i].numVal; k++){
       for (l = 0; l < combosides[j].numVal; l++){
         int sideA = combosides[i].vals[k];
         int sideB = combosides[j].vals[l];
         if (inshape->adjmatrix[sideA][sideB]){
           newshape.adjmatrix[i][j] = 1;
           newshape.adjmatrix[j][i] = 1;
           break;
         }
       }
       if (newshape.adjmatrix[i][j]){
         //we found a match inside
         break;
       }
     }
      }
    }
  }
  //cleanup
  for (i = 0; i < reducedNumSides; i++){
    fc_freeSortedIntArray(&combosides[i]);
  }
  free(combosides);
  //handle this shape better
  rc = fc_copyShape(&newshape,reducedshape);
  fc_freeShape(&newshape);
  return FC_SUCCESS;
}
FC_ReturnCode fc_reorderShape (int * neworder, FC_Shape * shape)
given a new ordering of the sides, reorders a shape
Description:
Given a new ordering of the sides, reorders a shape. Example: given the orig sides (set0,set1,set2,set3,set4) with new order = (2,4,1,0,3) then the sides will be reordered to (set2,set4,set1,set0,set3). That is what was in place 2 has been moved to place 0, as opposed to moving what was in place 0 to place 2.
This keeps the original names of the subsets to allow referring to subsets by name to still be consistent. If you want to reorder the names, you must do so manually.
Modifications:
06/18/06 ACG created
06/19/06 ACG changed reorder so the indicies are now what the new order is going to be, rather than where the old order is moving to, because its more intuitive that way.
Parameters:
neworder input - array of new order of indicies
shape output - ptr to the shape
Definition at line 2222 of file shape.c.
References FC_Shape::adjmatrix, FC_Shape::elems, FC_Shape::faces, fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, and FC_Shape::numSides.
 {
  FC_Subset *temp, *temp2;
  int numSides;
  int** adjmatrix;
  int i,j;
  //no defaults
  if (!shape || !neworder){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("reordering shape");
  numSides = shape->numSides;
  //make sure neworder array makes sense
  int *test = calloc(numSides, sizeof(int));
  if (test == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < numSides; i++){
    if (neworder[i] < 0 || neworder[i] >= numSides){
      free(test);
      return FC_INPUT_ERROR;
    }
    test[neworder[i]] = 1;
  }
  for (i = 0; i < numSides; i++){
    if (!test[i]){
      free(test);
      return FC_INPUT_ERROR;
    }
  }
  free(test);
  //doesnt swap ptrs to subsets, since the subsets themselves are just handles.
  temp = (FC_Subset*)malloc(numSides*sizeof(FC_Subset));
  temp2 = (FC_Subset*)malloc(numSides*sizeof(FC_Subset));
  adjmatrix = (int**)malloc(numSides*sizeof(int*));
  if (temp == NULL || temp2 == NULL || adjmatrix == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < numSides; i++){
    temp[i] = shape->faces[neworder[i]];
    temp2[i] = shape->elems[neworder[i]];
    adjmatrix[i] = (int*)malloc(numSides*sizeof(int));
    if (adjmatrix[i] == NULL){
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
  }
  free(shape->faces);
  free(shape->elems);
  shape->faces = temp;
  shape->elems = temp2;
  for (i =0; i < numSides; i++){
    for (j =0; j < numSides; j++){
      adjmatrix[i][j] = shape->adjmatrix[neworder[i]][neworder[j]];
    }
  }
  for (i =0; i < numSides; i++){
    free(shape->adjmatrix[i]);
  }
  free(shape->adjmatrix);
  shape->adjmatrix = adjmatrix;
  return FC_SUCCESS;
}
FC_ReturnCode fc_reshapeByAngle (FC_Shape * inshape, double newangle, int seg_dim, FC_Shape * newshape)
given a shape and a new angle, creates a new shape where the sides are distinguished byt he new angle
Description:
given a shape and a new angle, creates a new shape where the sides are distinguished by the new angle. The shared dim is used to determine neighbors for comparison when you build the sides, but since you are limited only to those sides that are in the orginal shape, you should keep this to the orignal number used. (I have no way of checking that)
This function is intended to be used 1) when you get too few sides or 2) if you have too many sides, as an alternate crtieria for merging sides than fc_reduceShapeNumSides uses.
The face and elem subsets will be named "Reshape" postpended with "Shape#" followed by "_FaceSurface#" or "_ElemSurface#" where # will be the index into the array of subsets for that shape.
Todo:
check if segdim is a problem or not
better new shape name
Modifications:
08/19/06 ACG creating
Parameters:
inshape input - orig shape
newangle input - new angle used for the reshaping
seg_dim input - seg dim, should be that used for building the orig shape
newshape output - the new shape
Definition at line 1609 of file shape.c.
References _fc_buildFaceInfoListFromShape(), _fc_createShapePartsFromFaceInfoList(), _fc_freeSFI_Array(), FC_Shape::adjmatrix, FC_Shape::elems, FC_Shape::faces, fc_getMeshFromSubset(), fc_getReturnCodeText(), fc_initShape(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, and FC_Shape::numSides.
 {
  FC_ReturnCode rc;
  FC_Mesh mesh;
  _FC_SFI_ARRAY faceinfo_list;
  int numSides;
  FC_Subset* newFaceSubsets;
  FC_Subset* newElemSubsets;
  int **adjmatrix;
  char* newname = "Reshape";
  // default return - freeing shape is not an option
  if (newshape){
    fc_initShape(newshape);
  }
  if (!inshape || !newshape || newangle < 0 ||
      newangle > 180 || seg_dim < 0 || seg_dim > 2 ||
      !(inshape->numSides)){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  //log message
  fc_printfLogMessage("reshape by angle");
  //assume that since we have a shape already, the topology etc is correct.
  rc = fc_getMeshFromSubset(inshape->faces[0],&mesh);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("cant get mesh for shape");
    return rc;
  }
  rc = _fc_buildFaceInfoListFromShape(inshape,&faceinfo_list);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("can't build face info list\n");
    return rc;
  }
  rc = _fc_createShapePartsFromFaceInfoList(mesh,&faceinfo_list,
                             &newname,newangle,
                             seg_dim,
                             &numSides,
                             &newFaceSubsets,
                             &newElemSubsets,
                             &adjmatrix);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("can't create shape parts from face info list\n");
    _fc_freeSFI_Array(&faceinfo_list);
    return rc;
  }
  //unlike subsetshapes we want to return this as one shape
  newshape->numSides = numSides;
  newshape->faces = newFaceSubsets;
  newshape->elems = newElemSubsets;
  newshape->adjmatrix = adjmatrix;
  //dont free anything since theyve been assigned to the shape
  return FC_SUCCESS;
}
FC_ReturnCode fc_segmentAdjacencyMatrix (int matrixdim, int ** adjmatrix, int * numsegments, int ** sidespersegment, int *** sideids)
Given an adjacency matrix, returns segments of it based on connectivities.
Description:
Given an adjacency matrix, returns segments of it based on connectivities
Note that pieces that are touching will come out as 1 distinct shape with a lot of edges as opposed to two distinct shapes. Segment will do the same thing.
Modifications:
06/01/06 ACG created.
06/23/06 ACG unittested, added defaults and input checking
Parameters:
matrixdim input - dim of the adj matrix
adjmatrix input - adj matrix
numsegments output - number of distinct shapes
sidespersegment output - number of sides for each distinct shape
sideids output - array of sideids(orig matrix numbers) for each distinct shape
Definition at line 3307 of file shape.c.
References FC_ERROR, fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by fc_getSubsetShapes().
 {
  int numSides;
  int **partsideids; /* array of arrays, 1 for each part */
  int *sidesperpart;
  int numparts;
  int maxparts;
  int *search;
  int i,j,k;
  //defaults
  if (numsegments)
    *numsegments = -1;
  if (sidespersegment)
    *sidespersegment = NULL;
  if (sideids)
    *sideids = NULL;
  if (matrixdim < 1 || !adjmatrix || !numsegments || !sidespersegment ||
      !sideids){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Segmenting Adj Matrix");
  //test that the matrix is symm and only has 0 & 1
  for (i = 0; i < matrixdim; i++){
    if (adjmatrix[i][i] != 0){
      fc_printfErrorMessage("adj matrix diag elem must be zero");
      return FC_ERROR;
    }
    for (j = 0; j < matrixdim; j++){
      if (adjmatrix[i][j] != adjmatrix[j][i] ||
       (adjmatrix[i][j] != 1 && adjmatrix[i][j] != 0)){
     fc_printfErrorMessage("adj matrix must be symm and elems must be 0 or 1");
     return FC_ERROR;
      }
    }
  }
  numSides = matrixdim;
  partsideids = (int**)malloc(sizeof(int*));
  sidesperpart = (int*)malloc(sizeof(int));
  search = (int*)malloc(numSides*sizeof(int));
  if (partsideids == NULL || sidesperpart == NULL || search == NULL){
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
  }
  for(i = 0; i < numSides; i++){
    search[i] = 1;
  }
  numparts = 0;
  maxparts = 1;
  for (i = 0; i < numSides; i++){
    if (search[i]){//start a new part
      int* currpartids;
      int currmax, currnum;
      currpartids = (int*)malloc(sizeof(int));
      if(currpartids == NULL){
     fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
     return FC_MEMORY_ERROR;
      }
      currpartids[0] = i;
      currnum = 1;
      currmax = 1;
      search[i] = 0;
      for (j = 0; j < currnum; j++){
     //find all the adj of this member
     for (k = 0; k < numSides; k++){
       if (search[k] && adjmatrix[currpartids[j]][k] == 1){
         //add to the currpart ids
         if (currnum == currmax){
           int *temp;
           temp = (int*)realloc(currpartids,(2*currmax)*sizeof(int));
           if (temp == NULL){
          fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
          return FC_MEMORY_ERROR;
           }
           currmax*=2;
           currpartids = temp;
         }
         currpartids[currnum] = k; //add this side to the current part
         currnum++;
         search[k] = 0; //take it out of the options
       }
     }
      }
      //now hand it off
      if (numparts == maxparts){
     int **temp;
     int *temp2;
     temp = (int**)realloc(partsideids,(2*maxparts)*sizeof(int*));
     if (temp == NULL){
       fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
       return FC_MEMORY_ERROR;
     }
     temp2 = (int*)realloc(sidesperpart,(2*maxparts)*sizeof(int));
     if (temp == NULL){
       fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
       return FC_MEMORY_ERROR;
     }
     maxparts*=2;
     partsideids = temp;
     sidesperpart = temp2;
      }
      partsideids[numparts] = currpartids;
      sidesperpart[numparts] = currnum;
      numparts++;
    }
  }
  *numsegments = numparts;
  *sidespersegment =sidesperpart;
  *sideids = partsideids;
  free(search);
  return FC_SUCCESS;
}