FCLib: (Private)
(Private)
[Subset]
Data Structures
struct _FC_SubSlot
Struct describing subset elements.
Functions
void _fc_initSubSlot (_FC_SubSlot *subSlot)
Initialize a subset slot.
void _fc_releaseSubSlot (_FC_SubSlot *subSlotp)
Release non-necessary resources in a subset slot.
void _fc_clearSubSlot (_FC_SubSlot *subSlotp)
Clear a subset slot.
int _fc_getSubTableSize ()
Get the size of the subset table.
_FC_SubSlot * _fc_getSubSlot (FC_Subset subset)
Get a subset slot from a subset handle.
_FC_SubSlot * _fc_getSubSlotFromID (int subID)
Get a subset slot based on ID.
FC_ReturnCode _fc_deleteSubSlot (FC_Subset subset)
Delete the subset slot associated with the subset handle.
_FC_SubSlot * _fc_getNewSubSlot ()
Get an empty subset slot from the subset table.
void _fc_printSubTable (char *label)
Print the contents of the Subset Table (subTable) to stderr.
void _fc_freeSubTable ()
Free all entries in the subset table.
Variables
static int subTableSize = 0
The number of allocated slots in the subset table.
static _FC_SubSlot ** subTable = NULL
The subset table.
static FC_SortedIntArray subOpenSlots = { 0, 0, 0 }
The list of unused slots in the subset table.
Function Documentation
void _fc_clearSubSlot (_FC_SubSlot * subSlotp)
Clear a subset slot.
Description:
Releases all dynamically allocated resources in a variable, and reinitializes all members.
Modifications:
05/11/04 WSK Created.
Parameters:
subSlotp input - subset slot
Definition at line 3755 of file subset.c.
References _fc_clearSlotHeader(), _fc_initSubSlot(), _fc_releaseSubSlot(), and _FC_SubSlot::header.
Referenced by _fc_deleteSubSlot(), and _fc_freeSubTable().
  {
  if (subSlotp != NULL) {
    // free big data
    _fc_releaseSubSlot(subSlotp);
    // free other dynamic arrays, if any
    // clear table header
    _fc_clearSlotHeader(&subSlotp->header);
    // reinit
    _fc_initSubSlot(subSlotp);
  }
}
FC_ReturnCode _fc_deleteSubSlot (FC_Subset subset)
Delete the subset slot associated with the subset handle.
Description:
This routine clears the dynamic data in the slot and then deletes the slot from the table.
Modifications:
12/20/2005 WSD. Created.
Parameters:
subset input - subset
Definition at line 3845 of file subset.c.
References _fc_clearSubSlot(), _fc_deleteSlot(), _fc_getSubSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, _FC_SubSlot::header, _FC_SlotHeader::slotID, and subTableSize.
Referenced by fc_deleteSeqSubset(), and fc_deleteSubset().
  {
  _FC_SubSlot* subSlot;
  subSlot = _fc_getSubSlot(subset);
  if (subSlot == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // do it
  _fc_clearSubSlot(subSlot);
  return _fc_deleteSlot(subSlot->header.slotID, subTableSize,
               (_FC_SlotHeader**)subTable, &subOpenSlots);
}
void _fc_freeSubTable (void)
Free all entries in the subset table.
Description:
This should only be called after making sure that all slots have been cleared.
Modifications:
05/21/04 WSK Created.
Definition at line 3954 of file subset.c.
References _fc_clearSubSlot(), fc_freeSortedIntArray(), and subTableSize.
Referenced by fc_finalLibrary().
{
  int i;
  for (i = 0; i < subTableSize; i++) {
    _fc_clearSubSlot(subTable[i]);
    free(subTable[i]);
  }
  free(subTable);
  fc_freeSortedIntArray(&subOpenSlots);
  subTableSize = 0;
  subTable = NULL;
}
_FC_SubSlot* _fc_getNewSubSlot (void)
Get an empty subset slot from the subset table.
Description:
Will return a new slot or NULL. A NULL means a memory error occurred.
Modifications:
5/11/04 WSK Created.
Definition at line 3873 of file subset.c.
References _fc_getNewSlot(), _fc_initSubSlot(), and subTableSize.
Referenced by fc_createSeqSubset(), and fc_createSubset().
{
  _FC_SubSlot* subSlot;
  subSlot = (_FC_SubSlot*) _fc_getNewSlot(&subTableSize,
                           (_FC_SlotHeader***)&subTable,
                           &subOpenSlots, sizeof(_FC_SubSlot));
  _fc_initSubSlot(subSlot);
  return subSlot;
}
_FC_SubSlot* _fc_getSubSlot (FC_Subset subset)
Get a subset slot from a subset handle.
Description:
The slot id of the subset handle is used to find the the slot in the subset table. The identity is then verified by checking that the slot and the handle's uIDs are the same. On success, a pointer to the slot is returned. Otherwise a NULL pointer is returned.
Modifications:
05/11/04 WSK Created
05/25/04 WSK Changed to call new _fc_isHandleValid common to all tables.
Parameters:
subset input - subset
Definition at line 3800 of file subset.c.
References _fc_isHandleValid(), FC_Subset::slotID, subTableSize, and FC_Subset::uID.
Referenced by _fc_deleteSubSlot(), _fc_loadExodusDataset(), _fc_readExodusSubsetMembers(), _fc_readSubsetMembers(), _fc_writeExodusDataset(), fc_addArrayMembersToSubset(), fc_addMaskMembersToSubset(), fc_addMemberToSubset(), fc_changeSeqSubsetName(), fc_changeSubsetName(), fc_convertSeqSubsetToSubsets(), fc_convertSubsetsToSeqSubset(), fc_copySeqSubset(), fc_copySubset(), fc_copySubsetWithNewAssociation(), fc_createSubsetComplement(), fc_createSubsetMesh(), fc_deleteArrayMembersFromSubset(), fc_deleteMaskMembersFromSubset(), fc_deleteMemberFromSubset(), fc_deleteSeqSubset(), fc_deleteSubset(), fc_getMeshFromSubset(), fc_getSequenceFromSeqSubset(), fc_getSubsetAssociationType(), fc_getSubsetInfo(), fc_getSubsetMaxNumMember(), fc_getSubsetMembersAsArray(), fc_getSubsetMembersAsMask(), fc_getSubsetName(), fc_getSubsetNumMember(), fc_isMemberInSubset(), fc_isSeqSubsetValid(), fc_printSeqSubsetRange(), fc_printSubset(), fc_projectedSubsetElementBoundingBoxIntersection(), fc_releaseSeqSubset(), fc_releaseSubset(), fc_rewriteDataset(), and fc_segment().
  {
  if (_fc_isHandleValid(subset.slotID, subset.uID, subTableSize,
                        (_FC_SlotHeader**)subTable))
    return subTable[subset.slotID];
  else
    return NULL;
}
_FC_SubSlot* _fc_getSubSlotFromID (int subID)
Get a subset slot based on ID.
Description:
The _FC_SubSlot at the requested slotID is returned. This should only be used when you really know that it is the slot you want because there is no checking of the uID like with _fc_getSubSlot. The only checking is that the slotID is exists in the table and that the uID is > 0 (i.e. it is not empty).
Modifications:
05/11/04 WSK Created.
05/25/04 WSK Changed to call new _fc_getSlot() common to all tables.
Definition at line 3826 of file subset.c.
References _fc_getSlot(), and subTableSize.
Referenced by fc_getSeqSubsetByName(), fc_getSeqSubsets(), fc_getSubsetByName(), and fc_getSubsets().
  {
  return (_FC_SubSlot*) _fc_getSlot(subID, subTableSize,
                                   (_FC_SlotHeader**)subTable);
}
int _fc_getSubTableSize (void)
Get the size of the subset table.
Modifications:
05/21/04 WSK Created.
Definition at line 3780 of file subset.c.
References subTableSize.
{
  return subTableSize;
}
void _fc_initSubSlot (_FC_SubSlot * subSlot)
Initialize a subset slot.
Modifications:
05/11/04 WSK. Created.
03/03/08 ACG support sequence subset
Parameters:
subSlot input - the subset slot to initialize
Definition at line 3706 of file subset.c.
References _fc_initSlotHeader(), _FC_SubSlot::assoc, FC_AT_UNKNOWN, fc_initSortedIntArray(), FC_NULL_MESH, FC_NULL_SEQUENCE, _FC_SubSlot::header, _FC_SubSlot::maxNumMember, _FC_SubSlot::mesh, _FC_SubSlot::numMember, _FC_SubSlot::sequence, _FC_SubSlot::sia, and _FC_SubSlot::stepID.
Referenced by _fc_clearSubSlot(), and _fc_getNewSubSlot().
  {
  if (subSlot != NULL) {
    _fc_initSlotHeader(&subSlot->header);
    subSlot->mesh = FC_NULL_MESH;
    subSlot->sequence = FC_NULL_SEQUENCE;
    subSlot->stepID = -1;
    subSlot->assoc = FC_AT_UNKNOWN;
    subSlot->numMember = 0;
    subSlot->maxNumMember = 0;
    fc_initSortedIntArray(&subSlot->sia);
  }
}
void _fc_printSubTable (char * label)
Print the contents of the Subset Table (subTable) to stderr.
Description:
Prints the contents of the Subset Table in a human readable form. It takes a string to use as a label for this print out of the table. Pass NULL if you don't want a label.
Modifications:
12/8/04 WSK created.
Parameters:
label Input - label for this version the table (without a trailing \n) pass NULL if no label is desired
Definition at line 3897 of file subset.c.
References _fc_printSlotHeader(), _FC_SubSlot::assoc, fc_getAssociationTypeText(), _FC_SubSlot::header, _FC_SubSlot::maxNumMember, FC_SortedIntArray::maxNumVal, _FC_SubSlot::mesh, _FC_SubSlot::numMember, FC_SortedIntArray::numVal, _FC_SubSlot::sia, FC_Mesh::slotID, subTableSize, TABLE_DIVIDER_STRING, FC_Mesh::uID, and FC_SortedIntArray::vals.
  {
  int i;
  _FC_SubSlot* subSlot;
  // print table heading
  fprintf(stderr, TABLE_DIVIDER_STRING);
  fprintf(stderr, "Subset Table (subTable):\n");
  if (label != NULL)
    fprintf(stderr, "%s\n", label);
  fprintf(stderr, TABLE_DIVIDER_STRING);
  fflush(NULL);
  // We're done if it's empty
  if (subTableSize < 1) {
    fprintf(stderr, "(empty)\n");
    fprintf(stderr, "\n");
    fflush(NULL);
    return;
  }
  // print contents for each slot
  for (i = 0; i < subTableSize; i++) {
    subSlot = subTable[i];
    fprintf(stderr, "%3d: %s\n", i, (subSlot) ? "exists" : "NULL");
    if (subSlot == NULL)
      continue;
    _fc_printSlotHeader(subSlot->header);
    fprintf(stderr, "     FC_Mesh = { %d, %d }\n",
            subSlot->mesh.slotID, subSlot->mesh.uID);
    fprintf(stderr, "     assoc = %s, numMember = %d, maxNumMember = %d\n",
            fc_getAssociationTypeText(subSlot->assoc), subSlot->numMember,
            subSlot->maxNumMember);
    fprintf(stderr, "     sia.numVal = %d, sia.maxNumVal = %d, sia.vals = %s\n",
         subSlot->sia.numVal, subSlot->sia.maxNumVal,
         (subSlot->sia.vals) ? "exists" :"NULL");
  }
  fprintf(stderr, "\n");
  fflush(NULL);
  return;
}
void _fc_releaseSubSlot (_FC_SubSlot * subSlotp)
Release non-necessary resources in a subset slot.
Description:
Releases the members
Modifications:
05/11/04 WSK Created.
Parameters:
subSlotp input - subset slot
Definition at line 3732 of file subset.c.
References fc_freeSortedIntArray(), and _FC_SubSlot::sia.
Referenced by _fc_clearSubSlot().
  {
  if (subSlotp) {
    // release big data
    fc_freeSortedIntArray(&subSlotp->sia);
  }
  return;
}
Variable Documentation
FC_SortedIntArray subOpenSlots = { 0, 0, 0 } [static]
The list of unused slots in the subset table.
Definition at line 109 of file subset.c.
_FC_SubSlot** subTable = NULL [static]
The subset table.
Definition at line 104 of file subset.c.
int subTableSize = 0 [static]
The number of allocated slots in the subset table.
Definition at line 99 of file subset.c.
Referenced by _fc_deleteSubSlot(), _fc_freeSubTable(), _fc_getNewSubSlot(), _fc_getSubSlot(), _fc_getSubSlotFromID(), _fc_getSubTableSize(), _fc_printSubTable(), and fc_isSubsetValid().