FCLib: Mesh
Mesh
[Data Interface]
Detailed Description
Operations on meshes.
Description:
(For an explanation of general data manipulations, see Data Interface.)
Modules
(Private)
Create new mesh from scratch.
FC_ReturnCode fc_createMesh (FC_Dataset dataset, char *meshname, FC_Mesh *mesh)
Create a new mesh.
FC_ReturnCode fc_setMeshCoords (FC_Mesh mesh, int dim, int numVertex, double *coords)
Set the mesh coordinates by copy.
FC_ReturnCode fc_setMeshCoordsPtr (FC_Mesh mesh, int dim, int numVertex, double *coords)
Set the pointer to the mesh coordinates.
FC_ReturnCode fc_setMeshElementConns (FC_Mesh mesh, FC_ElementType elemType, int numElem, int *connectivities)
Set the mesh element to vertex connectivities by copy.
FC_ReturnCode fc_setMeshElementConnsPtr (FC_Mesh mesh, FC_ElementType elemType, int numElem, int *connectivities)
Set the pointer to the mesh element connectivities.
Other ways to get new meshes.
FC_ReturnCode fc_copyMesh (FC_Mesh src_mesh, FC_Dataset dest_ds, char *newName, int doCopyVar, int doCopySeqVar, int doCopySubset, int doCopySeqSubset, FC_Mesh *new_mesh)
Copy a mesh.
FC_ReturnCode fc_createSubsetMesh (FC_Subset subset, FC_Dataset dest_ds, int doStrict, int doCopyVar, int doCopySeqVar, int doCopySubset, int doCopySeqSubset, char *newName, FC_Mesh *new_mesh, FC_Variable *vertmap, FC_Variable *elemmap)
Create a new mesh which is the subset of another mesh.
FC_ReturnCode fc_createSimpleHexMesh (FC_Dataset dataset, char *newName, int N, int M, int P, double *lower_coords, double *upper_coords, FC_Mesh *new_mesh)
Create a simple hex mesh.
FC_ReturnCode fc_createSphereMesh (FC_Dataset dataset, char *newName, FC_Coords center, double radius, int requestedNodes, FC_Mesh *new_mesh)
Create a simple sphere mesh.
FC_ReturnCode fc_setSphereDisplacementVariable (FC_Variable displacement_var, FC_Coords new_center, double new_radius)
Update a displacement variable for a sphere to have a new center and radius.
FC_ReturnCode _fc_setSphereCoords (int numVerts, FC_Coords center, double radius, double *coords)
Set coordinates for a sphere mesh.
Get existing meshes.
FC_ReturnCode fc_getMeshes (FC_Dataset dataset, int *numMesh, FC_Mesh **meshes)
Get the meshes in a dataset.
FC_ReturnCode fc_getNumMesh (FC_Dataset dataset, int *numMesh)
Get the the number of meshes in a dataset.
FC_ReturnCode fc_getMeshByName (FC_Dataset dataset, char *meshname, int *numMeshes, FC_Mesh **meshes)
Get all meshes with a given name from the dataset.
Change the name of a mesh.
FC_ReturnCode fc_changeMeshName (FC_Mesh mesh, char *newName)
Change the name of a mesh.
Release/delete meshes.
FC_ReturnCode fc_releaseMesh (FC_Mesh mesh)
Attempt to minimize mesh's memory usage.
FC_ReturnCode fc_deleteMesh (FC_Mesh mesh)
Delete a mesh.
Get mesh metadata.
int fc_isMeshValid (FC_Mesh mesh)
Check that the handle refers to a valid mesh.
FC_ReturnCode fc_getMeshName (FC_Mesh mesh, char **meshname)
Return name of a mesh.
FC_ReturnCode fc_getDatasetFromMesh (FC_Mesh mesh, FC_Dataset *dataset)
Get the parent dataset of the mesh.
FC_ReturnCode fc_getMeshInfo (FC_Mesh mesh, int *topodim, int *dim, int *numVertex, int *numElement, FC_ElementType *elemType)
Get information about a mesh.
FC_ReturnCode fc_getMeshTopodim (FC_Mesh mesh, int *topodim)
Returns the topological dimensionality of the mesh.
FC_ReturnCode fc_getMeshDim (FC_Mesh mesh, int *dim)
Returns dimensionality of the mesh coordinates.
FC_ReturnCode fc_getMeshNumVertex (FC_Mesh mesh, int *numVertex)
Return the number of vertices in a mesh.
FC_ReturnCode fc_getMeshNumElement (FC_Mesh mesh, int *numElem)
Returns number of elements in a mesh.
FC_ReturnCode fc_getMeshElementType (FC_Mesh mesh, FC_ElementType *elemType)
Returns type of elements in the mesh.
FC_ReturnCode fc_getMeshEdgeFaceInfo (FC_Mesh mesh, int *numEdge, int *numFace, FC_ElementType *faceType)
Get information about edges and faces in a mesh.
FC_ReturnCode fc_getMeshNumEdge (FC_Mesh mesh, int *numEdge)
Get number of edges in a mesh.
FC_ReturnCode fc_getMeshNumFace (FC_Mesh mesh, int *numFace)
Get number of faces in a mesh.
FC_ReturnCode fc_getMeshFaceType (FC_Mesh mesh, FC_ElementType *faceType)
Get element type of the face in the mesh.
FC_ReturnCode fc_getMeshNumEntity (FC_Mesh mesh, FC_AssociationType assoc, int *numEntity)
Returns number of a type of mesh entity.
FC_ReturnCode fc_getMeshEntityElementType (FC_Mesh mesh, FC_AssociationType assoc, int ID, FC_ElementType *elemType)
Get the element type of the mesh entity.
Get mesh big data.
FC_ReturnCode fc_getMeshCoordsPtr (FC_Mesh mesh, double **coords_p)
Return the vertex coordinates of the mesh.
FC_ReturnCode fc_getMeshCoordsAsVariable (FC_Mesh mesh, FC_Variable *coords_var)
Return the vertex coordinates of the mesh as a variable.
FC_ReturnCode fc_getMeshEdgeConnsPtr (FC_Mesh mesh, int **conns_p)
Return edge connectivities.
FC_ReturnCode fc_getMeshFaceTypesPtr (FC_Mesh mesh, FC_ElementType **faceTypes_p)
Return face types.
FC_ReturnCode fc_getMeshFaceConnsPtr (FC_Mesh mesh, int **numVertPerFace_p, int *maxNumVertPerFace_p, int **conns_p)
Return face connectivities.
FC_ReturnCode fc_getMeshElementConnsPtr (FC_Mesh mesh, int **conns_p)
Return element to vertex connectivities for the mesh.
FC_ReturnCode fc_getMeshElementToEdgeConnsPtr (FC_Mesh mesh, int **elemToEdgeConns_p)
Return element to edge connectivities.
FC_ReturnCode fc_getMeshElementToFaceConnsPtr (FC_Mesh mesh, int **elemToFaceConns_p)
Return element to face connectivities.
FC_ReturnCode fc_getMeshElementFaceOrientsPtr (FC_Mesh mesh, int **elemFaceOrients_p)
Return element's face's orientations relative to global faces.
Print mesh.
FC_ReturnCode fc_printMesh (FC_Mesh mesh, char *label, int print_edgeConns, int print_faceConns, int print_elemConns, int print_coords)
Print mesh meta data to stdout, and optionally the connections and/or coordinates.
Function Documentation
FC_ReturnCode _fc_setSphereCoords (int numVerts, FC_Coords center, double radius, double * coords)
Set coordinates for a sphere mesh.
Description:
This function creates a spehere mesh.
Note: numVerts must equal sqrt((numVerts-2)^2)+2 Note: the user supplies the coords array. This function just fills it in (no boundary checks are performed)
Modifications:
04/08/2008 CDU Created
Parameters:
numVerts Input - the number of vertices that describe the sphere.
center Input - coordinate for where sphere's center is located
radius Input - the radius of the spehere
coords Output - the pre-allocated array that holds the vertex coordinates
Definition at line 1875 of file mesh.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, and FC_SUCCESS.
Referenced by fc_createSphereMesh(), and fc_setSphereDisplacementVariable().
 {
  int numPlane;
  int place, zcount, i;
  const int numDim=3;
  double phi, theta;
  const double toRad = (M_PI/180.0);
  //quick check to make sure not null ptr
  if(!center || !coords){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_SUCCESS;
  }
  //Verify that we were given something with the right number of coordinates
  numPlane = sqrt(numVerts-2);
  if(numPlane*numPlane != numVerts-2){
    fc_printfErrorMessage("%s : given a number vertices that isn't sqrt((numVerts-2)^2)+2 == numVerts", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  //Work your way down all of the planes and all the circles
  place =0;
  phi  =180.0/(double)(numPlane+1);
  theta=360.0/(double)numPlane;
  for(zcount=1; zcount<=numPlane; zcount++){
    double zplane = cos((double)zcount*phi*toRad);
    for(i=0;i<numPlane; i++){
      double r=sqrt(1-zplane*zplane);
      coords[place*numDim+0] = center[0] + radius*(r*cos(theta*(double)i*toRad));
      coords[place*numDim+1] = center[1] + radius*(r*sin(theta*(double)i*toRad));
      coords[place*numDim+2] = center[2] + radius*zplane;
      //printf("(Plane %d Spot %d) <%.3lf, %.3lf, %.3lf>\n", zcount, place,
      //     coords[place*numDim+0],coords[place*numDim+1],coords[place*numDim+2]);
      place++;
    }
  }
  //Top
  coords[place*numDim+0] = center[0] + 0.0;
  coords[place*numDim+1] = center[1] + 0.0;
  coords[place*numDim+2] = center[2] + radius;
  place++;
  //Bottom
  coords[place*numDim+0] = center[0] + 0.0;
  coords[place*numDim+1] = center[1] + 0.0;
  coords[place*numDim+2] = center[2] - radius;
  place++;
  return FC_SUCCESS;
}
FC_ReturnCode fc_changeMeshName (FC_Mesh mesh, char * newName)
Change the name of a mesh.
Modifications:
8/24/2005 WSD. Created.
Parameters:
mesh Input - the mesh.
newName Input - new name for the mesh.
Definition at line 2369 of file mesh.c.
References _fc_getMeshSlot(), _fc_setSlotHeaderName(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, _FC_MeshSlot::header, and _FC_SlotHeader::name.
  {
  _FC_MeshSlot* meshSlot;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || newName == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Changing name of mesh from '%s' to '%s'",
                      meshSlot->header.name, newName);
  // Do it
  return _fc_setSlotHeaderName(&meshSlot->header, newName);
}
FC_ReturnCode fc_copyMesh (FC_Mesh src_mesh, FC_Dataset dest_ds, char * newName, int doCopyVar, int doCopySeqVar, int doCopySubset, int doCopySeqSubset, FC_Mesh * new_mesh)
Copy a mesh.
Description:
Create a copy of a mesh, in the specified dataset, with the given name. There is a flag to copy only the geom vs copying subsets and variables on the mesh.
Note: if you chose to copy the sub/var, if there are any sequence subsets/variables on the mesh, this routine may copy their related sequences if they do not exist in the destination dataset.
Note that this does not copy the globals, since those are on the dataset and not on the mesh
Todo:
Should better define what constitutes an appropriate sequence when copying sequence variables. Right now very conservative: expects to find essentially the same sequence: same name & same data values.
test doCopy = 0 option
test individual copy flags
Modifications:
2003-NOV-11 WSK Created
10/4/04 WSK, changed internals so they call more routines and go to the structs less often.
01/12/08 ACG - option to only copy geom
03/07/08 ACG - copy seq subset
06/17/08 ACG - individual copy flags
Parameters:
src_mesh Input - the source mesh to be copied
dest_ds Input - the destination dataset to be copied into
newName Input - the name of the new mesh, a NULL value is a flag to use the name of the source mesh
doCopyVar Input - 1 to copy over the var
doCopySeqVar Input - 1 to copy over the seqvar
doCopySubset Input - 1 to copy over the subsets
doCopySeqSubset Input - 1 to copy over the seqsubsets
new_mesh Output - handle to the new mesh
Definition at line 471 of file mesh.c.
References _fc_getDsSlot(), _fc_getMeshSlot(), _FC_MeshSlot::coordVarID, _FC_MeshSlot::ds, fc_copySeqSubset(), fc_copySequence(), fc_copySeqVariable(), fc_copySubset(), fc_copyVariable(), fc_createMesh(), fc_getMeshCoordsAsVariable(), fc_getMeshCoordsPtr(), fc_getMeshElementConnsPtr(), fc_getMeshInfo(), fc_getReturnCodeText(), fc_getSeqSubsets(), fc_getSequenceCoordsPtr(), fc_getSequenceFromSeqSubset(), fc_getSequenceFromSeqVariable(), fc_getSequenceInfo(), fc_getSequenceName(), fc_getSequences(), fc_getSeqVariables(), fc_getSubsets(), fc_getVariables(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, FC_NULL_MESH, FC_NULL_SEQUENCE, fc_printfErrorMessage, fc_printfLogMessage, fc_setMeshCoords(), fc_setMeshElementConns(), fc_sizeofDataType(), FC_SUCCESS, _FC_MeshSlot::header, and _FC_SlotHeader::name.
Referenced by fc_copyDataset(), fc_createSubsetMesh(), and processOneVar().
  {
  int i, j;
  FC_ReturnCode rc;
  int topodim, dim, numVert, numElem;
  int numSubset, numSeqSub, numVariable, numSeqVar, *numStepPerSeq;
  FC_Subset *subsets, new_subset, **seqSubs, *new_seqSub;
  FC_Variable *variables, new_var, **seqVars, *new_seqVar;
  FC_ElementType elemType;
  double *coords;
  int* conns;
  _FC_DsSlot* dest_dsSlot;
  _FC_MeshSlot* src_meshSlot;
  // default return value
  if (new_mesh)
    *new_mesh = FC_NULL_MESH;
  // check input
  dest_dsSlot = _fc_getDsSlot(dest_ds);
  src_meshSlot = _fc_getMeshSlot(src_mesh);
  if (dest_dsSlot == NULL || src_meshSlot == NULL || new_mesh == NULL
      || (doCopyVar < 0 || doCopyVar > 1 )
      || (doCopySeqVar < 0 || doCopySeqVar > 1 )
      || (doCopySubset < 0 || doCopySubset > 1 )
      || (doCopySeqSubset < 0 || doCopySeqSubset > 1 )){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // test for NULL name
  if (newName == NULL)
    newName = src_meshSlot->header.name;
  // log message
  fc_printfLogMessage("Copying mesh '%s' to '%s'", src_meshSlot->header.name,
                      newName);
  // get src data
  rc = fc_getMeshInfo(src_mesh, &topodim, &dim, &numVert, &numElem,
                        &elemType);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get info for mesh '%s'",
                          src_meshSlot->header.name);
    return rc;
  }
  rc = fc_getMeshCoordsPtr(src_mesh, &coords);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get coords for mesh '%s'",
                          src_meshSlot->header.name);
    return rc;
  }
  rc = fc_getMeshElementConnsPtr(src_mesh, &conns);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get connectivities for mesh '%s'",
                          src_meshSlot->header.name);
    return rc;
  }
  // create new mesh
  rc = fc_createMesh(dest_ds, newName, new_mesh);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get create new mesh '%s'", newName);
    return rc;
  }
  rc = fc_setMeshCoords(*new_mesh, dim, numVert, coords);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to set vertices on mesh '%s'", newName);
    return rc;
  }
  rc = fc_setMeshElementConns(*new_mesh, elemType, numElem, conns);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to set elements on mesh '%s'", newName);
    return rc;
  }
  if (doCopyVar == 0 && doCopySeqVar == 0 && doCopySubset == 0 && doCopySeqSubset == 0){
    return FC_SUCCESS;
  }
  // Note: if you change behavior here, might want to change in
  // fc_createSubsetMesh() too
  if (doCopySubset){
    // copy the subsets
    rc = fc_getSubsets(src_mesh, &numSubset, &subsets);
    if (rc != FC_SUCCESS)
      return rc;
    for (i = 0; i < numSubset; i++) {
      rc = fc_copySubset(subsets[i], *new_mesh, NULL, &new_subset);
      if (rc != FC_SUCCESS) {
     fc_printfErrorMessage("Failed to copy member subset");
     return rc;
      }
    }
    free(subsets);
  }
  if (doCopyVar){
    // copy the basic variables
    rc = fc_getVariables(src_mesh, &numVariable, &variables);
    if (rc != FC_SUCCESS)
      return rc;
    for (i = 0; i < numVariable; i++) {
      // do something different for the mesh 'coords as variable'
      if (variables[i].slotID == src_meshSlot->coordVarID) {
     rc = fc_getMeshCoordsAsVariable(*new_mesh, &new_var);
     if (rc != FC_SUCCESS) {
       fc_printfErrorMessage("Failed to create copy of coords variable");
       return rc;
     }
      }
      // normal path for variables
      else {
     rc = fc_copyVariable(variables[i], *new_mesh, NULL, &new_var);
     if (rc != FC_SUCCESS) {
       fc_printfErrorMessage("Failed to copy member variable");
       return rc;
     }
      }
    }
    free(variables);
  }
  if (doCopySeqVar){
    // copy the sequence variables
    rc = fc_getSeqVariables(src_mesh, &numSeqVar, &numStepPerSeq, &seqVars);
    if (rc != FC_SUCCESS)
      return rc;
    for (i = 0; i < numSeqVar; i++) {
      FC_Sequence src_seq, dest_seq;
      // look for appropriate sequence on the destination dataset
      rc = fc_getSequenceFromSeqVariable(numStepPerSeq[i], seqVars[i],
                          &src_seq);
      if (rc != FC_SUCCESS)
     return rc;
      dest_seq = FC_NULL_SEQUENCE;
      // if we are in the same dataset, reuse the same sequence
      if (FC_HANDLE_EQUIV(dest_ds, src_meshSlot->ds))
     dest_seq = src_seq;
      else { // look for an appropriate sequence in dest_ds
     int dest_numSequence, src_numStep, dest_numStep;
     FC_Sequence *dest_sequences;
     char* src_name, *dest_name;
     FC_DataType src_dataType, dest_dataType;
     void* src_coords_p, *dest_coords_p;
     // collect src sequence info
     rc = fc_getSequenceName(src_seq, &src_name);
     if (rc != FC_SUCCESS)
       return rc;
     rc = fc_getSequenceInfo(src_seq, &src_numStep, &src_dataType);
     if (rc != FC_SUCCESS)
       return rc;
     rc = fc_getSequenceCoordsPtr(src_seq, &src_coords_p);
     if (rc != FC_SUCCESS)
       return rc;
     // compare to dest sequences
     rc = fc_getSequences(dest_ds, &dest_numSequence, &dest_sequences);
     if (rc != FC_SUCCESS)
       return rc;
     for (j = 0; j < dest_numSequence; j++) {
       rc = fc_getSequenceName(dest_sequences[j], &dest_name);
       if (rc != FC_SUCCESS)
         return rc;
       rc = fc_getSequenceInfo(dest_sequences[j], &dest_numStep,
                      &dest_dataType);
       if (rc != FC_SUCCESS)
         return rc;
       rc = fc_getSequenceCoordsPtr(dest_sequences[j], &dest_coords_p);
       if (rc != FC_SUCCESS)
         return rc;
       // compare (?checking actual coords values might be too stringent)
       if (!strcmp(dest_name, src_name) && dest_numStep == src_numStep &&
           dest_dataType == src_dataType &&
           !memcmp(dest_coords_p, src_coords_p,
                fc_sizeofDataType(src_dataType))) {
         free(dest_name);
         // passed all tests, this is the match
         dest_seq = dest_sequences[j];
         break;
       }
       free(dest_name);
     }
     free(dest_sequences);
     free(src_name);
      }
      // if failed to find one, just copy it
      if (FC_HANDLE_EQUIV(dest_seq, FC_NULL_SEQUENCE)) {
     rc = fc_copySequence(src_seq, dest_ds, NULL, &dest_seq);
     if (rc != FC_SUCCESS) {
       fc_printfErrorMessage("Failed to copy sequence needed for seqVar");
       return rc;
     }
      }
      // copy the sequence variables
      rc = fc_copySeqVariable(numStepPerSeq[i], seqVars[i], *new_mesh, dest_seq,
                     NULL, &new_seqVar);
      if (rc != FC_SUCCESS) {
     fc_printfErrorMessage("Failed to copy member sequence variable");
     return rc;
      }
      free(new_seqVar);
      free(seqVars[i]);
    }
    free(numStepPerSeq);
    free(seqVars);
  }
  if (doCopySeqSubset){
    // copy the sequence subsets
    rc = fc_getSeqSubsets(src_mesh, &numSeqSub, &numStepPerSeq, &seqSubs);
    if (rc != FC_SUCCESS)
      return rc;
    for (i = 0; i < numSeqSub; i++) {
      FC_Sequence src_seq, dest_seq;
      // look for appropriate sequence on the destination dataset
      rc = fc_getSequenceFromSeqSubset(numStepPerSeq[i], seqSubs[i],
                                       &src_seq);
      if (rc != FC_SUCCESS)
     return rc;
      dest_seq = FC_NULL_SEQUENCE;
      // if we are in the same dataset, reuse the same sequence
      if (FC_HANDLE_EQUIV(dest_ds, src_meshSlot->ds))
     dest_seq = src_seq;
      else { // look for an appropriate sequence in dest_ds
     int dest_numSequence, src_numStep, dest_numStep;
     FC_Sequence *dest_sequences;
     char* src_name, *dest_name;
     FC_DataType src_dataType, dest_dataType;
     void* src_coords_p, *dest_coords_p;
     // collect src sequence info
     rc = fc_getSequenceName(src_seq, &src_name);
     if (rc != FC_SUCCESS)
       return rc;
     rc = fc_getSequenceInfo(src_seq, &src_numStep, &src_dataType);
     if (rc != FC_SUCCESS)
       return rc;
     rc = fc_getSequenceCoordsPtr(src_seq, &src_coords_p);
     if (rc != FC_SUCCESS)
       return rc;
     // compare to dest sequences
     rc = fc_getSequences(dest_ds, &dest_numSequence, &dest_sequences);
     if (rc != FC_SUCCESS)
       return rc;
     for (j = 0; j < dest_numSequence; j++) {
       rc = fc_getSequenceName(dest_sequences[j], &dest_name);
       if (rc != FC_SUCCESS)
         return rc;
       rc = fc_getSequenceInfo(dest_sequences[j], &dest_numStep,
                      &dest_dataType);
       if (rc != FC_SUCCESS)
         return rc;
       rc = fc_getSequenceCoordsPtr(dest_sequences[j], &dest_coords_p);
       if (rc != FC_SUCCESS)
         return rc;
       // compare (?checking actual coords values might be too stringent)
       if (!strcmp(dest_name, src_name) && dest_numStep == src_numStep &&
           dest_dataType == src_dataType &&
           !memcmp(dest_coords_p, src_coords_p,
                fc_sizeofDataType(src_dataType))) {
         free(dest_name);
         // passed all tests, this is the match
         dest_seq = dest_sequences[j];
         break;
       }
       free(dest_name);
     }
     free(dest_sequences);
     free(src_name);
      }
      // if failed to find one, just copy it
      if (FC_HANDLE_EQUIV(dest_seq, FC_NULL_SEQUENCE)) {
     rc = fc_copySequence(src_seq, dest_ds, NULL, &dest_seq);
     if (rc != FC_SUCCESS) {
       fc_printfErrorMessage("Failed to copy sequence needed for seqSub");
       return rc;
     }
      }
      // copy the sequence subsets
      rc = fc_copySeqSubset(numStepPerSeq[i], seqSubs[i], *new_mesh, dest_seq,
                            NULL, &new_seqSub);
      if (rc != FC_SUCCESS) {
     fc_printfErrorMessage("Failed to copy member sequence sub");
     return rc;
      }
      free(new_seqSub);
      free(seqSubs[i]);
    }
    free(numStepPerSeq);
    free(seqSubs);
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_createMesh (FC_Dataset dataset, char * meshname, FC_Mesh * mesh)
Create a new mesh.
Description:
Create a new, in-memory, mesh.
Modifications:
Nancy Collins, Created.
Parameters:
dataset input - dataset handle to associate mesh with
meshname input - new mesh name
mesh output - mesh handle
Definition at line 119 of file mesh.c.
References _FC_GET_HANDLE, _fc_getDsSlot(), _fc_getNewMeshSlot(), _fc_setSlotHeaderName(), _FC_MeshSlot::ds, fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, FC_NULL_MESH, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_DsSlot::meshIDs, _FC_DsSlot::numMesh, and _FC_SlotHeader::slotID.
Referenced by _fc_loadExodusDataset(), _fc_loadLSDynaDataset(), _fc_makeMeshFromFiles(), fc_convertTreeToMesh(), fc_copyMesh(), fc_createBoundingBoxMesh(), fc_createSimpleHexMesh(), fc_createSphereMesh(), fc_createSubsetMesh(), fc_saveSkeleton(), main(), and setupDataset().
  {
  int *tempslotIDs;
  _FC_DsSlot* dsSlot;
  _FC_MeshSlot* meshSlot;
  // default returns
  if (mesh)
    *mesh = FC_NULL_MESH;
  // check input
  dsSlot = _fc_getDsSlot(dataset);
  if (dsSlot == NULL || !meshname || !mesh) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Creating new mesh '%s'", meshname);
  // get an open slot
  meshSlot = _fc_getNewMeshSlot();
  if (meshSlot == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  // table header information
  _FC_GET_HANDLE(*mesh, meshSlot);
  _fc_setSlotHeaderName(&(meshSlot->header), meshname);
  // set back and forth references
  meshSlot->ds = dataset;
  // update owning dataset with info about this new mesh
  tempslotIDs = realloc(dsSlot->meshIDs, sizeof(int) * (dsSlot->numMesh+1));
  if (tempslotIDs == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  dsSlot->meshIDs = tempslotIDs;
  dsSlot->meshIDs[dsSlot->numMesh] = meshSlot->header.slotID;
  dsSlot->numMesh++;
  return FC_SUCCESS;
}
FC_ReturnCode fc_createSimpleHexMesh (FC_Dataset dataset, char * newName, int N, int M, int P, double * lower_coords, double * upper_coords, FC_Mesh * new_mesh)
Create a simple hex mesh.
Description:
This function creates a hex mesh which is a regular parallelpiped (if all the sides are the same length, a cube). The number of elements in each dimension are given by N, M, & K. The coordinates are specified by giving the coordinates of the lower and upper corners of the mesh.
Modifications:
11/09/2005 WSD Created.
Parameters:
dataset Input - dataset handle to associate mesh with
newName Input - the name of the new mesh
N Input - number of elements in the x direction
M Input - number of elements in the y direction
P Input - number of elements in the z direction
lower_coords Input - the coordinates of lower corner.
upper_coords Input - the coordinates of upper corner.
new_mesh output - new mesh handle
Definition at line 1748 of file mesh.c.
References fc_createMesh(), fc_deleteMesh(), FC_ET_HEX, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isDatasetValid(), FC_MEMORY_ERROR, FC_NULL_MESH, fc_printfErrorMessage, fc_printfLogMessage, fc_setMeshCoordsPtr(), fc_setMeshElementConnsPtr(), and FC_SUCCESS.
Referenced by main().
  {
  FC_ReturnCode rc;
  int i, j, k;
  int numElemPerDim[3] = { N, M, P }, eindex, vindex;
  int numDim = 3, numVertPerElem = 8;
  int numVert, numElem;
  double side_lengths[3];
  int *conns;
  double* coords;
  // default output
  if (new_mesh)
    *new_mesh = FC_NULL_MESH;
  // check input
  if (!fc_isDatasetValid(dataset) || !newName || N < 1 || M < 1 || P < 1 ||
      !lower_coords || !upper_coords || !new_mesh) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  for (i = 0; i < numDim; i++) {
    if (lower_coords[i] >= upper_coords[i]) {
      fc_printfErrorMessage("Upper coords for dim%d must be greater than lower "
                            "coords", i);
      return FC_INPUT_ERROR;
    }
  }
  // log message
  fc_printfLogMessage("Creating simple hex mesh '%s'", newName);
  // Set up
  numVert = (M+1)*(N+1)*(P+1);
  numElem = M*N*P;
  conns = (int*)malloc(numElem*numVertPerElem*sizeof(int));
  coords = (double*)malloc(numVert*numDim*sizeof(double));
  if (!conns || !coords) {
    free(conns);
    free(coords);
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < numDim; i++)
    side_lengths[i] = (upper_coords[i] - lower_coords[i])/numElemPerDim[i];
  // Make coords
  for (k = 0; k < P+1; k++) {
    for (j = 0; j < M+1; j++) {
      for (i = 0; i < N+1; i++) {
        vindex = k*(N+1)*(M+1) + j*(N+1) + i;
        coords[vindex*numDim] =   i*side_lengths[0] + lower_coords[0];
        coords[vindex*numDim+1] = j*side_lengths[1] + lower_coords[1];
        coords[vindex*numDim+2] = k*side_lengths[2] + lower_coords[2];
      }
    }
  }
  // Make conns
  for (k = 0; k < P; k++) {
    for (j = 0; j < M; j++) {
      for (i = 0; i < N; i++) {
        eindex = k*N*M + j*N + i;
        vindex = k*(N+1)*(M+1) + j*(N+1) + i; // index of lowest vert
        conns[eindex*numVertPerElem]   = vindex;
        conns[eindex*numVertPerElem+1] = vindex + 1;
        vindex = k*(N+1)*(M+1) + (j+1)*(N+1) + i;
        conns[eindex*numVertPerElem+2] = vindex + 1;
        conns[eindex*numVertPerElem+3] = vindex;
        vindex = (k+1)*(N+1)*(M+1) + j*(N+1) + i;
        conns[eindex*numVertPerElem+4] = vindex;
        conns[eindex*numVertPerElem+5] = vindex + 1;
        vindex = (k+1)*(N+1)*(M+1) + (j+1)*(N+1) + i;
        conns[eindex*numVertPerElem+6] = vindex + 1;
        conns[eindex*numVertPerElem+7] = vindex;
      }
    }
  }
  // Make the mesh
  rc = fc_createMesh(dataset, newName, new_mesh);
  if (rc != FC_SUCCESS) {
    free(coords);
    free(conns);
    return rc;
  }
  rc = fc_setMeshCoordsPtr(*new_mesh, numDim, numVert, coords);
  if (rc != FC_SUCCESS) {
    free(conns);
    fc_deleteMesh(*new_mesh);
    return rc;
  }
  rc = fc_setMeshElementConnsPtr(*new_mesh, FC_ET_HEX, numElem, conns);
  if (rc != FC_SUCCESS) {
    fc_deleteMesh(*new_mesh);
    return rc;
  }
  // All done!
  return FC_SUCCESS;
}
FC_ReturnCode fc_createSphereMesh (FC_Dataset dataset, char * newName, FC_Coords center, double radius, int requestedNodes, FC_Mesh * new_mesh)
Create a simple sphere mesh.
Description:
This function creates a spehere mesh.
Note: While the user can request a particular number of nodes, this function will round the actual number of nodes to a value that matches numNodes = sqrt(numNodes-2)^2+2.
Modifications:
04/08/2008 CDU Created
Parameters:
dataset Input - Dataset handle to associate sphere with
newName Input - the name of the new mesh
center Input - xyz coordinate of the sphere's center
radius Input - radius of the sphere
requestedNodes Input - Requested number of mesh nodes (or 0 for default)
new_mesh Output - new mesh handle
Definition at line 1949 of file mesh.c.
References _fc_setSphereCoords(), fc_createMesh(), fc_deleteMesh(), FC_ET_TRI, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isDatasetValid(), fc_lteqd(), FC_MEMORY_ERROR, FC_NULL_MESH, fc_printfErrorMessage, fc_setMeshCoordsPtr(), fc_setMeshElementConnsPtr(), and FC_SUCCESS.
Referenced by fc_saveSkeleton().
 {
  const int numDim=3;
  const int def_numNodes=38; //6^2 + 2
  int i,j;
  int    *conns;
  double *coords;
  int numVerts;
  int place;
  int numPlane;
  int numElem, numVertPerElem;
  FC_ReturnCode rc;
  int a,b,c,d, offset;
  //Default output
  if(new_mesh)
    *new_mesh = FC_NULL_MESH;
  //Check input
  if(!fc_isDatasetValid(dataset) || !newName || !center || fc_lteqd(radius,0.0) || !new_mesh){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  //Set the requested nodes if user didn't give us anything
  if(requestedNodes<1)
    requestedNodes = def_numNodes;
  numPlane = sqrt(requestedNodes);
  numVerts = numPlane*numPlane + 2;
  //Allocate the coordinates
  coords = (double *) calloc( numVerts*numDim, sizeof(double));
  if(!coords){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  //Set the coordinates
  rc = _fc_setSphereCoords(numVerts, center, radius, coords);
  if(rc != FC_SUCCESS){
    free(coords);
    return rc;
  }
  //Add to the mesh
  rc = fc_createMesh(dataset, newName, new_mesh);
  if(rc != FC_SUCCESS){
    *new_mesh = FC_NULL_MESH;
    free(coords);
    return rc;
  }
  //Note: if successful, we don't control coords any more
  rc = fc_setMeshCoordsPtr(*new_mesh, numDim, numVerts, coords);
  if(rc != FC_SUCCESS){
    fc_deleteMesh(*new_mesh);
    *new_mesh = FC_NULL_MESH;
    free(coords);
    return rc;
  }
  //Setup connectivity
  numVertPerElem=3;
  numElem = ((2*numPlane)*(numPlane-1) + //2tri/side * all planes but top/bottom
          (2*numPlane));               //Top and bottom
  conns = (int *)calloc(numElem*numVertPerElem,sizeof(int));
  if(!conns){
    fc_deleteMesh(*new_mesh);
    *new_mesh = FC_NULL_MESH;
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  //Link up all the triangles (excluding top and bottom)
  place=0;
  for(i=1; i<numPlane; i++){   //Each plane
    for(j=0; j<numPlane; j++){ //each point in a plane
      a = (i*numPlane)     + j;
      b = ((i-1)*numPlane) + j;
      c = ((i-1)*numPlane) + (j+1)%numPlane;
      d = (i*numPlane)     + (j+1)%numPlane;
      //Top triangle
      conns[place++] = a;
      conns[place++] = b;
      conns[place++] = c;
      //bottom triangle
      conns[place++] = a;
      conns[place++] = c;
      conns[place++] = d;
      //printf("place now %d (max elem=%d) %d %d %d %d\n", place, numElem, a,b,c,d);
    }
  }
  //Connect the top or bottom elements
  for(i=0; i<2;i++){
    a      = numVerts-2+i; //Top or bottom node
    offset = (i==0) ? 0 : numVerts-2-numPlane;
    for(j=0;j<numPlane; j++){
      conns[place++] = a;
      conns[place++] = offset + j;
      conns[place++] = offset + (j+1)%numPlane;
    }
  }
  //Pass the connection into the mesh. Note: if ok, don't need to free conns
  rc = fc_setMeshElementConnsPtr(*new_mesh, FC_ET_TRI, numElem, conns);
  if(rc != FC_SUCCESS){
    fc_deleteMesh(*new_mesh);
    *new_mesh = FC_NULL_MESH;
    free(conns);
    return rc;
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_createSubsetMesh (FC_Subset subset, FC_Dataset dest_ds, int doStrict, int doCopyVar, int doCopySeqVar, int doCopySubset, int doCopySeqSubset, char * newName, FC_Mesh * new_mesh, FC_Variable * vertmap, FC_Variable * elemmap)
Create a new mesh which is the subset of another mesh.
Description:
This function extracts a selected subset of a mesh as elements. Point and element indices are renumbered to maintain the correct vertex and element relationships. This does mean the correspondence between vertices and elements extracted in the subset and the original dataset are now lost, but will be stored in the special variables FC_VERTEXMAP, FC_ELEMENTMAP on the new mesh which will store the id of the original mesh entities, if they handles passed in are not null.
There are flags to determine whether subsets, seq subsets, variables and sequence variables will be copied over or not. NOTE: if you set them all to 0, only the geom is copied, NOTE: If they are to be copied, then all subsets and seq subsets are copied even if they have no members in the new mesh (they'll just be empty subsets). The original subset is also copied. NOTE: If they are not to be copied, note that the sequences will also be lost. NOTE: If you dont copy them over now, you wont be able to later because the numbering will have changed. There may be functions added later to allows this (like what is being done with regionmesh in variable)
If the association type of the subset is of lesser dimensionality than FC_AT_ELEMENT, the 'doStrict' flag determines whether to keep new entities if not all of their child entities are in the old subset. 1 = be strict and only have the entity in the new subset if all of it's children are present in the old subset. 0 = be lenient and add all entities that have at least one child in the old subset (see also fc_changeMeshEntityType).
NOTE: An FC_NULL_DATASET handle can be returned with no error if there is no appropriate dataset to make. (E.g. if the marked lists are all 0, or you want a 0 level mesh but not enough vertices are marked to get whole elements.)
Todo:
internals could probably be made more efficient spacewise?
Modifications:
2003-NOV-20 W Koegler Replace all 6 of old subset routines with new multipurpose routine.
08/20/04 WSK Changed to used new topo routine for figuring out which elements to keep.
10/2/04 WSK fixing up recursive subsetting of member subsets variables & seq vars.
01/07/2008 ACG adding flag for not copying subsets, seq vars etc over.
03/07/2008 ACG adding seq subset copy
04/25/2008 ACG mapping vars
06/17/2008 ACG changing copy flag to per type (var, seqvar, subset etc) individual copy flag
Parameters:
subset input - subset
dest_ds input - dataset to put the new mesh on
doStrict input - flag for dropping incomplete entities
doCopyVar Input - 1 to copy over the var
doCopySeqVar Input - 1 to copy over the seqvar
doCopySubset Input - 1 to copy over the subsets
doCopySeqSubset Input - 1 to copy over the seqsubsets
newName Input - the name of the new mesh, a NULL value is a flag to use the name of the source mesh
new_mesh Output - new mesh handle
vertmap Output - handle to a variable on the new mesh with the vertex mapping
elemmap Output - handle to a variable on the new mesh with the elem mapping
Definition at line 845 of file mesh.c.
References _fc_getDsSlot(), _fc_getMeshSlot(), _fc_getSubSlot(), _FC_MeshSlot::coordVarID, _FC_MeshSlot::ds, fc_addIntArrayToSortedIntArray(), fc_addMemberToSubset(), FC_AT_EDGE, FC_AT_ELEMENT, FC_AT_FACE, FC_AT_VERTEX, FC_AT_WHOLE_MESH, fc_changeMeshEntityType(), fc_convertSortedIntArrayToIntArray(), fc_copyMesh(), fc_copySequence(), fc_createMesh(), fc_createSeqSubset(), fc_createSeqVariable(), fc_createSubset(), fc_createVariable(), FC_DT_INT, FC_ERROR, fc_getElementTypeNumEdge(), fc_getElementTypeNumFace(), fc_getElementTypeNumVertex(), fc_getMeshCoordsAsVariable(), fc_getMeshCoordsPtr(), fc_getMeshElementConnsPtr(), fc_getMeshElementToEdgeConnsPtr(), fc_getMeshElementToFaceConnsPtr(), fc_getMeshFromSubset(), fc_getMeshInfo(), fc_getMeshNumElement(), fc_getMeshNumEntity(), fc_getReturnCodeText(), fc_getSeqSubsets(), fc_getSequenceCoordsPtr(), fc_getSequenceFromSeqSubset(), fc_getSequenceFromSeqVariable(), fc_getSequenceInfo(), fc_getSequenceName(), fc_getSequences(), fc_getSeqVariables(), fc_getSubsetAssociationType(), fc_getSubsetInfo(), fc_getSubsetMembersAsArray(), fc_getSubsetName(), fc_getSubsets(), fc_getVariableDataPtr(), fc_getVariableInfo(), fc_getVariableName(), fc_getVariables(), FC_HANDLE_EQUIV, fc_initSortedIntArray(), FC_INPUT_ERROR, FC_MEMORY_ERROR, FC_MT_SCALAR, FC_NULL_MESH, FC_NULL_SEQUENCE, FC_NULL_VARIABLE, fc_printfErrorMessage, fc_printfLogMessage, fc_setMeshCoordsPtr(), fc_setMeshElementConnsPtr(), fc_setVariableDataPtr(), fc_sizeofDataType(), FC_SUCCESS, _FC_MeshSlot::header, _FC_SubSlot::mesh, _FC_SlotHeader::name, and var_name.
Referenced by main(), and processOneVar().
  {
  FC_ReturnCode rc;
  int i, j, k;
  // original mesh
  int numVert, numElem, dim, numVertPerElem, numEdgePerElem, numFacePerElem;
  int subset_numVert, subset_numElem;
  // index by old ID, get new ID (-1 = doesn't exist)
  int *vertLUNewToOld, *elemLUNewToOld, *vertLUOldToNew, *elemLUOldToNew;
  int *edgeLUOldToNew = NULL, *faceLUOldToNew = NULL;
  int *edgeLUNewToOld = NULL, *faceLUNewToOld = NULL;
  int wholeLUOldToNew[1] = { 0 }, wholeLUNewToOld[1] = { 0 };
  int *LUOldToNew, *LUNewToOld;
  int* src_conns, *new_conns;
  double* src_coords, *new_coords;
  int numSubset, numVariable, numSeqVar, numSeqSub, *numStepPerSeqVar, *numStepPerSeqSub;
  FC_Subset *subsets, new_subset, **seqSubs, *new_seqSub;
  FC_Variable *variables, new_variable, **seqVars, *new_seqVar;
  _FC_DsSlot* dest_dsSlot;
  _FC_MeshSlot* src_meshSlot;
  _FC_SubSlot* subSlot;
  FC_Mesh src_mesh;
  FC_ElementType elemType;
  FC_AssociationType assoc, subset_assoc;
  int numOrig, *origIDs;
  FC_SortedIntArray list;
  int usingEdge, usingFace;
  // default output
  if (new_mesh)
    *new_mesh = FC_NULL_MESH;
  if (elemmap)
    *elemmap = FC_NULL_VARIABLE;
  if (vertmap)
    *vertmap = FC_NULL_VARIABLE;
  // check input
  subSlot = _fc_getSubSlot(subset);
  dest_dsSlot = _fc_getDsSlot(dest_ds);
  if (subSlot == NULL || dest_dsSlot == NULL || new_mesh == NULL ||
      !(doCopyVar == 1  || doCopyVar == 0) ||
      !(doCopySeqVar == 1  || doCopySeqVar == 0) ||
      !(doCopySubset == 1  || doCopySubset == 0) ||
      !(doCopySeqSubset == 1  || doCopySeqSubset == 0)){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  src_meshSlot = _fc_getMeshSlot(subSlot->mesh);
  if (src_meshSlot == NULL) {
    fc_printfErrorMessage("Bad library state, subset o.k. but mesh bad, ??");
    return FC_ERROR;
  }
 // test for NULL name
  if (newName == NULL)
    newName = src_meshSlot->header.name;
  // log message
  fc_printfLogMessage("Creating new mesh '%s' from a subset '%s' of mesh "
                      "'%s'", newName, "subName", src_meshSlot->header.name);
  // get subset & mesh info
  rc = fc_getSubsetInfo(subset, &numOrig, NULL, &assoc);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get subset info");
    return rc;
  }
  rc = fc_getMeshFromSubset(subset, &src_mesh);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get subset's parent mesh");
    return rc;
  }
  // get some mesh info
  rc = fc_getMeshInfo(src_mesh, NULL, &dim, &numVert, &numElem, &elemType);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get info for mesh '%s'",
                          src_meshSlot->header.name);
    return rc;
  }
  // trivial case: assoc = FC_AT_WHOLE_MESH
  if (assoc == FC_AT_WHOLE_MESH) {
    if (numOrig > 0) {
      rc = fc_copyMesh(src_mesh, dest_ds, newName, doCopyVar, doCopySeqVar,
                 doCopySubset, doCopySeqSubset, new_mesh);
      if (rc != FC_SUCCESS) {
     fc_printfErrorMessage("Failed to copy mesh");
     return rc;
      }
      if (elemmap != NULL){
     int* allelems = (int*)malloc(numElem*sizeof(int));
     if (!allelems){
       return FC_MEMORY_ERROR;
     }
     for (i = 0; i < numElem; i++){
       allelems[i] = i;
     }
     rc = fc_createVariable(*new_mesh,"FC_ELEMENTMAP",elemmap);
     if (rc != FC_SUCCESS){
       fc_printfErrorMessage("Cannot create elemmap var");
       return rc;
     }
     rc = fc_setVariableDataPtr(*elemmap, numElem,1,FC_AT_ELEMENT, FC_MT_SCALAR,
                       FC_DT_INT, allelems);
     if (rc != FC_SUCCESS){
       fc_printfErrorMessage("Cannot set elemmap var data");
       return rc;
     }
      }
      if (vertmap != NULL){
     int* allverts = (int*)malloc(numVert*sizeof(int));
     if (!allverts){
       return FC_MEMORY_ERROR;
     }
     for (i = 0; i < numVert; i++){
       allverts[i] = i;
     }
     rc = fc_createVariable(*new_mesh,"FC_VERTEXMAP",vertmap);
     if (rc != FC_SUCCESS){
       fc_printfErrorMessage("Cannot create vertmap var");
       return rc;
     }
     rc = fc_setVariableDataPtr(*vertmap, numVert,1,FC_AT_VERTEX, FC_MT_SCALAR,
                       FC_DT_INT, allverts);
     if (rc != FC_SUCCESS){
       fc_printfErrorMessage("Cannot set vertmap var data");
       return rc;
     }
      }
    }
    return FC_SUCCESS;
  }
  // get the elements that correspond with the subset
  //so the change is actually based on the corresponding elements, after
  //being subject to the doStrict constraint
  rc = fc_getSubsetMembersAsArray(subset, &numOrig, &origIDs);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get subset members");
    return rc;
  }
  rc = fc_changeMeshEntityType(src_mesh, assoc, numOrig, origIDs,
                               FC_AT_ELEMENT, doStrict, &subset_numElem,
                               &elemLUNewToOld);
  free(origIDs);
  if (rc != FC_SUCCESS) {
    return rc;
  }
  // more trivial cases: no elements or all elements
  if (subset_numElem == 0) {
    return FC_SUCCESS;
  }
  else if (subset_numElem == numElem) {
    rc = fc_copyMesh(src_mesh, dest_ds, newName, doCopyVar, doCopySeqVar,
               doCopySubset, doCopySeqSubset, new_mesh);
    if (rc != FC_SUCCESS) {
      fc_printfErrorMessage("Failed to copy mesh");
      return rc;
    }
    free(elemLUNewToOld);
    if (elemmap != NULL){
      int *allelems = (int*)malloc(numElem*sizeof(int));
      if (!allelems){
     return FC_MEMORY_ERROR;
      }
      for (i = 0; i < numElem; i++){
     allelems[i] = i;
      }
      rc = fc_createVariable(*new_mesh,"FC_ELEMENTMAP",elemmap);
      if (rc != FC_SUCCESS){
     fc_printfErrorMessage("Cannot create elemmap var");
     return rc;
      }
      rc = fc_setVariableDataPtr(*elemmap, numElem,1,FC_AT_ELEMENT, FC_MT_SCALAR,
                     FC_DT_INT, allelems);
      if (rc != FC_SUCCESS){
     fc_printfErrorMessage("Cannot set elemmap var data");
     return rc;
      }
    }
    if (vertmap != NULL){
      int* allverts = (int*)malloc(numVert*sizeof(int));
      if (!allverts){
     return FC_MEMORY_ERROR;
      }
      for (i = 0; i < numVert; i++){
     allverts[i] = i;
      }
      rc = fc_createVariable(*new_mesh,"FC_VERTEXMAP",vertmap);
      if (rc != FC_SUCCESS){
     fc_printfErrorMessage("Cannot create vertmap var");
     return rc;
      }
      rc = fc_setVariableDataPtr(*vertmap, numVert,1,FC_AT_VERTEX, FC_MT_SCALAR,
                     FC_DT_INT, allverts);
      if (rc != FC_SUCCESS){
     fc_printfErrorMessage("Cannot set vertmap var data");
     return rc;
      }
    }
    return FC_SUCCESS;
  }
  // more mesh info
  numVertPerElem = fc_getElementTypeNumVertex(elemType);
  numEdgePerElem = fc_getElementTypeNumEdge(elemType);
  numFacePerElem = fc_getElementTypeNumFace(elemType);
  rc = fc_getMeshElementConnsPtr(src_mesh, &src_conns);
  if (rc != FC_SUCCESS)
    return rc;
  // make element lookup tables
  elemLUOldToNew = malloc(numElem*sizeof(int));
  if (elemLUOldToNew == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < numElem; i++)
    elemLUOldToNew[i] = -1;
  for (i = 0; i < subset_numElem; i++)
    elemLUOldToNew[elemLUNewToOld[i]] = i;
 // Figure out which vertices are going to be kept & make lookup tables
  fc_initSortedIntArray(&list);
  for (i = 0; i < subset_numElem; i++) {
    int ret = fc_addIntArrayToSortedIntArray(&list, numVertPerElem,
                              &src_conns[elemLUNewToOld[i]*numVertPerElem], 0);
    if (ret < 0) {
      fc_printfErrorMessage("Failed to add ids to sia");
      return ret;
    }
  }
  rc = fc_convertSortedIntArrayToIntArray(&list, &subset_numVert, &vertLUNewToOld);
  if (rc != FC_SUCCESS)
    return rc;
  vertLUOldToNew = malloc(numVert*sizeof(int));
  if (vertLUOldToNew == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < numVert; i++)
    vertLUOldToNew[i] = -1;
  for (i = 0; i < subset_numVert; i++)
    vertLUOldToNew[vertLUNewToOld[i]] = i;
  // make element->vertex conns
  new_conns = malloc(subset_numElem * numVertPerElem * sizeof(int));
  if (new_conns == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < subset_numElem; i++)
    for (j = 0; j < numVertPerElem; j++)
      new_conns[i*numVertPerElem + j] =
        vertLUOldToNew[src_conns[elemLUNewToOld[i]*numVertPerElem+j]];
  // determine new coords
  new_coords = malloc(subset_numVert * dim * sizeof(double));
  if (new_coords == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  rc = fc_getMeshCoordsPtr(src_mesh, &src_coords);
  if (rc != FC_SUCCESS)
    return rc;
  for (i = 0; i < subset_numVert; i++)
    memcpy(&(new_coords[i*dim]), &(src_coords[vertLUNewToOld[i]*dim]),
           dim*sizeof(double));
  // create new mesh
  rc = fc_createMesh(dest_ds, newName, new_mesh);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_setMeshCoordsPtr(*new_mesh, dim, subset_numVert, new_coords);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_setMeshElementConnsPtr(*new_mesh, elemType, subset_numElem,
                                 new_conns);
  if (rc != FC_SUCCESS)
    return rc;
  if (elemmap != NULL){
    rc = fc_createVariable(*new_mesh,"FC_ELEMENTMAP",elemmap);
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("Cannot create elemmap var");
      return rc;
    }
    rc = fc_setVariableDataPtr(*elemmap, subset_numElem,1,FC_AT_ELEMENT, FC_MT_SCALAR,
                      FC_DT_INT, (void*)elemLUNewToOld);
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("Cannot set elemmap var data");
      return rc;
    }
  }
  if (vertmap != NULL){
    rc = fc_createVariable(*new_mesh,"FC_VERTEXMAP",vertmap);
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("Cannot create vertmap var");
      return rc;
    }
    rc = fc_setVariableDataPtr(*vertmap, subset_numVert,1,FC_AT_VERTEX, FC_MT_SCALAR,
                      FC_DT_INT, (void*)vertLUNewToOld);
    if (rc != FC_SUCCESS){
      fc_printfErrorMessage("Cannot set vertmap var data");
      return rc;
    }
  }
  if (doCopyVar == 0 && doCopySeqVar == 0 && doCopySubset == 0 && doCopySeqSubset == 0){
    //free stuff and exit
    free(vertLUOldToNew);
    free(edgeLUOldToNew);
    free(faceLUOldToNew);
    free(elemLUOldToNew);
    free(edgeLUNewToOld);
    free(faceLUNewToOld);
    if (elemmap == NULL) free(elemLUNewToOld);
    if (vertmap == NULL) free(vertLUNewToOld);
    return FC_SUCCESS;
  }
  // Get subsets & variables for use now & later
  rc = fc_getSubsets(src_mesh, &numSubset, &subsets);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getSeqSubsets(src_mesh, &numSeqSub, &numStepPerSeqSub, &seqSubs);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getVariables(src_mesh, &numVariable, &variables);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getSeqVariables(src_mesh, &numSeqVar, &numStepPerSeqVar, &seqVars);
  if (rc != FC_SUCCESS)
    return rc;
  // Build edge & face lu tables only if there are edge or face
  // subsets or variables
  usingEdge = 0;
  usingFace = 0;
  if (doCopySubset){
    for (i = 0; i < numSubset; i++) {
      fc_getSubsetInfo(subsets[i], NULL, NULL, &assoc);
      if (assoc == FC_AT_EDGE)
     usingEdge = 1;
      else if (assoc == FC_AT_FACE)
     usingFace = 1;
    }
  }
  if (doCopySeqSubset){
    for (i = 0; i < numSeqSub; i++) {
      fc_getSubsetInfo(seqSubs[i][0], NULL, NULL, &assoc);
      if (assoc == FC_AT_EDGE)
     usingEdge = 1;
      else if (assoc == FC_AT_FACE)
     usingFace = 1;
    }
  }
  if (doCopyVar){
    for (i = 0; i < numVariable; i++) {
      fc_getVariableInfo(variables[i], NULL, NULL, &assoc, NULL, NULL);
      if (assoc == FC_AT_EDGE)
     usingEdge = 1;
      else if (assoc == FC_AT_FACE)
     usingFace = 1;
    }
  }
  if (doCopySeqVar){
    for (i = 0; i < numSeqVar; i++) {
      fc_getVariableInfo(seqVars[i][0], NULL, NULL, &assoc, NULL, NULL);
      if (assoc == FC_AT_EDGE)
     usingEdge = 1;
      else if (assoc == FC_AT_FACE)
     usingFace = 1;
    }
  }
  if (usingEdge) {
    int numEdge, new_numElement, new_numEdge;
    int *src_elemToEdgeConns, *new_elemToEdgeConns;
    // initialize old to new lookup tables
    fc_getMeshNumEntity(src_mesh, FC_AT_EDGE, &numEdge);
    if (numEdge > 0) {
      edgeLUOldToNew = malloc(numEdge*sizeof(int));
      if (edgeLUOldToNew == NULL) {
        fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
        return FC_MEMORY_ERROR;
      }
      for (i = 0; i < numEdge; i++)
        edgeLUOldToNew[i] = -1;
    }
    // create new to old lu (& force building of edges & faces on new mesh)
    fc_getMeshNumEntity(*new_mesh, FC_AT_EDGE, &new_numEdge);
    if (new_numEdge > 0) {
      edgeLUNewToOld = malloc(new_numEdge*sizeof(int));
       if (edgeLUOldToNew == NULL) {
        fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
        return FC_MEMORY_ERROR;
      }
    }
    // create lookups
    fc_getMeshNumElement(*new_mesh, &new_numElement);
    rc = fc_getMeshElementToEdgeConnsPtr(src_mesh, &src_elemToEdgeConns);
    if (rc != FC_SUCCESS)
      return rc;
    rc = fc_getMeshElementToEdgeConnsPtr(*new_mesh, &new_elemToEdgeConns);
    if (rc != FC_SUCCESS)
      return rc;
    for (i = 0; i < new_numElement; i++) {
      int* new_edgeIDs = &new_elemToEdgeConns[i*numEdgePerElem];
      int* old_edgeIDs = &src_elemToEdgeConns[elemLUNewToOld[i]*numEdgePerElem];
      for (j = 0; j < numEdgePerElem; j++) {
        edgeLUNewToOld[new_edgeIDs[j]] = old_edgeIDs[j];
        edgeLUOldToNew[old_edgeIDs[j]] = new_edgeIDs[j];
      }
    }
  }
  if (usingFace) {
    int numFace, new_numElement, new_numFace;
    int *src_elemToFaceConns, *new_elemToFaceConns;
    // initialize old to new lookup tables
    fc_getMeshNumEntity(src_mesh, FC_AT_FACE, &numFace);
    if (numFace > 0) {
      faceLUOldToNew = malloc(numFace*sizeof(int));
      if (faceLUOldToNew == NULL) {
        fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
        return FC_MEMORY_ERROR;
      }
      for (i = 0; i < numFace; i++)
        faceLUOldToNew[i] = -1;
    }
    // create new to old lu (& force building of edges & faces on new mesh)
    fc_getMeshNumEntity(*new_mesh, FC_AT_FACE, &new_numFace);
    if (new_numFace > 0) {
      faceLUNewToOld = malloc(new_numFace*sizeof(int));
       if (faceLUOldToNew == NULL) {
        fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
        return FC_MEMORY_ERROR;
      }
    }
    // create lookups
    fc_getMeshNumElement(*new_mesh, &new_numElement);
    rc = fc_getMeshElementToFaceConnsPtr(src_mesh, &src_elemToFaceConns);
    if (rc != FC_SUCCESS)
      return rc;
    rc = fc_getMeshElementToFaceConnsPtr(*new_mesh, &new_elemToFaceConns);
    if (rc != FC_SUCCESS)
      return rc;
    for (i = 0; i < new_numElement; i++) {
      int* new_faceIDs = &new_elemToFaceConns[i*numFacePerElem];
      int* old_faceIDs = &src_elemToFaceConns[elemLUNewToOld[i]*numFacePerElem];
      for (j = 0; j < numFacePerElem; j++) {
        faceLUNewToOld[new_faceIDs[j]] = old_faceIDs[j];
        faceLUOldToNew[old_faceIDs[j]] = new_faceIDs[j];
      }
    }
  }
  // copy stuff -- a lot like in fc_copyMesh
  // copy subsets
  if (doCopySubset){
    for (i = 0; i < numSubset; i++) {
      int numMember, *memberIDs;
      char* subset_name;
      // create the new subset
      rc = fc_getSubsetAssociationType(subsets[i], &subset_assoc);
      if (rc != FC_SUCCESS)
     return rc;
      rc = fc_getSubsetName(subsets[i], &subset_name);
      if (rc != FC_SUCCESS)
     return rc;
      rc = fc_createSubset(*new_mesh, subset_name, subset_assoc, &new_subset);
      free(subset_name);
      if (rc != FC_SUCCESS)
     return rc;
      // Add the members that are in the new subset (i.e. have a new ID)
      switch (subset_assoc) {
      case FC_AT_VERTEX:   LUOldToNew = vertLUOldToNew;   break;
      case FC_AT_EDGE:     LUOldToNew = edgeLUOldToNew;   break;
      case FC_AT_FACE:     LUOldToNew = faceLUOldToNew;   break;
     case FC_AT_ELEMENT:  LUOldToNew = elemLUOldToNew;   break;
     case FC_AT_WHOLE_MESH:    LUOldToNew = wholeLUOldToNew;  break;
      default:
     fc_printfErrorMessage("Should never reach this point!");
     return rc;
      }
      rc = fc_getSubsetMembersAsArray(subsets[i], &numMember, &memberIDs);
      if (rc != FC_SUCCESS)
     return rc;
      for (j = 0; j < numMember; j++) {
     if (LUOldToNew[memberIDs[j]] > -1) {
       rc = fc_addMemberToSubset(new_subset, LUOldToNew[memberIDs[j]]);
       if (rc != FC_SUCCESS)
         return rc;
     }
      }
      free(memberIDs);
    }
    free(subsets);
  } else {
    free(subsets);
  }
  // copy the basic variables
  if (doCopyVar){
    for (i = 0; i < numVariable; i++) {
      // do something different for the mesh 'coords as variable'
      if (variables[i].slotID == src_meshSlot->coordVarID) {
     rc = fc_getMeshCoordsAsVariable(*new_mesh, &new_variable);
     if (rc != FC_SUCCESS) {
       fc_printfErrorMessage("Failed to create copy of coords variable");
       return rc;
     }
      }
      else { // normal path for variables
     int numDataPoint, numComp, new_numDataPoint, size;
     char* var_name;
     FC_AssociationType var_assoc;
     FC_MathType mathtype;
     FC_DataType datatype;
     void* src_data, *new_data;
     // make the variable
     rc = fc_getVariableName(variables[i], &var_name);
     if (rc != FC_SUCCESS)
       return rc;
     rc = fc_createVariable(*new_mesh, var_name, &new_variable);
     free(var_name);
     if (rc != FC_SUCCESS)
       return rc;
     // get the original data
     rc = fc_getVariableInfo(variables[i], &numDataPoint, &numComp,
                    &var_assoc, &mathtype, &datatype);
     if (rc != FC_SUCCESS)
       return rc;
     fc_getVariableDataPtr(variables[i], &src_data);
     if (rc != FC_SUCCESS)
       return rc;
     // create subset of data
     rc = fc_getMeshNumEntity(*new_mesh, var_assoc, &new_numDataPoint);
     if (rc != FC_SUCCESS)
       return rc;
     size = fc_sizeofDataType(datatype)*numComp;
     new_data = malloc(new_numDataPoint*size);
     if (new_data == NULL) {
       fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
       return FC_MEMORY_ERROR;
     }
     switch (var_assoc) {
     case FC_AT_VERTEX:   LUNewToOld = vertLUNewToOld;   break;
     case FC_AT_EDGE:     LUNewToOld = edgeLUNewToOld;   break;
     case FC_AT_FACE:     LUNewToOld = faceLUNewToOld;   break;
     case FC_AT_ELEMENT:  LUNewToOld = elemLUNewToOld;   break;
     case FC_AT_WHOLE_MESH:    LUNewToOld = wholeLUNewToOld;  break;
     default:
       fc_printfErrorMessage("Should never reach this point!");
       return rc;
     }
     for (j = 0; j < new_numDataPoint; j++)
       memcpy((char*)new_data + j*size,
           (char*)src_data + LUNewToOld[j]*size, size);
     // set the data
     rc = fc_setVariableDataPtr(new_variable, new_numDataPoint, numComp,
                       var_assoc, mathtype, datatype, new_data);
     if (rc != FC_SUCCESS)
       return rc;
      }
    }
    free(variables);
  } else {
    free(variables);
  }
  if (doCopySeqVar){
    // copy the sequence vars
    for (i = 0; i < numSeqVar; i++) {
      int numStep;
      FC_Sequence src_seq, dest_seq;
      char* var_name;
      // look for appropriate sequence on the destination dataset
      rc = fc_getSequenceFromSeqVariable(numStepPerSeqVar[i], seqVars[i],
                          &src_seq);
      if (rc != FC_SUCCESS)
     return rc;
      dest_seq = FC_NULL_SEQUENCE;
      // if we are in the same dataset, reuse the same sequence
      if (FC_HANDLE_EQUIV(dest_ds, src_meshSlot->ds))
     dest_seq = src_seq;
      else { // look for an appropriate sequence in dest_ds
     int dest_numSequence, src_numStep, dest_numStep;
     FC_Sequence *dest_sequences;
     char* src_name, *dest_name;
     FC_DataType src_dataType, dest_dataType;
     void* src_coords_p, *dest_coords_p;
     // collect src sequence info
     rc = fc_getSequenceName(src_seq, &src_name);
     if (rc != FC_SUCCESS)
       return rc;
     rc = fc_getSequenceInfo(src_seq, &src_numStep, &src_dataType);
     if (rc != FC_SUCCESS)
       return rc;
     rc = fc_getSequenceCoordsPtr(src_seq, &src_coords_p);
     if (rc != FC_SUCCESS)
       return rc;
     // compare to dest sequences
     rc = fc_getSequences(dest_ds, &dest_numSequence, &dest_sequences);
     if (rc != FC_SUCCESS)
       return rc;
     for (j = 0; j < dest_numSequence; j++) {
       rc = fc_getSequenceName(dest_sequences[j], &dest_name);
       if (rc != FC_SUCCESS)
         return rc;
       rc = fc_getSequenceInfo(dest_sequences[j], &dest_numStep,
                      &dest_dataType);
       if (rc != FC_SUCCESS)
         return rc;
       rc = fc_getSequenceCoordsPtr(dest_sequences[j], &dest_coords_p);
       if (rc != FC_SUCCESS)
         return rc;
       // compare (?checking actual coords values might be too stringent)
       if (!strcmp(dest_name, src_name) && dest_numStep == src_numStep &&
           dest_dataType == src_dataType &&
           !memcmp(dest_coords_p, src_coords_p,
                fc_sizeofDataType(src_dataType))) {
         free(dest_name);
         // passed all tests, this is the match
         dest_seq = dest_sequences[j];
         break;
       }
       free(dest_name);
     }
     free(dest_sequences);
     free(src_name);
      }
      // if failed to find one, just copy it
      if (FC_HANDLE_EQUIV(dest_seq, FC_NULL_SEQUENCE)) {
     rc = fc_copySequence(src_seq, dest_ds, NULL, &dest_seq);
     if (rc != FC_SUCCESS) {
       fc_printfErrorMessage("Failed to copy sequence needed for seqVar");
       return rc;
     }
      }
      // make the seq variable
      rc = fc_getVariableName(seqVars[i][0], &var_name);
      if (rc != FC_SUCCESS)
     return rc;
      rc = fc_createSeqVariable(*new_mesh, dest_seq, var_name, &numStep,
                    &new_seqVar);
      free(var_name);
      if (rc != FC_SUCCESS)
     return rc;
      // set data on steps
      for (j = 0; j < numStepPerSeqVar[i]; j++) {
     int numDataPoint, numComp, new_numDataPoint, size;
     FC_AssociationType var_assoc;
     FC_MathType mathtype;
     FC_DataType datatype;
     void* src_data, *new_data;
     // get the original data
     rc = fc_getVariableInfo(seqVars[i][j], &numDataPoint, &numComp,
                    &var_assoc, &mathtype, &datatype);
     if (rc != FC_SUCCESS)
       return rc;
     fc_getVariableDataPtr(seqVars[i][j], &src_data);
     if (rc != FC_SUCCESS)
       return rc;
     // create subset of data
     rc = fc_getMeshNumEntity(*new_mesh, var_assoc, &new_numDataPoint);
     if (rc != FC_SUCCESS)
       return rc;
     size = fc_sizeofDataType(datatype)*numComp;
     new_data = malloc(new_numDataPoint*size);
     if (new_data == NULL) {
       fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
       return FC_MEMORY_ERROR;
     }
     switch (var_assoc) {
     case FC_AT_VERTEX:   LUNewToOld = vertLUNewToOld;   break;
     case FC_AT_EDGE:     LUNewToOld = edgeLUNewToOld;   break;
     case FC_AT_FACE:     LUNewToOld = faceLUNewToOld;   break;
     case FC_AT_ELEMENT:  LUNewToOld = elemLUNewToOld;   break;
     case FC_AT_WHOLE_MESH:    LUNewToOld = wholeLUNewToOld;  break;
     default:
       fc_printfErrorMessage("Should never reach this point!");
       return rc;
     }
     for (k = 0; k < new_numDataPoint; k++)
       memcpy((char*)new_data + k*size,
           (char*)src_data + LUNewToOld[k]*size, size);
     // set the data
     rc = fc_setVariableDataPtr(new_seqVar[j], new_numDataPoint, numComp,
                       var_assoc, mathtype, datatype, new_data);
     if (rc != FC_SUCCESS)
       return rc;
      }
      free(new_seqVar);
      free(seqVars[i]);
    }
    free(numStepPerSeqVar);
    free(seqVars);
  } else {
    for(i = 0; i < numSeqVar; i++)
      free(seqVars[i]);
    free(numStepPerSeqVar);
    free(seqVars);
  }
  // copy the sequence subsets
  if (doCopySeqSubset){
    for (i = 0; i < numSeqSub; i++) {
      int numStep;
      FC_Sequence src_seq, dest_seq;
      char* sub_name;
      // look for appropriate sequence on the destination dataset
      rc = fc_getSequenceFromSeqSubset(numStepPerSeqSub[i], seqSubs[i],
                                       &src_seq);
      if (rc != FC_SUCCESS)
     return rc;
      dest_seq = FC_NULL_SEQUENCE;
      // if we are in the same dataset, reuse the same sequence
      if (FC_HANDLE_EQUIV(dest_ds, src_meshSlot->ds))
     dest_seq = src_seq;
      else { // look for an appropriate sequence in dest_ds
     int dest_numSequence, src_numStep, dest_numStep;
     FC_Sequence *dest_sequences;
     char* src_name, *dest_name;
     FC_DataType src_dataType, dest_dataType;
     void* src_coords_p, *dest_coords_p;
     // collect src sequence info
     rc = fc_getSequenceName(src_seq, &src_name);
     if (rc != FC_SUCCESS)
       return rc;
     rc = fc_getSequenceInfo(src_seq, &src_numStep, &src_dataType);
     if (rc != FC_SUCCESS)
       return rc;
     rc = fc_getSequenceCoordsPtr(src_seq, &src_coords_p);
     if (rc != FC_SUCCESS)
       return rc;
     // compare to dest sequences
     rc = fc_getSequences(dest_ds, &dest_numSequence, &dest_sequences);
     if (rc != FC_SUCCESS)
       return rc;
     for (j = 0; j < dest_numSequence; j++) {
       rc = fc_getSequenceName(dest_sequences[j], &dest_name);
       if (rc != FC_SUCCESS)
         return rc;
       rc = fc_getSequenceInfo(dest_sequences[j], &dest_numStep,
                      &dest_dataType);
       if (rc != FC_SUCCESS)
         return rc;
       rc = fc_getSequenceCoordsPtr(dest_sequences[j], &dest_coords_p);
       if (rc != FC_SUCCESS)
         return rc;
       // compare (?checking actual coords values might be too stringent)
       if (!strcmp(dest_name, src_name) && dest_numStep == src_numStep &&
           dest_dataType == src_dataType &&
           !memcmp(dest_coords_p, src_coords_p,
                fc_sizeofDataType(src_dataType))) {
         free(dest_name);
         // passed all tests, this is the match
         dest_seq = dest_sequences[j];
         break;
       }
       free(dest_name);
     }
     free(dest_sequences);
     free(src_name);
      }
      // if failed to find one, just copy it
      if (FC_HANDLE_EQUIV(dest_seq, FC_NULL_SEQUENCE)) {
     rc = fc_copySequence(src_seq, dest_ds, NULL, &dest_seq);
     if (rc != FC_SUCCESS) {
       fc_printfErrorMessage("Failed to copy sequence needed for seqVar");
       return rc;
     }
      }
      // make the seq sub
      rc = fc_getSubsetName(seqSubs[i][0], &sub_name);
      if (rc != FC_SUCCESS)
     return rc;
      rc = fc_getSubsetAssociationType(seqSubs[i][0], &subset_assoc);
      if (rc != FC_SUCCESS)
     return rc;
      rc = fc_createSeqSubset(*new_mesh, dest_seq, sub_name, subset_assoc, &numStep,
                              &new_seqSub);
      free(sub_name);
      if (rc != FC_SUCCESS)
     return rc;
      // set data on steps
      for (j = 0; j < numStepPerSeqSub[i]; j++) {
     int numMember, *memberIDs;
     // get the original data
     // Add the members that are in the new subset (i.e. have a new ID)
     switch (subset_assoc) {
     case FC_AT_VERTEX:   LUOldToNew = vertLUOldToNew;   break;
     case FC_AT_EDGE:     LUOldToNew = edgeLUOldToNew;   break;
     case FC_AT_FACE:     LUOldToNew = faceLUOldToNew;   break;
     case FC_AT_ELEMENT:  LUOldToNew = elemLUOldToNew;   break;
     case FC_AT_WHOLE_MESH:    LUOldToNew = wholeLUOldToNew;  break;
     default:
       fc_printfErrorMessage("Should never reach this point!");
       return rc;
     }
     rc = fc_getSubsetMembersAsArray(seqSubs[i][j], &numMember, &memberIDs);
     if (rc != FC_SUCCESS)
       return rc;
     for (k = 0; k < numMember; k++) {
       if (LUOldToNew[memberIDs[k]] > -1) {
         rc = fc_addMemberToSubset(new_seqSub[j], LUOldToNew[memberIDs[k]]);
         if (rc != FC_SUCCESS)
           return rc;
       }
     }
     if (memberIDs) free(memberIDs); //could have been empty subset
      }
      free(new_seqSub);
      free(seqSubs[i]);
    }
    free(numStepPerSeqSub);
    free(seqSubs);
  } else {
    for (i = 0; i < numSeqSub; i++)
      free(seqSubs[i]);
    free(numStepPerSeqSub);
    free(seqSubs);
  }
  // cleanup
  if (vertLUOldToNew) free(vertLUOldToNew);
  if (edgeLUOldToNew) free(edgeLUOldToNew);
  if (faceLUOldToNew) free(faceLUOldToNew);
  if (elemLUOldToNew) free(elemLUOldToNew);
  if (edgeLUNewToOld) free(edgeLUNewToOld);
  if (faceLUNewToOld) free(faceLUNewToOld);
  if (elemmap == NULL) free(elemLUNewToOld);
  if (vertmap == NULL) free(vertLUNewToOld);
  return FC_SUCCESS;
}
FC_ReturnCode fc_deleteMesh (FC_Mesh mesh)
Delete a mesh.
Description:
Call when this mesh is no longer needed. This automatically deletes all of the mesh's subsets and variables.
Modifications:
Nancy Collins, Created.
12/01/03 WSK Changed so it removes an uncommitted mesh form the owning dataset's meshID list.
12/03/03 RM, added more input checking, if mesh is FC_NULL_MESH, then do nothing and return success (issue warning if fc_getLibraryVerbosity()).
9/9/04 WSK changed name to delete. Changed behavior so that delete always deletes no matter whether on disk or not.
03/04/08 ACG added deleting seq subsets
Parameters:
mesh input - mesh handle
Definition at line 2626 of file mesh.c.
References _fc_deleteMeshSlot(), _fc_getDsSlot(), _fc_getMeshSlot(), _FC_MeshSlot::ds, fc_deleteSeqSubset(), fc_deleteSeqVariable(), fc_deleteSubset(), fc_deleteVariable(), fc_getReturnCodeText(), fc_getSeqSubsets(), fc_getSeqVariables(), fc_getSubsets(), fc_getVariables(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, FC_NULL_MESH, fc_printfErrorMessage, fc_printfLogMessage, fc_printfWarningMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_DsSlot::meshIDs, _FC_SlotHeader::name, _FC_DsSlot::numMesh, and _FC_SlotHeader::slotID.
Referenced by fc_createSimpleHexMesh(), fc_createSphereMesh(), fc_deleteDataset(), main(), and processOneVar().
  {
  FC_ReturnCode rc;
  int i, j;
  _FC_MeshSlot* meshSlot;
  _FC_DsSlot* dsSlot;
  int numSubset, numVar, numSeqVar, *numStepPerVar, numSeqSub, *numStepPerSub;
  FC_Subset *subsets, **seqSubsets;
  FC_Variable *variables, **seqVariables;
  // special case: deleting a null handle is not an error
  if ( FC_HANDLE_EQUIV(mesh, FC_NULL_MESH)) {
    fc_printfWarningMessage("Deleting FC_NULL_MESH");
    return FC_SUCCESS;
  }
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Deleting mesh '%s'", meshSlot->header.name);
  // delete member subsets
  rc = fc_getSubsets(mesh, &numSubset, &subsets);
  if (rc != FC_SUCCESS)
    return rc;
  for (i = 0; i < numSubset; i++) {
    rc = fc_deleteSubset(subsets[i]);
    if (rc != FC_SUCCESS)
      return rc;
  }
  free(subsets);
  // delete member seq subs
  rc = fc_getSeqSubsets(mesh, &numSeqSub, &numStepPerSub, &seqSubsets);
  if (rc != FC_SUCCESS)
    return rc;
  for (i = 0; i < numSeqSub; i++) {
    rc = fc_deleteSeqSubset(numStepPerSub[i], seqSubsets[i]);
    if (rc != FC_SUCCESS)
      return rc;
  }
  free(numStepPerSub);
  for (i = 0; i < numSeqSub; i++)
    free(seqSubsets[i]);
  free(seqSubsets);
  // delete member variables
  rc = fc_getVariables(mesh, &numVar, &variables);
  if (rc != FC_SUCCESS)
    return rc;
  for (i = 0; i < numVar; i++) {
    rc = fc_deleteVariable(variables[i]);
    if (rc != FC_SUCCESS)
      return rc;
  }
  free(variables);
  // delete member seq vars
  rc = fc_getSeqVariables(mesh, &numSeqVar, &numStepPerVar, &seqVariables);
  if (rc != FC_SUCCESS)
    return rc;
  for (i = 0; i < numSeqVar; i++) {
    rc = fc_deleteSeqVariable(numStepPerVar[i], seqVariables[i]);
    if (rc != FC_SUCCESS)
      return rc;
  }
  free(numStepPerVar);
  for (i = 0; i < numSeqVar; i++)
    free(seqVariables[i]);
  free(seqVariables);
  // remove reference from dataset
  dsSlot = _fc_getDsSlot(meshSlot->ds);
  if (dsSlot->numMesh == 1) {
    free(dsSlot->meshIDs);
    dsSlot->meshIDs = NULL;
    dsSlot->numMesh = 0;
  }
  else {
    for (i = 0; i < dsSlot->numMesh; i++) {
      if (dsSlot->meshIDs[i] == meshSlot->header.slotID)
        break;
    }
    for (j = i+1; j < dsSlot->numMesh; j++) {
      dsSlot->meshIDs[j - 1] = dsSlot->meshIDs[j];
    }
    dsSlot->numMesh--;
  }
  // clear & delete slot
  return _fc_deleteMeshSlot(mesh);
}
FC_ReturnCode fc_getDatasetFromMesh (FC_Mesh mesh, FC_Dataset * dataset)
Get the parent dataset of the mesh.
Modifications:
Nancy Collins, Created.
12/11/03 RM, added default return dataset = FC_NULL_DATASET, input check for dataset == NULL
Parameters:
mesh input - mesh handle
dataset output - dataset handle
Definition at line 2805 of file mesh.c.
References _fc_getMeshSlot(), _FC_MeshSlot::ds, fc_getReturnCodeText(), FC_INPUT_ERROR, FC_NULL_DATASET, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, and _FC_SlotHeader::name.
  {
  _FC_MeshSlot* meshSlot;
  // set up default value
  if(dataset != NULL)
    *dataset = FC_NULL_DATASET;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || dataset == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting dataset from mesh '%s'", meshSlot->header.name);
  // return requested value
  *dataset = meshSlot->ds;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshByName (FC_Dataset dataset, char * meshname, int * numMeshes, FC_Mesh ** meshes)
Get all meshes with a given name from the dataset.
Description:
Returns all meshes on the dataset with the specified name.
Modifications:
Nancy Collins Created.
2003-MAY-30 W Koegler Moved getting mesh meta data from _fc_setupDsSlot() to here. Moved getting variable meta data to fc_openVariable().
11/25/03 RM, added default return mesh = FC_NULL_MESH
11/26/03 RM, added checking for invalid mesh name, issue error if fc_getLibraryVerbosity()
12/03/03 RM added checking for parameter mesh == NULL
12/12/03 RM, eliminated _fc_lookup_meshSlot() and _fc_namematch() those input checking changed and added into this function
9/8/03 WSK, changed name and moved to dataset (to be next to fc_getMeshes)
9/21/06 ACG, now returns all meshes with matching names
Parameters:
dataset input - dataset handle
meshname input - name of mesh to get
numMeshes output - number of matching meshes
meshes output - array of mesh handles
Definition at line 2285 of file mesh.c.
References _FC_GET_HANDLE, _fc_getDsSlot(), _fc_getMeshSlotFromID(), fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_DsSlot::meshIDs, _FC_SlotHeader::name, and _FC_DsSlot::numMesh.
Referenced by getMeshByNameOrDie(), main(), and processOneVar().
  {
  int i;
  _FC_DsSlot* dsSlot;
  _FC_MeshSlot *meshSlot;
  FC_Mesh mesh;
  FC_Mesh *lmatch = NULL;
  int numlmatch, maxnumlmatch;
  // default values returned if anything goes wrong
  if (numMeshes)
    *numMeshes = -1;
  if (meshes)
    *meshes = NULL;
  // check input
  dsSlot = _fc_getDsSlot(dataset);
  if (dsSlot == NULL || meshname == NULL || !meshes || !numMeshes) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting mesh '%s'", meshname);
  numlmatch = 0;
  maxnumlmatch = 0;
  // look for existing slots with the matching name
  for (i = 0; i < dsSlot->numMesh; i++) {
    meshSlot = _fc_getMeshSlotFromID(dsSlot->meshIDs[i]);
    if (!strcmp(meshSlot->header.name, meshname)) {
      _FC_GET_HANDLE(mesh, meshSlot);
      if (lmatch == NULL){
     lmatch = (FC_Mesh*)malloc(sizeof(FC_Mesh));
     if (lmatch == NULL){
       fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
       return FC_MEMORY_ERROR;
     }
     numlmatch = 1;
     maxnumlmatch = 1;
     lmatch[0] = mesh;
      }else{
     if(numlmatch == maxnumlmatch){
       FC_Mesh *temp;
       temp = (FC_Mesh*)realloc(lmatch,(2*numlmatch)*sizeof(FC_Mesh));
       if (temp == NULL){
         fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
         return FC_MEMORY_ERROR;
       }
       maxnumlmatch*=2;
       lmatch = temp;
     }
     lmatch[numlmatch] = mesh;
     numlmatch++;
      }
    }
  }
  *numMeshes = numlmatch;
  *meshes = lmatch;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshCoordsAsVariable (FC_Mesh mesh, FC_Variable * coords_var)
Return the vertex coordinates of the mesh as a variable.
Description:
Returns the variable which is the coords of the mesh, creating it on the first call to this function (and returning the same handle on successive calls). The name of the variable will be 'coordinates'.
The official coords variable is treated a little differently from regular variables. Calling this routine always provides a handle to the same variable. However, making a copy gives back a normal variable with the same data (it's not an official coords variable).
This variable will not be written to disk when the dataset containing it is written to disk. If a copy of a mesh with a coords variable is made, the copied mesh will have an existing coords variable.
Modifications:
09/15/04 WSK, Created.
Parameters:
mesh input - mesh
coords_var output - variable containing coords
Definition at line 3497 of file mesh.c.
References _FC_GET_HANDLE, _fc_getMeshSlot(), _fc_getVarSlotFromID(), _FC_MeshSlot::coordVarID, _FC_MeshSlot::dim, FC_AT_VERTEX, fc_createVariable(), FC_DT_DOUBLE, FC_ERROR, fc_getMeshCoordsPtr(), fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MT_SCALAR, FC_MT_VECTOR, FC_NULL_VARIABLE, fc_printfErrorMessage, fc_printfLogMessage, fc_setVariableData(), FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numVertex, and FC_Variable::slotID.
Referenced by fc_copyMesh(), and fc_createSubsetMesh().
  {
  FC_ReturnCode rc;
  FC_MathType mathType;
  _FC_MeshSlot* meshSlot;
  double* coords_p;
  // default return
  if (coords_var)
    *coords_var = FC_NULL_VARIABLE;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || coords_var == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Creating coordinates variable for mesh '%s'",
                      meshSlot->header.name);
  // If the coords variable already exists, return it
  if (meshSlot->coordVarID > -1) {
    _FC_GET_HANDLE(*coords_var, _fc_getVarSlotFromID(meshSlot->coordVarID));
    return FC_SUCCESS;
  }
  // create the variable
  rc = fc_getMeshCoordsPtr(mesh, &coords_p);
  if (rc != FC_SUCCESS)
    return rc;
  if (meshSlot->dim == 1)
    mathType = FC_MT_SCALAR;
  else
    mathType = FC_MT_VECTOR;
  rc = fc_createVariable(mesh, "coords", coords_var);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_setVariableData(*coords_var, meshSlot->numVertex, meshSlot->dim,
                          FC_AT_VERTEX, mathType, FC_DT_DOUBLE,
                          (void*)coords_p);
  if (rc != FC_SUCCESS)
    return FC_ERROR;
  // set the coord var
  meshSlot->coordVarID = coords_var->slotID;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshCoordsPtr (FC_Mesh mesh, double ** coords_p)
Return the vertex coordinates of the mesh.
Description:
Return an array containing the values of each vertex location. If the vertices are 2D, the array has X0, Y0, X1, Y1, etc - interleaved. If the vertices are 3D, the array has X0, Y0, Z0, X1, Y1, Z1, ... The user gets a pointer back to a shared array and should treat it as read only. To modify any of the values the user must first make a copy.
Note, you can index to coordinate j of the ith vertex directly as coords[i*numDim + j];
Modifications:
Nancy Collins, Created.
Parameters:
mesh input - mesh
coords_p output - vertices. user should treat as read only
Definition at line 3436 of file mesh.c.
References _fc_getMeshSlot(), _fc_readMeshCoords(), _FC_SlotHeader::committed, _FC_MeshSlot::coords, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, and _FC_SlotHeader::name.
Referenced by _fc_geomSmoothCore(), _fc_getOutwardFaceNormal(), _fc_getSubsetDiameterCore(), _fc_getSubsetsDiameterCore(), _fc_getSubsetsProximityCore(), _fc_getVertexIDsWithinBoundingBoxUsingVertexBin(), _fc_getVertexIDsWithinSphereUsingVertexBin(), _fc_readLSDynaVariableData(), _fc_writeExodusDataset(), fc_copyMesh(), fc_createMeshVertexBin(), fc_createSubsetMesh(), fc_doesElementContainPoint(), fc_evalPrestoSpotWeld(), fc_getDisplacedMeshCoords(), fc_getEdgeLengths(), fc_getElementCenters(), fc_getElementsThatContainPoint(), fc_getFaceAreas(), fc_getMeshBoundingBox(), fc_getMeshCentroid(), fc_getMeshCoordsAsVariable(), fc_getRegionVolumes(), fc_getSubsetBoundingBox(), fc_getSubsetCentroid(), fc_getSurfaceNormals(), fc_getVariableWeightedMeshCentroid(), fc_getVariableWeightedSubsetCentroid(), fc_makeSpanningTree(), fc_printMesh(), fc_printSubsetOfMesh(), fc_projectedElementBoundingBoxIntersection(), fc_rewriteDataset(), fc_setSphereDisplacementVariable(), fc_unpackSkeletonFromMesh(), and main().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default return
  if (coords_p)
    *coords_p = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || coords_p == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting coordinates for mesh '%s'",
                      meshSlot->header.name);
  // lazy fetching of coords
  if (meshSlot->coords == NULL && meshSlot->header.committed == 1) {
    rc = _fc_readMeshCoords(mesh);
    if (rc != FC_SUCCESS) {
      fc_printfErrorMessage("Lazy loading of coords for mesh '%s' failed",
                            meshSlot->header.name);
      return rc;
    }
  }
  // fill in requested value
  *coords_p = meshSlot->coords;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshDim (FC_Mesh mesh, int * dim)
Returns dimensionality of the mesh coordinates.
Description:
I.e. 1D, 2D or 3D coordinates.
Modifications:
Nancy Collins, Created.
12/11/03 RM, added default return dim=-1, and check input for dim=NULL
Parameters:
mesh input - mesh
dim output - count of dimensions
Definition at line 2953 of file mesh.c.
References _fc_getMeshSlot(), _FC_MeshSlot::dim, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, and _FC_SlotHeader::name.
Referenced by _fc_geomSmoothCore(), _fc_getSubsetDiameterCore(), _fc_getSubsetsDiameterCore(), _fc_getSubsetsProximityArgsTest(), _fc_getSubsetsProximityCore(), fc_evalPrestoSpotWeld(), fc_getDisplacedSubsetBoundingBox(), fc_getDisplacedSubsetCentroid(), fc_getSubsetBoundingBox(), fc_getSubsetCentroid(), fc_printSubsetOfMesh(), getLinesAsVectors(), main(), and processOneVar().
  {
  _FC_MeshSlot* meshSlot;
  // set up defaults
  if (dim != NULL)
    *dim = -1;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || dim == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting topo dimensionality for mesh '%s'",
                      meshSlot->header.name);
  // fill in requested value
  *dim = meshSlot->dim;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshEdgeConnsPtr (FC_Mesh mesh, int ** conns_p)
Return edge connectivities.
Description:
This routine returns a pointer to the array that has the IDs of the vertices that make up the edges. The array is { Edge0Vert0 Edge0Vert1 Edge1Vert0 Edge1Vert1 ... EdgeNVert0 EdgeNVert1 }. This is a big data array and should NOT be freed by the calling program.
You can index to the jth vertex of the ith edge directly as conns[i*2 + j];
Note that edges may not yet exist for the mesh, and if they don't, calling this function will build them (which may take some time).
Modifications:
02/06/04 WSK, created.
09/21/04 WSK, removed args for non-big data values which can now be gotten with fc_getMeshEdgeFaceInfo().
Parameters:
mesh input - mesh
conns_p output - edge to vertex connections, treat read only
Definition at line 3571 of file mesh.c.
References _fc_buildEdgeConns(), _fc_getMeshSlot(), _FC_MeshSlot::edgeToVertConns, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, and _FC_MeshSlot::numEdge.
Referenced by _fc_buildMeshVertexNeighborsViaEdge(), _fc_buildParents(), _fc_geomSmoothCore(), _fc_getEdgeNeighbors(), _fc_getEdgeParents(), fc_getDisplacedEdgeLengths(), fc_getEdgeLengths(), fc_getMeshEntityChildren(), fc_printMesh(), fc_printSubsetOfMesh(), and main().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default return
  if (conns_p)
    *conns_p = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || conns_p == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting edge connectivities on mesh '%s'",
                      meshSlot->header.name);
  // if it doesn't exist, build vertex, element & neighbor stuff
  if (meshSlot->numEdge == -1) {
    rc = _fc_buildEdgeConns(mesh);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // return pointer
  *conns_p = meshSlot->edgeToVertConns;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshEdgeFaceInfo (FC_Mesh mesh, int * numEdge, int * numFace, FC_ElementType * faceType)
Get information about edges and faces in a mesh.
Description:
If edges and faces do not yet exist, they are built.
Modifications:
09/21/04 WSK, created.
Parameters:
mesh input - mesh handle
numEdge output - number of edges
numFace output - number of faces
faceType output - face type (tri, quad or mixed)
Definition at line 3099 of file mesh.c.
References _fc_buildEdgeConns(), _fc_buildFaceConns(), _fc_getMeshSlot(), _FC_MeshSlot::elemType, FC_ET_UNKNOWN, fc_getElementTypeFaceType(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numEdge, and _FC_MeshSlot::numFace.
Referenced by fc_printMesh().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default values returned if anything goes wrong
  if (numEdge != NULL)
    *numEdge = -1;
  if (numFace != NULL)
    *numFace = -1;
  if (faceType != NULL)
    *faceType = FC_ET_UNKNOWN;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || (!numEdge && !numFace && !faceType) ) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting edge and face info for mesh '%s'",
                      meshSlot->header.name);
  // build edges & faces if necessary
  if (numEdge != NULL && meshSlot->numEdge == -1) {
    rc = _fc_buildEdgeConns(mesh);
    if (rc != FC_SUCCESS)
      return rc;
  }
  if (numFace != NULL && meshSlot->numFace == -1) {
    rc = _fc_buildFaceConns(mesh);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // fill in requested values
  if (numEdge != NULL)
    *numEdge = meshSlot->numEdge;
  if (numFace != NULL)
    *numFace = meshSlot->numFace;
  if (faceType != NULL)
    *faceType = fc_getElementTypeFaceType(meshSlot->elemType);
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshElementConnsPtr (FC_Mesh mesh, int ** conns_p)
Return element to vertex connectivities for the mesh.
Description:
Return actual element indices. The return value is a pointer to an array of integers. The user must treat this array as read only. To modify any values, the user must make a copy first. If each element contains N vertices, the first N integers are for element 0, the next N integers are element 1, etc. To get the jth vertex ID of the ith element index as conns[i*numVertPrElem + j]. numVertPerElem can be find by calling fc_getElementTypeNumVertex() or fc_getElementTypeNumEntity().
Modifications:
Nancy Collins, Created.
Parameters:
mesh input - mesh
conns_p output - element index buffer, treat read only
Definition at line 3762 of file mesh.c.
References _fc_getMeshSlot(), _fc_readMeshElemConns(), _FC_SlotHeader::committed, _FC_MeshSlot::elemToVertConns, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, and _FC_SlotHeader::name.
Referenced by _fc_buildEdgeConns(), _fc_buildFaceConns(), _fc_buildMeshElementNeighborsViaEntity(), _fc_buildParents(), _fc_geomSmoothCore(), _fc_writeExodusDataset(), fc_convertTreeToMesh(), fc_copyMesh(), fc_createSubsetMesh(), fc_evalPrestoSpotWeld(), fc_getDisplacedRegionVolumes(), fc_getDisplacedSurfaceNormals(), fc_getElementCenters(), fc_getMeshEntityChildren(), fc_getRegionVolumes(), fc_getSurfaceNormals(), fc_makeSpanningTree(), fc_printMesh(), fc_printSubsetOfMesh(), fc_projectedElementBoundingBoxIntersection(), fc_rewriteDataset(), fc_saveSkeleton(), fc_unpackSkeletonFromMesh(), getLinesAsVectors(), and main().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default return
  if (conns_p)
    *conns_p = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || conns_p == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting element connectivities for mesh '%s'",
                      meshSlot->header.name);
  // lazy fetching of conns
  if (meshSlot->elemToVertConns == NULL && meshSlot->header.committed == 1) {
    rc = _fc_readMeshElemConns(mesh);
    if (rc != FC_SUCCESS) {
      fc_printfErrorMessage("Lazy loading of conns for mesh '%s' failed",
                            meshSlot->header.name);
      return rc;
    }
  }
  // fill in requested value
  *conns_p = meshSlot->elemToVertConns;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshElementFaceOrientsPtr (FC_Mesh mesh, int ** elemFaceOrients_p)
Return element's face's orientations relative to global faces.
Description:
By definition, the vertices of the faces of an element are ordered (counter clockwise) so that the face's normal points out of the element. In the gobal face array for a mesh, however, the vertices are (somewhat) arbitrarily ordered and you cannot know for sure the direction of a face without reference to an element. For example, a face shared by two elements has a different orientation depending on which element you are talking about. Let's say that the face was defined so that it points out of the first element. Then the entry of the faceOrients array for that face of the first element is 1. The faceOrients value for that face in the second element is -1. The -1 tells you that you need to reverse the order of the vertices of that face in order to treat it as if it had come from the second element.
This routine returns a pointer to the array that has orientation flags for the faces that make up the elements. The array is ordered { Elem0Face0 Elem0Face1 ... Elem0FaceN Elem1Face0 Elem1Face1 ... Elem1FaceN ...... ElemMFace0 ElemMFace1 ... ElemMFaceN }. This is a big data array and should NOT be freed by the calling program. Possible values are 1: vertices of the face are in order expected for the element; or -1: vertices of the face are in the reverse order of that expected for the element.
(I'm pretty sure that all unique faces will have orient = 1.)
Note that faces may not yet exist for the mesh, and if they don't, calling this function will build them (which may take some time).
Modifications:
10/26/05 WSD, created.
Parameters:
mesh input - mesh
elemFaceOrients_p output - element's face's orientations, treat read only
Definition at line 3952 of file mesh.c.
References _fc_buildFaceConns(), _fc_getMeshSlot(), _FC_MeshSlot::elemFaceOrients, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, and _FC_MeshSlot::numFace.
Referenced by _fc_getOutwardFaceNormal(), and calcFaceOrients().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default return
  if (elemFaceOrients_p)
    *elemFaceOrients_p = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || elemFaceOrients_p == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting element to face connectivities on mesh '%s'",
                      meshSlot->header.name);
  // if it doesn't exist, build vertex, element & neighbor stuff
  if (meshSlot->numFace == -1) {
    rc = _fc_buildFaceConns(mesh);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // return pointer
  *elemFaceOrients_p = meshSlot->elemFaceOrients;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshElementToEdgeConnsPtr (FC_Mesh mesh, int ** elemToEdgeConns_p)
Return element to edge connectivities.
Description:
This routine returns a pointer to the array that has the IDs of the edges that make up the elements. The array is { Elem0Edge0 Elem0Edge1 ... Elem0EdgeN Elem1Edge0 Elem1Edge1 ... Elem1EdgeN ...... ElemMEdge0 ElemMEdge1 ... ElemMEdgeN }. This is a big data array and should NOT be freed by the calling program. To get the id of the jth edge in the ith element, index by conns[i*numEdgePerElem+j]. numEdgePerElem can be found by a call to fc_getElementTypeNumEdge() or fc_getElementTypeNumEntity().
Note that edges may not yet exist for the mesh, and if they don't, calling this function will build them (which may take some time).
Modifications:
10/26/05 WSD, created.
Parameters:
mesh input - mesh
elemToEdgeConns_p output - element to edge connections, treat read only
Definition at line 3821 of file mesh.c.
References _fc_buildEdgeConns(), _fc_getMeshSlot(), _FC_MeshSlot::elemToEdgeConns, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, and _FC_MeshSlot::numEdge.
Referenced by _fc_buildMeshElementNeighborsViaEntity(), _fc_buildParents(), _fc_readExodusSubsetMembers(), _fc_writeExodusDataset(), fc_createSubsetMesh(), and fc_getMeshEntityChildren().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default return
  if (elemToEdgeConns_p)
    *elemToEdgeConns_p = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || elemToEdgeConns_p == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting element to edge connectivities on mesh '%s'",
                      meshSlot->header.name);
  // if it doesn't exist, build vertex, element & neighbor stuff
  if (meshSlot->numEdge == -1) {
    rc = _fc_buildEdgeConns(mesh);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // return pointer
  *elemToEdgeConns_p = meshSlot->elemToEdgeConns;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshElementToFaceConnsPtr (FC_Mesh mesh, int ** elemToFaceConns_p)
Return element to face connectivities.
Description:
This routine returns a pointer to the array that has the IDs of the faces that make up the elements. The array is { Elem0Face0 Elem0Face1 ... Elem0FaceN Elem1Face0 Elem1Face1 ... Elem1FaceN ...... ElemMFace0 ElemMFace1 ... ElemMFaceN }. This is a big data array and should NOT be freed by the calling program. To get the id of the jth face in the ith element, index by conns[i*numFacePerElem+j]. numFacePerElem can be found by a call to fc_getElementTypeNumFace() or fc_getElementTypeNumEntity().
See also fc_getMeshElementFaceOrientsPtr().
Note that faces may not yet exist for the mesh, and if they don't, calling this function will build them (which may take some time).
Modifications:
10/26/05 WSD, created.
Parameters:
mesh input - mesh
elemToFaceConns_p output - element to face connections, treat read only
Definition at line 3880 of file mesh.c.
References _fc_buildFaceConns(), _fc_getMeshSlot(), _FC_MeshSlot::elemToFaceConns, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, and _FC_MeshSlot::numFace.
Referenced by _fc_buildMeshElementNeighborsViaEntity(), _fc_buildParents(), _fc_getOutwardFaceNormal(), _fc_readExodusSubsetMembers(), _fc_writeExodusDataset(), calcFaceOrients(), fc_createSubsetMesh(), and fc_getMeshEntityChildren().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default return
  if (elemToFaceConns_p)
    *elemToFaceConns_p = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || elemToFaceConns_p == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting element to face connectivities on mesh '%s'",
                      meshSlot->header.name);
  // if it doesn't exist, build vertex, element & neighbor stuff
  if (meshSlot->numFace == -1) {
    rc = _fc_buildFaceConns(mesh);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // return pointer
  *elemToFaceConns_p = meshSlot->elemToFaceConns;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshElementType (FC_Mesh mesh, FC_ElementType * elemType)
Returns type of elements in the mesh.
Modifications:
Nancy Collins, Created.
12/11/03 RM, added default return elemType = FC_ET_UNKNOWN, and input check for elemType = NULL
Parameters:
mesh input - mesh
elemType output - element type
Definition at line 3061 of file mesh.c.
References _fc_getMeshSlot(), _FC_MeshSlot::elemType, FC_ET_UNKNOWN, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, and _FC_SlotHeader::name.
Referenced by _fc_geomSmoothCore(), _fc_loadExodusDataset(), _fc_readExodusSubsetMembers(), calcFaceOrients(), fc_evalPrestoSpotWeld(), fc_getMeshEntityChildren(), fc_getMeshEntityElementType(), and fc_printSubsetOfMesh().
  {
  _FC_MeshSlot* meshSlot;
  // set up defaults
  if(elemType != NULL)
    *elemType = FC_ET_UNKNOWN;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || elemType == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting dimensionality for mesh '%s'",
                      meshSlot->header.name);
  // fill in requested value
  *elemType = meshSlot->elemType;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshEntityElementType (FC_Mesh mesh, FC_AssociationType assoc, int ID, FC_ElementType * elemType)
Get the element type of the mesh entity.
Description:
This is really only interesting for faces and elements. The association type of "whole" returns the type of the elements of the mesh.
If you ask for edges or faces and they don't exist yet, they will be built.
It is an error to ask for the association type FC_AT_WHOLE_DATASET.
Modifications:
07/16/04 WSK Created.
Parameters:
mesh input - mesh
assoc input - the entity's type
ID input - the ID of the mesh entity
elemType output - the element type of the entity
Definition at line 3371 of file mesh.c.
References FC_AT_EDGE, FC_AT_ELEMENT, FC_AT_FACE, FC_AT_UNKNOWN, FC_AT_VERTEX, FC_AT_WHOLE_DATASET, FC_AT_WHOLE_MESH, FC_ET_LINE, FC_ET_POINT, FC_ET_UNKNOWN, fc_getMeshElementType(), fc_getMeshFaceTypesPtr(), fc_getMeshNumEntity(), FC_INPUT_ERROR, fc_isAssociationTypeValid(), fc_isMeshValid(), and FC_SUCCESS.
Referenced by _fc_buildFaceInfoListFromSubset(), _fc_buildParents(), fc_getMeshEntityChildren(), fc_getSubsetSkin(), and main().
  {
  FC_ReturnCode rc;
  int num;
  FC_ElementType* faceTypes;
  // default return
  if (elemType)
    *elemType = FC_ET_UNKNOWN;
  // check input
  if (!fc_isMeshValid(mesh) || !fc_isAssociationTypeValid(assoc) ||
      assoc == FC_AT_UNKNOWN || ID < 0 || !elemType)
    return FC_INPUT_ERROR;
  rc = fc_getMeshNumEntity(mesh, assoc, &num);
  if (rc != FC_SUCCESS)
    return rc;
  if (ID >= num)
    return FC_INPUT_ERROR;
  switch (assoc) {
  case FC_AT_VERTEX: *elemType = FC_ET_POINT; break;
  case FC_AT_EDGE:   *elemType = FC_ET_LINE;  break;
  case FC_AT_FACE:
    fc_getMeshFaceTypesPtr(mesh, &faceTypes);
    *elemType = faceTypes[ID];
    break;
  case FC_AT_ELEMENT: // fall through to FC_AT_WHOLE_MESH
  case FC_AT_WHOLE_MESH: fc_getMeshElementType(mesh, elemType); break;
  case FC_AT_WHOLE_DATASET: // fall through to FC_AT_UNKNOWN
  case FC_AT_UNKNOWN:
    return FC_INPUT_ERROR;
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshes (FC_Dataset dataset, int * numMesh, FC_Mesh ** meshes)
Get the meshes in a dataset.
Description:
This call returns an array of meshes in the dataset. The caller is responsible for freeing the array of sequence handles.
Modifications:
Nancy Collins Created.
July 23, 2002 W Koegler Changed so it no longer makes safcover calls
11/21/03 RM, added default return nmeshes = -1, and meshnames = NULL if anything is wrong
9/8/04 WSK, changed to return mesh handles instead of mesh names.
Parameters:
dataset input - dataset
numMesh output - number of meshes returned
meshes output - array of meshes
Definition at line 2183 of file mesh.c.
References _FC_GET_HANDLE, _fc_getDsSlot(), _fc_getMeshSlotFromID(), fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_DsSlot::header, _FC_DsSlot::meshIDs, _FC_SlotHeader::name, and _FC_DsSlot::numMesh.
Referenced by _fc_hasSharedLSDynaVertices(), _fc_writeExodusDataset(), fc_deleteDataset(), fc_releaseDataset(), fc_rewriteDataset(), and main().
  {
  int i;
  _FC_DsSlot* dsSlot;
  _FC_MeshSlot* meshSlot;
  // default return values
  if (numMesh != NULL)
    *numMesh = -1;
  if (meshes != NULL)
    *meshes = NULL;
  // check input
  dsSlot = _fc_getDsSlot(dataset);
  if (dsSlot == NULL || numMesh == NULL || meshes == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting meshes from dataset '%s'",
                      dsSlot->header.name);
  // get num meshes
  *numMesh = dsSlot->numMesh;
  // get meshes
  if (dsSlot->numMesh > 0) {
    *meshes = malloc(sizeof(FC_Mesh)*dsSlot->numMesh);
    if (*meshes == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return FC_MEMORY_ERROR;
    }
    for (i = 0; i < dsSlot->numMesh; i++) {
      meshSlot = _fc_getMeshSlotFromID(dsSlot->meshIDs[i]);
      _FC_GET_HANDLE((*meshes)[i], meshSlot);
    }
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshFaceConnsPtr (FC_Mesh mesh, int ** numVertPerFace_p, int * maxNumVertPerFace_p, int ** conns_p)
Return face connectivities.
Description:
This routine returns an array that has the IDs of the vertices that make up the faces. In addition there is an array with the number of vertices per face because some element types have multiple types of faces (i.e. pyramids and prisms). For example, if the faces are triangles, every entry of the numVertPerFace array will be '3' and the connectivity array will look like { Face0Vert0 Face0Vert1 Face0Vert2 Face1Vert0 ... FaceNVert0 FaceNVert1 FaceNVert2 }.
If the face type is mixed, the connectivity array will be maxNumVertPerFace * numFace long and the unused entries (for when numVertPerFace < maxNumVertPerFace) will be equal to -1. For example, a prism mesh's face connectivity might have numVertPerFace = { 3 4 3 ... } and conns = { Face0Vert0 Face0Vert1 Face0Vert2 -1 Face1Vert0 Face1Vert1 Face1Vert2 Face1Vert3 Face2Vert0 Face2Vert1 Face2Vert2 -1 ... }. Note you can index directly to face n by conns[n*maxNumVertPerFace].
The number of vertices per face and the connectivity arrays are both considered to big data arrays and should NOT be freed by the calling program. Fetching the numVertPerFaceArray is optional.
Note that faces may not yet exist for the mesh, and if they don't, calling this function will build them (which may take some time).
Modifications:
02/06/04 WSK, created.
09/21/04 WSK, removed args for non-big data values which can now be gotten with fc_getMeshEdgeFaceInfo().
Parameters:
mesh input - mesh
numVertPerFace_p output - (optional) num vert per face, treat read only
maxNumVertPerFace_p output - (optional) stride length of the conns array
conns_p output - face to vertex connections, treat read only
Definition at line 3691 of file mesh.c.
References _fc_buildFaceConns(), _fc_getMeshSlot(), _FC_MeshSlot::elemType, _FC_MeshSlot::faceToVertConns, FC_ET_MIXED, FC_ET_UNKNOWN, fc_getElementTypeFaceType(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numFace, and _FC_MeshSlot::numVertPerFace.
Referenced by _fc_buildParents(), _fc_geomSmoothCore(), _fc_getFaceNeighbors(), _fc_getOutwardFaceNormal(), fc_doesElementContainPoint(), fc_evalPrestoSpotWeld(), fc_getDisplacedFaceAreas(), fc_getElementsThatContainPoint(), fc_getFaceAreas(), fc_getMeshEntityChildren(), fc_printMesh(), fc_printSubsetOfMesh(), and main().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default return
  if (numVertPerFace_p)
    *numVertPerFace_p = NULL;
  if (maxNumVertPerFace_p)
    *maxNumVertPerFace_p = -1;
  if (conns_p)
    *conns_p = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || !conns_p) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting face connectivities for mesh '%s'",
                      meshSlot->header.name);
  // if it doesn't exist, build vertex, element & neighbor stuff
  if (meshSlot->numFace == -1) {
    rc = _fc_buildFaceConns(mesh);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // return values
  if (numVertPerFace_p)
    *numVertPerFace_p = meshSlot->numVertPerFace;
  if (maxNumVertPerFace_p) {
    FC_ElementType faceType = fc_getElementTypeFaceType(meshSlot->elemType);
    if (faceType == FC_ET_MIXED)
      *maxNumVertPerFace_p = 4; // assume will be mix of tris and quads
    else if (faceType == FC_ET_UNKNOWN)
      *maxNumVertPerFace_p = 0;
    else
      *maxNumVertPerFace_p = meshSlot->numVertPerFace[0];
  }
  *conns_p = meshSlot->faceToVertConns;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshFaceType (FC_Mesh mesh, FC_ElementType * faceType)
Get element type of the face in the mesh.
Description:
If edges and faces do not yet exist, they are built. Pyramids and prisms may return the type FC_ET_MIXED.
Modifications:
09/21/04 WSK, created.
Parameters:
mesh input - mesh handle
faceType output - face type (tri, quad or mixed)
Definition at line 3256 of file mesh.c.
References _fc_getMeshSlot(), _FC_MeshSlot::elemType, FC_ET_UNKNOWN, fc_getElementTypeFaceType(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, and _FC_SlotHeader::name.
Referenced by fc_printSubsetOfMesh().
  {
  _FC_MeshSlot* meshSlot;
  // default values returned if anything goes wrong
  if (faceType != NULL)
    *faceType = FC_ET_UNKNOWN;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || !faceType) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting edge and face info for mesh '%s'",
                      meshSlot->header.name);
  // fill in requested values
  if (faceType != NULL)
    *faceType = fc_getElementTypeFaceType(meshSlot->elemType);
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshFaceTypesPtr (FC_Mesh mesh, FC_ElementType ** faceTypes_p)
Return face types.
Description:
This routine returns a pointer to the array that has the element type of each face. This is a big data array and should NOT be freed by the calling program.
Note that faces may not yet exist for the mesh, and if they don't, calling this function will build them (which may take some time).
Modifications:
10/25/05 WSD, created.
Parameters:
mesh input - mesh
faceTypes_p output - face types, treat read only
Definition at line 3622 of file mesh.c.
References _fc_buildFaceConns(), _fc_getMeshSlot(), _FC_MeshSlot::faceTypes, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, and _FC_MeshSlot::numFace.
Referenced by _fc_getOutwardFaceNormal(), fc_evalPrestoSpotWeld(), fc_getDisplacedFaceAreas(), fc_getFaceAreas(), and fc_getMeshEntityElementType().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default return
  if (faceTypes_p)
    *faceTypes_p = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || faceTypes_p == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting edge connectivities on mesh '%s'",
                      meshSlot->header.name);
  // if it doesn't exist, build vertex, element & neighbor stuff
  if (meshSlot->numFace == -1) {
    rc = _fc_buildFaceConns(mesh);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // return pointer
  *faceTypes_p = meshSlot->faceTypes;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshInfo (FC_Mesh mesh, int * topodim, int * dim, int * numVertex, int * numElement, FC_ElementType * elemType)
Get information about a mesh.
Description:
Returns the topological dimensionality of the mesh elements, the spatial dimensionality of the mesh coordinates, the number of vertices, the number of elements, and the element type.
Modifications:
Nancy Collins Created.
11/25/03 RM, added checking for NULL mesh handle, default return: topodim = -1, dim = -1, numVertex = -1; numElement = -1, elemType = FC_ET_UNKNOWN; issue an error if fc_getLibraryVerbosity().
Parameters:
mesh input - mesh handle
topodim output - topological dimensionality of mesh (e.g. 0 for a point mesh, 2 for a surface, 3 for volume)
dim output - 2=2d coordinates, 3=3d coords
numVertex output - number of vertices
numElement output - number of elements
elemType output - element type (quad, tet)
Definition at line 2848 of file mesh.c.
References _fc_getMeshSlot(), _FC_MeshSlot::dim, _FC_MeshSlot::elemType, FC_ET_UNKNOWN, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numElement, _FC_MeshSlot::numVertex, and _FC_MeshSlot::topodim.
Referenced by _fc_buildEdgeConns(), _fc_buildFaceConns(), _fc_buildMeshElementNeighborsViaEntity(), _fc_getOutwardFaceNormal(), _fc_writeExodusDataset(), fc_copyMesh(), fc_copySeqVariableStepFromRegionMesh(), fc_createDisplacedMeshVertexBin(), fc_createMeshVertexBin(), fc_createSubsetMesh(), fc_doesElementContainPoint(), fc_getDisplacedEdgeLengths(), fc_getDisplacedFaceAreas(), fc_getDisplacedMeshBoundingBox(), fc_getDisplacedMeshCentroid(), fc_getDisplacedRegionVolumes(), fc_getDisplacedSurfaceNormals(), fc_getEdgeLengths(), fc_getElementCenters(), fc_getElementsThatContainPoint(), fc_getFaceAreas(), fc_getMeshBoundingBox(), fc_getMeshCentroid(), fc_getRegionVolumes(), fc_getSurfaceNormals(), fc_getVariableWeightedDisplacedMeshCentroid(), fc_getVariableWeightedDisplacedSubsetCentroid(), fc_getVariableWeightedMeshCentroid(), fc_getVariableWeightedSubsetCentroid(), fc_isValidDisplacementVariable(), fc_makeSpanningTree(), fc_printMesh(), fc_projectedElementBoundingBoxIntersection(), fc_setSphereDisplacementVariable(), fc_unpackSkeletonFromMesh(), and main().
  {
  _FC_MeshSlot* meshSlot;
  // default values returned if anything goes wrong
  if (topodim != NULL)
    *topodim = -1;
  if (dim != NULL)
    *dim = -1;
  if (numVertex != NULL)
    *numVertex = -1;
  if (numElement != NULL)
    *numElement = -1;
  if (elemType != NULL)
    *elemType = FC_ET_UNKNOWN;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL ||
      (!topodim && !dim && !numVertex && !numElement && !elemType) ) {
     fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting info for mesh '%s'", meshSlot->header.name);
  // fill in requested values
  if (dim != NULL)
    *dim = meshSlot->dim;
  if (topodim != NULL)
    *topodim = meshSlot->topodim;
  if (numVertex != NULL)
    *numVertex = meshSlot->numVertex;
  if (numElement != NULL)
    *numElement = meshSlot->numElement;
  if (elemType != NULL)
    *elemType = meshSlot->elemType;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshName (FC_Mesh mesh, char ** meshname)
Return name of a mesh.
Description:
Return the name associated with a mesh handle. Spaced is allocated for the string so it needs to be freed by the user when finished.
Modifications:
Aug, 9, 2002. W Koegler Created.
Parameters:
mesh input - mesh handle
meshname output - mesh name, space allocated here and must be freed by user when finished
Definition at line 2762 of file mesh.c.
References _fc_getMeshSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, and _FC_SlotHeader::name.
Referenced by fc_copySeqVariableStepFromRegionMesh(), fc_getMeshShapes(), fc_printSubsetOfMesh(), getMatchingMesh(), main(), and processOneVar().
  {
  char *cp;
  _FC_MeshSlot* meshSlot;
  // default
  if (meshname)
    *meshname = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || meshname == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting name for mesh '%s'", meshSlot->header.name);
  // copy name
  cp = meshSlot->header.name;
  *meshname = malloc(strlen(cp) + 1);
  if (*meshname == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  strcpy(*meshname, cp);
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshNumEdge (FC_Mesh mesh, int * numEdge)
Get number of edges in a mesh.
Description:
If edges and faces do not yet exist, they are built.
Modifications:
09/21/04 WSK, created.
Parameters:
mesh input - mesh handle
numEdge output - number of edges
Definition at line 3161 of file mesh.c.
References _fc_buildEdgeConns(), _fc_getMeshSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, and _FC_MeshSlot::numEdge.
Referenced by _fc_buildMeshVertexNeighborsViaEdge(), _fc_getEdgeNeighbors(), _fc_getEdgeParents(), fc_copySeqVariableWithNewAssociation(), fc_copyVariableWithNewAssociation(), fc_getDisplacedEdgeLengths(), fc_getEdgeLengths(), fc_printMesh(), and main().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default values returned if anything goes wrong
  if (numEdge != NULL)
    *numEdge = -1;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || !numEdge) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting num edge for mesh '%s'",
                      meshSlot->header.name);
  // build edges & faces if necessary
  if (meshSlot->numEdge == -1) {
    rc = _fc_buildEdgeConns(mesh);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // fill in requested values
  if (numEdge != NULL)
    *numEdge = meshSlot->numEdge;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshNumElement (FC_Mesh mesh, int * numElem)
Returns number of elements in a mesh.
Modifications:
Nancy Collins, Created.
12/11/03 RM, added default return numElem = -1, and input check for numElem = NULL
Parameters:
mesh input - mesh
numElem output - number of elements in this set
Definition at line 3025 of file mesh.c.
References _fc_getMeshSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, and _FC_MeshSlot::numElement.
Referenced by _fc_buildFaceInfoListFromSubset(), fc_copySeqVariableWithNewAssociation(), fc_copyVariableWithNewAssociation(), fc_createSubsetMesh(), fc_getSubsetSkin(), getLinesAsVectors(), main(), printStats(), and segmentMesh().
  {
  _FC_MeshSlot* meshSlot;
  // set up defaults
  if (numElem != NULL)
    *numElem = -1;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || numElem == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting numElement for mesh '%s'",
                      meshSlot->header.name);
  // fill in requested value
  *numElem = meshSlot->numElement;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshNumEntity (FC_Mesh mesh, FC_AssociationType assoc, int * numEntity)
Returns number of a type of mesh entity.
Description:
If you ask for edges or faces and they don't exist yet, they will be built.
It is an error to ask for the association type FC_AT_WHOLE_DATASET.
Modifications:
06/07/04 RM, Created.
07/16/04 WSK, Changed name.
Parameters:
mesh input - mesh
assoc input - association type of entity
numEntity output - number of entities in the mesh
Definition at line 3299 of file mesh.c.
References _fc_buildEdgeConns(), _fc_buildFaceConns(), _fc_getMeshSlot(), FC_AT_EDGE, FC_AT_ELEMENT, FC_AT_FACE, FC_AT_UNKNOWN, FC_AT_VERTEX, FC_AT_WHOLE_MESH, fc_getAssociationTypeText(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isAssociationTypeValid(), fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numEdge, _FC_MeshSlot::numElement, _FC_MeshSlot::numFace, and _FC_MeshSlot::numVertex.
Referenced by _fc_buildFaceInfoListFromSubset(), _fc_buildMeshElementNeighborsViaEntity(), _fc_buildParents(), _fc_makeVariableFromFile(), fc_changeMeshEntityType(), fc_copySeqSubset(), fc_copySeqVariable(), fc_copySubset(), fc_copyVariable(), fc_copyVariableFromRegionMesh(), fc_copyVariableToRegionMesh(), fc_createSeqSubset(), fc_createSubset(), fc_createSubsetMesh(), fc_getMeshEntityChildren(), fc_getMeshEntityElementType(), fc_getMeshEntityNeighbors(), fc_getMeshEntityParents(), fc_getSubsetSkin(), fc_printSubsetOfMesh(), fc_setVariableData(), and fc_setVariableDataPtr().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // set up default return
  if (numEntity != NULL)
    *numEntity = -1;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || !fc_isAssociationTypeValid(assoc) ||
      assoc == FC_AT_UNKNOWN || numEntity == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting number of entities of type %s for mesh '%s'",
                      fc_getAssociationTypeText(assoc),
                      meshSlot->header.name);
  // get the number entities on the mesh for given assoc type
  // build edges & faces if necessary
  switch(assoc) {
  case FC_AT_VERTEX:   *numEntity = meshSlot->numVertex;   break;
  case FC_AT_EDGE:
    if (meshSlot->numEdge == -1) {
      rc = _fc_buildEdgeConns(mesh);
      if (rc != FC_SUCCESS)
        return rc;
    }
    *numEntity = meshSlot->numEdge;     break;
  case FC_AT_FACE:
    if (meshSlot->numFace == -1) {
      rc = _fc_buildFaceConns(mesh);
      if (rc != FC_SUCCESS)
        return rc;
    }
    *numEntity = meshSlot->numFace;     break;
  case FC_AT_ELEMENT:  *numEntity = meshSlot->numElement;  break;
  case FC_AT_WHOLE_MESH:    *numEntity = 1;                     break;
  case FC_AT_UNKNOWN:  // fall through to default
  default:
    return FC_INPUT_ERROR;
  }
  // should never reach here
  //fc_printfErrorMessage("Should never reach here");
  //return FC_ERROR;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshNumFace (FC_Mesh mesh, int * numFace)
Get number of faces in a mesh.
Description:
If edges and faces do not yet exist, they are built.
Modifications:
09/21/04 WSK, created.
Parameters:
mesh input - mesh handle
numFace output - number of faces
Definition at line 3208 of file mesh.c.
References _fc_buildFaceConns(), _fc_getMeshSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, and _FC_MeshSlot::numFace.
Referenced by _fc_createShapePartsFromFaceInfoList(), _fc_getFaceNeighbors(), _fc_getFaceParents(), _fc_getOutwardFaceNormal(), calcFaceOrients(), fc_copySeqVariableWithNewAssociation(), fc_copyVariableWithNewAssociation(), fc_getDisplacedFaceAreas(), and fc_getFaceAreas().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default values returned if anything goes wrong
  if (numFace != NULL)
    *numFace = -1;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || !numFace) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting number of faces for mesh '%s'",
                      meshSlot->header.name);
  // build faces if necessary
  if (meshSlot->numFace == -1) {
    rc = _fc_buildFaceConns(mesh);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // fill in requested values
  if (numFace != NULL)
    *numFace = meshSlot->numFace;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshNumVertex (FC_Mesh mesh, int * numVertex)
Return the number of vertices in a mesh.
Modifications:
Nancy Collins, Created.
12/11/03 RM, added default return numVertex = -1, and input check for numVertex = NULL
Parameters:
mesh input - mesh
numVertex output - integer count of vertices
Definition at line 2989 of file mesh.c.
References _fc_getMeshSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, and _FC_MeshSlot::numVertex.
Referenced by _fc_buildMeshVertexNeighborsViaEdge(), _fc_geomSmoothCore(), _fc_getVertexNeighbors(), _fc_getVertexParents(), _fc_hasSharedLSDynaVertices(), fc_copySeqVariableWithNewAssociation(), and fc_copyVariableWithNewAssociation().
  {
  _FC_MeshSlot* meshSlot;
  // set up defaults
  if (numVertex != NULL)
    *numVertex = -1;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || numVertex == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting numVertex for mesh '%s'",
                      meshSlot->header.name);
  // fill in requested value
  *numVertex = meshSlot->numVertex;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getMeshTopodim (FC_Mesh mesh, int * topodim)
Returns the topological dimensionality of the mesh.
Description:
The topological dimensionality of the mesh is not the same as the dimensionality of the space it is embedded in. Instead the topological dimensionality is dependent on the element type where point meshes are 0D, lines meshes are 1D, surface meshes like triangles and quads are 2D, and volume meshes like tets, pyramids, prisms and hexs are 3D.
Modifications:
Nancy Collins, Created.
12/11/03 RM, added default return dim=-1, and input checking
Parameters:
mesh input - mesh
topodim output - topological dimensionality of elements
Definition at line 2914 of file mesh.c.
References _fc_getMeshSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, and _FC_MeshSlot::topodim.
Referenced by main().
  {
  _FC_MeshSlot* meshSlot;
  // set up defaults
  if (topodim != NULL)
    *topodim = -1;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || topodim == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting topo dim for mesh '%s'",
                      meshSlot->header.name);
  // fill in requested value
  *topodim = meshSlot->topodim;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getNumMesh (FC_Dataset dataset, int * numMesh)
Get the the number of meshes in a dataset.
Modifications:
9/28/04 WSK, created.
Parameters:
dataset input - dataset
numMesh output - number of meshes returned
Definition at line 2235 of file mesh.c.
References _fc_getDsSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_DsSlot::header, _FC_SlotHeader::name, and _FC_DsSlot::numMesh.
Referenced by fc_printDataset().
  {
  _FC_DsSlot* dsSlot;
  // default return values
  if (numMesh != NULL)
    *numMesh = -1;
  // check input
  dsSlot = _fc_getDsSlot(dataset);
  if (dsSlot == NULL || numMesh == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting number of meshes from dataset '%s'",
                      dsSlot->header.name);
  // get num meshes
  *numMesh = dsSlot->numMesh;
  return FC_SUCCESS;
}
int fc_isMeshValid (FC_Mesh mesh)
Check that the handle refers to a valid mesh.
Description:
Returns 1 (true) is the handle is valid, and 0 (false) if it is not.
Modifications:
05/25/04 WSK Created.
Parameters:
mesh input - mesh handle
Definition at line 2742 of file mesh.c.
References _fc_isHandleValid(), meshTableSize, FC_Mesh::slotID, and FC_Mesh::uID.
Referenced by _fc_buildMeshElementNeighborsViaEntity(), _fc_buildMeshVertexNeighborsViaEdge(), _fc_buildParents(), _fc_geomSmoothCore(), _fc_getEdgeNeighbors(), _fc_getEdgeParents(), _fc_getElementNeighbors(), _fc_getFaceNeighbors(), _fc_getFaceParents(), _fc_getMeshExodusGlobalElementIDOffset(), _fc_getMeshExodusGlobalNodalIDsPtr(), _fc_getOutwardFaceNormal(), _fc_getSubsetsProximityArgsTest(), _fc_getVertexIDsWithinBoundingBoxUsingVertexBin(), _fc_getVertexIDsWithinSphereUsingVertexBin(), _fc_getVertexNeighbors(), _fc_getVertexParents(), _fc_makeVariableFromFile(), doesSeqVarExist(), fc_calcMeshDeformationUsingCentroid(), fc_calcMeshDeformationUsingRefVertex(), fc_changeMeshEntityType(), fc_copySeqVariableStepFromRegionMesh(), fc_copySubset(), fc_copyVariable(), fc_copyVariableFromRegionMesh(), fc_copyVariableToRegionMesh(), fc_createDisplacedMeshVertexBin(), fc_createMeshVertexBin(), fc_displacedGeomSmoothSeqVariable(), fc_geomSmoothSeqVariable(), fc_getDisplacedEdgeLengths(), fc_getDisplacedFaceAreas(), fc_getDisplacedMeshBoundingBox(), fc_getDisplacedMeshCentroid(), fc_getDisplacedMeshCoords(), fc_getDisplacedMeshDiameter(), fc_getDisplacedMeshesDiameter(), fc_getDisplacedMeshVolume(), fc_getDisplacedRegionVolumes(), fc_getDisplacedSurfaceNormals(), fc_getEdgeLengths(), fc_getEntitiesWithinBoundingBox(), fc_getEntitiesWithinSphere(), fc_getFaceAreas(), fc_getMeshBoundingBox(), fc_getMeshCentroid(), fc_getMeshDiameter(), fc_getMeshEntityChildren(), fc_getMeshEntityElementType(), fc_getMeshEntityNeighbors(), fc_getMeshEntityParents(), fc_getMeshesDiameter(), fc_getMeshShapes(), fc_getMeshSkin(), fc_getRegionVolumes(), fc_getSurfaceNormals(), fc_getVariableWeightedDisplacedMeshCentroid(), fc_getVariableWeightedMeshCentroid(), fc_isValidDisplacementVariable(), fc_printSubsetOfMesh(), and fc_projectedElementBoundingBoxIntersection().
  {
  return _fc_isHandleValid(mesh.slotID, mesh.uID, meshTableSize,
                           (_FC_SlotHeader**)meshTable);
}
FC_ReturnCode fc_printMesh (FC_Mesh mesh, char * label, int print_edgeConns, int print_faceConns, int print_elemConns, int print_coords)
Print mesh meta data to stdout, and optionally the connections and/or coordinates.
Modifications:
11/20/03 WSK Created.
10/31/07 ACG optional precision
03/03/08 ACG seq subset
Parameters:
mesh input - mesh
label input - label to prepend variable name with, can be NULL
print_edgeConns input > 0 = print the edge connectivities.
print_faceConns input > 0 = print the face connectivities.
print_elemConns input > 0 = print the element connectivities.
print_coords input - 1 = print the coordinates too 2 = print the coordinates in exponential notation w 5 digits precision
Definition at line 4004 of file mesh.c.
References _fc_getMeshSlot(), FC_ERROR, FC_ET_MIXED, fc_getElementTypeNumVertex(), fc_getElementTypeText(), fc_getMeshCoordsPtr(), fc_getMeshEdgeConnsPtr(), fc_getMeshEdgeFaceInfo(), fc_getMeshElementConnsPtr(), fc_getMeshFaceConnsPtr(), fc_getMeshInfo(), fc_getMeshNumEdge(), fc_getNumSeqSubset(), fc_getNumSeqVariable(), fc_getNumSubset(), fc_getNumVariable(), fc_getReturnCodeText(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, FC_NULL_MESH, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, INDENT_STR, _FC_SlotHeader::name, _FC_MeshSlot::numEdge, and _FC_MeshSlot::numFace.
Referenced by main(), and processOneVar().
  {
  FC_ReturnCode rc;
  int i, j;
  _FC_MeshSlot* meshSlot;
  int topodim, dim, numVertex, numElement, numSubset, numSeqSubset, numVar, numSeqVar;
  int numEdge, numFace;
  FC_ElementType elemType, faceType;
  int* ebuf, *numVertPerFace, maxNum;
  double* vbuf;
  // special case: printing a null handle is not an error
  if (FC_HANDLE_EQUIV(mesh, FC_NULL_MESH)) {
    printf("Mesh: FC_NULL_MESH\n");
    fflush(NULL);
    return FC_SUCCESS;
  }
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Printing mesh '%s'", meshSlot->header.name);
  // print label & var name
  if (label)
    printf("%s: ", label);
  else
    printf("Mesh: ");
  printf("'%s'\n", meshSlot->header.name);
  fflush(NULL);
  // print meta data
  rc = fc_getMeshInfo(mesh,  &topodim, &dim, &numVertex, &numElement,
                      &elemType);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get info for mesh '%s'",
                          meshSlot->header.name);
    return rc;
  }
  rc = fc_getNumSubset(mesh, &numSubset);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get subsets for mesh '%s'",
                          meshSlot->header.name);
    return rc;
  }
  rc = fc_getNumSeqSubset(mesh, &numSeqSubset);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get seq subsets for mesh '%s'",
                          meshSlot->header.name);
    return rc;
  }
  rc = fc_getNumVariable(mesh, &numVar);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get variables for mesh '%s'",
                          meshSlot->header.name);
    return rc;
  }
  rc = fc_getNumSeqVariable(mesh, &numSeqVar);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("Failed to get seq variables for mesh '%s'",
                          meshSlot->header.name);
    return rc;
  }
  printf("%snumVertex = %d, dim = %d\n", INDENT_STR, numVertex, dim);
  printf("%snumElement = %d, topodim = %d, elemType = %s\n", INDENT_STR,
         numElement, topodim, fc_getElementTypeText(elemType));
  printf("%snumSubset = %d, numSeqSubset = %d\n", INDENT_STR, numSubset, numSeqSubset);
  printf("%snumVar = %d, numSeqVar = %d\n", INDENT_STR, numVar, numSeqVar);
  fflush(NULL);
  // print edge connectivities
  if (print_edgeConns > 0) {
    if (meshSlot->numEdge < 0) {
      printf("%sEdges have not been built for this mesh\n", INDENT_STR);
      fflush(NULL);
    }
    else {
      rc = fc_getMeshNumEdge(mesh, &numEdge);
      if (rc != FC_SUCCESS) {
        fc_printfErrorMessage("Failed to get numEdge for mesh '%s'",
                               meshSlot->header.name);
        return rc;
      }
      rc = fc_getMeshEdgeConnsPtr(mesh, &ebuf);
      if (rc != FC_SUCCESS) {
        fc_printfErrorMessage("Failed to get edge conns for mesh '%s'",
                              meshSlot->header.name);
        return rc;
      }
      // print the conns
      printf("%sEdge connectivities (2 vertices per edge):\n", INDENT_STR);
      for (i = 0; i < numEdge; i++) {
        printf("%s%s%d:  ", INDENT_STR, INDENT_STR, i);
        for (j = 0; j < 2; j++) {
          printf("%6d ", ebuf[i*2 + j]);
          fflush(NULL);
        }
        printf("\n");
        fflush(NULL);
      }
    }
  }
  // print face connectivities
  if (print_faceConns > 0) {
    if (meshSlot->numFace < 0) {
      printf("%sFaces have not been built for this mesh\n", INDENT_STR);
      fflush(NULL);
    }
    else {
      rc = fc_getMeshEdgeFaceInfo(mesh, NULL, &numFace, &faceType);
      if (rc != FC_SUCCESS) {
        fc_printfErrorMessage("Failed to get edge/face info for mesh '%s'",
                              meshSlot->header.name);
        return rc;
      }
      rc = fc_getMeshFaceConnsPtr(mesh, &numVertPerFace, &maxNum, &ebuf);
      if (rc != FC_SUCCESS) {
        fc_printfErrorMessage("Failed to get edge conns for mesh '%s'",
                              meshSlot->header.name);
        return rc;
      }
      // print the conns
      if (faceType == FC_ET_MIXED)
        printf("%sFace connectivities (faceType = %s, 3 or 4 vertices per "
               "element):\n", INDENT_STR, fc_getElementTypeText(faceType));
      else
        printf("%sFace connectivities (faceType = %s, %d vertices per "
               "element):\n", INDENT_STR, fc_getElementTypeText(faceType),
               fc_getElementTypeNumVertex(faceType));
      fflush(NULL);
      for (i = 0; i < numFace; i++) {
        printf("%s%s%d:  ", INDENT_STR, INDENT_STR, i);
        for (j = 0; j < numVertPerFace[i]; j++) {
          printf("%6d ", ebuf[i*maxNum+j]);
          fflush(NULL);
        }
        printf("\n");
        fflush(NULL);
      }
    }
  }
  // print element connectivities
  if (print_elemConns > 0) {
    int numVertPerElem = fc_getElementTypeNumVertex(elemType);
    rc = fc_getMeshElementConnsPtr(mesh, &ebuf);
    if (rc != FC_SUCCESS) {
      fc_printfErrorMessage("Failed to get element conns for mesh '%s'",
                            meshSlot->header.name);
      return FC_ERROR;
    }
    // print the conns
    printf("%sElement connectivities (%d vertices per element):\n",
           INDENT_STR, numVertPerElem);
    fflush(NULL);
    for (i = 0; i < numElement; i++) {
      printf("%s%s%d:  ", INDENT_STR, INDENT_STR, i);
      for (j = 0; j < numVertPerElem; j++) {
        printf("%6d ", ebuf[i*numVertPerElem + j]);
        fflush(NULL);
      }
      printf("\n");
      fflush(NULL);
    }
  }
  // print coords
  if (print_coords > 0) {
    rc = fc_getMeshCoordsPtr(mesh, &vbuf);
    if (rc != FC_SUCCESS) {
      fc_printfErrorMessage("Failed to get coords for mesh '%s'",
                            meshSlot->header.name);
      return FC_ERROR;
    }
    // print the coordinates per vertex
    printf("%sVertex Coordinates:\n", INDENT_STR);
    fflush(NULL);
    for (i = 0; i < numVertex; i++) {
      printf("%s%s%d:  ", INDENT_STR, INDENT_STR, i);
      for (j = 0; j < dim; j++) {
        // see comment on precision in for DOUBLE case in fc_printVariable()
        //printf("%20.15g ", vbuf[i*dim + j]);
     switch (print_coords){
     case 2:
       printf("%5le ", vbuf[i*dim + j]);
       break;
     default:
       printf("%16.11g ", vbuf[i*dim + j]);
       break;
     }
        fflush(NULL);
      }
      printf("\n");
      fflush(NULL);
    }
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_releaseMesh (FC_Mesh mesh)
Attempt to minimize mesh's memory usage.
Description:
Call to try to release un-needed memory in a mesh. If the mesh has been saved to disk, the large data is released. If the mesh has not be saved to disk, all large data is saved.
If internal mesh structures like elements and vertices exists, they may be freed as long as there are no subsets or variables associated with edges or faces.
This function will recursively call release on it's child subsets and variables
Modifications:
9/27/04 WSK Created.
03/07/08 ACG seq subsets
Parameters:
mesh input - mesh handle
Definition at line 2417 of file mesh.c.
References _fc_getMeshSlot(), _FC_SlotHeader::committed, _FC_MeshSlot::coords, _FC_MeshSlot::edgeParentsPerVert, _FC_MeshSlot::edgeToVertConns, _FC_MeshSlot::elemFaceOrients, _FC_MeshSlot::elemNeighsViaEdge, _FC_MeshSlot::elemNeighsViaFace, _FC_MeshSlot::elemNeighsViaVert, _FC_MeshSlot::elemParentsPerEdge, _FC_MeshSlot::elemParentsPerFace, _FC_MeshSlot::elemParentsPerVert, _FC_MeshSlot::elemToEdgeConns, _FC_MeshSlot::elemToFaceConns, _FC_MeshSlot::elemToVertConns, _FC_MeshSlot::faceParentsPerVert, _FC_MeshSlot::faceToVertConns, _FC_MeshSlot::faceTypes, FC_AT_EDGE, FC_AT_FACE, fc_getReturnCodeText(), fc_getSeqSubsets(), fc_getSeqVariables(), fc_getSubsetInfo(), fc_getSubsets(), fc_getVariableInfo(), fc_getVariables(), FC_HANDLE_EQUIV, FC_INPUT_ERROR, FC_NULL_MESH, fc_printfErrorMessage, fc_printfLogMessage, fc_printfWarningMessage, fc_releaseSeqSubset(), fc_releaseSeqVariable(), fc_releaseSubset(), fc_releaseVariable(), FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numEdge, _FC_MeshSlot::numEdgePerVert, _FC_MeshSlot::numElement, _FC_MeshSlot::numElemNeighsViaEdge, _FC_MeshSlot::numElemNeighsViaFace, _FC_MeshSlot::numElemNeighsViaVert, _FC_MeshSlot::numElemPerEdge, _FC_MeshSlot::numElemPerFace, _FC_MeshSlot::numElemPerVert, _FC_MeshSlot::numFace, _FC_MeshSlot::numFacePerVert, _FC_MeshSlot::numVertex, _FC_MeshSlot::numVertNeighsViaEdge, _FC_MeshSlot::numVertPerFace, and _FC_MeshSlot::vertNeighsViaEdge.
Referenced by fc_releaseDataset(), and main().
  {
  int i;
  int *numSteps;
  FC_Subset *subsets, **seqSubsets;
  FC_Variable *variables, **seqVariables;
  _FC_MeshSlot* meshSlot;
  FC_AssociationType assoc;
  int usingEdge, usingFace, numSubset, numVar, numSeqVar, numSeqSub;
  // special case: releasing a null handle is not an error
  if ( FC_HANDLE_EQUIV(mesh, FC_NULL_MESH)) {
    fc_printfWarningMessage("Releasing FC_NULL_MESH");
    return FC_SUCCESS;
  }
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Cleaning up mesh '%s'", meshSlot->header.name);
  // call release on children subsets & variables
  // also note whether any children use edges or faces
  usingEdge = 0;
  usingFace = 0;
  fc_getSubsets(mesh, &numSubset, &subsets);
  for (i = 0; i < numSubset; i++) {
    fc_releaseSubset(subsets[i]);
    fc_getSubsetInfo(subsets[i], NULL, NULL, &assoc);
    if (assoc == FC_AT_EDGE)
      usingEdge = 1;
    else if (assoc == FC_AT_FACE)
      usingFace = 1;
  }
  free(subsets);
  fc_getSeqSubsets(mesh, &numSeqSub, &numSteps, &seqSubsets);
  for (i = 0; i < numSeqSub; i++) {
    fc_releaseSeqSubset(numSteps[i], seqSubsets[i]);
    fc_getSubsetInfo(seqSubsets[i][0], NULL, NULL, &assoc);
    if (assoc == FC_AT_EDGE)
      usingEdge = 1;
    else if (assoc == FC_AT_FACE)
      usingFace = 1;
  }
  free(numSteps);
  for (i = 0; i < numSeqSub; i++)
    free(seqSubsets[i]);
  free(seqSubsets);
  fc_getVariables(mesh, &numVar, &variables);
  for (i = 0; i < numVar; i++) {
    fc_releaseVariable(variables[i]);
    fc_getVariableInfo(variables[i], NULL, NULL, &assoc, NULL, NULL);
    if (assoc == FC_AT_EDGE)
      usingEdge = 1;
    else if (assoc == FC_AT_FACE)
      usingFace = 1;
  }
  free(variables);
  fc_getSeqVariables(mesh, &numSeqVar, &numSteps, &seqVariables);
  for (i = 0; i < numSeqVar; i++) {
    fc_releaseSeqVariable(numSteps[i], seqVariables[i]);
    fc_getVariableInfo(seqVariables[i][0], NULL, NULL, &assoc, NULL, NULL);
    if (assoc == FC_AT_EDGE)
      usingEdge = 1;
    else if (assoc == FC_AT_FACE)
      usingFace = 1;
  }
  free(numSteps);
  for (i = 0; i < numSeqVar; i++)
    free(seqVariables[i]);
  free(seqVariables);
  // remove coords & conns if this slot is committed (they can be reloaded)
  if (meshSlot->header.committed == 1) {
    free(meshSlot->coords);
    meshSlot->coords = NULL;
    free(meshSlot->elemToVertConns);
    meshSlot->elemToVertConns = NULL;
  }
  //-- remove parent lists
  free(meshSlot->numEdgePerVert);
  meshSlot->numEdgePerVert = NULL;
  if (meshSlot->edgeParentsPerVert)
      for (i = 0; i < meshSlot->numVertex; i++)
        free(meshSlot->edgeParentsPerVert[i]);
  free(meshSlot->edgeParentsPerVert);
  meshSlot->edgeParentsPerVert = NULL;
  //--
  free(meshSlot->numFacePerVert);
  meshSlot->numFacePerVert = NULL;
  if (meshSlot->faceParentsPerVert)
    for (i = 0; i < meshSlot->numVertex; i++)
      free(meshSlot->faceParentsPerVert[i]);
  free(meshSlot->faceParentsPerVert);
  meshSlot->faceParentsPerVert = NULL;
  //--
  free(meshSlot->numElemPerVert);
  meshSlot->numElemPerVert = NULL;
  if (meshSlot->elemParentsPerVert)
    for (i = 0; i < meshSlot->numVertex; i++)
      free(meshSlot->elemParentsPerVert[i]);
  free(meshSlot->elemParentsPerVert);
  meshSlot->elemParentsPerVert = NULL;
  //--
  free(meshSlot->numElemPerEdge);
  meshSlot->numElemPerEdge = NULL;
  if (meshSlot->elemParentsPerEdge)
    for (i = 0; i < meshSlot->numEdge; i++)
      free(meshSlot->elemParentsPerEdge[i]);
  free(meshSlot->elemParentsPerEdge);
  meshSlot->elemParentsPerEdge = NULL;
  //--
  free(meshSlot->numElemPerFace);
  meshSlot->numElemPerFace = NULL;
  if (meshSlot->elemParentsPerFace)
    for (i = 0; i < meshSlot->numFace; i++)
      free(meshSlot->elemParentsPerFace[i]);
  free(meshSlot->elemParentsPerFace);
  meshSlot->elemParentsPerFace = NULL;
  //-- remove neighbor lists
  free(meshSlot->numVertNeighsViaEdge);
  meshSlot->numVertNeighsViaEdge = NULL;
  if (meshSlot->vertNeighsViaEdge)
    for (i = 0; i < meshSlot->numVertex; i++)
      free(meshSlot->vertNeighsViaEdge[i]);
  free(meshSlot->vertNeighsViaEdge);
  meshSlot->vertNeighsViaEdge = NULL;
  //--
  free(meshSlot->numElemNeighsViaVert);
  meshSlot->numElemNeighsViaVert = NULL;
  if (meshSlot->elemNeighsViaVert)
    for (i = 0; i < meshSlot->numElement; i++)
      free(meshSlot->elemNeighsViaVert[i]);
  free(meshSlot->elemNeighsViaVert);
  meshSlot->elemNeighsViaVert = NULL;
  //--
  free(meshSlot->numElemNeighsViaEdge);
  meshSlot->numElemNeighsViaEdge = NULL;
  if (meshSlot->elemNeighsViaEdge)
    for (i = 0; i < meshSlot->numElement; i++)
      free(meshSlot->elemNeighsViaEdge[i]);
  free(meshSlot->elemNeighsViaEdge);
  meshSlot->elemNeighsViaEdge = NULL;
  //--
  free(meshSlot->numElemNeighsViaFace);
  meshSlot->numElemNeighsViaFace = NULL;
  if (meshSlot->elemNeighsViaFace)
    for (i = 0; i < meshSlot->numElement; i++)
      free(meshSlot->elemNeighsViaFace[i]);
  free(meshSlot->elemNeighsViaFace);
  meshSlot->elemNeighsViaFace = NULL;
  // if no subsets or variables use edges or faces, conns & associated data
  // do this last because we might want numEdge or numFace
  if (!usingEdge) {
    free(meshSlot->edgeToVertConns);
    meshSlot->edgeToVertConns = NULL;
    free(meshSlot->elemToEdgeConns);
    meshSlot->elemToEdgeConns = NULL;
    //-- set edges back to "unknown"
    meshSlot->numEdge = -1;
  }
  if (!usingFace) {
    free(meshSlot->faceTypes);
    meshSlot->faceTypes = NULL;
    free(meshSlot->numVertPerFace);
    meshSlot->numVertPerFace = NULL;
    free(meshSlot->faceToVertConns);
    meshSlot->faceToVertConns = NULL;
    free(meshSlot->elemToFaceConns);
    meshSlot->elemToFaceConns = NULL;
    free(meshSlot->elemFaceOrients);
    meshSlot->elemFaceOrients = NULL;
    //-- set faces back to "unknown"
    meshSlot->numFace = -1;
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_setMeshCoords (FC_Mesh mesh, int dim, int numVertex, double * coords)
Set the mesh coordinates by copy.
Description:
Set the coordinate values for the vertices in a mesh. The dim parameter is the number of spatial dimensions a vertex exists in. The coords array should contain dim*numVertex floating point numbers. The order is interleaved, that is your give all coordinates values for each vertex (e.g. XYZXYZ ...).
This routine makes a copy of the vertices for the library, so the user remains responsible for freeing the original array. If you would like to give the coordinates array to the mesh instead of just copying them, use fc_setMeshCoordsPtr().
You cannot set coords if they already exist.
Modifications:
Nancy Collins Created.
12/09/03 WSK Changed so that it creates a coordinate variable
09/13/04 WSK Changed so you cannot reset coords
Parameters:
mesh input - mesh handle
dim input - number of dimensions in 1 vertex
numVertex input - vertex count
coords input - array of vertex data
Definition at line 193 of file mesh.c.
References _fc_getMeshSlot(), _FC_SlotHeader::committed, _FC_MeshSlot::coords, _FC_MeshSlot::dim, FC_ERROR, fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, and _FC_MeshSlot::numVertex.
Referenced by fc_convertTreeToMesh(), fc_copyMesh(), fc_createBoundingBoxMesh(), fc_saveSkeleton(), and setupDataset().
  {
  _FC_MeshSlot *meshSlot;
  // NOTE!: if you change stuff here, also change fc_setSetMeshCoordsPtr()
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || dim < 1 || dim > 3 || numVertex < 1 ||
      coords == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // a little more checking -- can't overwrite coords
  if (meshSlot->coords != NULL || meshSlot->header.committed == 1) {
    fc_printfErrorMessage("Coords already exist on mesh '%s'",
                          meshSlot->header.name);
    return FC_ERROR;
  }
  // log message
  fc_printfLogMessage("Setting vertex coords on mesh '%s'",
                      meshSlot->header.name);
  // copy meta data
  meshSlot->numVertex = numVertex;
  meshSlot->dim = dim;
  // big data
  meshSlot->coords = malloc(sizeof(double) * numVertex * dim);
  if (meshSlot->coords == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  memcpy(meshSlot->coords, coords, sizeof(double)*numVertex*dim);
  return FC_SUCCESS;
}
FC_ReturnCode fc_setMeshCoordsPtr (FC_Mesh mesh, int dim, int numVertex, double * coords)
Set the pointer to the mesh coordinates.
Description:
Set the coordinate values for the vertices in a mesh. The dim parameter is the number of spatial dimensions a vertex exists in. The coords array should contain dim*numVertex floating point numbers. The order is interleaved, that is your give all coordinates values for each vertex (e.g. XYZXYZ ...).
This routine passes the coords array directly to the library, so the user no longer has responsibility of the original buffer. If you would like to keep the coords array, you should use fc_setMeshCoords() instead which makes a copy of the coords array.
You cannot set coords if they already exist.
Modifications:
10/01/04 WSK, created.
Parameters:
mesh input - mesh handle
dim input - number of dimensions in 1 vertex
numVertex input - vertex count
coords input - array of vertex data
Definition at line 259 of file mesh.c.
References _fc_getMeshSlot(), _FC_SlotHeader::committed, _FC_MeshSlot::coords, _FC_MeshSlot::dim, FC_ERROR, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, and _FC_MeshSlot::numVertex.
Referenced by _fc_makeMeshFromFiles(), fc_createSimpleHexMesh(), fc_createSphereMesh(), fc_createSubsetMesh(), and main().
  {
  _FC_MeshSlot *meshSlot;
  // NOTE!: if you change stuff here, also change fc_setSetMeshCoords()
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || dim < 1 || dim > 3 || numVertex < 1 ||
      coords == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // a little more checking -- can't overwrite coords
  if (meshSlot->coords != NULL || meshSlot->header.committed == 1) {
    fc_printfErrorMessage("Coords already exist on mesh '%s'",
                          meshSlot->header.name);
    return FC_ERROR;
  }
  // log message
  fc_printfLogMessage("Setting vertex coords on mesh '%s'",
                      meshSlot->header.name);
  // copy meta data
  meshSlot->numVertex = numVertex;
  meshSlot->dim = dim;
  // big data
  meshSlot->coords = coords;
  return FC_SUCCESS;
}
FC_ReturnCode fc_setMeshElementConns (FC_Mesh mesh, FC_ElementType elemType, int numElem, int * connectivities)
Set the mesh element to vertex connectivities by copy.
Description:
Set the element to vertex connectivities for the mesh. Meshes can only be made of one element type and the connectivity array should be numElem*(number of vertices per element) long. The order is interleave, that is you give the vertex IDs for each element (e.g. E1V1 E1V2 ... E1V6 E2V1 E2V2 ... E2V6 E3V1 ...).
This routine makes a copy of the conns for the library, so the user remains responsible for freeing the original array. If you would like to give the conns array to the mesh instead of just copying them, use fc_setMeshElementConnsPtr().
You cannot set conns if they already exist.
Modifications:
Nancy Collins, Created.
09/13/04 WSK Changed so you cannot reset conns
Parameters:
mesh input - mesh handle
elemType input - element type
numElem input - count of elements
connectivities input - array of vertex IDs for each element
Definition at line 321 of file mesh.c.
References _fc_getMeshSlot(), _FC_SlotHeader::committed, _FC_MeshSlot::elemToVertConns, _FC_MeshSlot::elemType, FC_ERROR, FC_ET_MIXED, FC_ET_UNKNOWN, fc_getElementTypeNumVertex(), fc_getElementTypeTopoDim(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isElementTypeValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numElement, and _FC_MeshSlot::topodim.
Referenced by fc_convertTreeToMesh(), fc_copyMesh(), fc_createBoundingBoxMesh(), fc_saveSkeleton(), and main().
  {
  //FC_ReturnCode rc;
  int num;
  _FC_MeshSlot *meshSlot;
  // NOTE!: if you change stuff here, also change fc_setSetMeshElementConnsPtr()
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || numElem < 1 || !fc_isElementTypeValid(elemType) ||
      elemType == FC_ET_UNKNOWN || elemType == FC_ET_MIXED ||
      connectivities == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // a little more checking -- can't overwrite conns
  if (meshSlot->elemToVertConns != NULL || meshSlot->header.committed == 1) {
    fc_printfErrorMessage("Elem-to-vert conns already exist on mesh '%s'",
                          meshSlot->header.name);
    return FC_ERROR;
  }
  // log message
  fc_printfLogMessage("Setting elements on mesh '%s'", meshSlot->header.name);
  // copy meta data
  meshSlot->numElement = numElem;
  meshSlot->elemType = elemType;
  meshSlot->topodim = fc_getElementTypeTopoDim(elemType);
  // copy element buffer
  num = numElem * fc_getElementTypeNumVertex(elemType);
  meshSlot->elemToVertConns = malloc(sizeof(int) * num);
  if (meshSlot->elemToVertConns == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  memcpy(meshSlot->elemToVertConns, connectivities, sizeof(int)*num);
  return FC_SUCCESS;
}
FC_ReturnCode fc_setMeshElementConnsPtr (FC_Mesh mesh, FC_ElementType elemType, int numElem, int * connectivities)
Set the pointer to the mesh element connectivities.
Description:
Set the element to vertex connectivities for the mesh. Meshes can only be made of one element type and the connectivity array should be numElem*(number of vertices per element) long. The order is interleave, that is you give the vertex IDs for each element (e.g. E1V1 E1V2 ... E1V6 E2V1 E2V2 ... E2V6 E3V1 ...).
This routine passes the conns array directly to the library, so the user no longer has responsibility of the original buffer. If you would like to keep the conns array, you should use fc_setMeshElementConns() instead which makes a copy of the conns array.
You cannot set conns if they already exist.
Modifications:
10/01/04 WSK, created.
Parameters:
mesh input - mesh handle
elemType input - element type
numElem input - count of elements
connectivities input - array of vertex IDs for each element
Definition at line 391 of file mesh.c.
References _fc_getMeshSlot(), _FC_SlotHeader::committed, _FC_MeshSlot::elemToVertConns, _FC_MeshSlot::elemType, FC_ERROR, FC_ET_MIXED, FC_ET_UNKNOWN, fc_getElementTypeTopoDim(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isElementTypeValid(), fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numElement, and _FC_MeshSlot::topodim.
Referenced by _fc_makeMeshFromFiles(), fc_createSimpleHexMesh(), fc_createSphereMesh(), fc_createSubsetMesh(), and main().
  {
  _FC_MeshSlot *meshSlot;
  // NOTE!: if you change stuff here, also change fc_setSetMeshElementConns()
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || numElem < 1 || !fc_isElementTypeValid(elemType) ||
      elemType == FC_ET_UNKNOWN || elemType == FC_ET_MIXED ||
      connectivities == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // a little more checking -- can't overwrite conns
  if (meshSlot->elemToVertConns != NULL || meshSlot->header.committed == 1) {
    fc_printfErrorMessage("Elem-to-vert conns already exist on mesh '%s'",
                          meshSlot->header.name);
    return FC_ERROR;
  }
  // log message
  fc_printfLogMessage("Setting elements on mesh '%s'", meshSlot->header.name);
  // copy meta data
  meshSlot->numElement = numElem;
  meshSlot->elemType = elemType;
  meshSlot->topodim = fc_getElementTypeTopoDim(elemType);
  // copy element buffer
  meshSlot->elemToVertConns = connectivities;
  return FC_SUCCESS;
}
FC_ReturnCode fc_setSphereDisplacementVariable (FC_Variable displacement_var, FC_Coords new_center, double new_radius)
Update a displacement variable for a sphere to have a new center and radius.
Description:
This function sets a displacement variable for a sphere mesh so that it reflects a new center/radius for the sphere. This operation is useful for tracking the size and location of a feature as time progresses.
Modifications:
04/08/2008 CDU Created
Parameters:
displacement_var Input - the displacement variable to be adjusted
new_center Input - new coordinates for center of sphere
new_radius Input - new radius for sphere
Definition at line 2091 of file mesh.c.
References _fc_setSphereCoords(), FC_AT_VERTEX, FC_DT_DOUBLE, fc_getMeshCoordsPtr(), fc_getMeshFromVariable(), fc_getMeshInfo(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isVariableValid(), fc_lteqd(), FC_MEMORY_ERROR, FC_MT_VECTOR, fc_printfErrorMessage, fc_setVariableDataPtr(), and FC_SUCCESS.
Referenced by fc_saveSkeleton().
 {
  FC_Mesh mesh;
  int dim, numVertex;
  FC_ReturnCode rc;
  double *orig_coords; //ro
  double *new_coords;
  int i;
  //Check input
  if(!fc_isVariableValid(displacement_var) || fc_lteqd(new_radius,0.0) || !new_center){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  //Get basic info from variable and it's mesh
  rc=fc_getMeshFromVariable(displacement_var, &mesh);
  if(rc!=FC_SUCCESS) return rc;
  rc=fc_getMeshInfo(mesh, NULL, &dim, &numVertex, NULL, NULL);
  if(rc!=FC_SUCCESS) return rc;
  rc=fc_getMeshCoordsPtr(mesh, &orig_coords);
  if(rc!=FC_SUCCESS) return rc;
  //Create space for data
  new_coords = (double *)malloc(dim*numVertex*sizeof(double));
  if(!new_coords){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  //Fill new_coords with the proper values
  rc=_fc_setSphereCoords(numVertex, new_center, new_radius, new_coords);
  if(rc!=FC_SUCCESS){
    free(new_coords);
    return rc;
  }
  //Record the difference
  for(i=0; i<dim*numVertex; i++){
    new_coords[i] = new_coords[i] - orig_coords[i];
  }
  //new_coords now done. Have it absorbed into variable
  rc=fc_setVariableDataPtr(displacement_var, numVertex, dim,
                  FC_AT_VERTEX, FC_MT_VECTOR, FC_DT_DOUBLE,
                  new_coords);
  if(rc!=FC_SUCCESS) {
    free(new_coords);
    return rc;
  }
  return FC_SUCCESS;
}