FCLib: Threshold
Threshold
[FCLib API]
Detailed Description
Apply thresholds to variables.
Functions
FC_ReturnCode fc_createThresholdSubset (FC_Variable variable, char *compare_str, double ref_value, char *subsetName, FC_Subset *subset)
Create thresholded region.
FC_ReturnCode fc_createThresholdRangeSubset (FC_Variable variable, char *compare1, double ref_value1, char *operation, char *compare2, double ref_value2, char *subsetName, FC_Subset *subset)
Create subset according to range conditions.
Function Documentation
FC_ReturnCode fc_createThresholdRangeSubset (FC_Variable variable, char * compare1, double ref_value1, char * operation, char * compare2, double ref_value2, char * subsetName, FC_Subset * subset)
Create subset according to range conditions.
Description:
Creates a subset of the entities that pass the test specified by the given range condition; that is the reference variable satisfies two comparisons connected by a logical operator. Comparisons are defined by a string, with possible values: compare = ">",">=", "==","<","<=", "!=" . The operation string connecting the two comparisons can be: operation = "OR"="or"="||", "AND"="and"="&&"="&","XOR"="xor"="^" (exclusive or) .
Example: to get the range ((var >= a) && (var < b))
fc_markThresholdedRange(var, ">=", a, "&&", "<", "b", &subsetName, &subset);
Modifications:
Nancy Collins Created.
11/26/03 WSK added return of association type & cleaned up
04/12/04 RM, rewritten, added comparison strings to input argument list and an operation string to link both comparisons. f.e. we can now check condition: variable "<" reference1 && variable ">=" reference2.
06/25/04 RM changed to operate on subsets and return subset instead of marked list
Parameters:
variable input - variable
compare1 input - comparison (string eg.">") with reference1
ref_value1 input - reference data value
operation input - operation that links the two comparisons eg. "OR","AND","XOR", "||","&&" etc.
compare2 input - comparison (eg."<=") with reference2
ref_value2 input - reference data value
subsetName input - new subset's name
subset output - subset with thresholded elements
Definition at line 224 of file threshold.c.
References fc_createSubsetIntersection(), fc_createThresholdSubset(), fc_deleteSubset(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_isVariableGlobal(), fc_isVariableValid(), FC_NULL_SUBSET, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
  {
  FC_ReturnCode rc ;
  FC_Subset subset1;
  FC_Subset subset2;
  char *subset1Name = "temp_subset", *subset2Name ="temp_subset";
  // default return
  if (subset)
    *subset = FC_NULL_SUBSET;
  // check input
  if (!fc_isVariableValid(variable) || fc_isVariableGlobal(variable) ||
      !compare1 || !operation || !compare2 || !subsetName || !subset) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Creating new threshold range subset '%s'",
                subsetName);
  // for each comparison call fc_getThreshSubset() function, creating new
  // subsets, then perform operation on the two subsets
  rc = fc_createThresholdSubset(variable, compare1, ref_value1, subset1Name,
                    &subset1);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_createThresholdSubset(variable, compare2, ref_value2, subset2Name,
                    &subset2);
  if (rc != FC_SUCCESS) {
    fc_deleteSubset(subset1);
    return rc;
  }
  // perform desired operation on the two subsets
  rc = fc_createSubsetIntersection(subset1, operation, subset2, subsetName,
       subset);
  // delete temporary subsets
  fc_deleteSubset(subset1);
  fc_deleteSubset(subset2);
  // report error of intersection operation
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("error creating subset intersection.");
    return rc;
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_createThresholdSubset (FC_Variable variable, char * compare_str, double ref_value, char * subsetName, FC_Subset * subset)
Create thresholded region.
Description:
Takes a variable and a reference value, and creates a subset of entities whose data values pass the threshold test given by the comparison string. Possible values of this string: ">","<",">=","<=","=","==","=>","=<" .
Modifications:
Nancy Collins Created.
11/26/03 WSK added return of association type & cleaned up
04/12/04 RM, changed input int compare, to string (one of "<",">" "<=", ">=","=<","=>","=","=="). Changed comparison section to do all comparisons on doubles.
06/15/04 RM changed output to return subset instead of marked list = 11/8/04 WSK simplified internals. Added '!=' case.
Parameters:
variable input - variable
compare_str input - compare string (eg. "<","<=", etc.)
ref_value input - reference data value
subsetName input - new subset's name
subset output - subset with thresholded elements
Definition at line 88 of file threshold.c.
References fc_addMemberToSubset(), fc_createSubset(), FC_DT_DOUBLE, FC_DT_FLOAT, FC_DT_INT, fc_eq(), FC_ERROR, fc_getDataTypeText(), fc_getMeshFromVariable(), fc_getReturnCodeText(), fc_getVariableDataPtr(), fc_getVariableInfo(), fc_gt(), fc_gteq(), FC_INPUT_ERROR, fc_isVariableGlobal(), fc_isVariableValid(), fc_lt(), fc_lteq(), fc_neq(), FC_NULL_SUBSET, fc_printfErrorMessage, fc_printfLogMessage, and FC_SUCCESS.
Referenced by fc_createThresholdRangeSubset(), find_and_print_bbs(), getDeathThresholdSubset(), main(), and processOneVar().
  {
  FC_ReturnCode rc;
  int i;
  int numDataPoint, numComp;
  void *datap;
  double epsilon, minimum;
  FC_DataType datatype;
  FC_AssociationType assoc;
  FC_Mesh mesh;
  // comparisons
  int (*compare)(double, double, double, double);
  // default return
  if (subset)
    *subset = FC_NULL_SUBSET;
  // check input (can't be a global var)
  if (!fc_isVariableValid(variable) || fc_isVariableGlobal(variable) ||
      !compare_str || !subsetName || !subset) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // determine comparison
  if (!strcmp(compare_str, "=") || !strcmp(compare_str, "=="))
    compare = fc_eq;
  else if (!strcmp(compare_str, "!=") || !strcmp(compare_str, "=!"))
    compare = fc_neq;
  else if (!strcmp(compare_str, "<"))
    compare = fc_lt;
  else if (!strcmp(compare_str, "<=") || !strcmp(compare_str, "=<"))
    compare = fc_lteq;
  else if (!strcmp(compare_str, ">"))
    compare = fc_gt;
  else if (!strcmp(compare_str, ">=") || !strcmp(compare_str, "=>"))
    compare = fc_gteq;
  else {
    fc_printfErrorMessage("Unknown comparison string: '%s'", compare_str);
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Creating new threshold subset '%s'", subsetName);
  // get variable info
  rc = fc_getVariableInfo(variable, &numDataPoint, &numComp, &assoc, NULL,
                 &datatype);
  if (rc != FC_SUCCESS)
    return rc;
  // more checking
  if (numComp > 1) {
     fc_printfErrorMessage("can only do variables with 1 component.");
    return FC_ERROR;
  }
  if (datatype == FC_DT_INT || datatype == FC_DT_DOUBLE) {
    epsilon = DBL_EPSILON;
    minimum = DBL_MIN;
  }
  else if (datatype == FC_DT_FLOAT) {
    epsilon = FLT_EPSILON;
    minimum = FLT_MIN;
  }
  else {
    fc_printfErrorMessage("Can't do data type '%s'.",
                 fc_getDataTypeText(datatype));
    return FC_ERROR;
  }
  rc = fc_getVariableDataPtr(variable, &datap);
  if (rc != FC_SUCCESS) {
    fc_printfErrorMessage("error getting data.");
    return rc;
  }
  // get mesh that the variable belongs to
  rc = fc_getMeshFromVariable(variable, &mesh);
  if (rc != FC_SUCCESS)
    return rc;
  // create new subset
  rc = fc_createSubset(mesh, subsetName, assoc, &(*subset));
  if (rc != FC_SUCCESS)
    return rc;
  // determine subset members
  for (i = 0; i < numDataPoint; i++) {
    double value;
    if (datatype == FC_DT_INT)
      value = ((int*)datap)[i];
    else if (datatype == FC_DT_FLOAT)
      value = ((float*)datap)[i];
    else if (datatype == FC_DT_DOUBLE)
      value = ((double*)datap)[i];
    if (compare(value, ref_value, epsilon, minimum))
      fc_addMemberToSubset(*subset, i);
  }
  return FC_SUCCESS;
}