FCLib: Table (Private)
Table (Private)
[Data Interface]
Detailed Description
Routines for manipulating the table data structures.
Description:
The primary data structures for FCLib are managed as "tables" (arrays) of "slots" (structs), which are structures that hold metadata and data corresponding to that data entity type (i.e. _FC_DsSlot, _FC_SeqSlot, _FC_MeshSlot, _FC_SubSlot, _FC_VarSlot). For more information about what information each type of slot holds, see the documentation on the struct definitions.
All slot types have a common header (_FC_SlotHeader) as the their first member. This allows us to make some general purpose utility routines which work on any slot type. The header also contains information about the state of a slot like whether it can be modified on disk (writable), and whether the disk version matches the current version (committed).
Any table consists of an array of pointers to the appropriate slot type. The tables are expanded as necessary by doubling the number of entries at a time. Entries start with a NULL value and are allocated as needed. The slots of "Deleted" slots are freed and set back to NULL.
Each table has supporting data structures - xTableSize is the length of the table; xOpenSlots is a sorted array of available slots.
Generic versions of basic table operations are defined in this module (like get a new slot or delete a slot). These basic operations take a specific kind of table and the necessary supporting information. To simplify matters, each kind of data (dataset, mesh, etc) has a wrapper that does the operation on that type of table (e.g. _fc_getNewDsSlot() does _fc_getNewSlot() with the dataset table).
The data tables are not exposed at the user level and are instead manipulated by Handles which contain just enough information for called routines to locate the appropriate slot in the tables (i.e. the index into the table and a unique sequence number to make sure the slot still refers to the same entity).
Data Structures
struct _FC_SlotHeader
Slot Header.
Defines
#define INDENT_STR " "
Indent string for _fc_printXTable() routines.
#define TABLE_DIVIDER_STRING "----------------------------------------------\n"
A string of hyphens to use as a table divider for _fc_printXTable() routines.
#define _FC_GET_HANDLE(handle, xSlot_pointer)
Get a handle from a table slot.
Functions
FC_ReturnCode _fc_setSlotHeaderName (_FC_SlotHeader *header, char *name)
Replaces the name for a slot header with a copy of the input.
void _fc_initSlotHeader (_FC_SlotHeader *header)
Initialize a table header.
void _fc_clearSlotHeader (_FC_SlotHeader *header)
Clear a slot header's.
void _fc_printSlotHeader (_FC_SlotHeader header)
Print the contents of an _FC_SlotHeader to stderr.
_FC_SlotHeader * _fc_getNewSlot (int *tableSize, _FC_SlotHeader ***table, FC_SortedIntArray *openSlots, int slotSize)
Get an empty slot from table.
int _fc_isHandleValid (int slotID, int uID, int tableSize, _FC_SlotHeader **table)
Check that a handle is valid.
_FC_SlotHeader * _fc_getSlot (int slotID, int tableSize, _FC_SlotHeader **table)
Get a slot by ID.
FC_ReturnCode _fc_deleteSlot (int slotID, int tableSize, _FC_SlotHeader **table, FC_SortedIntArray *openSlots)
Delete the contents of a slot.
Variables
static int next_uID = 1
Master unique ID.
Define Documentation
#define _FC_GET_HANDLE (handle, xSlot_pointer)
Value:
((handle).slotID = (xSlot_pointer)->header.slotID, \
           (handle).uID = (xSlot_pointer)->header.uID )
Get a handle from a table slot.
Description:
Copies values from the table slot into the handle Warning! No type checking
Definition at line 76 of file tableP.h.
Referenced by fc_copyDataset(), fc_createDataset(), fc_createGlobalSeqVariable(), fc_createGlobalVariable(), fc_createMesh(), fc_createSeqSubset(), fc_createSequence(), fc_createSeqVariable(), fc_createSubset(), fc_createVariable(), fc_finalLibrary(), fc_getDatasetByName(), fc_getDatasets(), fc_getGlobalSeqVariableByName(), fc_getGlobalSeqVariables(), fc_getGlobalVariableByName(), fc_getGlobalVariables(), fc_getMeshByName(), fc_getMeshCoordsAsVariable(), fc_getMeshes(), fc_getSeqSubsetByName(), fc_getSeqSubsets(), fc_getSequenceByName(), fc_getSequences(), fc_getSeqVariableByName(), fc_getSeqVariables(), fc_getSubsetByName(), fc_getSubsets(), fc_getVariableByName(), and fc_getVariables().
#define INDENT_STR " "
Indent string for _fc_printXTable() routines.
Definition at line 57 of file tableP.h.
Referenced by fc_printDataset(), fc_printMesh(), fc_printSeqSubsetRange(), fc_printSequence(), fc_printSeqVariableRange(), fc_printSubset(), fc_printSubsetOfMesh(), fc_printSubsetOfVariable(), fc_printVariable(), get_and_print_stats(), and main().
#define TABLE_DIVIDER_STRING "----------------------------------------------\n"
A string of hyphens to use as a table divider for _fc_printXTable() routines.
Definition at line 64 of file tableP.h.
Referenced by _fc_printDsTable(), _fc_printMeshTable(), _fc_printSeqTable(), _fc_printSubTable(), and _fc_printVarTable().
Function Documentation
void _fc_clearSlotHeader (_FC_SlotHeader * header)
Clear a slot header's.
Description:
Releases all dynamically allocated resources in a table header, and reinitializes all members.
Modifications:
APR-29-2003 W Koegler Created.
2003-APR-31 W Koegler Made more comprehensive
Parameters:
header input/output - the slotheader to clear
Definition at line 195 of file table.c.
References _fc_initSlotHeader(), _FC_SlotHeader::name, and _FC_SlotHeader::uID.
Referenced by _fc_clearDsSlot(), _fc_clearMeshSlot(), _fc_clearSeqSlot(), _fc_clearSubSlot(), and _fc_clearVarSlot().
  {
  if (header != NULL) {
    // free dynamically allocated arrays
    if (header->name)
      free(header->name);
    // reinitialize
    _fc_initSlotHeader(header);
    // make "empty"
    header->uID = -1;
    // do NOT change header->slotID: for as long as the slot exists
    // it's slot ID is set and should stay the same
  }
}
FC_ReturnCode _fc_deleteSlot (int slotID, int tableSize, _FC_SlotHeader ** table, FC_SortedIntArray * openSlots)
Delete the contents of a slot.
Description:
If the slot exists, deletes the memory associated with that slot and add the slotID to the openSlots lists.
Assumes that dynamic data in the slot has already been "cleared".
Modifications:
12/20/05 WSD Created.
Parameters:
slotID input: slot id
tableSize input: the table size
table input: the table
openSlots input/output: the open slots
Definition at line 384 of file table.c.
References fc_addIntToSortedIntArray(), fc_printfErrorMessage, and FC_SUCCESS.
Referenced by _fc_deleteDsSlot(), _fc_deleteMeshSlot(), _fc_deleteSeqSlot(), _fc_deleteSubSlot(), and _fc_deleteVarSlot().
                                     : slot id  */
   int tableSize,          /**< input: the table size  */
   _FC_SlotHeader** table, /**< input: the table */
   FC_SortedIntArray* openSlots  /**< input/output: the open slots */
) {
  int ret;
  if (slotID >= 0 && slotID < tableSize && table[slotID]) {
    free(table[slotID]);
    table[slotID] = NULL;
    ret = fc_addIntToSortedIntArray(openSlots, slotID);
    if (ret < 0) {
      fc_printfErrorMessage("Failed to add ID to sia");
      return ret; // an error occured
    }
    else if (ret == 0) {
      fprintf(stderr, "***developer note: Algorithmic error! shouldn't reach here!");
      fflush(NULL);
    }
  }
  return FC_SUCCESS;
}
_FC_SlotHeader* _fc_getNewSlot (int * tableSize, _FC_SlotHeader *** table, FC_SortedIntArray * openSlots, int slotSize)
Get an empty slot from table.
Description:
Code to get an empty slot from any type of table. It first checks for an unused spot (either the entry is NULL or has a unique ID less than 0). If there are no unused slots, it grows the table by factor of 2. If the unused slot is NULL, it allocates a new slot.
Modifications:
5/11/04 WSK Moved common code from _fc_getNewDsSlot(), _fc_getNewSeqSlot(), _fc_getNewMeshSlot() & _fc_getNewVarSlot() to here.
Parameters:
tableSize input/output: pointer to table size
table input/output: pointer to table
openSlots input/output: sia holds indices of available slots
slotSize input: size of a slot
Definition at line 255 of file table.c.
References _fc_initSlotHeader(), fc_addIntToSortedIntArray(), fc_getReturnCodeText(), FC_MEMORY_ERROR, fc_popSortedIntArrayFront(), fc_printfErrorMessage, next_uID, FC_SortedIntArray::numVal, and FC_SortedIntArray::vals.
Referenced by _fc_getNewDsSlot(), _fc_getNewMeshSlot(), _fc_getNewSeqSlot(), _fc_getNewSubSlot(), and _fc_getNewVarSlot().
                                              : pointer to table size  */
   _FC_SlotHeader*** table,  /**< input/output: pointer to table */
   FC_SortedIntArray* openSlots,     /**< input/output:  sia holds
                    indices of available slots */
   int slotSize              /**< input: size of a slot */
) {
  int i;
  int slotID, newSize, ret;
  void *temp;
  // get an unused slot
  if (openSlots->numVal > 0) {
    slotID = openSlots->vals[0];
    fc_popSortedIntArrayFront(openSlots);
  }
  else { // if an unused slot doesn't exist, make some more slots
    if (*tableSize == 0)
      newSize = 1;
    else
      newSize = 2*(*tableSize);
    temp = realloc(*table, newSize*sizeof(_FC_SlotHeader*));
    if (temp == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return NULL;
    }
    *table = temp;
    for (i = (*tableSize); i < newSize; i++)
      (*table)[i] = NULL;
    // NOTE! the ID of the first new slot doesn't get added to openSlots
    slotID = (*tableSize);
    for (i = newSize-1; i > (*tableSize); i--) {
      ret = fc_addIntToSortedIntArray(openSlots, i);
      if (ret < 0) {
     fc_printfErrorMessage("Failed to add key to sia, memory error?");
     return NULL; // an error occured
      }
      else if (ret == 0) {
     fprintf(stderr, "***developer note: Algorithmic error! shouldn't reach here!");
     fflush(NULL);
      }
    }
    (*tableSize) = newSize;
  }
  // allocate slot if necessary
  if ((*table)[slotID] == NULL) {
    (*table)[slotID] = malloc(slotSize);
    if ((*table)[slotID] == NULL) {
      fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
      return NULL;
    }
  }
  // setup the slot
  _fc_initSlotHeader((*table)[slotID]);
  (*table)[slotID]->slotID = slotID;
  (*table)[slotID]->uID = next_uID;
  next_uID++;
  return (*table)[slotID];
}
_FC_SlotHeader* _fc_getSlot (int slotID, int tableSize, _FC_SlotHeader ** table)
Get a slot by ID.
Description:
Returns a slot if it exists (exists means has some thing in it and therefore the uID will be 1 or greater. Otherwise returns NULL.
Modifications:
05/25/04 WSK Created.
Parameters:
slotID input: slot id
tableSize input: the table size
table input: the table
Definition at line 357 of file table.c.
Referenced by _fc_getDsSlotFromID(), _fc_getMeshSlotFromID(), _fc_getSeqSlotFromID(), _fc_getSubSlotFromID(), and _fc_getVarSlotFromID().
                                     : slot id  */
   int tableSize,          /**< input: the table size  */
   _FC_SlotHeader** table  /**< input: the table */
) {
  if (slotID < 0 || slotID >= tableSize || !table[slotID] ||
      table[slotID]->uID < 1)
    return NULL;
  else
    return table[slotID];
}
void _fc_initSlotHeader (_FC_SlotHeader * header)
Initialize a table header.
Description:
Sets all table header values to appropriate default values. Except the slot number and the unique ID which should only be set by _fc_new_xxxSlot.
Modifications: APR-29-2003 W Koegler Created. Moved code from getnextslot
Parameters:
header input - the slotheader to initialize
Definition at line 171 of file table.c.
References _FC_SlotHeader::committed, and _FC_SlotHeader::name.
Referenced by _fc_clearSlotHeader(), _fc_getNewSlot(), _fc_initDsSlot(), _fc_initMeshSlot(), _fc_initSeqSlot(), _fc_initSubSlot(), and _fc_initVarSlot().
  {
  if (header != NULL) {
    // header->slot is NOT changed
    // header->uID is NOT changed
    header->name = NULL;
    header->committed = 0;
  }
}
int _fc_isHandleValid (int slotID, int uID, int tableSize, _FC_SlotHeader ** table)
Check that a handle is valid.
Description:
Returns 1 if the handle is valid and 0 if it is not. Valid means that the object exists and that it has the same uID as the handle (this extra check is necessary because the slot may get reused, at which time the handle is invalid even though it refers to a real object).
Modifications:
05/25/04 WSK Created.
Parameters:
slotID input: slot id from a handle
uID input: unique id from a handle
tableSize input: the table size
table input: the table
Definition at line 332 of file table.c.
Referenced by _fc_getDsSlot(), _fc_getMeshSlot(), _fc_getSeqSlot(), _fc_getSubSlot(), _fc_getVarSlot(), fc_isDatasetValid(), fc_isMeshValid(), fc_isSequenceValid(), fc_isSubsetValid(), and fc_isVariableValid().
                                     : slot id from a handle  */
   int uID,                /**< input: unique id from a handle */
   int tableSize,          /**< input: the table size  */
   _FC_SlotHeader** table  /**< input: the table */
) {
  if (slotID < 0 || slotID >= tableSize || !table[slotID] ||
      table[slotID]->uID != uID)
    return 0;
  else
    return 1;
}
void _fc_printSlotHeader (_FC_SlotHeader header)
Print the contents of an _FC_SlotHeader to stderr.
Description:
This is a helper routine for the _fc_printXTable routines, used to print _FC_SlotHeader information (all table have an _FC_SlotHeader). It is meant to be called from these routines and wont' have pretty formatting if called on its own; but the info will be right.
Modifications:
Nancy Collins Created.
2003-NOV-13 WSK Fixed up.
12/03/03 WSK Fixed up some more.
Definition at line 229 of file table.c.
References _FC_SlotHeader::committed, _FC_SlotHeader::name, _FC_SlotHeader::slotID, and _FC_SlotHeader::uID.
Referenced by _fc_printDsTable(), _fc_printMeshTable(), _fc_printSeqTable(), _fc_printSubTable(), and _fc_printVarTable().
  {
  fprintf(stderr, "     name = '%s'\n", header.name);
  fprintf(stderr, "     slotID = %d, uID = %d, committed = %d\n",
          header.slotID, header.uID, header.committed);
  fflush(NULL);
}
FC_ReturnCode _fc_setSlotHeaderName (_FC_SlotHeader * header, char * name)
Replaces the name for a slot header with a copy of the input.
Description:
Takes a name, allocates space for the name (realloc if a name is already set) and copies it (user is still responsible for input char string).
This replaces the current name (and frees that memory). Make sure to call this only if header has been initialized at some point with header.name = NULL.
Modifications:
Nancy Collins Created.
Parameters:
header input/output - pointer to a slot header
name input - name to set
Definition at line 132 of file table.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, FC_MEMORY_ERROR, fc_printfErrorMessage, FC_SUCCESS, and _FC_SlotHeader::name.
Referenced by _fc_loadLSDynaDataset(), fc_changeDatasetName(), fc_changeMeshName(), fc_changeSeqSubsetName(), fc_changeSequenceName(), fc_changeSeqVariableName(), fc_changeSubsetName(), fc_changeVariableName(), fc_convertSeqSubsetToSubsets(), fc_convertSubsetsToSeqSubset(), fc_convertVariablesToSeqVariable(), fc_createDataset(), fc_createGlobalSeqVariable(), fc_createGlobalVariable(), fc_createMesh(), fc_createSeqSubset(), fc_createSequence(), fc_createSeqVariable(), fc_createSubset(), and fc_createVariable().
  {
  // check input
  if (!header || !name) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // delete the current name
  if (header->name)
    free(header->name);
  // copy the name
  header->name = malloc(strlen(name) + 1);
  if (header->name == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  strcpy(header->name, name);
  return FC_SUCCESS;
}
Variable Documentation
int next_uID = 1 [static]
Master unique ID.
Description:
Each slot has a unique ID which is checked against when dereferencing a handle. Each uID is only used once, so this master uID keeps track of the next available number. uIDs start at 1 and go up. (Start with 1 so anything initialized with 0 won't be accidentally o.k.
Definition at line 113 of file table.c.
Referenced by _fc_getNewSlot().