FCLib: (Private)
(Private)
[Mesh]
Data Structures
struct _EdgeBlob
Special data blob for sorting edges.
struct _FaceBlob
Special data blob for sorting faces.
struct _FC_MeshSlot
Mesh Slot Structure for the Mesh Table.
Other ways to get new meshes.
FC_ReturnCode _fc_setSphereCoords (int numVerts, FC_Coords center, double radius, double *coords)
Set coordinates for a sphere mesh.
Functions
FC_ReturnCode _fc_getMeshEdgeParentsOfVerticesPtr (FC_Mesh mesh, int **numEdgePerVert, int ***edgeParentsPerVert)
Return parent edges of the vertices.
FC_ReturnCode _fc_getMeshFaceParentsOfVerticesPtr (FC_Mesh mesh, int **numFacePerVert, int ***faceParentsPerVert)
Return parent faces of the vertices.
FC_ReturnCode _fc_getMeshElementParentsOfVerticesPtr (FC_Mesh mesh, int **numElemPerVert, int ***elemParentsPerVert)
Return parent elements of the vertices.
FC_ReturnCode _fc_getMeshElementParentsOfEdgesPtr (FC_Mesh mesh, int **numElemPerEdge, int ***elemParentsPerEdge)
Return parent elements of the edges.
FC_ReturnCode _fc_getMeshElementParentsOfFacesPtr (FC_Mesh mesh, int **numElemPerFace, int ***elemParentsPerFace)
Return parent elements of the faces.
FC_ReturnCode _fc_getMeshVertexNeighborsViaEdgePtr (FC_Mesh mesh, int **numVertNeighsViaEdge, int ***vertNeighsViaEdge)
Return vertex neighbors that share an edge.
FC_ReturnCode _fc_getMeshElementNeighborsViaVertexPtr (FC_Mesh mesh, int **numElemNeighsViaVert, int ***elemNeighsViaVert)
Return element neighbors that share an vertex.
FC_ReturnCode _fc_getMeshElementNeighborsViaEdgePtr (FC_Mesh mesh, int **numElemNeighsViaEdge, int ***elemNeighsViaEdge)
Return element neighbors that share an edge.
FC_ReturnCode _fc_getMeshElementNeighborsViaFacePtr (FC_Mesh mesh, int **numElemNeighsViaFace, int ***elemNeighsViaFace)
Return element neighbors that share an face.
FC_ReturnCode _fc_buildParents (FC_Mesh mesh, FC_AssociationType childType, FC_AssociationType parentType)
Build an arrays of parent IDs.
FC_ReturnCode _fc_buildEdgeConns (FC_Mesh mesh)
Build the edge info for the mesh.
static int _faceBlob_compare (const void *node1, const void *node2)
Compare two faces.
FC_ReturnCode _fc_buildFaceConns (FC_Mesh mesh)
Build the face info for the mesh.
FC_ReturnCode _fc_buildMeshVertexNeighborsViaEdge (FC_Mesh mesh)
Build the neighbor information for the vertices array.
FC_ReturnCode _fc_buildMeshElementNeighborsViaEntity (FC_Mesh mesh, FC_AssociationType sharedType)
Build element neighbors that share the specified entity type.
void _fc_initMeshSlot (_FC_MeshSlot *meshSlot)
Initialize a mesh slot.
void _fc_releaseMeshSlot (_FC_MeshSlot *meshSlotp)
Release non-necessary information in a mesh slot.
void _fc_clearMeshSlot (_FC_MeshSlot *meshSlotp)
Clear a mesh slot.
int _fc_getMeshTableSize ()
Get the size of the mesh table.
_FC_MeshSlot * _fc_getNewMeshSlot ()
Get an empty mesh slot from the mesh table.
_FC_MeshSlot * _fc_getMeshSlot (FC_Mesh mesh)
Get a mesh slot from a mesh handle.
_FC_MeshSlot * _fc_getMeshSlotFromID (int meshID)
Get a mesh slot based on ID.
FC_ReturnCode _fc_deleteMeshSlot (FC_Mesh mesh)
Delete the mesh slot associated with the mesh handle.
void _fc_printMeshTable (char *label)
Print the contents of the Mesh Table (meshTable) to stderr.
void _fc_freeMeshTable ()
Free all entries in the mesh table.
Variables
static int meshTableSize = 0
The number of allocated slots in the mesh table.
static _FC_MeshSlot ** meshTable = NULL
The mesh table.
static FC_SortedIntArray meshOpenSlots = { 0, 0, 0 }
The list of unused slots in the mesh table.
Function Documentation
static int _faceBlob_compare (const void * node1, const void * node2) [static]
Compare two faces.
Description:
To be used in this file (mesh.c) only for comparing faces. Expects faces to already be sorted so that smallest node ID is first and 2nd smallest vertex ID is next. (The order of the last 1 or 2 vertices is set by PATRAN ordering conventions.)
This method returns -1 if the first face's vertex IDs are smaller than the 2nd face's, 0 if the faces are the same; and 1 if the first face's vertex IDs are greater than the 2nd's.
Note, only the 1st 3 vertices are compared. In well behaved meshes, this should be suffient to compare faces. (I.e. we are assuming that quads will share 1, 2 or 4 vertices, but never just 3--if 3 are the same, all 4 will be the same. We are also assuming that tris will not be "inside a quad" and therefore share 3 vertices.)
Modifications:
10/10/2005 WSD. Promoted. Used to be inside _fc_buildFaces() but static functions not allowed inside funtions in gcc 4.0.
Definition at line 5199 of file mesh.c.
References _FaceBlob::vertexIDs.
Referenced by _fc_buildFaceConns().
{
  const _FaceBlob* faceNode1 = (const _FaceBlob*)node1;
  const _FaceBlob* faceNode2 = (const _FaceBlob*)node2;
  if (faceNode1->vertexIDs[0] < faceNode2->vertexIDs[0])
    return -1;
  else if (faceNode1->vertexIDs[0] > faceNode2->vertexIDs[0])
    return 1;
  else {
    if (faceNode1->vertexIDs[1] < faceNode2->vertexIDs[1])
      return -1;
    else if (faceNode1->vertexIDs[1] > faceNode2->vertexIDs[1])
      return 1;
    else {
      if (faceNode1->vertexIDs[2] < faceNode2->vertexIDs[2])
        return -1;
      else if (faceNode1->vertexIDs[2] > faceNode2->vertexIDs[2])
        return 1;
      else
        return 0;
    }
  }
};
FC_ReturnCode _fc_buildEdgeConns (FC_Mesh mesh)
Build the edge info for the mesh.
Description:
Finds the unique list of edges for the given set of elements. It also adds edgeIDs arrays to each element.
Assumes that all elements are the same type.
Modifications:
Wendy Koegler 4/02 Created
02/06/04 WSK, changed to return raw data arrays too.
07/09/04 WSK, added building of upward and downward connections to vertices and elements (so could get rid of _fc_guildUpwardsConns).
Parameters:
mesh The mesh to build stuff on.
Definition at line 5002 of file mesh.c.
References _fc_addEntryToSortedBlobArray(), _fc_getMeshSlot(), _fc_lookupBlobInSortedBlobArray(), FC_SortedBlobArray::blobs, _EdgeBlob::edgeID, _FC_MeshSlot::edgeToVertConns, _FC_MeshSlot::elemToEdgeConns, _EdgeBlob::endVert, FC_ERROR, FC_ET_HEX, FC_ET_LINE, FC_ET_MIXED, FC_ET_POINT, FC_ET_PRISM, FC_ET_PYRAMID, FC_ET_QUAD, FC_ET_TET, FC_ET_TRI, FC_ET_UNKNOWN, fc_freeSortedBlobArray(), fc_getElementTypeNumEdge(), fc_getElementTypeNumVertex(), fc_getElementTypeText(), fc_getMeshElementConnsPtr(), fc_getMeshInfo(), fc_getReturnCodeText(), fc_intCompare(), FC_MEMORY_ERROR, fc_printfErrorMessage, FC_SUCCESS, FC_SortedBlobArray::numBlob, and _FC_MeshSlot::numEdge.
Referenced by fc_getMeshEdgeConnsPtr(), fc_getMeshEdgeFaceInfo(), fc_getMeshElementToEdgeConnsPtr(), fc_getMeshNumEdge(), and fc_getMeshNumEntity().
  {
  FC_ReturnCode rc;
  int i, j, k;
  int numVertex, numElement, *elemConns;
  int numVertPerElem, numEdgePerElem, numEdge;
  int temp_ID;
  int *edgeConns, *elemToEdgeConns;
  _FC_MeshSlot* meshSlot;
  FC_ElementType elemType;
  typedef int VertexIDPair[2];
  VertexIDPair vertexIDs;
  VertexIDPair* map; // map element's vertices to it's edges vertices
  // for 2D or less, edges are traversed in similar order to vertices
  // for 3D, edges traversed in order of faces, then faces edges (of course,
  // ignoring edges already traversed) -- see fc_buildFaces for face order.
  VertexIDPair lineMap[1] =    { { 0, 1 } };
  VertexIDPair triMap[3] =     { { 0, 1 }, { 1, 2 }, { 2, 0 } };
  VertexIDPair quadMap[4] =    { { 0, 1 }, { 1, 2 }, { 2, 3 }, { 3, 0 } };
  // tetMap: 3 from 1st face, 2 from 2nd face, 1 from 3rd face, 0 from base
  VertexIDPair tetMap[6] =     { { 0, 1 }, { 1, 3 }, { 3, 0 },
                                 { 1, 2 }, { 2, 3 },
                                 { 2, 0 } };
  // pyramidMap: 3 from 1st face, 2 from 2nd &3rd faces, 1 from 4th, 0 base
  VertexIDPair pyramidMap[8] = { { 0, 1 }, { 1, 4 }, { 4, 0 },
                                 { 1, 2 }, { 2, 4 },
                                 { 2, 3 }, { 3, 4 },
                                 { 3, 0 } };
  // prismMap: 4 for 1st face, 3 for 2nd face, 2 for 4rd face, 0 for base & top
  VertexIDPair prismMap[9] =   { { 0, 1 }, { 1, 4 }, { 4, 3 }, { 3, 0 },
                                 { 1, 2 }, { 2, 5 }, { 5, 4 },
                                 { 2, 0 }, { 3, 5 } };
  // hexMap: 4 for 1st face, 3 for 2nd & 3rd face, 2 for 4th face, 0 for b&t
  VertexIDPair hexMap[12] =    { { 0, 1 }, { 1, 5 }, { 5, 4 }, { 4, 0 },
                                 { 1, 2 }, { 2, 6 }, { 6, 5 },
                                 { 2, 3 }, { 3, 7 }, { 7, 6 },
                                 { 3, 0 }, { 4, 7 } };
  // store edges in set of blob arrays, one for each vertex where the vertex
  // it is stored in is the first vertex of the edge after "sorting"
  // A sorted edge has the smaller vertID first
  // some will have multiple edges, some will have none
  FC_SortedBlobArray* edgeLists; // numVertex long
  _EdgeBlob *edgeBlob;
  // log
  meshSlot = _fc_getMeshSlot(mesh);
  // setup I, assume all elements are of same type
  rc = fc_getMeshInfo(mesh, NULL, NULL, &numVertex, &numElement, &elemType);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getMeshElementConnsPtr(mesh, &elemConns);
  if (rc != FC_SUCCESS)
    return rc;
  // handle the element type & pick the vertex map
  switch (elemType) {
  case FC_ET_POINT:
    // no edges for point elements, so no references to edges for verts
    meshSlot->numEdge = 0;
    return FC_SUCCESS;
  case FC_ET_LINE:     map = lineMap;     break;
  case FC_ET_TRI:      map = triMap;      break;
  case FC_ET_QUAD:     map = quadMap;     break;
  case FC_ET_TET:      map = tetMap;      break;
  case FC_ET_PYRAMID:  map = pyramidMap;  break;
  case FC_ET_PRISM:    map = prismMap;    break;
  case FC_ET_HEX:      map = hexMap;      break;
  case FC_ET_MIXED:    // fall through to FC_ET_UNKNOWN
  case FC_ET_UNKNOWN:
    fc_printfErrorMessage("can't do element type %s",
                          fc_getElementTypeText(elemType));
    return FC_ERROR;
  }
  // setup II
  numVertPerElem = fc_getElementTypeNumVertex(elemType);
  numEdgePerElem = fc_getElementTypeNumEdge(elemType);
  // assuming that calloc will get me same results as fc_initSortedBlobArray
  edgeLists = (FC_SortedBlobArray*)calloc(numVertex, sizeof(FC_SortedBlobArray));
  if (edgeLists == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  // Find unique edges, filling in each element's edgeIDs array as we go
  elemToEdgeConns = malloc(numElement*numEdgePerElem*sizeof(int));
  if (elemToEdgeConns == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  numEdge = 0;
  // for each element:
  for (i = 0; i < numElement; i++) {
    // for each edge
    for (j = 0; j < numEdgePerElem; j++) {
      int foundBlob, blobIdx;
      // get and sort edge's vertexIDs
      for (k = 0; k < 2; k++)
        vertexIDs[k] = elemConns[i*numVertPerElem+map[j][k]];
      if (vertexIDs[0] > vertexIDs[1]) {
        temp_ID = vertexIDs[0];
        vertexIDs[0] = vertexIDs[1];
        vertexIDs[1] = temp_ID;
      }
      // look in edgeList of first vertex for edge with 2nd vertex
      _fc_lookupBlobInSortedBlobArray(&edgeLists[vertexIDs[0]], &vertexIDs[1],
                          fc_intCompare, &foundBlob, &blobIdx);
      if (foundBlob)  {
     edgeBlob = edgeLists[vertexIDs[0]].blobs[blobIdx];
      }
      else { // make an edge
     edgeBlob = (_EdgeBlob*)malloc(sizeof(_EdgeBlob));
        if (edgeBlob == NULL) {
          fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
          return FC_MEMORY_ERROR;
        }
        edgeBlob->endVert = vertexIDs[1];
        edgeBlob->edgeID = numEdge;
     _fc_addEntryToSortedBlobArray(&edgeLists[vertexIDs[0]], blobIdx,
                          edgeBlob);
        numEdge++;
      }
      elemToEdgeConns[i*numEdgePerElem+j] = edgeBlob->edgeID;
    }
  }
  // now build the edgeConns & edges array by walking array of edge lists
  edgeConns = malloc(2*numEdge*sizeof(int));
  if (edgeConns == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < numVertex; i++) {
    for (j = 0; j < edgeLists[i].numBlob; j++) {
      edgeBlob = (_EdgeBlob*)edgeLists[i].blobs[j];
      temp_ID = edgeBlob->edgeID;
      edgeConns[2*temp_ID] = i;
      edgeConns[2*temp_ID + 1] = edgeBlob->endVert;
      free(edgeBlob);
    }
    fc_freeSortedBlobArray(&edgeLists[i]);
  }
  free(edgeLists);
  // set output
  meshSlot->numEdge = numEdge;
  meshSlot->edgeToVertConns = edgeConns;
  meshSlot->elemToEdgeConns = elemToEdgeConns;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_buildFaceConns (FC_Mesh mesh)
Build the face info for the mesh.
Description:
Finds the unique list of faces for the given set of elements. It also adds faceIDs arrays to each element. The vertices in each face are ordered so that the "smallest" edge is first. That is, the smallest ID is first, then the edge from that vertex that has the smaller 2nd ID is next.
Assumes that if comparing first 3 vertices of two face and they are the same, it is the same face (follows from assuming planar faces or some kind of well behaved mesh).
When the face type is FC_ET_MIXED (i.e. mix of triangles and quads for pyramid and prism meshes), the returned connectivity array will be of the size numFace*maxNumVertPerFace and for faces that have fewer vertices than maxNumVertPerFace, the remaining entries for that face will have values of -1. Although this takes up more space, this organization makes it easier to index to a particular face.
Todo:
Make it so that unique faces will have orient of 1 in their element.
Modifications:
02/03/04 WSK, Created
02/06/04 WSK, changed to return raw data arrays too.
07/09/04 WSK, added building of upward and downward connections to vertices and elements (so could get rid of _fc_guildUpwardsConns).
Parameters:
mesh The mesh to build stuff on.
Definition at line 5255 of file mesh.c.
References _faceBlob_compare(), _fc_addEntryToSortedBlobArray(), _fc_getMeshSlot(), _fc_lookupBlobInSortedBlobArray(), FC_SortedBlobArray::blobs, _FC_MeshSlot::elemFaceOrients, _FC_MeshSlot::elemToFaceConns, _FaceBlob::faceID, _FC_MeshSlot::faceToVertConns, _FaceBlob::faceType, _FC_MeshSlot::faceTypes, FC_ERROR, FC_ET_HEX, FC_ET_LINE, FC_ET_MIXED, FC_ET_POINT, FC_ET_PRISM, FC_ET_PYRAMID, FC_ET_QUAD, FC_ET_TET, FC_ET_TRI, FC_ET_UNKNOWN, fc_freeSortedBlobArray(), fc_getElementTypeFaceType(), fc_getElementTypeNumFace(), fc_getElementTypeNumVertex(), fc_getElementTypeText(), fc_getMeshElementConnsPtr(), fc_getMeshInfo(), fc_getReturnCodeText(), FC_MEMORY_ERROR, fc_printfErrorMessage, FC_SUCCESS, FC_SortedBlobArray::numBlob, _FC_MeshSlot::numFace, _FaceBlob::numVertex, _FC_MeshSlot::numVertPerFace, and _FaceBlob::vertexIDs.
Referenced by fc_getMeshEdgeFaceInfo(), fc_getMeshElementFaceOrientsPtr(), fc_getMeshElementToFaceConnsPtr(), fc_getMeshFaceConnsPtr(), fc_getMeshFaceTypesPtr(), fc_getMeshNumEntity(), and fc_getMeshNumFace().
  {
  FC_ReturnCode rc;
  int i, j, k;
  int numVertex, numElement, *elemConns;
  int numVertPerElem, numFacePerElem, numFace, maxNumVertPerFace;
  int idx, temp_ID, numVertexID;
  int* numVertPerFace, *faceConns, *elemToFaceConns, *elemFaceOrients;
  _FC_MeshSlot* meshSlot;
  FC_ElementType elemType, faceType, *faceTypes;
  typedef int VertexIDSet[4]; // faces can have maximum of 4 vertices
  int temp_vertexIDs[7]; // 2*n -1
  FC_ElementType* faceTypeMap;
  FC_ElementType triFaceTypeMap[1] =     { FC_ET_TRI };
  FC_ElementType quadFaceTypeMap[1] =    { FC_ET_QUAD };
  FC_ElementType tetFaceTypeMap[4] =     { FC_ET_TRI, FC_ET_TRI,
                                         FC_ET_TRI, FC_ET_TRI };
  FC_ElementType pyramidFaceTypeMap[5] = { FC_ET_TRI, FC_ET_TRI,
                                         FC_ET_TRI, FC_ET_TRI, FC_ET_QUAD };
  FC_ElementType prismFaceTypeMap[5] =   { FC_ET_QUAD, FC_ET_QUAD, FC_ET_QUAD,
                                         FC_ET_TRI, FC_ET_TRI };
  FC_ElementType hexFaceTypeMap[6] =     { FC_ET_QUAD, FC_ET_QUAD, FC_ET_QUAD,
                                         FC_ET_QUAD, FC_ET_QUAD, FC_ET_QUAD,};
  VertexIDSet* map; // map element's vertex to it's faces vertices
  // Faces use exodus ordering
  VertexIDSet triMap[1] =     { { 0, 1, 2, -1 } };
  VertexIDSet quadMap[1] =    { { 0, 1, 2, 3 } };
  // tetMap: 3 sides in same order as bottom verts, then base
  VertexIDSet tetMap[4] =     { { 0, 1, 3, -1 },
                                { 1, 2, 3, -1 },
                                { 0, 3, 2, -1 },
                                { 0, 2, 1, -1 } };
  // pyramidMap: 4 sides in same order as bottom verts, then base
  VertexIDSet pyramidMap[8] = { { 0, 1, 4, -1 },
                                { 1, 2, 4, -1 },
                                { 2, 3, 4, -1 },
                                { 0, 4, 3, -1 },
                                { 0, 3, 2, 1 } };
  // prismMap: 3 sides in same order as bottom verts, then base & top
  VertexIDSet prismMap[9] =   { { 0, 1, 4, 3 },
                                { 1, 2, 5, 4 },
                                { 0, 3, 5, 2 },
                                { 0, 2, 1, -1 },
                                { 3, 4, 5, -1 } };
  // hexMap: 4 sides in same order as bottom verts, then base & top
  VertexIDSet hexMap[6] =     { { 0, 1, 5, 4 },
                                { 1, 2, 6, 5 },
                                { 2, 3, 7, 6 },
                                { 0, 4, 7, 3 },
                                { 0, 3, 2, 1 },
                                { 4, 5, 6, 7 } };
  // store faces in set of blob arrays, one for each vertex where the vertex
  // it is stored in is the first vertex of the face after "sorting"
  // A sorted face as the smallest vertID first, and the second smallest
  // vertID 2nd, the traversal order may have to be "flipped" to do this.
  // some will have multiple faces, some will have none
  FC_SortedBlobArray* faceLists;
  _FaceBlob tempFaceBlob, *faceBlob;
  // log
  meshSlot = _fc_getMeshSlot(mesh);
  // setup I, assume all elements are of same type
  rc = fc_getMeshInfo(mesh, NULL, NULL, &numVertex, &numElement, &elemType);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getMeshElementConnsPtr(mesh, &elemConns);
  if (rc != FC_SUCCESS)
    return rc;
  // handle the element type & pick the vertex map & faceType
  switch (elemType) {
  case FC_ET_POINT:    // fall through to FC_ET_LINE!
  case FC_ET_LINE:
    // no faces
    meshSlot->numFace = 0;
    return FC_SUCCESS;
  case FC_ET_TRI:    map = triMap;    faceTypeMap = triFaceTypeMap;    break;
  case FC_ET_QUAD:   map = quadMap;   faceTypeMap = quadFaceTypeMap;   break;
  case FC_ET_TET:    map = tetMap;    faceTypeMap = tetFaceTypeMap;    break;
  case FC_ET_PYRAMID: map = pyramidMap; faceTypeMap = pyramidFaceTypeMap; break;
  case FC_ET_PRISM:  map = prismMap;  faceTypeMap = prismFaceTypeMap;  break;
  case FC_ET_HEX:    map = hexMap;    faceTypeMap = hexFaceTypeMap;    break;
  case FC_ET_MIXED:    // fall through to FC_ET_UNKNOWN
  case FC_ET_UNKNOWN:
    fc_printfErrorMessage("can't do element type %s",
                          fc_getElementTypeText(elemType));
    return FC_ERROR;
  }
  // if points or lines, don't need to make face list
  // setup II
  numVertPerElem = fc_getElementTypeNumVertex(elemType);
  numFacePerElem = fc_getElementTypeNumFace(elemType);
  // assuming that calloc will get me same results as fc_initSortedBlobArray
  faceLists = (FC_SortedBlobArray*)calloc(numVertex, sizeof(FC_SortedBlobArray));
  if (faceLists == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  // Find unique faces, filling in each element's faceIDs array as we go
  //printf("numVertex = %d, numElement = %d\n", numVertex, numElement);
  elemToFaceConns = malloc(numElement*numFacePerElem*sizeof(int));
  elemFaceOrients = malloc(numElement*numFacePerElem*sizeof(int));
  if (elemToFaceConns == NULL || elemFaceOrients == NULL) {
    free(elemToFaceConns);
    free(elemFaceOrients);
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  numFace = 0;
  // for each element:
  for (i = 0; i < numElement; i++) {
    // for each face
    for (j = 0; j < numFacePerElem; j++) {
      int foundBlob, blobIdx;
      numVertexID = fc_getElementTypeNumVertex(faceTypeMap[j]);
      // get face's vertexIDs
      for (k = 0; k < numVertexID; k++)
        temp_vertexIDs[k] = elemConns[i*numVertPerElem+map[j][k]];
      // rotate array so smallest ID is first (keep order)
      idx = 0;
      temp_ID = temp_vertexIDs[0];
      for (k = 1; k < numVertexID; k++) {
        if (temp_vertexIDs[k] < temp_ID) {
          idx = k;
          temp_ID = temp_vertexIDs[k];
        }
      }
      for (k = 0; k < idx; k++)
        temp_vertexIDs[numVertexID + k] = temp_vertexIDs[k];
      // Fill in temporary face
      tempFaceBlob.faceType = faceTypeMap[j];
      tempFaceBlob.numVertex = numVertexID;
      // Make the vertex array, & flip orientation if needed
      if (temp_vertexIDs[idx + 1] < temp_vertexIDs[idx + numVertexID - 1]) {
        elemFaceOrients[i*numFacePerElem+j] = 1;
        for (k = 0; k < numVertexID; k++)
          tempFaceBlob.vertexIDs[k] = temp_vertexIDs[k+idx];
      }
      else {
        elemFaceOrients[i*numFacePerElem+j] = -1;
        tempFaceBlob.vertexIDs[0] = temp_vertexIDs[idx];
        for (k = 1; k < numVertexID; k++)
          tempFaceBlob.vertexIDs[k] = temp_vertexIDs[idx + numVertexID - k];
      }
      // look for entry in faceLists based on first vertex
      _fc_lookupBlobInSortedBlobArray(&faceLists[tempFaceBlob.vertexIDs[0]],
                          &tempFaceBlob, _faceBlob_compare,
                          &foundBlob, &blobIdx);
      if (foundBlob) {
     faceBlob = faceLists[tempFaceBlob.vertexIDs[0]].blobs[blobIdx];
      }
      else { // make a new face
     faceBlob = (_FaceBlob*)malloc(sizeof(_FaceBlob));
     if (faceBlob == NULL) {
       fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
          return FC_MEMORY_ERROR;
     }
     *faceBlob = tempFaceBlob; // check me!
        faceBlob->faceID = numFace;
     _fc_addEntryToSortedBlobArray(&faceLists[tempFaceBlob.vertexIDs[0]],
                          blobIdx, faceBlob);
        numFace++;
      }
      elemToFaceConns[i*numFacePerElem+j] = faceBlob->faceID;
    }
  }
  // now build the faceTypes, numVertPerFace, faceConns and faces arrays by walking array
  // of face lists
  faceType = fc_getElementTypeFaceType(elemType);
  maxNumVertPerFace = fc_getElementTypeNumVertex(faceType);
  if (maxNumVertPerFace < 0 && faceType == FC_ET_MIXED)
    maxNumVertPerFace = 4; // only pyramids & prisms have mixed face type
  faceTypes = malloc(numFace*sizeof(FC_ElementType));
  numVertPerFace = malloc(numFace*sizeof(int));
  faceConns = malloc(numFace*maxNumVertPerFace*sizeof(int));
  if (faceTypes == NULL || numVertPerFace == NULL || faceConns == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    free(faceTypes);
    free(numVertPerFace);
    free(faceConns);
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < numVertex; i++) {
    for (j = 0; j < faceLists[i].numBlob; j++) {
      faceBlob = (_FaceBlob*)faceLists[i].blobs[j];
      temp_ID = faceBlob->faceID;
      faceTypes[temp_ID] = faceBlob->faceType;
      numVertPerFace[temp_ID] = faceBlob->numVertex;
      memcpy(&faceConns[maxNumVertPerFace*temp_ID], faceBlob->vertexIDs,
             faceBlob->numVertex*sizeof(int));
      for (k = faceBlob->numVertex; k < maxNumVertPerFace; k++)
        faceConns[maxNumVertPerFace*temp_ID + k] = -1;
      free(faceBlob);
    }
    fc_freeSortedBlobArray(&faceLists[i]);
  }
  free(faceLists);
  // set output
  meshSlot->numFace = numFace;
  meshSlot->faceTypes = faceTypes;
  meshSlot->numVertPerFace = numVertPerFace;
  meshSlot->faceToVertConns = faceConns;
  meshSlot->elemToFaceConns = elemToFaceConns;
  meshSlot->elemFaceOrients = elemFaceOrients;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_buildMeshElementNeighborsViaEntity (FC_Mesh mesh, FC_AssociationType sharedType)
Build element neighbors that share the specified entity type.
Description:
Computes the big data arrays that store number of element neighbors per element and the ids of those neighbors.
This is a helper and should only be called internally. It doesn't have robust checking.
Modifications:
10/31/2005 WSD. Created to replace _fc_buildElementNeighbors. Since the code is essentially the same for three possible share entity types, replace 3 specific versions with 1 general one.
Parameters:
mesh The mesh to build stuff on.
sharedType The type of shared entity
Definition at line 5587 of file mesh.c.
References _fc_getMeshElementParentsOfEdgesPtr(), _fc_getMeshElementParentsOfFacesPtr(), _fc_getMeshElementParentsOfVerticesPtr(), _fc_getMeshSlot(), _FC_MeshSlot::elemNeighsViaEdge, _FC_MeshSlot::elemNeighsViaFace, _FC_MeshSlot::elemNeighsViaVert, fc_addIntArrayToSortedIntArray(), FC_AT_EDGE, FC_AT_ELEMENT, FC_AT_FACE, FC_AT_UNKNOWN, FC_AT_VERTEX, fc_convertSortedIntArrayToIntArray(), fc_deleteIntFromSortedIntArray(), fc_getAssociationTypeText(), fc_getElementTypeNumEntity(), fc_getMeshElementConnsPtr(), fc_getMeshElementToEdgeConnsPtr(), fc_getMeshElementToFaceConnsPtr(), fc_getMeshInfo(), fc_getMeshNumEntity(), fc_getReturnCodeText(), fc_initSortedIntArray(), FC_INPUT_ERROR, fc_isAssociationTypeValid(), fc_isMeshValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numElemNeighsViaEdge, _FC_MeshSlot::numElemNeighsViaFace, and _FC_MeshSlot::numElemNeighsViaVert.
Referenced by _fc_getMeshElementNeighborsViaEdgePtr(), _fc_getMeshElementNeighborsViaFacePtr(), and _fc_getMeshElementNeighborsViaVertexPtr().
  {
  FC_ReturnCode rc, rc2;
  int i, j;
  int numElem, numEntity, numEntityPerElem, entityID;
  int *elemToEntityConns, *numElemPerEntity, **elemParentsPerEntity;
  int *numElemNeighsViaEntity, **elemNeighsViaEntity;
  _FC_MeshSlot *meshSlot;
  FC_ElementType elemType;
  FC_SortedIntArray list; // list for each element
  // check inputs
  if (!fc_isMeshValid(mesh) || !fc_isAssociationTypeValid(sharedType) ||
      sharedType == FC_AT_UNKNOWN || sharedType >= FC_AT_ELEMENT) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // FIX?: Check that entity has topodim less than element
  // log message
  meshSlot = _fc_getMeshSlot(mesh);
  fc_printfLogMessage("Building element neighbors via '%s' on mesh '%s'",
                      fc_getAssociationTypeText(sharedType),
                      meshSlot->header.name);
  // setup
  rc = fc_getMeshInfo(mesh, NULL, NULL, NULL, &numElem, &elemType);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getMeshNumEntity(mesh, sharedType, &numEntity);
  if (rc != FC_SUCCESS)
    return rc;
  numEntityPerElem = fc_getElementTypeNumEntity(elemType, sharedType);
  // A little more checking
  if (numEntity < 1)
    return FC_SUCCESS; // Nothing to do
  // More setup
  // FIX: replace this if wrapper calls become available
  switch(sharedType) {
  case FC_AT_VERTEX:
    rc = fc_getMeshElementConnsPtr(mesh, &elemToEntityConns);
    rc2 = _fc_getMeshElementParentsOfVerticesPtr(mesh, &numElemPerEntity,
                                             &elemParentsPerEntity);
    break;
  case FC_AT_EDGE:
    rc = fc_getMeshElementToEdgeConnsPtr(mesh, &elemToEntityConns);
    rc2 = _fc_getMeshElementParentsOfEdgesPtr(mesh, &numElemPerEntity,
                                           &elemParentsPerEntity);
    break;
  case FC_AT_FACE:
    rc = fc_getMeshElementToFaceConnsPtr(mesh, &elemToEntityConns);
    rc2 = _fc_getMeshElementParentsOfFacesPtr(mesh, &numElemPerEntity,
                                           &elemParentsPerEntity);
    break;
  default :
    ; // nothing
  }
  if (rc != FC_SUCCESS)
    return rc;
  if (rc2 != FC_SUCCESS)
    return rc2;
  // FIX? different algorithm
  // This *might* be faster but will use more memory
  // For each entity, add it's parents to each other's lists
  // for (i = 0; i < numEntity; i++) {
  //   for (j = 0; j < numElemPerEntity[i]; j++) {
  //     for (k = 0; k < numElemPerEntity[i]; k++) {
  //       if (j != k) {
  //          fc_addIntToSortedIntArray(&list[k], elemParentsPerEntity[i][j]);
  //          fc_addIntToSortedIntArray(&list[j], elemParentsPerEntity[i][k]);
  //       }
  //     }
  //   }
  // }
  // find neighbors
  numElemNeighsViaEntity = (int*)malloc(numElem*sizeof(int));
  elemNeighsViaEntity = (int**)malloc(numElem*sizeof(int*));
  if (numElemNeighsViaEntity == NULL || elemNeighsViaEntity == NULL) {
    free(numElemNeighsViaEntity);
    free(elemNeighsViaEntity);
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < numElem; i++) {
    fc_initSortedIntArray(&list);
    for (j = 0; j < numEntityPerElem; j++) {
      entityID = elemToEntityConns[i*numEntityPerElem+j];
      int ret = fc_addIntArrayToSortedIntArray(&list,
                                numElemPerEntity[entityID],
                                elemParentsPerEntity[entityID],
                                0);
      if (ret < 0) {
     fc_printfErrorMessage("Failed to add entry to sia");
     return ret;
      }
    }
    fc_deleteIntFromSortedIntArray(&list, i); // don't count this elem
    rc = fc_convertSortedIntArrayToIntArray(&list, &numElemNeighsViaEntity[i],
                                &elemNeighsViaEntity[i]);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // Set results on mesh
  // FIX?: pass array pointer to function call?
  switch(sharedType) {
  case FC_AT_VERTEX:
    meshSlot->numElemNeighsViaVert = numElemNeighsViaEntity;
    meshSlot->elemNeighsViaVert = elemNeighsViaEntity;
    break;
  case FC_AT_EDGE:
    meshSlot->numElemNeighsViaEdge = numElemNeighsViaEntity;
    meshSlot->elemNeighsViaEdge = elemNeighsViaEntity;
    break;
  case FC_AT_FACE:
    meshSlot->numElemNeighsViaFace = numElemNeighsViaEntity;
    meshSlot->elemNeighsViaFace = elemNeighsViaEntity;
    break;
  default :
    ; // nothing
  }
  return FC_SUCCESS;
}
FC_ReturnCode _fc_buildMeshVertexNeighborsViaEdge (FC_Mesh mesh)
Build the neighbor information for the vertices array.
Description:
Modifications:
WSK 02/24/04 WSK, created to build quick lookups for vertex neighbors
WSK 07/15/04 WSK, now only builds "edge" neighbors
WSK 10/31/05 WSK, takes mesh as argument instead of all the stuf it needs.
Parameters:
mesh The mesh to build stuff on.
Definition at line 5487 of file mesh.c.
References _fc_getMeshSlot(), fc_addIntToSortedIntArray(), fc_convertSortedIntArrayToIntArray(), fc_getMeshEdgeConnsPtr(), fc_getMeshNumEdge(), fc_getMeshNumVertex(), fc_getReturnCodeText(), fc_initSortedIntArray(), FC_INPUT_ERROR, fc_isMeshValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numVertNeighsViaEdge, and _FC_MeshSlot::vertNeighsViaEdge.
Referenced by _fc_getMeshVertexNeighborsViaEdgePtr().
  {
  FC_ReturnCode rc;
  int i;
  int numVert, numEdge, *edgeConns;
  int* numVertNeighsViaEdge, **vertNeighsViaEdge;
  _FC_MeshSlot *meshSlot;
  FC_SortedIntArray *lists;  // a list of neighbor IDs
  // check inputs
  if (!fc_isMeshValid(mesh)) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  meshSlot = _fc_getMeshSlot(mesh);
  fc_printfLogMessage("Building vertex neighbors via edge on mesh '%s'",
                      meshSlot->header.name);
  // setup
  rc = fc_getMeshNumVertex(mesh, &numVert);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getMeshNumEdge(mesh, &numEdge);
  if (rc != FC_SUCCESS)
    return rc;
  // A little more checking
  if (numEdge < 1)
    return FC_SUCCESS; // Nothing to do
  // More setup
  rc = fc_getMeshEdgeConnsPtr(mesh, &edgeConns);
  if (rc != FC_SUCCESS)
    return rc;
  // for each edge, add each vertex to the other vertex's list
  lists = malloc(numVert*sizeof(FC_SortedIntArray));
  if (lists == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < numVert; i++)
    fc_initSortedIntArray(&lists[i]);
  for (i = 0; i < numEdge; i++) {
    int ret = fc_addIntToSortedIntArray(&lists[edgeConns[i*2+1]], edgeConns[i*2]);
    if (ret < 0) {
      fc_printfErrorMessage("Failed to add id to sia");
      return ret;
    }
    ret = fc_addIntToSortedIntArray(&lists[edgeConns[i*2]], edgeConns[i*2+1]);
    if (ret < 0) {
      fc_printfErrorMessage("Failed to add id to sia");
      return ret;
    }
  }
  // convert neigh lists to arrays & store on mesh
  numVertNeighsViaEdge = (int*)malloc(numVert*sizeof(int));
  vertNeighsViaEdge = (int**)malloc(numVert*sizeof(int*));
  if (numVertNeighsViaEdge == NULL || vertNeighsViaEdge == NULL) {
    free(numVertNeighsViaEdge);
    free(vertNeighsViaEdge);
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < numVert; i++) {
    rc = fc_convertSortedIntArrayToIntArray(&(lists[i]), &(numVertNeighsViaEdge[i]),
                                &(vertNeighsViaEdge[i]));
    if (rc != FC_SUCCESS)
      return rc;
  }
  free(lists);
  // set results on mesh
  meshSlot->numVertNeighsViaEdge = numVertNeighsViaEdge;
  meshSlot->vertNeighsViaEdge = vertNeighsViaEdge;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_buildParents (FC_Mesh mesh, FC_AssociationType childType, FC_AssociationType parentType)
Build an arrays of parent IDs.
Description:
Build arrays that hold the parent IDs for the requested child/parent combination.
Modifications:
11/01/2005 WSD. Creatd to replace building parents lists in _fc_buildElements(), _fc_buildEdges, & _fc_buildFaces.
Parameters:
mesh The mesh to build stuff on.
childType Child entity type.
parentType Parent entity type.
Definition at line 4830 of file mesh.c.
References _fc_getMeshSlot(), _FC_MeshSlot::edgeParentsPerVert, _FC_MeshSlot::elemParentsPerEdge, _FC_MeshSlot::elemParentsPerFace, _FC_MeshSlot::elemParentsPerVert, _FC_MeshSlot::faceParentsPerVert, fc_addIntToSortedIntArray(), FC_AT_EDGE, FC_AT_ELEMENT, FC_AT_FACE, FC_AT_UNKNOWN, FC_AT_VERTEX, FC_AT_WHOLE_MESH, fc_convertSortedIntArrayToIntArray(), fc_getAssociationTypeText(), fc_getElementTypeNumEntity(), fc_getMeshEdgeConnsPtr(), fc_getMeshElementConnsPtr(), fc_getMeshElementToEdgeConnsPtr(), fc_getMeshElementToFaceConnsPtr(), fc_getMeshEntityElementType(), fc_getMeshFaceConnsPtr(), fc_getMeshNumEntity(), fc_getReturnCodeText(), fc_initSortedIntArray(), FC_INPUT_ERROR, fc_isAssociationTypeValid(), fc_isMeshValid(), FC_MEMORY_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numEdgePerVert, _FC_MeshSlot::numElemPerEdge, _FC_MeshSlot::numElemPerFace, _FC_MeshSlot::numElemPerVert, and _FC_MeshSlot::numFacePerVert.
Referenced by _fc_getMeshEdgeParentsOfVerticesPtr(), _fc_getMeshElementParentsOfEdgesPtr(), _fc_getMeshElementParentsOfFacesPtr(), _fc_getMeshElementParentsOfVerticesPtr(), and _fc_getMeshFaceParentsOfVerticesPtr().
  {
  FC_ReturnCode rc;
  int i, j;
  int numChild, numParent, *parentToChildConns, *numVertPerFace = NULL;
  int numChildPerParent, maxNumChildPerParent;
  int *numParentPerChild, **parentsPerChild;
   _FC_MeshSlot *meshSlot;
   FC_ElementType elemType;
   FC_SortedIntArray* lists; // a list of parent IDs
  // check inputs
  if (!fc_isMeshValid(mesh) || !fc_isAssociationTypeValid(childType) ||
      childType == FC_AT_UNKNOWN || childType == FC_AT_WHOLE_MESH ||
      !fc_isAssociationTypeValid(parentType) || parentType == FC_AT_UNKNOWN ||
      parentType == FC_AT_WHOLE_MESH) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  if (childType >= parentType) {
    fc_printfErrorMessage("child type must be child of parent type");
    return FC_INPUT_ERROR;
  }
  // Setup I
  rc = fc_getMeshNumEntity(mesh, parentType, &numParent);
  if (rc != FC_SUCCESS)
    return rc;
  // Special case, if the parent type doesn't exist, then we're done
  if (numParent == 0)
    return FC_SUCCESS;
  // log message
  meshSlot = _fc_getMeshSlot(mesh);
  fc_printfLogMessage("Building vertex neighbors via edge on mesh '%s'",
                      meshSlot->header.name);
  // Setup II
  rc = fc_getMeshNumEntity(mesh, childType, &numChild);
  if (rc != FC_SUCCESS)
    return rc;
   rc = fc_getMeshEntityElementType(mesh, parentType, 0, &elemType);
  if (rc != FC_SUCCESS)
    return rc;
 // this # gets overwritten or vert-face case
  maxNumChildPerParent = fc_getElementTypeNumEntity(elemType, childType);
  // do entity specific stuff - conns
  if (childType == FC_AT_VERTEX && parentType == FC_AT_EDGE)
    rc = fc_getMeshEdgeConnsPtr(mesh, &parentToChildConns);
  else if (childType == FC_AT_VERTEX && parentType == FC_AT_FACE)
    rc = fc_getMeshFaceConnsPtr(mesh, &numVertPerFace, &maxNumChildPerParent,
                                &parentToChildConns);
  else if (childType == FC_AT_VERTEX && parentType == FC_AT_ELEMENT)
    rc = fc_getMeshElementConnsPtr(mesh, &parentToChildConns);
  // child = edge, parent = face not supported
  else if (childType == FC_AT_EDGE && parentType == FC_AT_ELEMENT)
    rc = fc_getMeshElementToEdgeConnsPtr(mesh, &parentToChildConns);
  else if (childType == FC_AT_FACE && parentType == FC_AT_ELEMENT)
    rc = fc_getMeshElementToFaceConnsPtr(mesh, &parentToChildConns);
  else {
    fc_printfErrorMessage("The combination: child = %s, parent = %s is "
                          "not supported",
                          fc_getAssociationTypeText(childType),
                          fc_getAssociationTypeText(parentType));
    return FC_INPUT_ERROR;
  }
  if (rc != FC_SUCCESS)
    return rc;
  lists = malloc(numChild*sizeof(FC_SortedIntArray));
  if (lists == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < numChild; i++)
    fc_initSortedIntArray(&lists[i]);
  // for each Parent
  for (i = 0; i < numParent; i++) {
    if (numVertPerFace)
      numChildPerParent = numVertPerFace[i];
    else
      numChildPerParent = maxNumChildPerParent;
    // get parent's children & add parent ID to those children's lists
    for (j = 0; j < numChildPerParent; j++) {
      int ret = fc_addIntToSortedIntArray(&(lists[parentToChildConns[i*maxNumChildPerParent+j]]),
                   i);
      if (ret < 0) {
        fc_printfErrorMessage("Failed to add id to sia");
        return ret;
      }
    }
  }
  // convert lists to arrays
  numParentPerChild = (int*)malloc(numChild*sizeof(int));
  parentsPerChild = (int**)calloc(numChild, sizeof(int*));
  if (numParentPerChild == NULL || parentsPerChild == NULL) {
    free(numParentPerChild);
    free(parentsPerChild);
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_MEMORY_ERROR));
    return FC_MEMORY_ERROR;
  }
  for (i = 0; i < numChild; i++) {
    rc = fc_convertSortedIntArrayToIntArray(&(lists[i]), &(numParentPerChild[i]),
                                &(parentsPerChild[i]));
    if (rc != FC_SUCCESS)
      return rc;
  }
  // cleanup
  free(lists);
  // set results on mesh
  if (childType == FC_AT_VERTEX && parentType == FC_AT_EDGE) {
    meshSlot->numEdgePerVert = numParentPerChild;
    meshSlot->edgeParentsPerVert = parentsPerChild;
  }
  else if (childType == FC_AT_VERTEX && parentType == FC_AT_FACE) {
    meshSlot->numFacePerVert = numParentPerChild;
    meshSlot->faceParentsPerVert = parentsPerChild;
  }
  else if (childType == FC_AT_VERTEX && parentType == FC_AT_ELEMENT) {
    meshSlot->numElemPerVert = numParentPerChild;
    meshSlot->elemParentsPerVert = parentsPerChild;
  }
  else if (childType == FC_AT_EDGE && parentType == FC_AT_ELEMENT) {
    meshSlot->numElemPerEdge = numParentPerChild;
    meshSlot->elemParentsPerEdge = parentsPerChild;
  }
  else if (childType == FC_AT_FACE && parentType == FC_AT_ELEMENT) {
    meshSlot->numElemPerFace = numParentPerChild;
    meshSlot->elemParentsPerFace = parentsPerChild;
  }
  return FC_SUCCESS;
}
void _fc_clearMeshSlot (_FC_MeshSlot * meshSlotp)
Clear a mesh slot.
Description:
Releases all dynamically allocated resources in a mesh, and reinitializes all members.
Modifications:
Aug 6, 2002 W Koegler Created
2003-APR-31 W Koegler Made more comprehensive
03-03-08 ACG added seqSubsets
Parameters:
meshSlotp input - vtable pointer
Definition at line 5962 of file mesh.c.
References _fc_clearSlotHeader(), _fc_initMeshSlot(), _fc_releaseMeshSlot(), _FC_MeshSlot::basicVarIDs, _FC_MeshSlot::header, _FC_MeshSlot::numSeqSub, _FC_MeshSlot::numSeqVar, _FC_MeshSlot::numStepPerSeqVar, _FC_MeshSlot::seqSubIDs, _FC_MeshSlot::seqVarIDs, and _FC_MeshSlot::subIDs.
Referenced by _fc_deleteMeshSlot(), and _fc_freeMeshTable().
  {
  int i;
  if (meshSlotp != NULL) {
    // release big data
    _fc_releaseMeshSlot(meshSlotp);
    // free other dynamic arrays
    if (meshSlotp->subIDs)
      free(meshSlotp->subIDs);
    if (meshSlotp->seqSubIDs) {
      for (i = 0; i < meshSlotp->numSeqSub; i++)
     free(meshSlotp->seqSubIDs[i]);
      free(meshSlotp->seqSubIDs);
    }
    if (meshSlotp->basicVarIDs)
      free(meshSlotp->basicVarIDs);
    if (meshSlotp->numStepPerSeqVar)
      free(meshSlotp->numStepPerSeqVar);
    if (meshSlotp->seqVarIDs) {
      for (i = 0; i < meshSlotp->numSeqVar; i++)
     free(meshSlotp->seqVarIDs[i]);
      free(meshSlotp->seqVarIDs);
    }
    // clear table header
    _fc_clearSlotHeader(&meshSlotp->header);
    // reinit
    _fc_initMeshSlot(meshSlotp);
  }
}
FC_ReturnCode _fc_deleteMeshSlot (FC_Mesh mesh)
Delete the mesh slot associated with the mesh handle.
Description:
This routine clears the dynamic data in the slot and then deletes the slot from the table.
Modifications:
12/20/2005 WSD. Created.
Parameters:
mesh input - mesh
Definition at line 6101 of file mesh.c.
References _fc_clearMeshSlot(), _fc_deleteSlot(), _fc_getMeshSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, _FC_MeshSlot::header, meshTableSize, and _FC_SlotHeader::slotID.
Referenced by fc_deleteMesh().
  {
  _FC_MeshSlot* meshSlot;
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // do it
  _fc_clearMeshSlot(meshSlot);
  return _fc_deleteSlot(meshSlot->header.slotID, meshTableSize,
               (_FC_SlotHeader**)meshTable, &meshOpenSlots);
}
void _fc_freeMeshTable (void)
Free all entries in the mesh table.
Description:
This should only be called after making sure that all slots have been cleared.
Modifications:
05/21/04 WSK Created.
Definition at line 6289 of file mesh.c.
References _fc_clearMeshSlot(), fc_freeSortedIntArray(), and meshTableSize.
Referenced by fc_finalLibrary().
{
  int i;
  for (i = 0; i < meshTableSize; i++) {
    _fc_clearMeshSlot(meshTable[i]);
    free(meshTable[i]);
  }
  free(meshTable);
  fc_freeSortedIntArray(&meshOpenSlots);
  meshTableSize = 0;
  meshTable = NULL;
}
FC_ReturnCode _fc_getMeshEdgeParentsOfVerticesPtr (FC_Mesh mesh, int ** numEdgePerVert, int *** edgeParentsPerVert)
Return parent edges of the vertices.
Description:
This routine returns pointers to two arrays which hold the number of parent edges for each vertex and the IDs of the parent edges for each vertex. The array with the edge IDs is a 2D array. Each vertex's edge parent IDs are in sorted order. Get an edge parent ID by
edgeParentsPerVert[VertID][i];
where i is 0 ... numEdgePerVert[vertID] - 1. These are big data arrays and should NOT be freed by the calling program.
Note that edges may not yet exist for the mesh, and if they don't, calling this function will build them (which may take some time).
Also note that if there cannot be any edges on the mesh (only happens for point meshes), NULLs will be returned instead of arrays.
Modifications:
10/27/05 WSD, created.
Parameters:
mesh input - mesh
numEdgePerVert output - array of number of edge parents per vertex
edgeParentsPerVert output - array of arrays of edge parent IDs, treat read only
Definition at line 4250 of file mesh.c.
References _fc_buildParents(), _fc_getMeshSlot(), _FC_MeshSlot::edgeParentsPerVert, FC_AT_EDGE, FC_AT_VERTEX, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numEdge, and _FC_MeshSlot::numEdgePerVert.
Referenced by _fc_getEdgeNeighbors(), and _fc_getVertexParents().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default return
  if (numEdgePerVert)
    *numEdgePerVert = NULL;
  if (edgeParentsPerVert)
    *edgeParentsPerVert = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || numEdgePerVert == NULL ||
      edgeParentsPerVert == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting parent edges of the vertices on mesh '%s'",
                      meshSlot->header.name);
  // if it doesn't exist, build stuff
  if (meshSlot->numEdge < 0 ||
      (meshSlot->numEdge > 0 && meshSlot->numEdgePerVert == NULL)) {
    rc = _fc_buildParents(mesh, FC_AT_VERTEX, FC_AT_EDGE);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // return pointers
  *numEdgePerVert = meshSlot->numEdgePerVert;
  *edgeParentsPerVert = meshSlot->edgeParentsPerVert;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_getMeshElementNeighborsViaEdgePtr (FC_Mesh mesh, int ** numElemNeighsViaEdge, int *** elemNeighsViaEdge)
Return element neighbors that share an edge.
Description:
This routine returns pointers to two arrays which hold the number of element neighbors for each element and the IDs of the element neighbors for each element. The array with the element IDs is a 2D array. Each elem's neighbor IDs are in sorted order. Get an vetex neighbor ID by
elemNeighsViaEdge[elemID][i];
where i is 0 ... numElemNeighsViaEdge[elemID] - 1. These are big data arrays and should NOT be freed by the calling program.
Note that edges may not yet exist for the mesh, and if they don't, calling this function will build them (which may take some time).
Also note that if there cannot be any edges on the mesh (only happens for point meshes), NULLs will be returned instead of arrays.
Modifications:
10/31/05 WSD, created.
Parameters:
mesh input - mesh
numElemNeighsViaEdge output - array of number of elem neighbors per elem (that share an edge)
elemNeighsViaEdge output - array of arrays of elem neighbor IDs, treat read only
Definition at line 4706 of file mesh.c.
References _fc_buildMeshElementNeighborsViaEntity(), _fc_getMeshSlot(), _FC_MeshSlot::elemNeighsViaEdge, FC_AT_EDGE, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numEdge, and _FC_MeshSlot::numElemNeighsViaEdge.
Referenced by _fc_getElementNeighbors().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default return
  if (numElemNeighsViaEdge)
    *numElemNeighsViaEdge = NULL;
  if (elemNeighsViaEdge)
    *elemNeighsViaEdge = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || numElemNeighsViaEdge == NULL ||
      elemNeighsViaEdge == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting parent elems of the faces on mesh '%s'",
                      meshSlot->header.name);
  // if it doesn't exist, build stuff
  if (meshSlot->numEdge < 0 ||
      (meshSlot->numEdge > 0 && meshSlot->numElemNeighsViaEdge == NULL)) {
    rc = _fc_buildMeshElementNeighborsViaEntity(mesh, FC_AT_EDGE);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // return pointers
  *numElemNeighsViaEdge = meshSlot->numElemNeighsViaEdge;
  *elemNeighsViaEdge = meshSlot->elemNeighsViaEdge;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_getMeshElementNeighborsViaFacePtr (FC_Mesh mesh, int ** numElemNeighsViaFace, int *** elemNeighsViaFace)
Return element neighbors that share an face.
Description:
This routine returns pointers to two arrays which hold the number of element neighbors for each element and the IDs of the element neighbors for each element. The array with the element IDs is a 2D array. Each elem's neighbor IDs are in sorted order. Get an vetex neighbor ID by
elemNeighsViaFace[elemID][i];
where i is 0 ... numElemNeighsViaFace[elemID] - 1. These are big data arrays and should NOT be freed by the calling program.
Note that faces may not yet exist for the mesh, and if they don't, calling this function will build them (which may take some time).
Also note that if there cannot be any faces on the mesh (only happens for point and line meshes), NULLs will be returned instead of arrays.
Modifications:
10/31/05 WSD, created.
Parameters:
mesh input - mesh
numElemNeighsViaFace output - array of number of elem neighbors per elem (that share an face)
elemNeighsViaFace output - array of arrays of elem neighbor IDs, treat read only
Definition at line 4774 of file mesh.c.
References _fc_buildMeshElementNeighborsViaEntity(), _fc_getMeshSlot(), _FC_MeshSlot::elemNeighsViaFace, FC_AT_FACE, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numElemNeighsViaFace, and _FC_MeshSlot::numFace.
Referenced by _fc_getElementNeighbors().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default return
  if (numElemNeighsViaFace)
    *numElemNeighsViaFace = NULL;
  if (elemNeighsViaFace)
    *elemNeighsViaFace = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || numElemNeighsViaFace == NULL ||
      elemNeighsViaFace == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting parent elems of the faces on mesh '%s'",
                      meshSlot->header.name);
  // if it doesn't exist, build stuff
  if (meshSlot->numFace < 0 ||
      (meshSlot->numFace > 0 && meshSlot->numElemNeighsViaFace == NULL)) {
    rc = _fc_buildMeshElementNeighborsViaEntity(mesh, FC_AT_FACE);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // return pointers
  *numElemNeighsViaFace = meshSlot->numElemNeighsViaFace;
  *elemNeighsViaFace = meshSlot->elemNeighsViaFace;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_getMeshElementNeighborsViaVertexPtr (FC_Mesh mesh, int ** numElemNeighsViaVert, int *** elemNeighsViaVert)
Return element neighbors that share an vertex.
Description:
This routine returns pointers to two arrays which hold the number of element neighbors for each element and the IDs of the element neighbors for each element. The array with the element IDs is a 2D array. Each elem's neighbor IDs are in sorted order. Get an vetex neighbor ID by
elemNeighsViaVert[elemID][i];
where i is 0 ... numElemNeighsViaVert[elemID] - 1. These are big data arrays and should NOT be freed by the calling program.
Modifications:
10/31/05 WSD, created.
Parameters:
mesh input - mesh
numElemNeighsViaVert output - array of number of elem neighbors per elem (that share an vert)
elemNeighsViaVert output - array of arrays of elem neighbor IDs, treat read only
Definition at line 4639 of file mesh.c.
References _fc_buildMeshElementNeighborsViaEntity(), _fc_getMeshSlot(), _FC_MeshSlot::elemNeighsViaVert, FC_AT_VERTEX, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numElemNeighsViaVert, and _FC_MeshSlot::numVertex.
Referenced by _fc_getElementNeighbors().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default return
  if (numElemNeighsViaVert)
    *numElemNeighsViaVert = NULL;
  if (elemNeighsViaVert)
    *elemNeighsViaVert = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || numElemNeighsViaVert == NULL ||
      elemNeighsViaVert == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting parent elems of the faces on mesh '%s'",
                      meshSlot->header.name);
  // if it doesn't exist, build stuff
  if (meshSlot->numVertex > 0 && meshSlot->numElemNeighsViaVert == NULL) {
    rc = _fc_buildMeshElementNeighborsViaEntity(mesh, FC_AT_VERTEX);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // return pointers
  *numElemNeighsViaVert = meshSlot->numElemNeighsViaVert;
  *elemNeighsViaVert = meshSlot->elemNeighsViaVert;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_getMeshElementParentsOfEdgesPtr (FC_Mesh mesh, int ** numElemPerEdge, int *** elemParentsPerEdge)
Return parent elements of the edges.
Description:
This routine returns pointers to two arrays which hold the number of parent elements for each edge and the IDs of the parent elements for each edge. The array with the element IDs is a 2D array. Each edge's element parent IDs are in sorted order. Get an element parent ID by
elemParentsPerEdge[EdgeID][i];
where i is 0 ... numElemPerEdge[edgeID] - 1. These are big data arrays and should NOT be freed by the calling program.
Note that edges may not yet exist for the mesh, and if they don't, calling this function will build them (which may take some time).
Modifications:
10/27/05 WSD, created.
Parameters:
mesh input - mesh
numElemPerEdge output - array of number of elem parents per edge
elemParentsPerEdge output - array of arrays of elem parent IDs, treat read only
Definition at line 4444 of file mesh.c.
References _fc_buildParents(), _fc_getMeshSlot(), _FC_MeshSlot::elemParentsPerEdge, FC_AT_EDGE, FC_AT_ELEMENT, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numEdge, and _FC_MeshSlot::numElemPerEdge.
Referenced by _fc_buildMeshElementNeighborsViaEntity(), _fc_getEdgeParents(), and _fc_writeExodusDataset().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default return
  if (numElemPerEdge)
    *numElemPerEdge = NULL;
  if (elemParentsPerEdge)
    *elemParentsPerEdge = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || numElemPerEdge == NULL ||
      elemParentsPerEdge == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting parent elems of the edges on mesh '%s'",
                      meshSlot->header.name);
  // if it doesn't exist, build stuff
  if (meshSlot->numEdge < 0 ||
      (meshSlot->numEdge > 0 && meshSlot->numElemPerEdge == NULL)) {
    rc = _fc_buildParents(mesh, FC_AT_EDGE, FC_AT_ELEMENT);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // return pointers
  *numElemPerEdge = meshSlot->numElemPerEdge;
  *elemParentsPerEdge = meshSlot->elemParentsPerEdge;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_getMeshElementParentsOfFacesPtr (FC_Mesh mesh, int ** numElemPerFace, int *** elemParentsPerFace)
Return parent elements of the faces.
Description:
This routine returns pointers to two arrays which hold the number of parent elements for each face and the IDs of the parent elements for each face. The array with the element IDs is a 2D array. Each face's element parent IDs are in sorted order. Get an element parent ID by
elemParentsPerFace[FaceID][i];
where i is 0 ... numElemPerFace[faceID] - 1. These are big data arrays and should NOT be freed by the calling program.
Note that faces may not yet exist for the mesh, and if they don't, calling this function will build them (which may take some time).
Modifications:
10/27/05 WSD, created.
Parameters:
mesh input - mesh
numElemPerFace output - array of number of elem parents per face
elemParentsPerFace output - array of arrays of elem parent IDs, treat read only
Definition at line 4509 of file mesh.c.
References _fc_buildParents(), _fc_getMeshSlot(), _FC_MeshSlot::elemParentsPerFace, FC_AT_ELEMENT, FC_AT_FACE, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numElemPerFace, and _FC_MeshSlot::numFace.
Referenced by _fc_buildMeshElementNeighborsViaEntity(), _fc_getFaceParents(), _fc_writeExodusDataset(), calcFaceOrients(), fc_getMeshEntityChildren(), and main().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default return
  if (numElemPerFace)
    *numElemPerFace = NULL;
  if (elemParentsPerFace)
    *elemParentsPerFace = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || numElemPerFace == NULL ||
      elemParentsPerFace == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting parent elems of the faces on mesh '%s'",
                      meshSlot->header.name);
  // if it doesn't exist, build stuff
  if (meshSlot->numFace < 0 ||
      (meshSlot->numFace > 0 && meshSlot->numElemPerFace == NULL)) {
    rc = _fc_buildParents(mesh, FC_AT_FACE, FC_AT_ELEMENT);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // return pointers
  *numElemPerFace = meshSlot->numElemPerFace;
  *elemParentsPerFace = meshSlot->elemParentsPerFace;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_getMeshElementParentsOfVerticesPtr (FC_Mesh mesh, int ** numElemPerVert, int *** elemParentsPerVert)
Return parent elements of the vertices.
Description:
This routine returns pointers to two arrays which hold the number of parent elements for each vertex and the IDs of the parent elements for each vertex. The array with the element IDs is a 2D array. Each vertex's element parent IDs are in sorted order. Get an element parent ID by
elemParentsPerVert[VertID][i];
where i is 0 ... numElemPerVert[vertID] - 1. These are a big data arrays and should NOT be freed by the calling program.
Modifications:
10/27/05 WSD, created.
Parameters:
mesh input - mesh
numElemPerVert output - array of number of elem parents per vertex
elemParentsPerVert output - array of arrays of elem parent IDs, treat read only
Definition at line 4380 of file mesh.c.
References _fc_buildParents(), _fc_getMeshSlot(), _FC_MeshSlot::elemParentsPerVert, FC_AT_ELEMENT, FC_AT_VERTEX, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, and _FC_MeshSlot::numElemPerVert.
Referenced by _fc_buildMeshElementNeighborsViaEntity(), and _fc_getVertexParents().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default return
  if (numElemPerVert)
    *numElemPerVert = NULL;
  if (elemParentsPerVert)
    *elemParentsPerVert = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || numElemPerVert == NULL ||
      elemParentsPerVert == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting parent elems of the vertices on mesh '%s'",
                      meshSlot->header.name);
  // if it doesn't exist, build stuff
  if (!meshSlot->numElemPerVert) {
    rc = _fc_buildParents(mesh, FC_AT_VERTEX, FC_AT_ELEMENT);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // return pointers
  *numElemPerVert = meshSlot->numElemPerVert;
  *elemParentsPerVert = meshSlot->elemParentsPerVert;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_getMeshFaceParentsOfVerticesPtr (FC_Mesh mesh, int ** numFacePerVert, int *** faceParentsPerVert)
Return parent faces of the vertices.
Description:
This routine returns pointers to two arrays which hold the number of parent faces for each vertex and the IDs of the parent faces for each vertex. The array with the face IDs is a 2D array. Each vertex's face parent IDs are in sorted order. Get an face parent ID by
faceParentsPerVert[VertID][i];
where i is 0 ... numFacePerVert[vertID] - 1. These are big data arrays and should NOT be freed by the calling program.
Note that faces may not yet exist for the mesh, and if they don't, calling this function will build them (which may take some time).
Also note that if there cannot be any faces on the mesh (only happens for point and line meshes), NULLs will be returned instead of arrays.
Modifications:
10/27/05 WSD, created.
Parameters:
mesh input - mesh
numFacePerVert output - array of number of face parents per vertex
faceParentsPerVert output - array of arrays of face parent IDs, treat read only
Definition at line 4318 of file mesh.c.
References _fc_buildParents(), _fc_getMeshSlot(), _FC_MeshSlot::faceParentsPerVert, FC_AT_FACE, FC_AT_VERTEX, fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numFace, and _FC_MeshSlot::numFacePerVert.
Referenced by _fc_getEdgeParents(), _fc_getFaceNeighbors(), _fc_getVertexParents(), and main().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default return
  if (numFacePerVert)
    *numFacePerVert = NULL;
  if (faceParentsPerVert)
    *faceParentsPerVert = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || numFacePerVert == NULL ||
      faceParentsPerVert == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting parent faces of the vertices on mesh '%s'",
                      meshSlot->header.name);
  // if it doesn't exist, build stuff
  if (meshSlot->numFace < 0 ||
      (meshSlot->numFace > 0 && meshSlot->numFacePerVert == NULL)) {
    rc = _fc_buildParents(mesh, FC_AT_VERTEX, FC_AT_FACE);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // return pointers
  *numFacePerVert = meshSlot->numFacePerVert;
  *faceParentsPerVert = meshSlot->faceParentsPerVert;
  return FC_SUCCESS;
}
_FC_MeshSlot* _fc_getMeshSlot (FC_Mesh mesh)
Get a mesh slot from a mesh handle.
Description:
The slot id of the mesh handle is used to find the the slot in the mesh table. The identity is then verified by checking that the slot and the handle's uIDs are the same. On success, a pointer to the slot is returned. Otherwise a NULL pointer is returned.
Modifications:
2003-OCT-19 WSK Created to replace using _fc_checkhandle and GET_ID for better type checking (using pointer's to slots is less bug prone than lot's of xxxTable[xxxID] references).
05/25/04 WSK Changed to call new _fc_isHandleValid common to all tables.
Parameters:
mesh input - mesh
Definition at line 6054 of file mesh.c.
References _fc_isHandleValid(), meshTableSize, FC_Mesh::slotID, and FC_Mesh::uID.
Referenced by _fc_buildEdgeConns(), _fc_buildFaceConns(), _fc_buildMeshElementNeighborsViaEntity(), _fc_buildMeshVertexNeighborsViaEdge(), _fc_buildParents(), _fc_deleteMeshSlot(), _fc_exo_seqVar_meshID_cmp(), _fc_getMeshEdgeParentsOfVerticesPtr(), _fc_getMeshElementNeighborsViaEdgePtr(), _fc_getMeshElementNeighborsViaFacePtr(), _fc_getMeshElementNeighborsViaVertexPtr(), _fc_getMeshElementParentsOfEdgesPtr(), _fc_getMeshElementParentsOfFacesPtr(), _fc_getMeshElementParentsOfVerticesPtr(), _fc_getMeshExodusGlobalElementIDOffset(), _fc_getMeshExodusGlobalNodalIDsPtr(), _fc_getMeshFaceParentsOfVerticesPtr(), _fc_getMeshVertexNeighborsViaEdgePtr(), _fc_hasSharedLSDynaVertices(), _fc_loadExodusDataset(), _fc_loadLSDynaDataset(), _fc_readExodusAttributeData(), _fc_readExodusMeshCoords(), _fc_readExodusMeshElemConns(), _fc_readExodusOneStepVariableData(), _fc_readExodusSubsetMembers(), _fc_readLSDynaMeshCoords(), _fc_readLSDynaMeshElemConns(), _fc_readLSDynaVariableData(), _fc_readMeshCoords(), _fc_readMeshElemConns(), _fc_readSubsetMembers(), _fc_writeExodusDataset(), fc_changeMeshName(), fc_convertSeqSubsetToSubsets(), fc_convertSubsetsToSeqSubset(), fc_convertVariablesToSeqVariable(), fc_copyMesh(), fc_copySeqSubset(), fc_copySeqVariable(), fc_createSeqSubset(), fc_createSeqVariable(), fc_createSubset(), fc_createSubsetMesh(), fc_createVariable(), fc_deleteMesh(), fc_deleteSeqSubset(), fc_deleteSeqVariable(), fc_deleteSubset(), fc_deleteVariable(), fc_getDatasetFromMesh(), fc_getMeshCoordsAsVariable(), fc_getMeshCoordsPtr(), fc_getMeshDim(), fc_getMeshEdgeConnsPtr(), fc_getMeshEdgeFaceInfo(), fc_getMeshElementConnsPtr(), fc_getMeshElementFaceOrientsPtr(), fc_getMeshElementToEdgeConnsPtr(), fc_getMeshElementToFaceConnsPtr(), fc_getMeshElementType(), fc_getMeshFaceConnsPtr(), fc_getMeshFaceType(), fc_getMeshFaceTypesPtr(), fc_getMeshInfo(), fc_getMeshName(), fc_getMeshNumEdge(), fc_getMeshNumElement(), fc_getMeshNumEntity(), fc_getMeshNumFace(), fc_getMeshNumVertex(), fc_getMeshTopodim(), fc_getNumSeqSubset(), fc_getNumSeqVariable(), fc_getNumSubset(), fc_getNumVariable(), fc_getOrGenerateUniqueSeqVariableByName(), fc_getOrGenerateUniqueVariableByName(), fc_getSeqSubsetByName(), fc_getSeqSubsets(), fc_getSeqVariableByName(), fc_getSeqVariableComponentsByName(), fc_getSeqVariables(), fc_getSubsetByName(), fc_getSubsets(), fc_getVariableByName(), fc_getVariableComponentsByName(), fc_getVariables(), fc_isSeqSubsetValid(), fc_isSeqVariableValid(), fc_printMesh(), fc_releaseMesh(), fc_rewriteDataset(), fc_setMeshCoords(), fc_setMeshCoordsPtr(), fc_setMeshElementConns(), fc_setMeshElementConnsPtr(), fc_setVariableData(), and fc_setVariableDataPtr().
  {
  if (_fc_isHandleValid(mesh.slotID, mesh.uID, meshTableSize,
                        (_FC_SlotHeader**)meshTable))
    return meshTable[mesh.slotID];
  else
    return NULL;
}
_FC_MeshSlot* _fc_getMeshSlotFromID (int meshID)
Get a mesh slot based on ID.
Description:
The _FC_MeshSlot at the requested slotID is returned. This should only be used when you really know that it is the slot you want because there is no checking of the uID like with _fc_getMeshSlot. The only checking is that the slotID is exists in the table and that the uID is > 0 (i.e. it is not empty).
Modifications:
11/27/03 WSK Created so that external routines can index into tables without knowing about them.
05/25/04 WSK Changed to call new _fc_getSlot() common to all tables.
Definition at line 6082 of file mesh.c.
References _fc_getSlot(), and meshTableSize.
Referenced by fc_copyDataset(), fc_deleteSequence(), fc_getMeshByName(), and fc_getMeshes().
  {
  return (_FC_MeshSlot*) _fc_getSlot(meshID, meshTableSize,
                                     (_FC_SlotHeader**)meshTable);
}
int _fc_getMeshTableSize (void)
Get the size of the mesh table.
Modifications:
05/21/04 WSK Created.
Definition at line 6004 of file mesh.c.
References meshTableSize.
{
  return meshTableSize;
}
FC_ReturnCode _fc_getMeshVertexNeighborsViaEdgePtr (FC_Mesh mesh, int ** numVertNeighsViaEdge, int *** vertNeighsViaEdge)
Return vertex neighbors that share an edge.
Description:
This routine returns pointers to two arrays which hold the number of vertex neighbors for each vertex and the IDs of the vertex neighbors for each vertex. The array with the vertex IDs is a 2D array. Each vert's neighbor IDs are in sorted order. Get an vetex neighbor ID by
vertNeighsViaEdge[vertID][i];
where i is 0 ... numVertNeighsViaEdge[vertID] - 1. These are big data arrays and should NOT be freed by the calling program.
Note that edges may not yet exist for the mesh, and if they don't, calling this function will build them (which may take some time).
Also note that if there cannot be any edges on the mesh (only happens for point meshes), NULLs will be returned instead of arrays.
Modifications:
10/31/05 WSD, created.
Parameters:
mesh input - mesh
numVertNeighsViaEdge output - array of number of vert neighbors per vert (that share an edge)
vertNeighsViaEdge output - array of arrays of vert neighbor IDs, treat read only
Definition at line 4577 of file mesh.c.
References _fc_buildMeshVertexNeighborsViaEdge(), _fc_getMeshSlot(), fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, fc_printfLogMessage, FC_SUCCESS, _FC_MeshSlot::header, _FC_SlotHeader::name, _FC_MeshSlot::numEdge, _FC_MeshSlot::numVertNeighsViaEdge, and _FC_MeshSlot::vertNeighsViaEdge.
Referenced by _fc_getVertexNeighbors().
  {
  FC_ReturnCode rc;
  _FC_MeshSlot* meshSlot;
  // default return
  if (numVertNeighsViaEdge)
    *numVertNeighsViaEdge = NULL;
  if (vertNeighsViaEdge)
    *vertNeighsViaEdge = NULL;
  // check input
  meshSlot = _fc_getMeshSlot(mesh);
  if (meshSlot == NULL || numVertNeighsViaEdge == NULL ||
      vertNeighsViaEdge == NULL) {
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  // log message
  fc_printfLogMessage("Getting parent elems of the faces on mesh '%s'",
                      meshSlot->header.name);
  // if it doesn't exist, build stuff
  if (meshSlot->numEdge < 0 ||
      (meshSlot->numEdge > 0 && meshSlot->numVertNeighsViaEdge == NULL)) {
    rc = _fc_buildMeshVertexNeighborsViaEdge(mesh);
    if (rc != FC_SUCCESS)
      return rc;
  }
  // return pointers
  *numVertNeighsViaEdge = meshSlot->numVertNeighsViaEdge;
  *vertNeighsViaEdge = meshSlot->vertNeighsViaEdge;
  return FC_SUCCESS;
}
_FC_MeshSlot* _fc_getNewMeshSlot (void)
Get an empty mesh slot from the mesh table.
Description:
Will return a new slot or NULL. A NULL means a memory error occurred.
Modifications:
2003-MAY-01 W Koegler Created
12/08/03 WSK Changed because changed XTables from arrays of slots to arrays of handles to slots. The _fc_new_XSlot() routines do not call a common helper routine anymore.
5/11/04 WSK Moved common code from _fc_getNewDsSlot(), _fc_getNewSeqSlot(), etc to _fc_getNewSlot().
Definition at line 6024 of file mesh.c.
References _fc_getNewSlot(), _fc_initMeshSlot(), and meshTableSize.
Referenced by fc_createMesh().
{
  _FC_MeshSlot* meshSlot;
  meshSlot = (_FC_MeshSlot*) _fc_getNewSlot(&meshTableSize,
                             (_FC_SlotHeader***)&meshTable,
                           &meshOpenSlots, sizeof(_FC_MeshSlot));
  _fc_initMeshSlot(meshSlot);
  return meshSlot;
}
void _fc_initMeshSlot (_FC_MeshSlot * meshSlot)
Initialize a mesh slot.
Modifications: APR-30-2003 W Koegler Created. 03-03-08 ACG adding sequence subsets
Parameters:
meshSlot input - the mtable slot to initialize
Definition at line 5726 of file mesh.c.
References _fc_initSlotHeader(), _FC_MeshSlot::basicVarIDs, _FC_MeshSlot::coords, _FC_MeshSlot::coordVarID, _FC_MeshSlot::dim, _FC_MeshSlot::ds, _FC_MeshSlot::edgeParentsPerVert, _FC_MeshSlot::edgeToVertConns, _FC_MeshSlot::elemFaceOrients, _FC_MeshSlot::elemNeighsViaEdge, _FC_MeshSlot::elemNeighsViaFace, _FC_MeshSlot::elemNeighsViaVert, _FC_MeshSlot::elemParentsPerEdge, _FC_MeshSlot::elemParentsPerFace, _FC_MeshSlot::elemParentsPerVert, _FC_MeshSlot::elemToEdgeConns, _FC_MeshSlot::elemToFaceConns, _FC_MeshSlot::elemToVertConns, _FC_MeshSlot::elemType, _FC_MeshSlot::faceParentsPerVert, _FC_MeshSlot::faceToVertConns, _FC_MeshSlot::faceTypes, FC_ET_UNKNOWN, FC_NULL_DATASET, _FC_MeshSlot::fileInfo, _FC_MeshSlot::header, _FC_MeshFileIOInfo::id, _FC_MeshSlot::numBasicVar, _FC_MeshSlot::numEdge, _FC_MeshSlot::numEdgePerVert, _FC_MeshSlot::numElement, _FC_MeshSlot::numElemNeighsViaEdge, _FC_MeshSlot::numElemNeighsViaFace, _FC_MeshSlot::numElemNeighsViaVert, _FC_MeshSlot::numElemPerEdge, _FC_MeshSlot::numElemPerFace, _FC_MeshSlot::numElemPerVert, _FC_MeshSlot::numFace, _FC_MeshSlot::numFacePerVert, _FC_MeshSlot::numSeqSub, _FC_MeshSlot::numSeqVar, _FC_MeshSlot::numStepPerSeqSub, _FC_MeshSlot::numStepPerSeqVar, _FC_MeshSlot::numSub, _FC_MeshSlot::numVertex, _FC_MeshSlot::numVertNeighsViaEdge, _FC_MeshSlot::numVertPerFace, _FC_MeshSlot::seqSubIDs, _FC_MeshSlot::seqVarIDs, _FC_MeshSlot::subIDs, _FC_MeshSlot::topodim, and _FC_MeshSlot::vertNeighsViaEdge.
Referenced by _fc_clearMeshSlot(), and _fc_getNewMeshSlot().
  {
  // Note: tried to use the same order of members as the meshSlot declaration
  if (meshSlot != NULL) {
    _fc_initSlotHeader(&meshSlot->header);
    meshSlot->ds = FC_NULL_DATASET;
    //---
    meshSlot->fileInfo.id = -1;
    //---
    meshSlot->dim = 0;
    meshSlot->topodim = 0;
    meshSlot->numVertex = 0;
    meshSlot->numElement = 0;
    meshSlot->elemType = FC_ET_UNKNOWN;
    //---
    meshSlot->coords = NULL;
    meshSlot->elemToVertConns = NULL;
    //--
    meshSlot->numEdge = -1;
    meshSlot->numFace = -1;
    meshSlot->edgeToVertConns = NULL;
    meshSlot->faceTypes = NULL;
    meshSlot->numVertPerFace = NULL;
    meshSlot->faceToVertConns = NULL;
    meshSlot->elemToEdgeConns = NULL;
    meshSlot->elemToFaceConns = NULL;
    meshSlot->elemFaceOrients = NULL;
    //---
    meshSlot->numEdgePerVert = NULL;
    meshSlot->edgeParentsPerVert = NULL;
    meshSlot->numFacePerVert = NULL;
    meshSlot->faceParentsPerVert = NULL;
    meshSlot->numElemPerVert = NULL;
    meshSlot->elemParentsPerVert = NULL;
    meshSlot->numElemPerEdge = NULL;
    meshSlot->elemParentsPerEdge = NULL;
    meshSlot->numElemPerFace = NULL;
    meshSlot->elemParentsPerFace = NULL;
    //---
    meshSlot->numVertNeighsViaEdge = NULL;
    meshSlot->vertNeighsViaEdge = NULL;
    meshSlot->numElemNeighsViaVert = NULL;
    meshSlot->elemNeighsViaVert = NULL;
    meshSlot->numElemNeighsViaEdge = NULL;
    meshSlot->elemNeighsViaEdge = NULL;
    meshSlot->numElemNeighsViaFace = NULL;
    meshSlot->elemNeighsViaFace = NULL;
    //---
    meshSlot->numSub = 0;
    meshSlot->subIDs = NULL;
    meshSlot->numSeqSub = 0;
    meshSlot->numStepPerSeqSub = NULL;
    meshSlot->seqSubIDs = NULL;
    //---
    meshSlot->coordVarID = -1;
    meshSlot->numBasicVar = 0;
    meshSlot->basicVarIDs = NULL;
    meshSlot->numSeqVar = 0;
    meshSlot->numStepPerSeqVar = NULL;
    meshSlot->seqVarIDs = NULL;
  }
}
void _fc_printMeshTable (char * label)
Print the contents of the Mesh Table (meshTable) to stderr.
Description:
Prints the contents of the Mesh Table in a human readable form. It takes a string to use as a label for this print out of the table. Pass NULL if you don't want a label.
Modifications:
Nancy Collins Created.
2003-NOV-13 WSK Fixed up.
03-03-08 ACG added seqSubset
Parameters:
label Input - label for this version the table (without a trailing \n) pass NULL if no label is desired
Definition at line 6133 of file mesh.c.
References _fc_printSlotHeader(), _FC_MeshSlot::basicVarIDs, _FC_MeshSlot::coords, _FC_MeshSlot::coordVarID, _FC_MeshSlot::dim, _FC_MeshSlot::ds, _FC_MeshSlot::edgeParentsPerVert, _FC_MeshSlot::edgeToVertConns, _FC_MeshSlot::elemFaceOrients, _FC_MeshSlot::elemNeighsViaEdge, _FC_MeshSlot::elemNeighsViaFace, _FC_MeshSlot::elemNeighsViaVert, _FC_MeshSlot::elemParentsPerEdge, _FC_MeshSlot::elemParentsPerFace, _FC_MeshSlot::elemParentsPerVert, _FC_MeshSlot::elemToEdgeConns, _FC_MeshSlot::elemToFaceConns, _FC_MeshSlot::elemToVertConns, _FC_MeshSlot::elemType, _FC_MeshSlot::faceParentsPerVert, _FC_MeshSlot::faceToVertConns, _FC_MeshSlot::faceTypes, fc_getElementTypeFaceType(), fc_getElementTypeText(), _FC_MeshSlot::header, meshTableSize, _FC_MeshSlot::numBasicVar, _FC_MeshSlot::numEdge, _FC_MeshSlot::numEdgePerVert, _FC_MeshSlot::numElement, _FC_MeshSlot::numElemNeighsViaEdge, _FC_MeshSlot::numElemNeighsViaFace, _FC_MeshSlot::numElemNeighsViaVert, _FC_MeshSlot::numElemPerEdge, _FC_MeshSlot::numElemPerFace, _FC_MeshSlot::numElemPerVert, _FC_MeshSlot::numFace, _FC_MeshSlot::numFacePerVert, _FC_MeshSlot::numSeqSub, _FC_MeshSlot::numSeqVar, _FC_MeshSlot::numStepPerSeqSub, _FC_MeshSlot::numStepPerSeqVar, _FC_MeshSlot::numSub, _FC_MeshSlot::numVertex, _FC_MeshSlot::numVertNeighsViaEdge, _FC_MeshSlot::numVertPerFace, _FC_MeshSlot::seqSubIDs, _FC_MeshSlot::seqVarIDs, FC_Dataset::slotID, _FC_MeshSlot::subIDs, TABLE_DIVIDER_STRING, _FC_MeshSlot::topodim, FC_Dataset::uID, and _FC_MeshSlot::vertNeighsViaEdge.
  {
  int i, j, k;
  _FC_MeshSlot* meshSlot;
  // print table heading
  fprintf(stderr, TABLE_DIVIDER_STRING);
  fprintf(stderr, "Mesh Table (meshTable):\n");
  if (label != NULL)
    fprintf(stderr, "%s\n", label);
  fprintf(stderr, TABLE_DIVIDER_STRING);
  fflush(NULL);
  // We're done if it's empty
  if (meshTableSize < 1) {
    fprintf(stderr, "(empty)\n");
    fprintf(stderr, "\n");
    fflush(NULL);
    return;
  }
  // print contents for each slot
  for (i = 0; i <  meshTableSize; i++) {
    meshSlot = meshTable[i];
    fprintf(stderr, "%3d: %s\n", i, (meshSlot) ? "exists" : "NULL");
    if (meshSlot == NULL)
      continue;
    _fc_printSlotHeader(meshSlot->header);
    fprintf(stderr, "     FC_Dataset = { %d, %d }\n",
            meshSlot->ds.slotID, meshSlot->ds.uID);
    fprintf(stderr, "     dim = %d, topodim = %d\n",
            meshSlot->dim, meshSlot->topodim);
    fprintf(stderr, "     numVertex = %d, coords = %s\n",
            meshSlot->numVertex, (meshSlot->coords) ? "exists" : "NULL");
    fprintf(stderr, "     numElement = %d, elemType = %s, elemConns = %s\n",
            meshSlot->numElement, fc_getElementTypeText(meshSlot->elemType),
            (meshSlot->elemToVertConns) ? "exists" : "NULL");
    fprintf(stderr, "     numEdge = %d, edgeConns = %s, elemToEdgeConns = %s\n",
            meshSlot->numEdge, (meshSlot->edgeToVertConns) ? "exists" : "NULL",
            (meshSlot->elemToEdgeConns) ? "exists" : "NULL");
    fprintf(stderr, "     numFace = %d, faceType = %s, faceTypes = %s\n",
            meshSlot->numFace,
            fc_getElementTypeText(fc_getElementTypeFaceType(meshSlot->elemType)),
            (meshSlot->faceTypes) ? "exists" : "NULL");
    fprintf(stderr, "         numVertPerFace = %s, faceConns = %s\n",
            (meshSlot->numVertPerFace) ? "exists" : "NULL",
            (meshSlot->faceToVertConns) ? "exists" : "NULL");
    fprintf(stderr, "         elemToFaceConns = %s, elemFaceOrients = %s\n",
            (meshSlot->elemToFaceConns) ? "exists" : "NULL",
            (meshSlot->elemFaceOrients) ? "exists" : "NULL");
    fprintf(stderr, "     numEdgePerVert = %s, edgeParentsPerVert = %s\n",
            (meshSlot->numEdgePerVert) ? "exists" : "NULL",
            (meshSlot->edgeParentsPerVert) ? "exists" : "NULL");
    fprintf(stderr, "     numFacePerVert = %s, faceParentsPerVert = %s\n",
            (meshSlot->numFacePerVert) ? "exists" : "NULL",
            (meshSlot->faceParentsPerVert) ? "exists" : "NULL");
    fprintf(stderr, "     numElemPerVert = %s, elemParentsPerVert = %s\n",
            (meshSlot->numElemPerVert) ? "exists" : "NULL",
            (meshSlot->elemParentsPerVert) ? "exists" : "NULL");
    fprintf(stderr, "     numElemPerEdge = %s, elemParentsPerEdge = %s\n",
            (meshSlot->numElemPerEdge) ? "exists" : "NULL",
            (meshSlot->elemParentsPerEdge) ? "exists" : "NULL");
    fprintf(stderr, "     numElemPerFace = %s, elemParentsPerFace = %s\n",
            (meshSlot->numElemPerFace) ? "exists" : "NULL",
            (meshSlot->elemParentsPerFace) ? "exists" : "NULL");
    fprintf(stderr, "     numVertNeighsViaEdge = %s, vertNeighsViaEdge = %s\n",
            (meshSlot->numVertNeighsViaEdge) ? "exists" : "NULL",
            (meshSlot->vertNeighsViaEdge) ? "exists" : "NULL");
    fprintf(stderr, "     numElemNeighsViaVert = %s, elemNeighsViaVert = %s\n",
            (meshSlot->numElemNeighsViaVert) ? "exists" : "NULL",
            (meshSlot->elemNeighsViaVert) ? "exists" : "NULL");
    fprintf(stderr, "     numElemNeighsViaEdge = %s, elemNeighsViaEdge = %s\n",
            (meshSlot->numElemNeighsViaEdge) ? "exists" : "NULL",
            (meshSlot->elemNeighsViaEdge) ? "exists" : "NULL");
    fprintf(stderr, "     numElemNeighsViaFace = %s, elemNeighsViaFace = %s\n",
            (meshSlot->numElemNeighsViaFace) ? "exists" : "NULL",
            (meshSlot->elemNeighsViaFace) ? "exists" : "NULL");
    fprintf(stderr, "     numSub = %d, subIDs = ", meshSlot->numSub);
    if (meshSlot->numSub == 0)
      fprintf(stderr, "NULL\n");
    else {
      fprintf(stderr, "{ %d", meshSlot->subIDs[0]);
      for (j = 1; j < meshSlot->numSub; j++)
        fprintf(stderr, ", %d", meshSlot->subIDs[j]);
      fprintf(stderr, " }\n");
    }
    fprintf(stderr, "     numSeqSub = %d, seqSubIDs = ", meshSlot->numSeqSub);
    if (!meshSlot->seqSubIDs)
      fprintf(stderr, "NULL\n");
    else {
      fprintf(stderr, "{\n");
      for (j = 0; j < meshSlot->numSeqSub; j++) {
     fprintf(stderr, "         seqSubIDs[%d] = { %d", j,
                  meshSlot->seqSubIDs[j][0]);
     for (k = 1; k < meshSlot->numStepPerSeqSub[j]; k++)
       fprintf(stderr, ", %d", meshSlot->seqSubIDs[j][k]);
     fprintf(stderr, " }\n");
      }
      fprintf(stderr, "     }\n");
    }
    fprintf(stderr, "     coordVarID = %d\n", meshSlot->coordVarID);
    fprintf(stderr, "     numBasicVar = %d, basicVarIDs = ",
            meshSlot->numBasicVar);
    if (meshSlot->numBasicVar == 0)
      fprintf(stderr, "NULL\n");
    else {
      fprintf(stderr, "{ %d", meshSlot->basicVarIDs[0]);
      for (j = 1; j < meshSlot->numBasicVar; j++)
        fprintf(stderr, ", %d", meshSlot->basicVarIDs[j]);
      fprintf(stderr, " }\n");
    }
    fprintf(stderr, "     numSeqVar = %d, numStepPerSeqVar = ", meshSlot->numSeqVar);
    if (!meshSlot->numStepPerSeqVar)
      fprintf(stderr, "NULL\n");
    else {
      fprintf(stderr, "{ %d", meshSlot->numStepPerSeqVar[0]);
      for (j = 1; j < meshSlot->numSeqVar; j++)
        fprintf(stderr, ", %d", meshSlot->numStepPerSeqVar[j]);
      fprintf(stderr, " }\n");
    }
    fprintf(stderr, "     seqVarIDs = ");
    if (!meshSlot->seqVarIDs)
      fprintf(stderr, "NULL\n");
    else {
      fprintf(stderr, "{\n");
      for (j = 0; j < meshSlot->numSeqVar; j++) {
     fprintf(stderr, "         seqVarIDs[%d] = { %d", j,
                  meshSlot->seqVarIDs[j][0]);
     for (k = 1; k < meshSlot->numStepPerSeqVar[j]; k++)
       fprintf(stderr, ", %d", meshSlot->seqVarIDs[j][k]);
     fprintf(stderr, " }\n");
      }
      fprintf(stderr, "     }\n");
    }
    fflush(NULL);
  }
  fprintf(stderr, "\n");
  fflush(NULL);
  return;
}
void _fc_releaseMeshSlot (_FC_MeshSlot * meshSlotp)
Release non-necessary information in a mesh slot.
Description:
Releases the coordinates, connectivities and topology structures.
Todo:
Make this smarter ....
Modifications: Aug 6, 2002 W Koegler Created
Parameters:
meshSlotp input - mtable pointer
Definition at line 5804 of file mesh.c.
References _FC_MeshSlot::coords, _FC_MeshSlot::edgeParentsPerVert, _FC_MeshSlot::edgeToVertConns, _FC_MeshSlot::elemFaceOrients, _FC_MeshSlot::elemNeighsViaEdge, _FC_MeshSlot::elemNeighsViaFace, _FC_MeshSlot::elemNeighsViaVert, _FC_MeshSlot::elemParentsPerEdge, _FC_MeshSlot::elemParentsPerFace, _FC_MeshSlot::elemParentsPerVert, _FC_MeshSlot::elemToEdgeConns, _FC_MeshSlot::elemToFaceConns, _FC_MeshSlot::elemToVertConns, _FC_MeshSlot::faceParentsPerVert, _FC_MeshSlot::faceToVertConns, _FC_MeshSlot::faceTypes, _FC_MeshSlot::numEdge, _FC_MeshSlot::numEdgePerVert, _FC_MeshSlot::numElement, _FC_MeshSlot::numElemNeighsViaEdge, _FC_MeshSlot::numElemNeighsViaFace, _FC_MeshSlot::numElemNeighsViaVert, _FC_MeshSlot::numElemPerEdge, _FC_MeshSlot::numElemPerFace, _FC_MeshSlot::numElemPerVert, _FC_MeshSlot::numFace, _FC_MeshSlot::numFacePerVert, _FC_MeshSlot::numVertex, _FC_MeshSlot::numVertNeighsViaEdge, _FC_MeshSlot::numVertPerFace, and _FC_MeshSlot::vertNeighsViaEdge.
Referenced by _fc_clearMeshSlot().
  {
  int i;
  // release big data
  //---
  if (meshSlotp->coords) {
    free(meshSlotp->coords);
    meshSlotp->coords = NULL;
  }
  if (meshSlotp->elemToVertConns) {
    free(meshSlotp->elemToVertConns);
    meshSlotp->elemToVertConns = NULL;
  }
  //---
  if (meshSlotp->edgeToVertConns) {
    free(meshSlotp->edgeToVertConns);
    meshSlotp->edgeToVertConns = NULL;
  }
  if (meshSlotp->faceTypes) {
    free(meshSlotp->faceTypes);
    meshSlotp->faceTypes = NULL;
  }
  if (meshSlotp->numVertPerFace) {
    free(meshSlotp->numVertPerFace);
    meshSlotp->numVertPerFace = NULL;
  }
  if (meshSlotp->faceToVertConns) {
    free(meshSlotp->faceToVertConns);
    meshSlotp->faceToVertConns = NULL;
  }
  if (meshSlotp->elemToEdgeConns) {
    free(meshSlotp->elemToEdgeConns);
    meshSlotp->elemToEdgeConns = NULL;
  }
  if (meshSlotp->elemToFaceConns) {
    free(meshSlotp->elemToFaceConns);
    meshSlotp->elemToFaceConns = NULL;
  }
  if (meshSlotp->elemFaceOrients) {
    free(meshSlotp->elemFaceOrients);
    meshSlotp->elemFaceOrients = NULL;
  }
  //---
  if (meshSlotp->numEdgePerVert) {
    free(meshSlotp->numEdgePerVert);
    meshSlotp->numEdgePerVert = NULL;
  }
  if (meshSlotp->edgeParentsPerVert) {
    for (i = 0; i < meshSlotp->numVertex; i++)
      free(meshSlotp->edgeParentsPerVert[i]);
    free(meshSlotp->edgeParentsPerVert);
    meshSlotp->edgeParentsPerVert = NULL;
  }
  if (meshSlotp->numFacePerVert) {
    free(meshSlotp->numFacePerVert);
    meshSlotp->numFacePerVert = NULL;
  }
  if (meshSlotp->faceParentsPerVert) {
    for (i = 0; i < meshSlotp->numVertex; i++)
      free(meshSlotp->faceParentsPerVert[i]);
    free(meshSlotp->faceParentsPerVert);
    meshSlotp->faceParentsPerVert = NULL;
  }
  if (meshSlotp->numElemPerVert) {
    free(meshSlotp->numElemPerVert);
    meshSlotp->numElemPerVert = NULL;
  }
  if (meshSlotp->elemParentsPerVert) {
    for (i = 0; i < meshSlotp->numVertex; i++)
      free(meshSlotp->elemParentsPerVert[i]);
    free(meshSlotp->elemParentsPerVert);
    meshSlotp->elemParentsPerVert = NULL;
  }
  if (meshSlotp->numElemPerEdge) {
    free(meshSlotp->numElemPerEdge);
    meshSlotp->numElemPerEdge = NULL;
  }
  if (meshSlotp->elemParentsPerEdge) {
    for (i = 0; i < meshSlotp->numEdge; i++)
      free(meshSlotp->elemParentsPerEdge[i]);
    free(meshSlotp->elemParentsPerEdge);
    meshSlotp->elemParentsPerEdge = NULL;
  }
   if (meshSlotp->numElemPerFace) {
    free(meshSlotp->numElemPerFace);
    meshSlotp->numElemPerFace = NULL;
  }
  if (meshSlotp->elemParentsPerFace) {
    for (i = 0; i < meshSlotp->numFace; i++)
      free(meshSlotp->elemParentsPerFace[i]);
    free(meshSlotp->elemParentsPerFace);
    meshSlotp->elemParentsPerFace = NULL;
  }
  //---
  if (meshSlotp->numVertNeighsViaEdge) {
    free(meshSlotp->numVertNeighsViaEdge);
    meshSlotp->numVertNeighsViaEdge = NULL;
  }
  if (meshSlotp->vertNeighsViaEdge) {
    for (i = 0; i < meshSlotp->numVertex; i++)
      free(meshSlotp->vertNeighsViaEdge[i]);
    free(meshSlotp->vertNeighsViaEdge);
    meshSlotp->vertNeighsViaEdge = NULL;
  }
  if (meshSlotp->numElemNeighsViaVert) {
    free(meshSlotp->numElemNeighsViaVert);
    meshSlotp->numElemNeighsViaVert = NULL;
  }
  if (meshSlotp->elemNeighsViaVert) {
    for (i = 0; i < meshSlotp->numElement; i++)
      free(meshSlotp->elemNeighsViaVert[i]);
    free(meshSlotp->elemNeighsViaVert);
    meshSlotp->elemNeighsViaVert = NULL;
  }
  if (meshSlotp->numElemNeighsViaEdge) {
    free(meshSlotp->numElemNeighsViaEdge);
    meshSlotp->numElemNeighsViaEdge = NULL;
  }
  if (meshSlotp->elemNeighsViaEdge) {
    for (i = 0; i < meshSlotp->numElement; i++)
      free(meshSlotp->elemNeighsViaEdge[i]);
    free(meshSlotp->elemNeighsViaEdge);
    meshSlotp->elemNeighsViaEdge = NULL;
  }
  if (meshSlotp->numElemNeighsViaFace) {
    free(meshSlotp->numElemNeighsViaFace);
    meshSlotp->numElemNeighsViaFace = NULL;
  }
  if (meshSlotp->elemNeighsViaFace) {
    for (i = 0; i < meshSlotp->numElement; i++)
      free(meshSlotp->elemNeighsViaFace[i]);
    free(meshSlotp->elemNeighsViaFace);
    meshSlotp->elemNeighsViaFace = NULL;
  }
  //---
  meshSlotp->numEdge = -1;
  meshSlotp->numFace = -1;
  return;
}
FC_ReturnCode _fc_setSphereCoords (int numVerts, FC_Coords center, double radius, double * coords)
Set coordinates for a sphere mesh.
Description:
This function creates a spehere mesh.
Note: numVerts must equal sqrt((numVerts-2)^2)+2 Note: the user supplies the coords array. This function just fills it in (no boundary checks are performed)
Modifications:
04/08/2008 CDU Created
Parameters:
numVerts Input - the number of vertices that describe the sphere.
center Input - coordinate for where sphere's center is located
radius Input - the radius of the spehere
coords Output - the pre-allocated array that holds the vertex coordinates
Definition at line 1875 of file mesh.c.
References fc_getReturnCodeText(), FC_INPUT_ERROR, fc_printfErrorMessage, and FC_SUCCESS.
Referenced by fc_createSphereMesh(), and fc_setSphereDisplacementVariable().
 {
  int numPlane;
  int place, zcount, i;
  const int numDim=3;
  double phi, theta;
  const double toRad = (M_PI/180.0);
  //quick check to make sure not null ptr
  if(!center || !coords){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_SUCCESS;
  }
  //Verify that we were given something with the right number of coordinates
  numPlane = sqrt(numVerts-2);
  if(numPlane*numPlane != numVerts-2){
    fc_printfErrorMessage("%s : given a number vertices that isn't sqrt((numVerts-2)^2)+2 == numVerts", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  }
  //Work your way down all of the planes and all the circles
  place =0;
  phi  =180.0/(double)(numPlane+1);
  theta=360.0/(double)numPlane;
  for(zcount=1; zcount<=numPlane; zcount++){
    double zplane = cos((double)zcount*phi*toRad);
    for(i=0;i<numPlane; i++){
      double r=sqrt(1-zplane*zplane);
      coords[place*numDim+0] = center[0] + radius*(r*cos(theta*(double)i*toRad));
      coords[place*numDim+1] = center[1] + radius*(r*sin(theta*(double)i*toRad));
      coords[place*numDim+2] = center[2] + radius*zplane;
      //printf("(Plane %d Spot %d) <%.3lf, %.3lf, %.3lf>\n", zcount, place,
      //     coords[place*numDim+0],coords[place*numDim+1],coords[place*numDim+2]);
      place++;
    }
  }
  //Top
  coords[place*numDim+0] = center[0] + 0.0;
  coords[place*numDim+1] = center[1] + 0.0;
  coords[place*numDim+2] = center[2] + radius;
  place++;
  //Bottom
  coords[place*numDim+0] = center[0] + 0.0;
  coords[place*numDim+1] = center[1] + 0.0;
  coords[place*numDim+2] = center[2] - radius;
  place++;
  return FC_SUCCESS;
}
Variable Documentation
FC_SortedIntArray meshOpenSlots = { 0, 0, 0 } [static]
The list of unused slots in the mesh table.
Definition at line 102 of file mesh.c.
_FC_MeshSlot** meshTable = NULL [static]
The mesh table.
Definition at line 97 of file mesh.c.
int meshTableSize = 0 [static]
The number of allocated slots in the mesh table.
Definition at line 92 of file mesh.c.
Referenced by _fc_deleteMeshSlot(), _fc_freeMeshTable(), _fc_getMeshSlot(), _fc_getMeshSlotFromID(), _fc_getMeshTableSize(), _fc_getNewMeshSlot(), _fc_printMeshTable(), and fc_isMeshValid().