FCLib: (Private)
(Private)
[Series Routines]
Functions
FC_ReturnCode _fc_makeNewSeqVar (int numStep, FC_Variable *seqvar, char *varname, FC_Variable **newseqvar)
Makes a new seq var on the mesh that is on the same sequence as a given variable. this is a helper function. inputs are not checked.
FC_ReturnCode _fc_createSeqVariableFromVariable (int numStep, FC_Sequence seq, FC_Variable normal, char *seq_var_name, FC_Variable **seqvar)
Given a regular multi-datapoint variable, make a sequence variable from it.
Function Documentation
FC_ReturnCode _fc_createSeqVariableFromVariable (int numStep, FC_Sequence seq, FC_Variable normal, char * seq_var_name, FC_Variable ** seqvar)
Given a regular multi-datapoint variable, make a sequence variable from it.
Description:
Given a regular multi-datapoint variable, make a sequence variable from it. Each data point maps into a different step in the sequence (lenght of sequnce = num data point) in the order they are in the regular variable's data array. Values then are assigned the assocation FC_AT_WHOLE_MESH.
A sequence must be provided such that the length of the sequence must equal the number of datapoints. fc_createRegularSequence exists in sequence module for assistance with that.
Handles multi component data.
NOTE: becuase this uses createSeqVariable the user must call deleteseqvariable *and* free when deallocating it unless delete gets changed.
Modifications:
2/1/05 ACG, Moved here from checkstats.c and renamed from fc_seqVarFromNormalVar to fc_createSeqVariableFromRegularVariable
2/2/05 ACG, changed to require user to pass in sequence, so that user can create several seq variables on the same sequence by this method. seqvars have to be on the same sequence to use the seqvar comparison routines in this module. Removed word "regular" from title so as not to confuse with use of "regular" elsewhere in this module. -2/10/05 ACG moved to private, since it may or may not be something we want to keep since ordering isnt necessarily meaningful in the translations. nevertheless, its worth hanging onto for the time being
01/09/06 ACG changing/removing handling/cleanup in case of datatype error at WSK recommendation since it skews the coverage testing. Either there is already an explict type check or if those lines are reached you've got serious errors and the cleanup doesnt matter.
Parameters:
numStep input - numstep in the provided seq
seq input - handle to the provided sequence
normal input - the regular variable
seq_var_name output - name of the new seq variable
seqvar output - handles to the new seq var
Definition at line 205 of file series.c.
References FC_AT_WHOLE_MESH, fc_createSeqVariable(), fc_deleteSeqVariable(), FC_DT_CHAR, FC_DT_DOUBLE, FC_DT_FLOAT, FC_DT_INT, fc_getMeshFromVariable(), fc_getReturnCodeText(), fc_getVariableDataPtr(), fc_getVariableInfo(), FC_INPUT_ERROR, fc_isSequenceValid(), fc_isVariableValid(), fc_printfErrorMessage, fc_printfLogMessage, fc_setVariableData(), FC_SUCCESS, and numComponent.
 {
  FC_ReturnCode rc;
  int i;
  FC_Mesh mesh;
  FC_MathType mathtype;
  FC_DataType datatype;
  FC_AssociationType assoc;
  int numComponent, numDataPoint, mystery;
  void *data, *dcounter;
  if (seqvar)
    *seqvar = NULL;
  if ((!fc_isVariableValid(normal)) || (!fc_isSequenceValid(seq))
      || seq_var_name == NULL){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(FC_INPUT_ERROR));
    return FC_INPUT_ERROR;
  };
  rc = fc_getVariableInfo (normal,&numDataPoint,&numComponent,
                          &assoc, &mathtype, &datatype);
  if (rc != FC_SUCCESS)
    return rc;
  if (numDataPoint != numStep){
    fc_printfErrorMessage("%s", "invalid sized seq for this regular variable");
    return FC_INPUT_ERROR;
  }
  fc_printfLogMessage("Creating seqvar from var");
  if (datatype != FC_DT_INT && datatype != FC_DT_FLOAT &&
      datatype != FC_DT_DOUBLE &&
      datatype != FC_DT_CHAR){
    fc_printfErrorMessage("Cant handle this datatype");
    return FC_INPUT_ERROR;
  }
  rc = fc_getMeshFromVariable(normal,&mesh);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_createSeqVariable(mesh,seq,seq_var_name,
                            &mystery, seqvar);
  if (rc != FC_SUCCESS)
    return rc;
  rc = fc_getVariableDataPtr(normal,&data);
  if (rc != FC_SUCCESS){
    fc_deleteSeqVariable(numStep,*seqvar);
    free(*seqvar);
    *seqvar=NULL;
    return rc;
  }
  for (i = 0; i <numStep; i++){
    switch (datatype){
    case FC_DT_INT:
      dcounter = &(((int*)data)[i*numComponent]);
      break;
    case FC_DT_FLOAT:
      dcounter = &(((float*)data)[i*numComponent]);
      break;
    case FC_DT_DOUBLE:
      dcounter = &(((double*)data)[i*numComponent]);
      break;
    default: //its a char cuase i checked types above
      dcounter = &(((char*)data)[i*numComponent]);
      break;
    }
    rc = fc_setVariableData((*seqvar)[i],1,numComponent,
                            FC_AT_WHOLE_MESH,mathtype,
                            datatype,dcounter);
    if (rc != FC_SUCCESS){
      fc_deleteSeqVariable(numStep,*seqvar);
      free(*seqvar);
      *seqvar=NULL;
      return rc;
    }
  }
  data = NULL;
  return FC_SUCCESS;
}
FC_ReturnCode _fc_makeNewSeqVar (int numStep, FC_Variable * seqvar, char * varname, FC_Variable ** newseqvar)
Makes a new seq var on the mesh that is on the same sequence as a given variable. this is a helper function. inputs are not checked.
Description:
Makes a new seq var on the mesh that is on the same sequence as a given variable. this is a helper function. inputs are not checked.
Like fc_createSeqVariable, it actaully allocates the memory for the array here. Since this uses createseqvar, the user has to call a deleteSeqvar *and* a free on the seq var when deallocating it, unless delete gets changed.
Modifications:
1/26/05 ACG, Created
Parameters:
numStep input - numSteps in orig seq
seqvar input - orig seq var
varname output - name of new seq
newseqvar output - new seqvar
Definition at line 122 of file series.c.
References fc_createSeqVariable(), fc_deleteSeqVariable(), fc_getMeshFromVariable(), fc_getReturnCodeText(), fc_getSequenceFromSeqVariable(), fc_printfErrorMessage, and FC_SUCCESS.
Referenced by fc_centeredWindowAverage(), fc_centeredWindowAverage_Time(), fc_firstDerivative_REA(), fc_leadingWindowAverage(), fc_leadingWindowAverage_Time(), and fc_normalForm().
   {
  FC_ReturnCode rc;
  FC_Mesh mesh;
  FC_Sequence seq;
  int newSteps;
  //not checking input since helper function
  rc = fc_getMeshFromVariable(seqvar[0],&mesh);
  if (rc != FC_SUCCESS){
    fc_printfErrorMessage("%s", fc_getReturnCodeText(rc));
    return rc;
  }
  rc = fc_getSequenceFromSeqVariable(numStep,seqvar,&seq);
  if (rc != FC_SUCCESS)
    return rc;
  //like the implementation of fc_createSeqVariable method,
  //actaully allocating the memory for the return variable here.
  //but i will free it in case of error, if i can
  rc = fc_createSeqVariable(mesh, seq, varname, &newSteps,newseqvar);
  if (rc != FC_SUCCESS){
    fc_deleteSeqVariable(newSteps, *newseqvar);
    free(*newseqvar);
    *newseqvar=NULL;
    return rc;
  }
  return FC_SUCCESS;
}