FCLib: (Private)
(Private)
[Library]
Obtain the number of error, warning, log, and debug messages that were posted.
static FC_VerbosityLevel library_verbosity = FC_QUIET
Global variable for Verbosity level of the library.
void fc_printLogCounters (FC_VerbosityLevel minLevel)
Obtain the number of error, warning, log, and debug messages that were posted.
Functions
int _fc_isLibraryInit (void)
Check initialization state of library.
Variables
static int library_init = 0
Global variable for initialization state of the library.
FC_LogCount _fc_log_count = {0,0,0,0}
Global variable for counting error, warning, log, and debug messages.
Function Documentation
int _fc_isLibraryInit (void)
Check initialization state of library.
Description:
Returns true (1) is library is available for use.
Modifications:
05/20/04 W Koegler Created.
Definition at line 326 of file library.c.
References library_init.
Referenced by _fc_loadExodusDataset(), _fc_loadLSDynaDataset(), fc_createDataset(), fc_getDatasetByName(), fc_getDatasets(), fc_getNumDataset(), and fc_loadDatasetWithFormat().
{
  return library_init;
}
void fc_printLogCounters (FC_VerbosityLevel minLevel)
Obtain the number of error, warning, log, and debug messages that were posted.
Description:
This function prints out info about how many error, warning, log, and debug messages were posted. The user can provide a verbosity setting to prevent
Modifications:
2/20/2008 CDU Created
Definition at line 115 of file library.c.
References FC_LogCount::debugs, FC_LogCount::errors, FC_DEBUG_MESSAGES, FC_ERROR_MESSAGES, FC_LOG_MESSAGES, FC_WARNING_MESSAGES, FC_LogCount::logs, and FC_LogCount::warnings.
Referenced by main().
{
  if( ((minLevel >= FC_ERROR_MESSAGES)   && (_fc_log_count.errors))   ||
      ((minLevel >= FC_WARNING_MESSAGES) && (_fc_log_count.warnings)) ||
      ((minLevel >= FC_LOG_MESSAGES)     && (_fc_log_count.logs))     ||
      ((minLevel >= FC_DEBUG_MESSAGES)   && (_fc_log_count.debugs))      )
    fprintf(stderr," FCLib Message Summary: %d Errors, %d Warnings, %d Logs, %d Debugs\n",
         _fc_log_count.errors,_fc_log_count.warnings,_fc_log_count.logs,_fc_log_count.debugs);
}
Variable Documentation
FC_LogCount _fc_log_count = {0,0,0,0}
Global variable for counting error, warning, log, and debug messages.
Definition at line 97 of file library.c.
int library_init = 0 [static]
Global variable for initialization state of the library.
Description:
1 = initialized, 0 = not initialized.
Definition at line 87 of file library.c.
Referenced by _fc_isLibraryInit(), fc_finalLibrary(), and fc_initLibrary().
FC_VerbosityLevel library_verbosity = FC_QUIET [static]
Global variable for Verbosity level of the library.
Definition at line 129 of file library.c.
Referenced by fc_getLibraryVerbosity(), and fc_setLibraryVerbosity().