FCLib: tools/skeleton/lib_skeleton.h File Reference
tools/skeleton/lib_skeleton.h File Reference
Data Structures
struct spanning_tree_node_t
struct spanning_tree_t
Defines
#define emsg(a, args...) {fprintf(stderr,"Error in %s()[%s:%d] " a "\n", __func__, __FILE__, __LINE__, ## args); exit(-1); }
#define dbg(a, args...) { if(_skeleton_dbg>1) printf("DBG:" a "\n", ## args); }
#define info(a, args...) { if(_skeleton_dbg) printf(a "\n", ## args); }
#define FREE(a) { if(!a) emsg("Free on NULL pointer?"); free(a); a=NULL; }
Enumerations
enum whittleAlgorithm_t {
FC_WA_UNKNOWN = -1,
FC_WA_UNSPECIFIED = 0,
FC_WA_OCTANTS = 1,
FC_WA_MIN_DESCENDANTS = 2,
FC_WA_MIN_SEGMENT_LENGTHS = 3,
FC_WA_MIN_ANGLE_CHANGE = 4
}
Functions
int _fc_compareSpanningTreeNodes (const void *a, const void *b)
FC_ReturnCode _fc_getIntersectionPointBetweenElements (int elemID_1, int elemID_2, int dim, int vertPerElement, int *conn_list, double *verts, FC_Coords *results)
int doesSeqVarExist (FC_Mesh m, char *seqvar_name)
FC_ReturnCode fc_getElementCenters (FC_Mesh m, FC_Variable displ, double **centers)
void printTree (spanning_tree_t *t, int include_nodes)
FC_ReturnCode fc_computeTreeDistances (spanning_tree_t *t)
FC_ReturnCode fc_computeTreeDescendantsAncestors (spanning_tree_t *tree)
FC_ReturnCode fc_makeSpanningTree (FC_Mesh m, int starting_element_id, spanning_tree_t **tree)
FC_ReturnCode fc_saveSkeleton (spanning_tree_t tree, char *displacement_var_name, char *file_name)
FC_ReturnCode fc_convertTreeToMesh (FC_Dataset ds, spanning_tree_t tree, char *mesh_name, char *displacement_var_name, FC_Mesh *mesh_out)
FC_ReturnCode replicateSpanningTreeWithMask (spanning_tree_t *ti, char *mask, spanning_tree_t **to)
FC_ReturnCode replicateSpanningTree (spanning_tree_t *ti, spanning_tree_t **to)
FC_ReturnCode treeTagNodesAncestorsMask (spanning_tree_t *ti, int node_id, char *mask)
void whittleSkeletonByNumDescendents (spanning_tree_t *ti, int min, spanning_tree_t **to)
void whittleSkeletonOctants (spanning_tree_t *ti, int per_oct, spanning_tree_t **to)
void whittleSkeletonBySegmentLengths (spanning_tree_t *ti, spanning_tree_t **to)
void whittleSkeletonByDullestAngles (spanning_tree_t *ti, spanning_tree_t **to)
FC_ReturnCode whittleSkeleton (spanning_tree_t *ti, whittleAlgorithm_t wtype, double desired_remaining_fraction, spanning_tree_t **to)
void fc_unpackSkeletonFromMesh (FC_Mesh m, spanning_tree_t **tptr)
whittleAlgorithm_t convertStringToWhittleAlg (char *s)
char * convertWhittleAlgToString (whittleAlgorithm_t w)
char * getWhittleAlgorithmName (whittleAlgorithm_t alg_id)
int getNextWhittleAlgorithmDescription (int count, char **name, char **sname, whittleAlgorithm_t *id, char **description)
Variables
int _skeleton_dbg
Define Documentation
#define dbg (a, args...) { if(_skeleton_dbg>1) printf("DBG:" a "\n", ## args); }
Definition at line 45 of file lib_skeleton.h.
Referenced by fc_makeSpanningTree(), and fc_saveSkeleton().
#define emsg (a, args...) {fprintf(stderr,"Error in %s()[%s:%d] " a "\n", __func__, __FILE__, __LINE__, ## args); exit(-1); }
Definition at line 44 of file lib_skeleton.h.
Referenced by _getParentIndexForIndex(), fc_computeTreeDescendantsAncestors(), fc_convertTreeToMesh(), fc_getElementCenters(), fc_saveSkeleton(), findNetDistanceChangeWhenRemovingNode(), findSharpestAngleForNodeIndex(), getMeshByNameOrDie(), main(), and mallocOrDie().
#define FREE (a) { if(!a) emsg("Free on NULL pointer?"); free(a); a=NULL; }
Definition at line 47 of file lib_skeleton.h.
Referenced by doesSeqVarExist(), fc_getElementCenters(), fc_makeSpanningTree(), getMeshByNameOrDie(), main(), and whittleSkeleton().
#define info (a, args...) { if(_skeleton_dbg) printf(a "\n", ## args); }
Definition at line 46 of file lib_skeleton.h.
Referenced by checkArgs(), dumpHelp(), fc_makeSpanningTree(), fc_unpackSkeletonFromMesh(), main(), and whittleSkeleton().
Enumeration Type Documentation
enum whittleAlgorithm_t
Enumerator:
FC_WA_UNKNOWN
FC_WA_UNSPECIFIED
FC_WA_OCTANTS
FC_WA_MIN_DESCENDANTS
FC_WA_MIN_SEGMENT_LENGTHS
FC_WA_MIN_ANGLE_CHANGE
Definition at line 50 of file lib_skeleton.h.
             {
  FC_WA_UNKNOWN             = -1,
  FC_WA_UNSPECIFIED         = 0,
  FC_WA_OCTANTS             = 1,
  FC_WA_MIN_DESCENDANTS     = 2,
  FC_WA_MIN_SEGMENT_LENGTHS = 3,
  FC_WA_MIN_ANGLE_CHANGE    = 4
} whittleAlgorithm_t;
Function Documentation
int _fc_compareSpanningTreeNodes (const void * a, const void * b)
FC_ReturnCode _fc_getIntersectionPointBetweenElements (int elemID_1, int elemID_2, int dim, int vertPerElement, int * conn_list, double * verts, FC_Coords * results)
Definition at line 166 of file lib_skeleton.c.
References FC_ERROR, and FC_SUCCESS.
{
  int verts_in_common=0;
  FC_Coords sum = {0.0,0.0,0.0};
  int i,j;
  int vert_id1;
  assert(elemID_1>=0);
  assert(elemID_2>=0);
  for(i=0;i<vertPerElement;i++){
    //See if the elements share this vert in common
    vert_id1 = conn_list[elemID_1*vertPerElement+i];
    for(j=0; (j<vertPerElement) && (vert_id1 != conn_list[elemID_2*vertPerElement+j]); j++);
    if(j!=vertPerElement){
      //This vert is common to both, add it in to the sum
      for(j=0;j<dim;j++)
     sum[j] += verts[ vert_id1 * dim + j];
      verts_in_common++;
    }
  }
  if(!verts_in_common) return FC_ERROR; //no intersection point
  for(i=0;i<dim;i++)
    (*results)[i] = sum[i] / (double)verts_in_common;
  return FC_SUCCESS;
}
whittleAlgorithm_t convertStringToWhittleAlg (char * s)
Definition at line 71 of file lib_skeleton.c.
References whittleAlgorithmDescription_t::alg_id, FC_WA_UNKNOWN, whittleAlgorithmDescription_t::name, and whittleAlgorithmDescription_t::shortname.
Referenced by checkArgs(), and main().
{
  whittleAlgorithmDescription_t *w;
  if(!s) return FC_WA_UNKNOWN;
  for(w=whittleAlgorithmDescription; w->name; w++){
    if(!strcasecmp(s, w->shortname)) return w->alg_id;
  }
  return FC_WA_UNKNOWN;
}
char* convertWhittleAlgToString (whittleAlgorithm_t w)
Definition at line 1633 of file lib_skeleton.c.
References FC_WA_MIN_ANGLE_CHANGE, FC_WA_MIN_DESCENDANTS, FC_WA_MIN_SEGMENT_LENGTHS, FC_WA_OCTANTS, FC_WA_UNKNOWN, and FC_WA_UNSPECIFIED.
Referenced by main().
{
  switch(w){
  case FC_WA_OCTANTS:             return "FC_WA_OCTANTS";
  case FC_WA_MIN_DESCENDANTS:     return "FC_WA_MIN_DESCENDANTS";
  case FC_WA_MIN_SEGMENT_LENGTHS: return "FC_WA_MIN_SEGMENT_LENGTHS";
  case FC_WA_MIN_ANGLE_CHANGE:    return "FC_WA_MIN_ANGLE_CHANGE";
  case FC_WA_UNKNOWN:             return "FC_WA_UNKNOWN";
  case FC_WA_UNSPECIFIED:         return "FC_WA_UNSPECIFIED";
  default: return "ERROR:Unknown Alg?";
  }
}
int doesSeqVarExist (FC_Mesh m, char * seqvar_name)
Definition at line 624 of file lib_skeleton.c.
References fc_getSeqVariableByName(), fc_isMeshValid(), FC_SUCCESS, and FREE.
Referenced by fc_saveSkeleton().
{
  FC_ReturnCode rc;
  int num_seqVar;
  int *numStepPerVar;
  FC_Variable **seqVars;
  int i;
  if(!fc_isMeshValid(m)) return 0; //Invalid mesh
  if(!seqvar_name)       return 0; //Null name
  rc = fc_getSeqVariableByName(m, seqvar_name,
                      &num_seqVar, &numStepPerVar, &seqVars);
  if(rc!=FC_SUCCESS) return 0;
  if(num_seqVar){
    FREE(numStepPerVar);
    for(i=0; i<num_seqVar; i++)
      FREE(seqVars[i]);
    FREE(seqVars);
  }
  return num_seqVar;
}
FC_ReturnCode fc_computeTreeDescendantsAncestors (spanning_tree_t * tree)
Definition at line 267 of file lib_skeleton.c.
References _fc_lookupIntInSortedIntArray(), emsg, fc_addIntArrayToSortedIntArray(), fc_exitIfError, fc_freeSortedIntArray(), fc_initSortedIntArray(), FC_INPUT_ERROR, fc_printfErrorMessage, FC_SUCCESS, spanning_tree_node_t::id_start, spanning_tree_node_t::id_stop, spanning_tree_t::nodes, spanning_tree_node_t::num_ancestors, spanning_tree_node_t::num_descendants, spanning_tree_t::numNodes, spanning_tree_t::root, and FC_SortedIntArray::tickets.
Referenced by fc_makeSpanningTree(), fc_unpackSkeletonFromMesh(), replicateSpanningTreeWithMask(), and whittleSkeletonByNumDescendents().
{
  int i,j,k;
  int hops_up;
  FC_SortedIntArray lut;
  FC_ReturnCode rc;
  int *tmp;
  //printf("Starting anc/dec\n");
  //Build a lookup table to speedup search of vals
  tmp = (int *) malloc(tree->numNodes * sizeof(int));
  for(i=0;i<tree->numNodes;i++){
    tree->nodes[i].num_ancestors = tree->nodes[i].num_descendants = 0;
    tmp[i] = tree->nodes[i].id_stop;
  }
  rc = fc_initSortedIntArray(&lut);                                   fc_exitIfError(rc);
  rc = fc_addIntArrayToSortedIntArray(&lut, tree->numNodes, tmp, 0);
  if(rc!=tree->numNodes)
    emsg("Wrong number of sorted vals?");
#if 0
  //Verify
  for(i=0; i<tree->numNodes;i++){
    int found, spot;
    rc = _fc_lookupIntInSortedIntArray(&lut, tree->nodes[i].id_stop, &found, &spot);
    fc_exitIfError(rc);
    if(lut.tickets[spot] != i)
      emsg("Got bad ticket for  %d", i);
  }
  printf("Verified lut\n");
#endif
  //visit all nodes
  for(i=0; i<tree->numNodes;i++){
    //For each node, trace the path back to the root. Along the way,
    //increment the number of descendants each visited node has. After
    //all is done for this node, store the number of hops it took to
    //get to the root.
    hops_up=1; //always at least one, since root not in tree
    j=tree->nodes[i].id_start;
    while(j!=tree->root){
      #if 0
         for(k=0; (k<tree->numNodes) && (tree->nodes[k].id_stop!=j) ; k++); //Find location of this node
         if(k==tree->numNodes){
        fc_printfErrorMessage("Did not find requested node %d in tree with %d nodes\n", j, tree->numNodes);
        return FC_INPUT_ERROR;
         }
      #else
      int found, spot;
      rc = _fc_lookupIntInSortedIntArray(&lut, j, &found, &spot);
      if(!found)
        emsg("Didn't find parent?");
      k = lut.tickets[spot];
      #endif
      tree->nodes[k].num_descendants++;
      j=tree->nodes[k].id_start;
      hops_up++;
    }
    tree->nodes[i].num_ancestors = hops_up;
  }
  fc_freeSortedIntArray(&lut);
  return FC_SUCCESS;
}
FC_ReturnCode fc_computeTreeDistances (spanning_tree_t * t)
Definition at line 237 of file lib_skeleton.c.
References _getParentIndexForIndex(), spanning_tree_node_t::dist_center, spanning_tree_t::elementCenters, fc_calcSquaredEuclideanDistance(), fc_exitIfError, FC_SUCCESS, spanning_tree_node_t::id_start, spanning_tree_node_t::id_stop, spanning_tree_t::nodes, and spanning_tree_t::numNodes.
Referenced by fc_unpackSkeletonFromMesh(), and replicateSpanningTreeWithMask().
{
  int i;
  int parent_spot;
  double sum;
  FC_ReturnCode rc;
  for(i=0; i<t->numNodes; i++){
    parent_spot = _getParentIndexForIndex(t, i);
    //Find distance for this link
    rc = fc_calcSquaredEuclideanDistance(&t->elementCenters[ t->nodes[i].id_start * 3],
                          &t->elementCenters[ t->nodes[i].id_stop  * 3],
                          3, &sum);
    fc_exitIfError(rc);
    //Add it to the distance accumulated at the parent
    sum += (parent_spot<0) ? 0.0 : t->nodes[parent_spot].dist_center;
    t->nodes[i].dist_center = sum;
  }
  return FC_SUCCESS;
}
FC_ReturnCode fc_convertTreeToMesh (FC_Dataset ds, spanning_tree_t tree, char * mesh_name, char * displacement_var_name, FC_Mesh * mesh_out)
Definition at line 817 of file lib_skeleton.c.
References spanning_tree_t::dim, spanning_tree_t::elementCenters, emsg, FC_AT_VERTEX, fc_copySequence(), fc_createMesh(), fc_createSeqVariable(), fc_createVariable(), FC_DT_DOUBLE, FC_DT_INT, FC_ET_LINE, fc_exitIfError, fc_getElementCenters(), fc_getMeshElementConnsPtr(), fc_getOrGenerateUniqueSeqVariableByName(), fc_getSequenceByName(), fc_getSequenceFromSeqVariable(), fc_getVariableDataPtr(), FC_INPUT_ERROR, FC_MT_SCALAR, FC_MT_VECTOR, fc_printfErrorMessage, fc_setMeshCoords(), fc_setMeshElementConns(), fc_setVariableDataPtr(), FC_SUCCESS, spanning_tree_node_t::id_start, spanning_tree_node_t::id_stop, spanning_tree_t::mesh, spanning_tree_t::mesh_is_centers, spanning_tree_t::nodes, spanning_tree_node_t::num_ancestors, spanning_tree_node_t::num_descendants, spanning_tree_t::numElement, spanning_tree_t::numNodes, and spanning_tree_t::root.
Referenced by main().
                    {
  FC_Mesh m_src;
  FC_Mesh m_skel;
  FC_Variable v_ancestors, v_descendants;
  int *tmp_ancestors, *tmp_descendants;
  FC_ReturnCode rc;
  int *id_conns;
  int numElement;
  int i,j;
  int dim;
  double *coords;
  int numCoords, numLinks;
  if(tree.numNodes<1){
    fc_printfErrorMessage("Skeleton did not have any links in it\n");
    return FC_INPUT_ERROR;
  }
  //elem_centers = tree.element_centers;
  dim          = tree.dim;
  numElement   = tree.numElement;
  m_src        = tree.mesh;
  //Simple case: just doing centers
  numCoords = tree.numElement;
  numLinks  = tree.numNodes;
  //Coords: made up of all element centers, nothing else
  coords = (double *)malloc(numCoords*dim*sizeof(double));
  memcpy(coords, tree.elementCenters, numCoords*dim*sizeof(double));
  //Conns: every node gets one link
  id_conns = (int *) malloc(numLinks*2*sizeof(int));
  for(i=0; i<numLinks; i++){
    //printf("%d/%d start/stop = %d/%d  max=%d\n", i,num_links, links[i+1].id_start, links[i+1].id_stop, numElement);
    assert((tree.nodes[i].id_start>=0) && (tree.nodes[i].id_start<numCoords));
    assert((tree.nodes[i].id_stop >=0) && (tree.nodes[i].id_stop <numCoords));
    id_conns[i*2+0] = tree.nodes[i].id_start; //First entry is not a link, it's
    id_conns[i*2+1] = tree.nodes[i].id_stop;  //the origin
  }
  //Create the Mesh
  rc=fc_createMesh(ds, mesh_name, &m_skel);                                                               fc_exitIfError(rc);
  rc=fc_setMeshCoords(m_skel, dim, numCoords, coords);                                                           fc_exitIfError(rc);
  rc=fc_setMeshElementConns(m_skel, FC_ET_LINE, numLinks, id_conns);                                             fc_exitIfError(rc);
  //Create variables for giving the number of ancestors and descendants
  rc=fc_createVariable(m_skel, "num_ancestors",   &v_ancestors);                                                 fc_exitIfError(rc);
  rc=fc_createVariable(m_skel, "num_descendants", &v_descendants);                                               fc_exitIfError(rc);
  tmp_ancestors   = (int *)calloc(numCoords,sizeof(int));
  tmp_descendants = (int *)calloc(numCoords,sizeof(int));
  tmp_ancestors[   tree.root ] = 0;
  tmp_descendants[ tree.root ] = tree.numNodes;
  for(i=0;i<tree.numNodes; i++){
    tmp_ancestors[   tree.nodes[i].id_stop ] = tree.nodes[i].num_ancestors;
    tmp_descendants[ tree.nodes[i].id_stop ] = tree.nodes[i].num_descendants;
  }
  { //error Check
    printf("Root is %d\n", tree.root);
    for(i=0; i<tree.numNodes; i++){
      if(tree.nodes[i].num_ancestors<=0)
     emsg("spot %d (node %d) had %d ancestors\n", i, tree.nodes[i].id_stop,tree.nodes[i].num_ancestors );
      //printf("spot %d : id %d  anc/dec= %d/%d\n", i, tree.nodes[i].id_stop,tree.nodes[i].num_ancestors, tree.nodes[i].num_descendants );
    }
  }
  rc=fc_setVariableDataPtr(v_ancestors,   numCoords, 1, FC_AT_VERTEX, FC_MT_SCALAR, FC_DT_INT, tmp_ancestors);   fc_exitIfError(rc);
  rc=fc_setVariableDataPtr(v_descendants, numCoords, 1, FC_AT_VERTEX, FC_MT_SCALAR, FC_DT_INT, tmp_descendants); fc_exitIfError(rc);
  if(displacement_var_name){
    FC_Sequence src_seq, dst_seq;
    FC_Variable *src_dispSV, *dst_dispSV_skel;
    int src_dispSV_steps, dst_dispSV_steps;
    int *orig_conns; //read only
    //Create displacement vars for the ball and skeleton
    rc = fc_getOrGenerateUniqueSeqVariableByName(m_src, displacement_var_name, &src_dispSV_steps, &src_dispSV);  fc_exitIfError(rc);
    { //We should only create one sequence for all meshes
      int          tmp_numSeq;
      FC_Sequence *tmp_seqs;
      rc = fc_getSequenceByName(ds, "tree_sequence", &tmp_numSeq, &tmp_seqs);  fc_exitIfError(rc);
      if(!tmp_numSeq){
     //Nothing created yet- copy in from original
     rc = fc_getSequenceFromSeqVariable(src_dispSV_steps, src_dispSV, &src_seq);                                  fc_exitIfError(rc);
     rc = fc_copySequence(src_seq, ds, "tree_sequence", &dst_seq);                                                fc_exitIfError(rc);
      } else {
     //Something already here - use it
     dst_seq = tmp_seqs[0];
     free(tmp_seqs);
      }
    }
    rc = fc_createSeqVariable(m_skel, dst_seq, "displacement", &dst_dispSV_steps, &dst_dispSV_skel);             fc_exitIfError(rc);
    //Need connections for original mesh if generating new intersection points
    rc = fc_getMeshElementConnsPtr(tree.mesh, &orig_conns);                                                      fc_exitIfError(rc);
    for(i=0; i<dst_dispSV_steps; i++){
      double *dst_centers_disp;
      if(!tree.mesh_is_centers){
     //Need to calculate the centers and figure out the displacements
     rc = fc_getElementCenters(m_src, src_dispSV[i], &dst_centers_disp);                                        fc_exitIfError(rc);
     //Change to a displacement
     for(j=0;j<numCoords*dim;j++)
       dst_centers_disp[j] -= coords[j];
      } else {
     double *tmp_disp;
     double  tmp_center[dim];
     dst_centers_disp = (double *)malloc(numCoords*dim*sizeof(double));
     rc = fc_getVariableDataPtr(src_dispSV[i], (void *) &tmp_disp);                                             fc_exitIfError(rc);
     memcpy(dst_centers_disp, tmp_disp, numCoords*dim*sizeof(double));
     for(j=0;j<dim;j++)
       tmp_center[j] = coords[tree.root*dim+j] + dst_centers_disp[tree.root*dim + j];
      }
      rc = fc_setVariableDataPtr(dst_dispSV_skel[i], numCoords, dim, FC_AT_VERTEX, FC_MT_VECTOR, FC_DT_DOUBLE, dst_centers_disp);
      fc_exitIfError(rc); //note: above absorbs the dst_centers pointer
    }
  }
  //rc=fc_writeDataset(ds, file_name, FC_FT_EXODUS); fc_exitIfError(rc);
  if(mesh_out)
    *mesh_out = m_skel;
  return FC_SUCCESS;
}
FC_ReturnCode fc_getElementCenters (FC_Mesh m, FC_Variable displ, double ** centers)
Definition at line 107 of file lib_skeleton.c.
References emsg, fc_exitIfError, fc_getDisplacedMeshCoords(), fc_getElementTypeNumVertex(), fc_getMeshCoordsPtr(), fc_getMeshElementConnsPtr(), fc_getMeshInfo(), FC_HANDLE_EQUIV, FC_NULL_VARIABLE, FC_SUCCESS, and FREE.
Referenced by fc_convertTreeToMesh(), fc_makeSpanningTree(), and fc_saveSkeleton().
{
  FC_ReturnCode rc;
  FC_ElementType elemType;
  int i,j,k;
  double *mesh_coords;
  int *elem_conns;
  int numElement, vertPerElem;
  int dim;
  double sum;
  double *elem_centers;
  int spot;
  //Get basic mesh info
  rc = fc_getMeshInfo(m, NULL, &dim, NULL, &numElement, &elemType); fc_exitIfError(rc);
  vertPerElem = fc_getElementTypeNumVertex(elemType);
  //Get the (possibly displaced) vert coords
  if(FC_HANDLE_EQUIV(displ, FC_NULL_VARIABLE)){
    //Note: mesh_coords is read-only in this case
    rc = fc_getMeshCoordsPtr(m, &mesh_coords); fc_exitIfError(rc);
  } else {
    //Note: mesh_coords needs to be freed in this case
    rc = fc_getDisplacedMeshCoords(m, displ, &mesh_coords); fc_exitIfError(rc);
  }
  //Get the element connectivity list
  rc = fc_getMeshElementConnsPtr(m, &elem_conns); fc_exitIfError(rc);
  //Calculate the center of all elements
  elem_centers = (double *) malloc(numElement*dim*sizeof(double));
  if(!elem_centers) emsg("Bad malloc");
  for(i=0; i<numElement; i++){
    for(j=0; j<dim; j++){
      sum=0.0;
      for(k=0; k<vertPerElem; k++){
     spot = elem_conns[i*vertPerElem + k];
     sum += mesh_coords[spot*dim + j];
      }
      elem_centers[i*dim + j] = sum / (double)vertPerElem;
    }
  }
  if(!FC_HANDLE_EQUIV(displ, FC_NULL_VARIABLE)){
    //When doing displacement we need to free the copy
    FREE(mesh_coords);
  }
  *centers = elem_centers;
  return FC_SUCCESS;
}
FC_ReturnCode fc_makeSpanningTree (FC_Mesh m, int starting_element_id, spanning_tree_t ** tree)
Definition at line 342 of file lib_skeleton.c.
References dbg, spanning_tree_t::dim, spanning_tree_node_t::dist_center, spanning_tree_t::elementCenters, FC_AT_ELEMENT, fc_calcSquaredEuclideanDistance(), fc_computeTreeDescendantsAncestors(), fc_eqd(), fc_exitIfError, fc_getElementCenters(), fc_getElementTypeNumVertex(), fc_getMeshCentroid(), fc_getMeshCoordsPtr(), fc_getMeshElementConnsPtr(), fc_getMeshEntityNeighbors(), fc_getMeshInfo(), fc_ltd(), FC_NULL_VARIABLE, fc_printfWarningMessage, FC_SUCCESS, FREE, spanning_tree_node_t::id_start, spanning_tree_node_t::id_stop, info, spanning_tree_t::mesh, spanning_tree_t::mesh_is_centers, spanning_tree_t::nodes, spanning_tree_node_t::num_ancestors, spanning_tree_node_t::num_descendants, spanning_tree_t::numElement, spanning_tree_t::numNodes, spanning_tree_t::root, and spanning_tree_t::vertPerElement.
Referenced by main().
{
  FC_ReturnCode rc;
  FC_ElementType elemType;
  int numElement, vertPerElement;
  double *elem_centers;
  int dim;
  FC_Coords centroid_coord;
  int i,j;
  double dist,best_dist;
  int spot, prv_spot, best_spot;
  double *mesh_coords;
  spanning_tree_node_t  *assembly, *neighbor;
  int assembly_num, neighbor_num;
  int *elem_conns;
  int *new_neighbors;
  int new_neighbors_num;
  const int NEIGHBOR_SEARCH_DIM = 1; //1=can share edges, 2=can only share faces
  char *visited_mask;
  //Get basic info about the mesh and elements
  rc = fc_getMeshInfo(m, NULL, &dim, NULL, &numElement, &elemType); fc_exitIfError(rc);
  vertPerElement = fc_getElementTypeNumVertex(elemType);
  rc = fc_getMeshCoordsPtr(m, &mesh_coords); fc_exitIfError(rc);
  //Get the element connectivity list
  rc = fc_getMeshElementConnsPtr(m, &elem_conns); fc_exitIfError(rc);
  //First find the centers for all the elements
  rc = fc_getElementCenters(m, FC_NULL_VARIABLE, &elem_centers); fc_exitIfError(rc);
  //Next, get a starting point for the skeleton
  if(starting_element_id<0){
    //Unknown starting point. Find the centroid..
    rc = fc_getMeshCentroid(m, &dim, &centroid_coord); fc_exitIfError(rc);
    //Then locate element that's closest.. BAD-Can be Wrong. TBD: find element that actually contains
    best_dist = DBL_MAX;
    best_spot = 0;
    for(i=0; i<numElement; i++){
      rc = fc_calcSquaredEuclideanDistance(centroid_coord, &elem_centers[i*dim], dim, &dist);
      fc_exitIfError(rc);
      if(dist<best_dist){
     best_dist = dist;
     best_spot = i;
      }
    }
    starting_element_id = best_spot;
    dbg("Starting point for tree generated by nearest element\n"
     "  Mesh centroid is (%.3f,%.3f,%.3f). Nearest element is %d, with center (%.3f,%.3f,%.3f)",
        centroid_coord[0], centroid_coord[1], centroid_coord[2],
        best_spot,
        elem_centers[best_spot*dim + 0],
        elem_centers[best_spot*dim + 1],
        elem_centers[best_spot*dim + 2]);
  } else {
    assert(starting_element_id<numElement);
    dbg("Starting point for tree specified by user as element %d, which has center (%.3f, %.3f, %.3f)",
     starting_element_id,
     elem_centers[best_spot*dim + 0],
     elem_centers[best_spot*dim + 1],
     elem_centers[best_spot*dim + 2]);
  }
  //Create space for everything
  assembly = (spanning_tree_node_t *)malloc((numElement-1)*sizeof(spanning_tree_node_t));
  neighbor = (spanning_tree_node_t *)malloc(numElement*sizeof(spanning_tree_node_t));
  visited_mask = (char *)calloc(numElement,sizeof(char));
  //Start with no neighbors and the starting element in the assembly
  assembly_num  = 0;
  neighbor_num  = 0;
  prv_spot = starting_element_id;
  //Main loop for building tree
  do{
    //printf("Assembly num: %d  Neighbor num: %d  prv_spot=%d spot=%d\n",
    //        assembly_num, neighbor_num, prv_spot, spot);
    //Find the new guy's neighbors
    //prv_spot = assembly[assembly_num-1].id_stop;
    rc = fc_getMeshEntityNeighbors(m, prv_spot, FC_AT_ELEMENT, NEIGHBOR_SEARCH_DIM, &new_neighbors_num, &new_neighbors);
    fc_exitIfError(rc);
    //Insert all of the new neighbors into list, and update shorter paths
    for(i=0; i<new_neighbors_num; i++){
      double dist_center;
      spot = new_neighbors[i];
      assert((spot>=0)&&(spot<numElement));
      //See if we already part of the assembly (means it must already have a smaller distance)
      if(spot==starting_element_id) continue; //Looped back to root
      #if 0 //previously a linear search
        for(j=0;(j<assembly_num) && (assembly[j].id_stop != spot); j++); //Scan all non-roots
        if(j!=assembly_num) continue; //Already a member, skip
      #else
     if(visited_mask[spot]) continue;
      #endif
      //Find the distance between the centers
      rc = fc_calcSquaredEuclideanDistance(&elem_centers[prv_spot*dim],
                            &elem_centers[    spot*dim], dim, &dist_center);
      fc_exitIfError(rc);
      dist_center = sqrt(dist_center); //needs to be Euclidean distance in order to be valid
      if(assembly_num)
     dist_center += assembly[assembly_num-1].dist_center; //Add in previous distance
      //See if we have this on the neighbor list
      for(j=0; (j<neighbor_num) && (neighbor[j].id_stop != spot); j++);
#if 1
      if(j!=neighbor_num){
     double tmp_dist;
     tmp_dist = dist_center;
     if(fc_eqd(neighbor[j].dist_center, tmp_dist)){
       //Equals case requires special handling. Chose based on id
       if(neighbor[j].id_stop < spot) continue; //already have a lower id
       //otherwise replace it
     } else {
       //Not Equals case just needs a threshold
       if(fc_ltd(neighbor[j].dist_center,tmp_dist)) continue;
     }
      }
#else
      //Bail out if we already know a closer distance to this node
      if((j!=neighbor_num) &&
      (fc_ltd(neighbor[j].dist_center,dist_center))) continue;
#endif
      neighbor[j].id_stop           = spot;
      neighbor[j].id_start          = prv_spot;
      neighbor[j].dist_center       = dist_center;
      neighbor[j].num_descendants   = 0;
      neighbor[j].num_ancestors     = 0;
      if(j==neighbor_num) neighbor_num++; //Only on appends
    }
    if(new_neighbors) FREE(new_neighbors);
    //Possible that starting node had no neighbors. In that case, terminate now
    if(!neighbor_num) break;
    //Find the shortest distance in the list
    dist = DBL_MAX;
    best_spot = 0;
    for(i=0; i<neighbor_num; i++) {
#if 1
      if(fc_eqd(neighbor[i].dist_center,dist)){
     if(neighbor[i].id_stop < best_spot){
       dist = neighbor[i].dist_center;
       best_spot = i;
     }
      }else if(fc_ltd(neighbor[i].dist_center,dist)){
     dist = neighbor[i].dist_center;
     best_spot = i;
      }
#else
      if(fc_ltd(neighbor[i].dist_center,dist)){
     dist = neighbor[i].dist_center;
     best_spot = i;
      }
#endif
    }
    //Promote to the assembly
    assert(assembly_num<numElement-1);
    assembly[assembly_num] = neighbor[best_spot];
    visited_mask[assembly[assembly_num].id_stop]=1;
    assembly_num++;
    prv_spot = neighbor[best_spot].id_stop;
    //Remove from neighbor list
    for(i=best_spot; i<neighbor_num; i++)
      neighbor[i] = neighbor[i+1];
    neighbor_num--;
    //if((neighbor_num%100)==0) printf("Spanning Neighbor num: %d\n", neighbor_num);
  } while(neighbor_num>0);
  dbg("Finished generating neighbors");
  FREE(visited_mask);
  //Sort nodes that have the same distance. We do this to make sure we produce
  //identical trees with no ambiguity
  //for(i=0; i<assembly_num; i+=j){
  //  for(j=1; ((i+j)<assembly_num) && (assembly[i+j].dist_center == assembly[i].dist_center); j++);
  //  if(j!=1){
  //  }
  //}
  if(assembly_num<=1){
    fc_printfWarningMessage("Selected element does not have any neighbors\n");
  }
  if(tree){
    spanning_tree_t *t;
    t = (spanning_tree_t *)malloc(sizeof(spanning_tree_t));
    t->root                    = starting_element_id;
    t->numNodes                = assembly_num;
    t->nodes                   = realloc(assembly, assembly_num*sizeof(spanning_tree_node_t));
    t->mesh                    = m;
    t->dim                     = dim;
    t->numElement              = numElement;
    t->vertPerElement          = vertPerElement;
    t->elementCenters          = elem_centers;
    t->mesh_is_centers         = 0;
    rc = fc_computeTreeDescendantsAncestors(t);
    *tree = t;
  } else {
    FREE(elem_centers);
    FREE(assembly);
    rc = FC_SUCCESS;
  }
  info("Done generating tree");
  return rc;
}
FC_ReturnCode fc_saveSkeleton (spanning_tree_t tree, char * displacement_var_name, char * file_name)
Definition at line 651 of file lib_skeleton.c.
References dbg, spanning_tree_t::dim, doesSeqVarExist(), spanning_tree_t::elementCenters, emsg, FC_AT_VERTEX, fc_copySequence(), fc_createDataset(), fc_createMesh(), fc_createSeqVariable(), fc_createSphereMesh(), fc_createVariable(), FC_DT_DOUBLE, FC_DT_INT, FC_ET_LINE, fc_exitIfError, FC_FT_EXODUS, fc_getElementCenters(), fc_getMeshElementConnsPtr(), fc_getOrGenerateUniqueSeqVariableByName(), fc_getSequenceFromSeqVariable(), fc_getVariableDataPtr(), FC_INPUT_ERROR, FC_MT_SCALAR, FC_MT_VECTOR, fc_printfErrorMessage, fc_printfWarningMessage, fc_setMeshCoords(), fc_setMeshElementConns(), fc_setSphereDisplacementVariable(), fc_setVariableDataPtr(), FC_SUCCESS, fc_writeDataset(), spanning_tree_node_t::id_start, spanning_tree_node_t::id_stop, spanning_tree_t::mesh, spanning_tree_t::mesh_is_centers, spanning_tree_t::nodes, spanning_tree_node_t::num_ancestors, spanning_tree_node_t::num_descendants, spanning_tree_t::numElement, spanning_tree_t::numNodes, and spanning_tree_t::root.
Referenced by main().
{
  FC_Mesh m_src;
  FC_Dataset ds_skel;
  FC_Mesh m_skel, m_ball;
  FC_Variable v_ancestors, v_descendants;
  int *tmp_ancestors, *tmp_descendants;
  FC_ReturnCode rc;
  int *id_conns;
  int numElement;
  int i,j;
  int dim;
  double *coords;
  int numCoords, numLinks;
  const double ball_radius = 2.0;
  const int    ball_points = 256;
  //if(tree.num_nodes<1){
    //tbd: more checking
  //  return FC_INPUT_ERROR;
  //}
  if(tree.numNodes<1){
    fc_printfErrorMessage("Skeleton did not have any links in it\n");
    return FC_INPUT_ERROR;
  }
  //elem_centers = tree.element_centers;
  dim          = tree.dim;
  numElement   = tree.numElement;
  m_src        = tree.mesh;
  //Simple case: just doing centers
  numCoords = tree.numElement;
  numLinks  = tree.numNodes;
  //Coords: made up of all element centers, nothing else
  coords = (double *)malloc(numCoords*dim*sizeof(double));
  memcpy(coords, tree.elementCenters, numCoords*dim*sizeof(double));
  //Conns: every node gets one link
  id_conns = (int *) malloc(numLinks*2*sizeof(int));
  for(i=0; i<numLinks; i++){
    //printf("%d/%d start/stop = %d/%d  max=%d\n", i,num_links, links[i+1].id_start, links[i+1].id_stop, numElement);
    assert((tree.nodes[i].id_start>=0) && (tree.nodes[i].id_start<numCoords));
    assert((tree.nodes[i].id_stop >=0) && (tree.nodes[i].id_stop <numCoords));
    id_conns[i*2+0] = tree.nodes[i].id_start; //First entry is not a link, it's
    id_conns[i*2+1] = tree.nodes[i].id_stop;  //the origin
  }
  //Create dataset and load it with (1) ball for origin and (2) mesh for skeleton
  rc=fc_createDataset("skel", &ds_skel);                                                                         fc_exitIfError(rc);
  rc=fc_createSphereMesh(ds_skel, "Tree Origin", &coords[tree.root*dim], ball_radius, ball_points, &m_ball);       fc_exitIfError(rc);
  rc=fc_createMesh(ds_skel, "skel_mesh", &m_skel);                                                               fc_exitIfError(rc);
  rc=fc_setMeshCoords(m_skel, dim, numCoords, coords);                                                           fc_exitIfError(rc);
  rc=fc_setMeshElementConns(m_skel, FC_ET_LINE, numLinks, id_conns);                                             fc_exitIfError(rc);
  //Create variables for giving the number of ancestors and descendants
  rc=fc_createVariable(m_skel, "num_ancestors",   &v_ancestors);                                                 fc_exitIfError(rc);
  rc=fc_createVariable(m_skel, "num_descendants", &v_descendants);                                               fc_exitIfError(rc);
  tmp_ancestors   = (int *)calloc(numCoords,sizeof(int));
  tmp_descendants = (int *)calloc(numCoords,sizeof(int));
  tmp_ancestors[   tree.root ] = 0;
  tmp_descendants[ tree.root ] = tree.numNodes;
  for(i=0;i<tree.numNodes; i++){
    tmp_ancestors[   tree.nodes[i].id_stop ] = tree.nodes[i].num_ancestors;
    tmp_descendants[ tree.nodes[i].id_stop ] = tree.nodes[i].num_descendants;
  }
  { //error Check
    dbg("Root is %d\n", tree.root);
    for(i=0; i<tree.numNodes; i++){
      if(tree.nodes[i].num_ancestors<=0)
     emsg("spot %d (node %d) had %d ancestors\n", i, tree.nodes[i].id_stop,tree.nodes[i].num_ancestors );
      dbg("spot %d : id %d  anc/dec= %d/%d\n", i, tree.nodes[i].id_stop,tree.nodes[i].num_ancestors, tree.nodes[i].num_descendants );
    }
  }
  rc=fc_setVariableDataPtr(v_ancestors,   numCoords, 1, FC_AT_VERTEX, FC_MT_SCALAR, FC_DT_INT, tmp_ancestors);   fc_exitIfError(rc);
  rc=fc_setVariableDataPtr(v_descendants, numCoords, 1, FC_AT_VERTEX, FC_MT_SCALAR, FC_DT_INT, tmp_descendants); fc_exitIfError(rc);
  //Check to see if displacement is available
  if((displacement_var_name)&&(!doesSeqVarExist(m_src, displacement_var_name))){
    fc_printfWarningMessage("Displacement var '%s' does not exist. Skipping displacement.", displacement_var_name);
    displacement_var_name = NULL;
  }
  if(displacement_var_name){
    FC_Sequence src_seq, dst_seq;
    FC_Variable *src_dispSV, *dst_dispSV_skel, *dst_dispSV_ball;
    int src_dispSV_steps, dst_dispSV_steps;
    int *orig_conns; //read only
    //Create displacement vars for the ball and skeleton
    rc = fc_getOrGenerateUniqueSeqVariableByName(m_src, displacement_var_name, &src_dispSV_steps, &src_dispSV);  fc_exitIfError(rc);
    rc = fc_getSequenceFromSeqVariable(src_dispSV_steps, src_dispSV, &src_seq);                                  fc_exitIfError(rc);
    rc = fc_copySequence(src_seq, ds_skel, "new_sequence", &dst_seq);                                            fc_exitIfError(rc);
    rc = fc_createSeqVariable(m_skel, dst_seq, "displacement", &dst_dispSV_steps, &dst_dispSV_skel);             fc_exitIfError(rc);
    rc = fc_createSeqVariable(m_ball, dst_seq, "displacement", &dst_dispSV_steps, &dst_dispSV_ball);             fc_exitIfError(rc);
    //Need connections for original mesh if generating new intersection points
    rc = fc_getMeshElementConnsPtr(tree.mesh, &orig_conns);                                                      fc_exitIfError(rc);
    for(i=0; i<dst_dispSV_steps; i++){
      double *dst_centers_disp;
      if(!tree.mesh_is_centers){
     //Need to calculate the centers and figure out the displacements
     rc = fc_getElementCenters(m_src, src_dispSV[i], &dst_centers_disp);                                        fc_exitIfError(rc);
     rc = fc_setSphereDisplacementVariable(dst_dispSV_ball[i], &dst_centers_disp[tree.root*dim], ball_radius);  fc_exitIfError(rc);
     //Change to a displacement
     for(j=0;j<numCoords*dim;j++)
       dst_centers_disp[j] -= coords[j];
      } else {
     double *tmp_disp;
     double  tmp_center[dim];
     dst_centers_disp = (double *)malloc(numCoords*dim*sizeof(double));
     rc = fc_getVariableDataPtr(src_dispSV[i], (void *) &tmp_disp);                                             fc_exitIfError(rc);
     memcpy(dst_centers_disp, tmp_disp, numCoords*dim*sizeof(double));
     for(j=0;j<dim;j++)
       tmp_center[j] = coords[tree.root*dim+j] + dst_centers_disp[tree.root*dim + j];
     rc = fc_setSphereDisplacementVariable(dst_dispSV_ball[i], &tmp_center[0], ball_radius);  fc_exitIfError(rc);
      }
      rc = fc_setVariableDataPtr(dst_dispSV_skel[i], numCoords, dim, FC_AT_VERTEX, FC_MT_VECTOR, FC_DT_DOUBLE, dst_centers_disp);
      fc_exitIfError(rc); //note: above absorbs the dst_centers pointer
    }
  }
  rc=fc_writeDataset(ds_skel, file_name, FC_FT_EXODUS); fc_exitIfError(rc);
  return FC_SUCCESS;
}
void fc_unpackSkeletonFromMesh (FC_Mesh m, spanning_tree_t ** tptr)
Definition at line 1519 of file lib_skeleton.c.
References spanning_tree_t::dim, spanning_tree_node_t::dist_center, spanning_tree_t::elementCenters, fc_computeTreeDescendantsAncestors(), fc_computeTreeDistances(), fc_exitIfError, fc_getMeshCoordsPtr(), fc_getMeshElementConnsPtr(), fc_getMeshInfo(), spanning_tree_node_t::id_start, spanning_tree_node_t::id_stop, info, spanning_tree_t::mesh, spanning_tree_t::mesh_is_centers, spanning_tree_t::nodes, spanning_tree_node_t::num_ancestors, spanning_tree_node_t::num_descendants, spanning_tree_t::numElement, spanning_tree_t::numNodes, spanning_tree_t::root, and spanning_tree_t::vertPerElement.
Referenced by main().
{
  spanning_tree_t *t;
  FC_ReturnCode rc;
  int topodim, dim, numVertex, numElement;
  FC_ElementType elemType;
  int *conns;
  int  i;
  t=(spanning_tree_t *)malloc(sizeof(spanning_tree_t));
  rc = fc_getMeshInfo(m, &topodim, &dim, &numVertex, &numElement, &elemType);  fc_exitIfError(rc);
  rc = fc_getMeshCoordsPtr(m, &t->elementCenters); fc_exitIfError(rc); //Read only
  rc = fc_getMeshElementConnsPtr(m, &conns);       fc_exitIfError(rc); //Read-only
  info("Unpack Skeleton from Mesh: numVertex=%d numElement=%d root=%d", numVertex, numElement, conns[0]);
  t->root            = conns[0]; //Root is first node in list
  t->numNodes        = numElement;
  t->nodes           = (spanning_tree_node_t *)calloc(numElement, sizeof(spanning_tree_node_t));
  t->dim             = dim;
  t->numElement      = numVertex; //Each vertex was at center of an element
  t->vertPerElement  = 1;
  t->mesh            = m;
  t->mesh_is_centers = 1;
  for(i=0; i<t->numNodes; i++){
    t->nodes[i].id_start = conns[i*2+0];
    t->nodes[i].id_stop  = conns[i*2+1];
    t->nodes[i].dist_center = 0.0;
    t->nodes[i].num_descendants = 0;
    t->nodes[i].num_ancestors   = 0;
    //printf("[%d] %d->%d\n", i, conns[i*2+0], conns[i*2+1]);
    assert(conns[i*2+0]<numVertex);
    assert(conns[i*2+1]<numVertex);
  }
  rc = fc_computeTreeDistances(t);            fc_exitIfError(rc);
  rc = fc_computeTreeDescendantsAncestors(t); fc_exitIfError(rc);
  *tptr = t;
}
int getNextWhittleAlgorithmDescription (int count, char ** name, char ** sname, whittleAlgorithm_t * id, char ** description)
Definition at line 90 of file lib_skeleton.c.
References whittleAlgorithmDescription_t::alg_id, whittleAlgorithmDescription_t::description, whittleAlgorithmDescription_t::name, and whittleAlgorithmDescription_t::shortname.
Referenced by dumpHelp().
{
  int i;
  *name=*sname=*description=NULL;
  *id=0;
  for(i=0; (i<count) && (whittleAlgorithmDescription[i].name); i++);
  if(!whittleAlgorithmDescription[i].name) return 0;
  //Found something
  *id          = whittleAlgorithmDescription[i].alg_id;
  *name        = whittleAlgorithmDescription[i].name;
  *sname       = whittleAlgorithmDescription[i].shortname;
  *description = whittleAlgorithmDescription[i].description;
  return 1;
}
char* getWhittleAlgorithmName (whittleAlgorithm_t alg_id)
Definition at line 81 of file lib_skeleton.c.
References whittleAlgorithmDescription_t::alg_id, and whittleAlgorithmDescription_t::name.
Referenced by main(), and whittleSkeleton().
{
  whittleAlgorithmDescription_t *w;
  for(w=whittleAlgorithmDescription; (w->name)&&(w->alg_id!=alg_id); w++);
  if(w->name) return w->name;
  return "Unknown";
}
void printTree (spanning_tree_t * t, int include_nodes)
Definition at line 605 of file lib_skeleton.c.
References spanning_tree_node_t::dist_center, spanning_tree_node_t::id_start, spanning_tree_node_t::id_stop, spanning_tree_t::nodes, spanning_tree_node_t::num_ancestors, spanning_tree_node_t::num_descendants, spanning_tree_t::numElement, spanning_tree_t::numNodes, spanning_tree_t::root, and spanning_tree_t::vertPerElement.
{
  int i;
  printf("tree root=%d numNodes=%d MeshElements=%d VertsPerElement=%d\n",
      t->root, t->numNodes, t->numElement, t->vertPerElement);
  if(include_nodes){
    for(i=0;i<t->numNodes;i++)
      printf("[%.4d] %4d->%4d \tDistance: %.8lf [c/i] Relatives:\t%d/%d [ancestors/descendants]\n",
          i,
          t->nodes[i].id_start,
          t->nodes[i].id_stop,
          t->nodes[i].dist_center,
          t->nodes[i].num_ancestors,
          t->nodes[i].num_descendants);
  }
}
FC_ReturnCode replicateSpanningTree (spanning_tree_t * ti, spanning_tree_t ** to)
Definition at line 1066 of file lib_skeleton.c.
References replicateSpanningTreeWithMask().
Referenced by whittleSkeleton().
{
  return replicateSpanningTreeWithMask(ti,NULL,to);
}
FC_ReturnCode replicateSpanningTreeWithMask (spanning_tree_t * ti, char * mask, spanning_tree_t ** to)
Definition at line 988 of file lib_skeleton.c.
References _getParentIndexForIndex(), spanning_tree_t::dim, spanning_tree_t::elementCenters, fc_computeTreeDescendantsAncestors(), fc_computeTreeDistances(), FC_SUCCESS, spanning_tree_node_t::id_start, spanning_tree_node_t::id_stop, spanning_tree_t::nodes, spanning_tree_t::numElement, spanning_tree_t::numNodes, and spanning_tree_t::root.
Referenced by replicateSpanningTree(), whittleSkeletonByDullestAngles(), whittleSkeletonBySegmentLengths(), and whittleSkeletonOctants().
{
  int mask_count;
  int elemCenter_num;
  int i,j;
  int parent_spot;
  spanning_tree_t *t2;
  FC_ReturnCode rc;
  if(mask){
    for(mask_count=0, i=0; i< ti->numNodes; i++)
      if(mask[i]) mask_count++;
  } else {
    mask_count = ti->numNodes;
  }
  //Allocate space for new element centers. Vector is either [numElement] or [numElement+nodes]
  elemCenter_num = ti->numElement;
  //Create a new tree and populate it
  t2 = (spanning_tree_t *)malloc(sizeof(spanning_tree_t));
  memcpy(t2, ti, sizeof(spanning_tree_t)); //Copy original values
  t2->numNodes = mask_count;
  t2->nodes    = (spanning_tree_node_t *) calloc(mask_count, sizeof(spanning_tree_node_t));
  t2->elementCenters = (double *)calloc( elemCenter_num, ti->dim*sizeof(double));
  if(!mask){
    //Just replicate the arrays
    memcpy(t2->nodes, ti->nodes, ti->numNodes * sizeof(spanning_tree_node_t));
    memcpy(t2->elementCenters,   ti->elementCenters, elemCenter_num * ti->dim * sizeof(double));
    rc = FC_SUCCESS;
  } else {
    //Copy in the first chunk of elementcenters, we may need to fill in the back half
    memcpy(t2->elementCenters, ti->elementCenters, ti->numElement * ti->dim * sizeof(double));
    for(i=0,j=0; i<ti->numNodes; i++){
      if(!mask[i]) continue; //Skip if not used
      //Copy the node data
      memcpy(&t2->nodes[j], &ti->nodes[i], sizeof(spanning_tree_node_t));
      //Assign a new parent if mask says it's no longer good
      //Loop through all ancestors until we find something that's in mask or is root
      parent_spot = _getParentIndexForIndex(ti,i);
      while( (parent_spot>=0) && (!mask[parent_spot])){
     parent_spot = _getParentIndexForIndex(ti, parent_spot);
      }
      //Update this node's parent
      t2->nodes[j].id_start = (parent_spot<0) ? ti->root
                                           : ti->nodes[parent_spot].id_stop;
      j++;
    }
    //Need to recompute distances for new tree
    rc = fc_computeTreeDistances(t2);
    //Need to recompute ancestors/descendants
    rc = fc_computeTreeDescendantsAncestors(t2);
  }
  *to = t2;
  return rc;
}
FC_ReturnCode treeTagNodesAncestorsMask (spanning_tree_t * ti, int node_id, char * mask)
Definition at line 1073 of file lib_skeleton.c.
References FC_INPUT_ERROR, fc_printfErrorMessage, FC_SUCCESS, spanning_tree_node_t::id_start, spanning_tree_node_t::id_stop, spanning_tree_t::nodes, spanning_tree_t::numNodes, and spanning_tree_t::root.
Referenced by whittleSkeletonOctants().
{
  int i;
  int search_node;
  if(!mask){
    fc_printfErrorMessage("Tag ancestors wasn't given a mask\n");
    return FC_INPUT_ERROR;
  }
  //Find where this node's index is in the array
  for(i=0; (i<ti->numNodes) && (ti->nodes[i].id_stop!=node_id); i++);
  if(i==ti->numNodes){
    fc_printfErrorMessage("Node not found in tree\n");
    return FC_INPUT_ERROR;
  }
  search_node = node_id; //Fake the first one
  do{
    while(ti->nodes[i].id_stop != search_node) i--;
    mask[i]=1;
    search_node = ti->nodes[i].id_start;
  } while(search_node!=ti->root);
  return FC_SUCCESS;
}
FC_ReturnCode whittleSkeleton (spanning_tree_t * ti, whittleAlgorithm_t wtype, double desired_remaining_fraction, spanning_tree_t ** to)
Definition at line 1567 of file lib_skeleton.c.
References fc_exitIfError, FC_INPUT_ERROR, fc_printfErrorMessage, FC_SUCCESS, FC_WA_MIN_ANGLE_CHANGE, FC_WA_MIN_DESCENDANTS, FC_WA_MIN_SEGMENT_LENGTHS, FC_WA_OCTANTS, FREE, getWhittleAlgorithmName(), info, spanning_tree_t::nodes, spanning_tree_t::numNodes, replicateSpanningTree(), whittleSkeletonByDullestAngles(), whittleSkeletonByNumDescendents(), whittleSkeletonBySegmentLengths(), and whittleSkeletonOctants().
Referenced by main().
{
  int target_num;
  int original_num;
  spanning_tree_t *t1,*t2;
  FC_ReturnCode rc;
  original_num = ti->numNodes;
  target_num = (int) (desired_remaining_fraction * (double) original_num);
  info("whittleSkeleton: Using %s to reduce %d nodes to approximately %d",
       getWhittleAlgorithmName(wtype), original_num, target_num);
  if( (!((desired_remaining_fraction>0.0) && (desired_remaining_fraction<1.0))) ||
      (target_num<2) || (target_num==original_num)){
    printf("Whittle fraction: %.3lf. TBD code to handle this specifically\n", desired_remaining_fraction);
    return FC_INPUT_ERROR;
  }
  rc = replicateSpanningTree(ti, &t1); fc_exitIfError(rc);
  t2 = NULL;
  while(target_num < t1->numNodes){
    switch(wtype){
    case FC_WA_OCTANTS:
      whittleSkeletonOctants(t1, 2, &t2);  //Arg: per_octant
      break;
    case FC_WA_MIN_DESCENDANTS:
      whittleSkeletonByNumDescendents(t1, 1, &t2);  //Arg: per_octant
      break;
    case FC_WA_MIN_SEGMENT_LENGTHS:
      whittleSkeletonBySegmentLengths(t1, &t2);
      break;
    case FC_WA_MIN_ANGLE_CHANGE:
      whittleSkeletonByDullestAngles(t1, &t2);
      break;
    default:
      fc_printfErrorMessage("Unknown whittle type\n");
      return FC_INPUT_ERROR;
    }
    printf("Whittle num nodes: %d goal: %d\n", t2->numNodes, target_num);
    //Get rid of previous tree
    FREE(t1->nodes);
    FREE(t1);
    t1 = t2;
  }
  *to = t2;
  return FC_SUCCESS;
}
void whittleSkeletonByDullestAngles (spanning_tree_t * ti, spanning_tree_t ** to)
Definition at line 1338 of file lib_skeleton.c.
References findSharpestAngleForNodeIndex(), spanning_tree_t::numNodes, and replicateSpanningTreeWithMask().
Referenced by whittleSkeleton().
{
  int i;
  int dullest_idx;
  double dullest_angle;
  double tmp;
  char *mask;
#if (!ENABLE_OPENMP)
  dullest_idx = -1;
  dullest_angle = 0.0;
  for(i=0; i<ti->numNodes; i++){
    //Look at the angle's for a node to see how critical it is
    tmp = findSharpestAngleForNodeIndex(ti, i);
    if(tmp>dullest_angle){
      dullest_angle = tmp;
      dullest_idx   = i;
    }
  }
#else
  {
    double *tmp_dullest_angles;
    int    *tmp_dullest_idxs;
    int id,nthreads;
    const int chunk = 32;
    #pragma omp parallel private(i,id, tmp)
    {
      id = omp_get_thread_num();
      //Root: allocate space and initialize it
      if ( id == 0 ) {
     nthreads = omp_get_num_threads();
     tmp_dullest_angles = (double *)malloc(nthreads * sizeof(double));
     tmp_dullest_idxs   =    (int *)malloc(nthreads * sizeof(int));
     for(i=0; i<nthreads; i++)
       tmp_dullest_angles[i] = 0.0;
      }
      #pragma omp barrier
      #pragma omp for schedule(dynamic, chunk)
      for(i=0; i<ti->numNodes; i++){
     //Look at the angle's for a node to see how critical it is
     tmp = findSharpestAngleForNodeIndex(ti, i);
     if(tmp>tmp_dullest_angles[id]){
       tmp_dullest_angles[id] = tmp;
       tmp_dullest_idxs[id]   = i;
     }
      }
      #pragma omp barrier
      //Combine all the results
      if(id==0){
     for(i=0, dullest_angle = 0.0; i<nthreads; i++)
       if(tmp_dullest_angles[i]>dullest_angle){
         dullest_angle  = tmp_dullest_angles[i];
         dullest_idx    = tmp_dullest_idxs[i];
       }
     free(tmp_dullest_angles);
     free(tmp_dullest_idxs);
      }
    }
  }
#endif
  //Create a mask with all values tagged except delete point
  mask = (char *)malloc(ti->numNodes*sizeof(char));
  memset(mask, 1, ti->numNodes*sizeof(char));
  mask[dullest_idx] = 0;
  replicateSpanningTreeWithMask(ti, mask, to);
  free(mask);
}
void whittleSkeletonByNumDescendents (spanning_tree_t * ti, int min, spanning_tree_t ** to)
Definition at line 1103 of file lib_skeleton.c.
References fc_computeTreeDescendantsAncestors(), fc_exitIfError, spanning_tree_t::nodes, spanning_tree_node_t::num_descendants, and spanning_tree_t::numNodes.
Referenced by whittleSkeleton().
{
  int i,j;
  int new_nodes;
  FC_ReturnCode rc;
  spanning_tree_t *t;
  //Figure out how many nodes fit in here
  for(i=0, new_nodes=0; i<ti->numNodes; i++)
    if(ti->nodes[i].num_descendants >= min) new_nodes++;
  t = malloc(sizeof(spanning_tree_t));
  memcpy(t, ti, sizeof(spanning_tree_t));
  t->numNodes = new_nodes;
  t->nodes = malloc(new_nodes * sizeof(spanning_tree_node_t));
  //Copy the nodes that match
  for(i=0,j=0; i<ti->numNodes; i++){
    if(ti->nodes[i].num_descendants >= min){
      memcpy(&t->nodes[j], &ti->nodes[i], sizeof(spanning_tree_node_t));
      j++;
    }
  }
  //Recompute the relatives
  rc = fc_computeTreeDescendantsAncestors(t);
  fc_exitIfError(rc);
  *to = t;
}
void whittleSkeletonBySegmentLengths (spanning_tree_t * ti, spanning_tree_t ** to)
Definition at line 1198 of file lib_skeleton.c.
References findNetDistanceChangeWhenRemovingNode(), spanning_tree_node_t::id_stop, spanning_tree_t::nodes, spanning_tree_t::numNodes, and replicateSpanningTreeWithMask().
Referenced by whittleSkeleton().
{
  int i;
  int    smallest_idx;
  double smallest_change;
  double tmp;
  char *mask;
#if (!ENABLE_OPENMP) //Serial code
  smallest_idx    = -1;
  smallest_change = DBL_MAX;
  for(i=0; i<ti->numNodes; i++){
    //printf("Trying to remove node %d of %d\n", i, ti->numNodes);
    //tmp1 = findNetDistanceChangeWhenRemovingNode(ti,ti->nodes[i].id_stop,1);
    tmp = findNetDistanceChangeWhenRemovingNode(ti,ti->nodes[i].id_stop,0);
    if(tmp<smallest_change) {
      smallest_change = tmp;
      smallest_idx    = i;
    }
  }
#else //OpenMP code
  {
    double *tmp_smallest_change;
    int    *tmp_smallest_idx;
    int id,nthreads;
    const int chunk = 32;
    #pragma omp parallel  private(i,id, tmp)
    {
      id = omp_get_thread_num();
      //Root: allocate space and initialize it
      if ( id == 0 ) {
     nthreads = omp_get_num_threads();
     tmp_smallest_change = (double *)malloc(nthreads * sizeof(double));
     tmp_smallest_idx    =    (int *)malloc(nthreads * sizeof(int));
     for(i=0; i<nthreads; i++)
       tmp_smallest_change[i] = DBL_MAX;
      }
      #pragma omp barrier
      #pragma omp for schedule(dynamic, chunk)
      for(i=0; i<ti->numNodes; i++){
     tmp = findNetDistanceChangeWhenRemovingNode(ti,ti->nodes[i].id_stop,0);
     if(tmp < tmp_smallest_change[id]){
       tmp_smallest_change[id] = tmp;
       tmp_smallest_idx[id]    = i;
     }
      }
      #pragma omp barrier
      //Combine all the results
      if(id==0){
     for(i=0, smallest_change = DBL_MAX; i<nthreads; i++)
       if(tmp_smallest_change[i]<smallest_change){
         smallest_change = tmp_smallest_change[i];
         smallest_idx    = tmp_smallest_idx[i];
       }
     free(tmp_smallest_change);
     free(tmp_smallest_idx);
      }
    }//Done with threads
  }
#endif
  //Create a mask with all values tagged except delete point
  mask = (char *)malloc(ti->numNodes*sizeof(char));
  memset(mask, 1, ti->numNodes*sizeof(char));
  mask[smallest_idx] = 0;
  replicateSpanningTreeWithMask(ti, mask, to);
  free(mask);
}
void whittleSkeletonOctants (spanning_tree_t * ti, int per_oct, spanning_tree_t ** to)
Definition at line 1427 of file lib_skeleton.c.
References spanning_tree_t::dim, spanning_tree_t::elementCenters, fc_exitIfError, spanning_tree_t::nodes, spanning_tree_t::numNodes, replicateSpanningTreeWithMask(), spanning_tree_t::root, and treeTagNodesAncestorsMask().
Referenced by whittleSkeleton().
{
  int i,j,k;
  int    *best_ids;
  double *best_dist;
  int     oid;
  int     dim;
  spanning_tree_node_t *nodes;
  FC_Coords cntr;
  double *cntrs;
  char   *hits;
  spanning_tree_t *t2;
  FC_ReturnCode rc;
  //shorthand
  nodes = ti->nodes;
  cntrs = ti->elementCenters;
  dim   = ti->dim;
  memcpy(&cntr, &cntrs[ti->root*dim], dim*sizeof(double));
  best_ids  = (int *)    malloc(per_oct*8*sizeof(int));
  best_dist = (double *) malloc(per_oct*8*sizeof(double));
  for(i=0;i<per_oct*8; i++){
    best_ids[i]=-1;
    best_dist[i]=DBL_MAX;
  }
  //Take a look at everyone and find the best matches in each quadrant
  for(i=0;i<ti->numNodes;i++){
    //Uncomment if you only want endpoints
    //if(!ti->nodes[i].num_descendants) continue;
    //Figure out what quadrant this is in
    for(oid=0, j=0; j<dim; j++){
      if(cntr[j] < cntrs[ (nodes[i].id_stop*dim) + j ])
     oid |= (1<<j);
    }
    assert((oid>=0) && (oid<8));
    //See if the distance is better than best known
    for(j=0;j<per_oct;j++){
      if( (best_ids[  (oid*per_oct) + j] < 0)                    ||
       (best_dist[ (oid*per_oct) + j] < nodes[i].dist_center)   ){
     //Shift worse answers right
     for(k=per_oct-1; k>j; k--){
       best_ids[ (oid*per_oct) + k] = best_ids[ (oid*per_oct) + k-1];
       best_dist[(oid*per_oct) + k] = best_dist[(oid*per_oct) + k-1];
     }
     //Insert in spot
     best_ids[ (oid*per_oct) + j] = i;
     best_dist[(oid*per_oct) + j] = nodes[i].dist_center;
      }
    }
  }
  //Tag all the winners, and all the winners' ancestors
  hits = (char *)calloc(ti->numNodes, sizeof(char));
  for(i=0; i<8*per_oct; i++){
    if(best_ids[i]<0) continue; //ran out of hits in this quadrant
    rc = treeTagNodesAncestorsMask(ti, nodes[best_ids[i]].id_stop, hits);
    fc_exitIfError(rc);
  }
  //Use the mask to create a new tree
  rc = replicateSpanningTreeWithMask(ti, hits, &t2);
  fc_exitIfError(rc);
  free(hits);
  //Copy out
  *to = t2;
  ////Tag each ancestor that belongs to this guy
  //k=best_ids[i];
  //search_node = nodes[k].id_stop; //First time we fake
  //do{
  //  while(nodes[k].id_stop != search_node) k--; //look for next ancestor
  //  hits[k]=1;
  //  search_node = nodes[k].id_start; //get parent
  //}while(search_node!=ti->root);
}
Variable Documentation
int _skeleton_dbg
Definition at line 53 of file lib_skeleton.c.
Referenced by checkArgs(), and main().