FCLib: tools/sierradump.c File Reference
tools/sierradump.c File Reference
Detailed Description
Read a sierra input file and report it's content to standard output.
Source
/usr/local/Repositories/fcdmf/fclib/tools/sierradump.c,v
Revision
1.17
Date
2006/08/30 19:20:04
Modifications:
2003-JUN-24 W Koegler Created to test new Sierra parser
Definition in file sierradump.c.
#include <stdio.h>
#include <stdlib.h>
#include "base.h"
#include "sierra.h"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 57 of file sierradump.c.
References fc_freeSierraInfo(), fc_getReturnCodeText(), fc_parseSierraInputFile(), fc_printSierraInfo(), and FC_SUCCESS.
{
  FC_ReturnCode rc; // return code
  char* filename;
  FC_SierraInfo* sierra;
  // Process arguments
  if (argc != 2) {
    printf("usage: sierradump <sierra_input_file>\n");
    fflush(NULL);
    exit(-1);
  }
  filename = argv[1];
  // do it
  rc = fc_parseSierraInputFile(filename, &sierra);
  if (rc != FC_SUCCESS) {
    printf("fc_parseSierraInputFile returned error: '%s'\n",
           fc_getReturnCodeText(rc));
    fflush(NULL);
    exit(rc);
  }
  rc = fc_printSierraInfo(sierra);
  if (rc != FC_SUCCESS) {
    printf("fc_printSierraInfo returned error: '%s'\n",
           fc_getReturnCodeText(rc));
    fflush(NULL);
    exit(rc);
  }
  // cleanup
  fc_freeSierraInfo(sierra);
  exit(0);
}