FCLib: tools/skeleton/whittle_tree.c File Reference
tools/skeleton/whittle_tree.c File Reference
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <assert.h>
#include <fc.h>
#include "lib_skeleton.h"
Functions
void dumpHelp (void)
static FC_ReturnCode getMeshByNameOrDie (FC_Dataset ds, char *mesh_name, FC_Mesh *m)
int main (int argc, char **argv)
Function Documentation
void dumpHelp (void)
Definition at line 72 of file whittle_tree.c.
References getNextWhittleAlgorithmDescription().
               {
  int i, rc;
  char *name, *sname, *description;
  int id;
  printf("Whittle Tree: a tool for reducing a spanning tree to a smaller representation\n"
      "  This tool takes an input file that holds a spanning tree and then whittles\n"
         "  the structure to a smaller form in order to provide a more convenient way\n"
         "  to examine and compare one or more meshes.\n"
      "\n"
      "Usage: whittle_tree [options] <algorithm>\n"
      "  [-i input file  ]                input file (default=result_tree.e)\n"
      "  [-o output file ]                output file (default=result_tree_whittled.e)\n"
      "  [-m mesh_name[step]]             can be appended with displacement step, like block_1[2])\n"
      "  [-d displacement_variable_name ] (does combinding on _x,_y,_z and defaults to 'displacement')\n"
      "  [-p 0-99 ]                       desired percentage of nodes to survive\n"
      "   -v                              display warning messages\n"
      "   -V                              display log messages\n"
      "   -S                              Silent operation: don't print info\n"
         "   -h                              this help screen\n"
      "   -w algorithm                    select whittle algorithm\n");
  for(i=0; (rc=getNextWhittleAlgorithmDescription(i,&name, &sname, &id, &description)); i++){
    printf("        %s : %23s - %s\n", sname, name, description);
  }
  exit(0);
}
static FC_ReturnCode getMeshByNameOrDie (FC_Dataset ds, char * mesh_name, FC_Mesh * m) [static]
Definition at line 54 of file whittle_tree.c.
References emsg, fc_exitIfError, fc_getMeshByName(), FC_SUCCESS, and FREE.
{
  FC_ReturnCode rc;
  FC_Mesh *meshes;
  int numMeshes;
  rc = fc_getMeshByName(ds, mesh_name, &numMeshes, &meshes);
  fc_exitIfError(rc);
  if(numMeshes!=1)
    emsg("Found %d meshes named %s", numMeshes, mesh_name);
  *m = meshes[0];
  FREE(meshes);
  return FC_SUCCESS;
}
int main (int argc, char ** argv)
Definition at line 103 of file whittle_tree.c.
References _skeleton_dbg, convertStringToWhittleAlg(), ds, dumpHelp(), fc_exitIfError, fc_initLibrary(), fc_loadDataset(), FC_LOG_MESSAGES, fc_saveSkeleton(), fc_setLibraryVerbosity(), fc_unpackSkeletonFromMesh(), FC_WARNING_MESSAGES, getMeshByNameOrDie(), getWhittleAlgorithmName(), info, verbose_level, and whittleSkeleton().
{
  FC_ReturnCode rc;
  FC_VerbosityLevel verbose_level = FC_WARNING_MESSAGES;
  FC_Dataset ds;
  FC_Mesh m;
  int ich;
  int percent = 75;
  spanning_tree_t *tree1, *tree2;
  char *file_name_i = "result_tree.e";
  char *file_name_o = "result_tree_whittled.e";
  char *mesh_name   = "skel_mesh";
  char *disp_name   = "displacement";
  int whittle_type=0;
  double remaining_fraction;
  _skeleton_dbg=1; //Default to printing info
  if(argc==1) dumpHelp();
  while( (ich = getopt(argc, argv, "o:i:m:d:p:w:SvVhH")) != EOF){
    switch(ich){
    case 'i':  file_name_i   = strdup(optarg); break;
    case 'o':  file_name_o   = strdup(optarg); break;
    case 'm':  mesh_name     = strdup(optarg); break;
    case 'd':  disp_name     = strdup(optarg); break;
    case 'p':  percent       = atoi(optarg);   break;
    case 'w':  whittle_type  = convertStringToWhittleAlg(optarg); break;
    case 'S':  _skeleton_dbg = 0;                   break;
    case 'v':  verbose_level = FC_WARNING_MESSAGES; break;
    case 'V':  verbose_level = FC_LOG_MESSAGES;     break;
    case 'h':
    case 'H':
    default:
      dumpHelp(); break;
    }
  }
  if(optind<argc)
    file_name_i = strdup(argv[optind++]);
  //Pass back info to user
  info("whittle_tree is running with args\n"
       "\tInput File   = '%s'\n"
       "\tOutput File  = '%s'\n"
       "\tMesh Name    = '%s'\n"
       "\tDisplacement = '%s'\n"
       "\tAlgorithm    = '%s'\n"
       "\tPercent      =  %d%%'",
       file_name_i,
       file_name_o,
       mesh_name,
       disp_name,
       getWhittleAlgorithmName(whittle_type),
       percent);
  //Setup
  rc = fc_setLibraryVerbosity(verbose_level);           fc_exitIfError(rc);
  rc = fc_initLibrary();                                fc_exitIfError(rc);
  //Load the first mesh
  rc = fc_loadDataset(file_name_i, &ds);                fc_exitIfError(rc);
  rc = getMeshByNameOrDie(ds, mesh_name, &m);           fc_exitIfError(rc);
  //Get the mesh
  fc_unpackSkeletonFromMesh(m, &tree1);
  //Send off to the whittle routine
  remaining_fraction = ((double)percent)/100.0;
  rc = whittleSkeleton(tree1, whittle_type,
                 remaining_fraction, &tree2);     fc_exitIfError(rc);
  //Save it out
  rc = fc_saveSkeleton(*tree2, disp_name, file_name_o); fc_exitIfError(rc);
  printf("Done");
  return 0;
}